- pages.pl/linux/networkctl.md
- pages/linux/networkctl.md
> networkctl: add page and Polish translation

- pages/common/nix-build.md
- pages/common/nix-classic.md
- pages/common/nix-shell.md
- pages/common/nix-store.md
- pages/common/nix.md
- pages/common/nix3-build.md
- pages/common/nix3-develop.md
- pages/common/nix3-edit.md
- pages/common/nix3-flake.md
- pages/common/nix3-profile.md
- pages/common/nix3-registry.md
- pages/common/nix3-repl.md
- pages/common/nix3-run.md
- pages/common/nix3-search.md
- pages/common/nix3-shell.md
- pages/common/nix3-store.md
- pages/common/nix3-why-depends.md
Updates the documentation on the new unstable nix command & subcommands,
and adds a separate page for the Classic nix commands.
> Nix: update and add documentation for nix subcommands

- pages/common/md5sum.md
I updated the `stdin` example to be like in the [b2sum page](https://github.com/tldr-pages/tldr/blob/main/pages/common/b2sum.md?plain=1#L16).
This also affects translations ([Tamil](https://github.com/tldr-pages/tldr/blob/main/pages.ta/common/md5sum.md?plain=1#L16) and [Italian](https://github.com/tldr-pages/tldr/blob/main/pages.it/common/md5sum.md?plain=1#L20)), but I don't know the languages, so someone else has to fix those.
There's also [Chinese](https://github.com/tldr-pages/tldr/blob/main/pages.zh/common/md5sum.md?plain=1), but it hasn't been updated in a while and this example doesn't exist there.
Closes #9910.
> md5sum: fix typo

- pages.pl/linux/bootctl.md
- pages/linux/bootctl.md
I removed unnecessary `sudo`s from commands and moved `bootctl` to `linux`, since it's a part of systemd which runs only on linux.
> bootctl: move from common to linux, update page, add Polish translation

- pages.fr/common/2to3.md
- pages.zh/common/androguard.md
- pages.zh/common/gunicorn.md
- pages/common/chroma.md
- pages/common/gitlint.md
- pages/common/meson.md
- pages/common/pipx.md
- pages/common/pystun3.md
- pages/common/tox.md
```sh
grep -R python pages* | grep -vE '`|#|<' | tr ':' ' '
```
> *: properly capitalize “Python”

- pages/linux/nala.md
This page mentions using sudo for searching where no root permissions are needed, but does not mention sudo for commands that need root permission.
This commit fixes the this by adding sudo to the commands that need root. Alternatively, sudo could be removed from all commands as users might also use another way to get privileges than sudo.
> nala: fix usage of sudo

- pages/common/gnmic-get.md
- pages/common/silicon.md
> gnmic-get, silicon: fix typos

- pages/common/tsort.md
The current example doesn't show what path/to/file should be like (or provide a concrete example)
- [] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- []  The page description(s) have links to documentation or a homepage.
> tsort: add example with a string

- pages/common/xzless.md
- **Version of the command being documented (if known):** XZ Utils - 5.4.2
- **Issue:** https://github.com/tldr-pages/tldr/issues/8859
> xzless: add examples

- pages/linux/systemd-cat.md
> systemd-cat: add page

- pages/common/[.md
- pages/common/[[.md
---
The wording before gives the impression we're expecting to see `0` or `1` get logged to the terminal. But it exits with the respective status code, so it should state this clearly.
Wording borrowed from the help page for the command.
```
seth@seth-pc-tux:~$ help [[
[[ ... ]]: [[ expression ]]
Execute conditional command.
Returns a status of 0 or 1 depending on the evaluation of the conditional
expression EXPRESSION.  Expressions are composed of the same primaries used
by the `test' builtin, and may be combined using the following operators:
```
```
seth@seth-pc-tux:~$ [[ 1 == 1 ]]
seth@seth-pc-tux:~$ [[ 1 == 2 ]]
seth@seth-pc-tux:~$ [[ 1 == 1 ]]; echo $?
0
seth@seth-pc-tux:~$ [[ 1 == 2 ]]; echo $?
1
```
> Observe how `[[` has …
> [, [[: reword description

- pages.nl/android/am.md
- pages.nl/common/[[.md
---
I didn't translate "string" because on technical topics the term "string" is acceptable, for example on Wikipedia pages.
> Strings zijn reeksen van karakters. Er zijn verschillende manieren om strings te representeren.
>
> - https://nl.wikipedia.org/wiki/Datatype#Strings
> am, [[: add Dutch translation

- pages/common/kinit.md
Add in an initial page for the kinit kerberos ticketing utility.
- **Version of the command being documented (if known): 1.20.1-8**
> kinit: add page

- pages/common/clifm.md
- pages/common/cs-complete-dep.md
- pages/common/ern.md
- pages/common/gh-secret-set.md
- pages/common/gnatprep.md
- pages/common/gsutil.md
- pages/common/lli.md
- pages/common/neomutt.md
- pages/common/railway.md
- pages/common/tailscale-up.md
- pages/common/tcc.md
- pages/common/tcsh.md
- pages/common/tts.md
- pages/common/u3d.md
- pages/common/vifm.md
- pages/common/xmlstarlet.md
- pages/common/yolo.md
- pages/linux/getopt.md
- pages/linux/goobook.md
- pages/linux/mpicc.md
- pages/linux/qm-showcmd.md
- pages/linux/toolbox.md
- pages/linux/ttyplot.md
- pages/linux/virt-xml.md
- pages/linux/zathura.md
- pages/windows/diskpart.md
- pages/windows/vcvarsall.md
```sh
$ grep -R command-line pages | wc -l
249
$ grep -R 'command line' pages | wc -l
28
$ grep -R commandline pages | grep -v 'More info' | wc -l
2
```
```sh
fd -t f . pages | xe sed -i '' 's/command line/command-line/g'
```
> *: standardize "command-line"

- pages/linux/xfreerdp.md
Added command to map a shared drive, enables upload or download of files between local and remote hosts.
> xfreerdp: add /drive example

- pages/common/mitmproxy.md
Hi
To mitmproxy, add the variable "SSLKEYLOGFILE". The explain is here : https://docs.mitmproxy.org/stable/howto-wireshark-tls/
> mitmproxy : add the variable "SSLKEYLOGFILE"

- pages/common/clido.md
> clido: add page

- pages/common/gitwatch.md
- I would like feedback on this. [gitwatch](https://github.com/gitwatch/gitwatch) is supported on osx and linux. Should the page therefore go in `common`, or should this PR add the gitwatch page only to `linux` and `osx` platform directories?
> gitwatch: add page

- pages/linux/i3-scrot.md
> i3-scrot: fix select-to-clipboard parameter typo

- pages/common/zellij.md
fix typo in detach command, it's O not N.
> zellij: fix typo

- pages.fr/linux/pacman.md
pacman -F is far more useful than pacman -Ss as it allows you to query a package name from a command name. It's very useful when you are locking for dependencies. It's the pacman equivalent of the apt-file command.
> pacman: update French translation

- pages/common/eol.md
- [⌛ Manage EoLs like a boss with endoflife.date 🛑 ](https://dev.to/optnc/manage-eols-like-a-boss-with-endoflifedate-2ikf)
> eol: add page

- pages.de/common/ssh-keygen.md
- pages.fr/common/ssh-keygen.md
- pages/common/ssh-keygen.md
Two changes:
1. The number of rounds in the ED25519 example has been changed to 32
- Considering the default value of 16 is already considered "reasonable"<sup>[\[1\]](https://flak.tedunangst.com/post/new-openssh-key-format-and-bcrypt-pbkdf)</sup> safety-wise, there's really no good reason in most cases to go as high as 100. Using such a high value causes noticeably longer login times, especially for resource-constrained systems. Thus I think 32 is a more reasonable number to use as an example.
3. The RSA example now matches description.
---
> ssh-keygen: small improvement and fix

- pages/osx/terminal-notifier.md
- **Version of the command being documented (if known): [2.0.0 the reboot](https://github.com/julienXX/terminal-notifier/releases/tag/2.0.0)**
Thank you for the great tool! Examples are inspired from the README page of this command, but simplified to go straight to the point.
> terminal-notifier: add page

- pages/common/ruby.md
- **Version of the command being documented (if known): Every ruby that is not EOL (3.0 to 3.2)**
> ruby: add http server example

- pages/common/age.md
"Input file must be specified after all flags" as of age v1.1.1
- v1.1.1
> age: fix argument ordering

- pages.es/common/git-cherry-pick.md
- pages.fr/common/git-cherry-pick.md
- pages.it/common/git-cherry-pick.md
- pages.tr/common/git-cherry-pick.md
- pages/common/git-cherry-pick.md
- **Version of the command being documented (if known):** 2.41.0
> git-cherry-pick: spelled-out version of `-n`

- pages.de/linux/archlinux-java.md
- pages.zh/linux/archlinux-java.md
- pages/linux/archlinux-java.md
---
https://github.com/michaellass/archlinux-java-run documents an entirely different program.
> archlinux-java: fix documentation link, update page

- pages/windows/w32tm.md
- **Version of the command being documented (if known):** versions implicitly follow Windows OS version, but these commands should work in any windows from WS2012 up until now
> w32tm: add page

- pages/common/read.md
- pages/linux/read.md
Removed all non-POSIX compliant options on the common platform version of `read`.
N/A
> read: update page

- pages/common/macchina.md
- **Version of the command being documented (if known):** 6.1.8
Adding page for [macchina](https://github.com/Macchina-CLI/macchina) which is a tool similar to `neofetch` for displaying system info.
> macchina: add page

- pages.nl/common/aircrack-ng.md
- pages.nl/common/airdecap-ng.md
- pages.nl/common/aireplay-ng.md
> aircrack-ng, airdecap-ng, aireplay-ng: add Dutch translation

- pages.de/common/bgpgrep.md
- pages.de/common/peerindex.md
- pages/common/bgpgrep.md
- pages/common/peerindex.md
Since gitea.it no longer allows registrations, neither issues nor PRs can be created. Therefore the main repo was moved from to Codeberg.
> bgpgrep, peerindex: update links

- pages/common/gallery-dl.md
> gallery-dl: add --cookies-from-browser example and fix typo

- pages/linux/farge.md
- **Version of the command being documented (if known):** 1.0.9
Add page for the [farge](https://github.com/sdushantha/farge) tool, which is used for clicking on a pixel on the screen and getting it's colour value. It's similar to [xcolor](https://github.com/Soft/xcolor) if you have used that before.
This one was a bit tricky with the descriptions, as for example, every command first enters you into an interactive mode to select the pixel, and then every command also copies the output value to the clipboard so I was unsure whether to include that every time or what should be done in that scenario. I opted to talk about the clipboard, as that is not as obvious as having to enter interactive mode to select a pixel, and is not mentioned in the `--help` output. Let me know if there is a …
> farge: add page

- pages/windows/netsh-interface-portproxy.md
- pages/windows/netsh.md
> netsh-interface-portproxy: add page

- pages/windows/slmgr.md
- pages/windows/slmgr.vbs.md
**Version of the command being documented (if known):** Windows 10 (also applies to Windows 7 and up)
The official program name for this is `slmgr.vbs`. However, users might be bothered after finding out they need to use `tldr slmgr.vbs` instead of `tldr slmgr` to view this documentation. This is why I decided to set the otherwise, where `slmgr.vbs` is an alias of `slmgr`. This will also be useful for documenting other Windows-specific `.vbs` scripts such as [`ospp.vbs`](https://docs.microsoft.com/en-us/deployoffice/vlactivation/tools-to-manage-volume-activation-of-office) as long as the unprefixed command is still acceptable for use in the Command Prompt.
> slmgr, slmgr.vbs: add page

- pages/common/xz.md
- pages/common/xzcmp.md
- pages/common/xzdiff.md
- pages/common/xzgrep.md
- pages/common/xzless.md
Explanations of less obvious changes:
Change the documentation link (the old one pointed to the specification of the `xz` format, not the command).
Remove the last example (it is copied directly from the `diff` page, and does not apply to `xzdiff` since it will not decompress files in directories recursively).
Replace `path/to/archive` with `path/to/file` since the file cannot be an archive, it has to be a single compressed file.
> xz*: update pages

- pages/common/docker-images.md
From: https://stackoverflow.com/a/61091528/520275
> docker-images: Adding command to sort images by size

- pages/linux/lsusb.md
Hello!
I've edited the command for viewing details for a single device.
The reason for this is that the `-D` flag which was earlier used, doesn't explicitly say that it is looking for a path to a device, which was confusing. And unless you are doing something very specific with usb devices existing outside `/dev/bus/usb`, just specifying bus and device number is easier than writing out `-D /dev/bus/usb/{{bus}}/{{devnum}}`
> lsusb: edit command for fetching details of single device

- pages/linux/locate.md
Put arg with  `*` in singe quotes to prevent expanding in non-empty directories.
> locate: wrap glob with quotes

- pages/common/nc.md
- Unified destination naming - it was unclear why it is hostname in one place vs ip_address in another.
- When ports are specified in listening mode (-l) -p parameter is mandatory, nc would not infer it as in the client mode.
- -k switch is not present in netcat
- More useful examples with file sending and shell access
> nc: edit page

- pages.fr/common/rsync.md
- pages.id/common/rsync.md
- pages.pl/common/rsync.md
- pages.zh/common/rsync.md
- pages/common/rsync.md
> rsync: update page, link to the official documentation instead of manned.org

- pages.pt_BR/linux/btrfs-version.md
Fix end-of line punctuation in two command descriptions from `.` to `:`. Not sure how this passed our tests in #22 —I mean, #10110 :smile:. Maybe we need to update them? :thinking:
> btrfs-version: fix syntax

- pages/osx/httpie.md
I've used the same file from pages/linux/httpie.md since the functionality is the same.
> httpie: add osx page

- pages/common/dhcpig.md
Add the dhcpig tool for IP resource exhaustion.
> dhcpig: add page

- pages/common/duckdb.md
- **Version of the command being documented (if known):** 0.8.1
> duckdb: add page

- scripts/build.sh
- scripts/deploy.sh
Updates build & deploy scripts to include steps which zip individual language directories.
Simple approach that adds another step to the build process that would zip up **_all_** lang directories on push.
Discussion at: https://matrix.to/#/!zXiOpjSkFTvtMpsenJ:gitter.im/$-lJoY5o2uP9LyeYJ7wi2qS9yH1ItvZP1aJLodTzhm9w?via=matrix.org
Would close: #10545
> feature support: provide translation archives

- pages/common/jf.md
```
> jf --version
jf version 2.41.0
```
> jf: add page for JFrog CLI

- pages/linux/restorecon.md
- pages/linux/semanage-fcontext.md
- **Version of the command being documented (if known):** `policycoreutils-3.5`
Closes #7479. Fine, I'll do it myself 🙃.
> semanage-fcontext, restorecon: add page

- pages/common/ffprobe.md
command does not work. show streams shows information corresponding with the description
> ffprobe: fix invalid command

- pages/common/watchexec.md
- **Version of the command being documented (if known):** 1.22.3
In the most recent watchexec version (1.22.3) to the date of this commit it is necessary to use the "--stop-signal" flag instead of "--signal". Otherwise an error message would show up telling the user that "--signal" and "--restart" cannot be used in combination
<details>
<summary>Attached is a screenshot showing the issue.</summary>
</details>
> watchexec: fix --restart example

- pages/common/procs.md
> procs: add `--tree` example

- pages/common/aws-cloudwatch.md
> aws-cloudwatch: add page

- pages/common/aws-cloud9.md
> aws-cloud9: add page

- pages.fr/common/docker-cp.md
**Notes**
In the previous version, 2 `}` were missing.
> docker-cp: add missing placeholders

- pages/linux/mktemp.md
- **Version of the command being documented (if known):** GNU coreutils 9.3
> mktemp(linux): improve examples

- .github/workflows/ci.yml
- .github/workflows/codespell.yml
This PR bumps the `actions/checkout` version from `v3` (Node 16) to `v4` (Node 20) as Node 16 reaches eol on September 11.
> CI: bump actions/checkout to v4

- pages/common/htop.md
Adds htop -d for delayed updates
> htop: add `--delay` example

- pages/linux/iptables.md
as line number is required to delete a rule (as seen in the examples for `iptables -D`), it is useful to see the numbers in the list command so adding `--line-numbers` in the list command example
> iptables: update page

- .github/codespell-ignore
- .github/workflows/codespell.yml
Superseeds #10704
This change would make the CI run only on English pages by directly passing the path to Codespell to prevent false detections like https://github.com/tldr-pages/tldr/pull/10702/files for other languages, There still would be annotations made for other pages not in PR similar to now, but it won't prevent us from merging the PR as we have the only_warn parameter set to 1. We can alternatively add those entries to codespell-ignore file.
Edit. Bonus It will also reduce the CI action run time of the codespell action.
> CI/codespell: remove changed-files action, use point release of action

- pages/common/rustup-help.md
- pages/common/rustup-install.md
- pages/common/rustup-man.md
- pages/common/rustup-run.md
- pages/common/rustup-which.md
> rustup-{install,run,which,help,man}: add page

- pages/linux/resolvectl.md
Getting the DNS statistics and clearing the DNS cache are some of the most common operations with resolvectl, hence it would make sense to have them in the tldr page.
I removed `resolvectl openpgp` from the tldr page, as it's rarely needed, and i needed to remove a command to go under the 8 example limit.
> resolvectl: add cache flushing and statistics, remove openpgp

- pages/osx/caffeinate.md
> caffeinate: add `-w` flag example

- pages/linux/pdftohtml.md
- **Version of the command being documented (if known):** 23.02.0
> pdftohtml: add page

- MAINTAINERS.md
Closes #10738
Generally, we would suggest the maintainer create a PR (with a few exceptions) to add themselves to `MAINTAINERS.md`. I created this PR as a part of the process of cleaning up the state issues (and labelling good first issues) as we prepare for Hacktoberfest next week.
> MAINTAINERS: add @kant as collaborator

- pages/common/todo.sh.md
Document https://github.com/todotxt/todo.txt-cli, version 2.12.0
- **Version of the command being documented (if known): 2.12**
> todo.sh: add page

- pages/linux/hwinfo.md
- **Version of the command being documented (if known):** 23.2
> hwinfo: add page

- contributing-guides/translation-templates/subcommand-mention.md
- pages.ko/common/aws-batch.md
- pages.ko/common/aws-cloud9.md
- pages.ko/common/aws.md
> aws: update Korean translation; aws-{batch, cloud9},subcommand-mention: add Korean translation

- .gitignore
Mind if we ignore `venv` everywhere, so it doesn't matter where the contributor chooses to create their virtual environment? I prefer to keep it in the workspace root. ^-^'
> chore: ignore venv recursively

- pages/common/ifs.md
Creating ifs.md file for Internal Field Separator Usage in bash/shell
> ifs: add page

- pages/common/mktemp.md
- pages/linux/mktemp.md
- pages/osx/mktemp.md
As promised in https://github.com/tldr-pages/tldr/pull/10651#issuecomment-1703191336
There are many inconsistencies between the different platforms, but I checked everything multiple times against docs and implementations and this seems to be correct
Documented versions:
- `common`: OpenBSD-current
- `linux`: GNU coreutils 9.4
- `osx`: macOS 12-14
> mktemp: fix `common` and standardize between variants

- pages/common/git-ls-tree.md
- pages/common/tree.md
I'm not sure if it's allowed (since this command also uses `git` )
But it's pretty handy to print the git repo files tree, and also shows that you can pipe a list of files to the `tree` command.
> git ls-tree: print the filenames of the current branch head in a tree structure

- pages.zh_TW/common/latex.md
- pages.zh_TW/windows/choco.md
"文檔" is used in zh_CN, for zh_TW, that is "文件".
> choco, latex: fix wrong term translation in zh_TW

- pages/common/gh-repo.md
The flags changed around listing source repositories. This change reflects that.
- **Version of the command being documented (if known):** `gh version 2.35.0 (2023-09-19)`
> gh-repo: update command

- pages/common/rustdoc.md
- **Version of the command being documented (if known):** rustdoc 1.72.0
> rustdoc: add page

- pages/common/open.fish.md
- pages/common/open.md
- **Version of the command being documented (if known):**  fish, version 3.6.1
This PR adds a collision page for `open`, which may also be understood as a `fish`-specific command.
> common/open, open.fish: add page

- contributing-guides/maintainers-guide.md
Continuing #10755
- Update/fix wording in specific sections.
- Fix all-contributors link from https://github.com/kentcdodds/all-contributors to the organization https://github.com/all-contributors/all-contributors.
- Remove mentions of Stale bot (as it has been removed) instead set 1 month as the period of the author's inactivity before the maintainer can fully take over the PR.
- The main branch is protected and doesn't allow direct push/force push so the section has been reworded to highlight it
- Add information about labelling `hacktoberfest-accepted` label at the end of October for applicable PRs.
- Add a new **Transparency** section guiding maintainers on how to document requests/mail sent on behalf of the tldr-pages project.
> MAINTAINERS-GUIDE: update page, add new Transparency section

- pages/common/npm.md
This existing example already explains how to install a specific version:
> - Download a specific version of a package and add it to the list of dependencies in `package.json`:
> 
>  `npm install {{module_name}}@{{version}}`
Let's be explicit about other examples that install the `latest` version! 🤓
> npm: describe implicit `latest` version

- pages/common/npm.md
Favor `package` over `module` for clarity and consistency. 😇 
As I understand the documentation, `module` is more specific: https://docs.npmjs.com/about-packages-and-modules
Note that the `package` term is used in the CLI help:
$ npm install --help
Install a package
Usage:
npm install [<package-spec> ...]
> npm: favor 'package' over 'module'

- pages/windows/dir.md
Add "dir /B" to the cheat sheet. It is quite useful for creating file lists, playlists and the like, without having to manually mangle the output.
> windows/dir: update page

- pages/common/cargo-generate-lockfile.md
> cargo-generate-lockfile: add page

- pages/linux/systemd-escape.md
> systemd-escape: add page

- pages.id/common/adb-install.md
- pages.id/common/adb-reverse.md
- pages.id/common/adb-shell.md
- pages.id/common/adb.md
> adb, adb-install, adb-reverse, adb-shell: use imperative mood on Indonesian translation

- pages/linux/systemd-creds.md
> systemd-creds: add page

- CLIENT-SPECIFICATION.md
- COMMUNITY-ROLES.md
- CONTRIBUTING.md
- MAINTAINERS.md
- contributing-guides/git-terminal.md
- contributing-guides/maintainers-guide.md
- contributing-guides/style-guide.md
There's a [new GitHub markdown feature](https://github.com/orgs/community/discussions/16925) to emphasize information.
```markdown
> [!NOTE]
> This is a note.
> [!IMPORTANT]
> Important stuff.
> [!WARNING]
> This is a warning.
```
becomes
> [!NOTE]
> This is a note.
> [!IMPORTANT]
> Important stuff.
> [!WARNING]
> This is a warning.
I replaced all "***Note:***"s and similar things in the docs with the new syntax.
> docs: use the new `[!NOTE]` syntax

- pages/osx/xcodes-runtimes.md
- pages/osx/xcodes.md
Our style guide mandates multi-word placeholders to be written in snake case.
> xcodes, xcodes-runtimes: fix placeholder style

- pages.pl/common/eza.md
I forgot to change `exa` to `eza` after copying the page (#10867).
> eza: fix Polish translation

- pages.es/common/az-apim.md
- pages.es/common/az-group.md
- pages.es/common/az-storage.md
- pages.es/common/az-tag.md
- pages.es/common/az-upgrade.md
- pages.es/common/az.md
Added Spanish translation for the following pages:
- az-apim
- az,
- az-storage
- az-group
- az-tag
- az-upgrade
> az, az-apim, az-group, az-storage, az-tag, az-upgrade: add Spanish translation

- pages/common/git-rscp.md
---
https://github.com/tldr-pages/tldr/pull/10996#pullrequestreview-1678866133
I checked the code of `git scp`. `git-rscp` is indeed a symlink to `git-scp`, but it checks what command has been run:
https://github.com/tj/git-extras/blob/master/bin/git-scp#L172
```bash
case $(basename "$0") in
git-scp)
case $1 in
''|-h|'?'|help|--help) shift; _test_git_scp; _usage "$@";;
*)                   scp_and_stage $@;;
esac
;;
git-rscp)                  reverse_scp $@;;
esac
```
and changes behavior appropriately.
> git-rscp: update page

- pages.es/common/adb.md
- pages.es/common/awk.md
- pages.es/linux/apt-get.md
- pages.es/linux/aptitude.md
> apt-get, aptitude, adb, awk: fix typo in Spanish translation

- pages/common/kubectl-expose.md
> kubectl-expose: add page

- pages/windows/add-appxpackage.md
It's a very useful tool to add packages when you are using LTSC versions of windows 10 which do not contain the Windows App Store.
> add-appxpackage: add page

- pages/common/kubectl-create.md
> kubectl-create: add page

- pages/openbsd/pkg.md
- pages/openbsd/pkg_add.md
- pages/openbsd/pkg_delete.md
- pages/openbsd/pkg_info.md
As [mentioned here](https://github.com/tldr-pages/tldr/issues/816#issuecomment-1196781520) I'm creating what seem to be the first few tldrs for OpenBSD, that include `pkg_add`, `pkg_info` and `pkg_delete`.
Closes https://github.com/tldr-pages/tldr/issues/816
> openbsd: add directory; openbsd/pkg_{add,info,delete}: add page

- pages/common/ppmflash.md
Issue #10887 
This adds ppmflash page documentation.
> ppmflash: add page

- pages/common/cadaver.md
A command-line WebDAV client for Unix.
> cadaver: add page

- scripts/pdf/README.md
- scripts/pdf/render.py
As discussed in [the chatroom](https://matrix.to/#/!zXiOpjSkFTvtMpsenJ:gitter.im/$sS4To9n1vUpB5exkWW5Aa6wQ-ymqMhLIsl-i6FEeTwE?via=gitter.im&via=matrix.org&via=one.ems.host), this PR adds a way to generate custom PDFs for specific platforms manually. Currently, we use `python3 render.py <../../pages>` to generate PDFs (`tldr-book.pdf` by default) and there is a `-o` or `--output` flag to give a custom name to the PDF.
This PR adds a new optional flag `-p` or `--platform`, allowing pages to be generated for the specified platform alone. For example, `python3 render.py ../../pages -p android` will generate a PDF file named `tldr-book-android.pdf`.
You can pass multiple platforms as arguments, for example, `python3 render.py ../../pages -p android sunos` will generate a PDF file named …
> feat/scripts: support generating PDFs for platforms

- contributing-guides/style-guide.md
- pages/common/duckdb.md
- pages/common/perl.md
- pages/common/readonly.md
- pages/linux/compress.md
- pages/linux/uncompress.md
- pages/linux/zbarcam.md
Continuation of #10436, #10442 and probably something else I forgot about.
Fixes the remaining long versions that have gone unnoticed in reviews since the two PRs.
> style-guide: add guidelines for standard streams; fix remaining pages

- COMMUNITY-ROLES.md
The link's display text implies that it points to GOVERNANCE.md, when in fact it points to COMMUNITY-ROLES.md (which is already covered by another link previously). This PR fixes this.
> COMMUNITY-ROLES: fix link to project governance principles

- scripts/build.sh
#11205
> Seems like symlinking ZIP files are supported only in a handful of file systems
The filesystem has nothing to do with it; once you download the symlink it becomes a plain text file with the string `tldr-pages.zip` in it.
> This PR updates the command to recursively copy the ZIP's contents of `tldr-pages.zip` to `tldr-pages.en.zip`
No, it copies the zip file itself, no extracting, no recursive copying needed.
> fix/scripts: remove unnecessary `-r` from `cp`

- pages/common/vf.md
- pages/common/virtualfish.md
- **Version of the command being documented:** 2.5.5
This tool actually has a different command name to use in the terminal, i.e. `vf` not `virtualfish`. Should I need to create `vf.md` also? What is guidelines for this?
> vf: add page

- pages/common/leaftoppm.md
Issue #10887
This adds leaftoppm page documentation.
> leaftoppm: add page

- pages.pt_BR/common/aws-codeartifact.md
- pages/common/aws-codeartifact.md
- **Version of the command being documented (if known):** `aws-cli/1.29.25 Python/3.11.5 Linux/6.1.59-1-lts botocore/1.31.25`
> aws codeartifact: add page; pt_BR translation

- scripts/build.sh
- scripts/check-pr.sh
- scripts/deploy.sh
- scripts/test.sh
Since all shell scripts are run in Bash, we can use `[[` in if statements.
This allows to chain multiple conditions inside a single set of brackets.
```bash
if [ condition1 ] && [ condition2 ] && [ condition3 ]
```
can be written as
```bash
if [[ condition1 && condition2 && condition3 ]]
```
Quoting variables inside if statements is no longer needed, since Bash does not do `$IFS` splitting or glob expansion inside `[[`.
> scripts: use `[[` instead of `[`, fix literal shell globs

- pages/common/gotelemetry.md
- **Version of the command being documented (if known):** I installed latest but according to this https://pkg.go.dev/golang.org/x/telemetry/cmd/gotelemetry It would be `v0`
> gotelemetry: add page

- pages.id/osx/xcodes-runtimes.md
- Fixes the untranslated path placeholder (@Magrid0 You seem to have accidentally merged the PR #11296 before updating this)
- In some places, the runtime placeholder wasn't translated but in some places, it was but differently. I have updated it to `nama_runtime` throughout the page. (This error passed through my initial oversight too, sorry)
> xcodes-runtimes: update Indonesian translation

- pages/freebsd/pkg.md
- pages/netbsd/pkgin.md
---
This PR adds the `freebsd` and `netbsd` directories and pages for their package managers.
We definitely don't want to add a big amount of platform directories. I'd like to hear everyone's opinion on adding more BSDs. I think those are the three most popular ones (+OpenBSD), and I wouldn't add any more myself after this.
Each platform addition requires updating all the clients, so adding them all in one go would be ideal.
Discussed in #10698.
Closes #7077.
> freebsd, netbsd: add directory; pkg, pkgin: add page

- .github/ISSUE_TEMPLATE/lets-document.yml
- .github/ISSUE_TEMPLATE/page-modification-request.yml
- .github/ISSUE_TEMPLATE/page-request.yml
- .github/ISSUE_TEMPLATE/page-translation.yml
- Set some fields as required
- Change OS selection from checkboxes to dropdown, because we only need to know the directory name anyway
- Add a field for documentation
- Remove most fields from the translation template, because if a page already exists we only need to know its name
> ISSUE-TEMPLATES: add Let's document; update others

- pages/osx/mysides.md
adding the page for [mysides](https://github.com/mosen/mysides)
- **Version of the command being documented (if known): 1.0.1**
> mysides: add page

- pages/windows/get-location.md
- pages/windows/gl.md
- pages/windows/mi.md
- pages/windows/move-item.md
- pages/windows/move.md
- pages/windows/mv.md
- pages/windows/pwd.md
This PR adds `Get-Location` and `Move-Item`, as well as their aliases: `gl`, `move`, `mi`, `mv`, and `pwd`. Additionally, the `move` documentation for Command Prompt is also added.
> windows/*: add PowerShell pwd and mv equivalents

- pages/common/get-nodeinstalllocation.md
- pages/common/get-nodeversions.md
- pages/common/install-nodeversion.md
- pages/common/ps-nvm.md
- pages/common/remove-nodeversion.md
- pages/common/set-nodeinstalllocation.md
- pages/common/set-nodeversion.md
This PR adds [ps-nvm](https://github.com/aaronpowell/ps-nvm), a PowerShell utility to manage Node.js versions akin to `nvm`. It is placed in `common` (instead of `windows`—see #6621) as the authors of this tool explicitly claims the tool to support Windows, macOS, and Linux, though they still require PowerShell to use the install Node.js versions.
> common/*: add ps-nvm commands

- pages/common/cli53.md
> cli53: fix missing curly brace

- pages.de/common/tar.md
Erroneously writing a word as two separate words is a common mistake in German.
> tar: fix grammatical errors in the German translation

- .github/workflows/codespell.yml
In addition to #11430, forgot to include the platform-subfolders in the glob.
> CI/codespell: ignore subfolders

- pages/linux/swaybg.md
> swaybg: add page

- scripts/test.sh
The reason for this PR are PR's which introduce/edit English pages. The tldr-lint runs on `./pages` and on `./ pages.en`. `./pages.en` is the symlinked version of `./pages`. This PR will fix this.
Ref: https://github.com/tldr-pages/tldr/pull/11535#issuecomment-1817189589
> test: skip symlinked English folder and optimise the script

- pages/common/keepassxc-cli.md
> keepassxc-cli: replace invalid `lookup` command with `search`

- pages/linux/systemd-cryptenroll.md
- pages/linux/systemd-id128.md
> systemd-id128: fix typo; systemd-cryptenroll: update page

- pages.pt_PT/common/7zr.md
The page said "7z" when it should have said "7zr".
> 7zr: fix pt_PT translation

- pages/windows/get-command.md
- pages/windows/get-help.md
- pages/windows/get-wuapiversion.md
- pages/windows/get-wuhistory.md
- pages/windows/get-wusettings.md
- pages/windows/install-module.md
- pages/windows/pswindowsupdate.md
+ PowerShell 5.1
+ PSWindowsUpdate 2.0.0.4
This PR adds and improves the following commands:
+ **Get-Command**
+ **Get-Help:** Clarify that the command may also be used for PowerShell aliases and functions
+ **Install-Module:** Part of PowerShell package management (PowerShellGet)
+ **PSWindowsUpdate:** Setup alias page for the following commands:
- **Get-WUApiVersion:** Get the Windows Update Agent version
- **Get-WUHistory:** Get the Windows Update history
- **Get-WUSettings:** Get the current Windows Update configuration
> windows/*: add more PowerShell commands

- pages/common/aws-s3-website.md
Add an initial description of the local options for aws s3 website command.
- **Version of the command being documented (if known):** j
> aws-s3-website: add page

- pages/common/gcloud-version.md
Adding initial description of gcloud version command.
> gcloud-version: add page

- CONTRIBUTING.md
- Update Markdown syntax throughout the page to conform to Markdownlint.
- Minor fixes to line/paragraph spacing and grammatical errors.
- Add the requirement that an English page should be added before creating a translation.
- Suggest adding entries to translation templates when creating a new language.
- Add documentation on running `tldr-lint` locally and how to install it. (While this would seem redundant with the style guide [the reference here is a bit short], I think it is fine to refer to tldr-lint in both places (as a majority of contributors would go through this page in detail then the style guide, I will add it as a check to PR templates too in a PR today)
- Add documentation on how to batch suggestions and make a single commit.
- Add a suggestion for contributors to enable …
> CONTRIBUTING: update page, fix Markdown syntax

- pages.es/linux/grub-mkconfig.md
> grub-mkconfig: fix typos in Spanish translation

- pages/linux/byzanz-record.md
- **Version of the command being documented (if known):** 0.3
I did not check the first item in the list above because I am not completely sure if the `byzanz-record` command will execute properly in operating systems other than Linux. I cloned the repository of `byzanz-record` (i.e.  https://gitlab.gnome.org/Archive/byzanz) and noticed some source files read X11 and/or glib headers (e.g. https://gitlab.gnome.org/Archive/byzanz/-/blob/master/src/byzanzsession.c), which might mean that those are some or all of the dependencies. 
Also, I wanted to include the following example for recording the current window:
```shell
eval $(xdotool getwindowfocus getwindowgeometry --shell) && byzanz-record --x "${X}" --y "${Y}" --width "${WIDTH}" --height "${HEIGHT}" …
```
> byzanz-record: add page

- .github/CODEOWNERS
- .github/workflows/ci.yml
- Bump `actions/setup-python` to `v5`.
- Set the Python version to 3.12.
- Fix the CODEOWNERS glob pattern for the `.github` directory by specifying the `workflows` subdirectory.
[^1]: I have tested the changes in my fork and the action run can be found [here](https://github.com/kbdharun/tldr/actions/runs/7182439409/job/19558953916).
> chore(ci): bump `actions/setup-python` to v5, set version to 3.12; fix CODEOWNERS

- pages.de/common/docker-inspect.md
- pages.fr/common/docker-inspect.md
- pages.it/common/docker-inspect.md
- pages.pt_BR/common/docker-inspect.md
- pages.tr/common/docker-inspect.md
- pages/common/docker-inspect.md
Addressing #10125, this PR adds placeholder escaping support to the format flag in `docker-inspect` pages to display the curly braces as it is.
The rendered pages will look like this (Note: I have taken this screenshot from `tlrc` as it is the only official client which has implemented the v2.1 specification till now):
> docker-inspect: escape placeholders

- COMMUNITY-ROLES.md
Ref https://matrix.to/#/!zXiOpjSkFTvtMpsenJ:gitter.im/$P2PB65z9pBYv7KXAcTVv8p4WK_v3r1mx5cMyw5sgF2o?via=gitter.im&via=matrix.org&via=one.ems.host, this PR documents the [`.github/CODEOWNERS` file](https://github.com/tldr-pages/tldr/blob/main/.github/CODEOWNERS) in COMMUNITY-ROLES.
It is of course completely everyones' choice as to whether they are in the CODEOWNERS file or not.
> COMMUNITY-ROLES: document CODEOWNERS file

- pages.id/common/aireplay-ng.md
> aireplay-ng: fix typo in URL

- pages/linux/scrot.md
- **Version of the command being documented (if known):** 1.9
I personally use the `scrot` command with the examples I added, so I thought they might be useful to others.
One problem though, I am not sure what color names does `scrot` admit. I skimmed through [a source file](https://github.com/resurrecting-open-source-projects/scrot/blob/master/src/scrot_selection.c#L178) and guessed `scrot` accepts [X11 color names](https://en.wikipedia.org/wiki/X11_color_names). I have successfully tried the following commands:
- `scrot --select --line color="Dark Sea Green"`
- `scrot --select --line color="Dark Violet"`
- `scrot --select --line color="Goldenrod"`
> scrot: add two examples

- pages/common/kcat.md
> kcat: fix typo

- pages.nl/common/get-nodeinstalllocation.md
> get-nodeinstalllocation: fix Dutch translation

- pages.es/common/dig.md
- pages.it/common/dig.md
- pages.ja/common/dig.md
- pages.ko/common/dig.md
- pages.pt_BR/common/dig.md
- pages/common/dig.md
The tldr page on dig lists `dig example.com ANY` for "Get all types of records for a given domain name"
This is not accurate. For example,  I've included the output `dig example.com ANY`, which just returns an error. What's happening here is pretty typical -- `example.com` does not implement `ANY`, so it doesn't return any results. It returns a `NOTIMP` aka "not implemented" error code instead.
See also the blog post [Saying goodbye to ANY](https://blog.cloudflare.com/rfc8482-saying-goodbye-to-any) for some more context around this.
dig sadly doesn't really have any reliable way to get all types of records for a given domain name so I don't think it makes sense to include at all.
```
; <<>> DiG 9.18.19 <<>> +all example.com ANY
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- …
```
> dig: remove inaccurate description of ANY

- pages.fr/common/age.md
- pages.fr/common/anki.md
- pages.fr/common/aria2c.md
- pages.fr/common/arp.md
- pages.fr/common/aws-quicksight.md
- pages.fr/common/az.md
- pages.fr/common/csh.md
- pages.fr/common/docker-machine.md
- pages.fr/common/docker-system.md
- pages.fr/common/gh.md
- pages.fr/common/ssh-keygen.md
- pages.fr/linux/cp.md
- pages.fr/sunos/svcadm.md
> pages.fr: fix descriptions missing a space before the semicolon

- scripts/deploy.sh
- scripts/pdf/build-pdf.sh
I noticed the Build-step took very long. This was due to the fact that all pages-folders were build every commit, even if they didn't change. By adding the provided change in this PR, we will gather the pages-folders that were changed in the last commit and deploy those. I have tested this locally as far as I could test it locally.
This PR resolves this issue: https://github.com/tldr-pages/tldr/pull/11773#issuecomment-1862658871
> build-pdf: only build changed folders since last commit

- scripts/deploy.sh
Currently, `tldr.sha256sums` looks like this:
```
<sha256sum>    /home/runner/site/assets/tldr-pages.lang.zip
```
Clients only need the filename.
```
<sha256sum>    tldr-pages.lang.zip
```
> scripts/deploy.sh: remove redundant paths from the sumfile

- scripts/deploy.sh
https://github.com/tldr-pages/tldr/pull/11825#issuecomment-1868687824 didn't work because it did the opposite - exit when there are changes, proceed if there aren't. I forgot to add a `!`.
---
I removed some of the variables used only once, because their contents were shorter than the variable name itself.
By the way, it would be great if we had some written conventions regarding the shell scripts.
- some scripts use `$var`, some `${var}`
- some quote every variable, some don't, etc.
> scripts/deploy.sh: exit immediately if there aren't any changes

- MAINTAINERS.md
It seems that 2 users have changed their usernames, so I've updated dead links to their accounts.
Closes #11839.
> MAINTAINERS: add @acuteenvy as org owner; update dead links

- scripts/check-pr.sh
Add `<` & `>` as special case to remove everything in between. Just like `{{` & `}}`, `"` and `'`.
> check-pr: add < and > as special cases and refactor

- .github/CODEOWNERS
In #11833 I removed my name from one of the pt-BR entries in CODEOWNERS, since there's already another maintainer looking after them, and I don't currently have the bandwidth to review changes in a timely manner. I kept my name as code owner for the pt-PT entries.
However, I didn't notice that there were actually two pt-BR entries in that file, so this PR does the same change for the other one.
Btw, thank you @isaacvicente for stepping up to help the project with the pt-BR content!
> CODEOWNERS: remove waldyrious from pt_BR line

- pages/common/cupstestppd.md
Partially fixes #6597. This command is deprecated in OpenPrinting CUPS. I'm only documenting this command because in Apple CUPS it is not deprecated yet.
> cupstestppd: add page

- pages.pt_BR/common/jwt.md
- pages/common/jwt.md
> jwt: escape placeholder

- contributing-guides/git-terminal.md
This PR fixes typos and broken renderings of warnings.
> git-terminal: fix typos and warnings

- .github/CODEOWNERS
This is polluting my review requests such that I can't tell which ones have been explicitly requested of me and which ones are automatic.
Merging immediately as this only affects me.
> CODEOWNERS: Remove @sbrl from pages/linux

- pages.de/common/docker-exec.md
- pages.fr/common/docker-exec.md
- pages.it/common/docker-exec.md
- pages.tr/common/docker-exec.md
- pages/common/docker-exec.md
> docker-exec: fix typo

- pages.de/linux/lastlog.md
- pages/linux/lastlog.md
One of these examples were used in #11946 as an example to when to not use placeholders 😅
> lastlog: leave values as part of the commands

- pages/common/rlwrap.md
- **Version of the command being documented (if known):** 0.43
> rlwrap: add page

- pages/common/git-stash.md
- pages/common/hyperfine.md
Ref. #11850
Although this still will have a non-placeholder bracket it is much better than not being shown itself.
> pages/common: fix typos in placeholders

- pages.ko/common/autoconf.md
> autoconf: add Korean translation

- COMMUNITY-ROLES.md
- Fix the broken note rendering.
- Remove the merged PR check URL (`https://github.com/tldr-pages/tldr/commits?committer=<username>`) as afaik GitHub no longer offers a direct way to check it. In future, we can continue manually checking the merged PRs (for this requirement).
> [!NOTE]
> As the wording signifies it is for checking merged commits by you, not to be confused with authored/coauthored commits `https://github.com/tldr-pages/tldr/commits?author=<username>`
> COMMUNITY-ROLES: fix note, remove broken link reference

- pages/linux/kill.md
*BSD and macOS don't have any extensions to POSIX, so I didn't create a page for each one of them.
For #11827 and #9612.
> kill: split POSIX and util-linux implementations

- pages/common/umount.md
- pages/linux/umount.md
It isn't a POSIX command, it first appeared on Version 1 AT&T UNIX and has some common options accross the implementation. I've used OpenBSD docs in common because it has less options and they are supported by FreeBSD, NetBSD and macOS.
For #11827.
> umount: split common and util-linux implementations

- pages.it/common/duplicity.md
- pages/common/duplicity.md
- **Version of the command being documented (if known):** 2.1.4
When I attempted to restore a backup with the command `duplicity restore --file-to-restore <FILE> file:///<DIRECTORY>`, it returned the following output:
```
CommandLineError: Option '--file-to-restore was changed in 2.0.0.
--file-to-restore to --path-to-restore
--do-not-restore-ownership to --no-restore-ownership
Enter 'duplicity --help' for help screen.
```
Later on, I could not find the option `--use-new-style` in the man page for my version of the command. However, I did find a [similar option in the source code](https://gitlab.com/duplicity/duplicity/-/blob/dev/duplicity/cli_data.py?ref_type=heads#L831) and the [file `CHANGELOG`](https://gitlab.com/duplicity/duplicity/-/blob/31abc1bf10b5b2e18f654ffe114054c8aa6369f6/CHANGE …
> duplicity: remove bad options

- pages/common/scc.md
fix --include-ext example
- version: **3.2.0:**
> scc: remove erroneous spacings

- contributing-guides/style-guide.md
- contributing-guides/translation-templates/common-arguments.md
This PR discorages the usage of `file` in Indonesian translations in favor `berkas`, which is a [standard word](https://kbbi.kemdikbud.go.id/entri/berkas) and already used in many software translations and local software (e.g. [BlankOn](https://dev.blankonlinux.or.id/TimPengembang/Dokumentasi/Panduan/PanduanWiki/KamusBlankOn/) and [Firefox](https://addons.mozilla.org/en-US/firefox/addon/indonesian-langpack/)).
As a consequence, the `jalan/menuju/file` placeholder should be replaced with `jalan/menuju/berkas`. This will be covered in another PR after this change is formally approved.
> style-guide: use "berkas" instead of "file" in Indonesian translations

- contributing-guides/style-guide.md
Currently, manned.org only supports Alpine Linux, Arch Linux, CentOS, Debian, Fedora, FreeBSD and Ubuntu, so we can be more specific on the style guide.
> style-guide: clarify available man pages on manned.org

- pages/common/find.md
- **Version of the command being documented (if known): findutils 4.9.0**
> find: Markdown format tweaks, introduce the '+' operator for exec

- pages/common/prosodyctl.md
From the [official docs](https://prosody.im/doc/prosodyctl#process-management):
> Do not use these to start and stop Prosody unless you know what you are doing. Instead, use your distributions init system tools, e.g. systemctl.
> prosodyctl: discourage process management through prosodyctl

- pages/common/id3tag.md
The `--title` parameter is now named `--song` ([man](https://manned.org/id3tag) reference).
- **Version of the command being documented (if known):** id3lib 3.8.3
> id3tag: update --title argument

- .github/ISSUE_TEMPLATE/lets-document.yml
- .github/ISSUE_TEMPLATE/page-modification-request.yml
- .github/ISSUE_TEMPLATE/page-request.yml
The VCS link can provide some useful information and we can inspect the code when the documentation is not that good.
The arrows in the Let's Document template suggests you can already put the arrows after each row.
> ISSUE_TEMPLATES: add VCS link and add arrow for PR number for the commands list of lets-document

- .github/workflows/ci.yml
- .github/workflows/copy-release-assets.yml
- scripts/deploy.sh
This PR does not break anything; the old method of distributing assets is still there.
My proposal for fixing this issue is: we merge this PR, then announce that we are moving the assets from https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/main/assets (https://tldr.sh/assets) to https://github.com/tldr-pages/tldr/releases/latest/download (and I think we should not make redirects so that we only have one URL). After some time, we swap the website repositories as described in https://github.com/tldr-pages/tldr/issues/12048#issue-2072204810 and remove the old distribution method from `deploy.sh`.
If someone comes up with a better solution, I'll just close this PR.
Discussed in #12048.
> scripts/deploy.sh: add deployment to GitHub releases

- .github/ISSUE_TEMPLATE/lets-document.yml
- .github/ISSUE_TEMPLATE/page-modification-request.yml
- .github/ISSUE_TEMPLATE/page-request.yml
`textarea` is a big text box. `input` is smaller (one-line), which I think is more appropriate here.
> ISSUE-TEMPLATES: set the type of the VCS link to `input`

- pages.nl/osx/cut.md
- pages.nl/osx/tail.md
> cut, tail: use keith.github.io for Dutch pages

- pages/common/mesg.md
- pages/linux/mesg.md
> mesg: split util-linux and POSIX pages

- pages/freebsd/chfn.md
- pages/freebsd/chpass.md
- pages/freebsd/chsh.md
- pages/freebsd/ypchfn.md
- pages/freebsd/ypchpass.md
- pages/freebsd/ypchsh.md
- pages/linux/chsh.md
- pages/netbsd/chfn.md
- pages/netbsd/chpass.md
- pages/netbsd/chsh.md
- pages/openbsd/chfn.md
- pages/openbsd/chpass.md
- pages/openbsd/chsh.md
- pages/osx/chpass.md
- scripts/set-alias-page.py
> chsh, chpass: add pages; pages/linux/chsh: update page

- pages.ko/common/virsh.md
- pages/common/cupsaccept.md
- pages/common/cupsdisable.md
- pages/common/cupsreject.md
- pages/common/cupstestppd.md
- pages/common/flex.md
- pages/common/kosmorro.md
- pages/common/lex.md
- pages/common/look.md
- pages/common/prosodyctl.md
- pages/common/q.md
- pages/common/tidy.md
- pages/common/virsh.md
- pages/common/virt-sparsify.md
- pages/linux/file-rename.md
- pages/linux/lid.md
- pages/linux/look.md
- pages/linux/perl-rename.md
- pages/linux/prename.md
- pages/linux/quickget.md
- pages/linux/rename.md
- pages/linux/switch_root.md
- pages/linux/urpmi-addmedia.md
- pages/linux/urpmi-removemedia.md
- pages/linux/urpmi-update.md
- pages/linux/virt-viewer.md
- pages/linux/virt-xml.md
- pages/osx/chpass.md
- pages/osx/launchctl.md
- pages/windows/wget.md
This PR standardizes the capitalization of the "note" term in descriptions to use "Note:" instead of "NOTE:" or "note:".
> pages.*: standardize capitalization in note term

- pages.zh/common/rsync.md
> rsync: update Chinese translation

- pages/linux/alien.md
debtap is more accurate than alien and focus on .deb -> Arch Linux packages/PKGBUILD, so it is nice to mention it there for Arch users
> alien: add debtap to see also section

- pages/common/git-diff.md
I'm currently learning Git, and when I looked up the command 'git diff,' I found the term 'uncommitted' quite confusing. It seemed more applicable to 'git diff HEAD' rather than to 'git diff.' I think it would be clearer to just use 'unstaged'.
> git-diff: clarify description of git diff

- contributing-guides/git-terminal.md
`git checkout` was split (even though it wasn't removed) into `git switch` and `git restore`, which provides a much cleaner separation of responsabilities.
> docs: use switch instead of checkout and fix header levels in contributing-guides/git-terminal

- pages/common/aws-quicksight.md
- **Version of the command being documented (if known):** 2.15.19
IMO the term "CLI" in page descriptions are unnecessary because most tldr pages document CLI programs, we should focus on making explicit that GUI programs are GUI programs.
> aws-quicksight: improve page description

- pages/common/aws-codeartifact.md
- **Version of the command being documented (if known):** 2.15.19
This PR has 3 changes:
1. Improve the page page description to a less generic one.
2. Improve the `--tool`'s argument placeholder of `aws codeartifact login` to show all possible options
3. Use generic wording for help commands
> aws-codeartifact: improve page description and examples

- pages/common/simplehttpserver.md
> simplehttpserver: add page

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
It can be a bit confusing to new contributors that the PR title is not mentioned in the link that they click on the PR template, they can think that the section only applies to commit messages.
This PR also contains some other changes:
1. Fix "its" vs. "it is"
2. Suggest "pages*" use for related changes that affect several unrelated pages
3. Define a standard for commit messages and PR titles of script changes
> docs: mention PR title in the commit message section

- pages/android/am.md
- pages/android/dalvikvm.md
- pages/android/dumpsys.md
- pages/android/logcat.md
- pages/android/pm.md
- pages/android/screencap.md
- pages/common/adb-install.md
- pages/common/adb-logcat.md
- pages/common/adb-reverse.md
- pages/common/adb-shell.md
- pages/common/adb.md
- pages/common/bundletool-dump.md
- pages/common/bundletool-validate.md
- pages/common/bundletool.md
- pages/common/sdkmanager.md
- pages/common/zipalign.md
Some pages return 301 (page moved permanently), causing a redirection. This PR updates these links.
> pages*: fix developer.android.com links

- pages/common/httpx.md
> httpx: add page

- pages/common/vcpkg.md
- **Version of the command being documented (if known):** 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e
> vcpkg: add page

- pages/linux/id3v2.md
The keyboard character is hyphen minus (‐, code point U+002D), while in the page the used character is hyphen (‐, code point U+2010).
This was causing an error with aiofile in my script (#12289).
> id3v2: use hyphen minus (U+002D) instead of hyphen (U+2010)

- pages/common/warp-cli.md
1. Improve a previously almost generic description ("CLI client for x service")
2. Add another VPNs services to "See also", improving the discoverability of pages for similar purposes
3. Add `set-mode` example
> warp-cli: improve page description, add "See also" and add example

- pages/common/:.md
- pages/common/colon.md
Adding page requested on #12070
closes #12070
> ":": add page 

- README.md
I initially thought of adding a separate index for the PDF files, but on second thought I don't think it is necessary as the files already contain the relevant language codes. This PR adds a note to the README referencing the translated PDFs and also updates the existing link from the website -> release assets. Since we will be removing the assets from the website in future.
> feat: add reference to other PDFs

- pages/common/tail.md
- pages/osx/tail.md
Add the missing article "a" in both common and osx pages as suggested by the change on the style guide by @kbdharun on #12304.
> tail: replace "the file" with "it"

- pages/common/fitstopnm.md
- pages/common/pamcut.md
- pages/common/pamdeinterlace.md
- pages/common/pamdice.md
- pages/common/pammixinterlace.md
- pages/common/pamtofits.md
- pages/common/pamundice.md
- pages/common/pnmtofits.md
> fitstopnm, pamcut, pamdeinterlace, pamdice, pammixinterlace, pamtofits, pamundice, pnmtofits: add pages

- pages/common/dolt-sql.md
- pages/common/dotnet-ef.md
- pages/common/duckdb.md
- pages/common/gcloud-sql-export-sql.md
- pages/common/mysqlsh.md
- pages/common/textql.md
- pages/linux/dnsrecon.md
This is all about the famous discussion about the pronunciation of SQL ("Ess-cue-ell" vs "Sequel"). If it is pronunciated like "Ess-cue-ell", the right wording is "an SQL", if it is pronunciated like "Sequel", the right wording is "a SQL".
I read [an article](https://www.dbvis.com/thetable/sql-or-sequel) and, in my opinion, "Ess-cue-ell" looks like the pronunciation more close to the "official" one.
Either way, the most important thing to me is keeping consistency through all pages.
> pages*: use "an SQL" instead of "a SQL"

- pages/common/git-clean.md
- Add mnemonics for all short options
- Make the page description a bit more verbose and the example descriptions a bit more concise, it was the opposite before
> git-clean: add all mnemonics and improve wording

- pages/common/jq.md
I've found and fixed a small issue in the `jq` command page regarding the Array/Object Value Iterator `.[]`.
- cur: Print all array items/object keys:
- fix: Print all array/object values:
For reference, the official documentation (https://jqlang.github.io/jq/manual/) explains it as follows:
```
Array/Object Value Iterator: .[]
If you use the .[index] syntax, but omit the index entirely, it will return all of the elements of an array. Running .[] with the input [1,2,3] will produce the numbers as three separate results, rather than as a single array. A filter of the form .foo[] is equivalent to .foo | .[].
You can also use this on an object, and it will return all the values of the object.
```
Additionally, I've updated the …
> jq: fix description and url

- pages/linux/apt-get.md
Copied from line 4 of [apt.md](https://github.com/tldr-pages/tldr/blob/main/pages/linux/apt.md) to recommend users to use `apt` instead of `apt-get` in Ubuntu versions 16.04 and later.
Latest/All
> apt-get: add recommendation for apt

- pages/linux/opkg.md
According to the official wiki, running ```opkg upgrade``` is highly discouraged.
https://openwrt.org/meta/infobox/upgrade_packages_warning
> opkg: remove upgrade command

- pages/common/select.md
This PR implements the fix from #12445 (`${{{fruits[@]}}}` will be rendered as $**{fruits[@]}** ), removes redundant braces (`{{x}} {{y}}` is rendered exactly the same as `{{x y}}`) and moves `select` to `common`, because Bash is not Linux-specific.
Closes #12445.
> select: move to common, fix placeholders

- pages/common/nmap.md
Fix description of example which is to evade detection rather than getting detected
> nmap: edit page

- pages/common/pambrighten.md
- pages/common/ppmbrighten.md
> pambrighten, ppmbrighten: add pages

- pages/common/aws-cognito-idp.md
- pages/common/aws-dynamodb.md
- pages/common/aws-ec2.md
- pages/common/aws-eks.md
- pages/common/aws-iam.md
- pages/common/aws-kinesis.md
- pages/common/aws-lambda.md
- pages/common/aws-rds.md
This PR rephrases AWS subcommands pages to use less generic and more useful descriptions, avoiding "CLI" when it is not directly related to the purpose of the command as the case of `aws history`, for example.
Although these are ready for review, there are still 4 AWS subcommands that need to be fixed:
- aws glue
- aws route53
- aws s3
- aws ses
> aws-*: rephrase page descriptions to avoid CLI when unnedeed

- pages/windows/reg-add.md
- pages/windows/reg-compare.md
- pages/windows/reg-copy.md
- pages/windows/reg-delete.md
- pages/windows/reg-export.md
- pages/windows/reg-flags.md
- pages/windows/reg-import.md
- pages/windows/reg-load.md
- pages/windows/reg-query.md
- pages/windows/reg-restore.md
- pages/windows/reg-save.md
- pages/windows/reg.md
---
- Add grouped examples of subcommands on reg.md to guide the reader through these pages rather than showing expected options first
- Distinguish save/restore and export/import on page descriptions, example path placeholders and reg.md
- "first_key_name" and "second_key_name" -> "key_name1" and "key_name2"
- Add mnemonics for all options
- Specify possible type arguments
- sub key -> subkey. This is the right spelling according to Microsoft's documentation
- Mark `reg load` note as such in the page description
> reg*: improve pages

- pages/common/ncmpcpp.md
- pages/common/youtube-viewer.md
- pages/linux/aplay.md
We can follow this common approach for CLI music/audio players or specify CLI on the other pages too (e.g. aplay).
> ncmpcpp, youtube-viewer, aplay: remove "command-line" from description

- pages/linux/virt-manager.md
- **Version of the command being documented (if known):** 4.1.0
- Remove "CLI launcher for virt-manager" from the page description
- Use generic wording on the first example (no options)
- Clarify the purpose of the argument for the performance and detail windows
> virt-manager: edit page

- pages/common/kdeconnect-cli.md
> kdeconnect-cli: expand description

- pages.it/common/expand.md
- pages/common/expand.md
The `expand` command doesn't accept the equal sign '=' as a separator between the short option `-t` and its arguments. Below are illustrations of the error the user faces in case the equal sign is used:
$ expand -t=2 path/to/file
expand: tab size contains invalid character(s): ‘=2’
$ expand -t=1,4,6
expand: tab size contains invalid character(s): ‘=1,4,6’
For the short option `-t`, the correct separator is space, so fix this in the examples.
> expand: fix short option `-t` argument separator

- pages/linux/iptables-save.md
- pages/windows/reg-query.md
- missing placeholder in #12301
- `iptables-save` had a typo ("to to" instead of "to do"). #12508 removed one word instead of fixing the typo.
> reg-query: add missing placeholder; iptables-save: fix typo

- pages/common/gitk.md
- pages/common/kitex.md
- pages/common/rclone.md
- pages/common/venv.md
Discovered through the proposed new check TLDR021 in the linter (see https://github.com/tldr-pages/tldr-lint/pull/310).
> gitk, kitex, rclone, venv: edit pages

- pages/linux/zipsplit.md
- **Version of the command being documented (if known):** Info-ZIP 3.00
- Move zipcloak to common (it is not Linux-exclusive: https://keith.github.io/xcode-man-pages/zipsplit.1.html)
- Use standard path placeholder formatting
- Use "smaller Zip archives" instead of "split Zip archives" for clarity (IMO "split" is kinda confusing when used as the result)
- Add the simplest example usage (no flags, default piece size)
- Make the description more consise (splitting an archive implies it is being read)
> zipsplit: improve page

- pages/common/zipcloak.md
- Move `zipcloak` to common (I don't if it works on Windows, but it is also [available for macOS](https://keith.github.io/xcode-man-pages/zipcloak.1.html))
- Replace "zipfile" with "Zip archive"
> zipcloak: move to `common` and replace "zipfile"

- pages/linux/agetty.md
- **Version of the command being documented (if known):** util-linux 2.39.3
> agetty: add page

- pages/linux/tunelp.md
- **Version of the command being documented (if known):** util-linux 2.39.3
> tunelp: add page

- pages/linux/agetty.md
- **Version of the command being documented (if known):** According to the output of `agetty --version`, `util-linux 2.39.3` 
As discussed in a comment of #12552, this adds the missing hyphen to indicate the option `-n`.
> agetty: add missing hyphen in placeholder

- COMMUNITY-ROLES.md
- MAINTAINERS.md
Closes #12209
- Update the `MAINTAINERS.md` file to reflect the users removed post-2FA enablement in org.
- Add a notice to the `COMMUNITY-ROLES.md` file and repository collaborator template regarding the same. (Note: I didn't add it to the Org member or Org owner template as they would have 2FA already enabled as a collaborator)
> MAINTAINERS: update file, COMMUNITY-ROLES: add notice for 2FA

- pages/common/gitui.md
- pages/common/tig.md
- `tig` has mouse support, although it is disabled by default. It can be enabled adding the following line to `tigrc`:
```
set mouse = true
```
- `tig` has so many key bindings that allows changing the view, for example. The help in the TUI shows them.
> gitui, tig: improve page descriptions and add "See also"; tig: add example

- pages/common/history.md
Add command to display timestamp when printing history in Zsh
> history: add command to display timestamp

- pages/common/dnsx.md
> dnsx: add page

- pages/common/julia.md
Switch example startup from parallel mode (-p) to multithreaded mode (-t) to align with the latest practices, which should lead to better performance.
- **Version of the command being documented (if known):** all
> julia: switch example from parallel to threaded

- pages/common/ps.md
Added a note that `ps aux | grep {{string}}` will match the grep process itself unless using a regex with grep. This is something that actively confused me as a newbie.
---
`ps from procps-ng 4.0.3`
`grep (GNU grep) 3.11`
> ps: clarify grep example

- pages/common/git-bug.md
- pages/common/git-bulk.md
This PR brings two new changes:
+ git-bug: use imperative mood for command examples
+ git-bulk: fix placeholder naming convention
> git-bug, git-bulk: fix English pages

- pages/linux/id3v2.md
This is `id3v2`'s `--help`:
```
Usage: id3v2 [OPTION]... [FILE]...
Adds/Modifies/Removes/Views id3v2 tags, modifies/converts/lists id3v1 tags
-h,  --help               Display this help and exit
-f,  --list-frames        Display all possible frames for id3v2
-L,  --list-genres        Lists all id3v1 genres
-v,  --version            Display version information and exit
-l,  --list               Lists the tag(s) on the file(s)
-d,  --delete-v2          Deletes id3v2 tags
-s,  --delete-v1          Deletes id3v1 tags
-D,  --delete-all         Deletes both id3v1 and id3v2 tags
-C,  --convert            Converts id3v1 tag to id3v2
-1,  --id3v1-only         Writes only id3v1 tag
-2,  --id3v2-only         Writes only id3v2 tag
-r,  --remove-frame "FRAMEID"   Removes the specified id3v2 frame
-a, …
```
> id3v2: fix `--list` flag

- contributing-guides/style-guide.md
- [N/A] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [N/A] The page(s) have at most 8 examples.
- [N/A] The page description(s) have links to documentation or a homepage.
- [N/A] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- **Version of the command being documented (if known):** N/A
When reviewing Spanish pages, I and other reviewers, often see the word `id` in placeholders to refer to an identifier (e.g. GPG key). I believe that is not correct. 
It is worth mentioning that this issue was suggested to be documented by @vitorhcl in a comment of #12675.
I have searched through the Spanish pages with the following command:
```shell
grep -REx …
```
> contributing-guides: document preference of Spanish word in placeholders

- pages/linux/sslstrip.md
> sslstrip: add page

- pages.es/common/figlet.md
- pages.es/common/git-am.md
- pages.es/common/git-checkout.md
- pages.es/common/git-cherry-pick.md
- pages.es/common/git-format-patch.md
- pages.es/common/git-restore.md
- pages.es/common/git-switch.md
- pages.es/common/showfigfonts.md
- pages.es/common/xkill.md
- pages.es/common/zsh.md
- pages.es/osx/arch.md
I ended up completing the missing commands
> pages*: replace "Véase" with "Vea" on some Spanish pages

- pages.id/common/git-clear-soft.md
- pages.id/common/git-coauthor.md
- pages.id/common/git-cola.md
- pages.id/common/git-column.md
- pages.id/common/git-commit-graph.md
Subcommands are `git-clear-soft`, `git-coauthor`, `git-cola`, `git-column`, and `git-commit-graph`.
> common: add Indonesian translations for Git subcommands

- pages/linux/chrt.md
Previous:
```
$ chrt --pid 3625066 --idle
chrt: invalid PID argument: '--idle'
```
(exit code 1)
With PR:
```
$ chrt --idle --pid 3625066  
pid 3625066's current scheduling policy: SCHED_OTHER
pid 3625066's current scheduling priority: 0
```
(exit code 0)
- **Version of the command being documented (if known):** chrt from util-linux 2.39.3
> chrt: fix argument order when changing the scheduling policy

- pages/common/fastfetch.md
- **Version of the command being documented (if known):** fastfetch 2.9.1
> fastfetch: add `--pipe` example

- pages.ar/linux/dockerd.md
- pages.pt_BR/linux/dockerd.md
- pages/linux/dockerd.md
Edit: There was another page (`./pages.ar/linux/dockerd.md`) that has the old URL.. but it's in Arabic and I can't seem to able to edit it.
> pages.{en, pt_BR}: replace the previous dockerd URL with the new one

- pages/common/dart.md
In this PR, I added an example to the `dart` command about automatic code fixes using the `dart fix --apply` command. I think we should add this example because this subcommand is useful, especially for novice programmers.
Please review and merge these changes. 
Thank you!
> dart: add fix subcommand example

- pages.pl/sunos/devfsadm.md
- pages.pl/sunos/dmesg.md
- pages.pl/sunos/prctl.md
- pages.pl/sunos/prstat.md
- pages.pl/sunos/snoop.md
- pages.pl/sunos/svcadm.md
- pages.pl/sunos/svccfg.md
- pages.pl/sunos/svcs.md
- pages.pl/sunos/truss.md
This PR adds Polish translation for all SunOS commands. Please review and merge the changes. Thank you!
> pages.pl/sunos/*: add pages

- pages/linux/pw-cli.md
This PR fixes the link to the documentation of the `pw-cli` command.
> pw-cli: fix link to the documentation

- pages/linux/systemctl.md
> systemctl: update page

- pages.es/common/dnsx.md
> dnsx: add Spanish translation

- pages.es/linux/vnstat.md
- pages.es/linux/vnstati.md
- pages/linux/vnstat.md
- pages/linux/vnstati.md
It seems before the flag was `--top10` but now the flag is `--top` and accepts an argument.
> vnstat*: fix flag, rename placeholder and add Spanish translation

- pages.es/common/pambrighten.md
> pambrighten: add Spanish translation

- pages/common/lstopo.md
- **Version of the command being documented (if known):** 2.10.0
> lstopo: add page

- pages.pl/linux/a2disconf.md
This PR adds Polish translation for `a2disconf` (`linux`).
> a2disconf: add Polish translation

- pages/osx/netstat.md
The common version doesn't seem to work in osx.
> netstat: add osx page

- pages/common/pactl.md
> pactl: add infodump example

- pages.es/common/archwiki-rs.md
> archwiki-rs: add Spanish translation

- pages.de/common/alacritty.md
- pages.es/common/alacritty.md
- pages.fr/common/alacritty.md
- pages.id/common/alacritty.md
- pages.it/common/alacritty.md
- pages.ko/common/alacritty.md
- pages.nl/common/alacritty.md
- pages.pt_BR/common/alacritty.md
- pages.pt_PT/common/alacritty.md
- pages.zh/common/alacritty.md
- pages/common/alacritty.md
This PR updates the `alacritty` command page to use `.toml` as its config file extension, instead of the deprecated `.yml`.
See https://github.com/alacritty/alacritty/pull/7028/files for their deprecation warning :)
- **Version of the command being documented (if known):** 0.13.2 (bb8ea18)
> alacritty: update configs to .toml from deprecated .yml

- pages/common/sops.md
Hi, 
my first public contribution here, so greetings to my Ma! :)
I think this one is essential, got stuck twice now by remembering this one and so I guess it should be shared with others 
> sops: update page

- .github/CODEOWNERS
In this PR I add myself to CODEOWNERS as a reviewer of  `/pages/common/`, `/pages/linux/`, `/pages/windows/`.
> CODEOWNERS: add @spageektti as reviewer for common, linux, windows

- pages/linux/pw-config.md
Hi. This PR adds a page for `pw-config`, which is part of `pipewire`. 
Instead of using placeholders, I used specific examples because I think they show more of what the command is about, but I will add placeholders if needed.
#11747 
- **Version of the command being documented (if known):** Compiled with libpipewire 1.0.6
> pw-config: add page

- pages.es/common/d2.md
> d2: add Spanish translation

- pages/linux/tor.md
- pages/linux/torify.md
> tor, torify: add pages

- pages/common/chezmoi.md
Add `chezmoi re-add` & move two `init` examples next to each other.
> chezmoi: update page

- pages.es/common/git-lfs.md
- pages.fr/common/git-lfs.md
- pages.it/common/git-lfs.md
- pages.tr/common/git-lfs.md
- pages/common/git-lfs.md
https://git-lfs.github.com now redirects to https://git-lfs.com/.
> git-lfs: update upstream link

- pages.es/common/tree.md
- pages.it/common/tree.md
- pages.ko/common/virsh.md
- pages.pt_BR/common/virsh.md
- pages.tr/common/tree.md
- pages.zh/common/tree.md
- pages/common/sam2p.md
- pages/common/secrethub.md
- pages/common/slimrb.md
- pages/common/spfquery.md
- pages/common/tree.md
- pages/common/unison.md
- pages/common/virsh.md
- pages/common/wireplumber.md
- pages/common/wpexec.md
- pages/common/xdelta.md
This PR is a continuation of #12821.
> pages*/common/*: fix broken links

- pages.es/common/7z.md
> 7z: update Spanish translation

- pages/linux/getenforce.md
- pages/linux/getsebool.md
- pages/linux/semanage-boolean.md
- pages/linux/semanage-permissive.md
- pages/linux/semanage-port.md
- pages/linux/semanage.md
- pages/linux/setenforce.md
- pages/linux/setsebool.md
- **Version of the command being documented (if known):** `policycoreutils-python-utils-3.6`
I also updated `semanage.md` and `getenforce.md` to reference these new pages.
> setenforce, {get,set}sebool, semanage-{boolean,port,permissive}: add page

- pages/linux/matchpathcon.md
- pages/linux/secon.md
- **Version of the command being documented (if known):** `libselinux-utils-3.6`, `policycoreutils-3.6`
> matchpathcon, secon: add page

- pages/common/docker.md
- pages/common/history.md
- pages/common/ollama.md
- pages/common/tldr.md
> docker, ollama, history, tldr: fix mnemonics

- pages/linux/ctop.md
> ctop: add page

- pages/common/dotnet-add-reference.md
- **Version of the command being documented (if known): .NET Core 3.1 SDK and later versions**
> dotnet-add-reference: add examples for multiple references

- pages/linux/auditctl.md
Hi. This PR adds a page for `auditctl` under `linux` directory.
- **Version of the command being documented (if known):** 4.0.1
> auditctl: add page

- pages/linux/tor.md
In this PR I removed the duplicate ( by default, tor acts as a client only). I also updated the link (removed the unnecessary `man/`).
> tor: remove duplicate and update link

- pages/common/pylint.md
The provided examples do not provide examples on how to lint packages and modules which is a common use-case. The added examples follow the recommended usage according to pylint docs.
- **Version of the command being documented (if known):3.2.2
> pylint: add package and module examples

- pages/common/virt-qemu-run.md
Added virt-qemu-run tldr page
For #5425
> virt-qemu-run: add page

- .github/workflows/ci.yml
- .github/workflows/copy-release-assets.yml
This PR adds support for attesting release artefacts both in our regular CI workflow and also for the copy assets workflow (which executes after we publish a release).
Currently, at tldr, we are migrating to providing our assets only via GitHub releases (which allows us to update assets in a non-git way, dynamically).
While this increases ease of use, it opens up a **glaring security issue** as it allows for any collaborator to update the assets (including the checksum) without a trace [and yep GitHub organization logs don't document Release assets modifications/uploads], causing us to have no idea which assets are tampered with (in case of a misuse/security incident).
Our current governance process facilitates inviting new collaborators/maintainers to this repository with write access …
> feat/ci: add support for attesting release assets

- pages/common/toipe.md
Toipe is a terminal typing test built in rust.
> toipe: add page

- pages/common/waybar.md
Waybar is a highly customizable Wayland bar for Sway and Wlroots based compositors.
> waybar: add page

- pages/common/toipe.md
In [0.5.0](https://github.com/Samyak2/toipe/releases/tag/v0.5.0) update `--punctuation` option was added to `toipe` so I added an example for this option.
- **Version of the command being documented (if known):** 0.5.0
> toipe: add example

- pages/common/age-keygen.md
- pages/common/age.md
- pages/common/apm.md
- pages/common/git-fsck.md
- pages/common/nix-build.md
- pages/common/nix-shell.md
- pages/common/nix-store.md
- pages/common/nix3-build.md
- pages/common/nix3-registry.md
- pages/common/nix3-run.md
- pages/common/nix3-search.md
- pages/common/nix3-shell.md
- pages/common/nix3-store.md
- pages/common/rustup-toolchain.md
- pages/linux/mount.ddi.md
- pages/linux/setcap.md
These pages are not following the "See also" standard ("See also: COMMAND_NAME").
> pages*: make "See also" conform to the new syntax (#12756)

- pages/linux/pw-dot.md
Hi. I added the short options and short option mnemonics. I also added examples about `--help` and `--json`. The `--json` option seems to not be included in the manual page but is present in the help (Fedora 40).
- **Version of the command being documented (if known):** `Compiled with libpipewire 1.0.6`
> pw-dot: update page

- README.md
The old method of using a fragment appended to the URL (i.e. `#gh-dark-mode-only` or `#gh-light-mode-only`), is deprecated and replaced with the HTML tag format.
Checkout <https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to> for more information.
> cleanup: remove URL theme fragment from console image

- pages/common/devenv.md
- **Version of the command being documented (if known):** devenv 1.0.5 (x86_64-linux)
however devenv supports multiple architectures thus `common` is most suitable place for it.
> devenv: add page

- pages/common/grep.md
Hi. I added short options because it will make the page more helpful.
I don't know what to do with the example on line 24 because there is already a placeholder.
- **Version of the command being documented (if known):** `grep (GNU grep) 3.11`
> grep: update page

- pages.nl/common/magick-convert.md
- pages/common/magick-convert.md
> magick-convert: fix typo

- pages/common/rkdeveloptool.md
- **Version of the command being documented (if known):** 1.3
[rkdeveloptool](https://github.com/rockchip-linux/rkdeveloptool) is an arcane command-line utility developed by [Rockchip](http://www.rock-chips.com/), a Chinese semiconductor company, to configure the boot process and target bootable storage for computers featuring Rockchip SoCs. This tool has been extensively used to install and troubleshoot some Rockchip-based single-board computer (SBC) products, such as the [Orange Pi 5](http://www.orangepi.org/orangepiwiki/index.php/Orange_Pi_5) and [Radxa ROCK Pi 5](http://radxa.com/products/rock5/5a/) (both featuring the same Rockchip RK3588S SoC).
It's arcane because it has limited documentation about its subcommands and parameters, leaving several SBC users puzzled with these:
``` …
```
> rkdeveloptool: add new command

- pages/common/git-contrib.md
> git-contrib: fix grammar

- pages/linux/kill.md
> I used this regex to find these: `-\{\{([a-z]{1})\|-(\w+(-\w+)*)\}\}`. It is also an issue in the `look`-pages, but those get fixed in #12932
> kill: fix highlighting long and short options according to guideline

- pages.id/common/ansible-doc.md
- pages.id/common/ansible-galaxy.md
- pages.id/common/ansible-inventory.md
- pages.id/common/ansible-playbook.md
- pages.id/common/ansible-pull.md
- pages.id/common/ansible-vault.md
- pages.id/common/ansible.md
This PR adds Indonesian translations to `ansible` and all of currently-documented subcommands.
> ansible, ansible-*: add Indonesian translation

- pages.es/common/pydocstyle.md
- pages.es/linux/agetty.md
- pages.es/linux/blkpr.md
- pages.es/linux/showkey.md
- pages/common/azurite.md
- pages/common/diff.md
- pages/common/git-archive.md
- pages/common/pydocstyle.md
- pages/linux/agetty.md
- pages/linux/blkpr.md
- pages/linux/pw-dot.md
- pages/linux/showkey.md
<details>
<summary>Script</summary>
```python
#!/usr/bin/env python3
"""
A Python script to generate or update alias pages.
Disclaimer: This script generates a lot of false positives so it isn't suggested to use the sync option. If used, only stage changes and commit verified changes for your language by using -l LANGUAGE.
Note: If the current directory or one of its parents is called "tldr", the script will assume it is the tldr root, i.e., the directory that contains a clone of https://github.com/tldr-pages/tldr
If you aren't, the script will use TLDR_ROOT as the tldr root. Also, ensure 'git' is available.
Usage:
python3 scripts/set-alias-page.py [-p PAGE] [-S] [-l LANGUAGE] [-s] [-n]
Options:
-p, --page PAGE
Specify the alias page in the format "platform/alias_command.md".
-S, --sync …
```
> pages*: remove mnemonics when highlighting both long and short options

- pages/common/bc.md
- pages/common/dd.md
- pages/common/nc.md
- pages/common/sed.md
- pages/common/tree.md
- pages/common/yacc.md
This PR updates links from `manned.org/man/` to `manned.org/` in `common`.
I'll send another PR for the Linux ones. 
```sh
$ grep -r "https://manned.org/man" pages/ | wc -l
26
```
```sh
$ grep -r "https://manned.org/" pages/ | wc -l
752
```
> bc, dd, nc, sed, tree, yacc: update links

- pages.id/common/ansiweather.md
- pages.id/common/ant.md
- pages.id/common/antibody.md
- pages.id/common/anytopnm.md
- pages.id/common/apg.md
- pages.id/common/apkleaks.md
- pages.id/common/apm.md
- pages.id/common/apropos.md
- pages.id/common/ar.md
- pages.id/common/arc.md
- pages.id/common/arch.md
- pages.id/common/archwiki-rs.md
- pages.id/osx/arch.md
- pages/common/rkdeveloptool.md
> common/*, osx/arch: add Indonesian translation

- pages.zh/common/accelerate.md
- pages.zh/common/age-keygen.md
- pages.zh/common/airdecap-ng.md
- pages.zh/common/airshare.md
- pages.zh/common/alex.md
> alex, age-keygen, accelerate, airdecap-ng, airshare: fix link typo

- pages/linux/portageq.md
> portageq: add page

- pages.nl/common/shred.md
> shred: add Dutch translation

- pages.nl/common/tee.md
> tee: add Dutch translation

- pages/linux/zramctl.md
The last example call (zramctl) needs also sudo.
> zramctl: update page

- pages.es/linux/fpsync.md
> fpsync: add Spanish translation

- pages/linux/eselect-locale.md
- pages/linux/eselect-repository.md
- pages/linux/eselect.md
There are a lot more `eselect` modules; this is just the main page and 2 modules
> eselect, eselect-{repository,locale}: add page

- pages.nl/common/who.md
- pages.zh/common/who.md
- pages/common/who.md
> who: update deprecated command

- pages/linux/efibootmgr.md
I'm not sure what the second example is about - `efibootmgr -v` does not list any paths, so I removed it.
> efibootmgr: update page

- pages/common/piper.md
- **Version of the command being documented (if known):** 1.2.0
> piper: add page

- pages/common/doggo.md
Add `doggo` DNS query command-line tool.
- **Version of the command being documented (if known): 1.0.4**
> doggo: add page

- pages/common/cargo-clippy.md
- **Version of the command being documented (if known):** `clippy 0.1.78`
> cargo-clippy: add lint group example

- pages/common/duckdb.md
**Version of the command being documented (if known):** 0.10.0
DuckDB's `read_csv_auto` is now accessible via `read_csv` since version 0.10.0 ([released in February 2024](https://github.com/duckdb/duckdb/releases/tag/v0.10.0)). This PR reflects this change.
> duckdb: simplify read_csv command

- pages/common/fdupes.md
This corrects the description of 'fdupes -rH', which causes `fdupes` to consider hardlinks as duplicates.  `fdupes` is not designed to convert duplicate files to hardlinks as implied by the original description.
```
❯ fdupes --version
fdupes 2.3.2
❯ fdupes --help
Usage: fdupes [options] DIRECTORY...
-r --recurse            for every directory given follow subdirectories
encountered within
-R --recurse:           for each directory given after this option follow
subdirectories encountered within (note the ':' at the
end of the option, manpage for more details)
-s --symlinks           follow symlinks
-H --hardlinks          normally, when two or more files point to the same
disk area they are treated as non-duplicates; this
option will change this behavior
```
The pertinent  code is:
``` c …
```
> fdupes: correct description of `-rH` to 'consider hardlinks'

- pages/common/whatwaf.md
> whatwaf: add page

- pages/osx/automount.md
Added page for osx command `automount`, in English.
> automount: add page

- pages/common/octez-client.md
This PR adds example commands for `octez-client`, the primary command-line client for the Tezos blockchain and one of the programs in the Octez suite of tools. TLDR, here are some quick install instructions: https://docs.tezos.com/developing/octez-client/installing. Official install instructions are at https://tezos.gitlab.io/introduction/howtoget.html. 
- **Version of the command being documented (if known): 20.02**
> octez-client: add page

- pages/common/aws-ce.md
> aws-ce: add page

- pages/common/read.md
Replaced example worked in zsh only. Fixed example works in both zsh and bash.
> read: fix example command

- pages/common/git-config.md
I tried to somehow add the new example without deleting any of the previous ones.
If we want to dedicate two examples to setting the username and email, we have to get rid of something else because of the 8 example limit.
Closes #13415.
> git-config: update page

- pages/linux/kill.md
> kill: remove the `--table` long option

- pages.nl/common/timeout.md
> timeout: update Dutch translation

- .github/CODEOWNERS
- MAINTAINERS.md
https://github.com/tldr-pages/tldr/pull/13461#issuecomment-2295286922
This PR adds back yutyo with their renamed username to the CODEOWNERS file and updates the MAINTAINERS file for the same.
> MAINTAINERS: fix @tansiret username, add back to CODEOWNERS file

- pages.ko/common/git-commit-graph.md
- pages.ko/common/git-commit-tree.md
- pages.ko/common/git-config.md
- pages.ko/common/git-reflog.md
- pages.ko/common/git-stash.md
**Translation**
git-{config,commit-tree,commit-graph,reflog,stash}
**Checklists**
> git-*: add Korean translation

- pages.nl/common/mycli.md
- pages.nl/linux/mycli.md
> mycli: add Dutch translation

- pages/common/uv-python.md
- pages/common/uv-tool.md
- pages/common/uv.md
Tried to do `tldr uv` but it could't find anything, so I have added the core pages for [uv](https://github.com/astral-sh/uv).
> uv, uv-{python,tool}: add page

- pages/common/git-diff.md
There are already 8 examples. The diffstat is more useful for users to get a quick summary of what changed, and is what's shown for a git pull by default. The changed file names is more useful programmatically.
> git-diff: Use --stat command instead of only names

- pages.id/common/bat.md
- pages.nl/common/bat.md
- pages.nl/common/http.md
- pages/common/bat.md
- pages/common/git-add.md
- pages/common/git-annotate.md
- pages/common/git-archive.md
- pages/common/git-blame.md
- pages/common/git-branch.md
- pages/common/git-cherry.md
- pages/common/git-clean.md
- pages/common/git-diff-tree.md
- pages/common/git-lfs.md
- pages/common/git-log.md
- pages/common/git-rebase.md
- pages/common/git-reflog.md
- pages/common/git-remote.md
- pages/common/git-rev-list.md
- pages/common/git-revert.md
- pages/common/git-shortlog.md
- pages/common/git-svn.md
- pages/common/git-tag.md
- pages/common/http.md
- pages/common/mitmproxy.md
Ref: https://github.com/tldr-pages/tldr/pull/13441#pullrequestreview-2273750884
> pages*: convert long-short to short-long syntax

- pages/linux/deb-get.md
Users must **NOT** use `sudo deb-get` - it is not needed and as well as being bad practice it causes problems.
- **Version of the command being documented (if known):**  0.4.2
> deb-get: correct examples and move to linux section

- pages/common/pg_dumpall.md
Hi!
I found an example in `pg_dumpall` which is invalid. Also tried to make the flags similar to `pg_dump`.
Should I do it the other way arount and modify the existing "single-letter options" to the long ones for both `pg_dump` and `pg_dumpall` (as it's mentioned in [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines) 3.)?
Thanks!
Andras
> pg_dumpall: update page

- pages/common/git-commit.md
- pages/common/rubocop.md
Followup to the https://github.com/tldr-pages/tldr/pulls/13609 to update `git-commit` and `rubocop` pages for English translation
> git-commit, rubocop: use grouped parameters

- pages/linux/quickget.md
the nixos example was incorrect, the macos release list has been updated and some options have been added, renamed or removed
- 4.9.6 **Version of the command being documented (if known):**
> quickget: fix correct examples and update changed options

- pages.id/common/git-add.md
- pages.id/common/git-bulk.md
- pages.id/common/git-bundle.md
- pages.id/common/git-cherry-pick.md
- pages.id/common/git-clean.md
- pages.id/common/git-clear.md
- pages.id/common/git-count.md
- pages.id/common/git-cp.md
- pages.id/common/git-create-branch.md
- pages.id/common/git-format-patch.md
- pages.id/common/git-init.md
- pages.id/common/git-push.md
- pages.id/common/git-remote.md
- pages.id/common/git-rm.md
- pages.id/common/git-status.md
This commit updates some subcommands (e.g. `common/git-pull`) to use the imperative mood (see #8576), updates outdated Git subcommands (see #13572), while also prioritizes translation for commonly-translated subcommands including `common/git-push` and `common/git-pull`.
> git-*: add and update Indonesian translations

- pages/common/pulumi-up.md
> pulumi-up: add --continue-on-error example

- pages/common/az-serial-console.md
- pages/common/az-vm.md
> az serial-console: add page, az: improve command

- pages/common/ffmpeg.md
Moved `-ss` and `-to` flags to after input file so they function as output options. Using the example provided will result in artifacting before the ffmpeg encounters the first keyframe in the input file. Moving them to output options will force ffmpeg to decode the entire input file, which may result in performance overhead, but avoids artifacting in the output file.
> ffmpeg: update page

- pages/linux/firewall-cmd.md
**Changes**
- Added short additional description in heading
- Made the differentiation between runtime and permanent configuration clearer
- Switched from "--get-active-zone" to "--list-all-zones" to show all available zones and their rules
- Removed command "--list-all" as it returns a subset of the first command (the runtime state of the default zone)
- Removed additional command for adding arbitrary ports
- Added command to create a new local port forwarding (for example for rootless reverse proxy containers) to showcase rich rules
- Added information about loss of runtime configuration/changes to reload command
- Added command for saving the current runtime configuration state to the permanent configuration ( in contrast to editing the permanent configuration directly and reloading …
> firewall-cmd: clarify runtime/permanent configuration and add commands

- pages.pl/linux/journalctl.md
- pages.uk/linux/journalctl.md
- pages/linux/journalctl.md
I had trouble using `YYYY-MM-DD HH:mm:ss` style timestamps as recommended in the page for `journalctl`.  
This was probably because the space character separated the HH:mm:ss string from its date: following the recommended syntax (in this case, on Ubuntu 24.04 and using with the HH:mm:ss string 13:33:00), the command failed with the output: ` Failed to add match '13:33:00': Invalid argument`. 
It was therefore solved by surrounding the timestamps with quotation marks. So, I'm recommending a small change to the relevant TLDR pages to demonstrate the use of quotation marks.
All the best
Tris
...
> journalctl: add quotation marks around space-separated timestamps

- pages.es/common/doggo.md
- pages/common/doggo.md
https://doggo.mrkaran.dev/ results in 502 and is currently offline
> doggo: fix link

- pages/common/dtc.md
Add an initial example for a common way to use dtc, the Device Tree Compiler which can create and decompile device trees for embedded Linux systems.
I started using this tool today and was sad I couldn't find a tldr, but didn't let that stop me from reading the man page, using it successfully, and making this.
I've only used it on Linux but Googling around says it should also function on Window (using the Linux subsystem) and the common BSDs as well.
> dtc: add page

- pages.id/linux/dos2unix.md
- pages.id/linux/mac2unix.md
- pages.id/linux/unix2dos.md
- pages.id/linux/unix2mac.md
- pages/linux/dos2unix.md
- pages/linux/mac2unix.md
- pages/linux/unix2dos.md
- pages/linux/unix2mac.md
This PR encourages the use of manned.org links in place of the original project website over https://waterlan.home.xs4all.nl/dos2unix.html, adding long-form options, and also Indonesian translations.
Note that the "More Information" links of other translations are not replaced as most of them are outdated in terms of content.
> dos2unix, mac2unix, unix2dos, unix2mac: standardize More Information links, add Indonesian translation

- pages.pl/linux/raspi-config.md
- pages/linux/raspi-config.md
> raspi-config: update documentation link

- pages.ko/common/cmctl.md
- pages.ko/common/convert.md
- pages.ko/common/coproc.md
- pages.ko/common/core-validate-commit.md
- pages.ko/common/corepack.md
> cmctl, convert, coproc, core-validate-commit, corepack: add Korean translation

- pages.ko/common/cbonsai.md
- pages.ko/common/cbt.md
- pages.ko/common/ccache.md
- pages.ko/common/ccomps.md
- pages.ko/common/cdk.md
> cbonsai, cbt, ccache, ccomps, cdk: add Korean translation

- pages/common/vinmap.md
Added a tldr page for vinmap, a multithreaded Nmap scanner that enhances Nmap’s capabilities for large-scale network exploration.
Includes five usage examples covering basic scans, domain scanning with version and OS detection, custom chunking and threading, JSON output, and scanning multiple IPs.
Ensures clarity and user-friendliness by using descriptive explanations and appropriate placeholders.
> vinmap: add page

- pages/common/yadm-alt.md
- pages/common/yadm-bootstrap.md
- pages/common/yadm-clone.md
- pages/common/yadm-config.md
- pages/common/yadm-decrypt.md
- pages/common/yadm-encrypt.md
- pages/common/yadm-enter.md
- pages/common/yadm-git-crypt.md
- pages/common/yadm-gitconfig.md
- pages/common/yadm-init.md
- pages/common/yadm-introsepct.md
- pages/common/yadm-list.md
- pages/common/yadm-perms.md
- pages/common/yadm-transcrypt.md
- pages/common/yadm-upgrade.md
- pages/common/yadm.md
> yadm: add pages

- pages/common/yadm-config.md
> yadm-config: fix more info line

- contributing-guides/translation-templates/alias-pages.md
- contributing-guides/translation-templates/subcommand-mention.md
In translation-templates, use imperative mood  for pt_BR instead of the verb's infinite conjugation.
In alias-pages, fix two typos in pt_BR: "tem" (has in English) receives a caret when the substantive is plural, making it têm (have). Also "própria" is the proper translation for "own" translation.
> contributing-guides: fix pt_BR templates

- pages.pt_BR/common/rc.md
- pages.pt_BR/common/strings.md
- pages.pt_BR/common/tldr-lint.md
- pages.pt_BR/common/tlmgr-platform.md
- pages.pt_BR/common/todo.md
- pages.pt_BR/common/transmission-cli.md
- pages.pt_BR/common/transmission-create.md
- pages.pt_BR/common/transmission-daemon.md
- pages.pt_BR/common/transmission-edit.md
- pages.pt_BR/common/transmission-remote.md
- pages.pt_BR/common/transmission-show.md
> pages.pt_BR/common/*: add Portuguese Brazilian translations 

- pages/common/ollama.md
This link is necessary, because model ids from the list are required to access/use models using ollama, but it can not be viewed through the `ollama` command.
---
- **Version of the command being documented (if known):** v0.3.12
> ollama: add link to model list

- pages.ko/windows/ver.md
- pages.ko/windows/virtualboxvm.md
- pages.ko/windows/vol.md
- pages.ko/windows/vswhere.md
- pages.ko/windows/w32tm.md
> ver,virtualboxvm,vol,vswhere,w32tm: add Korean translation

- pages/osx/launchd.md
The description was a bit odd, we've noticed it on PR #14090 , so I am sending this small fix.
> launchd: improving main description

- pages.id/freebsd/base64.md
- pages.id/osx/base64.md
- pages/freebsd/base64.md
- pages/osx/base64.md
On #13807 I originally promised to migrate existing translations of `common/base64` to `osx/base64` (and `freebsd/base64`). But since the macOS and FreeBSD's `base64` command has an additional feature (i.e. to write the output directly to file), I can only provide the English and Indonesian translations right now.
I am aware that the macOS manpage also include references to `b64decode` and `b64encode`, but these commands are not available as of macOS Sonoma although `uudecode` and `uuencode` exist. The former commands might be available on FreeBSD but further confirmation is required.
> freebsd/base64, osx/base64: refresh page, duplicate osx to freebsd, and add Indonesian translation

- pages.de/linux/cgroups.md
- pages.es/linux/cgroups.md
- pages.fr/linux/cgroups.md
- pages.hi/linux/cgroups.md
- pages.id/linux/cgroups.md
- pages.it/linux/cgroups.md
- pages.ko/linux/cgroups.md
- pages.ne/linux/cgroups.md
- pages.pl/linux/cgroups.md
- pages.pt_PT/linux/cgroups.md
- pages.th/linux/cgroups.md
- pages.tr/linux/cgroups.md
- pages.zh/linux/cgroups.md
- pages.zh_TW/linux/cgroups.md
I checked each code history, if there exists a correct version, I will revert the page to that version. Otherwise, I will delete the page.
Unaffected translations: [en](https://github.com/tldr-pages/tldr/blob/main/pages/linux/cgroups.md), [nl](https://github.com/tldr-pages/tldr/blob/main/pages.nl/linux/cgroups.md), [pt_BR](https://github.com/tldr-pages/tldr/blob/main/pages.pt_BR/linux/cgroups.md), [ta](https://github.com/tldr-pages/tldr/blob/main/pages.ta/linux/cgroups.md)
> cgroups: remove wrong auto-generated alias pages

- pages.ar/windows/curl.md
- pages.bs/windows/curl.md
- pages.ca/windows/curl.md
- pages.da/windows/curl.md
- pages.es/windows/curl.md
- pages.fr/windows/curl.md
- pages.hi/windows/curl.md
- pages.it/windows/curl.md
- pages.ja/windows/curl.md
- pages.ko/windows/curl.md
- pages.lo/windows/curl.md
- pages.ml/windows/curl.md
- pages.ne/windows/curl.md
- pages.no/windows/curl.md
- pages.pt_PT/windows/curl.md
- pages.ru/windows/curl.md
- pages.sv/windows/curl.md
- pages.th/windows/curl.md
- pages.tr/windows/curl.md
- pages.uk/windows/curl.md
- pages.zh/windows/curl.md
- pages.zh_TW/windows/curl.md
I checked each code history, if there exists a correct version, I will revert the page to that version. Otherwise, I will delete the page.
Unaffected translations: [en](https://github.com/tldr-pages/tldr/blob/main/pages/windows/curl.md), [bn](https://github.com/tldr-pages/tldr/blob/main/pages.bn/windows/curl.md), [de](https://github.com/tldr-pages/tldr/blob/main/pages.de/windows/curl.md), [id](https://github.com/tldr-pages/tldr/blob/main/pages.id/windows/curl.md), [nl](https://github.com/tldr-pages/tldr/blob/main/pages.nl/windows/curl.md), [pl](https://github.com/tldr-pages/tldr/blob/main/pages.pl/windows/curl.md), [pt_BR](https://github.com/tldr-pages/tldr/blob/main/pages.pt_BR/windows/curl.md), [ta](https://github.com/tldr-pages/tldr/blob/main/pages.ta/windows/curl.md)
- **Version of …
> windows/curl: remove wrong auto-generated alias pages

- pages/common/npm-unpublish.md
> npm-unpublish: add page

- pages/common/zapier.md
I'm not sure if we should have a generic page for the command but I have made it just in case
- **Version of the command being documented (if known): 15.16.1**
#14172
> zapier: add page

- pages/linux/faillock.md
> faillock: add non-root commands

- pages/common/zapier-scaffold.md
- **Version of the command being documented (if known): 15.16.1**
#14172
> zapier-scaffold: add page

- pages.ko/common/eol.md
- pages.ko/common/eqn.md
- pages.ko/common/erl.md
- pages.ko/common/ern.md
- pages.ko/common/errno.md
> eol, eqn, erl, ern, errno: add Korean translation

- pages/common/unzip.md
While translating this file (#14231) I discovered incorrect descriptions happened in PR #7997, I offer to fix them:
According to UnZip 6.00 in my Linux
> -O CHARSET  specify a character encoding for DOS, Windows and OS/2 archives  
According to https://manned.org/unzip
> -c     extract files to stdout/screen (``CRT'').  This option is similar to the -p option except that the name of each file is printed as it is extracted
> unzip: fix incorrect descriptions

- pages/common/typst.md
- **Version of the command being documented (if known):** 0.11.0
This PR adds examples for creating a new Typst project via the `typst init` command. Since this is intended to be the entry point of a Typst document, I have decided to promote this example as the top example in the page. In doing so, I have relegated the previous top example to the bottom as I believe that the `typst compile` and `typst watch` commands are more relevant in typical usage.
> typst: add examples for project initialization via template

- pages/common/oxipng.md
- **Version of the command being documented (if known): 9.1.2**
[Oxipng](https://github.com/shssoichiro/oxipng) is a multithreaded lossless PNG/APNG compression optimizer written in Rust. This PR adds a page for commonly-used Oxipng commands. 🌟
> oxipng: add page

- pages/common/lambo-new.md
- pages/common/ncu.md
- pages/common/npm-doctor.md
- pages/common/npm-home.md
- pages/common/npm-name.md
- pages/common/npm-why.md
- pages/common/pnpx.md
> pages/common/*: put `npm` in code ticks

- pages/common/fastfetch.md
See https://github.com/fastfetch-cli/fastfetch/issues/1058
- **Version of the command being documented (if known):** 2.21.3 (x86_64)
> fastfetch: update no logo example

- pages.de/common/vim.md
- pages.es/common/vim.md
- pages.fr/common/vim.md
- pages.id/common/nvim.md
- pages.it/common/nvim.md
- pages.ja/common/vim.md
- pages.nl/common/nvim.md
- pages.pt_BR/common/nvim.md
- pages/common/nvim.md
- pages/common/vim.md
Fix issues mentioned in the #14208 review
> vim, nim: add `:x` and fix inconsistency

- pages/linux/useradd.md
- pages/linux/userdel.md
- pages/linux/usermod.md
Motivation:
When user confronts the command `sudo usermod -aG docker $USER` he may use `tldr` to reveal meaning of `-aG`. This adds hightlighting both long and short option as recommended in [Style guide for Option Syntax](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#option-syntax)
> useradd, userdel, usermod: highlighting both long and short options

- pages/common/az-feedback.md
- pages/common/az-login.md
- pages/common/az-logout.md
Those pages pages/common/az-feedback.md, az-login.md, and az-logout.md have an outdated more info link.
It should use `-` instead of `_` to link the correct page.
> az-feedback, az-login, az-logout: update more info link

- pages/common/az.md
use [https://learn.microsoft.com/cli/azure/reference-index](https://learn.microsoft.com/cli/azure/reference-index) to replace [https://learn.microsoft.com/cli/azure](https://learn.microsoft.com/cli/azure)
The first one is more fit on command info. The second one is more like a whole Azure CLI tool document.
> az: update more info link

- pages.pt_BR/freebsd/chfn.md
- pages.pt_BR/freebsd/chsh.md
- pages.pt_BR/freebsd/ypchfn.md
- pages.pt_BR/freebsd/ypchpass.md
- pages.pt_BR/freebsd/ypchsh.md
Add translation to  `freebsd`  "missing alias" pages.
> pages.pt_BR/freebsd: add Brazilian Portuguese translation

- pages/common/npm-cache.md
> npm-cache: add page

- pages.pt_BR/common/2to3.md
The PT-BR translation was missing the deprecated warning for the 2to3 lib, which has been deprecated since python 3.11 and removed on 3.13.
> 2to3: update Portuguese Brazilian translation

- pages/common/npm-access.md
> npm access: add page

- pages.ko/common/vboxmanage-clonevm.md
- pages.ko/common/vboxmanage-cloud.md
- pages.ko/common/vboxmanage-controlvm.md
- pages.ko/common/vboxmanage-createvm.md
- pages.ko/common/vboxmanage-export.md
- pages.ko/common/vboxmanage-extpack.md
- pages.ko/common/vboxmanage-import.md
- pages.ko/common/vboxmanage-list.md
- pages.ko/common/vboxmanage-movevm.md
- pages.ko/common/vboxmanage-registervm.md
- pages.ko/common/vboxmanage-showvminfo.md
- pages.ko/common/vboxmanage-startvm.md
- pages.ko/common/vboxmanage-unregistervm.md
- pages.ko/common/vboxmanage.md
- pages/common/vboxmanage-startvm.md
> vboxmanage*: add Korean translation

- pages.ko/linux/pipewire.md
- pages.ko/linux/pw-cat.md
- pages.ko/linux/pw-cli.md
- pages.ko/linux/pw-config.md
- pages.ko/linux/pw-dot.md
- pages.ko/linux/pw-dump.md
- pages.ko/linux/pw-link.md
- pages.ko/linux/pw-loopback.md
- pages.ko/linux/pw-metadata.md
- pages.ko/linux/pw-mon.md
- pages.ko/linux/pw-play.md
- pages.ko/linux/pw-profiler.md
- pages.ko/linux/pw-record.md
- pages.ko/linux/pw-top.md
> pipewire,pw*: add Korean translation

- pages.ko/linux/grub-bios-setup.md
- pages.ko/linux/grub-editenv.md
- pages.ko/linux/grub-file.md
- pages.ko/linux/grub-install.md
- pages.ko/linux/grub-mkconfig.md
- pages.ko/linux/grub-reboot.md
- pages.ko/linux/grub-script-check.md
- pages.ko/linux/grub-set-default.md
- pages.ko/linux/grubby.md
> grub*: add Korean translation

- pages.pt_BR/common/2to3.md
For some reason the suggestion of @rffontenelle did not show up to me on [this PR](https://github.com/tldr-pages/tldr/pull/14401#discussion_r1817925259). It was a quite relevant comment and I've merged it before the suggestion was applied. So I am fixing the mistake on this PR and applying his suggestion.
> 2to3: fix Portuguese Brazilian translation

- pages.pt_BR/freebsd/chpass.md
Add missing `freebsd` page: chpass
> chpass: add Brazilian Portuguese translation

- pages.ko/common/kube-capacity.md
- pages.ko/common/kube-fzf.md
- pages.ko/common/kubeadm.md
- pages.ko/common/kubectl-apply.md
- pages.ko/common/kubectl-config.md
- pages.ko/common/kubectl-create.md
- pages.ko/common/kubectl-delete.md
- pages.ko/common/kubectl-describe.md
- pages.ko/common/kubectl-edit.md
- pages.ko/common/kubectl-expose.md
- pages.ko/common/kubectl-get.md
- pages.ko/common/kubectl-label.md
- pages.ko/common/kubectl-logs.md
- pages.ko/common/kubectl-replace.md
- pages.ko/common/kubectl-rollout.md
- pages.ko/common/kubectl-run.md
- pages.ko/common/kubectl-scale.md
- pages.ko/common/kubectl-taint.md
- pages.ko/common/kubectl.md
- pages.ko/common/kubectx.md
- pages.ko/common/kubens.md
- pages.ko/common/kubetail.md
- pages.ko/common/kustomize.md
> kube*, kustomize: add Korean translation

- pages/common/npm-audit.md
> npm audit: add page 

- README.md
- Revert 9dae3aef2eb465b0c30fea1ec1adc027ef95856d since GitHub READMEs doesn't support the tag (we have already verified tldr.sh and the org on Fosstodon so these two are enough IG)
- Minor fixes to wording throughout the page.
---
Btw, should we reorder the similar projects section based on the project's activity? (since some are barely updated)
> cleanup: update README

- pages/common/wireplumber.md
This is a word error in the original text discovered during the review. Correction is needed.
https://github.com/tldr-pages/tldr/pull/14523#issuecomment-2452050953
> wireplumber: fix typo

- pages/common/npm-whoami.md
> npm-whoami: add page

- pages.nl/windows/chromium.md
Adds the Chromium page in Dutch.
> chromium: add Dutch translation

- pages.id/common/rails-db.md
- pages/common/rails-db.md
The new documentation link has far more `rails db` examples than the existing one.
> rails-db: update documentation link

- pages/linux/fatrace.md
- **Version of the command being documented (if known):** 0.17.0
Regarding point one: it is packaged for NixOS, which I think makes it available for MacOS users, but it might be
broken because MacOS does not have a `/proc` filesystem?. No BSD packaged version I have seen.
Could arguably be placed under `common` instead of `linux` directory depending on that.
> fatrace: add page

- pages.es/common/gcc.md
> gcc: add Spanish translation

- pages.es/linux/dnf-config-manager.md
> dnf-config-manager: add Spanish translation

- pages.es/common/btop.md
> btop: update Spanish translation

- contributing-guides/translation-templates/common-arguments.md
We want to make more terse the translation for {{username}} given that we already have more translations targeted to the proposed update for this page
```command
i@h:tldr$ rg '\{\{usuario\}\}' | wc -l
44
```
Among other translations
```command
i@h:tldr$ rg '\{\{nombre_de_usuario\}\}' | wc -l
30
i@h:tldr$ rg '\{\{nombre_usuario\}\}' | wc -l
10
```
Once we merge this, I will be doing a PR to move nombre_de_usuario and nombre_usuario in to usuario in `pages.es`.
> common-arguments: username unification for Spanish translation

- pages/linux/wl-paste.md
wl-paste add primary clipboard flag
> wl-paste: update page

- pages/linux/vgremove.md
- **Version of the command being documented (if known): LVM version: 2.03.11(2) (2021-01-08); Library version: 1.02.175 (2021-01-08)**
> vgremove: add page

- pages/common/yt-dlp.md
- **Version of the command being documented (if known):** 2024.11.04
**Note:** I read through the content and style guides as best I could, but I was still ultimately somewhat confused about whether this sort of example should be completely placeholder'd with abstract descriptions, or whether it's acceptable to use "real" example values, given that the `--playlist-items` option requires a value in a specific format (one or more index-specification strings, separated by commas).
I felt like it would be useful to have an example that showed actual usage of "a specific index", "a range of indices", and "a negative index" (since when I looked for `tldr` examples for `yt-dlp` earlier today, that's what I was hoping to find), so that's the version I'm submitting a PR for.
> yt-dlp: add --playlist-items example

- pages/common/rich.md
> rich: fix line numbers flag typo

- contributing-guides/style-guide.md
The example used to highlight the ambiguity when not using a serial comma was actually using the serial comma. Thus, making the example not helpful. This commit removes this erroneous usage of the comma in the example.
> 14851: Do not use serial comma in negative example

- pages.pt_BR/common/emacs.md
- pages.pt_BR/common/fc-list.md
- pages.pt_BR/common/fc.md
- pages.pt_BR/common/ftp.md
- pages.pt_BR/common/g++.md
- pages.pt_BR/common/gcc.md
- pages.pt_BR/common/gzip.md
- pages/common/gzip.md
> common/e~g*: fix outdated Brazilian Portuguese pages

- pages.es/common/fossil-commit.md
> fossil-commit: add Spanish translation

- pages.es/linux/iptables-restore.md
> iptables-restore: add Spanish translation

- pages.es/common/xzgrep.md
> xzgrep: add Spanish translation

- pages/common/podman-login.md
- **Version of the command being documented (if known):** 5.3.0
> podman-login: add page

- pages/linux/let.md
> let: add page

- pages/linux/hyprctl.md
The reason for this is that the old 'exec {{app}}' is too specific.
'exec' doesn't have to be the dispatcher it could be a lot of other things too.
> hyprctl: fixed false example

- pages/common/fabric.md
- **Version of the command being documented (if known):** v1.4.107
> fabric: add page

- pages/linux/tmt-run.md
- pages/linux/tmt-try.md
- pages/linux/tmt.md
- **Version of the command being documented (if known):** 1.38.0
> tmt, tmt-run, tmt-try: add pages

- pages/common/clear.md
clear -x is equivalent to pressing Ctrl + L.
> clear: fix -x description

- pages.es/common/gh-codespace.md
> gh-codespace: add Spanish translation

- pages/common/pulumi-config.md
> pulumi-config: add page

- pages.es/linux/dmenu.md
> dmenu: add Spanish translation

- pages/common/flexget.md
> flexget: add page

- pages.es/common/podman-run.md
> podman-run: add Spanish translation

- pages/linux/systemd-cryptsetup.md
> systemd-cryptsetup: add page

- pages/common/tex-fmt.md
- **Version of the command being documented (if known):** tex-fmt v0.4.7
> tex-fmt: add page

- pages.de/common/basename.md
- pages.es/common/basename.md
- pages.fr/common/basename.md
- pages.it/common/basename.md
- pages.ko/common/basename.md
- pages.nl/common/basename.md
- pages.pl/common/basename.md
- pages.pt_BR/common/basename.md
- pages.zh/common/basename.md
- pages/common/basename.md
> basename: update documentation link

- pages.es/linux/qm-create.md
> qm-create: add Spanish translation

- pages.es/linux/qm-cloud-init.md
> qm-cloud-init: add Spanish translation

- pages.es/linux/zenity.md
> zenity: add Spanish translation

- pages.es/linux/qm-guest-exec-status.md
> qm-guest-exec-status: add Spanish translation

- pages.es/linux/qm-guest-passwd.md
> qm-guest-passwd: add Spanish translation

- pages/common/gh-skyline.md
> gh-skyline: add page

- pages/linux/emerge.md
---
* Add long options
* Replace `--unmerge` with `--depclean`, as suggested in the Gentoo wiki:
https://wiki.gentoo.org/wiki/Emerge
> Do **not** use the `--unmerge` (`-C`) option (unless its particular behavior is known to be specifically required). This option will remove important packages that are needed for the system to function, without warning.
> emerge: update page

- pages/common/cidr.md
Adds `cidr`, which is available in Homebrew Core, all Debian/Ubuntu repositories, PureOS and more: https://repology.org/project/cidr/packages
> cidr: add page

- pages/linux/grub2-mkpasswd-pbkdf2.md
> grub2-mkpasswd-pbkdf2: add page

- pages/linux/pacman-q.md
- pages/linux/pacman-query.md
> pacman-q: add alias page; pacman-query: update page

- pages/common/tcpreplay.md
```
tcpreplay version: 4.4.4 (build git:v4.4.4) (debug)
Copyright 2013-2022 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Compiled against libdnet: 1.17.0 (libdumbnet)
Compiled against libpcap: 1.10.4
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Packet editing: disabled
Fragroute engine: enabled
Injection method: PF_PACKET send()
Not compiled with netmap
```
> tcpreplay: add page

- pages.es/common/ruff-check.md
> ruff-check: add Spanish translation

- pages/linux/pacman-d.md
- pages/linux/pacman-database.md
> pacman-d: add alias page; pacman-database: update page

- pages.es/linux/distrobox-host-exec.md
> distrobox-host-exec: add Spanish translation

- pages.es/linux/distrobox-export.md
> distrobox-export: add Spanish translation

- pages/linux/pacman.md
> pacman: refresh page

- pages/common/latexpand.md
- pages/common/pnmmercator.md
- pages/common/ppmdraw.md
- pages/common/ppmglobe.md
> ppmdraw, ppmglobe, pnmmercator: add pages

- pages/common/tuc.md
The examples are taken from original repo (https://github.com/riquito/tuc), just a shorter list.
> tuc: add page

- pages/common/case.md
> case: remove unnecessary semicolon

- pages.zh/linux/makepkg.md
- [✔] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [✔] The page(s) have at most 8 examples.
- [✔] The page description(s) have links to documentation or a homepage.
- [✔] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [✔] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [✔] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
> makepkg: add Chinese translation

- pages.id/common/chsh.md
- pages.id/common/echo.md
- pages.id/common/mkdir.md
- pages.id/common/mv.md
- pages.id/common/tldr.md
This PR adds the following new translations, which was organized based on the number of existing (non-Indonesian) translations for each command.
+ `common/chsh` (Translated in 13 languages)
+ `common/echo` (Translated in 14 languages)
+ `common/mkdir` (Outdated, translated in 14 languages)
+ `common/mv` (Outdated, translated in 11 languages)
+ `common/tldr` (Translated in 18 languages)
> chsh, echo, mkdir, mv, tldr: add and improve Indonesian translations

- pages/linux/plasma-apply-colorscheme.md
- pages/linux/plasma-apply-cursortheme.md
- pages/linux/plasma-apply-desktoptheme.md
- pages/linux/plasma-apply-wallpaperimage.md
> plasma-apply-colorscheme, plasma-apply-cursortheme, plasma-apply-desktoptheme, plasma-apply-wallpaperimage: add page

- pages/common/kubeadm.md
After v 1.20 the terminology evolved and the nodes controlling the cluster are now called control nodes
current version stable version is 1.31, but the modified term applies to any version more recent that 1.20 (https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#urgent-upgrade-notes)
> kubeadm: update page

- pages.es/common/filecheck.md
> filecheck: add Spanish translation

- pages.id/common/curl.md
- pages.id/common/docker-ps.md
- pages.id/common/rsync.md
- pages.id/common/tar.md
- pages.id/common/vim.md
- pages.id/linux/ruget.md
- pages.id/windows/choco-info.md
- pages.id/windows/choco.md
- pages.id/windows/cmd.md
- pages.id/windows/scoop-bucket.md
> pages.id/common/*, pages.id/windows/*: add and update Indonesian translations

- pages.pl/netbsd/cal.md
- pages.pl/netbsd/chpass.md
- pages.pl/netbsd/df.md
- pages.pl/netbsd/pkgin.md
- pages.pl/netbsd/sed.md
- pages.pl/netbsd/sockstat.md
This PR adds Polish translations for 6 NetBSD-specific commands that were previously untranslated: `cal`, `chpass`, `df`, `pkgin`, `sed`, and `sockstat`.
> pages.pl/netbsd/*: add Polish translations

- pages.zh/common/npm.md
> npm: add Chinese translation

- pages/common/uv-add.md
- pages/common/uv-tree.md
- pages/common/uv.md
- **Version of the command being documented (if known):** 0.5.13
Add pages for uv subcommands. It's difficult to limit the amount of examples, given the versatility of uv. But I think I narrowed it down to the most important actions.
> uv-{add, tree}: Add page

- pages/common/mpremote.md
- **Version of the command being documented (if known):** 1.24.1
> mpremote: add page

- pages/common/proxify.md
This PR is mainly for clarification related to network interface. The term `network_interface` may be interpreted as the interface name like `eth0`, but the command actually looks for the listening addresses.
> proxify: update page

- pages.es/common/jupyter-lab.md
> jupyter-lab: add Spanish translation

- pages/common/pulumi-config.md
> pulumi-config: add `--stack` example

- pages/common/git-cliff.md
> git-cliff: add page

- pages/common/pulumi-env.md
> pulumi-env: add page

- pages/common/vagrant-box.md
> vagrant-box: add page

- pages.ar/common/7z.md
> 7z: add Arabic translation

- pages/common/rmlint.md
The current examples were rather redundant, so added some more info
> rmlint: include some more advanced flags

- pages.zh/common/cut.md
- pages/common/cut.md
> cut: add chinese translation

- pages.es/common/pocount.md
- pages/common/pocount.md
> pocount: add page & Spanish translation

- pages.ar/common/gpg.md
> gpg: add Arabic translation

- pages/linux/kill.md
`tldr kill` incorrectly displays the `kill -l` command as `kill -L`, as mentioned in #15694.
This PR closes #15694 by fixing the command option to `-l` (lowercase L).
Checklist:
> kill: fix incorrect `-L`  to `-l` option

- pages/common/tput.md
> tput: add examples

- pages/common/print.md
> print: add page

- pages/common/fswatch.md
The `fswatch` command supports the "Removed" event flag, not the "Deleted" event flag.
- **Version of the command being documented (if known):** 1.17.1
> fswatch: fix flag

- pages/linux/fuzzel.md
> fuzzel: add page

- pages.ko/linux/udevadm.md
- pages/linux/udevadm.md
> udevadm: fix wrong reload command flag

- pages.pl/common/git-abort.md
- pages.pl/common/git-add.md
- pages.pl/common/git-alias.md
- pages.pl/common/git-am.md
- pages.pl/common/git.md
This PR adds five Polish translations for `Git`-related commands.
> git, git-*: add Polish translations

- CLIENT-SPECIFICATION.md
The new phrasing does not imply that all options have a short and long form specified in the table.
The motivation for this change is to allow adding options that only have a long form. In particular, I was aiming for such an option in https://github.com/tldr-pages/tldr/pull/15253#discussion_r1965450746 but there was no agreement on whether or not this change would be backwards compatible.
Given that all current entries in the table have both a short and long form, the implication is equivalent for both statements. Thus, this is not a breaking change.
Regardless of whether or not we keep the `-S` and `-E` flags around, I think this rephrasing makes sense so that future additions could use long forms only. Requiring only the long form of an option makes sense to release a new feature …
> CLIENT-SPECIFICATION: rephrase requirement to implement option variants

- contributing-guides/style-guide.md
> style-guide: etc is not a command

- contributing-guides/style-guide.md
I have vscode set so that it removes any trailing whitespace on save. This creates a problem as I have to make sure I don't accidentally push unintended changes.
> style-guide: remove trailing whitespaces

- CLIENT-SPECIFICATION.md
I think that these short versions of `--short-options` and `--long-options` are unintuitive and it might be better to only have the long variants. If users ask for short variants, we can still add them later to the specification. On the other hand, releasing them now means that it will be a breaking change to remove them again.
> CLIENT-SPECIFICATION: remove `-S` and `-E`

- contributing-guides/style-guide.md
> style-guide: clarify placeholders

- contributing-guides/style-guide.md
> style-guide: add keypress documentation instructions.

- CLIENT-SPECIFICATION.md
As discussed in https://github.com/tldr-pages/tldr/pull/15253#discussion_r1957223790 and in the [chatroom](https://matrix.to/#/!zXiOpjSkFTvtMpsenJ:gitter.im/$4J7H1ryHsTkjuKuTgZsk19d7EyAk7Fc6TtDBnoFomYw?via=gitter.im&via=matrix.org&via=one.ems.host) this PR updates the client spec to require clients to support passing common as a platform to the platform flag i.e. `tldr -p common some-command` when a page exists in the native platform too but is a bit different (i.e. non POSIX, etc).
We currently document a lot of POSIX variant pages in common and use the above format to reference pages but it was brought to my notice by a user that some clients (both official and community ones) don't support this behavior yet, this addition ensures that this works the same regardless of the client.
> CLIENT-SPECIFICATION: require support for common as an arg in platform flag

- pages/common/pulumi-stack.md
Made the example more useful. Resource URNs are useful when running other `pulumi` commands such as `pulumi state delete`, `pulumi state move`, and `pulumi state rename`.
> pulumi-stack: update example

- CLIENT-SPECIFICATION.md
relevant issue: #12048
and Matrix comment:
https://matrix.to/#/!zXiOpjSkFTvtMpsenJ:gitter.im/$R-en52Ahyojqz2hzROC2WzBPxZQGTtUAxzBVaIpqhpE?via=gitter.im&via=matrix.org&via=one.ems.host
If the release notes are going to include this notice, I thought it should be updated here too.
> CLIENT-SPECIFICATION: add the date of removal of the old asset website

- CLIENT-SPECIFICATION.md
The client specifications are now in a good shape and ready for release.
Notable changes in this release:
- Added longform/shortform specifications ([#15253](https://github.com/tldr-pages/tldr/pull/15253))
- Specify `common` as a supported platform option ([#15855](https://github.com/tldr-pages/tldr/pull/15855))
- Add the date of removal of the old asset website ([#15862](https://github.com/tldr-pages/tldr/pull/15862))
- Various grammar fixes
> CLIENT-SPECIFICATION: 2.3 release

- pages.de/common/zoxide.md
- pages.fr/common/zoxide.md
- pages.ko/common/zoxide.md
- pages.zh/common/zoxide.md
- pages/common/zoxide.md
> zoxide: remove nonexistent --interactive option

- pages/common/wezterm.md
- **Version of the command being documented (if known):** 
wezterm 0-unstable-2025-01-24
> wezterm: add page

- pages/linux/lxc-attach.md
- pages/linux/lxc-checkconfig.md
- pages/linux/lxc-destroy.md
- pages/linux/lxc-info.md
- pages/linux/lxc-ls.md
- pages/linux/lxc-start.md
- pages/linux/lxc-stop.md
> lxc-{checkconfig, destroy, start, stop, info, attach}: add page; lxc-ls: add an example and sudo

- pages.es/linux/pihole.md
- pages.ko/linux/pihole.md
- pages/linux/pihole.md
Chronometer was removed in v6.0: https://github.com/pi-hole/pi-hole/releases/tag/v6.0
whitelist and blacklist were renamed to allow/denylist some time ago
`restartdns` was also removed, I don't know when.
I replaced `restartdns` with `reloaddns` and added some more examples to the English page. I also removed examples that don't work anymore from translations.
> pihole: update page

- contributing-guides/style-guide.md
I'm seeing a trend that we prefer to use shortform options by themselves less and less
> style-guide: rework option syntax instructions

- pages/common/git-restore.md
By default, "git restore" restores from the index, not from HEAD. See the [git-restore documentation](https://git-scm.com/docs/git-restore):
> By default, if --staged is given, the contents are restored from HEAD, otherwise from the index.
> git-restore: fix default to restore from staging

- pages/common/bacon.md
- Version of command: **bacon 3.11.0**
I was unsure about how to word the descriptions, as this is a tool like `cargo watch`, which will run `cargo` commands when it detects a change in a directory. Is there a better to describe each command?
I also did not add in _every_ command, as they are only minor variations of the 2nd example listed, e.g. `bacon doc`, `bacon clippy`. Should I include those?
> bacon: add page

- pages.es/osx/osascript.md
- pages.id/osx/osascript.md
- pages.ko/osx/osascript.md
- pages.zh/osx/osascript.md
- pages/osx/osascript.md
- [ x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**?
macOS gives an error when running the examples the way they are provided currently:
```
4:5: syntax error: Expected “given”, “in”, “of”, expression, “with”, “without”, other parameter name, etc. but found unknown token. (-2741)
```
This is fixed with this PR.
> osascript: fix single and double quotes

- pages/common/home-manager.md
Remove command test that doesn't exist in the current version (25.05-pre).
Add an explanation for the '--flake' option, useful for anyone using home-manager as a fiake.
- **Version of the command being documented (if known):** 25.05-pre
> home-manager: remove test, add --flake example

- pages/linux/ip-route-list.md
- pages/linux/ip-route-show.md
- pages/linux/ip-route.md
`ip route sh<Tab>` autocompletes to `showdump` whereas `ip route l<Tab>` autocompletes to `list`.
> ip-route*: swap from show to list

- pages/linux/eject.md
> eject: add option placeholders and eject prevention

- contributing-guides/style-guide.md
> style-guide: further clarify option grouping and move keypress order instructions

- pages/common/git-init.md
> git-init: update placeholders

- pages/common/busybox.md
---
I don't think it makes sense to document all BusyBox commands, as they are very similar to the already documented coreutils and util-linux. We'll end up with pages that are almost the same.
Closes #16015.
> busybox: add page

- pages/common/openstack-help.md
- pages/common/openstack-image.md
- pages/common/openstack-server.md
- pages/common/openstack-volume.md
> openstack-{help, image, server, volume}: add page

- pages/common/%.md
- pages/common/ddgr.md
- pages/common/dirs.md
- pages/common/go-vet.md
- pages/common/googler.md
- pages/common/julia.md
- pages/common/logout.md
- pages/common/lp.md
- pages/common/macptopbm.md
- pages/common/mpg321.md
- pages/common/pamenlarge.md
- pages/common/pamoil.md
- pages/common/pamstretch-gen.md
- pages/common/pamstretch.md
- pages/common/pbmpscale.md
- pages/common/pbmreduce.md
- pages/common/rawtopgm.md
- pages/common/readarray.md
- pages/common/return.md
- pages/common/shift.md
- pages/common/wait.md
- pages/linux/dpigs.md
- pages/linux/duperemove.md
- pages/linux/journalctl.md
- pages/linux/logread.md
- pages/linux/netselect.md
- pages/linux/pdftoppm.md
- pages/windows/choice.md
Lowercase `n` is used more often.
```sh
$ rg "\{\{N\}\}" pages -l | wc -l
28
$ rg "\{\{n\}\}" pages -l | wc -l
37
```
> pages/*: use lowercase `n` for integer placeholders

- pages/common/tofu-fmt.md
- pages/common/tofu-output.md
- pages/common/tofu-plan.md
- pages/common/tofu.md
OpenTofu is the open source fork of Terraform.
Pages based on the Terraform ones.
> tofu: add page

- contributing-guides/style-guide.md
> style-guide: remove angle brackets so that it's clear that the instruction is talking about what happens inside angle brackets

- pages/common/kubeseal.md
Closes https://github.com/tldr-pages/tldr/issues/15439
> kubeseal: add page

- pages/linux/rnm.md
> rnm: add page

- pages/common/impacket-rpcdump.md
- pages/common/impacket-rpcmap.md
- pages/common/rpcdump.py.md
- pages/common/rpcmap.py.md
> rpcdump.py, rpcmap.py, impacket-rpcdump, impacket-rpcmap: add page

- pages.ko/common/fastfetch.md
- pages/common/fastfetch.md
- **fastfetch: update repo to fastfetch-cli/fastfetch**
- **fastfetch: add command to display full system info**
- **Version of the command being documented (if known):** 2.40.3
~~I suggest doing a traditional `git merge` rather than a squash merge in order to preserve the commits.~~
**Edit**: was decided against in the review comments
> fastfetch: refresh English and Korean pages

- pages.zh/common/git-cola.md
- pages.zh/common/git-column.md
- pages.zh/common/git-commit-graph.md
> git-{cola, column, commit-graph}: add Chinese translation

- pages.zh/common/git-commit-tree.md
- pages.zh/common/git-commits-since.md
- pages.zh/common/git-contrib.md
> git-{commit-tree, commits-since, contrib}: add Chinese translation

- pages.zh/common/git-cat-file.md
- pages.zh/common/git-changelog.md
> git-{cat-file, changelog}: add Chinese translation

- pages.zh/common/git-check-attr.md
- pages.zh/common/git-check-ignore.md
> git-{check-attr, check-ignore}: add Chinese translation

- pages.zh/common/git-clean.md
- pages.zh/common/git-clear.md
> git-{clear, clean}: add Chinese translation

- pages.zh/common/git-clear-soft.md
- pages.zh/common/git-cliff.md
- pages.zh/common/git-coauthor.md
> git-{clear-soft, cliff, coauthor}: add Chinese translation

- pages/common/ansible.md
- pages/common/az-lock.md
- pages/common/az-storage-blob.md
- pages/common/bzip3.md
- pages/linux/btrfs-restore.md
- pages/linux/swww.md
- pages/linux/urpmi.removemedia.md
> btrfs-restore, swww, urpmi.removemedia, ansible, az-lock, az-storage-blob, bzip3: add or remove mnemonics

- pages/linux/ttyplot.md
Not sure what the purpose of the `{ }` is, but they're definitely working. Odd for the official documentation to instruct to use them.
> ttyplot: fix page

- pages/common/venv.md
This page is interesting in that `venv` doesn't exist as a command, but there is value in keeping the page.
> venv: add alias example

- pages/linux/arptables.md
---
Adds a TLDR page for `arptables`, a tool for managing ARP filtering rules using the nftables backend.
This page includes examples for listing, adding, deleting, flushing rules, setting default policies, and saving configurations.
Based on: https://man7.org/linux/man-pages/man8/arptables-nft.8.html
> arptables: add page

- pages.nl/netbsd/chpass.md
- pages.nl/openbsd/chpass.md
- pages.pl/netbsd/chpass.md
- pages.pl/openbsd/chpass.md
- pages/netbsd/chpass.md
- pages/openbsd/chpass.md
> chpass: use chpass in man page link instead of the alias chsh

- pages/common/impacket-ping.md
- pages/common/impacket-ping6.md
- pages/common/ping.py.md
- pages/common/ping6.py.md
> ping.py, ping6.py, impacket-{ping, ping6}: add page

- pages/linux/virt-viewer.md
- pages/linux/virt-xml.md
> virt-{viewer, xml}: add missing backticks

- pages/linux/lvextend.md
Updated upstream link to a more verbose man page
Closes #15379
> lvextend: fix improper flag usage, add additional example

- pages/common/stty.md
> stty: add size display example

- pages.de/common/nix.md
- pages.ko/common/nix.md
- pages/common/nix.md
Update the "More infos" link to point directly to the online documentation of the `nix` command (instead of the Nix landing page).
Fixes #16274
> nix: update more information link to be more precise

- pages/linux/xhost.md
- Version of the command being documented (if known): 1.0.10
---
Adds a TLDR page for `xhost`, the X server access control utility.
Includes examples for displaying, allowing, denying hosts and users.
> xhost: add page

- .github/CODEOWNERS
- .github/dependabot.yml
---
https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
> To improve reliability and reduce review assignment conflicts, we’re removing the [Dependabot reviewers configuration option](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#reviewers--) on Tuesday, May 27, 2025.
>
> We’re retiring this dependabot.yml configuration option because the functionality overlaps with [GitHub code owners](https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners). This has caused issues in the past, and it’s duplicated effort to maintain the same functionality.
> 
> Moving forward, we recommend relying solely on code …
> dependabot: migrate reviewers to CODEOWNERS file

- pages.es/osx/base64.md
- pages.hi/osx/base64.md
- pages.id/osx/base64.md
- pages.it/osx/base64.md
- pages.ko/osx/base64.md
- pages.nl/osx/base64.md
- pages.pt_BR/osx/base64.md
- pages.zh/osx/base64.md
- pages/osx/base64.md
The documentation link for the OSX version of `base64` is outdated. Instructions for `base64` have been merged into the [bintrans](https://keith.github.io/xcode-man-pages/bintrans.1) page.
> base64: update documentation link

- pages.de/osx/pbpaste.md
- pages.es/osx/pbpaste.md
- pages.id/osx/pbpaste.md
- pages.ko/osx/pbpaste.md
- pages.th/osx/pbpaste.md
- pages.zh/osx/pbpaste.md
- pages/osx/pbpaste.md
Documentation for `pbpaste` is combined with `pbcopy`'s
> pbpaste: update docs link

- pages.de/common/nix.md
- pages.ko/common/nix.md
Aligns the German and Korean translations with the English original. Addresses the bot comments from https://github.com/tldr-pages/tldr/pull/16286#issuecomment-2835285356.
> - The page `pages.de/common/nix.md` is outdated, based on number of commands, compared to the English page.
> - The page `pages.ko/common/nix.md` is outdated, based on the command contents itself, compared to the English page.
- **Version of the command being documented (if known):** nix (Nix) 2.28.2
> nix: align examples of translations

- pages.nl/common/$.md
- pages.nl/common/,.md
- pages.nl/common/b2sum.md
- pages.nl/common/basenc.md
- pages.nl/common/gcrane-help.md
- pages.nl/linux/distrobox-host-exec.md
- pages.nl/linux/tftp.md
> pages.nl/*: translate 'command' like 'commando'

- pages/common/impacket-ntfs-read.md
- pages/common/ntfs-read.py.md
> ntfs-read.py, impacket-ntfs-read: add page

- pages/common/ipmitool.md
- pages/freebsd/ipmitool.md
- pages/linux/distrobox-export.md
- pages/linux/ipmitool.md
> pages/*: fix colon typo

- pages.ko/common/rustup-toolchain.md
- pages/common/rustup-toolchain.md
Was not working for list and link without `toolchain` before it. Seems to have worked for install and uninstall as a shortcut, but not really how the commands of the toolchain subcommand are supposed to look.
- **Version of the command being documented (if known):** rustup 1.28.1 (2025-03-05)
> rustup-toolchain: fix missing toolchain subcommand in all commands

- pages/common/mullvad.md
The `mullvad account get` command provides essential information for Mullvad VPN CLI users by displaying both the account expiration date and the current device's auto-generated name in a single command.
This addition is particularly valuable for users who:
- Need to quickly check when their VPN subscription expires
- Want to identify their current device's name when managing multiple devices
- Are approaching Mullvad's 5-device limit and need to make informed decisions about which devices to keep connected
The command complements the existing `mullvad status` command by providing account-specific information rather than just connection status.
```
$ mullvad account get
Account number: XXXX XXXX XXXX XXXX
Paid until: 2026-03-15
Device: Monkey Ship
```
- **Version of the command being …
> mullvad: add example

- pages.de/common/bash.md
- pages.fr/common/bash.md
- pages.it/common/bash.md
- pages.ko/common/bash.md
- pages.pl/common/bash.md
- pages.pt_BR/common/bash.md
- pages.zh/common/bash.md
- pages.zh_TW/common/bash.md
This PR makes the information link consistent among all `bash.md` pages.
> bash: update documentation links

- pages.nl/common/rg.md
> rg: update Dutch translation

- pages.de/common/ansible.md
- pages.fr/common/ansible.md
- pages.id/common/ansible.md
- pages.it/common/ansible.md
- pages.ko/common/ansible.md
- pages.pt_BR/common/ansible.md
- pages.zh/common/ansible.md
> ansible: update more information link

- pages/common/reuse.md
- **Version of the command being documented (if known):** 5.0.2
---
Just used this in one of the projects I maintain, so figured I'd document it here.
TL;DR: It's a tool by the FSFE for managing license compliance, particularly useful when a project pulls in code from a variety of sources and so a single `LICENSE` file in the project root isn't good enough to properly denote the license of all distributed files.
> reuse: add page

- pages.ko/common/sqlmap.md
- pages/common/sqlmap.md
> sqlmap: remove extra spaces in english page, add option placeholders in korean page

- pages/common/zoxide.md
This PR removes the aliases `za`, `zq`, `zr`, that have not been bundled with zoxide for years.
It also adds some new shells supported by the current version of zoxide.
> zoxide: refresh page

- pages/common/grep.md
`without-match` must be provided, so remove `{{` to make output simpler to read
> grep: with-match

- pages/linux/kde-builder.md
> kde-builder: add hint for desktop compilation

- pages/common/mise.md
Adds plugin options syntax.
E.g. for java release type:
```sh
mise use java[release_type=ea]@openjdk-25
```
> mise: adds plugin options example

- pages/common/ntp-ctl.md
> ntp-ctl: add page

- pages/common/git-for-each-ref.md
For https://github.com/tldr-pages/tldr/issues/3953
> git-for-each-ref: add page

- pages.id/common/git-authors.md
- pages.ko/common/git-authors.md
- pages.zh/common/git-authors.md
> git-authors: update more information links

- pages/linux/fwupdmgr.md
- pages/linux/fwupdtool.md
> fwupdtool: add page, fwupdmgr: refer to fwupdtool and add example

- pages/common/duckdb.md
- **Version of the command being documented (if known):** 1.3.0
This PR add a new CLI feature introduced in DuckDB 1.3.0 (https://duckdb.org/2025/05/21/announcing-duckdb-130).
> duckdb: add direct querying option

- pages/common/exo-compute-block-storage.md
- pages/common/exo-compute-instance.md
- pages/common/exo-compute-sks.md
- pages/common/exo-compute.md
- pages/common/exo-dbaas.md
- pages/common/exo-iam.md
- pages/common/exo-storage.md
- pages/common/exo.md
> exo*: add pages

- pages.nl/common/getnpusers.py.md
> GetNPUsers.py: translate placeholders to Dutch

- pages/common/doggo.md
Although the previous one is also referred to by the GitHub repository itself, it does not exist.
> doggo: update More Info link

- pages/linux/setfacl.md
The shorthand for --remove-all is -b, and not -X
setfacl 2.3.2
> setfacl: fix incorrect shorthand argument for --remove-all

- pages/common/ssh-keygen.md
Users would mostly install ssh-keys into servers after generating them
using ssh-keygen. Provide hint for ssh-copy-id in the current page.
Inspiration:
I used ssh-keygen to generate a key pair, and then I wanted to copy the public key. But i didn't know about ssh-copy-id, so after some fiddling around, i ultimately searched for it using the internet. I think it would be helpful to have a hint about ssh-copy-id in the ssh-keygen page, given that a common workflow is to generate a key pair and then copy the public key to a server.
OpenSSH_10.0p2, OpenSSL 3.5.0 8 Apr 2025
> ssh-keygen: provide hint for ssh-copy-id

- pages/common/rustfmt.md
- **Version of the command being documented (if known): 1.8.0**
> rustfmt: add examples

- pages/linux/mktemp.md
I wanted to use a similar feature where i wanted to create a temporary filename but not create the file yet. After a bit of searching, i realised `mktemp` had that built-in functionality. So, i thought it would be a good idea to add this as an example to the `mktemp` page.
Translations required.
mktemp (GNU coreutils) 9.7
Copyright (C) 2025 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Jim Meyering and Eric Blake.
> mktemp: document dry-run flag

- pages/linux/intercept.md
- pages/linux/mux.md
- pages/linux/udevmon.md
- pages/linux/uinput.md
> intercept, mux, udevmon, uinput: prune info link

- pages/common/k3s.md
> k3s: add page

- pages.ko/common/wget2.md
> wget2: update outdated Korean translation

- pages/common/p7zip.md
> p7zip: fix typo for --keep flag

- pages/common/prowler-aws.md
- pages/common/prowler-azure.md
- pages/common/prowler-gcp.md
- pages/common/prowler-github.md
- pages/common/prowler-kubernetes.md
- pages/common/prowler-m365.md
- pages/common/prowler.md
Added a new main page for prowler, a cloud security assessment tool, as well as subcommand pages for the following providers:
- prowler-aws
- prowler-azure
- prowler-gcp
- prowler-kubernetes
- prowler-m365
- prowler-github
Issue: #13453
> prowler, prowler-{aws,azure,gcp,kubernetes,m365,github}: add pages

- pages/windows/msedge.md
- [x ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
> msedge: remove '=' from long options

- contributing-guides/style-guide.md
> style-guide: be explicit on how to handle options and arguments that don't have a space in between

- pages/common/bunzip2.md
> bunzip2: add page

- pages/common/bitcoind.md
- pages/common/bpython.md
- pages/common/crane-index-append.md
- pages/common/doppler.md
- pages/common/flexget.md
- pages/common/frps.md
- pages/common/immich-go.md
- pages/common/kubie.md
- pages/common/piper.md
- pages/common/pre-commit.md
- pages/common/rage.md
- pages/common/secrethub.md
> common/*: use "configuration" instead of "config"

- pages/common/bzip2recover.md
> bzip2recover: add page

- pages/linux/fakeroot.md
- pages/linux/flameshot.md
- pages/linux/fprintd-verify.md
- pages/linux/fsck.md
- pages/linux/fuser.md
> linux/f*: add option placeholders and mnemonics

- pages/linux/a2disconf.md
- pages/linux/a2dismod.md
- pages/linux/a2dissite.md
- pages/linux/a2enconf.md
- pages/linux/a2enmod.md
- pages/linux/a2ensite.md
- pages/linux/aa-complain.md
- pages/linux/aa-enforce.md
- pages/linux/abroot.md
- pages/linux/add-apt-repository.md
- pages/linux/alien.md
- pages/linux/alpine.md
- pages/linux/apt-add-repository.md
- pages/linux/ark.md
- pages/linux/auracle.md
> linux/a*: add option placeholders

- pages/linux/apt.md
- **Version of the command being documented (if known):** `apt 2.7.14 (amd64)`
---
The descriptions on the page looked clunky so I took the liberty to revise most of them.
I couldn't find a mention of multiline commands in guidelines. ~~If this would break anything, please feel free to edit this PR~~ yes it breaks, thanks @tldr-bot :]
Two major fixes are:
- `--names-only` gives error since the flag is actually from [`apt-cache`](https://linux.die.net/man/8/apt-cache). Apt instead uses the `apt list` subcommand
- Removed `apt list` entry as nobody would want to dump the entire apt repository into their terminal
> apt: revised all descriptions

- pages/linux/hlint.md
- pages/linux/homectl.md
- pages/linux/id3v2.md
- pages/linux/img2txt.md
- pages/linux/inotifywait.md
- pages/linux/instaloader.md
- pages/linux/ipcmk.md
> linux/{h, i}*: add option placeholders

- pages/common/elasticsearch-keystore.md
> elasticsearch-keystore: add page

- pages/linux/dnf-install.md
> dnf-install: add page

- pages/linux/run-mailcap.md
> run-mailcap: conform with style guide

- pages/common/jj-absorb.md
This change makes it clear that running `jj absorb` on a revision will only move eligible and unambiguous changes to ancestral revisions, not just a blanket "move all changes".
See also: https://github.com/tldr-pages/tldr/pull/17129#discussion_r2190398185
- **Version of the command being documented (if known):** v0.30.0
> jj-absorb: clarify move semantics

- pages/linux/minicom.md
> minicom: add more examples

- MAINTAINERS.md
Hey, as I explained in #17214, I'm stepping back as a repository collaborator.
Closes #17214
> MAINTAINERS: remove @marchersimon as collaborator

- pages/common/pulumi-plugin.md
- **Version of the command being documented (if known): v3.181.0**
> pulumi-plugin: add page

- pages/common/spotify_player.md
> spotify_player: add page

- pages/common/aws-eks.md
- pages/common/coproc.md
- pages/common/d8.md
- pages/common/dropdb.md
- pages/common/for.md
- pages/common/highlight.md
- pages/common/hyperfine.md
- pages/common/jello.md
- pages/common/kubetail.md
- pages/common/linode-cli-linodes.md
- pages/common/mamba-repoquery.md
- pages/common/phpcbf.md
- pages/common/quarto.md
- pages/common/swig.md
- pages/common/trdsql.md
- pages/common/vagrant-validate.md
- pages/linux/keyd.md
- pages/linux/pstoedit.md
- pages/linux/rpicam-still.md
- pages/linux/sfdisk.md
- pages/linux/unzipsfx.md
These were found by running `grep -r {{{` and `grep -r }}}` in the project 
#17107
Even more found with 
`find . -type f -print0 | xargs -0 awk '{ o=gsub(/{/,"&"); c=gsub(/}/,"&"); if(o!=c) print FILENAME ": " $0 }'`
`find . -type f -print0 | xargs -0 awk '{ o=gsub(/\[/,"&"); c=gsub(/\]/,"&"); if(o!=c) print FILENAME ": " $0 }'`
`find . -type f -print0 | xargs -0 awk '{ o=gsub(/\(/,"&"); c=gsub(/\)/,"&"); if(o!=c) print FILENAME ": " $0 }'`
`find . -type f -print0 | xargs -0 awk '{ q=gsub(/"/,"&"); if(q % 2 != 0) print FILENAME ": " $0 }'`
Also found an interesting case where a `<` was not inside `" "` with this
`find . -type f -print0 | xargs -0 awk '{ o=gsub(/</,"&"); c=gsub(/>/,"&"); if(o!=c) print FILENAME ": " $0 }' | cut -d : -f 2- | grep -v '\.' | grep "[a-zA-Z]<"`
> *: fix curly brace syntax, nested placeholders and mismatched brackets

- pages/common/in-toto-run.md
- pages/common/ippeveps.md
- pages/common/pueue-add.md
- pages/common/x8.md
- pages/linux/pasuspender.md
- pages/linux/screenkey.md
> in-toto-run, pueue-add, x8, ippeveps, pasuspender, screenkey: fix nested placeholders

- pages.ar/common/fzf.md
- pages.es/common/fzf.md
- pages.fr/common/fzf.md
- pages.ko/common/fzf.md
- pages.tr/common/fzf.md
- pages.zh/common/fzf.md
> fzf: add long and short options to commands in translations

- pages/common/minecraft.md
- pages/linux/counter-strike-2.md
- pages/linux/factorio.md
- pages/linux/terraria.md
Since the title is already the game name instead of the binary name, I think it should be properly capitalized. Only exception I took was openttd since the game can be installed with a package manager to your $PATH and the binary matches the filename of the page.
> factorio, terraria, counter-strike-2, minecraft: capitalize title

- pages/linux/trace-cmd-list.md
- pages/linux/trace-cmd-record.md
- pages/linux/trace-cmd-report.md
- pages/linux/trace-cmd.md
> trace-cmd-{list, record, report}: add page, tracecmd: refresh page

- pages/linux/btrfs-balance.md
- pages/linux/btrfs-check.md
- pages/linux/btrfs-device.md
- pages/linux/btrfs-filesystem.md
- pages/linux/btrfs-inspect-internal.md
- pages/linux/btrfs-property.md
- pages/linux/btrfs-rescue.md
- pages/linux/btrfs-restore.md
- pages/linux/btrfs-scrub.md
- pages/linux/btrfs-subvolume.md
- pages/linux/btrfs-version.md
- pages/linux/btrfs.md
> btrfs: add aliases

- pages/common/gst-inspect-1.0.md
Found with
```
grep -r '`' | grep 'md:`' | sed "s/-/ /g" | grep -vEi '/([a-zA-Z0-9+_ \.\^,!~%\[]+)\.md:`.*\1' | grep -v tldr | grep -v "<" | grep -v "pacman" | grep -vEi ' ([a-zA-Z0-9+_ \.]+)\.md:`.*\1\]}}' | cut -d ":" -f 1 | uniq -u
```
> gst-inspect-1.0: fix typo

- pages.de/common/docker-login.md
- pages.fr/common/docker-login.md
- pages.ko/common/docker-login.md
- pages.pt_BR/common/docker-login.md
> docker-login: add long & short options to commands in translations

- pages/common/k9s.md
Not found in official documentation. Only found in `k9s -h`
> k9s: add short options

- pages/common/unlzma.md
- pages/linux/aplay.md
- pages/linux/wol.md
> aplay, wol, unlzma: remove `=` and add short options

- pages/common/speedtest.md
> speedtest: remove `=` and add short options

- pages/common/cli53.md
> cli53: add proper option placeholders and fix example link

- pages.cs/linux/ip.md
- pages.cs/linux/nmcli-device.md
- pages.cs/linux/nmcli-general.md
- pages.cs/linux/nmcli-monitor.md
- pages.cs/linux/nmcli.md
> ip, nmcli, nmcli-device, nmcli-general, nmcli-monitor: add Czech translation

- pages/linux/apt-install.md
> apt-install: add page

- pages/common/slocate.md
> slocate: add page

- pages.ko/linux/pw-link.md
- pages.pt_BR/linux/pw-link.md
- pages/linux/pw-link.md
`pw-link` pages listed `--ids` as availabe option, however actual option is spelled `--id`. Using `--ids` fails with:
```
$ pw-link --links --ids
pw-link: unrecognized option '--ids'
```
- **Version of the command being documented (if known):** `1.4.6`
> pw-link: fix typo in id option

- pages/linux/flock.md
- **Version of the command being documented (if known):** flock from util-linux 2.41.1
Changes:
- don't use `{{[-c|--command]}}` since that didn't allow passing arguments to the command being executed, so why use it?
- improve wording for clarity (previous one was so misleading that the man page was much clearer at that point, plus the desc for `--nonblock` was straight up lying due to being the other way around than how it actually works)
- added missing form `--nb` to `--nonblock`
- changed `{{error_code}}` to `{{123}}` to make it clear how the exit code should be specified (that it's not some kind of text code)
- added a pretty useful/common example with wait/timeout for lock before exiting and giving up
- added a practical example with actual command (tar, you don't want to run two …
> flock: improvements and fix of misleading wording

- pages.cs/common/avrdude.md
- pages.cs/common/cmatrix.md
- pages.cs/common/esptool.py.md
- pages.cs/common/i3.md
- pages.cs/common/picotool.md
> avrdude, picotool, esptool.py, i3, cmatrix: add Czech translation

- pages/windows/dir.md
Add "dir /o:d" to the cheat sheet. It is quite useful for creating sort/order by size, date, name, etc.
> dir: add sort example

- pages/linux/grub-install.md
Seems to be possible to do this with less effort.
> grub-install: add simplified example, sudo, and help

- pages/common/crane-index-filter.md
- pages/common/crane-mutate.md
- pages/common/crane.md
- pages/common/gcrane.md
- pages/linux/aide.md
Found with ``grep -r {{ | grep -v '`'``
> *: remove placeholders from descriptions

- pages/common/elasticsearch-users.md
The final command in the list of elasticsearch commands. Related #16522 
> elasticsearch-users: add page

- pages.pt_BR/common/history.md
- pages.pt_BR/common/htop.md
- pages.pt_BR/common/id.md
- pages.pt_BR/common/join.md
- pages.pt_BR/common/kill.md
- pages.pt_BR/common/magick-convert.md
- pages.pt_BR/common/man.md
- pages/common/magick-convert.md
> common/h~m*: fix outdated Brazilian Portuguese pages

- pages/linux/lsfd.md
> lsfd: remove leading slash in file path

- pages/linux/pct-clone.md
- pages/linux/pct-template.md
- pages/linux/pve-firewall.md
- pages/linux/pveam.md
- pages/linux/pvecm.md
- pages/linux/pvesh.md
- pages/linux/pvesm.md
- pages/linux/pveum.md
- pages/linux/qm-disk-rescan.md
- pages/linux/qm-list.md
- pages/linux/qm-terminal.md
> pve*, qm*: add missing option placeholders

- pages/linux/partclone.md
> partclone: fix manpage link

- pages/linux/systemd-cgtop.md
One of the few cases in systemd tools where `=` is a must and I didn't test it.
> systemd-cgtop: fix page

- pages/common/cbonsai.md
> cbonsai: add examples

- pages/linux/systemctl-status.md
> systemctl-status: add page

- pages/cisco-ios/ip.md
> ip: add page

- pages/common/git-blame.md
> git-blame: add an example to blame similar to github UI

- pages/cisco-ios/line.md
Removed the tracking for chatgpt.com in the documentation URL
> line: update more information link

- pages/cisco-ios/show.md
Changed the `s` command shortcut to `sh` in the examples since using only `s` produce an error :
```cisco
Switch#s ip interface brief
% Ambiguous command: "s ip interface brief"
```
Working example with `sh` :
```cisco
Switch#sh ip interface brief
Interface              IP-Address      OK? Method Status                Protocol 
FastEthernet0/1        unassigned      YES manual down                  down
...
```
This has been tested on a Cisco Switch Catalyst 2960 and a Cisco Router 1941
> show: fix example

- pages/common/wget.md
This PR updates the "More information" link in the `wget` page to point to the official GNU Wget manual instead of the previous reference.  
This ensures users always get the most accurate and up-to-date documentation directly from the official source.
> wget: update 'More information' link to official manual

- pages/common/cpio.md
- pages/common/g++.md
- pages/common/gcal.md
- pages/common/gcc.md
- pages/common/gdb.md
- pages/common/guile.md
- pages/common/help2man.md
- pages/common/lzip.md
- pages/common/m4.md
- pages/common/parallel.md
- pages/common/tar.md
- pages/common/units.md
- pages/linux/zile.md
> GNU software: use direct documentation link

- pages/cisco-ios/transport.md
Added an example that show how to configure the line communication protocol to Telnet. Even if Telnet isn't recommended today, one may want to know how to configure it for specific or testing purpose.
> transport: add example

- pages/linux/systemd-cat.md
> systemd-cat: add examples

- pages/common/mitmproxy.md
- **Version of the command being documented (if known): 11.0.2**
> mitmproxy: add examples

- pages.it/common/bash-it.md
* **Version of the command being documented (if known):** N/A
This PR adds the Italian translation for the [`[bash-it](https://bash-it.readthedocs.io/en/latest/)`](https://bash-it.readthedocs.io/en/latest/) command.
> bash-it: add Italian translation

- pages.it/linux/dkms.md
- Added `pages.it/linux/dkms.md` with Italian translation.
- Verified that examples remain consistent and functional.
> dkms: add italian translation

- pages.it/linux/aur.md
- Added `pages.it/linux/aur.md` with Italian translation.
- Verified that examples remain consistent and functional.
> aur: add Italian translation

- pages.cs/linux/bluetoothctl.md
> bluetoothctl: Minor Czech word corrections

- pages/common/alacritty.md
- **Version of the command being documented (if known):** 0.15.1 (0c405d53)
```
$ alacritty --live-config-reload --config-file ~/.config/alacritty/alacritty.toml
error: unexpected argument '--live-config-reload' found
Usage: alacritty [OPTIONS] [COMMAND]
For more information, try '--help'.
```
> alacritty: remove nonexistant command

- pages.nl/common/fzf.md
- pages/common/fzf.md
- **Version of the command being documented (if known):** 0.65.1 (e5cd7f0a)
The last example doesn't work for me without the `\`, but I'm not sure if this is the case on all systems.
> fzf: update page and add Dutch translation

- pages.nl/linux/iwctl.md
- pages/linux/iwctl.md
> iwctl: update page and add Dutch translation

- pages.it/linux/rpm-ostree.md
- Added `pages.it/linux/rpm-ostree.md` with Italian translation.
> rpm-ostree: add Italian translation

- pages.it/common/pwd.md
- Added `pages.it/common/pwd.md` with Italian translation.
> pwd: add Italian translation

- pages.it/linux/retroarch.md
- Added `pages.it/linux/retroarch.md` with Italian translation.
> retroarch: add italian translation

- pages.it/linux/rankmirrors.md
- Added `pages.it/linux/rankmirrors.md` with Italian translation.
> rankmirrors: add Italian translation

- pages/common/uname.md
- **Version of the command being documented (if known):** 9.7
- fixed a minor typo in `uname` command in the `common` page.
> uname: fix typo

- pages/linux/systemctl-cat.md
- pages/linux/systemctl-disable.md
- pages/linux/systemctl-edit.md
- pages/linux/systemctl-enable.md
- pages/linux/systemctl-mask.md
- pages/linux/systemctl-restart.md
- pages/linux/systemctl-start.md
- pages/linux/systemctl-status.md
- pages/linux/systemctl-stop.md
> systemctl-*: add user unit examples

- pages.es/common/trufflehog.md
- pages.ko/common/trufflehog.md
> trufflehog: remove unnecessary `=` sign

- pages/linux/hyprshot.md
- **Version of the command being documented (if known): 1.3.0**
Let me know if I can improve the wording or reduce the number of examples by showing e.g. `freeze` and `--clipboard` in the earlier examples.
> hyprshot: add page

- pages/common/hexyl.md
> hexyl: remove unsupported examples

- pages/common/poetry-env.md
Changing `virtualenv` -> `virtual environment` per discussion on https://github.com/tldr-pages/tldr/pull/17960#pullrequestreview-3197950104
> poetry-env: change virtualenv verbiage

- contributing-guides/style-guide.md
I'm looking for feedback on where this might not apply and what else to add to the list.
> style-guide: add argument order suggestion

- pages/linux/lvmpolld.md
> lvmpolld: add page

- pages/common/sudo.md
In PR #18104, it was pointed out that page descriptions should use the imperative mood (e.g., "Execute" instead of "Executes").
This PR applies that style fix to the English page for sudo.
> sudo: Use imperative mood in description

- pages/osx/duti.md
Added command to find bundle ID using AppleScript. Because i have to google it every time and tldr is for me the solution to not have to google irregularly used commands.
> duti: add reference to osascript

- pages/linux/systemctl-bind.md
Addresses the part of the Issue #17684
> systemctl-bind: add page

- pages/common/tail.md
This PR fixes a minor inconsistency in the description for the last example on the tail page.
The description used the placeholders num, file, and n, while the code example below uses count, path/to/file, and seconds.
This change harmonizes the description with the code, making the page clearer and easier to translate accurately.
> tail: harmonize description placeholders with code

- pages/common/agg.md
> agg: add --font-size example

- pages/common/cargo-deb.md
> cargo-deb: add page

- pages/common/cargo-msrv.md
> cargo-msrv: add page

- pages/common/hg.md
Makes the `hg` page very similar to `git`, as described in #18255.
> hg: update page

- pages.es/linux/flex.md
Added documentation for the flex lexical analyzer generator.
x
> flex: add Spanish translation

- pages/common/htop.md
> htop: add readonly example

- pages.de/common/nix-collect-garbage.md
- pages.es/common/nix-collect-garbage.md
- pages.ko/common/nix-collect-garbage.md
- pages/common/nix-collect-garbage.md
It works without `sudo` on a single-user installation of Nix.
> nix-collect-garbage: remove `sudo`

- pages.it/linux/nixos-container.md
- pages.it/linux/nixos-option.md
- pages.it/linux/nixos-rebuild.md
> nixos-*: add italian translation

- pages/common/cargo-verify-project.md
The previous more info link redirects to https://doc.rust-lang.org/cargo/commands/deprecated-and-removed.html.
> cargo-verify-project: add deprecation notice

- pages/common/cargo-binstall.md
> cargo-binstall: add page

- pages.es/common/whatweb.md
- pages.ko/common/vela.md
- pages/common/vela.md
- pages/common/whatweb.md
Replaced broken links (vela, whatweb) as of https://github.com/tldr-pages/tldr-maintenance/issues/129 with updated, working links.
> vela, whatweb: replace broken links

- contributing-guides/style-guide.md
As was discussed in https://github.com/tldr-pages/tldr/pull/18484#discussion_r2404785339, it is hard to differentiate between positional arguments and options with arguments when they were mixed like this. This new order does away with that issue.
> style-guide: refine argument order

- pages/common/pg_archivecleanup.md
> pg_archivecleanup: add page

- pages/common/pg_walsummary.md
> pg_walsummary: add page

- pages/common/curl.md
It's unclear what "a resource" refers to here, plainly stating that the certificate and key are for the request makes this more clear.
> curl: improve wording

- pages/common/vacuumdb.md
> vacuumdb: add page

- pages.cs/common/st-flash.md
> st-flash: add Czech translation

- pages/linux/ip-monitor.md
- pages/linux/rtmon.md
> ip-monitor, rtmon: add page

- pages/common/tesseract.md
- **Version of the command being documented (if known):** 5.5.1
> tesseract: update page

- pages/linux/grub-mkrescue.md
- **Version of the command being documented (if known):** grub-mkrescue (GRUB) 2:2.12.r359.g19c698d12-1
Part of #8080
> grub-mkrescue: add page

- pages/linux/semodule.md
Adds documentation for the semodule command.
- **Version of the command being documented (if known):**  libsemanage-3.7-3.fc41.x86_64
> semodule: add page

- pages/linux/sealert.md
Adds documentation for the sealert command.
- **Version of the command being documented (if known):**  setroubleshoot-server-3.3.35-4.fc41.x86_64
> sealert: add page

- pages/linux/newrole.md
Adds documentation for the newrole command.
- **Version of the command being documented (if known):**  policycoreutils-newrole-3.7-8.fc41.x86_64
> newrole: add page

- pages/linux/run_init.md
Adds documentation for the run_init command.
> run_init: add page

- pages/linux/semanage-interface.md
Adds documentation for the semanage-interface command.
- **Version of the command being documented (if known):**  policycoreutils-python-utils-3.7-8.fc41.noarch
> semanage-interface: add page

- pages/linux/setfiles.md
Adds documentation for the setfiles command.
- **Version of the command being documented (if known):**  policycoreutils-3.7-8.fc41.x86_64
> setfiles: add page

- pages/common/kubectl-top.md
- **Version of the command being documented (if known):** -
This PR is related to the issue #17606 (Let's document kubectl)
> kubectl-top: add page

- pages/common/pg_test_fsync.md
> pg_test_fsync: add page
