pages/linux/qm-import-disk.md
Ref: https://github.com/tldr-pages/tldr/pull/11730#issuecomment-1856114318
=> qm-import-disk: match with translations

pages.nl/linux/qm-move-disk.md
=> qm-move-disk: update Dutch translation

pages.es/osx/csrutil.md
=> csrutil: fix Spanish typo

pages/common/pnmshear.md
=> pnmshear: add page

pages/common/pnmsmooth.md
=> pnmsmooth: add page

pages/common/pampop9.md
=> pampop9: add page

pages/common/pnmtile.md
=> pnmtile: add page

pages.ko/common/adscript.md
=> adscript: add Korean translation

pages/common/pnmtoddif.md
=> pnmtoddif: add page

pages.ko/common/audacious.md
=> audacious: add Korean translation

pages.es/windows/nvm.md
=> nvm: update Spanish translation

pages.pt_BR/common/cupsctl.md, pages.pt_BR/common/lpadmin.md, pages.pt_BR/common/lpoptions.md, pages.pt_BR/common/lpq.md, pages.pt_BR/common/lprm.md, pages/common/cupsctl.md, pages/common/lpadmin.md, pages/common/lpoptions.md, pages/common/lpq.md, pages/common/lprm.md
=> cupsctl, lpq, lprm, lpadmin, lpoptions: add pages

contributing-guides/style-guide.md
@isaacvicente I've drafted the rule you mentioned in #11745, based on a quite similar rule written for French translators and on your comments. What do you think?
=> style-guide: add Portuguese specific rules

pages.pt_BR/linux/pw-mon.md, pages/linux/pw-mon.md
=> pw-mon: add page and pt_BR translation

pages.es/osx/m.md
=> m: fix verb in Spanish translation

pages.nl/common/install-nodeversion.md
=> install-nodeversion: add Dutch translation

pages/common/fiascotopnm.md, pages/common/pnmtofiasco.md
=> fiascotopnm, pnmtofiasco: add pages

pages.nl/linux/qm-move_disk.md
=> qm-move-disk: add Dutch alias page

pages.nl/common/objdump.md
=> objdump: add Dutch translation

pages.nl/common/strings.md
=> strings: add Dutch translation

pages.nl/common/pamtowinicon.md
=> pamtowinicon: add Dutch translation

pages.nl/common/winicontopam.md
=> winicontopam: add Dutch translation

pages.nl/common/pamtotiff.md
=> pamtotiff: add Dutch translation

pages.nl/common/pamtotga.md
=> pamtotga: add Dutch translation

pages.nl/common/pbmtoxbm.md
=> pbmtoxbm: add Dutch translation

pages.nl/common/xzmore.md
=> xzmore: add Dutch translation

pages.nl/common/netlify.md
=> netlify: add Dutch translation

pages.nl/common/pamoil.md
=> pamoil: add Dutch translation

pages.es/common/gradle.md
=> gradle: update Spanish translation

scripts/pdf/build-pdf.sh
=> Revert "build-pdf: only build changed folders since last commit"

pages/common/nixpkgs-review.md
=> nixpkgs-review: add page

pages/common/vboxmanage-movevm.md
=> vboxmanage-movevm: add page

pages/common/pamflip.md, pages/common/pnmcolormap.md, pages/common/pnmquant.md, pages/common/pnmremap.md, pages/common/pnmrotate.md, pages/common/ppmquant.md
=> pamflip, pnmcolormap, pnmquant, pnmremap, pnmrotate, ppmquant: add pages

pages.pt_BR/common/python.md, pages.zh/common/python.md, pages/common/python.md
Will check other languages as well!
=> python: remove placeholders

pages.nl/common/remove-nodeversion.md, pages.nl/common/set-nodeinstalllocation.md, pages.nl/common/set-nodeversion.md
=> node: add Dutch translation

pages.nl/common/ptpython.md
=> ptpython: add Dutch translation

pages.nl/linux/resolvectl.md, pages.nl/linux/systemd-resolve.md
=> systemd-resolve: add Dutch translation

pages.nl/common/python.md
=> python: add Dutch translation

pages.nl/common/pamscale.md, pages.nl/common/pnmscale.md
=> pnmscale, pamscale: add Dutch translation

pages.nl/common/pnmquant.md, pages.nl/common/pnmremap.md, pages.nl/common/ppmquant.md
=> ppmquant, pnmquant pnmremap: add Dutch translation

pages.pt_BR/linux/pw-cat.md, pages/linux/pw-cat.md
=> pw-cat: update page and pt_BR translation

pages.es/common/nix-classic.md
=> nix-classic: add Spanish translation

pages.it/common/mv.md
=> mv: update Italian translation

pages.es/common/chmod.md
=> chmod: update Spanish translation

pages.es/common/git-push.md
=> git-push: update Spanish translation

pages.es/common/vboxmanage-movevm.md, pages/common/vboxmanage-movevm.md
=> vboxmanage-movevm: add Spanish translation

pages.es/common/calc.md
=> calc: update Spanish translation

pages.es/linux/apt-get.md
=> apt-get: update Spanish translation

pages.es/common/git-remote.md
=> git-remote: update Spanish translation

.github/CODEOWNERS, contributing-guides/translation-templates/common-arguments.md, pages.pt_PT/android/dalvikvm.md, pages.pt_PT/android/logcat.md, pages.pt_PT/common/7z.md, pages.pt_PT/common/7za.md, pages.pt_PT/common/7zr.md, pages.pt_PT/common/alacritty.md, pages.pt_PT/common/cd.md, pages.pt_PT/common/chmod.md
This PR updates the values of the common arguments for tldr-pages entries in Portuguese (Portugal).
Existing pages are also normalized to follow the same patterns.
Finally, I also removed my name from the pt-BR entry in CODEOWNERS, since there's already another maintainer looking after them, and I don't currently have the bandwidth to review changes in a timely manner.
=> common-arguments: update pt-PT values;  codeowners: remove waldyrious from pt-BR

scripts/build.sh, scripts/deploy.sh
=> Revert "scripts: don't build archives when pages haven't been changed"

scripts/build.sh, scripts/deploy.sh
=> cleanup: revert back don't build scripts archive step

pages/common/ansible-inventory.md, pages/common/gcloud.md, pages/common/git-release.md, pages/common/git-svn.md, pages/common/kubectl-describe.md, pages/common/kubectl-get.md, pages/common/pip-install.md, pages/common/ssh-copy-id.md, pages/linux/cuyo.md, pages/linux/genid.md, pages/linux/ip.md, pages/linux/lastlog.md, pages/linux/rpm2cpio.md, pages/linux/vgchange.md, pages/linux/zathura.md, pages/osx/fdesetup.md, pages/osx/icalbuddy.md
=> pages/*: fix small typos

pages.it/common/tac.md
=> tac: update Italian translation

pages.es/common/git-stash.md
=> git-stash: update Spanish translation

contributing-guides/style-guide.md
Adresses the "Document Display help and Display version generic term preference and order. [Existing informal rule]" part of #11146.
=> style-guide: add help and version commands section

pages/common/cups.md
This is an introduction to CUPS, I think it would help people that are new to the CUPS commands. If this PR is approved, I will translate it to pt_BR in another PR.
=> cups: add page

pages.pt_BR/common/cancel.md, pages.pt_BR/common/lpmove.md, pages/common/cancel.md, pages/common/lpmove.md
=> cancel, lpmove: add pages and pt_BR translation

pages.ko/common/auditd.md
=> auditd: add Korean translation

MAINTAINERS.md
=> MAINTAINERS: add @cyqsimon to collaborators

pages.pt_BR/common/cupsctl.md, pages.pt_BR/common/lpadmin.md, pages.pt_BR/common/lpoptions.md, pages.pt_BR/common/lpq.md, pages.pt_BR/common/lprm.md, pages/common/cups-config.md, pages/common/cupsctl.md, pages/common/cupsd.md, pages/common/lpadmin.md, pages/common/lpinfo.md, pages/common/lpoptions.md, pages/common/lpq.md, pages/common/lpr.md, pages/common/lprm.md
=> cups*: use OpenPrinting CUPS docs instead of Apple CUPS

pages.pt_BR/linux/pw-cli.md, pages/linux/pw-cli.md
=> pw-cli: use a more clear description instead of a generic one

pages.de/common/lpinfo.md, pages.de/common/lpr.md, pages.nl/common/cupsd.md, pages.nl/common/lpadmin.md, pages.nl/common/lprm.md, pages.pt_BR/common/lpmove.md
=> pages.*: update CUPS documentation URL

pages.id/common/[.md, pages.id/common/adb-install.md, pages.id/common/aria2c.md, pages.id/common/asar.md, pages.id/common/clamscan.md, pages.id/common/docker.md, pages.id/common/git-clone.md, pages.id/linux/dnf.md, pages.id/linux/pacman.md, pages.id/osx/date.md, pages.id/osx/shuf.md, pages.id/osx/xcodes.md, pages.id/windows/find.md, pages.id/windows/invoke-webrequest.md, pages.id/windows/scoop.md, pages.id/windows/set-location.md, pages.id/windows/wget.md
=> pages.id: update outdated pages

pages/common/wpexec.md
=> wpexec: add page

pages.de/common/bash.md, pages.es/common/bash.md, pages.fr/common/bash.md, pages.it/common/bash.md, pages.ko/common/bash.md, pages.nl/common/bash.md, pages.pt_BR/common/bash.md, pages.zh/common/bash.md, pages.zh_TW/common/bash.md, pages/common/bash.md, pages/linux/fold.md
=> bash, fold: update link to match other pages

pages.pt_BR/common/ippevepcl.md, pages.pt_BR/common/ippeveprinter.md, pages.pt_BR/common/ippeveps.md
=> ippeve{pcl,printer,ps}: add pt_BR translations

pages.es/linux/lsusb.md
=> lsusb: update Spanish translation

pages.es/common/git-branch.md
=> git-branch: update Spanish translation

pages/linux/pw-dot.md
=> pw-dot: add page

pages.sh/common/sh.md
=> sh: update Serbian-Croatian translation

pages/common/cs.md
Ref #11811
- **Version of the command being documented (if known):** n/a
=> cs: fix grammar in description

pages.zh/linux/paru.md
=> paru: add Chinese translation

pages.id/common/accelerate.md, pages.ko/common/accelerate.md, pages.nl/common/accelerate.md, pages/common/accelerate.md
=> accelerate: leave value as part of the command

pages.tr/common/git-annotate.md, pages/common/git-annotate.md
This PR adds a command mnemonic to `git annotate`.
=> git-annotate: use short mnemonics

scripts/check-pr.sh
=> scripts/check-pr: check only for English pages

pages/common/pbzip2.md
=> pbzip2: add page

MAINTAINERS.md
@korECM I took the name from your GitHub profile banner, feel free to let me know if you want to modify it.
=> MAINTAINERS: add @korECM as collaborator

.github/CODEOWNERS, MAINTAINERS.md
=> MAINTAINERS: add @tricantivu as collaborator, CODEOWNERS: add @tricantivu for Spanish

pages.fa/common/cppclean.md
=> cppclean: add Farsi translation

pages/linux/wami.md
=> wami: fix typo

pages.es/osx/lsappinfo.md
=> lsappinfo: add Spanish translation

pages.fa/common/airpaste.md, pages.fa/common/ani-cli.md
=> ani-cli, airpaste: add Farsi translation

pages.nl/common/df.md, pages.nl/freebsd/df.md, pages.nl/linux/df.md, pages.nl/netbsd/df.md, pages.nl/openbsd/df.md, pages.nl/osx/df.md, pages/openbsd/df.md
=> df: add Dutch translation

pages/common/tidy.md
=> tidy: add page

pages/common/df.md
=> df: use manned.org in more info link

pages.es/common/kill.md, pages.fr/common/kill.md, pages.ko/common/kill.md, pages.pt_BR/common/kill.md
=> kill: update link

pages/common/rustscan.md
=> rustscan: add page

pages.ko/common/blockout2.md
=> blockout2: add Korean translation

pages/osx/dockutil.md
- **Version of the command being documented (if known): 3.1.1**
=> dockutil: add page

pages/linux/cp.md
cp -i: text files -> file, more general.
---
=> cp: replace ambiguous text

pages/common/bshell.md, pages/common/bssh.md, pages/common/bvnc.md
=> bssh: use manned.org in more info link

pages/common/boxes.md
=> boxes: change more info link to manual page

pages/common/qownnotes.md
=> qownnotes: add page

pages.es/linux/lid.md
=> lid: add Spanish translation

pages.fa/common/boxes.md, pages.ko/common/boxes.md
=> boxes: update more info links on translations

pages/common/qc.md
- **Version of the command being documented (if known):** 0.5.1
=> qc: add page

contributing-guides/style-guide.md
=> style-guide: recommend keith.github.io for osx pages

MAINTAINERS.md
=> MAINTAINERS: add @vitorhcl as Org member

pages/common/qownnotes.md
=> qownnnotes: suggest qc page

pages/common/ffuf.md
=> ffuf: add page

COMMUNITY-ROLES.md
- Fixes spacing in issue templates (for better readability).
- Minor fixes to descriptions.
=> cleanup: update community roles file

pages.pt_BR/osx/indent.md
=> indent: fix more info link for Brazilian Portuguese

README.md
The Matrix chat is too hidden for now, we could add it to the README.
=> README.md: add link to the Matrix room

pages.nl/common/flock.md, pages.nl/common/head.md, pages.nl/common/lckdo.md, pages.nl/common/tail.md, pages.nl/linux/tailf.md, pages.nl/osx/tail.md
=> pages.nl: add Dutch translation

pages.es/common/kopia.md
=> kopia: add Spanish translation

pages.es/osx/dockutil.md
=> dockutil: add Spanish translation

pages.es/osx/rargs.md
=> rargs: add Spanish translation

pages.es/common/jbang.md
=> jbang: add Spanish translation

pages.fr/common/act.md, pages/common/act.md
- **Version of the command being documented (if known):** 0.2.57
Fix https://github.com/tldr-pages/tldr/issues/12116
=> act: fix error for running job

pages.nl/linux/sed.md, pages/linux/sed.md
=> sed: update Dutch translation

pages.es/common/qc.md
=> qc: add Spanish translation

pages.es/osx/split.md
=> split: add Spanish translation

pages.es/netbsd/pkgin.md
=> pkgin: add Spanish translation

pages.es/common/qownnotes.md
=> qownnotes: add Spanish translation

pages.es/common/picocom.md
=> picocom: add Spanish translation

pages/linux/unmount.md
=> unmount: add page

pages/common/ccache.md
- **Version of the command being documented (if known):** ccache version 4.9
=> ccache: add page

pages.nl/linux/umount.md, pages.nl/linux/unmount.md, pages/linux/unmount.md
=> umount, unmount: add Dutch translation

pages/common/moreutils.md
=> moreutils: add page

pages/linux/pacstrap.md
=> pacstrap: update page

pages.es/common/pnmpsnr.md
=> pnmpsnr: add Spanish translation

pages/linux/man.md
=> man: update page

pages/common/pbmnoise.md, pages/common/pgmhist.md, pages/common/pgmkernel.md, pages/common/pgmnoise.md, pages/common/pgmramp.md, pages/common/pgmtexture.md, pages/common/ppmhist.md
=> pbmnoise, pgmhist, pgmkernel, pgmnoise, pgmramp, pgmtexture: add pages; ppmhist: modify page

pages/linux/getfacl.md, pages/linux/setfacl.md
- setfacl: add acronym to description
- setfacl: `{{file}}` -> `{{path/to/file_or_directory}}`
- {get,set}facl: use long options
---
- **Version of the command being documented (if known):** 2.3.2
=> {get,set}facl: update & unify style

pages/common/bru.md
- Version of the command being documented: `1.8.0`
Documentation: https://docs.usebruno.com 📖
The team: https://www.usebruno.com/about 🧑‍💻+🐶
Tested with:
bru --version
1.8.0
I dit not mention the `bru run folder` command because I could not make it work. 🤷
=> bru: add page

pages/common/minikube.md
=> minikube: update documentation link

pages/linux/kdesrc-build.md
=> kdesrc-build: update page

pages.es/freebsd/look.md
=> look: add Spanish translation

pages/common/parallel.md
=> parallel: fix example

pages/common/naabu.md
line 23: `80,443` --> `80, 443`
=> naabu: fix typo

pages/common/mat2.md
=> mat2: add example

pages/common/zip.md, pages/linux/zip.md
=> zip: follow style guide for compression level placeholder

pages/common/nl.md, pages/linux/nl.md
=> common/nl: update page; linux/nl: add page

pages/common/gdal2tiles.py.md
- **Version of the command being documented (if known):** 3.8.3
=> gdal2tils.py: fix zoom placeholders

pages/linux/chcpu.md
- **Version of the command being documented (if known):** util-linux 2.39.3
=> chcpu: improve example descriptions

pages/common/tailscale-up.md
=> tailscale-up: fix page description and improve examples

pages/linux/ncat.md
=> ncat: add examples

pages.es/common/gammastep.md
=> gammastep: add Spanish translation

MAINTAINERS.md
=> MAINTAINERS: add @fazlearefin as collaborator

pages/common/meshnamed.md
- **Version of the command being documented (if known): *0.2.0*
=> meshnamed: add page

pages.es/common/bru.md
=> bru: add Spanish translation

pages/common/yes.md
=> yes: add example

pages/common/atktopbm.md, pages/common/pamditherbw.md, pages/common/pamenlarge.md, pages/common/pbmreduce.md, pages/common/pbmtext.md, pages/common/pbmtextps.md, pages/common/pbmtoatk.md, pages/common/pbmtobbnbg.md
=> pamditherbw: edit page; atktopbm, pamenlarge, pbmreduce, pbmtext, pbmtextps, pbmtoatk, pbmtobbnbg; add pages

pages/common/naabu.md
=> naabu: add example

pages/common/cmuwmtopbm.md, pages/common/escp2topbm.md, pages/common/pbmtocmuwm.md, pages/common/pbmtoepsi.md, pages/common/pbmtoepson.md, pages/common/pbmtoescp2.md, pages/common/pbmtogo.md
=> cmuwmtopbm, escp2topbm, pbmtocmuwm, pbmtoepsi, ebmtoepson, pbmtoescp2, pbmtogo: add pages

pages/common/asciinema.md, pages/common/terminalizer.md
=> terminalizer, asciinema: update page

pages/osx/yabai.md
- **Version of the command being documented (if known):** 6.0.11
=> yabai: use GitHub wiki in more info link and improve examples

pages.de/common/dd.md, pages.es/osx/dd.md, pages.it/common/dd.md, pages.ko/linux/dd.md, pages.pt_BR/common/dd.md, pages/linux/dd.md
=> dd: use -x in pgrep

pages/common/gifsicle.md
- **Version of the command being documented (if known):** 1.94
=> gifsicle: improve description and examples

pages/common/aria2c.md
=> aria2c: fix multiple url use syntax and add checksum usage

pages/osx/bless.md
=> bless: fix manual section in more info link

pages/common/pcapfix.md
- **Version of the command being documented (if known): *1.1.7*
=> pcapfix: add page

pages.de/common/meshnamed.md
- **Version of the command being documented (if known):*0.2.0*
=> meshnamed: add German translation

pages/common/jfrog.md
=> jfrog: add alias page

pages/common/gouldtoppm.md, pages/common/mtvtoppm.md, pages/common/pamstack.md
=> gouldtoppm, mtvtoppm, pamstack: add pages

pages.es/common/more.md, pages.es/osx/bless.md, pages.es/osx/yabai.md, pages.it/common/more.md, pages.pt_BR/osx/bless.md, pages.zh/common/more.md
=> bless, more, yabai: update more info link

pages/common/subfinder.md
=> subfinder: edit page

pages/common/nuclei.md
=> nuclei: add page

pages.it/linux/pacman.md
=> pacman: add Italian translation

pages.nl/linux/cal.md
=> cal: update Dutch translation

pages/common/golangci-lint.md
- **Version of the command being documented (if known):** 1.55.2
=> golangci-lint: add page

pages/linux/strace.md
=> strace: update page

pages/common/usql.md
=> usql: add page

pages/common/qmmp.md
1. Add details to page description: its interface is similar to Winamp and XMMS
2. Use "Launch the GUI" instead of "Launch program_name"
3. Add mnemonics for abbreviated long options
4. Use "display" instead of "print"
5. Use "%" instead of "steps" to talk about volume changes, which makes it clearer
=> qmmp: improve examples and page description

pages.es/common/git-gui.md
=> git-gui: add Spanish translation

pages/common/gocr.md
- **Version of the command being documented (if known):** 0.52-20181015
=> gocr: add page

pages/common/searchsploit.md
=> searchsploit: edit page

pages/common/clementine.md
- **Version of the command being documented (if known):** 1.4 rc2
=> clementine: improve examples, more info link, and add example

pages.fr/common/hexyl.md
- **Version of the command being documented (if known):** 0.14.0
=> hexyl: add French translation

pages.fr/common/btop.md
- **Version of the command being documented (if known):** 1.3.2
=> btop: add French translation

pages.fr/common/mktemp.md
- **Version of the command being documented (if known):** 9.4
=> mktemp: add French translation

pages/android/wm.md
=> wm: remove wrong placeholder marks

pages/linux/aur.md
=> aur: add page

contributing-guides/style-guide.md
- Add a special case for enclosing mnemonic terms inside brackets (Ref. #12151)
- Revise the entire option syntax section (implementing suggestions from #12125)
- Minor fixes
=> style-guide: update page

pages/linux/repo-add.md
=> repo-add: add barebones example

pages/common/^.md
=> ^: add page

pages/common/bats.md
=> bats: add page

pages.fr/common/ffuf.md, pages/common/ffuf.md
- **Version of the command being documented (if known):** 2.1.0
=> ffuf: add French translation

pages.fr/common/fzf.md
- **Version of the command being documented (if known):** 0.46.1 (3c0a6304)
=> fzf: add French translation

pages/common/mpc.md
=> mpc: update page

pages/linux/aur.md
=> aur: update page

pages.es/netbsd/df.md
=> df: add Spanish translation

pages/common/docker-rm.md
=> docker-rm: fix example

pages/linux/navi.md
=> navi: add page

pages/common/trufflehog.md
=> trufflehog: add page

pages/linux/bspc.md, pages/linux/bspwm.md
- **Version of the command being documented (if known):** 0.9.10
=> bspwm, bspc: improve descriptions, add "See also" and add example

pages/linux/grubby.md
- **Version of the command being documented (if known):** 8.40-75
=> grubby: add page

pages/linux/select.md
=> select: update page

pages.es/common/gocr.md
=> gocr: add Spanish translation

pages.pt_BR/common/ncdu.md
- **Version of the command being documented (if known):** 2.3
=> ncdu: add pt_BR translation

pages/common/ruff-check.md, pages/common/ruff-format.md, pages/common/ruff.md
=> ruff, ruff-{check,format}: add page

pages/common/poetry.md
=> poetry: edit page

pages/linux/debuginfod-find.md
=> debuginfod-find: add page

pages.es/common/tgpt.md
=> tgpt: add Spanish translation

pages.es/common/hexyl.md
=> hexyl: add Spanish translation

pages.es/linux/aur.md
=> aur: add Spanish translation

pages.es/common/bats.md
=> bats: add Spanish translation

pages.pt_BR/common/micro.md
- **Version of the command being documented (if known):** 2.0.13
=> micro: add pt_BR translation

pages.pt_BR/linux/makepkg.md
- **Version of the command being documented (if known):** 6.0.2
=> makepkg: add pt_BR translation

pages.pt_BR/common/kate.md
- **Version of the command being documented (if known):** 23.08.5
=> kate: add pt_BR translation

pages.pt_BR/linux/xrandr.md
- **Version of the command being documented (if known):** 1.5.2
=> xrandr: add pt_BR translation

pages/linux/check-dfsg-status.md
- **Version of the command being documented (if known):** 1.33
=> check-dfsg-status: add page

pages.pt_BR/common/eza.md
- **Version of the command being documented (if known):** 0.18.3
=> eza: add pt_BR translation

pages/linux/pwn.md
=> pwn: add page

pages.fr/common/colorls.md
=> colorls: add French translation

pages/common/entr.md
=> entr: edit page

pages.fr/common/deno.md
=> deno: add French translation

pages.pt_BR/common/find.md
- **Version of the command being documented (if known):** 4.9.0
=> find: add pt_BR translation

pages/common/trivy.md
=> trivy: edit page

pages.fr/common/exa.md
=> exa: add French translation

pages.es/linux/grubby.md
=> grubby: add Spanish translation

pages/common/pbmto4425.md, pages/common/pbmtoascii.md, pages/common/ppmtoascii.md, pages/common/ppmtoterm.md
=> ppmtoterm, ppmtoascii, pbmto4425: add pages; pbmtoascii: edit page

pages.es/common/trufflehog.md
=> trufflehog: add Spanish translation

pages/common/duf.md
=> duf: edit page

pages/common/pamarith.md, pages/common/pnmarith.md
=> pnmarith, pamarith: add pages

pages/common/pnmquant.md, pages/common/pnmquantall.md, pages/common/ppmquantall.md
=> pnmquantall, ppmquantall: add pages; pnmquant: edit page

pages/common/icontopbm.md, pages/common/pbmtoicon.md, pages/common/pbmtosunicon.md, pages/common/sunicontopbm.md
=> icontopbm, pbmtoicon, pbmtosunicon, sunicontopbm: add pages

pages/common/checkov.md
=> checkov: add page

pages/common/mise.md
add tldr for mise runtime
- **2024.2.18**
=> mise: add page

pages/common/printf.md
=> printf: edit page

pages/common/btop.md
=> btop: edit page

pages/common/nmap.md
=> nmap: edit page

pages.es/linux/pwn.md
=> pwn: add Spanish translation

pages.es/common/vcpkg.md
=> vcpkg: add Spanish translation

pages/common/dd.md, pages/common/trivy.md, pages/linux/dd.md
Commits
1. _dd: add `status=progress` to base example_
2. _dd: merged two uses into one_
3. _dd: added information about what is being benchmarked_
4. _dd: changed `noerror` to `fsync` example use flag_
- [] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title). (sorry)
- **Version of the command being documented (if known):** 9.4
=> dd: update page

pages/common/pamrgbatopng.md, pages/common/pamtopng.md, pages/common/pngtopam.md
=> pamrgbatopng, pamtopng, pngtopam: add pages

pages/common/pamcrater.md, pages/common/pamshadedrelief.md, pages/common/pgmcrater.md
=> pgmcrater, pamcrater, pamshadedrelief: add pages

pages/common/pamexec.md, pages/common/pampick.md, pages/common/pamsplit.md, pages/common/pnmsplit.md
=> pnmsplit, pamsplit, pamexec, pampick: add pages

pages/common/pgmtopbm.md
=> pgmtopbm: add page

pages/common/pamtogif.md, pages/common/ppmtogif.md
=> ppmtogif, pamtogif: add pages

pages/common/pgmslice.md
=> pgmslice: add page

pages/common/pnmenlarge.md
=> pnmenlarge: add page

pages/common/ppmtomap.md
=> ppmtomap: add page

pages/common/pcdindex.md, pages/common/pcdovtoppm.md
=> pcdindex, pcdovtoppm: add pages

pages/common/pnmflip.md
=> pnmflip: add page

pages/common/pamtouil.md, pages/common/ppmtouil.md
=> ppmtouil, pamtouil: add pages

pages/common/pamedge.md, pages/common/pgmedge.md
=> pgmedge, pamedge: add pages

pages/common/pnmfile.md
=> pnmfile: add page

pages/common/pgmnorm.md, pages/common/ppmnorm.md
=> ppmnorm, pgmnorm: add pages

pages/common/bmptoppm.md
=> bmptoppm: add page

pages/common/ppmtojpeg.md
=> ppmtojpeg: add page

pages/common/pnminterp.md
=> pnminterp: add page

pages/common/pnmcut.md
=> pnmcut: add page

pages.zh/linux/bootctl.md
=> bootctl: add Chinese translation

pages.es/linux/check-dfsg-status.md
=> check-dfsg-status: add Spanish translation

pages/linux/iwconfig.md
=> iwconfig: fix example parameter

pages.es/common/pnmtojpeg.md
=> pnmtojpeg: add Spanish translation

pages/common/bat.md
=> bat: edit page

pages/linux/macchanger.md
=> macchanger: edit page

pages/common/pipes.sh.md
=> pipes.sh: add page

pages/common/pngtopnm.md
=> pngtopnm: add page

pages/linux/iwlist.md
=> iwlist: add page

pages.fr/common/b3sum.md
- **Version of the command being documented (if known):** 1.5.0
=> b3sum: add French translation

pages.es/common/golangci-lint.md
=> golangci-lint: add Spanish translation

pages.es/common/checkov.md
=> checkov: add Spanish translation

pages.es/common/mise.md
=> mise: add Spanish translation

pages.es/linux/repo-remove.md
=> repo-remove: add Spanish translation

pages/common/airodump-ng.md
=> airodump-ng: edit page

pages/common/audacious.md
- **Version of the command being documented (if known):** 4.3.1
=> audacious: improve examples and page description and add example

pages.es/common/pnmcut.md
=> pnmcut: add Spanish translation

pages/common/go-tool.md
=> go-tool: edit page

pages.es/common/pngtopnm.md
=> pngtopnm: add Spanish translation

pages/osx/diskutil-partitiondisk.md, pages/osx/diskutil.md
- **Version of the command being documented (if known):** macOS Sonoma 14.3.1
=> diskutil-partitiondisk: add page

pages.id/linux/apt-get.md
=> apt-get: add Indonesian translation

pages.id/linux/add-apt-repository.md, pages.id/linux/apt-cache.md
=> add-apt-repository, apt-cache: add Indonesian translation

pages.id/linux/apt-file.md
=> apt-file: add Indonesian translation

pages.nl/common/cat.md
=> cat: fix more information link

pages/linux/waypipe.md
=> waypipe: add page

pages/common/bpkg.md
- **Version of the command being documented (if known):** 1.1.3
=> bpkg: add page

pages.es/common/ppmtojpeg.md
=> ppmtojpeg: add Spanish translation

pages.de/common/traefik.md, pages/common/traefik.md
=> traefik: add German translation; update page

pages.es/common/bpkg.md
=> bpkg: add Spanish translation

pages.es/common/bmptoppm.md
=> bmptoppm: add Spanish translation

pages/common/waymore.md
=> waymore: add page

pages/common/gau.md
=> gau: add page

pages/common/shellcheck.md
=> shellcheck: edit page

pages.id/linux/a2ensite.md
=> a2ensite: add Indonesian translation

pages.id/linux/acpi.md
=> acpi: add Indonesian translation

pages.id/linux/adduser.md
=> adduser: add Indonesian translation

pages/linux/tlp-stat.md
=> tlp-stat: edit page

pages/common/colima.md, pages/osx/colima.md
=> colima: add page

pages.es/common/dolt-gc.md
=> dolt-gc: add Spanish translation

pages/common/wdiff.md
- **Version of the command being documented (if known):** 1.2.2
=> wdiff: add page

pages/linux/choom.md
- **Version of the command being documented (if known):** util-linux 2.39.3
=> choom: add page

pages.fa/common/ln.md
=> ln: add Farsi translation

pages.es/common/figlet.md, pages/common/figlet.md
- **Version of the command being documented (if known): 2.2.5**
=> figlet: 2 more commands and Spanish translation

pages.es/common/simplehttpserver.md
=> simplehttpserver: add Spanish translation

pages/common/base32.md, pages/common/base64.md
=> base*: edit pages

pages/common/diff.md
=> diff: edit page

pages/common/dig.md
=> dig: edit page

pages/common/hashcat.md
=> hashcat: add example

pages.de/common/pcapfix.md, pages/common/pcapfix.md
- **Version of the command being documented (if known):*1.1.7*
=> pcapfix: add German translation

pages.de/common/sc_analysis_dump.md, pages.de/common/sc_tracediff.md, pages.de/common/sc_ttlexp.md, pages.de/common/sc_warts2csv.md, pages.de/common/sc_warts2json.md, pages.de/common/sc_warts2pcap.md, pages.de/common/sc_warts2text.md, pages.de/common/sc_wartscat.md, pages.de/common/sc_wartsdump.md, pages.de/common/sc_wartsfilter.md, pages.de/common/sc_wartsfix.md, pages.de/common/scamper.md
sc_analysis_dump, sc_tracediff, sc_ttlexp, sc_warts2csv, sc_warts2json, sc_warts2pcap, sc_warts2text, sc_wartscat, sc_wartsdump, sc_wartsfilter, sc_wartsfix, scamper: add German translation
- **Version of the command being documented (if known):*20240122*
=> sc_*, scamper: add German translation

pages.fa/common/curl.md
=> curl: add Farsi translation

pages/common/wfuzz.md
=> wfuzz: edit page

pages.es/linux/choom.md
=> choom: add Spanish translation

pages.es/linux/dhcpcd.md
=> dhcpcd: add Spanish translation

pages.es/common/pnmfile.md
=> pnmfile: add Spanish translation

pages/common/chisel.md
=> chisel: edit page

pages/common/pi1toppm.md, pages/common/ppmtopi1.md
=> pi1toppm, ppmtopi1: add pages

pages.es/common/pnmenlarge.md
=> pnmenlarge: add Spanish translation

pages.es/common/ppmtopi1.md
=> ppmtopi1: add Spanish translation

pages.es/common/pi1toppm.md
=> pi1toppm: add Spanish translation

pages.es/common/ppmtomap.md
=> ppmtomap: add Spanish translation

pages.es/common/gau.md
=> gau: add Spanish translation

pages.es/common/git-mktree.md
=> git-mktree: add Spanish translation

pages/linux/torsocks.md
=> torsocks: add page

pages.es/common/waymore.md
=> waymore: add Spanish translation

pages.es/linux/torsocks.md
=> torsocks: add Spanish translation

pages.es/linux/waypipe.md
=> waypipe: add Spanish translation

pages/linux/firejail.md
=> firejail: edit page

pages/common/hashcat.md, pages/linux/showkey.md
- **Version of the command being documented (if known): 2.6.4**
=> showkey: add page

pages/common/gist.md, pages/common/vboxmanage-cloud.md
=> gist, vboxmanage-cloud: fix typos

pages/linux/mkfs.f2fs.md
=> mkfs.f2fs: add page

pages/common/pydocstyle.md
=> pydocstyle: add page

pages/linux/cacaclock.md, pages/linux/cacademo.md, pages/linux/cacafire.md, pages/linux/cacaview.md
- 0.99.beta19-2.2ubuntu4 amd64
=> cacafire, cacaview, cacademo, cacaclock: add pages

MAINTAINERS.md
=> MAINTAINERS: readd @quantumflo as collaborator

MAINTAINERS.md
Closes https://github.com/tldr-pages/tldr/issues/12595
=> MAINTAINERS: add @fazlearefin to Org

pages.es/common/ppmnorm.md
=> ppmnorm: add Spanish translation

pages.es/common/pgmnorm.md
=> pgmnorm: add Spanish translation

pages.es/common/pydocstyle.md
=> pydocstyle: add Spanish translation

pages/linux/ydotool.md
=> ydotool: add page

pages.es/linux/cacaview.md
=> cacaview: add Spanish translation

pages.es/linux/mkfs.f2fs.md
=> mkfs.f2fs: add Spanish translation

pages.es/linux/tunelp.md
=> tunelp: add Spanish translation

pages.es/linux/showkey.md
=> showkey: add Spanish translation

pages.es/common/fclones.md
=> fclones: add Spanish translation

MAINTAINERS.md
=> cleanup: update formatting for MAINTAINERS file

pages.es/linux/mount.ddi.md
=> mount.ddi: add Spanish translation

pages.es/linux/cacaclock.md
=> cacaclock: add Spanish translation

pages.es/linux/cacafire.md
=> cacafire: add Spanish translation

pages.es/linux/cacademo.md
=> cacademo: add Spanish translation

pages.es/linux/systemd-tmpfiles.md
=> systemd-tmpfiles: add Spanish translation

pages.nl/common/pamfixtrunc.md
=> pamfixtrunc: add Dutch translation

pages/linux/rpi-otp-private-key.md
=> rpi-otp-private-key: add page

pages.es/common/pgmedge.md
=> pgmedge: add Spanish translation

pages.es/common/pcdovtoppm.md
=> pcdovtoppm: add Spanish translation

pages.es/common/pcdindex.md
=> pcdindex: add Spanish translation

pages/common/upt.md
- **Version of the command being documented (if known):** 0.7.0
=> upt: add page

pages.es/linux/ydotool.md
=> ydotool: add Spanish translation

pages.nl/common/pamfixtrunc.md
=> pamfixtrunc: fix styling

pages.id/sunos/devfsadm.md, pages.id/sunos/dmesg.md, pages.id/sunos/prctl.md, pages.id/sunos/prstat.md, pages.id/sunos/snoop.md, pages.id/sunos/svcadm.md, pages.id/sunos/svccfg.md, pages.id/sunos/svcs.md, pages.id/sunos/truss.md
=> sunos*: add Indonesian translation

pages/linux/last.md
- **Version of the command being documented (if known):** `2.39.3`
=> last: add page

pages/linux/autorecon.md
=> autorecon: add page

pages/common/difft.md
=> difft: add page

pages.es/linux/last.md
=> last: add Spanish translation

pages/common/ollama.md
- Add command to update Ollama
- Add command to update pulled models
- **Version of the command being documented (if known):** 0.1.31
=> ollama: add examples

pages.es/common/upt.md
=> upt: add Spanish translation

pages/common/katana.md
=> katana: add page

pages/linux/blkpr.md
- **Version of the command being documented (if known):** util-linux 2.40
TODO:
=> blkpr: add page

pages/common/dnsx.md
=> dnsx: fixed proper spacing

pages/common/masscan.md
=> masscan: edit page

pages.es/common/difft.md
=> difft: add Spanish translation

pages/linux/export.md
- **Version of the command being documented (if known):** Unknown (Does not work with `-v` or `--version` flags and has no man page)
=> export: edit page

pages.es/common/pgmslice.md
=> pgmslice: add Spanish translation

pages.es/common/ppmtouil.md
=> ppmtouil: add Spanish translation

pages/common/duplicity.md
- **Version of the command being documented (if known):** `2.1.5`
Closes #12615
=> duplicity: add description to clarify discrepancy of options

pages.es/common/pamtouil.md
=> pamtouil: add Spanish translation

pages/common/z.md
=> z: fix typo

pages/common/quarkus.md
- **Version of the command being documented:** 3.9.2
=> quarkus: add page

pages.es/linux/blkpr.md
=> blkpr: add Spanish translation

pages/common/du.md
=> du: add example

MAINTAINERS.md
=> MAINTAINERS: add @sebastiaanspeck as organization owner

pages.es/windows/ospp.vbs.md
=> ospp.vbs: add Spanish translation

pages.es/common/ppmbrighten.md
=> ppmbrighten: add Spanish translation

pages.es/common/pgmtopbm.md
=> pgmtopbm: add Spanish translation

pages.es/common/par2.md
=> par2: add Spanish translation

pages.es/common/cat.md
=> cat: update Spanish translation

pages.es/linux/debuginfod-find.md
=> debuginfod-find: add Spanish translation

pages/linux/aur.md
=> aur: add automation example

pages.es/linux/ntpd.md
=> ntpd: add Spanish translation

pages.es/common/type.md
=> type: add Spanish translation

pages.es/common/tar.md
=> tar: fix typos on Spanish page

pages.id/common/!.md, pages.id/common/^.md, pages.id/common/airodump-ng.md, pages.id/common/aria2.md, pages.id/common/bat.md, pages.id/common/cp.md
=> common: update outdated Indonesian translations

pages.es/common/ppmtogif.md
=> ppmtogif: add Spanish translation

pages.es/common/gitleaks.md
=> gitleaks: add Spanish translation

pages.es/common/pamtogif.md
=> pamtogif: add Spanish translation

pages.es/common/quarkus.md, pages/common/quarkus.md
=> quarkus: add Spanish translation, fix placeholder

MAINTAINERS.md
Add @Magrid0 to the collaborators list.
Closes #12717
=> MAINTAINERS: add @Magrid0 as Org Member

pages.pl/android/logcat.md, pages.pl/android/screencap.md
This pull request updates the Polish translation of the `logcat` command to match the latest English version and adds a translation for the `screencap` command. Please review and merge the changes.
=> logcat: update Polish translation; screencap: add Polish translation

pages/common/d2.md
=> d2: add page

pages/common/cut.md
=> cut: edit page

pages/linux/chrt.md
=> chrt: update page

pages.es/common/immich-cli.md, pages.es/common/immich-go.md, pages/common/immich-cli.md, pages/common/immich-go.md
=> immich-{cli,go}: add page and Spanish translation

pages/linux/prime-run.md
Just as a note, although this is installable through the arch package manager, it is actually (to my knowledge) just a bash script
```bash
#!/bin/bash
__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia "$@"
```
=> prime-run: add page

pages.pl/osx/xsltproc.md, pages.pl/osx/yaa.md
=> xsltproc, yaa: update Polish translation

pages.nl/common/icontopbm.md
Ref: https://github.com/tldr-pages/tldr/pull/12739
=> icontopbm: fix typo for alias page

pages/linux/getenforce.md
=> getenforce: add page

pages.nl/common/bmptopnm.md
=> bmptopnm: add Dutch translation

pages/common/theharvester.md
=> theharvester: edit page

scripts/set-alias-page.py
set-more-info-link will follow in another PR 😄
=> scripts/set-alias-page.py: add language option, fix script

contributing-guides/style-guide.md
https://github.com/tldr-pages/tldr/pull/12553#issuecomment-2080376442
=> style-guide: update the "See also" section

pages/linux/krfb-virtualmonitor.md
=> krfb-virtualmonitor: add page

pages/linux/aur.md
=> aur: add another automation option

.github/CODEOWNERS, MAINTAINERS.md
=> MAINTAINERS: add @spageektti as a collaborator; CODEOWNERS: add Polish reviewer

pages/linux/readelf.md
=> readelf: update link

pages/common/gleam.md
- **Version of the command being documented (if known): 1.1.0**
=> gleam: add page

pages/common/touch.md
=> touch: update page

pages/common/lsar.md, pages/common/unar.md
Hello. This PR adds a page for `lsar`. 
Please review and approve these changes. Thank you!
- **Version of the command being documented (if known):** v1.10.7
=> lsar: add page; unar: update page

pages.es/linux/getenforce.md
=> getenforce: add Spanish translation

pages/common/apkleaks.md
=> apkleaks: add page

pages.es/linux/bwa.md
=> bwa: add Spanish translation

pages.es/common/lstopo.md
=> lstopo: add Spanish translation

.github/CODEOWNERS
=> CODEOWNERS: add @kbdharun as reviewer for scripts directory

pages.es/common/ansible.md
=> ansible: add Spanish translation

pages.es/common/gleam.md
=> gleam: add Spanish translation

pages.es/common/act.md, pages.es/common/argocd-app.md, pages.es/common/asciinema.md, pages.es/common/aws-cognito-idp.md, pages.es/common/aws-ec2.md, pages.es/common/aws-route53.md, pages.es/common/az-account.md, pages.es/common/az-tag.md, pages.es/common/kill.md, pages.es/linux/apt-key.md, pages.es/linux/pwdx.md, pages.es/linux/top.md, pages.es/osx/vpnd.md
=> pages.es/*: update placeholders with the word "id"

pages/common/dotnet-test.md
- **Version of the command being documented (if known):** Since .NET Core 3.1
=> dotnet-test: add page

pages.zh/linux/dnf.md
=> dnf: add Chinese translation

contributing-guides/style-guide.md
=> style-guide: fix typos

pages/linux/xrandr.md, pages/linux/xset.md
=> xset, xrandr: add example

pages.es/common/arp.md
=> arp: add Spanish translation

pages.es/common/arp.md, pages.pt_BR/common/tree.md
=> arp: fix typo, tree: update link in translation

pages.pt_BR/linux/dconf-reset.md, pages/linux/dconf-reset.md
=> dconf-reset: fix examples

pages/linux/togglesebool.md
- **Version of the command being documented (if known):** unknown (this thing's been deprecated for a ***long*** time now, so it's difficult to find a distro that even ships it)
=> togglesebool: add page

pages/common/mypy.md
- **Version of the command being documented (if known):** mypy 1.10.0 (compiled: no)
=> mypy: add page

pages.es/linux/agetty.md
=> agetty: fix Spanish translation

pages.es/linux/ctop.md
=> ctop: add Spanish translation

pages.es/linux/torify.md
=> torify: add Spanish translation

pages/common/hledger-accounts.md, pages/common/hledger-aregister.md, pages/common/hledger-balance.md, pages/common/hledger-balancesheet.md, pages/common/hledger-incomestatement.md, pages/common/hledger-ui.md, pages/common/hledger-web.md, pages/common/hledger.md
- **Version of the command being documented (if known):** 1.33
=> hledger-*: update pages

pages/common/zint.md
- **Version of the command being documented (if known): 2.13.0**
First time contributing, let me know what to improve! 🙃
=> zint: add page 

MAINTAINERS.md
=> MAINTAINERS: add @spageektti to Org

pages.es/common/waybar.md
=> waybar: add Spanish translation

pages/linux/pw-metadata.md
#11747
- **Version of the command being documented (if known):** `libpipewire 1.0.6`
=> pw-metadata: add page

pages/common/mpv.md
=> mpv: fix typo

pages/common/gzip.md
=> gzip: update page

pages/common/audtool.md
- **Version of the command being documented (if known):** 4.3.1
=> audtool: add page

pages/common/ansible-playbook.md
=> ansible-playbook: add dryrun --check --diff example

pages.es/common/audtool.md
=> audtool: add Spanish translation

pages.nl/common/compare.md, pages.nl/common/convert.md, pages.nl/common/identify.md, pages.nl/common/import.md, pages.nl/common/magick.md, pages.nl/common/mogrify.md, pages.nl/common/montage.md
=> magick: update and add alias pages for Dutch

contributing-guides/style-guide.md, pages/windows/clear-host.md, pages/windows/get-acl.md, pages/windows/get-childitem.md, pages/windows/get-content.md, pages/windows/get-date.md, pages/windows/get-filehash.md, pages/windows/get-history.md, pages/windows/invoke-item.md, pages/windows/invoke-webrequest.md, pages/windows/measure-command.md, pages/windows/measure-object.md, pages/windows/new-item.md, pages/windows/out-string.md, pages/windows/resolve-path.md, pages/windows/select-string.md, pages/windows/set-acl.md, pages/windows/set-date.md, pages/windows/set-location.md, pages/windows/set-service.md, pages/windows/show-markdown.md, pages/windows/sort-object.md, pages/windows/start-service.md, pages/windows/stop-service.md, pages/windows/tee-object.md, pages/windows/test-json.md, pages/windows/test-netconnection.md, pages/windows/wait-process.md, pages/windows/where-object.md
=> style-guide, pages/windows/*: add note for PowerShell descriptions

pages.es/common/grep.md
=> grep: fix typo in Spanish translation

pages.es/common/hledger-balance.md
=> hledger-balance: add Spanish translation

pages.nl/common/magick-compare.md, pages.nl/common/magick-convert.md, pages.nl/common/magick-identify.md, pages.nl/common/magick-import.md, pages.nl/common/magick-mogrify.md, pages.nl/common/magick-montage.md
=> magick-*: add Dutch translation

pages.es/common/typeinc.md, pages/common/typeinc.md
=> typeinc: add Spanish translation, update page

pages/common/neo4j-admin.md
- **Version of the command being documented (if known): Neo4j 5.20**
=> neo4j-admin: add page

pages.es/osx/dd.md
=> dd: update Spanish translation

pages.es/linux/abbr.md
=> abbr: fix Spanish translation

pages.id/common/amass-enum.md, pages.id/common/amass-intel.md, pages.id/common/amass.md, pages.id/common/androguard.md, pages.id/common/ani-cli.md, pages.id/common/anki.md
=> amass, amass-enum, amass-intel, androguard, ani-cli, anki: add Indonesian translation

pages.es/linux/turbostat.md
=> turbostat: add Spanish translation

pages.nl/common/^.md
=> ^: add Dutch translation

pages.es/freebsd/look.md, pages.nl/common/look.md, pages.nl/freebsd/look.md, pages.nl/linux/look.md, pages.nl/osx/look.md, pages/freebsd/look.md, pages/linux/look.md, pages/osx/look.md
=> look: add Dutch translation, fix typos

pages/common/ansiweather.md, pages/common/apkleaks.md
=> ansiweather, apkleaks: use imperative descriptions

pages.nl/common/cal.md, pages.nl/common/gcal.md, pages.nl/freebsd/cal.md, pages.nl/netbsd/cal.md, pages.nl/openbsd/cal.md, pages.nl/osx/cal.md, pages.pt_BR/common/gcal.md, pages/common/gcal.md
=> cal: add Dutch translation, gcal: add Dutch translation, fix placeholders

pages.id/common/brew-autoremove.md, pages.id/common/brew-bundle.md, pages.id/common/brew-install.md, pages.id/common/brew.md
I forgot to push this into a PR (originally created on March), so here are the translated pages (Part 1) for [Homebrew](https://brew.sh)!
=> brew, brew-*: add Indonesian translation

pages/common/kubectx.md
=> kubectx: add 2 command examples

pages/common/kubectl-logs.md
remove stream + container name which is a combination of two commands to keep list at recommended size
=> kubectl-logs: add logs for deployment

pages.nl/common/gcal.md
=> gcal: fix Dutch translation

pages.es/common/tree.md, pages.it/common/tree.md, pages.pt_BR/common/tree.md, pages.tr/common/tree.md, pages.zh/common/tree.md
This PR updates translations for `tree` (see: #12956).
=> tree: update translations

pages.da/common/sed.md, pages.ja/common/sed.md, pages.ko/common/sed.md, pages.nl/common/sed.md
This PR updates translations for `sed` (see: #12956).
=> sed: update translations

pages.es/common/nc.md, pages.ko/common/nc.md, pages.nl/common/nc.md
This PR updates translations for `nc` (see: #12956).
=> nc: update translations

pages.pl/common/atom.md
Updates the Polish translation to conform with the English page.
=> atom: update Polish translation

pages.pl/common/autoflake.md
=> autoflake: update Polish translation

pages.pl/common/babel.md
=> babel: update Polish translation

pages.pl/common/dotnet.md
=> dotnet: update Polish translation

pages.pl/common/7z.md
Updates the translation to conform with the English page.
=> 7z: update Polish translation

pages.pl/common/ag.md, pages.pl/common/bash.md
=> ag, bash: update Polish translation

pages.pl/common/mysql.md
=> mysql: update Polish translation

pages.pl/common/yes.md
=> yes: update Polish translation

pages.pl/common/7za.md
=> 7za: update Polish translation

pages.es/common/rkdeveloptool.md
=> rkdeveloptool: add Spanish translation

pages.es/common/yacc.md
=> yacc: add Spanish translation

pages/linux/hyprctl.md
- **Version of the command being documented (if known):** 0.41.0
=> hyprctl: add page

CLIENT-SPECIFICATION.md, contributing-guides/style-guide.md, pages/common/crystal.md, pages/common/immich-cli.md, pages/common/jbang.md, pages/common/mods.md, pages/common/set.md, pages/common/sf.md, pages/common/vboxmanage-registervm.md, pages/common/wfuzz.md, pages/common/wikit.md, pages/linux/grub-editenv.md, pages/linux/navi.md
See https://github.com/tldr-pages/tldr/pull/12914#pullrequestreview-2106150550
=> *: change `command line` to `command-line`

pages.es/linux/pw-metadata.md
=> pw-metadata: add Spanish translation

pages/linux/lsns.md
=> lsns: update more information link

pages/linux/lslogins.md
=> lslogins: update more information link

pages.tr/linux/ip-rule.md, pages/linux/ip-rule.md
=> ip-rule: update more information link

pages.tr/linux/ip-link.md, pages/linux/ip-link.md
=> ip-link: update more information link

pages/linux/e2undo.md
=> e2undo: update more information link

pages/linux/chrt.md
=> chrt: update more information link

pages/common/cypher-shell.md
- **Version of the command being documented (if known):** 5.20
=> cypher-shell: add page

pages.id/common/arduino-builder.md, pages.id/common/arduino.md, pages.id/common/argocd-app.md, pages.id/common/argocd.md, pages.id/common/argon2.md, pages.id/common/arp-scan.md, pages.id/common/arp.md, pages.id/common/arping.md
…arping: add Indonesian translations
The commands are `arduino`, `arduino-builder`, `argocd`, `argocd-app`, `argon2`, `arp`, `arp-scan`, `arping`.
=> common: add Indonesian translation

pages.nl/common/expand.md, pages.nl/windows/expand.md
=> expand: add Dutch translation

pages.nl/common/ed.md, pages.nl/osx/ed.md
=> ed: add Dutch translation

pages.nl/common/expr.md
=> expr: add Dutch translation

pages.de/linux/ip.md, pages.fr/linux/ip.md, pages.it/linux/ip.md, pages.pt_BR/linux/ip.md, pages.tr/linux/ip.md, pages/linux/ip.md
=> ip: update more information link

pages/common/pgrep.md
=> pgrep: update more information link

pages/linux/mandb.md
=> mandb: update more information link

pages/linux/lvdisplay.md
=> lvdisplay: update more information link

pages/linux/lvm.md
=> lvm: update more information link

pages/linux/lvresize.md
=> lvresize: update more information link

pages/linux/ethtool.md
=> ethtool: update more information link

pages/linux/numactl.md
=> numactl: update more infomation link

pages/linux/partx.md
=> partx: update more information link

pages.nl/common/uname.md, pages.nl/linux/uname.md, pages.nl/osx/uname.md
=> uname: add Dutch translation

pages.nl/common/uptime.md, pages.nl/osx/uptime.md
=> uptime: add Dutch translation

pages.nl/common/wc.md, pages.nl/osx/wc.md
=> wc: add Dutch translation

pages.nl/common/stat.md, pages.nl/osx/stat.md
=> stat: add Dutch translation

pages.nl/common/readlink.md, pages.nl/osx/readlink.md
=> readlink: add Dutch translation

pages.nl/common/groups.md, pages.nl/linux/groupadd.md, pages.nl/linux/groupdel.md, pages.nl/linux/groupmod.md
=> group*: add Dutch translation

pages.pl/android/bugreportz.md
Like it was changed in the English page in #12107 
=> bugreportz: update Polish translation

pages.pl/android/wm.md
=> wm: update Polish translation

pages.pl/common/import.md
=> import: add Polish translation

pages.pl/common/jfrog.md
=> jfrog: add Polish translation

pages.pl/common/identify.md
=> identify: add Polish translation

pages.pl/common/icontopbm.md
=> icontopbm: add Polish translation

pages.pl/common/gemtopbm.md
=> gemtopbm: add Polish translation

pages.pl/common/cups.md
=> cups: add Polish translation

pages.pl/common/convert.md
=> convert: add Polish translation

pages.pl/common/compare.md
=> compare: add Polish translation

pages.pl/common/bmptoppm.md
=> bpmtoppm: add Polish translation

pages.pl/common/lckdo.md
=> lckdo: add Polish translation

pages.pl/common/frp.md
=> frp: add Polish translation

pages.es/common/diff.md
=> diff: add Spanish translation

pages/linux/pvdisplay.md
=> pvdisplay: update more information link

pages/linux/pvcreate.md
=> pvcreate: update more information link

pages/osx/sntpd.md
=> sntpd: update more information link

pages/linux/vgdisplay.md
=> vgdisplay: update more information link

pages/linux/vgs.md
=> vgs: update more information link

pages.ca/linux/poweroff.md, pages.es/linux/poweroff.md, pages.id/linux/poweroff.md, pages.it/linux/poweroff.md, pages.pt_BR/linux/poweroff.md, pages.zh/linux/poweroff.md, pages/linux/poweroff.md
=> poweroff: update more information link

pages.nl/common/sleep.md, pages.nl/linux/sleep.md
=> sleep: add Dutch translation

pages.nl/linux/talk.md
=> talk: add Dutch translation

pages.nl/linux/tftp.md
=> tftp: add Dutch translation

pages.nl/linux/updatedb.md
=> updatedb: add Dutch translation

pages.nl/osx/port.md
=> port: add Dutch translation

pages.nl/common/tac.md, pages.nl/linux/tac.md
=> tac: add Dutch translation

pages/linux/lvremove.md
=> lvremove: update more information link

pages.zh/common/sleep.md, pages.zh/linux/sleep.md
=> sleep: add Chinese translation

pages/common/git-tag.md
I think this is a pretty crucial piece of information on how you use tags in Git.
=> git-tag: add example on how to push a tag

pages.pl/common/csslint.md
=> csslint: update Polish translation

pages.pl/common/aws.md
=> aws: update Polish translation

pages.pl/common/ls.md
=> ls: update Polish translation

pages.es/common/toipe.md
=> toipe: add Spanish translation

pages.es/linux/systool.md
=> systool: add Spanish translation

pages.nl/common/git-add.md
=> git-add: update Dutch translation

pages/common/knotc.md
- **Version of the command being documented (if known): 3.3**
=> knotc: add page

pages/osx/mist.md
- **Version of the command being documented (if known): 2.1**
=> mist: add page

pages.nl/linux/rsh.md
=> rsh: add Dutch translation

pages.nl/linux/runcon.md
=> runcon: add Dutch translation

pages.nl/linux/secon.md
=> secon: add Dutch translation

pages.nl/linux/rexec.md
=> rexec: add Dutch translation

pages.nl/linux/rlogin.md
=> rlogin: add Dutch translation

pages.nl/linux/rcp.md, pages/linux/rcp.md
=> rcp: add Dutch translation and fix placeholder

pages.nl/linux/nl.md
=> nl: add Dutch translation

pages.nl/linux/ptx.md
=> ptx: add Dutch translation

pages.nl/linux/libtool.md
=> libtool: add Dutch translation

pages.nl/linux/libtoolize.md
=> libtoolize: add Dutch translation

pages.nl/common/nice.md
=> nice: add Dutch translation

pages.nl/common/mkfifo.md
=> mkfifo: add Dutch translation

pages.nl/common/sha1sum.md, pages.nl/common/sha224sum.md, pages.nl/common/sha256sum.md, pages.nl/common/sha384sum.md, pages.nl/common/sha512sum.md
=> sha*sum: add Dutch translation

pages.nl/common/nl.md, pages/common/nl.md, pages/linux/nl.md
=> nl: add Dutch translation and align mnemonics

pages.nl/common/units.md
=> units: add Dutch translation

pages.nl/common/uniq.md
=> uniq: add Dutch translation

pages.nl/common/unexpand.md
=> unexpand: add Dutch translation

pages.nl/common/whois.md
=> whois: add Dutch translation

pages.nl/common/vdir.md
=> vdir: add Dutch translation

pages.nl/common/unlink.md
=> unlink: add Dutch translation

pages.nl/common/pathchk.md
=> pathchk: add Dutch translation

pages.nl/common/nohup.md
=> nohup: add Dutch translation

pages.nl/common/paste.md, pages/common/paste.md
=> paste: add Dutch translation and fix placeholders

pages.nl/common/od.md, pages/common/od.md
=> od: add Dutch translation and fix placeholders

pages.nl/common/which.md
=> which: add Dutch translation

pages.nl/common/numfmt.md, pages/common/numfmt.md
=> numfmt: add Dutch translation and fix placeholders

pages.nl/common/printf.md
=> printf: add Dutch translation

pages.nl/common/printenv.md
=> printenv: add Dutch translation

pages.nl/common/realpath.md
=> realpath: add Dutch translation

pages.nl/common/pr.md, pages/common/pr.md
=> pr: add Dutch translation and fix placeholders

pages.nl/common/xargs.md, pages/common/xargs.md
=> xargs: add Dutch translation and fix placeholder

pages.nl/common/nproc.md
=> nproc: add Dutch translation

pages/linux/fpsync.md
- **Version of the command being documented (if known):** 1.6.1
=> fpsync: add page

pages.nl/common/stty.md
=> stty: add Dutch translation

pages.nl/common/sum.md
=> sum: add Dutch translation

pages.nl/common/sort.md
=> sort: add Dutch translation

pages.nl/common/tar.md
=> tar: add Dutch translation

pages.nl/common/timeout.md
=> timeout: add Dutch translation

pages.nl/common/telnet.md
=> telnet: add Dutch translation

pages.nl/common/traceroute.md
=> traceroute: add Dutch translation

pages.nl/common/tr.md
=> tr: add Dutch translation

pages.nl/common/touch.md
=> touch: add Dutch translation

pages.nl/common/tsort.md
=> tsort: add Dutch translation

pages.nl/common/true.md
=> true: add Dutch translation

pages.nl/common/seq.md
=> seq: add Dutch translation

pages.nl/common/stdbuf.md, pages/common/stdbuf.md
=> stdbuf: add Dutch translation and fix placeholders

pages.nl/common/truncate.md, pages/common/truncate.md
=> truncate: add Dutch translation and fix placeholders

pages.pl/linux/zramctl.md, pages.pt_BR/linux/zramctl.md
Updates translations for #13200.
The Polish translation needs other fixes, but that's something for another PR.
=> zramctl: update translations

pages.es/linux/systool.md
=> systool: fix typos in Spanish translation

pages.es/common/kubectl-logs.md
=> kubectl-logs: add Spanish translation

pages/common/wafw00f.md
=> wafw00f: add page

pages.es/common/knotc.md
=> knotc: add Spanish translation

pages.es/linux/zramctl.md
=> zramctl: add Spanish translation

pages.es/common/zint.md
=> zint: add Spanish translation

pages.es/osx/mist.md
=> mist: add Spanish translation

pages.es/common/streamlit.md
=> streamlit: add Spanish translation

pages.es/linux/hyprpm.md
=> hyprpm: add Spanish translation

pages/common/xmake.md
=> xmake: add page

pages/common/id.md
=> id: edit page

pages.es/common/wafw00f.md
=> wafw00f: add Spanish translation

pages.zh/common/aircrack-ng.md
=> aircrack-ng: add Chinese translation

pages.es/common/cypher-shell.md
=> cypher-shell: add Spanish translation

pages.es/linux/portageq.md
=> portageq: add Spanish translation

pages/common/kubectl-config.md
=> kubectl-config: add page

pages.es/linux/poweroff.md
=> poweroff: update Spanish translation

pages/common/nxc-ssh.md
=> nxc ssh: add page

pages/common/nnn.md
- **Version of the command being documented (if known): 4.9**
=> nnn: add page

pages.es/common/mypy.md
=> mypy: add Spanish translation

pages/common/bats.md
- **Version of the command being documented (if known): 1.8.2**
=> bats: edit page

pages/linux/steamos-add-to-steam.md, pages/linux/steamos-dump-info.md, pages/linux/steamos-readonly.md, pages/linux/steamos-session-select.md, pages/linux/steamos-update.md
=> steamos-{session-select, readonly, dump-info, update}: add page

contributing-guides/style-guide.md
=> style-guide: update note on cases
