pages.es/common/virt-qemu-run.md

virt-qemu-run: add Spanish translation

---

pages.es/linux/auditctl.md

auditctl: add Spanish translation

---

pages.es/common/frpc.md

frpc: add Spanish translation

---

pages/common/jq.md

jq: add single binary version

---

pages.es/common/xmake.md

xmake: add Spanish translation

---

pages/common/gdown.md

- **Version of the command being documented (if known):** 4.7.3

gdown: add page

---

pages/linux/sbctl.md

sbctl: add page

---

pages.es/common/frps.md

frps: add Spanish translation

---

pages.es/common/frp.md

frp: add Spanish translation

---

pages.nl/linux/eselect-locale.md
pages.nl/linux/eselect-repository.md
pages.nl/linux/eselect.md

eselect*: add Dutch translation

---

pages.id/common/accelerate.md
pages.ko/common/accelerate.md
pages.nl/common/accelerate.md
pages.zh/common/accelerate.md

accelerate: lowercase page title of translations

---

pages/common/find.md

find: edit page

---

pages/common/msfconsole.md

- **Version of the command being documented (if known): 6.4.15-dev**

msfconsole: add page

---

pages/common/medusa.md

- **Version of the command being documented (if known): 2.2**

medusa: edit page

---

pages.zh/common/docker-run.md

docker-run: add Chinese translation

---

pages.es/common/id.md

id: add Spanish translation

---

pages.es/common/vulkaninfo.md

vulkaninfo: add Spanish translation

---

pages.fa/common/agate.md

agate: add Farsi translation

---

pages/linux/nsenter.md

nsenter: update page

---

pages/common/bitcoind.md

bitcoind: add page

---

pages/common/qalc.md

qalc: add page

---

pages.es/linux/eselect.md

eselect: add Spanish translation

---

pages/common/bitcoin-cli.md

bitcoin-cli: edit page

---

pages.pl/linux/fatlabel.md

fatlabel: update Polish translation

---

pages.pl/linux/line.md

line: update Polish translation

---

pages/common/dc.md

dc: edit page

---

pages/common/bc.md

bc: edit page

---

pages/common/aws-kendra.md

aws-kendra: add page

---

pages/linux/mkfs.erofs.md

mkfs.erofs: add page

---

pages/common/aws-kendra.md

aws-kendra: update link and conform to the style guide

---

pages.es/common/nnn.md

nnn: add Spanish translation

---

pages.es/linux/eselect-repository.md

eselect-repository: add Spanish translation

---

pages.es/common/huggingface-cli.md

huggingface-cli: add Spanish translation

---

pages/common/aws-acm-pca.md

aws-acm-pca: add page

---

pages/common/aws-amplify.md

aws-amplify: add page

---

pages/common/xargs.md

Resolves #13333
- **Version of the command being documented (if known):** all

xargs: add -n1 example

---

pages/common/ping.md

ping: edit page

---

pages/common/aws-accessanalyzer.md

aws-accessanalyzer: add page

---

pages/common/doppler-projects.md
pages/common/doppler-run.md
pages/common/doppler-secrets.md
pages/common/doppler.md

- **Version of the command being documented (if known): idk 😐**

doppler: add page

---

pages.nl/linux/httpie.md
pages.nl/osx/httpie.md

httpie: add Dutch translation

---

pages.es/linux/mkfs.erofs.md

mkfs.erofs: add Spanish translation

---

pages.es/common/aws-acm.md

aws-acm: add Spanish translation

---

pages/linux/kdesrc-build.md
pages/linux/kdesrc-run.md

kdesrc-build: add run example and update link, kdesrc-run: delete page

---

pages/common/ntfyme.md

ntfyme: add common page

---

pages/common/xargs.md

xargs: improve example command

---

pages/linux/dysk.md

Added new page for dysk in linux
- dysk 2.8.2

dysk: add page

---

pages.es/linux/sbctl.md
pages/linux/sbctl.md

https://github.com/Foxboron/sbctl/releases/tag/0.15
> Move from `/usr/share/secureboot` to `/var/lib/sbctl`

sbctl: update page

---

pages/common/nxc-ftp.md

nxc-ftp: add page

---

pages/common/nxc-ldap.md

nxc-ldap: add page

---

pages/common/nxc-smb.md

nxc-smb: add page

---

pages/common/nxc.md

nxc: add page

---

pages.pt_BR/linux/ascii.md

ascii: add Portuguese translation

---

pages/common/wakeonlan.md

wakeonlan: add page

---

pages/common/crackle.md

crackle: add page

---

pages/linux/cu.md

cu: add page

---

pages.es/osx/iostat.md

iostat: add Spanish translation

---

pages.es/common/bitcoind.md

bitcoind: add Spanish translation

---

pages.es/common/aws-kendra.md

aws-kendra: add Spanish translation

---

pages/common/git-stash.md

git-stash: convert options to longform

---

pages.nl/common/exit.md
pages.nl/windows/exit.md

exit: add Dutch translation

---

pages.nl/common/exec.md
pages.nl/linux/exec.md

exec: add Dutch translation

---

pages.nl/common/curl.md

curl: add Dutch translation

---

pages.nl/common/export.md
pages.nl/linux/export.md

export: add Dutch translation

---

pages.nl/common/clear.md

clear: add Dutch translation

---

pages.nl/common/coproc.md
pages.nl/linux/coproc.md

coproc: add Dutch translation

---

pages.nl/common/bird.md
pages.nl/osx/bird.md

bird: add Dutch translation

---

pages.nl/common/at.md
pages.nl/linux/at.md

at: add Dutch translation

---

pages.nl/common/find.md

find: add Dutch translation

---

pages.nl/common/finger.md
pages.nl/windows/finger.md

finger: add Dutch translation

---

pages.nl/common/xargs.md

xargs: update Dutch translation

---

pages.nl/common/certutil.md
pages.nl/windows/certutil.md

certutil: add Dutch translation

---

pages.nl/common/for.md
pages.nl/windows/for.md

for: add Dutch translation

---

pages.nl/common/fc.md
pages.nl/windows/fc.md

fc: add Dutch translation

---

pages.nl/linux/iostat.md
pages.nl/osx/iostat.md

iostat: add Dutch translation

---

pages.nl/common/killall.md
pages.nl/linux/killall.md

killall: add Dutch translation

---

pages.nl/common/jobs.md
pages.nl/linux/jobs.md

jobs: add Dutch translation

---

pages.nl/common/ipcs.md
pages.nl/linux/ipcs.md

ipcs: add Dutch translation

---

pages.nl/linux/dmesg.md
pages.nl/osx/dmesg.md

dmesg: add Dutch translation

---

pages.nl/common/if.md
pages.nl/windows/if.md

if: add Dutch translation

---

pages.nl/linux/dir.md
pages/linux/dir.md

dir: add Dutch translation and fix placeholder

---

pages.nl/osx/ipconfig.md
pages.nl/windows/ipconfig.md

ipconfig: add Dutch translation

---

pages.nl/common/bc.md
pages.nl/osx/bc.md

bc: add Dutch translation

---

pages.nl/common/duc.md
pages.nl/linux/duc.md
pages.pt_BR/common/duc.md
pages/common/duc.md

duc: add Dutch translation and fix long description

---

pages.nl/linux/fsck.md
pages.nl/osx/fsck.md

fsck: add Dutch translation

---

pages.nl/linux/head.md
pages.nl/osx/head.md

head: add Dutch translation

---

pages.nl/linux/xed.md
pages.nl/osx/xed.md

xed: add Dutch translation

---

pages.nl/linux/caffeinate.md
pages.nl/osx/caffeinate.md

caffeinate: add Dutch translation

---

pages.nl/osx/base64.md

base64: add Dutch translation

---

pages.nl/windows/cmd.md

cmd: add Dutch translation

---

pages.nl/linux/cat.md
pages.nl/osx/cat.md

cat: add Dutch translation

---

pages.nl/linux/chfn.md

chfn: add Dutch translation

---

pages.nl/linux/chsh.md

chsh: add Dutch translation

---

pages.nl/linux/ac.md

ac: add Dutch translation

---

pages.nl/osx/arch.md

arch: add Dutch translation

---

pages.nl/linux/archey.md
pages.nl/osx/archey.md

archey: add Dutch translation

---

pages.nl/common/ping.md

ping: update Dutch translation

---

pages/common/aws-ce.md

aws-ce: fix typo in title

---

pages/linux/plasmashell.md

plasmashell: add page

---

pages/common/mv.md

mv: update options to longform

---

MAINTAINERS.md

MAINTAINERS: add @debghs as a collaborator

---

pages.ko/common/git-ls-files.md
pages.ko/common/git-ls-remote.md
pages.ko/common/git-ls-tree.md
pages.ko/common/git-remote.md
pages.pt_BR/linux/ascii.md

pages.*: fix typo in more information

---

pages/osx/mas.md

mas: add `lucky`, `outdated`

---

pages.es/common/aws-ce.md

aws-ce: fix Spanish title

---

pages.nl/common/netstat.md
pages.nl/osx/netstat.md
pages.nl/windows/netstat.md

netstat: add Dutch translation

---

pages.nl/common/last.md
pages.nl/linux/last.md

last: add Dutch translation

---

pages.nl/osx/lpstat.md

lpstat: add Dutch translation

---

pages.nl/common/lex.md
pages.nl/linux/lex.md

lex: add Dutch translation

---

pages.nl/common/more.md
pages.nl/linux/more.md
pages.nl/windows/more.md

more: add Dutch translation

---

pages.nl/common/man.md
pages.nl/linux/man.md

man: add Dutch translation

---

pages.nl/common/lldb.md
pages.nl/osx/lldb.md

lldb: add Dutch translation

---

pages.nl/osx/open.md

open: add Dutch translation

---

pages.nl/common/nvm.md
pages.nl/windows/nvm.md

nvm: add Dutch translation

---

pages.it/windows/mount.md
pages.nl/common/mount.md
pages.nl/windows/mount.md
pages/windows/mount.md

mount: add Dutch translation and fix placeholder

---

MAINTAINERS.md

Closes #13451
Hopefully I did it correctly

MAINTAINERS: add @jxu

---

pages/linux/bcachefs.md

bcachefs: add runtime replication examples

---

pages.zh/linux/wg.md

wg: add Chinese translation

---

pages/linux/man.md

man: add clarification to --html

---

pages/common/mv.md

mv: improve example command

---

pages.nl/common/http.md

http: add Dutch translation

---

pages.nl/common/mv.md

mv: update Dutch translation

---

pages/linux/pacgraph.md

- **Version of the command being documented (if known):** 20110629-8

pacgraph: add page

---

pages/common/mkfifo.md

mkfifo: add usage examples

---

pages.nl/common/mkfifo.md

mkfifo: update Dutch translation

---

pages/common/nuclei.md

- **Version of the command being documented (if known): 3.3.0**

nuclei: edit page

---

pages.nl/common/http.md
pages.nl/common/httpie.md

http, httpie: update Dutch translation

---

pages.nl/common/awk.md

awk: update Dutch translation

---

pages/linux/cjxl.md
pages/linux/djxl.md

cjxl, djxl: add page

---

pages/common/bfs.md

bfs: add page

---

pages/common/mitmproxy.md

- **Version of the command being documented (if known): 10.4.2**

mitmproxy: update page

---

pages/linux/flatpak-run.md

flatpak-run: add page

---

pages/linux/flatpak.md

fixes app id names
e.g. com.spotify.Client instead of just spotify

flatpak: update page

---

pages/common/ya.md
pages/common/yazi.md

ya, yazi: add pages

---

pages/common/pulumi.md

pulumi: update docs link

---

pages/linux/dos2unix.md
pages/linux/mac2unix.md
pages/linux/unix2dos.md
pages/linux/unix2mac.md

dos2unix,mac2unix,unix2dos,unix2mac: update pages

---

pages.zh/common/fastboot.md

fastboot: add Chinese translation

---

pages/common/http.md

- **Version of the command being documented (if known): 3.2.1**

http: update page

---

pages/common/pulumi-up.md

pulumi-up: add --suppress-outputs example

---

pages/common/pulumi.md

pulumi: add login --local example

---

pages.es/common/nxc-ftp.md

nxc-ftp: add Spanish translation

---

pages.es/common/mkfifo.md

mkfifo: add Spanish translation

---

pages.es/common/ipscan.md
pages.es/linux/pacgraph.md

ipscan, pacgraph: add Spanish translation

---

.github/CODEOWNERS

CODEOWNERS: add @debghs for Hindi pages

---

pages.pl/android/am.md

Translated "intent" to "intencja" based on the android docs.

am: update Polish translation

---

pages.es/linux/kde-builder.md

kde-builder: add Spanish translation

---

pages.es/linux/flatpak.md

flatpak: add Spanish translation

---

pages.es/linux/flatpak-run.md

flatpak-run: add Spanish translation

---

pages/linux/rm.md

rm: add safe directory removal example

---

pages/common/passwd.md

passwd: add longform options

---

pages.ko/common/adb-shell.md
pages.ko/common/adguardhome.md

adb-shell, adguardgome: update Korean translation

---

pages.es/common/bfs.md

bfs: add Spanish translation

---

pages/common/hugo-server.md

hugo-server: add page

---

pages/linux/wofi.md

- **Version of the command being documented (if known):** v1.4.1

wofi: add page

---

scripts/check-pr.sh

https://github.com/tldr-pages/tldr/pull/13599#issuecomment-2329910492

CI: mute output from Python script

---

pages.ko/common/amass-enum.md
pages.ko/common/amass-intel.md
pages.ko/common/amass.md

amass*: add Korean translation

---

pages.fr/linux/dos2unix.md

dos2unix: add French translation

---

pages/common/trash-cli.md
pages/linux/trash.md

trash: adjust wording, trash-cli: make into an alias of trash

---

pages.de/common/npm.md
pages.es/common/npm.md
pages.id/common/npm.md
pages.ko/common/npm.md
pages.pt_BR/common/npm.md
pages/common/npm.md

npm: add --yes to init and add shortform options

---

pages.de/common/docker-build.md
pages.fr/common/docker-build.md
pages.id/common/docker-build.md
pages.it/common/docker-build.md
pages.ja/common/docker-build.md
pages.ko/common/docker-build.md
pages.pt_BR/common/docker-build.md
pages.tr/common/docker-build.md
pages.zh/common/docker-build.md
pages/common/docker-build.md

docker-build: update documentation link

---

pages.nl/common/pngcheck.md
pages.nl/linux/pngcheck.md
pages/common/pngcheck.md

pngcheck: add Dutch translation and fix placeholder

---

pages.nl/common/bc.md
pages.nl/common/netcat.md
pages.nl/common/touch.md
pages.nl/common/trash-cli.md

bc, netcat, touch: update Dutch more info link, trash-cli: add Dutch translation

---

pages/linux/sfdisk.md

sfdisk: add page

---

pages.fr/common/docker-commit.md
pages.pt_BR/common/docker-commit.md
pages/common/docker-commit.md

docker-commit: update documentation link

---

pages.nl/linux/trash.md
pages.tr/linux/trash.md
pages/linux/trash.md

trash: add Dutch translation and fix placeholder

---

pages/common/xh.md

- **Version of the command being documented (if known): 0.22.2**

xh: update page

---

pages.nl/linux/reboot.md
pages.nl/osx/reboot.md

reboot: add Dutch translation

---

README.md

README: add Mastodon badge

---

pages/common/ls.md

ls: refresh descriptions

---

pages/common/az.md

az: add examples

---

pages/common/dircolors.md

dircolors: add example to print the colors

---

pages.de/common/docker-compose.md
pages.es/common/docker-compose.md
pages.fr/common/docker-compose.md
pages.id/common/docker-compose.md
pages.it/common/docker-compose.md
pages.ja/common/docker-compose.md
pages.ko/common/docker-compose.md
pages.ne/common/docker-compose.md
pages.pt_BR/common/docker-compose.md
pages.tr/common/docker-compose.md
pages/common/docker-compose.md

docker-compose: update documentation link

---

pages.fr/common/docker-diff.md
pages.nl/common/docker-container-diff.md
pages.nl/common/docker-diff.md
pages.pl/common/docker-container-diff.md
pages/common/docker-container-diff.md
pages/common/docker-diff.md

docker-container-diff: update documentation link

---

pages/linux/mkfs.xfs.md

mkfs.xfs: add page

---

pages.ko/common/az-account.md
pages.ko/common/az-acr.md
pages.ko/common/az-advisor.md
pages.ko/common/az-aks.md
pages.ko/common/az-apim.md
pages.ko/common/az-appconfig.md
pages.ko/common/az-bicep.md
pages.ko/common/az-config.md
pages.ko/common/az-devops.md
pages.ko/common/az-feedback.md

az-*: add Korean translation

---

pages/common/mysql_secure_installation.md

mysql_secure_installation: add page

---

pages/common/unzip.md

unzip: improve example clarity

---

pages/linux/chat.md

chat: add page

---

pages.fr/common/docker-rm.md
pages.nl/common/docker-container-remove.md
pages.nl/common/docker-container-rm.md
pages.nl/common/docker-rm.md
pages.pl/common/docker-container-remove.md
pages.pl/common/docker-container-rm.md
pages/common/docker-container-remove.md
pages/common/docker-container-rm.md
pages/common/docker-rm.md

Docs links for aliases were also updated.

docker-rm: update documentation link

---

pages.de/common/docker-container.md
pages.fr/common/docker-container.md
pages.it/common/docker-container.md
pages.ko/common/docker-container.md
pages.pt_BR/common/docker-container.md
pages/common/docker-container.md

docker-container: update documentation link

---

pages/common/aws-ce.md

aws-ce: update page

---

pages.nl/linux/chsh.md
pages/linux/chsh.md

chsh: remove sudo where not needed

---

pages/linux/bcachefs-device.md
pages/linux/bcachefs.md

bcachefs: update header; bcachefs-device: add page

---

pages.nl/linux/rm.md

rm: add Dutch translation

---

pages.nl/linux/rename.md
pages.nl/osx/rename.md

rename: add Dutch translation

---

pages.nl/common/az.md

az: update Dutch translation

---

pages.nl/common/dircolors.md

dircolors: update Dutch translation

---

pages/linux/ceph.md

ceph: fix link

---

pages.ko/common/bmptopnm.md
pages.ko/common/bmptoppm.md
pages.ko/common/bob.md

bmptopnm, bmptoppm, bob: add Korean translation

---

pages.ko/common/brew-autoremove.md
pages.ko/common/brew-bundle.md
pages.ko/common/brew-install.md
pages.ko/common/brew-list.md
pages.ko/common/brew-outdated.md
pages.ko/common/brew-search.md
pages.ko/common/brew-uninstall.md
pages.ko/common/brew-update.md
pages.ko/common/brew-upgrade.md

brew-*: add Korean translation

---

pages.es/common/read.md

read: add Spanish translation

---

pages.es/common/passwd.md

passwd: add Spanish translation

---

pages.es/linux/sslstrip.md

sslstrip: add Spanish translation

---

pages.es/common/pants.md

pants: add Spanish translation

---

pages.ko/common/aws-cloudformation.md
pages.ko/common/aws-codeartifact.md
pages.ko/common/aws-codecommit.md
pages.ko/common/aws-cognito-idp.md

aws*: add Korean translation

---

pages.nl/common/pwd.md
pages.nl/linux/pwd.md

pwd: add Dutch translation

---

pages.nl/common/ps.md
pages.nl/osx/ps.md

ps: add Dutch translation

---

pages.nl/linux/print.md
pages.nl/windows/print.md

print: add Dutch translation

---

pages.nl/windows/powershell.md

powershell: add Dutch translation

---

pages.nl/common/pushd.md
pages.nl/windows/pushd.md

pushd: add Dutch translation

---

pages.nl/common/popd.md
pages.nl/windows/popd.md

popd: add Dutch translation

---

pages.nl/linux/rpcinfo.md
pages.nl/windows/rpcinfo.md

rpcinfo: add Dutch translation

---

pages.nl/common/rmdir.md
pages.nl/common/route.md
pages.nl/linux/rmdir.md
pages.nl/osx/route.md

rmdir, route: add Dutch translation

---

pages.nl/common/renice.md
pages.nl/linux/renice.md

renice: add Dutch translation

---

pages.es/common/toipe.md

toipe: fix verbs in Spanish translation

---

pages/common/pulumi-preview.md

pulumi-preview: add page

---

pages/linux/xfs_repair.md

xfs_repair: add page

---

pages.zh/linux/timedatectl.md

timedatectl: add Chinese translation

---

MAINTAINERS.md

This PR closes https://github.com/tldr-pages/tldr/issues/13781

MAINTAINERS: add @nelsonfigueroa as collaborator

---

pages.pt_BR/linux/bspc.md

bspc: add Brazilian Portuguese translation

---

MAINTAINERS.md

This PR closes https://github.com/tldr-pages/tldr/issues/13780

MAINTAINERS: add @LiLittleCat as collaborator

---

pages/common/gdal_translate.md
pages/common/gdaladdo.md
pages/common/gdaldem.md
pages/common/gdalwarp.md

gdal*: fix broken links

---

pages.fr/common/docker-load.md
pages.pt_BR/common/docker-load.md
pages/common/docker-load.md

docker-load: update documentation link

---

pages.de/common/docker-inspect.md
pages.fr/common/docker-inspect.md
pages.it/common/docker-inspect.md
pages.pt_BR/common/docker-inspect.md
pages.tr/common/docker-inspect.md
pages/common/docker-inspect.md

docker-inspect: update documentation link

---

pages.de/common/docker-images.md
pages.fr/common/docker-images.md
pages.it/common/docker-images.md
pages.ko/common/docker-images.md
pages.pl/common/docker-images.md
pages.pt_BR/common/docker-images.md
pages.tr/common/docker-images.md
pages/common/docker-images.md

docker-images: update documentation link

---

pages.ko/common/aws-kinesis.md
pages.ko/common/aws-lambda.md
pages.ko/common/aws-lightsail.md
pages.ko/common/aws-pricing.md
pages.ko/common/aws-quicksight.md
pages.ko/common/aws-rds.md
pages.ko/common/aws-route53.md
pages.ko/common/aws-s3-rm.md

aws-*: add Korean translation

---

pages/linux/mkfs.bcachefs.md

mkfs.bcachefs: add page

---

pages.nl/osx/tail.md
pages/osx/tail.md

tail: fix link

---

pages.nl/common/clang.md

clang: update Dutch translation

---

pages.nl/common/gcc.md

gcc: update Dutch translation

---

pages.nl/common/clang++.md

clang++: update Dutch translation

---

pages.es/common/git-rev-list.md

git-rev-list: update Spanish translation

---

pages.es/linux/togglesebool.md

togglesebool: add Spanish translation

---

pages.es/common/apkleaks.md

apkleaks: add Spanish translation

---

pages.es/linux/pw-config.md

pw-config: add Spanish translation

---

pages.es/linux/xfs_repair.md

xfs_repair: add Spanish translation

---

pages.es/osx/tail.md

tail: add Spanish translation

---

pages.es/common/git-reflog.md

git-reflog: update Spanish translation

---

pages/common/git-reflog.md

git-reflog: correct example

---

pages/linux/df.md

df: add longform options

---

pages.es/common/rubocop.md

rubocop: update Spanish translation

---

pages.es/common/git-revert.md

git-revert: update Spanish translation

---

pages.es/common/git-rebase.md

git-rebase: update Spanish translation

---

pages.es/common/git-shortlog.md

git-shortlog: update Spanish translation

---

pages.es/common/git-svn.md

git-svn: update Spanish translation

---

pages.id/common/fastd.md
pages.id/common/ivpn.md
pages.id/common/mozillavpn.md
pages.id/common/mullvad.md
pages.id/common/warp-cli.md
pages/common/fastd.md
pages/common/ivpn.md
pages/common/mozillavpn.md
pages/common/mullvad.md
pages/common/warp-cli.md

fastd, ivpn, mozillavpn, mullvad, warp-cli: propagate "See Also" information, add Indonesian translations

---

pages.nl/linux/df.md

df: update Dutch translation

---

pages/osx/safeejectgpu.md

safeejectgpu: fix link

---

pages.pt_BR/common/docker-tag.md
pages/common/docker-tag.md

docker-tag: update documentation link

---

pages.nl/common/linode-cli.md
pages.pl/common/linode-cli.md
pages/common/linode-cli.md

linode-cli: update documentation link

---

pages/common/linode-cli-tickets.md

linode-cli-tickets: update documentation link 

---

pages/common/linode-cli-events.md

linode-cli-events: update documentation link

---

pages/linux/vcgencmd.md

vcgencmd: update documentation link

---

pages.fr/common/docker-volume.md
pages.pt_BR/common/docker-volume.md
pages/common/docker-volume.md

docker-volume: update documentation link

---

pages.pt_BR/common/docker-update.md
pages/common/docker-update.md

docker-update: update documentation link

---

pages/common/nettacker.md

nettacker: add page

---

pages.es/common/git-blame.md
pages.es/common/git-branch.md
pages.es/common/git-bundle.md
pages.es/common/git-clean.md
pages.es/common/git-commit.md
pages.es/common/git-lfs.md

Only changed the page if it was a trivial change (short option -> short|long option).

git-*: update Spanish translation

---

pages.es/linux/evtest.md

evtest: add Spanish translation

---

pages.es/linux/rpi-otp-private-key.md
pages/linux/rpi-otp-private-key.md

rpi-otp-private-key: update documentation link

---

pages/common/msgfmt.md
pages/common/msgunfmt.md

msgfmt, msgunfmt: add page

---

pages.ta/android/bugreportz.md

bugreportz: update Tamil translation

---

README.md
contributing-guides/style-guide.md
contributing-guides/style-guide.zh.md

As previously discussed in the chatroom, will make a archive issue for the same.
https://github.com/tldr-pages/tldr/issues/13915

feat: update clients wiki to new link

---

LICENSE.md

LICENSE: switch to https

---

contributing-guides/maintainers-guide.md

https://github.com/tldr-pages/tldr/pull/13839#discussion_r1782717789

maintainers-guide: simplify description of CODEOWNERS

---

pages/common/onefetch.md

onefetch: add page

---

pages.es/common/dotenvx.md

dotenvx: add Spanish translation

---

MAINTAINERS.md

Closes https://github.com/tldr-pages/tldr/issues/13956

MAINTAINERS: add @Managor as Org member

---

.github/CODEOWNERS
MAINTAINERS.md

[Invited on PR 13946 ](https://github.com/tldr-pages/tldr/issues/13946)

CODEOWNERS: add @renie for pt_BR, MAINTAINERS: add @renie as collaborator

---

pages/linux/eselect-kernel.md
pages/linux/eselect-profile.md

eselect-{kernel,profile}: add page

---

pages/common/ollama.md

ollama: update page

---

pages/common/fping.md

fping: update page

---

pages/linux/eselect.md

There is already an example on the page, but it wouldn't hurt to include it in the description as well, like on all the other pages.

eselect: update page

---

pages.es/linux/ceph.md

ceph: add Spanish translation

---

pages.es/linux/journalctl.md

journalctl: add Spanish translation

---

pages/common/pest.md

pest: add examples for Pest 3.x

---

package-lock.json
package.json

**Changelog**: https://github.com/tldr-pages/tldr-lint/blob/main/CHANGELOG.md#v0016---2024-10-04

chore: bump tldr-lint to v0.0.16, update lockfile

---

pages.pt_BR/linux/apport-bug.md
pages.pt_BR/linux/cgclassify.md
pages.pt_BR/linux/cgcreate.md
pages.pt_BR/linux/cgexec.md
pages.pt_BR/linux/ip-route-show.md
pages.pt_BR/linux/megatools-dl.md

pages.pt_BR/linux/*: add Portuguese Brazilian translations

---

pages/windows/scoop.md

mention bucket subcommand documentation
- **Version of the command being documented (if known):** v0.5.2

scoop: add subcommand mention

---

pages/linux/qm.md
pages/linux/qmrestore.md

qm, qmrestore: edit page

---

pages/linux/waydroid.md

waydroid: update page

---

pages/common/shotcut.md

- **Version of the command being documented (if known):** 24.09.13

shotcut: add page

---

pages/linux/zdump.md

zdump: add page

---

pages/linux/ifstat.md

ifstat: add page

---

pages/common/socat.md

socat: add sudo

---

pages.es/common/az-vm.md

az-vm: update Spanish translation

---

pages.es/common/aws-ce.md

aws-ce: update Spanish translation

---

pages.es/common/awk.md

awk: update Spanish translation

---

pages/common/redshift.md

- **Version of the command being documented (if known):** redshift 1.12
Added the -P flag to the oneshot example since otherwise successive redshift calls with -O would stack the temperature changes on top of each other. Also added mnemonics for that example.

redshift: edit page

---

pages/common/wget2.md

- **Version of the command being documented (if known):** 2.1.0

wget2: add page

---

pages/common/^.md

^: add example

---

pages/linux/sestatus.md

https://github.com/tldr-pages/tldr/issues/11896

sestatus: add page

---

pages/common/fc.md

fc: refresh page

---

pages/common/adb-reboot.md

adb reboot: add page

---

pages/linux/speaker-test.md

speaker-test: add page

---

pages.nl/common/^.md

^: update Dutch translation

---

pages.nl/common/fc.md

fc: update Dutch translation

---

pages.nl/windows/sdelete.md
pages.nl/windows/sdelete64.md

sdelete, sdelete64: add Dutch translation

---

pages/common/!.md

!: add examples

---

pages/common/mkfifo.md

mkfifo: add terminal share example

---

pages/common/pulumi-stack.md

pulumi-stack: add page

---

pages/common/nice.md

nice: edit page

---

pages/common/pandoc.md

pandoc: adjust order and make the example what newbies would most likely use it for

---

pages.pl/linux/caffeinate.md
pages.pl/linux/ip6tables.md
pages.pl/linux/lz.md

lz, caffeinate, ip6tables: add Polish translation

---

pages/common/adb-devices.md

https://github.com/tldr-pages/tldr/issues/13997

adb-device: add page

---

pages.ko/windows/whoami.md
pages.ko/windows/winget.md
pages.ko/windows/wmic.md

whoami, winget, wmic: add Korean translation

---

pages.pt_BR/common/7z.md
pages.pt_BR/common/7za.md
pages.pt_BR/common/7zr.md
pages.pt_BR/common/awk.md
pages.pt_BR/common/aws-codeartifact.md
pages.pt_BR/common/aws-iam.md
pages.pt_BR/common/aws-lambda.md
pages.pt_BR/common/banner.md
pages.pt_BR/common/chromium.md
pages.pt_BR/common/cmatrix.md
pages.pt_BR/common/cups-config.md

pages.pt_BR/common/*: update out-of-date translations

---

pages/common/set.md

set: list all modes

---

pages/common/npm-outdated.md

npm-outdated: add page

---

pages.nl/common/just.md
pages.nl/common/lckdo.md
pages.nl/common/moreutils.md
pages.nl/common/mscore.md
pages.nl/common/open.md
pages.nl/common/pnmscale.md
pages.nl/common/ppmquant.md
pages.nl/common/ps-nvm.md
pages.nl/common/vi.md
pages.nl/common/ykman.md
pages.nl/linux/eselect.md
pages.nl/linux/lid.md
pages.nl/linux/systemd-resolve.md
pages.nl/linux/tailf.md
pages.nl/linux/xbps.md
pages.nl/windows/cd.md
pages.nl/windows/chdir.md
pages.nl/windows/mv.md
pages.nl/windows/pwd.md
pages.nl/windows/rmdir.md

pages.nl/*: rephrase Dutch alias pages

---

pages/common/greater-than.md

>: add file emptying example

---

pages.es/osx/look.md

look: update Spanish translation

---

pages/linux/chronyc.md

chronyc: fix more info link

---

pages.es/osx/caffeinate.md

caffeinate: update Spanish translation

---

pages.nl/linux/dnf-config-manager.md
pages.nl/linux/yum-config-manager.md

*-config-manager: add Dutch translation

---

pages.ko/common/cargo.md
pages.ko/common/rustc.md
pages.ko/common/rustdoc.md
pages.ko/common/rustfmt.md
pages.ko/common/rustic.md
pages.ko/common/rustscan.md
pages.ko/common/rustup-check.md
pages.ko/common/rustup-completions.md
pages.ko/common/rustup-component.md
pages.ko/common/rustup-default.md
pages.ko/common/rustup-doc.md
pages.ko/common/rustup-help.md
pages.ko/common/rustup-init.sh.md
pages.ko/common/rustup-install.md
pages.ko/common/rustup-man.md
pages.ko/common/rustup-override.md
pages.ko/common/rustup-run.md
pages.ko/common/rustup-self.md
pages.ko/common/rustup-set.md
pages.ko/common/rustup-show.md
pages.ko/common/rustup-target.md
pages.ko/common/rustup-toolchain.md
pages.ko/common/rustup-update.md
pages.ko/common/rustup-which.md
pages.ko/common/rustup.md

cargo,rust*: add and update Korean translation

---

pages.pt_BR/common/ar.md
pages.pt_BR/common/clamdscan.md
pages.pt_BR/common/clamscan.md
pages.pt_BR/common/clang++.md
pages.pt_BR/common/clang-format.md
pages.pt_BR/common/clang-tidy.md
pages.pt_BR/common/clang.md
pages.pt_BR/common/clangd.md
pages.pt_BR/common/crontab.md
pages.pt_BR/common/fossil-add.md
pages.pt_BR/common/fossil-commit.md
pages.pt_BR/common/fossil-init.md
pages.pt_BR/common/fossil-rm.md
pages.pt_BR/common/fossil.md
pages.pt_BR/common/freshclam.md
pages.pt_BR/common/gh-codespace.md

pages.pt_BR/common/*: add Brazilian Portuguese translation

---

pages/linux/pkgfile.md

pkgfile: fix more info link

---

pages.ko/common/cups-config.md
pages.ko/common/cups.md
pages.ko/common/cupsaccept.md
pages.ko/common/cupsctl.md
pages.ko/common/cupsd.md
pages.ko/common/cupsdisable.md
pages.ko/common/cupsenable.md
pages.ko/common/cupsreject.md
pages.ko/common/cupstestppd.md

cups*: add Korean translation

---

pages/linux/unopkg.md

unopkg: add page

---

pages/common/aws-sso.md

aws-sso: add page

---

pages/linux/pdfattach.md

pdfattach: add page

---

pages/linux/abrt-action-analyze-backtrace.md

abrt-action-analyze-backtrace: add page

---

pages/linux/diffimg.md

diffimg: add page

---

pages/linux/abrt-action-analyze-c.md

abrt-action-analyze-c: add page

---

pages/linux/pdfdetach.md

pdfdetach: add page

---

pages/common/onionsearch.md

onionsearch: add page

---

pages/common/less-than.md

Closes https://github.com/tldr-pages/tldr/issues/12694

<: add here strings and documents

---

pages.ko/common/aws-sso.md
pages.ko/common/bind.md

aws-sso, bind: add Korean translation

---

pages/common/wait.md

wait: add an example for jobs

---

pages.ko/common/crane-append.md
pages.ko/common/crane-auth.md
pages.ko/common/crane-blob.md
pages.ko/common/crane-catalog.md
pages.ko/common/crane-config.md
pages.ko/common/crane-copy.md
pages.ko/common/crane-delete.md
pages.ko/common/crane-digest.md
pages.ko/common/crane-export.md
pages.ko/common/crane-flatten.md
pages.ko/common/crane-index-append.md
pages.ko/common/crane-index-filter.md
pages.ko/common/crane-index.md
pages.ko/common/crane-ls.md
pages.ko/common/crane-manifest.md
pages.ko/common/crane-mutate.md
pages.ko/common/crane-pull.md
pages.ko/common/crane-push.md
pages.ko/common/crane-rebase.md
pages.ko/common/crane-registry.md
pages.ko/common/crane-tag.md
pages.ko/common/crane-validate.md
pages.ko/common/crane-version.md
pages.ko/common/crane.md
pages.ko/common/createdb.md

crane*, createdb: add Korean translation

---

pages.id/common/adb-devices.md
pages.id/common/adb-reboot.md
pages.id/common/asciitopgm.md
pages.id/common/atktopbm.md
pages.id/common/cal.md
pages.id/common/gemtopbm.md
pages.id/common/gemtopnm.md
pages.id/common/pbmtoatk.md
pages.id/freebsd/cal.md

common/*, freebsd/cal: add Indonesian translations

---

pages/linux/betterlockscreen.md

betterlockscreen: fix link

---

pages.zh/android/logcat.md

logcat: update Chinese translation

---

package-lock.json
pages.fr/common/cargo-add.md
pages.fr/common/cargo-bench.md
pages.fr/common/cargo-build.md
pages.fr/common/cargo-init.md

cargo-add, cargo-bench, cargo-build, cargo-init: add French translation

---

pages/common/nvim.md
pages/common/vim.md

vim, nvim: add ZZ in save and exit example 

---

pages.nl/common/time.md
pages/common/time.md

time: update Dutch translation and titlecase Bash

---

pages.nl/osx/base64.md

base64: update Dutch translation

---

pages.nl/linux/bleachbit.md
pages.nl/windows/bleachbit.md

bleachbit: add Dutch translation

---

pages/linux/dpkg.md

apt: add purge command

---

pages/common/zapier-build.md

- **Version of the command being documented (if known): 15.16.1**
#14172

zapier-build: add page

---

pages/common/zapier-analytics.md

- **Version of the command being documented (if known): 15.16.1**
#14172

zapier-analytics: add page

---

pages/common/gcrane.md

Fix small issue with `gcrane` command

gcrane: fix typo

---

pages/common/az-image.md

az-image: add page

---

pages/common/az-logicapp.md

az-logicapp: add page

---

pages.zh/common/docker.md
pages.zh_TW/common/docker.md

- **Version of the command being documented (if known):** N/A
Catch up its English version.

docker: update Chinese translations

---

pages.ko/common/fastd.md
pages.ko/common/fastfetch.md
pages.ko/common/fastlane.md
pages.ko/common/fastmod.md

fa*: add Korean translation

---

pages/common/gcloud-container.md

gcloud-container: add describe command

---

pages/common/mail.md

mail: add interactive example

---

pages/common/less-than.md

<: add clarification

---

pages.nl/windows/bleachbit_console.md

bleachbit_console: add Dutch translation

---

pages.nl/linux/aa-complain.md
pages.nl/linux/aa-disable.md
pages.nl/linux/aa-enforce.md
pages.nl/linux/aa-status.md
pages.nl/linux/apparmor_status.md

apparmor_status: add Dutch alias page, aa-*: add Dutch translation

---

pages.ko/common/docsify.md
pages.ko/common/doctl-account.md
pages.ko/common/doctl-apps.md
pages.ko/common/doctl-auth.md
pages.ko/common/doctl-balance.md
pages.ko/common/doctl-compute-droplet.md
pages.ko/common/doctl-databases-db.md
pages.ko/common/doctl-databases-firewalls.md
pages.ko/common/doctl-databases-maintenance-window.md
pages.ko/common/doctl-databases-options.md
pages.ko/common/doctl-databases-pool.md
pages.ko/common/doctl-databases-replica.md
pages.ko/common/doctl-databases-sql-mode.md
pages.ko/common/doctl-databases-user.md
pages.ko/common/doctl-databases.md
pages.ko/common/doctl-kubernetes-cluster.md
pages.ko/common/doctl-kubernetes-options.md
pages.ko/common/doctl-serverless.md

docsify, doctl-*: add Korean translation

---

pages/linux/cryptsetup-luksformat.md
pages/linux/cryptsetup-open.md
pages/linux/cryptsetup.md

cryptsetup: update page; cryptsetup-{open,luksformat}: add page

---

pages/linux/upnpc.md

- **Version of the command being documented (if known):** `upnpc: miniupnpc library test client, version 2.2.7.`

upnpc: add page

---

pages/common/pnpx.md

pnpx: fix more info link

---

pages/common/npm-update.md

npm-update: add page

---

pages.pt_BR/common/ffmpeg.md
pages.pt_BR/common/img2pdf.md
pages.pt_BR/common/java.md
pages.pt_BR/common/javac.md
pages.pt_BR/common/mongo.md
pages.pt_BR/common/pssh.md
pages.pt_BR/common/ssh-copy-id.md
pages.pt_BR/common/ssh-keygen.md
pages.pt_BR/common/ssh-keyscan.md
pages.pt_BR/common/ssh.md
pages.pt_BR/common/sshfs.md
pages.pt_BR/common/sshpass.md

pages.pt_BR/common/*: fix translation

---

pages/common/npm-token.md

npm-token: add page

---

pages/common/crane-cp.md

crane-cp: add alias page

---

pages/linux/lbu.md

lbu: add page

---

pages/common/zapier-analytics.md
pages/common/zapier-build.md
pages/common/zapier-convert.md
pages/common/zapier-init.md
pages/common/zapier-push.md
pages/common/zapier-scaffold.md
pages/common/zapier.md

zapier-{analytics, build, convert, init, push}: update more info link

---

pages/common/cpan.md

cpan: add page

---

pages/common/ansible-galaxy.md

- **Version of the command being documented (if known): 2.16.11**

ansible-galaxy: update page

---

pages/common/npm-view.md

npm-view: add page

---

pages/common/npm-doctor.md

npm-doctor: add page

---

pages.ko/windows/sfc.md
pages.ko/windows/show-markdown.md
pages.ko/windows/showmount.md
pages.ko/windows/shutdown.md
pages.ko/windows/sl.md
pages.ko/windows/slmgr.md
pages.ko/windows/slmgr.vbs.md

sl*,sh*,sfc: add Korean translation

---

pages.ko/linux/flatpak-builder.md
pages.ko/linux/flatpak-run.md
pages.ko/linux/flatpak.md

flatpak*: add Korean translation

---

pages/common/bear.md

- **Version of the command being documented (if known): 3.0.18**

bear: add page

---

pages/common/cdecl.md

- **Version of the command being documented (if known): 2.5.1**

cdecl: add page

---

pages/common/npm-team.md

npm-team: add page

---

pages.ko/common/gacutil.md
pages.ko/common/gallery-dl.md
pages.ko/common/gammastep.md
pages.ko/common/ganache-cli.md
pages.ko/common/gatsby.md
pages.ko/common/gau.md
pages.ko/common/gcal.md
pages.ko/common/gcalcli.md

ga*, gc*: add Korean translation

---

pages.nl/common/2to3.md

2to3: update Dutch translation

---

pages.nl/common/more.md
pages.nl/linux/dir.md
pages.nl/linux/dnf-config-manager.md
pages.nl/linux/more.md
pages.nl/windows/ftp.md

pages.nl/: rephrase 'hulp' to 'help'

---

pages.nl/common/abduco.md
pages.nl/common/duc.md
pages.nl/common/kill.md
pages.nl/common/netstat.md
pages.nl/common/npm.md
pages.nl/linux/bleachbit.md
pages.nl/linux/duc.md
pages.nl/linux/eselect-locale.md
pages.nl/linux/jobs.md
pages.nl/linux/kill.md
pages.nl/linux/killall.md
pages.nl/osx/ipconfig.md
pages.nl/osx/port.md
pages.nl/osx/yaa.md
pages.nl/windows/ipconfig.md
pages.nl/windows/rpcinfo.md
pages/common/npm.md

pages.nl/*: rephrase 'lijst' to 'toon', npm: rephrase description

---

pages.ko/common/flutter-pub.md
pages.ko/common/flutter.md
pages.ko/common/fluxctl.md
pages.ko/common/fly.md
pages.ko/common/flyctl.md

fl*: add Korean translation

---

pages.nl/android/bugreportz.md

bugreportz: update Dutch translation

---

MAINTAINERS.md

MAINTAINERS: add @renie as a member

---

pages.ko/osx/xcode-select.md
pages.ko/osx/xcodebuild.md
pages.ko/osx/xcodes-runtimes.md
pages.ko/osx/xcodes.md

xcode*: add Korean translation

---

pages/common/docker-images.md

docker-images: escape curly braces

---

pages.id/common/aws-accessanalyzer.md
pages.id/common/aws-backup.md
pages.id/common/aws-codecommit.md
pages.id/common/aws-configure.md
pages.id/common/aws-google-auth.md
pages.id/common/aws-history.md
pages.id/common/aws-lambda.md
pages.id/common/aws-s3.md
pages.id/common/aws-sts.md
pages.id/common/aws.md

aws, aws-*: add Indonesian translations

---

pages.es/common/yes.md

yes: update Spanish translation

yes: update Spanish translation

---

pages/linux/cointop.md

cointop: add page

---

contributing-guides/style-guide.md

#10906 again.
Let me know if this was intentionally removed and I missed it, I'll close the PR then. I couldn't find anything about this.

style-guide: readd guidelines for `--opt arg`

---

pages.id/android/bugreportz.md
pages.id/common/2to3.md
pages.id/common/atom.md
pages.id/common/bandwhich.md
pages.id/common/banner.md
pages.id/common/brew-list.md
pages.id/common/brew-outdated.md
pages.id/common/cake.md
pages.id/common/cancel.md
pages.id/common/code.md
pages.id/common/cowsay.md
pages.id/common/fping.md
pages.id/common/msedge.md
pages.id/common/ping.md
pages.id/common/touch.md

bugreportz, common/*: add and update Indonesian translations

---

pages/common/cfssl.md

cfssl: add page

---

pages.pt_BR/android/bugreportz.md

bugreportz: update Portuguese Brazilian translation

---

pages.pt_BR/common/alias.md

https://github.com/tldr-pages/tldr-maintenance/issues/110.

alias: update Portuguese Brazilian translation

---

pages.pt_BR/common/compare.md

> add pt-BR missing translation for 'compare.md'.
> add description for the command.
> add website link to documentation.

compare: add Portuguese Brazilian translation

---

pages.pt_BR/common/bundler.md

bundler: add Portuguese Brazilian translation

---

pages.pt_BR/common/bat.md

tldr-pages/tldr-maintenance#110

bat: update Portuguese Brazilian translation

---

pages/linux/pvremove.md

- **Version of the command being documented (if known): LVM version: 2.03.23(2) (2023-11-21) Library version: 1.02.197 (2023-11-21)**

pvremove: add page

---

pages/common/nxcdb.md

nxcdb: add page

---

pages/common/ntpctl.md

ntpctl: add page

---

pages/linux/swww.md

swww: add page

---

pages.ko/windows/pushd.md
pages.ko/windows/pwd.md
pages.ko/windows/pwlauncher.md
pages.ko/windows/query.md
pages.ko/windows/rdpsign.md

rdpsign,query,pw*,pushd: add Korean translation

---

pages/common/goenv.md

goenv: add page

---

pages.ko/common/glab-alias.md
pages.ko/common/glab-auth.md
pages.ko/common/glab-issue.md
pages.ko/common/glab-mr-create.md
pages.ko/common/glab-mr-merge.md
pages.ko/common/glab-mr.md
pages.ko/common/glab-pipeline.md
pages.ko/common/glab-release.md
pages.ko/common/glab-repo.md
pages.ko/common/glab.md
pages.ko/common/gladtex.md
pages.ko/common/glances.md
pages.ko/common/gleam.md
pages.ko/common/glib-compile-resources.md
pages.ko/common/glow.md

gl*: add Korean translation

---

pages.es/common/ping.md

ping: update Spanish translation

ping: update Spanish translation

---

pages.es/common/azure-cli.md

azure-cli: add Spanish translation

---

pages/common/swift.md

- **Version of the command being documented (if known):** 5.10

swift: update REPL command

---

pages/common/nxc-winrm.md

nxc-winrm: add page

---

pages.nl/common/ripgrep.md

ripgrep: add Dutch translation

---

pages.nl/common/az.md

az: update Dutch more info link

---

pages.nl/common/cron.md

cron: add Dutch translation

---

pages.nl/linux/aa-enforce.md

aa-enforce: update Dutch translation

---

pages/common/idevice_id.md
pages/common/idevicebackup.md
pages/common/idevicebackup2.md
pages/common/idevicecrashreport.md
pages/common/idevicedate.md
pages/common/idevicediagnostics.md
pages/common/ideviceimagemounter.md
pages/common/ideviceinfo.md
pages/common/idevicename.md
pages/common/idevicepair.md
pages/common/idevicescreenshot.md
pages/common/idevicesetlocation.md
pages/common/idevicesyslog.md
pages/common/iproxy.md

idevice*, iproxy: add pages

---

pages.ko/common/mongo.md
pages.ko/common/mongod.md
pages.ko/common/mongodump.md
pages.ko/common/mongoexport.md
pages.ko/common/mongoimport.md
pages.ko/common/mongorestore.md
pages.ko/common/mongosh.md

mongo*: add Korean translation

---

pages/common/sui-client-faucet.md
pages/common/sui-client-ptb.md
pages/common/sui-client.md
pages/common/sui-move.md
pages/common/sui.md

- **Version of the command being documented (if known):** 1.36.2

sui: add page

---

pages/common/npm-init.md

- **Version of the command being documented (if known):10.9.0**

npm-init: add page

---

pages.ko/common/doppler-projects.md
pages.ko/common/doppler-run.md
pages.ko/common/doppler-secrets.md
pages.ko/common/doppler.md

doppler*: add Korean translation

---

pages.ko/common/hangups.md
pages.ko/common/hardhat.md
pages.ko/common/hashcat.md
pages.ko/common/hashid.md
pages.ko/common/haxelib.md

ha*: add Korean translation

---

pages.es/common/nano.md

nano: update Spanish translation

nano: update Spanish translation

---

pages.es/common/age.md

age: update Spanish translation

---

README.md

https://joinmastodon.org/verification

feat: add link rel="me" for repo verification in Fosstodon

---

pages.ko/common/tlmgr-backup.md
pages.ko/common/tlmgr-candidates.md
pages.ko/common/tlmgr-check.md
pages.ko/common/tlmgr-conf.md
pages.ko/common/tlmgr-dump-tlpdb.md
pages.ko/common/tlmgr-generate.md
pages.ko/common/tlmgr-gui.md
pages.ko/common/tlmgr-info.md
pages.ko/common/tlmgr-install.md
pages.ko/common/tlmgr-key.md
pages.ko/common/tlmgr-option.md
pages.ko/common/tlmgr-paper.md
pages.ko/common/tlmgr-path.md
pages.ko/common/tlmgr-pinning.md
pages.ko/common/tlmgr-platform.md
pages.ko/common/tlmgr-recreate-tlpdb.md
pages.ko/common/tlmgr-remove.md
pages.ko/common/tlmgr-repository.md
pages.ko/common/tlmgr-restore.md
pages.ko/common/tlmgr-search.md
pages.ko/common/tlmgr-shell.md
pages.ko/common/tlmgr-update.md
pages.ko/common/tlmgr.md

tlmgr*: add Korean translation

---

.github/CODEOWNERS
MAINTAINERS.md

Closes https://github.com/tldr-pages/tldr/issues/14539

MAINTAINERS: add @karthik-script as collaborator

---

pages.ko/common/dotnet-add-package.md
pages.ko/common/dotnet-add-reference.md
pages.ko/common/dotnet-build.md
pages.ko/common/dotnet-ef.md
pages.ko/common/dotnet-publish.md
pages.ko/common/dotnet-restore.md
pages.ko/common/dotnet-run.md
pages.ko/common/dotnet-test.md
pages.ko/common/dotnet-tool.md
pages.ko/common/dotnet.md

dotnet*: add and update Korean translation

---

pages.es/common/bats.md

bats: update Spanish translation

---

pages.es/common/az.md

az: update Spanish translation

---

pages.es/common/chown.md

chown: update Spanish translation

---

pages.es/common/chsh.md

chsh: update Spanish translation

---

pages.ko/windows/net.md
pages.ko/windows/netsh-interface-portproxy.md
pages.ko/windows/new-item.md
pages.ko/windows/nfsstat.md
pages.ko/windows/ni.md
pages.ko/windows/nvm.md
pages.ko/windows/octo.md
pages.ko/windows/ospp.vbs.md
pages.ko/windows/out-string.md

ne*,nfstat,ni,nvm,o*: add Korean translation

---

pages/common/tar.md

corrected the language used on 2 lines

tar: update page

---

pages.ko/common/pio-access.md
pages.ko/common/pio-account.md
pages.ko/common/pio-boards.md
pages.ko/common/pio-check.md
pages.ko/common/pio-ci.md
pages.ko/common/pio-debug.md
pages.ko/common/pio-device.md
pages.ko/common/pio-home.md
pages.ko/common/pio-lib.md
pages.ko/common/pio-org.md
pages.ko/common/pio-package.md
pages.ko/common/pio-platform.md
pages.ko/common/pio-project.md
pages.ko/common/pio-remote.md
pages.ko/common/pio-run.md
pages.ko/common/pio-settings.md
pages.ko/common/pio-system.md
pages.ko/common/pio-team.md
pages.ko/common/pio-test.md
pages.ko/common/pio-update.md
pages.ko/common/pio-upgrade.md
pages.ko/common/pio.md

pio*: add Korean translation

---

.github/CODEOWNERS
MAINTAINERS.md

Thank you. I have updated `maintainer.md` and `CODEOWNERS`.
Closes #14538

MAINTAINERS: add @Zamoca42 as collaborator

---

pages/common/npm-star.md

npm-star: add page

---

pages/common/npm-root.md

npm-root: add page

---

pages/common/bdfr.md

bdfr: add page

---

pages/common/npm-unstar.md

npm-unstar: add page

---

pages.es/common/nnn.md

nnn: update Spanish translation

nnn: update Spanish translation

---

pages.es/common/du.md

du: update Spanish translation

---

pages/common/npm-author.md
pages/common/npm-owner.md

npm-{owner, author}: add page

---

pages/common/stripe.md

stripe: update documentation link

---

pages.ko/common/go-test.md
pages.tr/common/go-test.md
pages/common/go-test.md

go-test: update documentation link

---

pages.de/common/terraform-plan.md
pages/common/terraform-plan.md

terraform-plan: update documentation link

---

scripts/set-alias-page.py

https://github.com/tldr-pages/tldr/issues/12747#issuecomment-2452914616
Open issues:
https://github.com/tldr-pages/tldr/issues/12747#issuecomment-2452921154
https://github.com/tldr-pages/tldr/issues/12747#issuecomment-2452927900

set-alias-page: use translated regex

---

pages.ko/windows/if.md
pages.ko/windows/install-module.md
pages.ko/windows/invoke-item.md
pages.ko/windows/invoke-webrequest.md
pages.ko/windows/ipconfig.md
pages.ko/windows/iscc.md
pages.ko/windows/logoff.md
pages.ko/windows/netstat.md

netstat,logoff,i*: add Korean translation

---

pages.de/common/terraform-fmt.md
pages/common/terraform-fmt.md

terraform-fmt: update documentation link

---

pages.nl/windows/get-history.md

- [*] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [*] The page(s) have at most 8 examples.
- [*] The page description(s) have links to documentation or a homepage.
- [*] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [*] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [*] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).

get-history: add Dutch translation

---

pages.nl/windows/color.md

- [*] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [* The page(s) have at most 8 examples.
- [*] The page description(s) have links to documentation or a homepage.
- [* The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [*] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [*] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).

color: add Dutch translation

---

pages/common/npm-ogr.md
pages/common/npm-org.md

npm-org: add page

---

pages/common/basename.md

Apply page typo corrections found in #14603.

basename: fix typo

---

pages.ko/common/pgmbentley.md
pages.ko/common/pgmcrater.md
pages.ko/common/pgmdeshadow.md
pages.ko/common/pgmedge.md
pages.ko/common/pgmenhance.md
pages.ko/common/pgmhist.md
pages.ko/common/pgmkernel.md
pages.ko/common/pgmmake.md
pages.ko/common/pgmnoise.md
pages.ko/common/pgmnorm.md
pages.ko/common/pgmoil.md
pages.ko/common/pgmramp.md
pages.ko/common/pgmslice.md
pages.ko/common/pgmtexture.md
pages.ko/common/pgmtofs.md
pages.ko/common/pgmtolispm.md
pages.ko/common/pgmtopbm.md
pages.ko/common/pgmtopgm.md
pages.ko/common/pgmtoppm.md
pages.ko/common/pgmtosbig.md
pages.ko/common/pgmtost4.md

pgm*: add Korean translation

---

pages.nl/common/ifconfig.md

ifconfig: update Dutch translation

---

pages.ko/windows/gal.md
pages.ko/windows/gcrane-completion.md
pages.ko/windows/gl.md
pages.ko/windows/gpupdate.md
pages/common/basename.md

windows/g*: add Korean translation

---

.github/CODEOWNERS
MAINTAINERS.md

https://github.com/tldr-pages/tldr/issues/14537#issuecomment-2457381463
Closes https://github.com/tldr-pages/tldr/issues/14537

MAINTAINERS: add @CodePsy-2001 as collaborator

---

pages.ko/common/hledger-accounts.md
pages.ko/common/hledger-add.md
pages.ko/common/hledger-aregister.md
pages.ko/common/hledger-balance.md
pages.ko/common/hledger-balancesheet.md
pages.ko/common/hledger-import.md
pages.ko/common/hledger-incomestatement.md
pages.ko/common/hledger-print.md
pages.ko/common/hledger-ui.md
pages.ko/common/hledger-web.md
pages.ko/common/hledger.md

hledger,hledger-*: add Korean translation

---

pages.ko/common/ifconfig.md
pages.ko/common/ifdata.md
pages.ko/common/ifne.md
pages.ko/common/ifs.md
pages.ko/common/ignite.md
pages.ko/common/ilbmtoppm.md
pages.ko/common/imapsync.md
pages.ko/common/imgcat.md
pages.ko/common/imgtoppm.md
pages.ko/common/immich-cli.md
pages.ko/common/immich-go.md
pages.ko/common/import.md

if*, ignite, ilbmtoppm, im*: add Korean translation

---

pages.zh/common/adb-devices.md

adb-devices: add Chinese translation

---

pages/common/helix.md

helix: add example to open multiple files and tutorial

---

pages.ko/common/idnits.md
pages.ko/common/iex.md
pages.ko/common/if.md

idnits, iex, if: add Korean translation

---

pages/common/z.md

```
~ ❯❯❯ brew info z
==> z: stable 1.12 (bottled), HEAD
```

z: remove unnecessary dot

---

pages/common/aws-s3-rm.md

aws-s3-rm: add example

---

pages/osx/networkquality.md

networkQuality: update documentation link

---

pages.zh/android/bugreportz.md

bugreportz: update Chinese translation

---

pages/common/gzip.md

gzip: fix parameters formatting

---

pages.fa/common/cradle.md

cradle: add Farsi translation

---

pages.es/common/mc.md

mc: add Spanish translation

---

pages.es/common/crontab.md

crontab: add Spanish translation

---

pages.es/common/ar.md

ar: add Spanish translation

---

pages.es/linux/apport-bug.md

apport-bug: add Spanish translation

---

pages.es/linux/qm-disk-resize.md

qm-disk-resize: add Spanish translation

---

pages.es/linux/qm-disk-move.md

qm-disk-move: add Spanish translation

---

pages.es/linux/qm-disk-import.md

qm-disk-import: add Spanish translation

---

pages.es/linux/nmtui.md

nmtui: add Spanish translation

---

pages.es/linux/systemd-mount.md

systemd-mount: add Spanish translation

---

pages.es/linux/megatools-dl.md

megatools-dl: add Spanish translation

---

pages.es/linux/ip-route-show.md

ip-route-show: add Spanish translation

---

pages.ko/common/~.md

~: add Korean translation

---

pages/common/pulumi-whoami.md

pulumi-whoami: add page

---

pages.pl/common/http.md
pages/common/http.md

https://github.com/tldr-pages/tldr/pull/14655#issuecomment-2459080291

http: update page and Polish translation

---

pages.hi/common/steamcmd.md

steamcmd: add Hindi translation

---

pages/common/npm-login.md

- **Version of the command being documented (if known):10.9.0**

npm-login: add page

---

pages/common/pulumi-version.md

pulumi-version: add page

---

pages.es/common/clamscan.md

clamscan: add Spanish translation

---

pages.es/common/cp.md

cp: update Spanish translation

---

pages.es/common/df.md

df: update Spanish translation

---

pages.es/common/at.md

at: update Spanish translation

---

pages.es/osx/chpass.md

chpass: add Spanish translation

---

pages.es/common/helix.md

helix: add Spanish translation

---

pages.es/common/clj.md

clj: add Spanish translation

---

pages.es/common/hexdump.md

hexdump: add Spanish translation

---

pages.es/common/freshclam.md

freshclam: add Spanish translation

---

pages.es/common/crane-copy.md

crane-copy: add Spanish translation

---

pages.es/common/git-cola.md

git-cola: add Spanish translation

---

pages.zh/common/zsh.md

zsh: update Chinese translation

---

pages/common/aws-secretsmanager.md

aws-secretsmanager: update page

---

pages.es/common/dig.md

dig: update Spanish translation

---

pages/common/docker-node.md

My first contribution to this fantastic project!

docker-node: add page

---

pages/linux/nft.md

nft: fix missing semicolon

---

pages/common/magick-mogrify.md

magick-mogrify: add gif optimization

---

pages.es/common/limactl.md

limactl: add Spanish translation

---

pages.es/common/kcat.md

kcat: add Spanish translation

---

pages.es/common/hping3.md

hping3: add Spanish translation

---

pages.es/common/http.md

http: add Spanish translation

---

pages.es/common/strings.md

strings: add Spanish translation

---

pages.pt_BR/common/mpv.md

mpv: update Brazilian Portuguese description and commands

---

pages.es/common/tlmgr-platform.md

tlmgr-platform: add Spanish translation

---

pages.es/common/fossil-rm.md

fossil-rm: add Spanish translation

---

pages.es/common/xzmore.md

xzmore: add Spanish translation

---

pages.es/common/xzless.md

xzless: add Spanish translation

---

pages.es/common/zstd.md

zstd: add Spanish translation

---

pages.es/linux/mount.cifs.md

mount.cifs: add Spanish translation

---

pages.es/linux/shnsplit.md

shnsplit: add Spanish translation

---

pages.es/linux/iptables.md

iptables: add Spanish translation

---

pages.es/common/jf.md

jf: add Spanish translation

---

pages.es/common/tldr-lint.md

tldr-lint: add Spanish translation

---

pages.hi/windows/pswindowsupdate.md

PSWindowsUpdate: add Hindi translation

---

pages.hi/windows/psversiontable.md

PSVersionTable: add Hindi translation

---

pages.hi/windows/popd.md

popd: add Hindi translation

---

pages.hi/windows/mv.md

mv: add Hindi translation

---

pages.hi/windows/gl.md

gl: add Hindi translation

---

pages.hi/windows/cls.md

cls: add Hindi translation

---

pages.hi/windows/pwd.md

pwd: add Hindi translation

---

pages.hi/windows/choco-feature.md

choco-feature: add Hindi translation

---

pages.hi/windows/chdir.md

chdir: add Hindi translation

---

pages.hi/windows/bleachbit.md

bleachbit: add Hindi translation

---

pages.hi/windows/clear-host.md

Clear-Host: add Hindi translation

---

pages.hi/windows/nfsstat.md

nfsstat: add Hindi translation

---

pages/common/pulumi-new.md

pulumi-new: add page

---

pages/common/argos-translate.md

argos-translate: add page

---

pages.fr/common/argon2.md

argon2: add French translation

---

pages.fr/common/du.md

du: add French translation

---

pages.fr/common/adb-devices.md

adb-devices: add French translation

---

pages/common/wikiman.md

wikiman: add page

---

pages/common/m4b-tool.md

- **Version of the command being documented (if known): v.0.4.2**

m4b-tool: add page

---

pages/common/wikiman.md

https://github.com/tldr-pages/tldr/pull/14922#discussion_r1854551703

wikiman: update page

---

pages.es/linux/patool.md

patool: add Spanish translation

---

pages.es/common/airodump-ng.md

airodump-ng: update Spanish translation

---

pages.es/linux/pacman-r.md

pacman-r: add Spanish translation

---

pages.es/common/argos-translate.md

argos-translate: add Spanish translation

---

pages.es/common/docker-diff.md

docker-diff: add Spanish translation

---

pages.es/common/docker-rename.md

docker-rename: add Spanish translation

---

pages.es/common/docker-rm.md

docker-rm: add Spanish translation

---

pages.es/common/docker-top.md

docker-top: add Spanish translation

---

pages.zh/linux/minicom.md

minicom: add Chinese translation

---

pages.zh/common/fzf.md

fzf: add Chinese translation

---

pages/linux/darling.md

darling: add page

---

pages/common/pulumi-gen-completion.md

pulumi-gen-completion: add page

---

pages/common/incus.md

- **Version of the command being documented (if known):** 6.0 LTS

incus: add page

---

pages/linux/wf-recorder.md

wf-recorder: add page

---

pages.es/linux/brightnessctl.md

brightnessctl: add Spanish translation

---

pages.es/linux/dnf5-group.md

dnf5-group: add Spanish translation

---

pages.es/common/wikiman.md

wikiman: add Spanish translation

---

pages.es/linux/grim.md

grim: add Spanish translation

---

pages.es/common/m4b-tool.md

m4b-tool: add Spanish translation

---

pages.es/linux/xfce4-screenshooter.md

xfce4-screenshooter: add Spanish translation

---

pages.es/linux/gnome-screenshot.md

gnome-screenshot: add Spanish translation

---

pages.es/common/cowsay.md

cowsay: add Spanish translation

---

pages.es/linux/wine.md

wine: add Spanish translation

---

pages.es/linux/pacman-sync.md

pacman-sync: add Spanish translation

---

pages.es/linux/pacman-remove.md

pacman-remove: add Spanish translation

---

pages.es/linux/swww.md

swww: add Spanish translation

---

pages.es/linux/tuned-adm.md

tuned-adm: add Spanish translation

---

pages.es/common/pamstretch.md

pamstretch: add Spanish translation

---

pages.es/common/pwd.md

pwd: update Spanish translation

---

pages.es/common/hugo-server.md

hugo-server: update Spanish translation

---

pages/linux/imv.md

imv: add page

---

pages/linux/readcd.md

readcd: add page

---

pages.es/common/fzf.md

fzf: add Spanish translation

---

pages/common/pulumi-install.md

pulumi-install: add page

---

pages/linux/cdrdao.md

cdrdao: add page

---

pages.ko/common/printenv.md
pages.nl/common/printenv.md
pages/common/printenv.md

printenv: update documentation link

---

pages/common/brew-list.md

brew-list: add `--pinned` example

---

pages/common/fd.md

fd: update page

---

pages.bn/common/arch.md
pages.es/common/arch.md
pages.fr/common/arch.md
pages.hi/common/arch.md
pages.id/common/arch.md
pages.it/common/arch.md
pages.ja/common/arch.md
pages.ko/common/arch.md
pages.nl/common/arch.md
pages.no/common/arch.md
pages.pt_BR/common/arch.md
pages.sv/common/arch.md
pages.tr/common/arch.md
pages.zh/common/arch.md
pages/common/arch.md

arch: update documentation link

---

pages.es/linux/apt-moo.md

apt-moo: add Spanish translation

---

pages.es/common/adb-devices.md

adb-devices: add Spanish translation

---

pages.es/common/adb-reboot.md

adb-reboot: add Spanish translation

---

pages.es/linux/apt-clone.md

apt-clone: add Spanish translation

---

pages.es/common/podman-image.md

podman-image: add Spanish translation

---

pages.es/common/podman-compose.md

podman-compose: add Spanish translation

---

pages.es/common/podman-images.md

podman-images: add Spanish translation

---

pages.es/common/podman-build.md

podman-build: add Spanish translation

---

pages.es/common/podman-login.md

podman-login: add Spanish translation

---

pages.es/common/podman-machine.md

podman-machine: add Spanish translation

---

pages.es/common/podman-ps.md

podman-ps: add Spanish translation

---

pages.es/common/podman-rmi.md

podman-rmi: add Spanish translation

---

pages.es/linux/wl-copy.md

wl-copy: add Spanish translation

---

pages.es/linux/wl-paste.md

wl-paste: add Spanish translation

---

pages/common/zpaq.md

zpaq: add page

---

pages/linux/eclean.md

- **Version of the command being documented (if known): 0.6.8**

eclean: add page

---

pages/common/while.md

while: add conditional repeat of command example

---

pages/linux/protontricks.md

protontricks: add launch command

---

pages.es/linux/nmcli-radio.md

nmcli-radio: add Spanish translation

---

pages.es/linux/nmcli-networking.md

nmcli-networking: add Spanish translation

---

pages.es/linux/nmcli-monitor.md

nmcli-monitor: add Spanish translation

---

pages.es/linux/nmcli-general.md

nmcli-general: add Spanish translation

---

pages.es/linux/nmcli-device.md

nmcli-device: add Spanish translation

---

pages.es/linux/nmcli-connection.md

nmcli-connection: add Spanish translation

---

pages.es/linux/nmcli-agent.md

nmcli-agent: add Spanish translation

---

pages.es/linux/nmcli.md

nmcli: add Spanish translation

---

pages.es/common/trdsql.md

trdsql: add Spanish translation

---

pages.es/common/zola.md

zola: add Spanish translation

---

pages.es/linux/nm-online.md

nm-online: add Spanish translation

---

pages.es/common/podman.md

podman: add Spanish translation

---

pages.es/common/fabric.md

fabric: add Spanish translation

---

pages.es/common/incus.md

incus: add Spanish translation

---

pages.es/linux/readcd.md

readcd: add Spanish translation

---

pages.es/linux/cdrdao.md

cdrdao: add Spanish translation

---

pages.es/linux/imv.md

imv: add Spanish translation

---

pages.es/linux/wf-recorder.md

wf-recorder: add Spanish translation

---

pages.es/linux/darling.md

darling: add Spanish translation

---

pages.es/common/hatch.md

hatch: add Spanish translation

---

pages.es/linux/vgremove.md

vgremove: add Spanish translation

---

pages.es/linux/farge.md

farge: add Spanish translation

---

pages.es/linux/xsel.md

xsel: add Spanish translation

---

pages.es/common/^.md

caret: add Spanish translation

---

pages/common/docker-context.md

docker-context: add page

---

pages.es/common/pamflip.md

pamflip: add Spanish translation

---

pages.nl/common/b2sum.md
pages.nl/common/md5sum.md
pages.nl/common/sha1sum.md
pages.nl/common/sha224sum.md
pages.nl/common/sha384sum.md
pages.nl/common/sha512sum.md

b2sum,md5sum,sha*sum: update Dutch translation

---

pages.nl/linux/jobs.md
pages/common/pwd.md

jobs: update Dutch more info link; pwd: update Dutch translation
