tldr-pages/tldr

- pages.nl/linux/dnf5-group.md
- pages.nl/linux/pacman-f.md
> dnf5-group,pacman-f: add Dutch alias pages

- pages.ko/common/basenc.md
- pages.nl/common/basenc.md
- pages/common/basenc.md
> basenc: update documentation link

- pages.zh/windows/rmdir.md
- pages.zh/windows/shutdown.md
- pages.zh/windows/whoami.md
- pages.zh/windows/winget.md
> rmdir, shutdown, whoami, winget: update Chinese translation

- pages/common/git-branch.md
To improve readability for non-native speakers, complex grammar has been replaced.
> git-branch: update page

- pages.es/common/pulumi-config.md
> pulumi-config: add Spanish translation

- pages.es/linux/dnf-group.md
> dnf-group: add Spanish translation

- pages.es/common/complete.md
> complete: add Spanish translation

- pages.es/common/compgen.md
> compgen: add Spanish translation

- pages.es/linux/qm.md
> qm: add Spanish translation

- pages.es/linux/qm-cleanup.md
> qm-cleanup: add Spanish translation

- pages.es/linux/ip-address.md
> ip-address: add Spanish translation

- pages.es/linux/ip-link.md
> ip-link: add Spanish translation

- pages.es/linux/ip-neighbour.md
> ip-neighbour: add Spanish translation

- pages.es/common/tex-fmt.md
> tex-fmt: add Spanish translation

- pages.es/linux/qm-config.md
> qm-config: add Spanish translation

- pages.es/linux/qm-cloudinit-dump.md
> qm-cloudinit-dump: add Spanish translation

- pages.es/linux/qm-clone.md
> qm-clone: add Spanish translation

- pages.es/linux/ip-rule.md
> ip-rule: add Spanish translation

- pages.es/linux/ip-route.md
> ip-route: add Spanish translation

- pages.es/linux/qm-destroy.md
> qm-destroy: add Spanish translation

- pages.es/common/gum.md
> gum: add Spanish translation

- pages.es/linux/whiptail.md
> whiptail: add Spanish translation

- pages.es/linux/qm-guest-cmd.md
> qm-guest-cmd: add Spanish translation

- pages.es/linux/qm-guest-exec.md
> qm-guest-exec: add Spanish translation

- pages/osx/tag.md
> tag: add page

- pages/linux/loginctl.md
> loginctl: add user logout example

- pages.es/linux/qm-list.md
> qm-list: add Spanish translation

- pages.es/linux/qm-mtunnel.md
> qm-mtunnel: add Spanish translation

- pages.es/linux/qm-monitor.md
> qm-monitor: add Spanish translation

- pages.es/linux/qm-migrate.md
> qm-migrate: add Spanish translation

- pages.es/linux/qm-nbdstop.md
> qm-nbdstop: add Spanish translation

- pages.es/linux/qm-reboot.md
> qm-reboot: add Spanish translation

- pages.es/linux/qm-reset.md
> qm-reset: add Spanish translation

- pages.es/linux/qm-resume.md
> qm-resume: add Spanish translation

- pages.es/linux/qm-pending.md
> qm-pending: add Spanish translation

- pages.es/linux/qm-rescan.md
> qm-rescan: add Spanish translation

- pages.es/common/qmmp.md
> qmmp: add Spanish translation

- pages.es/linux/qm-rollback.md
> qm-rollback: add Spanish translation

- pages.es/common/qmv.md
> qmv: add Spanish translation

- pages.fr/common/chgrp.md
- pages.it/common/chgrp.md
- pages.ko/common/chgrp.md
- pages.nl/common/chgrp.md
- pages/common/chgrp.md
> chgrp: update documentation link

- pages.de/common/chroot.md
- pages.fr/common/chroot.md
- pages.it/common/chroot.md
- pages.ko/common/chroot.md
- pages.nl/common/chroot.md
- pages.tr/common/chroot.md
- pages/common/chroot.md
> chroot: update documentation link

- pages.es/linux/qm-wait.md
> qm-wait: add Spanish translation

- pages.it/common/comm.md
- pages.ko/common/comm.md
- pages.nl/common/comm.md
- pages/common/comm.md
> comm: update documentation link

- pages/common/vitest.md
- **Version of the command being documented (if known): 2.1.8**
> vitest: add page

- pages/linux/kwallet-query.md
> kwallet-query: add page

- pages.es/common/ruff.md
> ruff: add Spanish translation

- pages.es/linux/qm-sendkey.md
> qm-sendkey: add Spanish translation

- pages.es/linux/qm-showcmd.md
> qm-showcmd: add Spanish translation

- pages.es/linux/qm-shutdown.md
> qm-shutdown: add Spanish translation

- pages.es/linux/qm-start.md
> qm-start: add Spanish translation

- pages.es/linux/qm-status.md
> qm-status: add Spanish translation

- pages.es/linux/qm-stop.md
> qm-stop: add Spanish translation

- pages.es/linux/qm-unlock.md
> qm-unlock: add Spanish translation

- pages.es/linux/qm-vncproxy.md
> qm-vncproxy: add Spanish translation

- pages.es/linux/qm-snapshot.md
> qm-snapshot: add Spanish translation

- pages.es/common/obs.md
> obs: add Spanish translation

- pages.es/common/~.md
> tilde: add Spanish translation

- pages.ar/common/ls.md
- pages.ca/common/ls.md
- pages.de/common/ls.md
- pages.es/common/ls.md
- pages.fa/common/ls.md
- pages.fr/common/ls.md
- pages.hi/common/ls.md
- pages.id/common/ls.md
- pages.it/common/ls.md
- pages.ja/common/ls.md
- pages.ko/common/ls.md
- pages.ne/common/ls.md
- pages.nl/common/ls.md
- pages.pl/common/ls.md
- pages.pt_BR/common/ls.md
- pages.ru/common/ls.md
- pages.ta/common/ls.md
- pages.th/common/ls.md
- pages.zh/common/ls.md
- pages.zh_TW/common/ls.md
- pages/common/ls.md
> ls: update documentation link

- pages.es/linux/pdftohtml.md
> pdftohtml: add Spanish translation

- pages.es/linux/pdfdetach.md
> pdfdetach: add Spanish translation

- pages.es/linux/pdfattach.md
> pdfattach: add Spanish translation

- pages.es/common/gh-skyline.md
> gh-skyline: add Spanish translation

- pages.es/linux/pdfxup.md
> pdfxup: add Spanish translation

- pages.es/common/patch.md
> patch: add Spanish translation

- pages.es/common/pgrep.md
> pgrep: add Spanish translation

- pages.es/common/pg_isready.md
> pg_isready: add Spanish translation

- pages.es/common/pg_restore.md
> pg_restore: add Spanish translation

- pages.es/common/pg_dumpall.md
> pg_dumpall: add Spanish translation

- pages.es/common/pg_dump.md
> pg_dump: add Spanish translation

- pages.es/common/pgbench.md
> pgbench: add Spanish translation

- pages.es/common/pg_ctl.md
> pg_ctl: add Spanish translation

- pages.es/osx/tag.md
- pages.es/osx/tags.md
- pages/osx/tag.md
> tag: add Spanish translation, fix typo

- pages.de/common/echo.md
- pages.fa/common/echo.md
- pages.fr/common/echo.md
- pages.it/common/echo.md
- pages.ja/common/echo.md
- pages.ko/common/echo.md
- pages.nl/common/echo.md
- pages.pt_BR/common/echo.md
- pages.ru/common/echo.md
- pages.sr/common/echo.md
- pages.zh/common/echo.md
- pages.zh_TW/common/echo.md
- pages/common/echo.md
> echo: update documentation link

- pages.de/common/date.md
- pages.it/common/date.md
- pages.ko/common/date.md
- pages.nl/common/date.md
- pages.pt_BR/common/date.md
- pages.tr/common/date.md
- pages/common/date.md
> date: update documentation link

- pages.de/common/cut.md
- pages.es/common/cut.md
- pages.it/common/cut.md
- pages.ko/common/cut.md
- pages.nl/common/cut.md
- pages.pt_BR/common/cut.md
- pages.ru/common/cut.md
- pages/common/cut.md
> cut: update documentation link

- pages/common/lazygit.md
> lazygit: add page

- pages.es/common/batch.md
> batch: update Spanish translation

- pages.es/common/atq.md
> atq: add Spanish translation

- pages.es/common/atrm.md
> atrm: add Spanish translation

- pages.es/common/mail.md
> mail: add Spanish translation

- pages.es/common/npm-ls.md
> npm-ls: add Spanish translation

- pages.es/linux/rmdir.md
> rmdir: add Spanish translation

- pages.es/windows/sc.md
> sc: add Spanish translation

- pages.es/windows/clear-host.md
> clear-host: add Spanish translation

- pages.es/windows/remove-item.md
> remove-item: add Spanish translation

- pages.es/windows/set-location.md
> set-location: add Spanish translation

- pages.es/linux/pacman-f.md
> pacman-f: add Spanish translation

- pages.it/common/md5sum.md
- pages.ko/common/md5sum.md
- pages.nl/common/md5sum.md
- pages.ta/common/md5sum.md
- pages.zh/common/md5sum.md
- pages/common/md5sum.md
> md5sum: update documentation link

- pages.es/linux/export.md
> export: add Spanish translation

- pages.es/common/expr.md
> expr: add Spanish translation

- pages/common/$.md
> $: add $PS0 to examples

- pages/common/lazydocker.md
> lazydocker: add page

- pages/linux/pg.md
> pg: add page

- pages/linux/exch.md
> exch: add page

- pages.es/linux/debuild.md
> debuild: add Spanish translation

- pages.es/linux/debtap.md
> debtap: add Spanish translation

- pages.es/linux/debsecan.md
> debsecan: add Spanish translation

- pages.es/linux/debootstrap.md
> debootstrap: add Spanish translation

- pages.es/linux/debman.md
> debman: add Spanish translation

- pages.es/linux/deb-get.md
> deb-get: add Spanish translation

- pages.es/linux/debchange.md
> debchange: add Spanish translation

- pages.es/linux/unix2mac.md
> unix2mac: add Spanish translation

- pages.es/linux/unix2dos.md
> unix2dos: add Spanish translation

- pages.es/linux/mac2unix.md
> mac2unix: add Spanish translation

- pages.es/linux/tuxi.md
> tuxi: add Spanish translation

- pages.es/linux/ttyplot.md
> ttyplot: add Spanish translation

- pages.es/linux/lddd.md
> lddd: add Spanish translation

- pages.es/linux/ldd.md
> ldd: add Spanish translation

- pages.es/linux/ldconfig.md
> ldconfig: add Spanish translation

- pages.es/linux/dpkg-reconfigure.md
> dpkg-reconfigure: add Spanish translation

- pages.es/linux/dpkg-query.md
> dpkg-query: add Spanish translation

- pages.es/linux/dpkg-deb.md
> dpkg-deb: add Spanish translation

- pages.es/linux/asciiart.md
> asciiart: add Spanish translation

- pages.es/linux/ascii.md
> ascii: add Spanish translation

- pages/linux/lsfd.md
> lsfd: add page

- pages/common/set.md
> set: add parameter reset

- pages/common/v.md
> v: add page

- pages.es/common/unzip.md
> unzip: add Spanish translation

- pages.es/common/lynx.md
> lynx: add Spanish translation

- pages.es/common/emacs.md
> emacs: add Spanish translation

- pages.es/common/emacsclient.md
> emacsclient: add Spanish translation

- pages.es/linux/tac.md
> tac: add Spanish translation

- pages.es/linux/zip.md
> zip: add Spanish translation

- pages/common/{.md
> {: add page

- pages.es/common/elinks.md
> elinks: add Spanish translation

- pages.es/common/echo.md
> echo: add Spanish translation

- pages/common/until.md
> until: add page

- pages/common/typeset.md
> typeset: convert to alias

- pages/common/speedtest.md
> speedtest: update page

- pages.it/common/dircolors.md
- pages.ko/common/dircolors.md
- pages.nl/common/dircolors.md
- pages/common/dircolors.md
> dircolors: update documentation link

- pages/linux/lsfd.md
> lsfd: add longform options

- pages/common/break.md
> break: add page

- pages/common/adb-uninstall.md
> adb-uninstall: add page

- pages/common/virsh.md
> virsh: add network activation example

- pages.es/common/josm.md
> josm: add Spanish translation

- pages.es/linux/distrobox-upgrade.md
> distrobox-upgrade: add Spanish translation

- pages/linux/insmod.md
> insmod: update page

- pages/common/latexpand.md
> latexpand: add page

- pages/common/pangolin.md
> pangolin: add page

- pages/common/continue.md
> continue: fix grammar

- pages.es/linux/dpkg.md
> dpkg: add Spanish translation

- pages.es/linux/killall.md
> killall: add Spanish translation

- pages.es/common/ruff-format.md
> ruff-format: add Spanish translation

- pages.es/common/btop.md
> btop: update Spanish translation

- pages.es/windows/invoke-webrequest.md
> Invoke-WebRequest: add Spanish translation

- pages/common/suspend.md
> suspend: add page

- pages/common/while.md
> while: clarify descriptions

- pages/common/declare.md
> declare: add function print example and update link

- pages/linux/steamos-session-select.md
> steamos-session-select: refresh page

- pages/common/compgen.md
> compgen: add example to show completing given strings

- pages/linux/pacman-u.md
- pages/linux/pacman-upgrade.md
> pacman-u: add alias page; pacman-upgrade: update page

- pages/linux/pacman-de.md
- pages/linux/pacman-deptest.md
> pacman-t: add alias page; pacman-deptest: update page

- pages/linux/bootc-switch.md
> bootc-switch: add page

- pages.es/linux/distrobox-stop.md
> distrobox-stop: add Spanish translation

- pages.es/linux/distrobox-rm.md
> distrobox-rm: add Spanish translation

- pages.es/linux/distrobox-list.md
> distrobox-list: add Spanish translation

- pages.es/linux/distrobox-create.md
> distrobox-create: add Spanish translation

- pages.es/linux/toolbox-run.md
> toolbox-run: add Spanish translation

- pages.es/linux/toolbox-rmi.md
> toolbox-rmi: add Spanish translation

- pages.es/linux/toolbox-rm.md
> toolbox-rm: add Spanish translation

- pages.es/linux/toolbox-list.md
> toolbox-list: add Spanish translation

- pages.es/linux/toolbox-init-container.md
> toolbox-init-container: add Spanish translation

- pages.es/linux/toolbox-help.md
> toolbox-help: add Spanish translation

- pages.es/linux/toolbox-enter.md
> toolbox-enter: add Spanish translation

- pages.es/linux/toolbox-create.md
> toolbox-create: add Spanish translation

- pages.es/linux/toolbox.md
> toolbox: add Spanish translation

- pages.es/linux/schroot.md
> schroot: update Spanish translation

- pages.es/osx/dhcp6d.md
> dhcp6d: update Spanish translation

- pages.es/osx/ctkd.md
> ctkd: update Spanish translation

- pages/common/bpython.md
> bpython: add page

- pages/linux/fadvise.md
> fadvise: add page

- pages/common/latexpand.md
- pages/common/ppmtoapplevol.md
- pages/common/ppmtopjxl.md
- pages/common/ppmwheel.md
> ppmtopjxl, ppmwheel, ppmtoapplevol: add pages

- pages/common/latexpand.md
- pages/common/ppmtorgb3.md
- pages/common/rgb3toppm.md
- pages/common/rlatopam.md
- pages/common/spottopgm.md
> spottopgm, rlatopam, rgb3toppm, ppmtorgb3: add pages

- pages/common/dbx.md
> dbx: add page

- pages/linux/i386.md
- pages/linux/linux32.md
- pages/linux/linux64.md
- pages/linux/uname26.md
- pages/linux/x86_64.md
> x86_64, uname26, linux32, linux64, i386: add page

- pages/linux/fincore.md
> fincore: add page

- pages.es/common/llvd.md
> llvd: add Spanish translation

- pages.ar/linux/uname.md
> uname: add Arabic translation

- pages/common/function.md
> function: add page

- pages/common/readarray.md
> readarray: add page

- pages/linux/flatpak-run.md
add example for using different runtimes for flatpaks
source: https://docs.flatpak.org/en/latest/tips-and-tricks.html
> flatpak-run: update page

- pages/common/apkeep.md
> apkeep: add page

- pages.es/common/latexpand.md
> latexpand: add Spanish translation

- pages.es/common/suspend.md
> suspend: add Spanish translation

- pages.es/common/pangolin.md
> pangolin: add Spanish translation

- pages/linux/coredumpctl.md
> coredumpctl: simplify commands

- pages.nl/linux/pacman-q.md
- pages.nl/linux/pacman-query.md
> pacman-q, pacman-query: add Dutch translation

- pages.nl/linux/i386.md
- pages.nl/linux/linux32.md
- pages.nl/linux/linux64.md
- pages.nl/linux/uname26.md
- pages.nl/linux/x86_64.md
> x86_64, uname26, linux32, linux64, i386: add Dutch translation

- pages/linux/semanage-port.md
- **Version of the command being documented (if known):** policycoreutils-3.6-2.1
> semanage-port: add port range example

- pages/linux/kpackagetool5.md
- pages/linux/kpackagetool6.md
> kpackagetool6: add page; kpackagetool5: update link

- pages/linux/lookandfeeltool.md
> lookandfeeltool: add page

- pages.nl/common/npm.md
- pages.nl/freebsd/pkg.md
- pages.nl/linux/apx-pkgmanagers.md
- pages.nl/linux/apx-stacks.md
- pages.nl/linux/distrobox-upgrade.md
- pages.nl/linux/dnf.md
- pages.nl/linux/xbps.md
- pages.nl/openbsd/pkg.md
- pages.nl/osx/port.md
> pages.nl/*: uniform translation for 'package manager'

- pages.nl/common/bc.md
- pages.nl/common/httpie.md
- pages.nl/common/mesg.md
- pages.nl/common/more.md
- pages.nl/common/nvm.md
- pages.nl/common/popd.md
- pages.nl/common/pushd.md
- pages.nl/common/renice.md
- pages.nl/common/rmdir.md
- pages.nl/common/uname.md
- pages.nl/linux/groupmod.md
- pages.nl/linux/ipcs.md
- pages.nl/linux/iptables.md
- pages.nl/linux/mesg.md
- pages.nl/linux/more.md
- pages.nl/linux/pacman-sync.md
- pages.nl/linux/renice.md
- pages.nl/linux/rm.md
- pages.nl/linux/rmdir.md
- pages.nl/linux/secon.md
- pages.nl/linux/semanage-boolean.md
- pages.nl/linux/semanage-fcontext.md
- pages.nl/linux/semanage-permissive.md
- pages.nl/linux/semanage-port.md
- pages.nl/osx/arch.md
- pages.nl/osx/bc.md
- pages.nl/osx/netstat.md
- pages.nl/windows/pushd.md
> pages.nl/*: uniform translation for 'See also'

- pages.nl/linux/pacman-d.md
- pages.nl/linux/pacman-database.md
- pages.nl/linux/pacman-deptest.md
- pages.nl/linux/pacman-files.md
- pages.nl/linux/pacman-query.md
- pages.nl/linux/pacman-t.md
- pages.nl/linux/pacman-u.md
- pages.nl/linux/pacman-upgrade.md
- pages/linux/pacman-database.md
- pages/linux/pacman-deptest.md
- pages/linux/pacman-upgrade.md
> pacman-*: update pages and add Dutch translations

- pages.nl/common/jupyterlab.md
> jupyterlab: add Dutch translation

- pages.nl/common/mapfile.md
- pages.nl/common/readarray.md
> mapfile, readarray: add Dutch translation

- pages.es/common/tldr.md
> tldr: update Spanish translation

- pages.nl/common/jupyter-lab.md
> jupyter-lab: add Dutch translation

- .github/CODEOWNERS
I won't be contributing to this, but I can look over the finnish translations.
> CODEOWNERS: add Managor for finnish pages

- pages.es/common/false.md
> false: add Spanish translation

- pages/linux/steamos-chroot.md
> steamos-chroot: add page

- pages/linux/lookandfeeltool.md
- pages/linux/plasma-apply-lookandfeel.md
> lookandfeeltool: convert to alias, plasma-apply-lookandfeel: add page

- pages.es/common/mkdir.md
- pages.fa/common/mkdir.md
- pages.fr/common/mkdir.md
- pages.hi/common/mkdir.md
- pages.id/common/mkdir.md
- pages.it/common/mkdir.md
- pages.ko/common/mkdir.md
- pages.nl/common/mkdir.md
- pages.sr/common/mkdir.md
- pages.ta/common/mkdir.md
- pages.tr/common/mkdir.md
- pages.zh/common/mkdir.md
- pages.zh_TW/common/mkdir.md
- pages/common/mkdir.md
> mkdir: update documentation link

- pages.es/linux/scriptlive.md
> scriptlive: add Spanish translation

- pages/linux/reflector.md
> reflector: add config file example

- pages.it/common/dirname.md
- pages.ko/common/dirname.md
- pages.nl/common/dirname.md
- pages.tr/common/dirname.md
- pages/common/dirname.md
> dirname: update documentation link

- pages.es/linux/kpackagetool6.md
> kpackagetool6: add Spanish translation

- pages.nl/common/if.md
> if: update Dutch translation

- pages.es/linux/steamos-chroot.md
> steamos-chroot: add Spanish translation

- contributing-guides/translation-templates/subcommand-mention.md
- pages.id/common/adb.md
- pages.id/common/ansible.md
- pages.id/common/argocd.md
- pages.id/common/aws-s3.md
- pages.id/common/docker.md
- pages.id/common/git.md
- pages.id/common/pip.md
- pages.id/common/vue.md
Over the past commits it is more preferable to use this new notice format to follow the same passive sentence structure as the English version, and removing any first-person nouns, i.e. "kami" ("we").
> contributing-guides, common/*: revise subcommand mention notices

- pages/linux/aurpublish.md
> aurpublish: add page

- pages.zh/linux/df.md
> df: add Chinese translation

- pages/linux/qmake.md
> qmake: add page

- pages/linux/informant.md
> informant: add page

- pages/common/tqdm.md
> tqdm: add page

- pages.zh/linux/head.md
> head: add Chinese translation

- pages.es/common/pre-commit.md
- pages/common/pre-commit.md
- **Version of the command being documented (if known):** 4.0.1
Translation of git slang gotten from git book Spanish version
> pre-commit: update page, add Spanish translation

- pages.pl/common/ack.md
- pages.pl/common/xkill.md
- pages.pl/linux/groupadd.md
- pages.pl/linux/groupdel.md
- pages.pl/linux/links2.md
- pages.pl/linux/uuid.md
- pages.pl/linux/uuidgen.md
```bash
$ grep -r "Zobacz też" * | wc -l
7
```
```bash
grep -r "Zobacz także" * | wc -l
24
```
> pages.pl/*: replace `zobacz też` with `zobacz także`

- pages/linux/systemd-analyze.md
> systemd-analyze: add baseline command 

- pages.ar/common/cut.md
> cut: add Arabic translation

- pages/linux/libinput.md
> libinput: add page

- pages.zh/linux/dmidecode.md
> dmidecode: add Chinese translation

- pages.zh/linux/ip.md
> ip: add Chinese translation

- pages/common/alacritty.md
> alacritty: update page

- pages/linux/insmod.md
- pages/linux/kmod.md
- pages/linux/lsmod.md
- pages/linux/modinfo.md
- pages/linux/modprobe.md
- pages/linux/rmmod.md
> kmod: add page, *mod*: add 'See also'

- pages/linux/pw-dump.md
> pw-dump: add object dump example

- pages/common/git-maintenance.md
> git-maintenance: clarify description

- pages/common/git-blame.md
> git-blame: add examples

- pages/linux/lxc-create.md
- **Version of the command being documented (if known): 6.0.2**
> lxc-create: add page

- MAINTAINERS.md
> MAINTAINERS: add @MachiavelliII as collaborator

- pages.de/common/exa.md
- pages.fr/common/exa.md
- pages.it/common/exa.md
- pages.ko/common/exa.md
- pages.pl/common/exa.md
- pages/common/exa.md
> exa: update documentation link

- pages.zh/common/arthas-trace.md
- pages.zh/common/arthas-watch.md
- pages.zh/common/arthas.md
- pages/common/arthas-trace.md
- pages/common/arthas-watch.md
- pages/common/arthas.md
- [✔] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [✔] The page(s) have at most 8 examples.
- [✔] The page description(s) have links to documentation or a homepage.
- [✔] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [✔] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [✔] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
> arthas, arthas-{trace,watch}: add page and Chinese translation

- pages.zh/common/xkill.md
> xkill: add Chinese translation

- pages/common/socat.md
> socat: add multicast example

- pages/linux/kde-builder.md
> kde-builder: update initialization

- pages.pl/common/%.md
- pages.pl/common/..md
> ., %: add Polish translation

- pages/common/proxify.md
- **Version of the command being documented (if known): 0.0.15**
> proxify: add page

- pages/common/rails-new.md
> rails-new: add page

- pages/common/rails-console.md
> rails-console: add page

- pages/linux/ip-maddress.md
> ip-maddress: add page

- pages/common/gt.md
Thanks for this awesome tool 🙏 
I noticed that the docs for `gt` or graphite were out of date, so this is a quick PR to update them
> gt: update more information and more commands

- pages/common/whatweb.md
> whatweb: add page

- pages.es/linux/informant.md
> informant: add Spanish translation

- pages.es/linux/aurpublish.md
> aurpublish: add Spanish translation

- pages/common/$.md
> $: add examples

- pages/linux/dialog.md
> dialog: add page

- pages/common/read.md
> read: update more information link

- pages/common/{.md
> {: update more information link

- pages/common/local.md
> local: update more information link

- pages/linux/gtk-launch.md
> gtk-launch: add page

- pages.id/linux/a2disconf.md
- pages.id/linux/a2dismod.md
- pages.id/linux/a2dissite.md
- pages.id/linux/a2enconf.md
- pages.id/linux/a2enmod.md
- pages.id/linux/a2ensite.md
- pages.id/linux/a2query.md
> linux/*: add and update Indonesian translations

- pages/linux/lxc-ls.md
> lxc-ls: add page

- pages.es/linux/libinput.md
> libinput: add Spanish translation

- pages.es/linux/tune.exfat.md
> tune.exfat: add Spanish translation

- pages.es/linux/dump.exfat.md
> dump.exfat: add Spanish translation

- pages.ar/common/zip.md
> zip: add Arabic translation

- pages/common/trip.md
> trip: add page

- pages.es/linux/lxc-create.md
> lxc-create: add Spanish translation

- pages.ar/linux/ufw.md
> ufw: add Arabic translation

- pages.es/linux/fincore.md
> fincore: add Spanish translation

- pages.es/common/dbx.md
> dbx: add Spanish translation

- pages.es/common/uv-add.md
> uv-add: add Spanish translation

- pages.es/common/uv-tree.md
> uv-tree: add Spanish translation

- pages.es/common/alacritty.md
> alacritty: update Spanish translation

- pages.es/linux/insmod.md
> insmod: add Spanish translation

- pages.es/linux/kmod.md
> kmod: add Spanish translation

- pages.es/linux/modinfo.md
> modinfo: add Spanish translation

- pages.es/linux/modprobe.md
> modprobe: add Spanish translation

- pages.es/linux/rmmod.md
> rmmod: add Spanish translation

- pages/common/filebrowser.md
> filebrowser: add page

- pages/linux/opkg.md
> opkg: add examples

- pages/common/stty.md
> stty: add examples

- pages.ar/linux/pacman.md
> pacman: add Arabic translation

- pages/linux/ifstatus.md
> ifstatus: add page

- pages/common/img2sixel.md
> img2sixel: add page

- pages/common/dtrx.md
- **Version of the command being documented (if known):** 8.5.3
> dtrx: add page

- pages/common/snmpwalk.md
> snmpwalk: move to common, update page

- pages.pl/windows/scoop-bucket.md
- pages.pl/windows/scoop.md
> scoop, scoop-bucket: add Polish translation

- pages/common/rails.md
> rails: add `generate`, `db:migrate`, and `routes` examples

- pages/linux/eglinfo.md
> eglinfo: add page

- pages/linux/trap.md
> trap: simplify example and add example

- pages/linux/bwrap.md
> bwrap: add page

- pages.es/common/rails-new.md
> rails-new: add Spanish translation

- pages.ar/common/chisel.md
> chisel: add Arabic translation

- pages.es/common/rails-server.md
> rails-server: add Spanish translation

- pages.ar/common/tr.md
> tr: add Arabic translation

- pages.ar/common/openssl-req.md
> openssl-req: add Arabic translation

- pages.ar/common/openssl-x509.md
> openssl-x509: add Arabic translation

- pages.ar/linux/systemctl.md
> systemctl: add Arabic translation

- pages.es/common/stty.md
> stty: add Spanish translation

- pages.es/common/git-cliff.md
> git-cliff: add Spanish translation

- pages.es/common/bloodhound-python.md
> bloodhound-python: add Spanish translation

- pages.es/linux/ip-maddress.md
> ip-maddress: add Spanish translation

- pages/common/htmlq.md
- **Version of the command being documented (if known):** 0.4.0
> htmlq: add page

- pages.es/common/byobu.md
> byobu: add Spanish translation

- pages.es/common/rails-console.md
> rails-console: add Spanish translation

- pages.es/common/filebrowser.md
> filebrowser: add Spanish translation

- pages.es/common/aider.md
> aider: add Spanish translation

- pages.es/common/rmlint.md
> rmlint: add Spanish translation

- pages/common/docker-image.md
- pages/common/docker.md
> docker: improve example, docker-image: add a pointer towards docker-rmi

- pages/common/mariadb-install-db.md
> mariadb-install-db: add page

- pages/linux/growpart.md
- **Version of the command being documented (if known):** 0.33
> growpart: add page

- pages.ar/linux/rkhunter.md
> rkhunter: add Arabic translation

- pages.ar/linux/dialog.md
> dialog: add Arabic translation

- pages.es/common/bpython.md
> bpython: add Spanish translation

- pages.es/linux/fadvise.md
> fadvise: add Spanish translation

- pages.es/linux/lxc-ls.md
> lxc-ls: add Spanish translation

- pages.es/linux/paxs.md
> paxs: add Spanish translation

- pages.es/common/kubeadm.md
> kubeadm: add Spanish translation

- pages.es/linux/dialog.md
> dialog: add Spanish translation

- pages.es/common/gt.md
> gt: add Spanish translation

- pages.es/linux/opkg.md
> opkg: add Spanish translation

- pages/linux/waypipe.md
> waypipe: add skip vulkan check example

- pages/common/less-than.md
> less-than: add examples

- pages/linux/pw-cat.md
- pages/linux/pw-play.md
- pages/linux/pw-record.md
> pw-cat, pw-record: convert to alias; pw-cat: update more information link

- pages/linux/inxi.md
> inxi: add examples

- pages/common/picotool.md
- **Version of the command being documented (if known):** 2.0.0
> picotool: add page

- pages/linux/pacman-sync.md
> pacman-sync: update page

- contributing-guides/style-guide.md
> style-guide: minor grammar correction

- pages.zh/common/alacritty.md
> alacritty: update Chinese translation

- pages.pl/freebsd/base64.md
- pages.pl/freebsd/cal.md
- pages.pl/freebsd/chpass.md
- pages.pl/freebsd/df.md
- pages.pl/freebsd/look.md
- pages.pl/freebsd/pkg.md
- pages.pl/freebsd/sed.md
- pages.pl/freebsd/sockstat.md
> pages.pl/freebsd/*: add Polish translations

- pages/common/print.md
> print: fix typo in line 13

- pages/common/gdb.md
- pages/linux/coredumpctl.md
> gdb, coredumpctl: add prompt skip examples

- pages/common/ani-cli.md
> ani-cli: add two examples

- pages.es/common/htmlq.md
> htmlq: add Spanish translation

- pages/common/protoc.md
> protoc: add encode/decode commands

- pages/common/pulumi-state.md
> pulumi-state: add page

- pages.es/linux/kde-builder.md
> kde-builder: update Spanish translation

- pages/common/nhentai.md
> nhentai: fix issues

- pages/freebsd/procstat.md
> procstat: add page

- pages.nl/common/$.md
- pages.nl/common/..md
- pages.nl/common/alacritty.md
- pages.nl/common/ani-cli.md
- pages.nl/common/read.md
- pages.nl/common/stty.md
- pages.nl/linux/kill.md
- pages.nl/linux/pacman-sync.md
- pages.nl/linux/pw-play.md
- pages.nl/linux/pw-record.md
- pages/linux/pacman-sync.md
> pages.nl/*: add/update translations, pacman-sync: rewrite

- contributing-guides/style-guide.md
> style-guide: do not translate example.com

- pages.es/linux/growpart.md
> growpart: add Spanish translation

- pages.es/linux/fuzzel.md
> fuzzel: add Spanish translation

- pages.es/common/dtrx.md
> dtrx: add Spanish translation

- pages/common/vagrant-plugin.md
https://developer.hashicorp.com/vagrant/docs/cli/plugin#plugin-uninstall
> vagrant-plugin: fix uninstall command

- pages/common/ghostty.md
Some examples were taken from here: https://github.com/tldr-pages/tldr/issues/15371#issuecomment-2616877239
Closes #15371.
> ghostty: add page

- pages.es/common/mariadb-install-db.md
> mariadb-install-db: add Spanish translation

- pages.es/linux/bwrap.md
> bwrap: add Spanish translation

- pages.es/linux/bluebuild.md
> bluebuild: add Spanish translation

- pages.es/linux/eglinfo.md
> eglinfo: add Spanish translation

- pages.es/common/picotool.md
> picotool: add Spanish translation

- pages.es/common/nhentai.md
> nhentai: add Spanish translation

- pages/common/snmpbulkget.md
- pages/common/snmpdf.md
- pages/common/snmpgetnext.md
- pages/common/snmpset.md
- pages/common/snmpstatus.md
- pages/common/snmptable.md
- pages/common/snmptest.md
> snmp{getnext, bulkget, set, test, status, table, df}: add page

- contributing-guides/style-guide.md
> style-guide: add disambiguation page documentation

- pages.es/common/vagrant-plugin.md
> vagrant-plugin: add Spanish translation

- pages.es/linux/chsh.md
> chsh: add Spanish translation

- pages.es/freebsd/procstat.md
> procstat: add Spanish translation

- pages.ko/linux/pw-loopback.md
- pages.pt_BR/linux/pw-loopback.md
- pages.tr/linux/pw-loopback.md
- pages/linux/pw-loopback.md
> pw-loopback: update more information

- contributing-guides/style-guide.md
> style-guide: fix table of contents

- pages.es/windows/es.md
> es: add Spanish translation

- pages.es/common/pulumi-env.md
> pulumi-env: add Spanish translation

- pages.es/common/img2sixel.md
> img2sixel: add Spanish translation

- pages.es/linux/ifstatus.md
> ifstatus: add Spanish translation

- pages.es/common/snmpget.md
> snmpget: add Spanish translation

- pages.es/linux/logread.md
> logread: add Spanish translation

- pages.es/common/ghostty.md
> ghostty: add Spanish translation

- pages.es/common/olevba.md
> olevba: add Spanish translation

- pages.es/linux/smbcacls.md
> smbcacls: add Spanish translation

- contributing-guides/style-guide.md
> style-guide: fix grammar

- pages/linux/ubus.md
> ubus: add page

- pages/common/pulumi-refresh.md
> pulumi-refresh: add page

- pages/linux/yakuake.md
> yakuake: add page

- pages.es/linux/mangohud.md
> mangohud: add Spanish translation

- pages.es/common/lazygit.md
> lazygit: add Spanish translation

- pages.es/linux/bootc-switch.md
> bootc-switch: add Spanish translation

- pages.es/common/virsh.md
> virsh: add Spanish translation

- pages.es/common/exa.md
> exa: add Spanish translation

- pages.es/linux/gtk-launch.md
> gtk-launch: add Spanish translation

- pages.es/common/protoc.md
> protoc: add Spanish translation

- pages.ko/linux/gcrane-completion.md
- pages.ko/osx/gcrane-completion.md
- pages.nl/linux/gcrane-completion.md
- pages.nl/osx/gcrane-completion.md
- pages/linux/gcrane-completion.md
- pages/osx/gcrane-completion.md
> gcrane-completition: fix broken syntax

- pages/linux/uci.md
> uci: add page

- CLIENT-SPECIFICATION.md
> CLIENT-SPECIFICATION: remove useless newlines

- pages/common/getnpusers.py.md
- pages/common/impacket-getnpusers.md
> GetNPUsers.py, impacket-GetNPUsers: add page

- CLIENT-SPECIFICATION.md
> CLIENT-SPECIFICATION: remove trailing whitespace

- README.md
> README: remove trailing whitespace

- pages/linux/uname.md
> uname: add shortform options

- pages/common/snmpdf.md
- pages/common/snmpgetnext.md
- pages/common/snmpset.md
- pages/common/snmpstatus.md
- pages/common/snmptable.md
- pages/common/snmptest.md
> snmp*: fix example mistakes

- pages/common/git-feature.md
- pages/linux/mkfs.md
> mkfs, git-feature: fix GitHub preview rendering

- pages/linux/iwinfo.md
> iwinfo: add page

- pages/linux/apachectl.md
> apachectl: add page

- pages.ar/common/dhclient.md
> dhclient: add Arabic translation

- pages/common/impacket-mssqlclient.md
- pages/common/mssqlclient.py.md
> mssqlclient.py, impacket-mssqlclient: add page

- pages.zh/common/print.md
- pages.zh/common/print.zsh.md
- pages.zh/common/printenv.md
- pages.zh/common/printf.md
> printf, print.zsh, print, printenv: add Chinese translation

- pages.zh/linux/cryptsetup-luksformat.md
> cryptsetup-luksformat: add Chinese translation

- pages.es/linux/ubus.md
> ubus: add Spanish translation

- pages.es/common/pulumi-refresh.md
> pulumi-refresh: add Spanish translation

- pages/common/getuserspns.py.md
- pages/common/impacket-getuserspns.md
> GetUserSPNs.py, impacket-GetUserSPNs: add page

- pages/common/btop.md
> btop: add exit example

- pages/linux/lbu.md
> lbu: add option placeholders

- pages.es/common/ack.md
> ack: fix typo in Spanish translation

- pages/common/o.md
> o: add page

- pages/common/htop.md
- pages/common/id.md
- pages/common/picocom.md
- pages/common/su.md
- pages/common/tcpdump.md
- pages/common/uniq.md
- pages/common/wc.md
- pages/common/xargs.md
- pages/linux/agetty.md
- pages/linux/cu.md
- pages/linux/dmesg.md
- pages/linux/halt.md
- pages/linux/iostat.md
- pages/linux/iptables.md
- pages/linux/minicom.md
- pages/linux/reboot.md
- pages/linux/rmdir.md
- pages/linux/shutdown.md
- pages/linux/strace.md
- pages/linux/systemctl.md
> *: add more option placeholders

- pages/common/getarch.py.md
- pages/common/impacket-getarch.md
> getArch.py, impacket-getArch: add page

- pages/osx/herd-list.md
> herd-list: add page

- contributing-guides/style-guide.md
> style-guide: reorder instructions

- pages/linux/lxc-console.md
> lxc-console: add page

- pages.es/common/tcpreplay.md
> tcpreplay: add Spanish translation

- pages.es/linux/iwinfo.md
> iwinfo: add Spanish translation

- pages.es/common/wezterm.md
> wezterm: add Spanish translation

- pages/common/phpstan.md
> phpstan: edit page

- pages/common/tailscale-file.md
- pages/common/tailscale-ssh.md
- pages/common/tailscale-up.md
- pages/common/tailscale.md
> tailscale*: update page

- pages/common/impacket-sniff.md
- pages/common/impacket-sniffer.md
- pages/common/sniff.py.md
- pages/common/sniffer.py.md
> sniff.py, sniffer.py, impacket-{sniff, sniffer}: add page

- pages/linux/parted-interactive.md
> parted-interactive: add reference to parted

- pages/linux/systemd-ask-password.md
> systemd-ask-password: refresh page

- pages/linux/ubuntu-drivers.md
> ubuntu-drivers: add page

- pages.ar/common/node.md
> node: add Arabic translation

- pages/common/byobu.md
> byobu: add exit instructions

- pages/common/docker-exec.md
- pages/common/docker-images.md
- pages/common/docker-logs.md
- pages/common/docker-ps.md
- pages/common/docker-pull.md
- pages/common/docker-rm.md
- pages/common/docker-run.md
- pages/common/docker-start.md
- pages/common/docker.md
> docker*: add option placeholders

- pages/linux/systemctl-enable.md
- pages/linux/systemd-disable.md
> systemctl-{enable, disable}: add page

- pages/common/hostname.md
> hostname: remove non-functional example and add option placeholders

- pages/osx/herd.md
> herd: add page

- contributing-guides/style-guide.md
- pages/common/rg.md
> rg, style-guide: improve heading wording

- pages/common/npm-config.md
- **Version of the command being documented (if known):11.2.0**
#14000
> npm-config: add page

- pages/common/browsh.md
> browsh: add page

- pages/common/,.md
- pages/common/comma.md
- scripts/wrong-filename.sh
- **Version of the command being documented (if known):** 1.9.0
> comma: add page

- contributing-guides/style-guide.md
> style-guide: instruct option grouping and clarify option instructions

- pages/linux/apt.md
`apt search package` will search within metadata like description, homepage, etc. Passing in `-n` will make sure only package names are searched.
> apt: update page

- pages/common/suspend.md
> suspend: clarify description

- pages/common/type.md
The live version of this page points to a more-information link that does not describe the possible command argument flags.
> type: improve more information link

- pages/common/npm-deprecate.md
- Version of the command being documented (if known):*11.2.0*
> npm-deprecate: add page

- pages/linux/ip-route-show.md
- pages/linux/ip-route.md
> ip-{route-show, route}: fix command and clarify

- pages/linux/yakuake.md
> yakuake: fix typo

- pages/linux/hollywood.md
> hollywood: add page

- pages/common/compgen.md
> compgen: add examples

- pages/linux/lldpctl.md
> lldpctl: add page

- pages/linux/ip-rule.md
> ip-rule: fix example description and add generic table creation example

- pages/linux/ip-route-add.md
> ip-route-add: add page

- pages.es/linux/expac.md
> expac: add Spanish translation

- pages.es/common/bacon.md
> bacon: add Spanish translation

- pages.es/common/comma.md
> comma: add Spanish translation

- pages.es/common/npm-config.md
> npm-config: add Spanish translation

- pages/common/passwd.md
> passwd: add script example

- pages/common/at.md
> at: add examples

- pages/osx/date.md
> date: add relative date example osx

- pages/common/aws-s3-sync.md
> aws-s3-sync: add page

- pages.es/linux/hollywood.md
> hollywood: add Spanish translator

- pages.es/linux/ubuntu-drivers.md
> ubuntu-drivers: add Spanish translation

- pages/common/tailscale-set.md
> tailscale-set: add page

- pages.es/common/dockdiver.md
> dockdiver: add Spanish translation

- pages.es/linux/cdrdao.md
- pages.es/linux/dnf-group.md
- pages.ko/linux/init.md
- pages.nl/linux/dnf-group.md
- pages/common/qcp.md
- pages/common/qmv.md
- pages/linux/atool.md
- pages/linux/cdrdao.md
- pages/linux/dnf-group.md
- pages/linux/init.md
- pages/linux/lldpctl.md
- pages/linux/nl.md
- pages/linux/yakuake.md
> *: shorten manned links

- pages.es/common/ng.md
> ng: add Spanish translation

- pages/common/patator.md
- **Version of the command being documented (if known): 1.1.0**
> patator: add page

- pages.ko/common/brew-update.md
- pages.ko/common/brew-upgrade.md
- pages/common/brew-update.md
- pages/common/brew-upgrade.md
Noticed some outdated links so I updated them.
> brew-update, brew-upgrade: update documentation links

- pages/common/zmap.md
> zmap: add page

- pages/common/brew-services.md
> brew-services: add page

- pages.es/common/hledger.md
> hledger: add Spanish translation

- pages/common/copr-cli.md
- pages/common/copr.md
> copr, copr-cli: add page

- pages.es/common/tofu.md
> tofu: add Spanish translation

- pages.es/common/tofu-output.md
> tofu-output: add Spanish translation

- pages.es/common/tofu-fmt.md
> tofu-fmt: add Spanish translation

- pages.es/common/marimo.md
> marimo: add Spanish translation

- pages/common/rsactftool.py.md
> RsaCtfTool.py: add page

- pages/linux/wpctl.md
> wpctl: add limit example

- pages/linux/steamos-select-branch.md
> steamos-select-branch: add page

- pages/linux/mkinitfs.md
> mkinitfs: add page

- pages/linux/emerge.md
> emerge: fix typo

- pages/common/pandoc.md
> pandoc: update page

- pages/linux/patool.md
Add description of the 'create' command!
> patool: add example

- pages/common/eza.md
- **Version of the command being documented:** Tested on versions 0.18.9 and 0.21.0
> eza: update page

- pages/common/masscan.md
> masscan: add example

- pages/windows/py.md
> py: add page

- pages/linux/caligula.md
- **Version of the command being documented (if known):** 0.4.8
> caligula: add page

- pages.es/common/o.md
> o: add Spanish translation

- pages.es/linux/resize.md
> resize: add Spanish translation

- pages.es/linux/apachectl.md
> apachectl: add Spanish translation

- pages.es/common/rsactftool.py.md
> rsactftool.py: add Spanish translation

- pages.es/common/copr.md
- [] The page(s) have at most 8 examples.
> copr: add Spanish translation

- pages.es/common/gpg2.md
> gpg2: add Spanish translation

- pages.es/common/impacket-getadusers.md
> impacket-getadusers: add Spanish translation

- pages.es/common/impacket-getarch.md
> impacket-getarch: add Spanish translation

- pages.es/common/impacket-getnpusers.md
> impacket-getnpusers: add Spanish translation

- pages.es/common/impacket-mssqlclient.md
> impacket-mssqlclient: add Spanish translation

- pages.es/common/impacket-secretsdump.md
> impacket-secretsdump: add Spanish translation

- pages.es/common/impacket-sniff.md
> impacket-sniff: add Spanish translation

- pages.es/common/impacket-sniffer.md
> impacket-sniffer: add Spanish translation

- pages.es/common/jupyterlab.md
> jupyterlab: add Spanish translation

- pages.es/common/mapfile.md
> mapfile: add Spanish translation

- pages.es/linux/avahi-resolve-address.md
> avahi-resolve-address: add Spanish translation

- pages.es/linux/avahi-resolve-host-name.md
> avahi-resolve-host-name: add Spanish translation

- pages.es/linux/i386.md
> i386: add Spanish translation

- pages.es/linux/lex.md
> lex: add Spanish translation

- pages.zh/common/,.md
> ,: add Chinese translation

- pages.zh/linux/iostat.md
> linux/iostat: add Chinese translation

- pages.zh/common/git-check-mailmap.md
- pages.zh/common/git-check-ref-format.md
> git-{check-mailmap, check-ref-format}: add Chinese translation

- pages/linux/chage.md
> chage: fix typo

- pages.es/linux/pw-record.md
> pw-record: add Spanish translation

- pages/common/sfdk-check.md
- pages/common/sfdk-deploy.md
- pages/common/sfdk-emulator-device-model-show.md
- pages/common/sfdk-emulator-install.md
- pages/common/sfdk-emulator-start.md
- pages/common/sfdk-init.md
- pages/common/sfdk-maintain.md
- pages/common/sfdk-qmltypes.md
- pages/common/sfdk-scrape.md
- pages/common/sfdk-undeploy.md
- pages/common/sfdk.md
@roundedrectangle I did some asking around and I was provided a link to the github repository.
I'll probably add option placeholders as I think I can find them from the code here.
> sfdk*: add more information links and option placeholders

- pages.es/linux/pacman-u.md
> pacman-u: add Spanish translation

- pages.es/linux/pw-play.md
> pw-play: add Spanish translation

- pages.es/linux/pacman-t.md
> pacman-t: add Spanish translation

- pages.es/linux/pacman-d.md
> pacman-d: add Spanish translation

- pages.es/linux/linux64.md
> linux64: add Spanish translation

- pages.es/linux/linux32.md
> linux32: add Spanish translation

- pages/common/gomi.md
- **Version of the command being documented (if known):** v0.0.0-20250320175644-1375d048b87e
For the time being, `gomi` does not have a man page, thus, instead of [manned](manned.org), I decided to link the [github](https://github.com/babarot/gomi) repository. 
I also believe since there is no actual man page, the `tldr` command should be a must for this program. There is a [website](https://gomi.dev/) but hardly contains any help with the command.
> gomi: add page

- pages/linux/mkfs.vfat.md
> mkfs.vfat: convert to alias

- pages/linux/mkfs.exfat.md
The page was created 10 years ago. I assume the options were changed somewhere along the line.
> mkfs.exfat: update page

- pages.es/linux/uname26.md
> uname26: add Spanish translation

- pages.es/linux/trash-put.md
> trash-put: add Spanish translation

- pages/linux/abrt.md
> abrt: add alias page

- pages/linux/mkfs.bcachefs.md
- pages/linux/mkfs.btrfs.md
- pages/linux/mkfs.cramfs.md
- pages/linux/mkfs.exfat.md
- pages/linux/mkfs.ext4.md
- pages/linux/mkfs.f2fs.md
- pages/linux/mkfs.fat.md
- pages/linux/mkfs.md
- pages/linux/mkfs.minix.md
- pages/linux/mkfs.ntfs.md
- pages/linux/mkfs.xfs.md
> mkfs*: unify format

- pages.es/linux/mkfs.vfat.md
> mkfs.vfat: add Spanish translation

- pages.es/linux/abrt.md
> abrt: add Spanish translation

- pages/linux/yay.md
> yay: add --noconfirm 

- pages/common/git-clone.md
- [ x ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ x ] The page(s) have at most 8 examples.
- [ x ] The page description(s) have links to documentation or a homepage.
- [ x ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ x ] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [ x ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
> git clone: fix typo

- pages/linux/eclean-kernel.md
- **Version of the command being documented (if known): [0.6.8](https://gitweb.gentoo.org/repo/gentoo.git/tree/app-portage/gentoolkit/gentoolkit-0.6.8.ebuild)**
> eclean-kernel: add page

- pages/common/duckdb.md
- **Version of the command being documented (if known):** 1.2.1
> duckdb: add UI example

- pages/common/ansible-lint.md
> ansible-lint: add page

- pages.nl/linux/abrt.md
- pages.nl/linux/mkfs.vfat.md
> abrt, mkfs.vfat: add Dutch translation

- pages/common/figlist.md
> figlist: add page

- pages/common/chkfont.md
> chkfont: add page

- pages.de/common/brew-bundle.md
- pages.fr/common/brew-bundle.md
- pages.id/common/brew-bundle.md
- pages.it/common/brew-bundle.md
- pages.ko/common/brew-bundle.md
- pages/common/brew-bundle.md
The upstream repository has been archived, and the code moved into the main https://github.com/homebrew/Brew repository, so link to the documentation for the specific command instead.
> brew-bundle: update more information url

- pages.es/common/ac.md
> ac: update Spanish translation

- pages/common/autojump.md
- pages/common/bashmarks.md
- pages/common/darkhttpd.md
- pages/common/deluge-console.md
- pages/common/dhcpwn.md
- pages/common/forever.md
- pages/common/fossa.md
- pages/common/hn.md
- pages/common/jpegoptim.md
- pages/common/kahlan.md
- pages/common/keybase.md
- pages/common/kubectx.md
- pages/common/kubens.md
- pages/common/lua.md
- pages/common/luac.md
- pages/common/ngrep.md
- pages/common/peerflix.md
- pages/common/phive.md
- pages/common/phpstorm.md
- pages/common/picard.md
- pages/common/pickle.md
- pages/common/rdfind.md
- pages/common/skicka.md
- pages/common/slackcat.md
- pages/common/spike.md
- pages/common/sqlite3.md
- pages/common/st-flash.md
- pages/common/velero.md
- pages/common/virtualenv.md
- pages/common/yarn.md
By using `git ls-files -z | xargs -0 -n1 -I{} -- git log -1 --format="%ai {}" {} | sort -r` I was able to sort files by their last modification date. Then I just took the oldest files with no changes and updated them.
> common*: refresh old pages part 1

- pages.zh/common/git-create-branch.md
- pages.zh/common/git-credential.md
> git-{create-branch, credential}: add Chinese translation

- pages/common/buku.md
- pages/common/cronic.md
- pages/common/csvtool.md
- pages/common/dirsearch.md
- pages/common/dokku.md
- pages/common/flow.md
- pages/common/git-replace.md
- pages/common/git-show-ref.md
- pages/common/jupyter.md
- pages/common/lt.md
- pages/common/makebuildserver.md
- pages/common/matlab.md
- pages/common/mdp.md
- pages/common/middleman.md
- pages/common/mmdc.md
- pages/common/nasm.md
- pages/common/ocaml.md
- pages/common/ocamlc.md
- pages/common/ocamlfind.md
- pages/common/ocamlopt.md
- pages/common/pass-otp.md
- pages/common/qr.md
- pages/common/reflac.md
- pages/common/sequelize.md
- pages/common/sqlmap.md
- pages/common/terraform.md
- pages/common/thunderbird.md
- pages/common/tmpmail.md
- pages/common/xmlto.md
By using `git ls-files -z | xargs -0 -n1 -I{} -- git log -1 --format="%ai {}" {} | sort -r` I was able to sort files by their last modification date. Then I just took the oldest files with no changes and updated them.
> common*: refresh old pages part 3

- pages/common/{.md
> {: change example

- pages/common/chars.md
- pages/common/drupal-check.md
- pages/common/drush.md
- pages/common/grumphp.md
- pages/common/guacd.md
- pages/common/info.md
- pages/common/jp2a.md
- pages/common/makebuildserver.md
- pages/common/pageres.md
- pages/common/robo.md
- pages/common/shiori.md
- pages/common/vue-build.md
- pages/common/vue-serve.md
- pages/common/vue.md
By using `git ls-files -z | xargs -0 -n1 -I{} -- git log -1 --format="%ai {}" {} | sort -r` I was able to sort files by their last modification date. Then I just took the oldest files with no changes and updated them.
> common*: refresh old pages part 4

- pages/common/webpmux.md
> webpmux: add page

- pages/linux/addr2line.md
- pages/linux/bpftrace.md
- pages/linux/flatpak-builder.md
- pages/linux/gnome-terminal.md
- pages/linux/gs.md
- pages/linux/jpegtran.md
- pages/linux/lxi.md
- pages/linux/mklost+found.md
- pages/linux/mocp.md
- pages/linux/openvpn3.md
- pages/linux/partprobe.md
- pages/linux/pulseaudio.md
- pages/linux/tune2fs.md
- pages/linux/updatedb.md
- pages/linux/uuidd.md
- pages/linux/wifi-menu.md
- pages/linux/xfce4-screenshooter.md
By using `git ls-files -z | xargs -0 -n1 -I{} -- git log -1 --format="%ai {}" {} | sort -r` I was able to sort files by their last modification date. Then I just took the oldest files with no changes and updated them.
> linux*: refresh old pages part 3

- pages.es/linux/arptables.md
> arptables: add Spanish translation

- pages.es/common/abduco.md
> abduco: update Spanish translation

- pages.es/common/act.md
> act: update Spanish translation

- pages.es/common/ag.md
> ag: update Spanish translation

- pages.es/common/ani-cli.md
> ani-cli: update Spanish translation

- pages.es/common/bash.md
> bash: update Spanish translation

- pages/common/wlsunset.md
> wlsunset: add page

- pages/linux/fadvise.md
> fadvise: fix example

- pages/common/cariddi.md
- **Version of the command being documented (if known): 1.4.0**
> cariddi: add page

- pages/common/sfdk-apply.md
- pages/common/sfdk-build-init.md
- pages/common/sfdk-build-requires.md
- pages/common/sfdk-build-shell.md
- pages/common/sfdk-check.md
- pages/common/sfdk-cmake.md
- pages/common/sfdk-compiledb.md
- pages/common/sfdk-config.md
- pages/common/sfdk-deploy.md
- pages/common/sfdk-device.md
- pages/common/sfdk-emulator-exec.md
- pages/common/sfdk-emulator-set.md
- pages/common/sfdk-emulator.md
- pages/common/sfdk-engine.md
- pages/common/sfdk-init.md
- pages/common/sfdk-make.md
- pages/common/sfdk-package.md
- pages/common/sfdk-prepare.md
- pages/common/sfdk-qmake.md
- pages/common/sfdk-undeploy.md
- pages/common/sfdk.md
@roundedrectangle Running this through you to make sure that the new links are better.
> sfdk*: update more information link

- pages/linux/mkinitcpio.md
> mkinitcpio: refresh page

- pages/common/ascii-image-converter.md
> ascii-image-converter: add note and example

- pages/linux/kscreen-console.md
- pages/linux/kscreen-doctor.md
> kscreen-{console, doctor}: add option placeholders

- pages/common/spectacle.md
- pages/linux/kinfocenter.md
- pages/linux/systemsettings.md
> kinfocenter, systemsettings: add page; spectacle: add example

- pages/linux/mount.md
> mount: simplify example

- pages/linux/iwctl.md
> iwctl: refresh page

- pages.nl/common/musescore.md
> musescore: update Dutch More Info link

- pages/common/figlet.md
> figlet: make examples more universal

- pages/linux/locale-gen.md
- pages/linux/localedef.md
> locale-gen, localedef: add page

- pages/common/fc-cache.md
- **Version of the command being documented (if known): 2.15.0**
> fc-cache: add examples

- pages/linux/kde-builder.md
These seem to have been combined to this at some point.
> kde-builder: simplify initialization

- pages.nl/common/indent.md
- pages.nl/common/inkscape.md
- pages.nl/common/install.md
- pages/common/inkscape.md
> pages.nl/common/i*: update Dutch translation

- pages.nl/common/look.md
> look: update Dutch translation

- pages.nl/common/killall.md
> killall: update Dutch translation

- pages.nl/common/just.1.md
> just: update Dutch translation

- pages.nl/common/fgrep.md
- pages.nl/common/fmt.md
> pages.nl/common/f*: update Dutch translation

- pages.nl/common/egrep.md
- pages.nl/common/env.md
- pages.nl/common/expand.md
> pages.nl/common/e*: update Dutch translation

- pages.nl/common/chroot.md
- pages.nl/common/clamscan.md
- pages.nl/common/clang.md
- pages.nl/common/clj.md
- pages.nl/common/cut.md
> pages.nl/common/c*: update Dutch translation

- pages.nl/common/stty.md
> stty: update Dutch translation

- pages.nl/common/date.md
- pages.nl/common/dircolors.md
- pages.nl/common/dirname.md
- pages.nl/common/docker-rm.md
- pages.nl/common/docker.md
> pages.nl/common/d*: update Dutch translation

- pages/common/bandwhich.md
- pages/common/buku.md
- pages/common/fakedata.md
- pages/common/gh-alias.md
- pages/common/gh-api.md
- pages/common/gh-auth.md
- pages/common/gh-browse.md
- pages/common/gh-completion.md
- pages/common/gh-gist.md
- pages/common/gh-issue-create.md
- pages/common/gh-issue.md
- pages/common/gh-label.md
- pages/common/gh-pr-create.md
- pages/common/gh-pr-merge.md
- pages/common/gh-pr.md
- pages/common/gh-repo.md
- pages/common/gh-run.md
- pages/common/gh-screensaver.md
- pages/common/gh-secret-set.md
- pages/common/gh-secret.md
- pages/common/gh-ssh-key.md
- pages/common/gh-workflow.md
- pages/common/gh.md
- pages/common/peludna-prognoza.md
- pages/common/virsh-undefine.md
- pages/common/virt-clone.md
- pages/common/virt-install.md
- pages/common/virt-qemu-run.md
- pages/common/virt-sparsify.md
- pages/common/x11docker.md
By using `git ls-files -z | xargs -0 -I{} -- git log -1 --format="%ai {}" {} | sort -r` I was able to sort files by their last modification date. Then I just took the oldest files with no changes and updated them.
> common*: refresh old pages part 6

- pages/common/awslogs.md
- pages/common/chronic.md
- pages/common/dillo.md
- pages/common/dirsearch.md
- pages/common/fdroid.md
- pages/common/geth.md
- pages/common/git-fame.md
- pages/common/git-ignore-io.md
- pages/common/git-ignore.md
- pages/common/git-ls-remote.md
- pages/common/git-root.md
- pages/common/jhipster.md
- pages/common/josm.md
- pages/common/minifab.md
- pages/common/mongoimport.md
- pages/common/mpg321.md
- pages/common/nix-classic.md
- pages/common/nix3-search.md
- pages/common/podman-rmi.md
- pages/common/raco.md
- pages/common/react-native-start.md
- pages/common/rustscan.md
- pages/common/scalafmt.md
- pages/common/siege.md
- pages/common/spotdl.md
- pages/common/tlmgr-info.md
- pages/common/vboxmanage-cloud.md
- pages/common/whois.md
- pages/common/wrangler.md
- pages/common/xml-validate.md
By using `git ls-files -z | xargs -0 -I{} -- git log -1 --format="%ai {}" {} | sort -r` I was able to sort files by their last modification date. Then I just took the oldest files with no changes and updated them.
I also hunted a couple of pages by running `grep -r "\.\.\." --color`
> common*: refresh old pages part 8

- pages/common/nuclei.md
> nuclei: add option placeholders

- pages/common/pueue-completions.md
- pages/common/sfdk-compiledb.md
- pages/common/sfdk-qmltypes.md
- pages/linux/mcookie.md
> sfdk-{compiledb, qmltypes}, pueue-completions, mcookie: use imperative mood

- pages/common/netstat.md
No one is ever typing all of that out.
> netstat: add option placeholders

- pages/linux/setfont.md
> setfont: add page

- pages/common/tmux.md
> tmux: add option placeholders and mnemonics

- pages/linux/pkexec.md
> pkexec: add page

- pages.es/common/rsactftool.py.md
- pages/common/rsactftool.py.md
> RsaCtfTool: fix page title

- pages/common/naabu.md
> naabu: update page

- pages/common/dnsx.md
> dnsx: update page

- pages/common/httpx.md
> httpx: update page

- pages/linux/systemd-analyze.md
> systemd-analyze: add example

- pages.nl/linux/avahi-resolve.md
> avahi-resolve: add Dutch translation

- pages.nl/common/lckdo.md
- pages.nl/linux/flock.md
- pages/linux/flock.md
> flock: add Dutch translation, lckdo: update More Info

- pages.nl/common/whois.md
> whois: update Dutch More Info link

- pages.nl/freebsd/ipmitool.md
- pages/freebsd/ipmitool.md
> ipmitool: add Dutch translation

- pages.nl/sunos/share.md
> share: add Dutch translation

- pages.nl/freebsd/procstat.md
> procstat: add Dutch translation

- pages.nl/windows/microsoft-edge.md
> microsoft-edge: update Dutch translation

- pages/common/git-apply.md
- pages/common/hydra.md
- pages/common/iex.md
- pages/common/ippeveps.md
- pages/common/medusa.md
- pages/common/meson.md
- pages/common/mg.md
- pages/common/mp3info.md
- pages/common/mupdf.md
- pages/common/mutool.md
- pages/common/mutt.md
- pages/common/mvn.md
- pages/common/neomutt.md
- pages/common/nmblookup.md
- pages/common/nokogiri.md
- pages/common/nxc-ftp.md
- pages/common/nxc-ldap.md
- pages/common/nxc-mssql.md
- pages/common/nxc-rdp.md
- pages/common/nxc-smb.md
- pages/common/nxc-ssh.md
- pages/common/nxc-vnc.md
- pages/common/nxc-winrm.md
- pages/common/nxc-wmi.md
- pages/common/racket.md
- pages/common/ruby.md
- pages/common/sngrep.md
- pages/common/w3m.md
- pages/common/wal.md
- pages/common/xe.md
These were found with `grep -rl " -[A-Z][^a-zA-Z]" | xargs -n1 code`
> *: add option placeholders

- pages.nl/common/git.md
> git: update Dutch More Info link

- pages.es/common/git-sizer.md
- pages.fr/common/git-sizer.md
- pages.it/common/git-sizer.md
- pages.ko/common/git-sizer.md
- pages.ko/common/npm-home.md
- pages.ko/common/virsh-undefine.md
- pages.pt_BR/common/virsh-undefine.md
- pages.tr/common/git-sizer.md
> pages.*/common/*: match page title with English page

- pages/common/mqtt_check.py.md
- pages/common/ntfs-read.py.md
> mqtt_check.py, ntfs-read.py: comply with style-guide

- pages/common/rustup-install.md
- pages/common/rustup-uninstall.md
> rustup-uninstall: add page; rustup-install: convert to alias

- pages/common/cmake.md
- pages/common/cppcheck.md
- pages/common/dalfox.md
- pages/common/gdown.md
- pages/common/gfortran.md
- pages/common/ghc.md
> cmake, cppcheck, dalfox, gdown, gfortran, ghc: add option placeholders and update more information

- pages/linux/lsusb.md
> lsusb: fix switch case

- pages.nl/linux/ip-route-list.md
> ip-route-list: update Dutch translation

- pages.nl/common/crane-registry.md
- pages.nl/common/crane.md
- pages.nl/common/gcrane-help.md
- pages.nl/common/more.md
- pages.nl/common/radare2.md
- pages.nl/linux/more.md
- pages.nl/windows/finger.md
> pages.nl/*: better wording

- pages.es/common/asciinema.md
> asciinema: update Spanish translation

- pages.es/common/adb.md
> adb: update Spanish translation

- pages.es/common/$.md
> $: update Spanish translation

- pages/common/kite.md
- pages/common/kiterunner-brute.md
- pages/common/kiterunner-kb.md
- pages/common/kiterunner-scan.md
- pages/common/kiterunner-wordlist.md
- pages/common/kiterunner.md
- pages/common/kr.md
> kiterunner-{brute, kb, scan, wordlist}, kite, kr: add page

- pages/common/x8.md
> x8: add page

- pages.nl/common/rustup-install.md
- pages.nl/common/rustup-toolchain.md
- pages.nl/common/rustup-uninstall.md
> rustup-*: add Dutch translation

- pages.nl/common/impacket-ntfs-read.md
- pages.nl/common/ntfs-read.py.md
> impacket-ntfs-read, ntfs-read.py: add Dutch translation

- pages/common/case.md
> case: use long options

- pages.es/common/history.md
- pages.id/common/history.md
- pages.ja/common/history.md
- pages.ko/common/history.md
- pages.pt_BR/common/history.md
- pages.pt_PT/common/history.md
- pages.ru/common/history.md
Matching more information links with the english `history.md` page.
> history: update more information link

- pages.de/common/alacritty.md
- pages.fr/common/alacritty.md
- pages.id/common/alacritty.md
- pages.it/common/alacritty.md
- pages.ko/common/alacritty.md
- pages.pt_BR/common/alacritty.md
- pages.pt_PT/common/alacritty.md
- pages.zh/common/alacritty.md
> alacritty: update more information link

- pages.fr/common/ag.md
- pages.id/common/ag.md
- pages.it/common/ag.md
- pages.ja/common/ag.md
- pages.ko/common/ag.md
- pages.pl/common/ag.md
- pages.pt_BR/common/ag.md
- pages.ru/common/ag.md
- pages.zh/common/ag.md
> ag: update more information link

- pages.ar/common/tr.md
> tr: update Arabic page

- pages/common/godot.md
- **Version of the command being documented (if known):** 4.4-stable
> godot: update `--export` example to `--export-release`

- pages/common/doctl-account.md
- pages/common/doctl-auth.md
- pages/common/doctl-balance.md
- pages/common/doctl-databases-db.md
- pages/common/doctl-databases-firewalls.md
- pages/common/doctl-databases-maintenance-window.md
- pages/common/doctl-databases-options.md
- pages/common/doctl-databases-pool.md
- pages/common/doctl-databases-replica.md
- pages/common/doctl-databases-sql-mode.md
- pages/common/doctl-databases-user.md
- pages/common/doctl-databases.md
- pages/common/handbrakecli.md
- pages/common/ipaggmanip.md
- pages/common/jadx.md
- pages/common/mongodump.md
By using `git ls-files -z | xargs -0 -I{} -- git log -1 --format="%ai {}" {} | sort -r` I was able to sort files by their last modification date. Then I just took the oldest files with no changes and updated them.
> common*: refresh old pages part 10

- pages/linux/bcachefs.md
I did not test it. I copied the example from here https://old.reddit.com/r/bcachefs/comments/18rp9lc/how_exactly_do_snapshots_work/
> bcachefs: add snapshot example

- pages/common/watchexec.md
> watchexec: add example

- pages/linux/dysk.md
> dysk: add option placeholders and update more information link

- pages/linux/lshw.md
> lshw: add option placeholders

- pages/linux/dpkg-deb.md
- pages/linux/dpkg-query.md
> dpkg-{deb, query}: add option placeholders

- pages.de/common/arp.md
- pages.es/common/arp.md
- pages.fr/common/arp.md
- pages.id/common/arp.md
- pages.it/common/arp.md
- pages.ja/common/arp.md
- pages.ko/common/arp.md
- pages.pl/common/arp.md
- pages.pt_BR/common/arp.md
- pages.tr/common/arp.md
- pages.zh/common/arp.md
> arp: update more information link

- pages/common/pulumi-about.md
- pages/common/pulumi-cancel.md
- pages/common/pulumi-config.md
- pages/common/pulumi-destroy.md
- pages/common/pulumi-env.md
- pages/common/pulumi-new.md
- pages/common/pulumi-preview.md
- pages/common/pulumi-refresh.md
- pages/common/pulumi-stack.md
- pages/common/pulumi-state.md
- pages/common/pulumi-up.md
> pulumi*: add option placeholders
