pages/linux/rofi.md, pages/linux/wofi.md
=> rofi, wofi: refresh pages

pages.de/common/zsh.md, pages.es/common/zsh.md, pages.fr/common/zsh.md, pages.it/common/zsh.md, pages.ko/common/zsh.md, pages.pt_BR/common/zsh.md, pages.ru/common/zsh.md, pages.zh/common/zsh.md
=> zsh: update more information links

pages.es/common/autossh.md, pages.fr/common/autossh.md, pages.it/common/autossh.md, pages.ko/common/autossh.md, pages.pt_BR/common/autossh.md
=> autossh: update more information links

pages/common/ssh.md
=> ssh: add shorthand example

pages/common/ffuf.md
=> ffuf: use example.com

pages/common/ippevepcl.md, pages/common/ippeveps.md, pages/common/ngrok.md, pages/linux/exiqgrep.md
=> *: fix example websites

pages/linux/systemd-ac-power.md, pages/linux/systemd-cgls.md, pages/linux/systemd-cgtop.md, pages/linux/systemd-creds.md, pages/linux/systemd-delta.md, pages/linux/systemd-detect-virt.md, pages/linux/systemd-dissect.md, pages/linux/systemd-escape.md, pages/linux/systemd-firstboot.md, pages/linux/systemd-hwdb.md, pages/linux/systemd-id128.md, pages/linux/systemd-machine-id-setup.md, pages/linux/systemd-mount.md, pages/linux/systemd-notify.md, pages/linux/systemd-nspawn.md, pages/linux/systemd-repart.md, pages/linux/systemd-run.md, pages/linux/systemd-socket-activate.md, pages/linux/systemd-stdio-bridge.md
=> systemd*: add option placeholders and remove =

CONTRIBUTING.md
=> CONTRIBUTING: add a link to style-guide and clarify option usage

pages/common/olevba.md
=> olevba: fix more information text

pages/linux/toolbox-create.md, pages/linux/toolbox-enter.md, pages/linux/toolbox-list.md, pages/linux/toolbox-rm.md, pages/linux/toolbox-rmi.md, pages/linux/toolbox-run.md, pages/linux/toolbox.md
=> toolbox*: add option placeholders

pages/common/hub-ci-status.md, pages/common/hub-create.md, pages/common/hub-issue.md, pages/common/hub.md
=> hub*: add option placeholders

pages/linux/apt-add-repository.md, pages/linux/apt-file.md
=> apt-{add-repository, file}: add option placeholders

pages/common/glab-alias.md, pages/common/glab-auth.md, pages/common/glab-issue.md, pages/common/glab-mr-create.md, pages/common/glab-mr-merge.md, pages/common/glab-mr.md, pages/common/glab-pipeline.md, pages/common/glab-release.md, pages/common/glab-repo.md, pages/common/glab.md
=> glab*: refresh pages

pages/common/bzegrep.md, pages/common/bzfgrep.md, pages/common/bzgrep.md, pages/common/pdfgrep.md, pages/common/ptargrep.md, pages/common/ugrep.md, pages/common/vgrep.md, pages/common/xzgrep.md, pages/common/zegrep.md, pages/linux/btrfs-check.md, pages/linux/btrfs-device.md, pages/linux/btrfs-inspect-internal.md
=> *grep*, btrfs*: add option placeholders

pages/common/fossil-commit.md
=> fossil-commit: add option placeholders

pages/common/blahaj.md
=> blahaj: add page

pages/linux/gamescope.md
=> gamescope: add example explaining the steam syntax

pages/common/dbeaver.md
=> dbeaver: add page

pages/common/dockdiver.md
=> dockdiver: refresh page

pages.de/common/code.md, pages.es/common/code.md, pages.fr/common/code.md, pages.id/common/code.md, pages.it/common/code.md, pages.ko/common/code.md, pages.pt_BR/common/code.md, pages.zh/common/code.md, pages.zh_TW/common/code.md
=> code: update more information links

pages/linux/dmesg.md
=> dmesg: add mnemonic

pages/linux/lshw.md
=> lshw: refresh page

pages/linux/keyd.md
=> keyd: add page

pages/common/progress.md
=> progress: add explicit monitor example

pages/linux/chmem.md
- Version of the command being documented (if known): 2.40.4 
---
Adds a TLDR page for `chmem`, a utility for enabling or disabling memory blocks in Linux.
=> chmem: add page

pages/common/pulumi-down.md
=> pulumi-down: add page

pages/common/time.md, pages/common/times.md
=> time, times: refer to each other

pages/linux/blkid.md
=> blkid: add example

pages/linux/mkswap.md
=> mkswap: update page

pages.de/common/arping.md, pages.es/common/arping.md, pages.fr/common/arping.md, pages.id/common/arping.md, pages.it/common/arping.md, pages.ko/common/arping.md
=> arping: update more information links

pages.es/common/axel.md, pages.fr/common/axel.md, pages.it/common/axel.md, pages.ko/common/axel.md, pages.pt_BR/common/axel.md, pages.zh/common/axel.md
=> axel: update more information links

pages/linux/btrfs-filesystem.md
=> btrfs-filesystem: add swapfile example

pages/common/pulumi-update.md
=> pulumi-update: add alias page

pages/linux/efibootmgr.md
=> efibootmgr: edit boot order example

pages.ca/linux/acpi.md, pages.de/linux/acpi.md, pages.es/linux/acpi.md, pages.fr/linux/acpi.md, pages.id/linux/acpi.md, pages.it/linux/acpi.md, pages.ko/linux/acpi.md, pages.pl/linux/acpi.md, pages.pt_BR/linux/acpi.md, pages.zh/linux/acpi.md
=> acpi: update more information links

pages/common/biff.md
- **Version of the command being documented (if known):** v0.1.0
=> biff: add page

pages.bn/common/abduco.md, pages.fr/common/abduco.md, pages.id/common/abduco.md, pages.it/common/abduco.md, pages.ko/common/abduco.md, pages.no/common/abduco.md, pages.pt_BR/common/abduco.md, pages.ru/common/abduco.md, pages.zh/common/abduco.md
=> abduco: update more information links

pages.es/common/cowsay.md, pages.es/linux/xcowsay.md, pages.id/common/cowsay.md, pages.it/common/cowsay.md, pages.ko/common/cowsay.md, pages.ko/linux/xcowsay.md, pages.zh/linux/xcowsay.md
=> cowsay, xcowsay: update more information links

pages.es/common/git-lfs.md, pages.fr/common/git-lfs.md, pages.it/common/git-lfs.md, pages.ko/common/git-lfs.md, pages.tr/common/git-lfs.md
=> git-lfs: update more information links

pages.de/common/gh.md, pages.fr/common/gh.md, pages.id/common/gh.md, pages.ko/common/gh.md
=> gh: update more information links

pages.es/common/byobu.md
=> byobu: update Spanish translation

pages.es/common/declare.md
=> declare: update Spanish translation

pages.es/common/blahaj.md
=> blahaj: add Spanish translation

pages.es/common/kite.md
=> kite: add Spanish translation

pages.es/common/netexec.md
=> netexec: add Spanish translation

pages.es/common/pulumi-down.md
=> pulumi-down: add Spanish translation

pages.es/common/impacket-mqtt_check.md
=> impacket-mqtt_check: add Spanish translation

pages.es/common/impacket-ping.md
=> impacket-ping: add Spanish translation

pages.es/common/impacket-ping6.md
=> impacket-ping6: add Spanish translation

pages.es/common/impacket-rpcmap.md
=> impacket-rpcmap: add Spanish translation

pages.es/common/jco.md
=> jco: add Spanish translation

pages.es/common/kr.md
=> kr: add Spanish translation

pages/common/rustscan.md
- **Version of the command being documented (if known): 2.4.1**
=> rustscan: update page

pages/common/dunst.md
=> dunst: add page

pages/common/elasticsearch-reset-password.md
=> elasticsearch-reset-password: add page

pages.id/common/vue.md, pages.ko/common/vue.md, pages.pl/common/vue.md, pages.zh/common/vue.md
=> vue: update more information links

pages.fr/common/act.md, pages.id/common/act.md, pages.ko/common/act.md, pages.pt_BR/common/act.md, pages.ru/common/act.md, pages.zh/common/act.md
=> act: update more information links

pages.de/linux/ascii.md, pages.es/linux/ascii.md, pages.fr/linux/ascii.md, pages.ko/linux/ascii.md, pages.pt_BR/linux/ascii.md, pages.ta/linux/ascii.md, pages.zh/linux/ascii.md
=> ascii: update more information links

pages.id/common/git-create-branch.md, pages.ko/common/git-create-branch.md, pages.zh/common/git-create-branch.md, pages/common/git-create-branch.md
=> git-create-branch: update more information links

pages.it/common/mpv.md, pages.ko/common/mpv.md, pages.pt_BR/common/mpv.md, pages.zh/common/mpv.md
=> mpv: update more information links

pages.id/common/git-changelog.md, pages.ko/common/git-changelog.md, pages.zh/common/git-changelog.md
=> git-changelog: update more information links

pages/linux/fadvise.md, pages/linux/fincore.md
=> fincore, fadvise: refer to each other

pages/linux/steamos-factory-reset-config.md, pages/linux/steamos-factory-reset.md
=> steamos-{factory-reset, factory-reset-config}: add pages

pages.id/linux/exif.md, pages.ko/linux/exif.md
=> exif: update more information links

pages.de/common/sqlite3.md, pages.ko/common/sqlite3.md
=> sqlite3: update more information links

pages.ar/common/ulimit.md, pages.ko/common/ulimit.md, pages.zh/common/ulimit.md
=> ulimit: update more information links

pages.ca/linux/cpuid.md, pages.es/linux/cpuid.md, pages.hi/linux/cpuid.md, pages.ko/linux/cpuid.md, pages.pt_BR/linux/cpuid.md, pages.zh/linux/cpuid.md
=> cpuid: update more information links

pages.de/linux/arithmetic.md, pages.es/linux/arithmetic.md, pages.ko/linux/arithmetic.md, pages.zh/linux/arithmetic.md
=> arithmetic: update more information links

pages/linux/mkfs.fat.md
=> mkfs.fat: add fat type example

pages/linux/parted-interactive.md, pages/linux/parted.md
=> parted, parted-interactive: refresh pages

pages/linux/setarch.md
=> setarch: add page

pages/common/impacket-smbserver.md, pages/common/smbserver.py.md
=> smbserver.py, impacket-smbserver: add page

pages/common/impacket-smbclient.md, pages/common/smbclient.py.md
=> smbclient.py, impacket-smbclient: add page

pages/common/elasticsearch-syskeygen.md
=> elasticsearch-syskeygen: add page

pages.ja/common/mvn.md, pages.ko/common/mvn.md, pages.pt_BR/common/mvn.md, pages.zh/common/mvn.md
=> mvn: update more information links

pages/linux/gio.md
- **Version of the command being documented (if known):** 2.84.2
=> gio: add page

pages/common/nicotine.md
- **Version of the command being documented (if known):** 3.3.10
=> nicotine: add page

pages.nl/linux/pacman.md
=> pacman: add Dutch translation

pages.nl/common/gpg.md
=> gpg: add Dutch translation

pages.nl/common/xml-c14n.md, pages.nl/common/xml-canonic.md, pages.nl/common/xml-depyx.md, pages.nl/common/xml-p2x.md, pages.nl/common/xml-pyx.md, pages.nl/common/xml-xmln.md
=> xml-*: add Dutch translations

pages.nl/common/pulumi-destroy.md, pages.nl/common/pulumi-down.md, pages.nl/common/pulumi-up.md, pages.nl/common/pulumi-update.md
=> pulumi-{update,down,destroy,up}: add Dutch translation

pages/linux/systemctl.md
=> systemctl: add edit example

pages/common/wcurl.md
- **Version of the command being documented (if known):** `2025.05.26`
=> wcurl: add page

pages/osx/mac-cleanup.md
=> mac-cleanup: fix issues

pages.id/common/open.md, pages.ko/common/open.md, pages.nl/common/open.md, pages.pl/common/open.md
=> open: update outdated translations

pages.nl/common/md5sum.md
=> md5sum: update Dutch translation

pages.nl/common/git-cola.md
=> git-cola: update Dutch translation

pages.nl/linux/apt.md
=> apt: update Dutch translation

pages.nl/common/sha1sum.md, pages.nl/common/sha224sum.md, pages.nl/common/sha256sum.md, pages.nl/common/sha384sum.md, pages.nl/common/sha512sum.md
=> sha*sum: update Dutch translation

pages.nl/linux/updatedb.md
=> updatedb: update Dutch translation

pages.nl/linux/distrobox-create.md, pages.nl/linux/distrobox-enter.md, pages.nl/linux/distrobox-export.md, pages.nl/linux/distrobox-list.md, pages.nl/linux/distrobox-rm.md, pages.nl/linux/distrobox-stop.md, pages.nl/linux/distrobox-upgrade.md
=> distrobox*: update Dutch translation

pages.nl/common/pnmcolormap.md, pages.nl/common/pnmnorm.md, pages.nl/common/pnmquantall.md, pages.nl/common/pnmremap.md
=> pnm*: update Dutch translation

pages.nl/common/aircrack-ng.md
=> aircrack-ng: update Dutch translation

pages.nl/linux/yay.md, pages/linux/yay.md
=> yay: fix page and add Dutch translation

pages.nl/common/ugrep.md, pages.nl/common/unexpand.md
=> pages.nl/common/u*: update Dutch translation

pages/common/rlwrap.md
=> rlwrap: refresh page

pages/linux/gamescope.md
=> gamescope: add Steam example

pages.nl/common/shred.md, pages.nl/common/shuf.md, pages.nl/common/split.md, pages.nl/common/stat.md, pages.nl/common/stdbuf.md, pages.nl/common/strings.md
=> pages.nl/common/s*: update Dutch translation

pages.ko/common/jenv.md, pages.zh/common/jenv.md, pages/common/jenv.md
=> jenv: update link

pages.es/linux/arpspoof.md, pages.ko/linux/arpspoof.md
=> arpspoof: update more information links

pages.nl/common/latex.md, pages.nl/common/pdflatex.md, pages.nl/common/pdftex.md, pages.nl/common/tex.md
=> tex, latex, pdftex, pdflatex: add Dutch translation

pages.de/common/ansible-doc.md, pages.de/common/ansible-inventory.md, pages.de/common/ansible-playbook.md, pages.de/common/ansible-pull.md, pages.es/common/ansible-doc.md, pages.es/common/ansible-inventory.md, pages.es/common/ansible-pull.md, pages.fr/common/ansible-doc.md, pages.fr/common/ansible-inventory.md, pages.fr/common/ansible-playbook.md, pages.fr/common/ansible-pull.md, pages.id/common/ansible-doc.md, pages.id/common/ansible-inventory.md, pages.id/common/ansible-playbook.md, pages.id/common/ansible-pull.md, pages.it/common/ansible-playbook.md, pages.ko/common/ansible-doc.md, pages.ko/common/ansible-inventory.md, pages.ko/common/ansible-playbook.md, pages.ko/common/ansible-pull.md, pages.zh/common/ansible-playbook.md
=> ansible-*: update outdated translations

.github/CODEOWNERS
=> CODEOWNERS: add @sebastiaanspeck to contributing-guides, remove @cyqsimon from pages/linux

pages.nl/common/screen.md, pages.nl/common/tmux.md, pages.nl/common/zellij.md
=> screen, tmux, zellij: add Dutch translation

pages/linux/caligula.md
=> caligula: fix option placeholder

pages.nl/common/uv-add.md, pages.nl/common/uv-init.md, pages.nl/common/uv-python.md, pages.nl/common/uv-tool.md, pages.nl/common/uv-tree.md, pages.nl/common/uv.md
=> uv*: add Dutch translation

contributing-guides/translation-templates/common-descriptions.md
=> contributing-guides: add translations for common descriptions

pages.nl/common/magick.md
=> magick: fix typo in Dutch translation

pages.nl/common/sudo.md
=> sudo: add Dutch translation

pages.nl/common/pip.md, pages.nl/common/pip3.md
=> pip, pip3: add Dutch translation

pages.ar/common/xz.md, pages.es/common/xz.md, pages.ko/common/xz.md, pages.nl/common/xz.md, pages.pt_BR/common/xz.md, pages.zh/common/xz.md, pages/common/xz.md
=> xz: add Arabic translation and short options

README.md
=> README: deprioritize node.js client

pages/linux/kde-builder.md
=> kde-builder: indicate that multiple components are allowed

pages/common/loft.md
=> loft: add page

pages/common/vcluster.md
=> vcluster: add page

pages/common/devpod.md
=> devpod: add page

pages/common/sync.md
=> sync: add examples

pages/common/dog.md, pages/common/exa.md, pages/common/fabric.md, pages/common/fd.md, pages/common/fzf.md, pages/common/mosh.md, pages/common/mtr.md, pages/common/ranger.md, pages/common/shred.md
Inspired by this video: https://www.youtube.com/watch?v=6P-vjgPx9ww
=> dog, exa, fabric, fd, fzf, mosh, mtr, ranger, shred: add option placeholders and refresh more info link

pages/common/touch.md
=> touch: add string parsing example

pages.nl/common/sync.md
=> sync: update Dutch translation

pages.nl/linux/mktemp.md
=> mktemp: update Dutch translation

pages.ar/common/chisel.md, pages.ko/common/chisel.md, pages/common/chisel.md
=> chisel: add long options

pages/common/touch.md
=> touch: add missing quotation mark

pages/common/mitmdump.md
=> mitmdump: add example

pages.ar/common/tar.md
=> tar: clarify Arabic example

pages/common/env.md
=> env: add custom 0th argument example

pages.es/common/mosh.md
=> mosh: update Spanish translation

pages/common/xargs.md
=> xargs: add example

pages/linux/xdg-user-dir.md, pages/linux/xdg-user-dirs-update.md
=> xdg-user-dir: add page

pages/linux/reflector.md
=> reflector: add option placeholders

pages/linux/sed.md
=> sed: edit page and add example

pages/linux/ip.md
=> ip: clarify examples

pages/linux/aa-update-browser.md
- **Version of the command being documented (if known):** Unknown
✅ Added TLDR page for the following AppArmor command as part of [issue #11857](https://github.com/tldr-pages/tldr/issues/11857):
- `aa-update-browser`
=> aa-update-browser: add page

pages/common/bing-rewards.md
- **Version of the command being documented (if known):** 3.2.0
=> bing-rewards: add page

pages/common/zcat.md
=> zcat: edit page and add examples

pages/common/pv.md
- **Version of the command being documented (if known): 1.9.31**
=> pv: edit page and add example

pages/linux/crond.md
=> crond: add page

pages/common/bzip2.md
=> bzip2: adding variants to description

pages.fr/linux/ip.md, pages.it/linux/ip.md
=> ip: fix issues caused by find and replace

pages/linux/ip.md
=> ip: separate arguments

pages.nl/common/alias.md, pages.nl/common/env.md, pages.nl/common/test.md, pages.nl/common/touch.md, pages.nl/common/xargs.md, pages.nl/linux/sed.md, pages.nl/osx/caffeinate.md
=> pages.nl/*: fix translation Dutch issues

pages/common/uv-build.md, pages/common/uv-cache.md, pages/common/uv-export.md, pages/common/uv-publish.md, pages/common/uv-self.md
- **Version of the command being documented (if known):** 0.7.13
=> uv-{build,cache,export,publish,self}: add pages

pages.nl/common/mplayer.md, pages.nl/common/mpv.md, pages.nl/common/vlc.md
=> mpv, mplayer, vlc: add Dutch translation

contributing-guides/translation-templates/common-arguments.md, contributing-guides/translation-templates/more-info-link.md, contributing-guides/translation-templates/subcommand-mention.md
=> translation templates: fix Finnish translations

pages/linux/gamescope.md
=> gamescope: add display selection example

pages/common/mp3info.md, pages/common/zdb.md, pages/common/zegrep.md, pages/linux/sfill.md
=> mp3info, zbd, sfill: add mnemonic hints and option placeholders

pages/linux/ip-address.md, pages/linux/ip-link.md, pages/linux/ip-maddress.md, pages/linux/ip-neighbour.md, pages/linux/ip-route-add.md, pages/linux/ip-route-get.md, pages/linux/ip-route-list.md, pages/linux/ip-route.md, pages/linux/ip.md
=> ip*: unify network interface notation

contributing-guides/style-guide.md
With this order the hint makes more sense in the context.
=> style-guide: reorganize mnemonic guide

pages/linux/ldd.md
=> ldd: add option placeholders

pages.nl/common/$.md
=> $: update Dutch translation

pages/common/nano.md
=> nano: adding pico and rnano in see also section

pages/common/qemu-system-riscv64.md
=> qemu-system-riscv64: add page

pages/linux/pw-cli.md
=> pw-cli: refresh page

pages/common/pwqgen.md
=> pwqgen: add page

pages/common/hexedit.md
=> hexedit: add page

pages/common/poetry.md
=> poetry: update example for newer version

pages/common/crystal.md, pages/common/gh-issue-create.md, pages/common/glab-alias.md, pages/common/meson.md, pages/common/pixi.md, pages/common/ts-node.md, pages/common/upx.md, pages/linux/proctl.md, pages/linux/setxkbmap.md
=> *: replace non-standard help page descriptions

pages/linux/pihole.md
- **Version of the command being documented (if known):** v6+
=> pihole: refresh page

pages/common/nano.md, pages/common/rnano.md
https://manned.org/nano
> -R, --restricted
Restricted mode: don't read or write to any file not specified on the command line.  This means: don't read or write history files; don't allow suspending; don't allow spell checking; don't  al‐
low  a  file to be appended to, prepended to, or saved under a different name if it already has one; and don't make backup files.  _**Restricted mode can also be activated by invoking nano with any
name beginning with 'r' (e.g. "rnano").**_
=> nano: update page; rnano: convert to alias

pages.es/common/b2sum.md
=> b2sum: add Spanish translation

pages/common/pulumi-org.md
=> pulumi-org: add page

pages/linux/coredumpctl.md, pages/linux/resolvectl.md, pages/linux/udevadm.md
=> systemd tools: add option placeholders

pages/linux/e2freefrag.md, pages/linux/e2fsck.md, pages/linux/e2image.md, pages/linux/e2undo.md, pages/linux/eclean.md, pages/linux/euse.md, pages/linux/exiqgrep.md, pages/linux/expect.md, pages/linux/export.md, pages/linux/extrace.md
=> linux/e*: add option placeholders and mnemonics

pages/linux/vlock.md
=> vlock: add page

pages.es/common/gvim.md
=> gvim: add Spanish translation

pages/common/hugo-server.md, pages/common/hugo.md
=> hugo, hugo-server: update commands with short and long options

pages/common/gst-launch-1.0.md
=> gst-launch-1.0: add debugging example

pages/common/go-bug.md, pages/common/go-build.md, pages/common/go-clean.md, pages/common/go-doc.md, pages/common/go-env.md, pages/common/go-fix.md, pages/common/go-generate.md, pages/common/go-list.md, pages/common/go-mod.md, pages/common/go-version.md, pages/common/go.md, pages/common/gofmt.md, pages/common/goimports.md
=> go*: update documentation links

pages/linux/haveged.md
=> haveged: add page

pages/common/ndc.md
=> ndc: add page

pages/linux/xhost.md
=> xhost: remove long hyphen

pages/linux/daemon.md, pages/linux/dbus-daemon.md, pages/linux/debchange.md, pages/linux/debman.md, pages/linux/deborphan.md, pages/linux/debtap.md, pages/linux/dnf-config-manager.md, pages/linux/do-release-upgrade.md, pages/linux/dolphin.md, pages/linux/dracut.md
=> linux/d*: add option placeholders, mnemonics and refresh more info links

pages/linux/away.md
=> away: add page

pages.es/common/fabric.md
=> fabric: update Spanish translation

pages.es/common/alias.md
=> alias: update Spanish translation

pages.es/common/basenc.md
=> basenc: add Spanish translation

pages.es/common/bzcat.md
=> bzcat: add Spanish translation

pages.es/common/komac.md
=> komac: add Spanish translation

pages.es/common/ftp.md
=> ftp: add Spanish translation

pages.es/common/aircrack-ng.md
=> aircrack-ng: update Spanish translation

pages.es/common/dircolors.md
=> dircolors: add Spanish translation

pages.zh/common/asciinema.md
=> asciinema: update Chinese translation

MAINTAINERS.md
=> MAINTAINERS: add @Managor as code owner

pages/common/boxxy.md
=> boxxy: add page

pages/common/gst-discoverer-1.0.md
=> gst-discoverer-1.0: add page

pages/linux/gio.md
=> gio: use manned 

pages.nl/common/grep.md, pages.nl/common/nano.md
=> pages.nl/common/*: update Dutch translation

pages/common/gst-inspect-1.0.md
=> gst-inspect-1.0: add examples

pages/common/magick-convert.md
=> magick-convert: add "no background" to append example

pages.it/common/binwalk.md, pages.ko/common/binwalk.md, pages.pt_BR/common/binwalk.md, pages.zh/common/binwalk.md, pages/common/binwalk.md
=> binwalk: add short options

pages/linux/lsdev.md
=> lsdev: add page

pages.nl/common/stow.md
=> stow: add Dutch translation

contributing-guides/style-guide.md
=> style-guide: link to IANA

pages/common/tzconfig.md
=> tzconfig: add page

pages/common/tcpdump.md
=> tcpdump: add mnemonics and sudo

pages/linux/dex.md
=> dex: fix typo

contributing-guides/style-guide.md
=> style-guide: give instructions on sudo usage

pages/linux/fwupdmgr.md
=> fwupdmgr: add update history example

pages.es/common/nano.md, pages.fr/common/nano.md, pages.ko/common/nano.md, pages.pt_BR/common/nano.md, pages.zh/common/nano.md
=> nano: update more information links

pages.de/common/gobuster.md, pages.ko/common/gobuster.md
=> gobuster: update outdated translations

pages/common/zellij.md
=> zellij: add option placeholders

pages/common/gron.md
=> gron: add page

pages/common/gdm-binary.md
=> gdm-binary: add page

pages/common/pkcs11-tool.md
- **Version of the command being documented (if known):** OpenSC 0.26.1-1
=> pkcs11-tool: add page

pages/common/steamcmd.md
=> steamcmd: add example on how to delete credential cache

pages/common/jj-bookmark.md, pages/common/jj-status.md, pages/common/jj.md
=> jj, jj-status, jj-bookmark: add option placeholder for aliases

pages/linux/dnf-config-manager.md, pages/linux/dnf-group.md
=> dnf-{group, config-manager}: edit more info link and add option placeholders

pages/common/gdmsetup.md
=> gdmsetup: add page

pages/common/nix-channel.md
=> nix-channel: add page

pages/common/xlsclients.md
=> xlsclients: add missing placeholders

pages/common/jj-abandon.md, pages/common/jj-revert.md, pages/common/jj-show.md, pages/common/jj-simplify-parents.md
- **Version of the command being documented (if known):** v0.30.0
#17040
=> jj-{abandon, revert, show, simplify-parents}: add pages

pages/linux/expac.md
=> expac: add missing hyphens

pages/common/nagios.md, pages/common/nagios2.md, pages/common/nagios3.md, pages/common/nagios4.md
=> nagios, nagios2, nagios3, nagios4: add pages

pages/common/scrcpy.md
- **Version of the command being documented (if known):** 3.3.1
=> scrcpy: update examples

pages/linux/dnf-module.md
=> dnf-module: add page

pages.id/common/subl.md, pages.ko/common/subl.md
=> subl: update outdated translations

pages.ca/linux/add-apt-repository.md, pages.de/linux/add-apt-repository.md, pages.es/linux/add-apt-repository.md, pages.id/linux/add-apt-repository.md, pages.it/linux/add-apt-repository.md, pages.ko/linux/add-apt-repository.md, pages.pt_BR/linux/add-apt-repository.md, pages.zh/linux/add-apt-repository.md
=> add-apt-repository: update outdated translations

CONTRIBUTING.md
This gives a bit more flexibility.
=> CONTRIBUTING: reword name collission instructions

pages/common/filen.md
- **Version of the command being documented (if known): v0.0.33**
=> filen: add page

pages.nl/common/gdm.md
=> gdm: add Dutch translation

pages/common/sccache.md
- **Version of the command being documented (if known):** 0.10.0
=> sccache: add page

pages/common/jj-git-clone.md, pages/common/jj-git-fetch.md, pages/common/jj-git-init.md, pages/common/jj-git-push.md, pages/common/jj-git-remote.md
- **Version of the command being documented (if known):** v0.30.0
#17040
=> jj-git-*: add pages

pages/linux/dnf-changelog.md
=> dnf changelog: add page

pages/common/ocrmypdf.md
- Merge two similar examples
- Add lossy optimization example
- Unify path examples
- Fix grammar
- **Version of the command being documented (if known):** `16.10.2`
=> ocrmypdf: replace semi-duplicate with optimization

pages/linux/dnf-builddep.md
=> dnf builddep: add page

pages/linux/dnf-config-manager.md
=> dnf-config-manager: add remarks over `dnf`

pages/linux/i2cdetect.md, pages/linux/i2cdump.md, pages/linux/i2cget.md, pages/linux/i2cset.md
=> i2c-tools: add page

pages/common/mailsy.md
=> mailsy: add page

pages.es/linux/dnf-config-manager.md
=> dnf-config-manager: update Spanish translation

pages.cs/common/cp.md, pages.cs/common/mkdir.md, pages.cs/common/mv.md, pages.cs/common/rm.md, pages.cs/common/rmdir.md
=> cp, mv, rm, rmdir, mkdir: add Czech translation

pages.cs/common/ls.md
=> ls: update Czech translation

pages/common/rsql.md
- **Version of the command being documented (if known): 0.19.0**
=> rsql: add page

pages.pl/common/!.md
=> !: update Polish translation

pages/common/dtc.md
=> dtc: add more examples

pages.nl/common/ollama.md, pages/common/ollama.md
=> ollama: add Dutch translation

pages/common/helm-install.md
=> helm-install: add option placeholders

pages.zh_TW/common/docker.md
=> docker: update Chinese translation

pages.es/common/btop.md, pages.fr/common/btop.md, pages.ko/common/btop.md, pages.zh/common/btop.md, pages/common/btop.md
=> btop: add option placeholders

pages/common/flutter.md
=> flutter: add an example

pages/common/ncspot.md
=> ncspot: add page

pages/common/zed.md, pages/common/zeditor.md
=> zed: add page

pages.de/common/deno.md, pages.es/common/deno.md, pages.fa/common/deno.md, pages.fr/common/deno.md, pages.id/common/deno.md, pages.ko/common/deno.md, pages.zh/common/deno.md
=> deno: update more information links

pages/common/audit2why.md
=> audit2why: add page

pages.ko/common/gpg-tui.md
I forgot about translations in #17225
=> ko/gpg-tui: correct the description

pages/common/mpicxx.md
- **Version of the command being documented (if known):** 5.0.8
=> mpicxx: add page

pages/common/chainctl.md
Add handy tldr entry for Chainguard's CLI tool
=> chainctl: add page

pages.nl/common/tldr.md
=> tldr: add Dutch translation

pages/linux/hwinfo.md
- **Version of the command being documented (if known):** 24.0
=> hwinfo: refresh page

pages/common/openocd.md
=> openocd: add page

contributing-guides/style-guide.md
=> style-guide: instruct to avoid nested placeholders

pages/linux/links.md
=> links: fix missing angle brackets

pages/common/rabbitmqctl-cluster.md, pages/common/rabbitmqctl-users.md, pages/common/rabbitmqctl-vhosts.md
- **Version of the command being documented (if known):** 3.12.14
=> rabbitmqctl-{cluster,users,vhosts}: add page

pages/common/rabbitmqctl.md
- **Version of the command being documented (if known):** 3.12.14
=> rabbitmqctl: add page

pages/common/hexdump.md, pages/common/hexyl.md, pages/common/od.md, pages/common/xxd.md, pages/linux/hexdump.md
=> hexyl, od, xxd, hexdump: add see also information

pages/linux/zypper.md
I have not tested these. I only went by what I found in the documentation.
=> zypper: add aliases

pages/linux/nmcli-agent.md, pages/linux/nmcli-connection.md, pages/linux/nmcli-device.md, pages/linux/nmcli-general.md, pages/linux/nmcli-monitor.md, pages/linux/nmcli-networking.md, pages/linux/nmcli-radio.md, pages/linux/nmcli.md
=> nmcli*: refresh pages

pages.nl/common/source.md
=> source: fix typo in Dutch translation

pages.nl/linux/counter-strike-2.md
=> counter-strike-2: capitalize Dutch title

pages/common/kerl.md
- **Version of the command being documented (if known):** 4.4.0
=> kerl: add page

pages/common/objdump.md
=> objdump: add -t | --syms example

pages.ko/common/cargo-uninstall.md, pages.zh/common/cargo-uninstall.md, pages/common/cargo-uninstall.md
@acuteenvy Not sure if this is intentional
=> cargo-uninstall: fix command

pages/common/function.md
=> function: add short example

pages/linux/qm-disk-import.md
=> qm-disk-import: fix typo

pages/common/cargo-rustc.md
=> cargo-rustc: fix typo

pages/common/mid3v2.md
=> mid3v2: fix typo

pages/linux/mke2fs.md
=> mke2fs: fix examples

pages/common/pamditherbw.md
=> pamditherbw: fix typo

pages/common/immich.md
=> immich-cli: rename to immich

pages/common/cargo-bench.md, pages/common/cargo-fix.md, pages/common/django-admin.md, pages/common/docker-commit.md, pages/common/doctl-databases-sql-mode.md, pages/common/git-mktree.md, pages/common/git-replace.md, pages/common/home-manager.md, pages/common/ipcs.md, pages/common/npm-audit.md, pages/common/secretsdump.py.md, pages/common/zgrep.md, pages/linux/wireplumber.md
=> *: unify apostrophes

pages/common/brew-autoremove.md, pages/common/brew-install.md, pages/common/brew-upgrade.md
=> brew-{autoremove, install, upgrade}: add short options

pages/common/dmypy.md
- **Version of the command being documented (if known):** 1.15.0
=> dmypy: add page

pages.es/common/impacket-psexec.md
=> impacket-psexec: update Spanish translation

pages.es/common/zeditor.md
=> zeditor: add Spanish translation

pages.es/common/mpicxx.md
=> mpicxx: add Spanish translation

pages.es/linux/terraria.md
=> Terraria: update Spanish translation

pages.cs/common/7z.md, pages.cs/common/gzip.md, pages.cs/common/tar.md, pages.cs/common/unzip.md, pages.cs/common/zip.md
=> zip, unzip, 7z, gzip, tar: add Czech translation

pages/common/tar.md
=> tar: remove `=` and add short options

CONTRIBUTING.md
=> CONTRIBUTING: update name collision link

pages/linux/pct.md
=> pct: add aliases

pages/common/fastfetch.md
=> fastfetch: be explicit on what the structure looks like

pages/linux/nmcli.md, pages/linux/nmtui.md
=> nmtui, nmcli: refer to each other

pages/linux/nmcli-device.md
=> nmcli-device: add example

pages/linux/hddtemp.md
=> hddtemp: add page

pages.nl/linux/systemctl-disable.md, pages.nl/linux/systemctl-enable.md, pages.nl/linux/systemctl-reboot.md, pages.nl/linux/systemctl.md
=> systemctl*: add Dutch translation

pages.de/common/fish.md, pages.fr/common/fish.md, pages.ko/common/fish.md, pages.nl/common/fish.md, pages.zh/common/fish.md
=> fish: refresh translation pages

pages/common/qwen.md
- **Version of the command being documented (if known):** 0.0.1-alpha.10
=> qwen: add page

pages.nl/common/git-switch.md, pages.nl/common/objdump.md, pages.nl/common/tar.md, pages.nl/linux/nmcli-device.md, pages.nl/linux/pacman-upgrade.md, pages.nl/linux/qm-disk-import.md, pages.nl/linux/qm-disk-move.md, pages.nl/linux/qm-disk-resize.md, pages.nl/linux/systemd-mount.md
=> pages.nl/*: update Dutch translations

pages.nl/linux/cmus.md, pages/linux/cmus.md
- **Version of the command being documented (if known):** cmus v2.12.0
=> cmus: update page and add Dutch translation

pages/common/papermc.md
=> papermc: add page

pages/common/elasticsearch-croneval.md
Addresses a part of the Issue #16522
=> elasticsearch-croneval: add page

pages.es/common/kerl.md
=> kerl: add Spanish translation

pages.es/common/rabbitmqctl.md
=> rabbitmqctl: add Spanish translation

pages.es/common/sha1sum.md
=> sha1sum: add Spanish translation

pages.es/common/gdm-binary.md
=> gdm-binary: add Spanish translation

pages.es/osx/mas.md
=> mas: update Spanish translation

pages.es/linux/dnf-group.md
=> dnf-group: update Spanish translation

pages.es/linux/factorio.md, pages.ko/linux/factorio.md
=> factorio: update Korean and Spanish title

pages.nl/common/mc.cli.md, pages.nl/common/mcli.md, pages.nl/common/minio-client.md
=> mc.cli, mcli, minio-client: add Dutch translation

pages.ko/common/lychee.md, pages/common/lychee.md
=> lychee: fix broken links

pages/linux/nordvpn.md
=> nordvpn: add aliases

pages.ko/common/pdftocairo.md, pages/common/pdftocairo.md
=> pdftocairo: fix broken links

pages/linux/fdisk.md
- **Version of the command being documented (if known):** 2.41.1
I'm not sure if mnemonics are supported for keybindings, but I added them anyways. If they aren't supported, I'll remove them.
=> fdisk: update page

pages/linux/gpu-screen-recorder.md
~~I wasn't able to get the replay buffer to work so this starting point page will have to do.~~
=> gpu-screen-recorder: add page

pages.es/osx/whence.md, pages.ko/osx/whence.md, pages/osx/whence.md
=> whence: fix broken links

pages.de/linux/numlockx.md, pages.ko/linux/numlockx.md, pages/linux/numlockx.md
=> numlockx: fix broken links

pages.es/common/jbang.md, pages.ko/common/jbang.md, pages.zh/common/jbang.md, pages/common/jbang.md
=> jbang: fix broken links

pages.ko/linux/f5fpc.md, pages/linux/f5fpc.md
=> f5fpc: fix broken links

pages/common/chainctl.md
=> chainctl: fix broken links

pages/linux/partclone.md
=> partclone: add page

contributing-guides/translation-templates/common-arguments.md
=> common-arguments: update Russian placeholders

pages/common/elasticsearch-create-enrollment-token.md
Addresses a part of the Issue #16522
=> elasticsearch-create-enrollment-token: add page

pages/linux/bootctl.md
=> bootctl: simplify command

pages/common/syncthing.md
=> syncthing: refresh page

pages/linux/yaourt.md
I wasn't able to find a better link
=> yaourt: update more info link

pages/common/vhs.md
- **Version of the command being documented (if known):** v0.10.0 (517bcda)
=> vhs: update page

pages/linux/qm.md
=> qm: match options with manual page

pages.es/common/npm-owner.md
=> npm-owner: updated Spanish translation

pages.es/common/npm-ls.md
=> npm-ls: updated Spanish translation

pages/linux/findmnt.md
=> findmnt: expand to multiple types

pages/linux/pacman-key.md
=> pacman-key: simplify command

pages/linux/pct-resize.md
=> pct-resize: add page

pages/linux/qm-agent.md, pages/linux/qm-disk-rescan.md, pages/linux/qm-rescan.md, pages/linux/qm-unlink.md
=> qm*: add missing alias pages

pages/linux/qm-guest.md
=> qm-guest: add page

pages/linux/qm-import-disk.md, pages/linux/qm-importdisk.md, pages/linux/qm-move-disk.md
=> qm-{import-disk, move-disk}: fix incorrect aliases

pages/linux/pvesm.md
=> pvesm: add page

pages/common/devenv.md, pages/common/gt.md
=> devenv, gt: conform with style guide and fix typo

pages/linux/pveum.md
=> pveum: add page

pages/linux/pct-status.md
=> pct-status: add page

pages.de/common/kubectl-delete.md, pages.de/common/kubectl-describe.md, pages.ko/common/kubectl-delete.md, pages.ko/common/kubectl-describe.md
=> kubectl-delete, kubectl-describe: refresh pages

pages/linux/update-initramfs.md
=> update-initramfs: add page

pages.es/osx/shuf.md, pages.id/osx/shuf.md, pages.ko/osx/shuf.md, pages.nl/osx/shuf.md, pages.zh/osx/shuf.md, pages/osx/shuf.md
=> shuf: fix broken links

pages/linux/pct-set.md
=> pct-set: add page

pages/common/elasticsearch-node.md
Addresses a part of the Issue #16522 
=> elasticsearch-node: add page

pages/linux/lspci.md
=> lspci: add device ID example

pages.es/osx/emond.md, pages.ko/osx/emond.md, pages.pt_BR/osx/emond.md, pages/osx/emond.md
=> emond: fix broken links

pages.es/osx/wps.md, pages.ko/osx/wps.md, pages/osx/wps.md
=> wps: fix broken links

pages.es/osx/bnepd.md, pages.ko/osx/bnepd.md, pages.pt_BR/osx/bnepd.md, pages/osx/bnepd.md
=> bnepd: fix broken links

pages.es/osx/wwand.md, pages.ko/osx/wwand.md, pages/osx/wwand.md
=> wwand: fix broken links

pages/common/kodi-send.md
=> kodi-send: add page

pages/linux/pct-exec.md
=> pct-exec: add page

pages/linux/bindfs.md
=> bindfs: add page

pages.ko/linux/terraria.md
=> terraria: update Korean translation

contributing-guides/style-guide.md
=> style-guide: add instructions to shorten the link

pages.pt_BR/common/crontab.md, pages.pt_BR/common/head.md, pages.pt_BR/common/nmap.md, pages.pt_BR/common/pass.md, pages.pt_BR/common/pwd.md
=> pass, pwd, nmap: add pt_BR translation

pages/linux/lxc-top.md
=> lxc-top: add page

pages/linux/repo-add.md, pages/linux/repo-remove.md
=> repo-add: fix incorrect description, add manual addition and a see also section

pages/common/sr.md, pages/common/surfraw.md
=> surfraw: refresh page, sr: add alias page

pages/common/rmdir.md
=> rmdir: add cleanup example

pages/linux/qm-create.md
=> qm-create: simplify example and add install media

pages.ko/common/hg-add.md, pages.ko/common/hg-branch.md, pages.ko/common/hg-clone.md, pages.ko/common/hg-commit.md, pages.ko/common/hg-init.md, pages.ko/common/hg-log.md, pages.ko/common/hg-pull.md, pages.ko/common/hg-push.md, pages.ko/common/hg-remove.md, pages.ko/common/hg-root.md, pages.ko/common/hg-serve.md, pages.ko/common/hg-status.md, pages.ko/common/hg-update.md, pages.ko/common/hg.md, pages/common/hg-add.md, pages/common/hg-branch.md, pages/common/hg-clone.md, pages/common/hg-commit.md, pages/common/hg-init.md, pages/common/hg-log.md, pages/common/hg-pull.md, pages/common/hg-push.md, pages/common/hg-remove.md, pages/common/hg-root.md, pages/common/hg-serve.md, pages/common/hg-status.md, pages/common/hg-update.md, pages/common/hg.md
hg, -add, -log, -init, -pull, -push, -root, -clone, -serve, -branch, -commit, -remove, -status, -update
=> hg*: fixing broken links

pages.nl/common/audit2allow.md, pages.nl/common/audit2why.md
=> audit2{allow,why}: add Dutch translation

pages/common/python.md
I wasn't able to find the official documentation for these options.
=> python: update more info link

pages/common/kubectl-create.md, pages/common/kubectl-delete.md, pages/common/kubectl-describe.md, pages/common/kubectl-taint.md
=> kubectl-{describe, delete, create, taint}: add option placeholders

pages/common/monolith.md
Closes https://github.com/tldr-pages/tldr/issues/17633.
=> monolith: add page

pages/cisco-ios/crypto.md
=> crypto: add page

pages.es/common/zbarimg.md
=> zbarimg: update Spanish translation

pages/linux/modprobe.md
=> modprobe: add short options

pages/common/flake8.md
=> flake8: fix link

pages/linux/pct-destroy.md
=> pct-destroy: add page

pages/common/mpijavac.md
- **Version of the command being documented (if known): Open MPI 5.0.x**
=> mpijavac: add page

pages/cisco-ios/delete.md
=> delete: add page

pages/cisco-ios/configure.md
=> configure: add page

pages/linux/pvesm.md
=> pvesm: add storage set and file remove example

pages/linux/systemctl.md
=> systemctl: edit page

pages/common/alr.md, pages/common/bird.md, pages/common/birdc.md, pages/common/browsh.md, pages/common/crontab.md, pages/common/devcontainer.md, pages/common/gnuplot.md, pages/common/go.md, pages/common/helm.md, pages/common/htop.md, pages/common/multipass.md, pages/common/nxc-vnc.md, pages/common/railway.md, pages/common/rtmpdump.md, pages/common/testssl.md, pages/common/trip.md
=> *: use a more specific more info link

pages/cisco-ios/username.md
=> username: add page

pages/linux/modetest.md
=> modetest: add page

pages/linux/chvt.md
=> chvt: add page

pages/common/kubectl-apply.md
=> kubectl-apply: refresh page

pages.es/linux/nmcli-device.md
=> nmcli-device: updated Spanish translation

pages.es/linux/nmcli-monitor.md
=> nmcli-monitor: updated Spanish translation

pages.es/linux/nmcli-radio.md
=> nmcli-radio: updated Spanish translation

pages/common/babel.md, pages/common/bower.md, pages/common/codecrafters.md, pages/common/conan.md, pages/common/ctags.md, pages/common/esbuild.md, pages/common/hexo.md, pages/common/hugo.md, pages/common/packer.md, pages/common/prettier.md, pages/common/streamlit.md, pages/common/todoman.md, pages/common/tqdm.md, pages/common/typeorm.md, pages/linux/abrt-cli.md, pages/linux/pivpn.md
=> *: use a more specific more info link, io domain

pages/linux/cage.md
=> cage: add examples

pages/common/declare.md
=> declare: add example

pages.es/linux/cmus.md
=> cmus: update Spanish translation

pages.ko/common/conan-frogarian.md, pages/common/conan-frogarian.md
This was an easter egg that has been removed
=> conan-frogarian: delete page

pages/linux/qm.md
=> qm: use scsi instead of ide

pages/common/{.md
=> {: add placeholders

pages/common/kubectl-edit.md
=> kubectl-edit: refresh page

pages.es/common/sudoedit.md
=> sudoedit: add Spanish translation

pages/cisco-ios/show.md
=> show: add page

pages/linux/fbset.md
=> fbset: add page

pages/linux/umount.md
=> umount: add sudo

pages/common/kubectl-label.md
=> kubectl-label: add option placeholders

pages/common/tig.md
=> tig: add blame example

pages/common/argos-translate.md, pages/common/flake8.md, pages/common/heroku.md, pages/common/linkchecker.md, pages/common/monodevelop.md, pages/common/pinta.md, pages/common/serverless.md, pages/common/tcpreplay.md, pages/linux/etckeeper.md, pages/linux/links.md, pages/linux/links2.md, pages/osx/cot.md
=> *: use a more specific more info link, com domain

pages/common/complete.md
=> complete: simplify builtin option

pages/common/kubectl-config.md
=> kubectl-config: add default namespace switching example

pages/linux/pct-config.md
=> pct-config: add page

pages/cisco-ios/clock.md
=> clock: add page

pages/cisco-ios/write.md
I wasn't able to find a good more info link that documents all possibilities
=> write: add page

pages/linux/qm-snapshot.md
=> qm-snapshot: specify name format and add related commands examples

pages.de/common/git-am.md, pages.es/common/git-am.md, pages.id/common/git-am.md, pages.ko/common/git-am.md, pages.pl/common/git-am.md, pages.ta/common/git-am.md
=> git-am: refresh pages

MAINTAINERS.md
I added myself in list of Maintainers, Addresses Issue #17708 
=> MAINTAINERS: add @TheRootDaemon as a collaborator

pages/linux/scanimage.md
=> scanimage: add examples

pages.pl/linux/links2.md, pages/linux/links.md, pages/linux/links2.md
=> links, links2: update with added differentiation

pages.es/common/qownnotes.md
=> qownnotes: updated Spanish translation

pages.es/common/git-grep.md
=> git-grep: update Spanish translation

pages/common/sftp.md
=> sftp: fix filepaths

pages/linux/fbi.md
=> fbi: add page

pages/common/plink.md
=> plink: add page

pages.es/common/sr.md
=> sr: add Spanish translation

pages/linux/systemctl-start.md, pages/linux/systemctl-stop.md
- **Version of the command being documented (if known):** systemd 257 (257.8-2-arch)
#17684
=> systemctl-{start,stop}: add pages

pages/common/okular.md
- **Version of the command being documented (if known):** 25.08.0
=> okular: add short option

pages/linux/lvresize.md
=> lvresize: add short options

pages/common/conda-doctor.md
Addition to #17762
The verbose argument can take `-v` or `--verbose` repeated up to four times to get default (`-v`), INFO, DEBUG, or TRACE (`-vvvv`) logging levels respectively. Wasn't sure how to format this info - please lmk of any suggestions!
=> conda-doctor: add page

MAINTAINERS.md
#17772 Added myself as Collaborator.
=> MAINTAINERS: add @SpikeTheDragon40k as a collaborator (#17772)

pages/common/jj.md
Also fixes some existing commands to comply with style guide (long arguments, concise)
- **Version of the command being documented (if known):** 0.32
=> jj: add edit, undo

pages.fr/common/docker-load.md, pages.ko/common/docker-load.md, pages.pt_BR/common/docker-load.md
=> docker-load: refresh pages

pages/linux/pvcreate.md, pages/linux/pvremove.md, pages/linux/vgchange.md, pages/linux/vgremove.md
=> pvcreate, pvremove, vgchange, vgremove: add short options

pages/linux/fgconsole.md
=> fgconsole: add page

pages/linux/qm-set.md
=> qm-set: add gpu passthrough example and extend delete example

pages/common/wait.md
=> wait: add hint towards waitpid

pages/linux/systemd-sysusers.md
=> systemd-sysusers: add simple example

pages.nl/common/alias.md, pages.nl/common/cd.md, pages.nl/common/fc.md, pages.nl/common/gcal.md, pages.nl/common/gcc.md, pages.nl/common/sleep.md, pages.nl/common/source.md, pages.nl/common/tar.md, pages.nl/common/unalias.md, pages.nl/common/units.md, pages.nl/common/xargs.md
=> pages.nl/*: update Dutch more info links

pages.es/common/alr.md
=> alr: updated Spanish translation

pages.nl/common/git-init.md, pages/common/git-init.md
=> git-init: update page and add Dutch translation

pages.es/linux/dnf-deplist.md
Add documentation for dnf deplist command.
=> dnf-deplist: add Spanish translation

pages/linux/vgcfgbackup.md
=> vgcfgbackup: add page

pages.es/common/ctags.md
Updated the link for more information about Espanso.
x
=> ctags: updated Spanish translation

pages.es/common/libreoffice.md
=> LibreOffice: updated Spanish translation

pages/linux/inputattach.md
=> inputattach: add page

pages/common/dust.md
- **Version of the command being documented (if known):** 1.2.3
=> dust: update page

pages/linux/cec-client.md
=> cec-client: add page

pages/linux/dpkg-reconfigure.md
=> dpkg-reconfigure: add example

pages/linux/fbset.md
=> fbset: add missing option

pages.es/common/complete.md
=> complete: updated Spanish translation

pages.es/common/browsh.md
=> browsh: updated Spanish translation

pages/linux/dnf-download.md
=> dnf-download: add page

pages/linux/cec-ctl.md
=> cec-ctl: add page

pages/common/mullvad.md
- **Version of the command being documented (if known):** 2025.8
=> mullvad: add server selection examples

pages.nl/common/git-log.md
=> git-log: add Dutch translation

pages.nl/common/git-merge.md
=> git-merge: add Dutch translation

pages.nl/common/git-pull.md
=> git-pull: add Dutch translation

pages.nl/common/git-reflog.md
=> git-reflog: add Dutch translation

pages.cs/common/cat.md, pages.cs/common/less.md, pages.cs/common/more.md
=> cat, more, less: add Czech translation

pages/linux/mkinitcpio.md
=> mkinitcpio: fix placeholders

pages/common/i3-nagbar.md
=> i3-nagbar: add page

pages.es/common/pulumi-env.md, pages.es/common/pulumi-refresh.md, pages.ko/common/pulumi-about.md, pages.ko/common/pulumi-destroy.md, pages.ko/common/pulumi-stack.md, pages.ko/common/pulumi-up.md
=> pulumi-*: refresh pages

pages.it/common/docker-images.md, pages.pl/common/docker-images.md, pages.pt_BR/common/docker-images.md, pages.tr/common/docker-images.md
=> docker-images: refresh pages

pages.ko/common/b2.md
=> b2: fix Korean title

pages.bn/linux/apt.md, pages.ca/linux/apt.md, pages.de/linux/apt.md, pages.es/linux/apt.md, pages.fr/linux/apt.md, pages.hi/linux/apt.md, pages.id/linux/apt.md, pages.it/linux/apt.md, pages.ja/linux/apt.md, pages.ko/linux/apt.md, pages.ml/linux/apt.md, pages.pl/linux/apt.md, pages.pt_BR/linux/apt.md, pages.ta/linux/apt.md, pages.tr/linux/apt.md, pages.uk/linux/apt.md, pages.zh/linux/apt.md
=> apt: refresh pages

pages/common/ruby.md
- **Version of the command being documented (if known):** 3.4.5
=> ruby: update page

pages/common/keepassxc-cli.md
- **Version of the command being documented (if known):** 2.7.10
=> keepassxc-cli: update page

pages/common/gem.md
- **Version of the command being documented (if known):** 3.6.9
=> gem: update link and add short options

pages/common/jq.md
- **Version of the command being documented (if known):** 1.8.1
=> jq: remove unnecessary /

pages.nl/common/git-reset.md
=> git-reset: add Dutch translation

pages.nl/common/git-clone.md, pages/common/git-clone.md
=> git-clone: update page and add Dutch translation

pages.nl/linux/lsblk.md
=> lsblk: add Dutch translation

pages.nl/linux/zathura.md, pages/linux/zathura.md
=> zathura: update page and add Dutch translation

pages.nl/common/uv-run.md, pages/common/uv-run.md
- **Version of the command being documented (if known):** uv 0.8.13 (ede75fe62 2025-08-21)
=> uv-run: fix placeholders and add Dutch translation

pages.nl/common/impacket-sambapipe.md, pages.nl/common/vc.md
=> impacket-sambapipe, vc: add Dutch translation

pages/linux/fscrypt.md
=> fscrypt: add example and sudo

pages.it/windows/wget.md
- Added `pages.it/windows/wget.md` with Italian translation.
- Verified that examples remain consistent and functional.
=> wget: add Italian translation

pages.es/common/crontab.md
Updated the crontab documentation link for more accurate information.
=> crontab: updated Spanish translation

pages.es/common/helm.md
Updated Helm documentation link for more details.
x
=> helm: updated Spanish translation

pages/common/history.md
=> history: remove unnecessary placeholder

pages/common/nuclei.md
=> nuclei: refresh page

pages/linux/systemctl-cat.md
Addresses a part of the Issue: #17684
=> systemctl-cat: add page

pages/linux/updatectl.md
=> updatectl: simplify page

pages/linux/aur-sync.md
=> aur-sync: add page

pages/linux/lvconvert.md
=> lvconvert: add page

pages/linux/gksu.md, pages/linux/gksudo.md
=> gksu, gksudo: add pages

pages/common/ts-node.md
=> ts-node: update more info link and update options

pages/common/choose.md
=> choose: update more info link and short options

pages/linux/pacman-sync.md
=> pacman-sync: fix description

pages/common/pngcheck.md
=> pngcheck: use manned

pages.es/common/npm-docs.md, pages/common/npm-docs.md
Issue: #14000 
Lenguages: english & spanish
=> npm-docs: add page and Spanish translation

pages/common/tsc.md
=> tsc: add initialization example and short options

pages/common/lpoptions.md, pages/common/lpq.md, pages/common/lprm.md
=> lp{rm, q, options}: remove optionality

pages.es/common/a2ping.md
- [✓] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [✓] The page(s) have at most 8 examples.
- [✓] The page description(s) have links to documentation or a homepage.
- [✓] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [✓] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [✓] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
=> a2ping: update Spanish page

pages.ar/common/gpg.md, pages.de/common/gpg.md, pages.ja/common/gpg.md, pages.ko/common/gpg.md, pages.pt_BR/common/gpg.md, pages.zh/common/gpg.md
=> gpg: refresh pages

pages.nl/common/file.md, pages/common/file.md
=> file: update page and add Dutch translation

pages.nl/common/ghcup.md, pages/common/ghcup.md
=> ghcup: update page and add Dutch translation

pages.nl/common/history.md, pages/common/history.md
=> history: update page and add Dutch translation

pages.es/common/aws-s3-cp.md
=> Aws-s3-cp: Add spanish translation

pages/common/pest.md
=> pest: update more info link

pages/common/kubectl-describe.md
This pull request improves the documentation for `kubectl describe` by adding more clear and common use cases.
=> kubectl-describe: refresh page description

pages/linux/gnome-software.md
=> gnome-software: update more info link

pages/linux/mdbook.md
=> mdbook: update more info link

pages/linux/flameshot.md
=> flameshot: add short options

pages/linux/ufw.md
=> ufw: update page

pages.es/common/yes.md, pages.ko/common/yes.md, pages.nl/common/yes.md, pages.pl/common/yes.md, pages.pt_BR/common/yes.md, pages.tr/common/yes.md, pages.zh/common/yes.md, pages/common/yes.md
- **Version of the command being documented (if known):** 9.7
=> yes: add backticks to apt-get

pages.es/common/tldr.md, pages.id/common/tldr.md
=> tldr: refresh pages

pages.nl/common/createdb.md, pages/common/createdb.md
=> createdb: add short options and add Dutch translation

pages/common/cmatrix.md
=> cmatrix: add screensaver example

pages/linux/systemctl-suspend.md
=> systemctl-suspend: add page

pages.nl/common/dropdb.md, pages/common/dropdb.md
=> dropdb: update page and add Dutch translation

pages/common/xteddy.md
=> xteddy: fix keypress syntax

pages/common/piper.md
=> piper: fix more info link

pages/linux/kde-builder.md
=> kde-builder: group options

pages/common/mamba-repoquery.md, pages/common/mamba.md
=> mamba, mamba-repoquery: update pages

pages/linux/lvm_import_vdo.md
=> lvm_import_vdo: add page

pages/windows/runas.md
=> runas: add page

pages/linux/pvesh.md
=> pvesh: add usage instructions

pages/linux/lvmdiskscan.md
- [x ] The page description(s) have links to documentation or a homepage.
=> lvmdiskscan: add page

pages.es/common/tqdm.md
Updated the tqdm documentation with additional examples and improved clarity.
x
=> tqdm: update Spanish translation

pages.es/linux/grub-mkconfig.md
=> grub-mkconfig: updated Spanish translation

pages.nl/common/g++.md, pages/common/g++.md
- **Version of the command being documented (if known):** g++ (GCC) 15.2.1 20250813
=> g++: update page and add Dutch translation

pages.nl/common/git-bisect.md, pages/common/git-bisect.md
- **Version of the command being documented (if known):** 2.51.0
=> git-bisect: update page and add Dutch translation

pages.es/linux/qm-agent.md
Add documentation for qm agent command alias
x
=> qm-agent: add Spanish translation

pages.es/linux/avahi-browse.md
=> avahi-browse: updated Spanish translation

pages/common/qdbus.md
=> qdbus: fix syntax

pages/common/dbeaver.md
- **Version of the command being documented (if known):** 25.1.5.202508172103
=> dbeaver: update page

pages.nl/common/ruby.md
=> ruby: add Dutch translation

pages/linux/systemctl-suspend-then-hibernate.md
Addresses the part of the Issue #17684 
=> systemctl-suspend-then-hibernate: add page

pages/common/pulumi-stack-hist.md, pages/common/pulumi-stack-history.md
=> pulumi-stack-history, pulumi-stack-hist: add page and alias

pages/linux/mkvpropedit.md
=> mkvpropedit: add page

pages.es/linux/wine.md
Updated the link for more information about Wine commands.
=> wine: update Spanish translation

pages/common/feh.md
- **Version of the command being documented (if known):** 3.11.1
=> feh: update page

pages.es/linux/pivpn.md
=> pivpn: update Spanish translation

pages.es/common/josm.md
=> josm: update Spanish translation

pages/common/omz.md
- **Version of the command being documented (if known):** master (2525dae)
=> omz: add enabled plugins example

pages/linux/lvmpersist.md
=> lvmpersist: add page

pages.ko/common/transmission-create.md, pages.ko/common/transmission-daemon.md, pages.ko/common/transmission-show.md, pages.pt_BR/common/transmission-create.md, pages.pt_BR/common/transmission-daemon.md, pages.pt_BR/common/transmission-show.md
=> transmission-*: refresh pages

pages/common/git-show.md
=> git-show: reorder examples

pages/common/git-subtree.md
=> git-subtree: refresh page

pages.zh/common/brew-autoremove.md, pages.zh/common/brew-bundle.md, pages.zh/common/brew-install.md, pages.zh/common/brew-list.md
=> brew-{autoremove, install, list, bundle}: add Chinese translation

pages.de/common/ansible.md, pages.fr/common/ansible.md, pages.id/common/ansible.md, pages.it/common/ansible.md, pages.ko/common/ansible.md, pages.pt_BR/common/ansible.md, pages.zh/common/ansible.md
=> ansible: refresh pages

pages/linux/systemctl-emergency.md
Addresses part of the Issue #17684
=> systemctl-emergency: add page

pages.es/common/batch.md
- **Vxrsion of the command being documented (if known):*x
=> batch: updated Spanish translation

pages/common/gh-alias.md, pages/common/gh-codespace.md, pages/common/gh-completion.md, pages/common/gh-config.md, pages/common/gh-extension.md, pages/common/gh-gist.md, pages/common/gh-help.md, pages/common/gh-issue-create.md, pages/common/gh-issue.md, pages/common/gh-label.md, pages/common/gh-pr-create.md, pages/common/gh-pr-merge.md, pages/common/gh-pr.md, pages/common/gh-release.md, pages/common/gh-repo-create.md, pages/common/gh-repo.md, pages/common/gh-screensaver.md, pages/common/gh-secret.md, pages/common/gh-ssh-key.md, pages/common/gh-workflow.md, pages/common/gh.md
=> gh-*: update pages

pages/osx/fuser.md
=> fuser: add page

pages.es/windows/sdelete64.md
- x ] The page(s) have at most 8 examples.
-x[ ] The page description(s) have links to documentation or a homepage.
x [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).x- [ ] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.mdx.
=> sdelete64: updated Spanish translation

pages/linux/lvmsadc.md
=> lvmsadc: add page

pages.nl/common/gh.md, pages/common/gh.md
- **Version of the command being documented (if known):** 2.79.0 (2025-09-09)
=> gh: update page and add Dutch translation

pages/common/behat.md, pages/common/cf.md, pages/common/scrapy.md, pages/common/supervisorctl.md, pages/common/supervisord.md, pages/common/telegram-desktop.md, pages/common/valgrind.md, pages/common/you-get.md, pages/common/zig.md, pages/linux/postfix.md, pages/osx/port.md
=> *: improve more info links, org domain

pages.nl/linux/adduser.md
=> adduser: add Dutch translation

pages.es/common/b2sum.md
=> b2sum: updated Spanish translation

pages.es/windows/sfc.md
=> sfc: updated Spanish translation

pages.es/windows/vol.md
=> vol: updated Spanish translation

pages.es/windows/wget.md
=> wget: updated Spanish translation

pages.es/windows/tree.md
=> tree: updated Spanish translation

pages.es/common/pulumi-stack-hist.md
- x ] The page(s) have at most 8 examples.
-x[ ] The page description(s) have links to documentation or a homepage.
x [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).x- [ ] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.mdx.
=> pulumi-stack-hist: add Spanish translation

pages.ko/common/xkcdpass.md, pages.pl/common/xkcdpass.md
=> xkcdpass: refresh pages

pages/common/git-blame.md
=> git-blame: fix filepath

pages/common/caddy.md, pages/common/ember.md, pages/common/gatsby.md, pages/common/git-annex.md, pages/common/ngrok.md, pages/common/pgcli.md, pages/common/plesk.md, pages/common/pre-commit.md, pages/common/pyinfra.md, pages/common/sails.md, pages/common/svgr.md, pages/common/terminalizer.md, pages/linux/ddcutil.md, pages/linux/xfreerdp.md, pages/osx/herd-list.md, pages/osx/herd.md
=> *: improve more info links, com domain

pages.es/common/env.md
- x ] The page(s) have at most 8 examples.
-x[ ] The page description(s) have links to documentation or a homepage.
x [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).x- [ ] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.mdx.
=> env: updated Spanish translation

pages/common/magick.md
=> magick: add percentage resize example

pages/common/agg.md
=> agg: add `--cols`,`--rows`, `--help` examples

pages.es/windows/where.md
=> where: updated Spanish translation

pages.es/windows/query.md
=> query: updated Spanish translation

pages/common/poetry-add.md
=> poetry-add: add page

pages.es/windows/scoop.md
=> Scoop: updated Spanish translation

pages.nl/linux/playerctl.md, pages/linux/playerctl.md
- **Version of the command being documented (if known):** v2.4.1
=> playerctl: update page and add Dutch translation

pages/common/split.md
=> split: add read from stdin example

pages.id/common/brew-autoremove.md, pages.ko/common/brew-autoremove.md
=> brew-autoremove: refresh pages

pages.id/common/brew-install.md, pages.ko/common/brew-install.md
=> brew-install: refresh pages

pages.es/common/docker-rm.md, pages.fr/common/docker-rm.md, pages.ko/common/docker-rm.md
=> docker-rm: refresh pages

pages.es/common/git-restore.md, pages.ko/common/git-restore.md, pages.tr/common/git-restore.md
=> git-restore: refresh pages

pages/common/chainctl.md, pages/common/django-admin.md, pages/common/fastd.md, pages/common/hg.md, pages/common/npm-version.md, pages/common/pueue.md, pages/common/puppet.md, pages/common/rails.md
=> *: conform to the style guide

pages/linux/systemctl-add-requires.md
Addresses the part of the Issue #17684
=> systemctl-add-requires: add page

pages.it/common/git-prune.md, pages.ko/common/git-prune.md, pages.tr/common/git-prune.md
=> git-prune: add short/long options

pages/common/fast.md
=> fast: added verbose option

pages.es/windows/fsutil.md
=> fsutil: updated Spanish translation

pages.es/windows/prompt.md
=> prompt: updated Spanish translation

pages.nl/common/git-blame.md
https://github.com/tldr-pages/tldr/pull/18196 for translations
=> nl/git-blame: fix file path

pages/linux/systemctl-poweroff.md
=> systemctl-poweroff: add page

pages.es/windows/expand.md
=> expand: updated Spanish translation

pages.es/windows/netstat.md
=> netstat: updated Spanish translation

pages.es/windows/vol.py.md
=> vol.py: updated Spanish translation

pages/linux/lsblk.md
=> lsblk: add ROTA information column

pages/common/type.md, pages/common/which.md, pages/linux/whatis.md, pages/linux/whereis.md
=> whereis, which, whatis, type: refer to each other

pages.es/windows/replace.md
=> replace: updated Spanish translation

pages/common/btop.md
=> btop: add a more direct more info link

pages.es/common/pulumi-login.md, pages.ko/common/pulumi-login.md, pages/common/pulumi-login.md
=> pulumi-login: fix URL in command description

pages.nl/common/pip-install.md, pages/common/pip-install.md
- **Version of the command being documented (if known):** 24.3.1
=> pip-install: update page and add Dutch translation

pages.nl/common/pip-uninstall.md, pages/common/pip-uninstall.md
- **Version of the command being documented (if known):** 24.3.1
=> pip-uninstall: update link and add Dutch translation

pages/common/ping6.md
=> ping6: add a note

pages/common/pip.md
=> pip: update more info link

pages.fr/common/docker-pull.md, pages.ko/common/docker-pull.md, pages.pt_BR/common/docker-pull.md
=> docker-pull: add short/long options

pages.es/common/fgrep.md
=> fgrep: add Spanish translation

pages.es/common/dirname.md
=> dirname: add Spanish translation

pages.nl/common/duc.md, pages.nl/common/pip.md
=> duc, pip: update Dutch more info link

pages.nl/common/brew-remove.md, pages.nl/common/brew-rm.md, pages.nl/common/gh-agent.md, pages.nl/common/npx.md, pages.nl/common/pulumi-stack-hist.md
=> pages.nl/common/*: add missing Dutch alias pages

contributing-guides/style-guide.md
=> style-guide: add subcommand instructions

pages/common/curl.md, pages/common/wget.md
=> wget, curl: add see also section

pages/common/btm.md, pages/common/btop.md, pages/common/glances.md, pages/common/htop.md, pages/linux/atop.md, pages/linux/top.md
=> btm, top, htop, btop, glances, atop: refresh pages

pages.pl/common/wcurl.md
=> wcurl: add Polish translation

pages/linux/systemctl-halt.md
=> systemctl-halt: add page

MAINTAINERS.md
Thank you once again for the opportunity, I have added myself to the active contributors in `maintainers.md`
Closes #18393
=> MAINTAINERS: add @Sadeeed as collaborator

pages/common/pip-lock.md, pages/common/pip-search.md
- **Version of the command being documented (if known): 25.2**
#18348
=> pip-lock, pip-search: add page

CONTRIBUTING.md, README.md, pages/dos/cd.md
=> dos: add platform, dos/cd: add page

pages/common/gh-variable.md
- **Version of the command being documented (if known):** documented at gh 2.80.0 (first added [gh 2.32.0](https://github.com/cli/cli/releases/tag/v2.32.0))
=> gh-variable: add page

pages/common/pg_test_timing.md
=> pg_test_timing: add page

pages/common/st-flash.md
No better PR/commit title came through my mind
=> st-flash: adjust formatting

pages.ru/common/uname.md
**Note on the `--nodename` flag:**
The original English page has two duplicate examples for the `-n|--nodename` flag. I believe this is a redundancy, so in this Russian translation, I have included only a single, more accurate example for this flag to improve clarity.
=> uname: add Russian translation

pages/linux/paclog.md
=> paclog: add page

pages/common/git-fast-export.md
- Fix one of the [review comments](https://github.com/tldr-pages/tldr/pull/18490#discussion_r2407821125).
=> git-fast-export: update page

.github/PULL_REQUEST_TEMPLATE.md
The command count gets automatically checked by the bot so it's not needed.
The page count however is better to be announce before the PR is sent
=> PULL_REQUEST_TEMPLATE: Update template

pages/common/poetry-install.md
#18042
- **Version of the command being documented (if known):** poetry 2.2
=> poetry-install: add page

pages/common/mvn-site.md
=> mvn-site: add page

pages/linux/mhwd.md
=> mhwd: add page

pages/linux/systemctl-preset.md
=> systemctl-preset: add page

pages/common/npm-dist-tag.md
=> npm-dist-tag: add page

pages.nl/common/brew-uninstall.md
I kept formula untranslated because all the other translations also did this.
=> brew-uninstall: add Dutch translation

pages.pt_BR/common/tail.md
- **Version of the command being documented (if known): GNU coreutils 9.3**
=> tail: add Portuguese translation

pages/common/cargo-info.md, pages/common/kubectl-port-forward.md
- **Version of the command being documented (if known):**   -
This PR is related to #17606.
=> kubectl-port-forward: add page

pages/linux/systemctl-get-default.md
=> systemctl-get-default: add page
