pages/common/ln.md

to make it clear what the `-T` option does, as discussed in #180.

add a separate example for overwriting a symlink

---

pages/common/git-remote.md

Add git remote

---

pages/common/rename.md

Ubuntu's rename (included in perl 5.14.2) does not include -c or --nows

add the regex for whitespace replace

---

CONTRIBUTING.md

- merge do's and don'ts, since they had mostly the same advice
- move token formatting info to the guideline section and the markdown section, as appropriate
- tweak spelling and fix a couple typos
- fix options vs. values in the formatting example, and add a token there.

rework/expand CONTRIBUTING.md

---

pages/common/uname.md

I think the connection with -s is still reasonably discernible, and the term OS is less ambiguous than just "system", so it doesn't need examples.

"system name" --> "operating system", rmv examples

---

README.md

Fix readme typo 'exilir' -> 'elixir'

---

pages/linux/apt-get.md
pages/linux/aptitude.md
pages/linux/dpkg.md
pages/linux/du.md
pages/linux/ip.md
pages/linux/mdadm.md
pages/linux/pacman.md
pages/linux/strace.md
pages/linux/wpa_cli.md

This topic is discussed in #278 
```
pages/linux/apt-get.md:6: MD009 Trailing spaces
pages/linux/apt-get.md:15: MD009 Trailing spaces
pages/linux/apt-get.md:13: MD012 Multiple consecutive blank lines
pages/linux/ip.md:13: MD009 Trailing spaces
pages/linux/aptitude.md:6: MD009 Trailing spaces
pages/linux/aptitude.md:18: MD009 Trailing spaces
pages/linux/aptitude.md:25: MD009 Trailing spaces
pages/linux/dpkg.md:1: MD018 No space after hash on atx style header
pages/linux/strace.md:1: MD009 Trailing spaces
pages/linux/strace.md:5: MD009 Trailing spaces
pages/linux/wpa_cli.md:19: MD009 Trailing spaces
pages/linux/mdadm.md:1: MD018 No space after hash on atx style header
pages/linux/pacman.md:6: MD009 Trailing spaces
pages/linux/pacman.md:14: MD009 Trailing spaces
pages/linux/du.md:17: MD009 …
```

Fix markdown lint warnings for linux man pages

---

pages/common/sort.md
scripts/markdown-style.rb

The discussion is in #314 ,  there is no need for excluding md038 warning now, so remove it :)

Remove markown md038 warning, close #314

---

scripts/pre-commit

It changes pre-commit hook to only lint, but not reindex.
This is a debatable thing to do, but I think I should do it.
Currently making index causes many issues for contributors, because when public requests are applied in different order, the index causes merging issues. Examples: #328, #325, #331 and many more.
I don't think we should remove index.json at the moment, because several clients still uses it: NodeJS and Web client, from what I know. After clients are switched to built index in [static site](http://tldr-pages.github.io/) and maybe some time after it (so we will give people time to update) we can completely remove index.json from the tree.
Until that one of the collaborators or owners can directly make index and commit it from time to time.

Don't make reindex on commit

---

.travis.yml
Makefile

Optimize make lint in approximately 80 times.
~~~
$ time make lint
make lint  80.43s user 10.98s system 97% cpu 1:33.85 total
$ time make check
make check  0.99s user 0.12s system 96% cpu 1.136 total
~~~
It is so fast that maybe there is no need for `make lint-changed` anymore.

Optimize make lint task

---

pages/common/python.md

I'm wondering if it'd make sense to include samples of the actual purposes for running the `-m` syntax, like running a webserver, or parsing json output in the terminal, with examples for those.
```md
* Parse JSON output
`cat raw.json | python -m json.tool`
* Serve the current directory at `localhost:8000`
`python -m SimpleHTTPServer`
```
Any ideas?

Adds -m syntax to python page

---

pages/common/cal.md
pages/common/ls.md
pages/common/scp.md
pages/common/srm.md
pages/linux/ss.md
pages/osx/systemsetup.md

These 6 files had multiple examples all separated by a single newline.
While rendering it in markdown, the examples all come up in a single
line.
Adding another newline makes rendering better.
Also will help in easier copying (double click on the line to copy).

Add extra newline between consecutive commands examples.

---

pages/common/test.md

It is controversial: see the last example.
~~~Markdown
- If-else statement
`test {{condition}} && echo "true" || echo "false"`
~~~
But honestly, IMO it is one of the most googled case regarding `test`.

test: add page

---

pages/common/lpstat.md

I took those examples from PR #324 (kudos to @Qtrain).
However I do not like the original PR because of several reasons:
* it has `lpstat` example in `lp`-page, which breaks the [guidelines](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md)
* it fixes `lint-changed.sh`, which must be done in separate commit
* it has index.json, which makes it harder to merge
So I took 2 missing examples of `lpstat` from original commit, also reworded it a little bit.

Update lpstat command: add 2 examples

---

pages/common/ls.md

This commit removes 2 things from `ls` command:
- I removed suffix and prefix example (`ls *files`), because it is against the rule to avoid explaining general UNIX concepts
- I removed -s from `ls -ls`, so it becomes `ls -l`. Rule 2 of Contributing Guidelines says "When in doubt, keep new command-line users in mind". `-s` shows the number of file system blocks actually used by each. I don't think CLI newcomers need this in 2015. Actually I think a few people still need to know this info.

Remove suffix & prefix example, remove -s from ls -ls

---

CONTRIBUTING.md

It makes it easier to mention in pull requests discussions.
E.g.
"This is against rule N3 from Guidelines"

Numbered list of rules in Contributing Rules instead of bulled list

---

CONTRIBUTING.md
Makefile

Rebuilding index is so old school.
See PR #378.

Remove index mention from Contributing Guidelines

---

pages/common/find.md

A simple way to find and delete files older than a certain number of days.
This is something I use frequently to clean up old log files (sometimes setup as a cron).

find: Delete files older than 'x' days

---

pages/osx/netstat.md

Added netstat.md file to OSX. (Wasn't sure if sunos had netstat, if it does, netstat should be moved to common)
Added some changes for common use cases for netstat. 
Added the -t (TCP) and -c (Continuous) options.

Add netstat to OSX, made small changes

---

pages/common/pip.md

Add tldr for installing a specific version of a python package, useful for working with python packages with annoying compatibility issues.

Add tldr for installing a specific version of a python package

---

pages/common/cordova.md

"plutin" -> "plugin"
Noticed it here: https://twitter.com/brianleroux/status/681649386338689024

Fix typo in cordova tldr page

---

pages/common/tar.md

It might confuse users if everything has no dash in front but the last command does. tar doesn't need the dash so let's keep it that way.

Make tar page consistent

---

CONTRIBUTING.md

We have several issues later when newcomers merge their master branch 
I improved (at least i think so) Contributing Guidelines:
- mention feature branches
- have detailed workflow to work with pull requests
- move it to the bottom
- add link to license
- some minor fixes
I took some part of it from bower (MIT), but reworked it.

Improve Contributing Guidelines

---

pages/common/printf.md

- printf is a bash command that acts like C's printf, supporting format
strings and modifiers.
Signed-off-by: Jose Ricardo Ziviani <jrziviani@gmail.com>

Add a new page about the printf command

---

pages/linux/pacman.md

Hey there,
I took the liberty to add the command `pacman -Qe` for listing all and only the explicitly installed packages (`-e` option), still showing versions. Useful when you want a concise list of the packages you have without all the dependencies.

Added command 'pacman -Qe'

---

README.md

Just published to Google Play, download link will only be available in a few hours.

Add Android client

---

pages/common/comm.md

`comm` is one of the lesser-known unix commands.

add comm command

---

Makefile

- adds prerequisites task to Makefile
- it warns about installation of Ruby and Bundler.
- It does not actually check anything, it just warns
Probably this should fix #468, as I think people were mostly frustrated by lack of messaging.
Actual checks that software is not installed is more complicated, and I might do it later.

Partially fix #468: warns that Ruby and Bundler must be installed

---

pages/common/gem.md

Specific version instruction missed gem name and mixed up -v and --version

Fixed tldr for gem

---

pages/common/ar.md

Does notation like `{{libfoo.a}}` and `{{foo.o}}` seem cromulent? Or should it be something like `{{archive.a}}` `{{source1.o}}...`?

ar: add examples and clean-up

---

pages/osx/diskutil.md

As of El Capitan, `sudo diskutil repairPermissions /` returns `diskutil: did not recognize verb "repairPermissions"; type "diskutil" for a list` since repairPermissions has been removed.
In the interest of keeping this tldr-compatible I've removed it. In the interest of not leaving things out, there could instead be a "this no longer works" notice.

removes no-longer-there diskutil verb

---

pages/common/host.md
pages/common/passwd.md
pages/common/salt.md
pages/common/sed.md
pages/common/touch.md
pages/linux/hostname.md
pages/osx/hostname.md

Page format consistency should be enforced to allow/facilitate parsing.
I made sure it matches the following template (I've used `+` as 'one or more',  parenthesis for grouping, and ignored empty lines):
```
(>{command_description})+
(
- {example_description}
(`{example_command}`)+
)+
```

make markup format consistent

---

pages/common/pkill.md

There is already an example of `pkill` on the `pgrep` page but I assume we want users to be able to look things up directly wherever possible. For that reason I have created a standalone page for `pkill` with an additional example.

pkill: add page

---

pages/common/pgrep.md

As discussed in https://github.com/tldr-pages/tldr/pull/541, I've removed the `pkill` example from the `pgrep` page.
As was originally the case for my `pkill` page, the `pgrep` command was using the incorrect token style `{{Finder}}`. I've corrected this use throughout. Let me know if you want me to change anything.

pgrep: remove pkill example and correct tokens

---

README.md

I wrote a client in Rust and would love for it to be included in the Readme. Thanks :smile:

Add Rust client to README.md

---

pages/common/nginx.md

Added the syntax for testing nginx configuration without affecting the running server, invaluable for people new to nginx when making configuration changes on a 'live' server.

nginx: add -t example

---

README.md

We are often asked to mention or collaborate with bro pages or cheat:
- #266
- #558
- #488 
- and more
Let's at least mention those projects in README.md as it is done in cheat.

Mention cheat and bro as similar projects in README.md

---

pages/common/grep.md

Option to print line number when a match is found.  If you are a VIM user, it's common to grep -> show line number -> open file and go directly to the line number in the file instead of having to grep for the matches once again once in vim.

grep: add line number

---

pages/common/ln.md

Hard links are generally not allowed for directories.

ln: remove note about hard links for directories

---

pages/common/unrar.md

extracting with original directory structure is arguably a more common use case than extracting the files in a flattened manner.

unrar: reorder examples

---

pages/common/ln.md

-T is not present on my system, and the behavior itself is completely unintuitive.
How exactly do you overwrite a directory? Do you recursively delete its children?

ln: remove overwrite option for directories

---

pages/common/curl.md

According user contributing guidelines: User-provided values should use the {{token}} syntax.

curl: fix example according to style guide.

---

pages/common/tcpdump.md

- Fixed the syntax error in 'dest'.
- Changed the port filter to differentiate between source and destination ports. This gives a better idea to the user if he/she wants to filter on a particular source or destination port.

tcpdump: fixed syntax error and added better params

---

README.md

@rilut beat me to it :) Here's another Rust client that aims to support
offline caching, the way the NodeJS client does it.
Maybe we can merge the two clients somehow (rilut/rust-tldr#1),
otherwise they can coexist as they have a different focus: One fetches
the pages from the net on each command invocation, the other does local
caching.

Add another Rust client to the list

---

CONTRIBUTING.md

I changed the tldr page example in `CONTRIBUTING.md`, the starting point for most of our contributors. This way we should have some nicely new-looking pages in no time.
I also took ahold of the opportunity to add examples that demonstrate the naming convention that we've been using, then explained it afterwards. Happy to debate this bit, but I feel we've already done a fair bit of discussing on that. If we do, I'll split this PR and merge in the first bit. It's urgent.

Edited CONTRIBUTING.md to reflect final convention.

---

README.md

This is a reopening of #492, with better install instructions.

Add Crystal client

---

pages/common/autossh.md

Add autoSSH.
This one is perhaps a little overwhelming, especially since we're mostly documenting SSH flags for port forwarding. But as someone who supports hundreds of customer AutoSSH tunnels at work, the final command is (crazily enough) the minimal sane autossh command for a persistent tunnel.

Add AutoSSH

---

pages/linux/nm.md
pages/osx/nm.md

I did not use long options for compatibility between Apple and GNU `nm`. I limited examples to options that are available on both platforms.

nm: add page

---

pages/common/fortune.md

As I've commented in #373, I think the description of the -f example should use the word "file" because it matches with the short option name.
I've also updated the `fortune {{database}}` example to match the terminology, and reordered the examples in an order that I believe is more intuitive.

fortune: reword description of -f option, reorder

---

pages/common/git-tag.md

I think I somehow managed to create this in this repository instead of in my own.
Anyway, I was looking up how to create an annotated tag since only those will be pushed to GitHub. Couldn't find it in the tldr page. Except it was really just hidden.

git-tag: Clarified how to create annotation

---

pages/common/pkill.md

Its useful to be able to kill processes by their full command. The pgrep tldr page already has a -f flag example.

pkill: Add example with -f flag

---

pages/linux/xinput.md

The xinput utility is useful when you want to turn off a input device (laptop keyboard, for example).

Added xinput command for Linux

---

pages/common/tldrl.md

Contributing guidelines in #694 refer to this page, but currently do so using `tldr tldr-lint`. I'm trying to get `tldrl` to become the pedantic way of referring to it.
Let's get this tool used and save us some work like it's supposed to be. It's rather sad Travis is the only audience.

tldrl: add page

---

pages/common/sed.md

- don't use g in all examples
- fix option for extended regex (-E is in grep :))
- use the term "in-place" in the example using -i (and remove a stray `''`)
- use the term "expressions" in the example using -e

various fixes and tweaks to sed

---

CONTRIBUTING.md

A few lines on how to use `tldr-lint`, since the automatic formatting could save us a lot of trouble. Basically the best feature it has emerges through `tldrl pages -fi`, short for `tldrl pages --format --in-place`. It can fix pretty much everything except for wording issues and general weirdness. 
Basically I want Travis to be our last line of defense, everything else fixed by contributors before changes get sent in. Maybe I could refactor the linter a bit to make a distinction between normal and fatal (unfixable) errors, then always attempt a format in place in the git hook which errors out when you've messed up too badly and just silently fixes your stuff when you didn't. It's a bit ambitious but we're almost there anyway.
Also tried to think of a good way to mention somewhere "Please …

Added contributing guidelines on tldr-lint

---

pages/common/scp.md
pages/common/sftp.md

Reworked SCP:
* No double examples
* Replace IP address with hostname place holders.
* change word use to avoid upload & download
* alter two remote hosts example to not require agent forwarding.
Added SFTP.

SSH File Transfer (SCP, SFTP)

---

pages/common/ln.md

"original" can be associated with the origin of the link and lead to confusion if not read carefully. Using "target" instead prevents this ambiguity.
Btw, the third example seems to have been copied from the prior example but not fully adapted: "original/file" should have said (if I'm reading this correctly) "original/folder".
Also, I removed `/file` from the "file or folder" examples, to make it more generic.

reword to prevent ambiguity

---

CONTRIBUTING.md

Added a note on our linter/formatter right after mentioning our syntax. It's also somewhere in the step-by-step instructions but it looks like people hardly read those. This way it's near the bits that people _probably_ read if they read the page at all. No guarantees.

Added more notes on tldr-lint

---

pages/common/license.md

[license](https://github.com/nishanths/license) is a tool for quickly/easily adding a license file to an open source project.
In the last example, you might wonder why I say "explicitly-set name and year". By default, license pulls your name from your git/mercurial config files (or the environment variable `LICENSE_FULL_NAME`), and just uses the current year. Thus, you only need to use those command flags if you specifically don't want your git/mercurial name or the current year. I can't really think of a succinct way to explain that in the tldr page, unfortunately.

Add license

---

pages/common/redshift.md

[Redshift](http://jonls.dk/redshift/) is a tool for adjusting your computer screen's color temperature to match your surroundings. (Same concept as [f.lux](https://justgetflux.com/), if you've heard of that, but it has more config options and you run it from the command-line.)
I used a lot of specific examples rather than generic examples, because it seemed like it'd be harder to succinctly get the point across otherwise (given how odd the formatting is on a lot of redshift's params).

Add Redshift

---

pages/common/read.md

Added a page for the read builtin of BASH shell. I mentioned in the description that this is the read for this specific shell, as the options of read in zsh and fish differ from those in BASH.

added a page for the read builtin

---

pages/common/lsof.md

The last letter of last word of [the three lines](https://github.com/tldr-pages/tldr/commit/9676334119847078e5e05fec393a3fe36991dbc2#diff-fe9ad5b63478a92eaf51544c5808ee6cL14) was omitted after reformatted.

[lsof] Fixed typo after reformatted

---

pages/osx/airport.md

Just noticed the two commands I find most useful in `airport` are both excluded from `airport`'s tldr page! Here's a quick revision adding these commands.

airport: added sniff and status info commands

---

pages/common/lwp-request.md
pages/common/skicka.md
pages/common/youtube-dl.md

Added three tools for downloading remote files:
* [skicka](https://github.com/google/skicka), a CLI tool for working with Google Drive
* [youtube-dl](https://rg3.github.io/youtube-dl/), a very complex/versatile tool for downloading videos and playlists from YouTube and other sites
* [lwp-request](http://search.cpan.org/dist/libwww-perl/bin/lwp-request), a simple HTTP client (this ships with OS X, but you can actually install it on any platform, so I put it in _common_)
lwp-request also typically is installed with aliases GET, POST, and HEAD, which are the equivalent to doing `lwp-request -m METHOD`. I wasn't sure how I might mention these, so at present, my lwp-request.md file doesn't mention these. But they are quite handy and common, so maybe they should be worked in somehow.

Added download tools

---

pages/linux/archey.md
pages/osx/archey.md

Archey is a tool that displays some basic system information alongside an ASCII version of your OS's logo. The tool exists on both OS X and Linux, but they're separate codebases that work slightly differently, so they get separate pages.
The OS X version has a couple of flags for tweaking the output, while the Linux version has absolutely no options (and I would have never bothered adding it if I wasn't also simultaneously adding the OS X one). I used the long forms of the flags for the OS X page, even though every flag does have a shortcut, simply because I don't think anyone uses archey frequently enough to memorize the flags.

Add archey

---

pages/common/dhcpwn.md

[DHCPwn](https://github.com/mschwager/dhcpwn) is a pentesting tool for attempting IP exhaustion attacks and for sniffing DHCP traffic.
I'm a bit worried that the meaning of `{{network_interface}}` might not be clear enough to some people. You're meant to use the standard interface names that are used system-wide, e.g. eth0, wlan0, lp, etc. I thought about including a command to get the list of network interfaces, but that differs between OSes and so forth. I thought about using a common placeholder interface name, but that too would be OS-specific (example: on Linux, your wifi card is probably `wlan0`, but on OS X it's probably `en0`). Maybe it's just clear enough as is? Chances are, if you're savvy enough to even know/understand what DHCPwn does, then you probably already know how your …

dhcpwn: add page

---

pages/common/npm.md

- 2 lines description, mentioned that it is not only Node.js package manager, but also JavaScript package manager (see official docs)
- Moved `npm init` to the bottom, it is the rarest command in the list. Change its description to more obvious one.
- Removed `npm prune`, this command is for hackers, not for regular users
- Removed `npm version`, it is useless
- Removed `npm publish`. It is for those who have npm modules published. Well in fact, even them do not do it every day.
- Added `npm uninstall` example
- Added `npm list` example

npm: removed some examples and added others

---

pages/common/awk.md

Searching for values in lines is a common operation with awk. I didn't specify that "something" is a regexp because it's not really useful at first.

awk: add /search/ example

---

pages/common/phpize.md

phpize is a little script you have to run in the process of compiling a PHP extension from source. Not a very frequently used or complex tool, but hey, it was one I knew how to use that wasn't already in the tldr pages.

phpize: add page

---

pages/common/xargs.md

The use of `ls` for piping is not recommended because of it's tendency to format into columns. It is more user friendly than machine friendly.
See http://stackoverflow.com/a/938052

Change 'ls' example for xargs page to 'find -name'

---

pages/common/tldr.md

The `--update` flag in the tldr command is super useful, and I was really surprised it wasn't in the tldr page when I was trying to remember how to update the other day. Thus, I've added it here!

tldr: added `--update` example

---

pages/common/sum.md

[sum](https://www.gnu.org/software/coreutils/manual/html_node/sum-invocation.html#sum-invocation) is an old checksum tool in GNU Coreutils, a predecessor to cksum.

sum: add page

---

pages/common/fzf.md

An awesome command-line fuzzy finder, here is the [homepage of FZF](https://github.com/junegunn/fzf).
Can fuzzy find quite everything, the [wiki](https://github.com/junegunn/fzf/wiki/examples) is a great place to discover this. 
It's also a great alternative to `ctrl-p` or `command-t` for vim users.

fzf: add page

---

pages/common/openssl.md

Shorten OpenSSL to 24 lines. Split keygen and csr to distinct examples. Standardize pathing. Remove commands which are just md5 verifying csr/key/csr.
The </dev/null are there because otherwise openssl waits for more input (batch mode) like a jerk until you send it an EOF.
Also switch to signing the CSR with SHA256 because SHA1 cert signing is deprecated for most browsers.

OpenSSL condensing.

---

pages/osx/say.md

The tldr page for `say` seemed like it needed some revision. I corrected the audio file command (it creates an AIFF file, not an M4A file). I added an example of how to use a custom voice and speech rate (it told you how to list the voices, but it didn't tell you how to actually use them!). Then there are just a couple of other formatting things and clarifications I made.

say: lots of cleanup

---

pages/common/mitmdump.md

[mitmdump](http://docs.mitmproxy.org/en/stable/mitmdump.html) is a tool for monitoring, recording, and transforming HTTP traffic on your local machine.

mitmdump: add page

---

pages/common/gdb.md

Add a page to `common` for `gdb`, the GNU Debugger.
Four examples were added:
* debug an executable,
* attach a process to `gdb`,
* execute given GDB commands upon start,
* start `gdb` and pass arguments.

gdb: add page

---

pages/common/crontab.md

Add a page to `common` for `crontab` command.
I found the most useful use cases were to:
* __edit__ crontab
* __list__ cron jobs
* __remove__ cron jobs
Tested on Ubuntu and OSX.

crontab: add page

---

pages/common/mkfifo.md

mkfifo is a standard POSIX utility, similar to mkdir, except it makes a named pipe (aka a FIFO; first-in first-out). Documentation for the GNU version of mkfifo is [here](http://www.gnu.org/software/coreutils/mkfifo), and the POSIX specification is [here](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/mkfifo.html) (this tldr page conforms to both specs \o/)
Could maybe document the --mode flag, which allows you to specify chmod-style file permissions. But I dunno how frequently used that would be, so it's probably fine as-is.

mkfifo: add page

---

pages/common/jobs.md

[jobs](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/jobs.html) is the POSIX utility for viewing status info on jobs running in the current shell environment. I pretty much only included arguments specified in the POSIX standard, but [Bash has some additional arguments](https://www.gnu.org/software/bash/manual/html_node/Job-Control-Builtins.html#index-jobs).

jobs: add page

---

pages/common/fg.md

[fg](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/fg.html) is the POSIX standardized utility for bringing suspended/background jobs to the foreground. If you run a job in the background with `somecommand &`, or if you suspend a job by pressing ^Z, you use fg to resume it.

fg: add page

---

pages/common/chgrp.md
pages/common/chown.md

Was quite surprised to get a "Page not found" error trying to look up a tldr page for chgrp today, so I whipped one up. Originally, I was planning to do an almost direct copy of chown's tldr page (since chown and chgrp have essentially identical syntax), but then I noticed I didn't like some things about the chown page. So, I made chgrp.md the way I thought looked best, and then changed chown.md to match.

Add chgrp (and tweak chown to match)

---

pages/common/pwd.md

Okay this is super trivial but bear with me. The acronym "e.g." means "for example, ", but in this case, an example wasn't being given, so the correct acronym to use is "i.e." (meaning "that is, ").

pwd: fixed minor typo

---

pages/common/hn.md

[hn](https://github.com/rafaelrinaldi/hn-cli) is a CLI for browsing Hacker News.

hn: add page

---

pages/common/xcv.md

[xcv](https://github.com/busterc/xcv) is a tool for cut/copy/paste on the command-line (unlike mv/cp, you don't have to specify a destination when cutting/copying, or a source when pasting -- it works just like Ctrl+X/C/V on your keyboard).

xcv: add page

---

pages/common/cmp.md

[cmp](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/cmp.html) is a POSIX-standard tool for finding differences between files. I only documented the POSIX-defined options, but there is a useful `-i` flag that pretty much every real world implementation of `cmp` supports (check out [this man page](http://man7.org/linux/man-pages/man1/cmp.1.html)). I was trying to document it but every way I worded it felt too awkward.

cmp: add page

---

pages/common/c99.md

c99 is the POSIX standard compiler for C that is meant to strictly meet the ISO C standard. This tldr page is based on [this POSIX spec](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/c99.html).

c99: add page

---

pages/osx/look.md

It is rarely used command, but still worth having it.
http://linux.die.net/man/1/look

look: add page

---

pages/linux/fc-match.md

The `fc-match` command is invaluable for diagnosing font problems in linux.  It describes the fall-back fonts that will be used for glyphs not in your current font.  For instance, I discovered that Debian Jessie wasn't detecting my font Monoid as Monospace and using standard book fonts with incorrect spacing.  I also have a PR for `fc-pattern` which displays extended information about a font.

fc-match: add page

---

pages/common/sed.md

Something I find myself doing more and more is to match on a line instead of trying to match all I want with `{{find}}`.
So in a file like:
```erl
{ riak_core, [ {
{riak_ip, "127.0.0.1"},
%% ...
}, 
%% ...
] }
```
Instead of replacing that ip by doing
```zsh
sed 's/riak_ip,"127\.0\.0\.1/riak_ip,"$NEW_IP/'
```
I do
```zsh
sed '/riak_ip/s/127\.0\.0\.1/$NEW_IP/'
```
Which has the added benefit of working regardless of whether I use single or double quotes on the file, or  if there's any space between `riak_ip` and the `,` and the actual ip.

Sed: adds replace before matching sample

---

pages/common/tput.md

tput is a utility for showing and modifying terminal capabilities. It can do a TON of stuff, and I'm not sure I did it justice. I tried picking some of the most common/useful commands, but it's entirely arbitrary. There are about a million capabilities you can pass to `tput` -- check out the list of cap-names in [the man page for terminfo](http://manpages.debian.org/cgi-bin/man.cgi?query=terminfo&sektion=5).

tput: add page

---

pages/common/gcc.md

Added the option for "converting" C* source code into assembler instructions.
Provided we have source.c, the output will be written to a new file called source.s.

added gcc option

---

pages/common/scp.md

The order of arguments in `scp` was [wrong](http://serverfault.com/a/264598/283749). Thank you, though –this is awesome!

Wrong order of arguments in command

---

pages/common/git-submodule.md

I think this pretty well covers the basics. I'm not including removing a submodule because you use `git-rm` instead of `git-submodule` for that, but I would be happy to add it in if it's something that makes sense here.

git-submodule: Add tldr page for the git-submodule command.

---

pages/common/curl.md

Passing client certificates to access protected resources is something I find myself commonly doing in cURL and is something difficult to decipher solely from the `man` pages.

Client certificate in cURL example

---

pages/common/bower.md

Still related to issue #823. This command page is a lot based on the `npm` common page.
Link to the [bower homepage](http://bower.io/).

added bower to common pages

---

pages/linux/bzip2.md
pages/linux/expr.md
pages/linux/iptables.md

Two new pages: expr and bzip2.
Fixed type on iptables.md page.

expr, bzip2: add page. Typo fixed in iptables

---

pages/common/grep.md

- use "case-insensitive" in the description of the -i option to make the initialism clear
- use path/to/file instead of file_path
- mention extended regex syntax and expand first occurrence to spell "regular expression"
- clarify wording of the -C example description

various tweaks to grep

---

scripts/generate-pdf.sh
scripts/template.tex

Added code to export all current Markdown files as PDF with [pandoc](http://pandoc.org/).
To create the PDF file, go to `scripts` and run `./generate-pdf.sh` (It takes a bit to compile; about 30 seconds on my MacBook Air).

Export to PDF

---

pages/common/less.md

Example usage of the `-R` flag for enabling the interpretation of ANSI escape "colour" codes by less.

less: Add example for enabling ANSI color output

---

pages/common/odps-auth.md

odps auth command(like the concept of subcommand) deals with a set of commands dedicated to authority management.
This page serves as supplementary to odpscmd(https://github.com/tldr-pages/tldr/blob/master/pages/common/odps.md)
Other subcommands like odps-function, odps-instance... will come in other pages.

Odps auth tldr

---

pages/common/xargs.md

I wrote that command a while ago. When I read it today, I did not understand what I meant. I think it is now shorter, more clear and inline with the rest of the `tldr` style

xargs man page - shorter

---

pages/common/odps-auth.md

Add a `desc role {{user_role}}` to reduce the confusion as mentioned in https://github.com/tldr-pages/tldr/pull/884

odps-auth: add desc role

---

pages/common/gcc.md

Writing `Makefile` usually requires `-c` option of `gcc` to generate object files.
p.s. remote of previous PR #896 was broken by myself, I send this PR again with correct git config. Sorry about the inconvenience.

gcc: add -c option

---

pages/osx/xattr.md

Added a new page for osx xattr utility which deals with filesystem extended attributes.
http://xattr.sourceforge.net/
http://gotofritz.net/blog/geekery/os-x-extended-attibutes/
https://www.safaribooksonline.com/library/view/macintosh-terminal-pocket/9781449328962/re38.html

xattr: add page

---

pages/common/gpg.md

This chage adds examples for exporting public and private GPG keys.
This is particularly useful for backing up keys. In both cases they have
been output as ASCII armored text with the `--armor` flag to make the
output easier to work with.

Add examples for exporting GPG keys

---

pages/linux/unexpand.md

Added page for linux 'unexpand' command following previous pull request for 'expand' command page.
Omitted rarely used -t=LIST option.

unexpand: add page

---

pages/linux/expand.md

Added page for 'expand' command, page for 'unexpand' to follow.
Omitted rarely used -t=LIST option.

expand: add page

---

README.md

Hey guys, I've rebuilt the web client in a nicer way, with nicer tools and a better design.
I've also hosted it elsewhere so it can use HTML5 PushState (now url's look like `tldr.ostera.io/linux/du` instead of the scrambled mess it was before).
Would be great to have it merged ASAP so I can get rid of the old one :)

Update URL of Web Client

---

pages/common/grep.md

By default, grep already uses regular expressions when searching.
The example `grep -e {{^regex$}} {{path/to/file}}` is the same as `grep {{^regex$}} {{path/to/file}}`.
However, because of the comment about extended regular expressions, I mistakenly assumed `-e` was the option to enable it.
I believe most people would refer to `tldr` in this use case looking for the `-E` extended regular expressions.
With this in mind, I believe that example would be better rephrased as this pull request makes it.

Make extended regular expressions clearer

---

pages/common/uniq.md

This involves another command, but it's such a natural extension of uniq's `-c` functionality that I feel it's warranted to show here.
We should probably add a sort to the -c example too, because uniq only deals with *sequential* line repetitions.

uniq: add sorting example

---

pages/linux/iostat.md

- Added basic command usage without any flags.
- Removed the '-h' flag as it seems to be added implicitly by the cmd.
- Added the interval parameter.
- Added the '-m' flag.

iostat: Added some flags

---

pages/common/adb.md
pages/common/grep.md
pages/common/mkdir.md
pages/common/pv.md
pages/common/rmdir.md
pages/common/umount.md
pages/linux/cryptsetup.md
pages/linux/iptables.md
pages/osx/open.md

All pages follow a "path/to/some_file" convention. 
Its better to follow a single convention throughout. So fixed a few pages, which were not following it.

Applying the 'path/to/item' convention uniformly

---

pages/common/git-remote.md

`git-remote` is the only file with unicode characters (two of them), both of which can be replaced with their ascii counterparts.
Living in 2016 this shouldn't pose a problem, but then again many terminals are ascii only.

git-remote: unicode quotes to ascii quotes

---

pages/common/uniq.md

'uniq' does not detect repeated lines unless they are adjacent, so we need to sort them

sort uniq first

---

CONTRIBUTING.md

this allows the reader to visually separate the instructions and makes the longer git-command section less prone to trigger a TLDR (heh) when reading this part.
also, line wrapping tweaks, split a paragraph into two, and reword a couple passages for clarity

add subsections to "submit a PR" section

---

pages/common/ssh-keygen.md

Adds an ssh-keygen command to show the fingerprint of an SSH key in the same format that is used by Github to list SSH keys that it knows about.

Adds command to show SSH key fingerprint

---

pages/osx/du.md

The version I have uses `-d` for the depth option, not `-depth`. Here's the version string as shown by `man du`:
```
BSD                              June 2, 2004                              BSD
```
In addition to this fix, this commit changes the tokens to clarify that they are paths, and changes "directory" to "folder", which is shorter and more accessible.

osx/du.md: fix depth option, plus minor tweaks

---

pages/common/dig.md

Doing a reverse DNS lookup by typing out the IP address in reverse, plus adding `.in-addr.arpa` to the end is tedious, but fortunately `dig` has the `-x` option which makes that process much simpler as one can just feed it a normal IP address. I figured this should be documented for others who want to do reverse DNS lookups.

add section in dig.md for reverse DNS lookups

---

pages/common/7z.md
pages/common/7za.md
pages/common/7zr.md

There's already a tldr page for `7za`, the 7zip archiving tool from the p7zip package. But actually, the main executable from p7zip is `7z`. `7z` uses plugins to support lots of archive formats, while `7za` is a standalone version that only supports a limited set of archive formats. There's also `7zr`, which is another standalone version that exclusively supports the .7z formats. (I got all this info from [the ever-indispensible Arch Linux wiki](https://wiki.archlinux.org/index.php/p7zip#Differences_between_7z.2C_7za_and_7zr_binaries))
This PR adds a note to 7za.md explaining the relationship to `7z`, and also adds pages for `7z` and `7zr` (both pages are essentially copies of the original 7za.md page).

Added missing p7zip tools (7z and 7zr)

---

pages/osx/xcodebuild.md

rebased, squashed and reworded commits from #583 in order to keep only xcodebuild.md (the pod.md changes were picked into #1007) and to provide more informative commit messages.

xcodebuild.md: add page

---

pages/common/kill.md

I've rebased, improved the descriptions, and fixed linting issues in #616. This had to be done in a separate PR for the reasons explained in #996, but the original commits by @lanzhiwang remain properly attributed.
/cc @igorshubovych, @markusthoemmes, @rubenvereecken, @ostera.

kill.md: change signal explanation (closes #616)

---

pages/linux/apt-get.md

`apt-get autoremove` is surely one of the six most used `apt-get` commands, so it should be here among the others. For example, it is more common than `apt-get dist-upgrade`.

Add `apt-get autoremove`

---

pages/common/chmod.md

- To specify which single-letter parameter is being referenced
- As per #1018
- [grep](https://tldr.ostera.io/grep) also uses brackets

chmod: Use brackets instead of parenthesis

---

pages/common/curl.md

- Based on discussion in #1019
- Download: first example introduces `-o`, second one introduces `-O`,
third example introduces `-L` and `-C` using brackets as per #1018
- Data: first example introduces `-d` (default method is POST and
default Content-Type is application/x-www-form-urlencoded), second
example introduces `-X` and `-H`
- Count of examples is still 8 as before

curl: Add more download and rewrite data examples

---

pages/common/git-stash.md

- Difference between a stash name and a stash message was not clear. For
example, you cannot do:
$ git stash save foo
$ git stash apply foo
fatal: ambiguous argument 'foo': unknown revision or path not in
the working tree.
- Difference between stash `apply` and `pop` was not clear
- Make it clearer that all `apply`, `pop` and `drop` can take an
optional stash name, and that the default name is `stash@{0}`

git-stash: Make examples clearer

---

pages/common/more.md

- This makes sense in the less page, where there are examples for both
Page down and up, but not here.

more: Remove redundant `(next)` for Page down

---

pages/linux/useradd.md

Creating a new system user is common administrative task on the average linux server. Adding the appropriate command to tldr-pages will be rather useful, since it isn't something you do every day and is easy to forget.

useradd: Add command to create a system user.

---

pages/common/st-flash.md
pages/common/st-info.md
pages/common/st-util.md

[STLink](https://github.com/texane/stlink) provides some tools for developing on STM32 ARM Cortex microcontrollers.
- st-flash
- st-util
- st-info
Those are the standard open source tools for STM32.

Stlink pages

---

pages/common/git-rebase.md

`git rebase --onto <NEW_BASE> <OLD_BASE>` is a common usage if you want to keep history tidy.

git-rebase: add --onto option

---

pages/common/c99.md
pages/common/gradle.md
pages/common/handbrakecli.md
pages/common/mp4box.md
pages/common/parallel.md
pages/common/python.md
pages/common/ssh.md
pages/common/sshfs.md
pages/osx/xctool.md

Inspired by @liuderchi's #1081 and others before that: #967, #965, #947, #699, #658, #534, #313, #312, #309, and #308 (Phew! I think I got them all. Maybe we should create a new label for large-scale cleanups like these).

page format: lowercase command names consistently

---

pages/common/column.md

Built following this man page : [column(1): columnate lists - Linux man page](http://linux.die.net/man/1/column)
Sadly the options don't have a long format, that's why is so hard for me to remember.
It is similar to [tldr/csvlook.md](https://github.com/tldr-pages/tldr/blob/aa60fa0f7ad3c9d5471b77329686a3e40e270106/pages/common/csvlook.md), but way quicker.
After some trouble, I installed  the linter/formatter locally via the [arch-npm/](https://hub.docker.com/r/nfnty/arch-npm/) docker image and aliased `tldrl` as
`alias tldrl "docker exec npm tldrl"`, work like a charm :-)
Thanks for tldr!

column: add page

---

CONTRIBUTING.md

All contributors to this project are invited to voice their opinion about this Contributor License Agreement (CLA) :) I crafted it after doing some research on CLAs, particularly https://github.com/clahub/clahub#whats-a-cla and https://opensource.com/law/11/7/trouble-harmony-part-1
The text of the CLA can be found at https://cla-assistant.io/tldr-pages/tldr. Copied below for convenience:
> ## TDLR Pages contributor agreement
> (1) I assert that any past, present and future contributions I make to the tldr-pages project are my own work, and that I have the right to license them.
>
> (2) I agree to license all my contributions to the tldr-pages project under the terms of the license included in the tldr-pages repository I’m contributing to.
>
> (3) I grant the tldr-pages organization a …

add CLA to contributing.md

---

scripts/generate-pdf.sh
scripts/template.tex

It looks like the pull request submitter hasn't used an editor with `.editorconfig` support, so he got wrong indentation. I got that fixed. :book:

Fix the indentation in PDF conversion files

---

CONTRIBUTING.md

- adjust whitespace & line breaks to make the markdown source more readable and consistent
- remove "we"/"our", to avoid reinforcing the "us vs. them" paradigm
- clarify a couple passages
- remove obsolete license agreement notice, now covered by the CLA
- remove redundant (and oddly specific) plea for contributions and the end of the document,
since there's already one at the beginning
- remove a redundant example of commit message format

contributing.md: various tweaks

---

.travis.yml

- This was not letting new changes from tldr-lint repo to be fetched.
Therefore, preventing new checks like trailing spaces to appear.
- Also, its a good practice to get possible updates from npm packages.

Setting cache to false

---

package.json

- And keep tldr-lint on a greater than mode
As discussed in #1095

Pin down the dependencies to their exact version

---

pages/common/vim.md

I tried to condense the most useful basic commands into this page without surpassing our length limit.
I also expanded the main description -- I wonder if there's a way to phrase it which could allow us to get rid of all the <Esc>s...
I combined copy/cut/paste into a single command, since it was important to allow space for a slightly more advanced command, (the find/replace example), which introduces some important vim concepts, such as command application ranges.

vim: improve examples

---

pages/common/vim.md

Once in normal mode, which is the mode user should stay most of the time in vim, one does not need to press `<Esc>` before each command. Insert mode is a temporary mode.
Make this more explicit in the examples (using the ...then... format also present in `less`, `more`, etc.) Also use ...then... for the search example.
Remove the yand and delete example, due to the complexity and the fact that there's `P` to paste before and `p` to paste after the cursor, and in favor of the quit without saving example.

vim: Normal mode is the normal mode

---

pages/common/less.md
pages/common/more.md

Instead, explain additional keystrokes in the example title. See https://github.com/tldr-pages/tldr/pull/1106#discussion_r82836295
Also, change order of page up / down in `less` example to match title and to match the order of the other examples.

less, more: Don't use ...then... in examples

---

CONTRIBUTING.md

Commands requiring 'sudo' should be mentioned directly in examples. It would be helpful to include it in the guidelines.

add new guideline in CONTRIBUTING.md

---

pages/common/git-diff.md

- use {{commit}} instead of {{PATHSPEC}}
- start with the simplest invocation, git diff
- move command to show staged changes next to the first two, which it is related to
- clarify description of --summary example

git-diff: rework a bit for clarity

---

pages/common/git-reset.md

As mentioned in https://github.com/tldr-pages/tldr/pull/1088#issuecomment-249368792

git-reset: expand page

---

pages/linux/yum.md

"yum provides" is incredibly useful when you come from a different distro, and you don't know exactly what package provides a particular command.

yum: added "provides" as it is incredibly useful

---

pages/common/rg.md

ripgrep is a fast command line searcher like awk or the silver searcher that is implemented in rust.

rg: add page

---

pages/common/fuck.md

fuck command has no options.
However, you should consider setting the alias first (for example in ~/.bashrc) as specified in 'thefuck' repository.
fixes #1097

fuck: add page

---

.gitignore
.travis.yml
package.json
scripts/post_pr_comment.py

Add script to post Travid build errors on PRs

---

pages/common/aws-s3.md

Adds a few common aws-s3 cli commands.
Since the aws cli is quite large, I thought it would be useful to enter s3 separately. I'm assuming what we can do is `tldr 'aws s3'`.

aws s3: add page

---

pages/linux/uname.md
pages/osx/uname.md

Instead of a "if you're on Linux, which is irrelevant to those who aren't, this change uses tldr-pages' platform-specific support to provide relevant information for Linux and OS X users.

uname: split page to provide contextually-relevant info in the main desc.

---

CONTRIBUTING.md

- moved one entry from the general guidelines, since now there's a specific section for tokens;
- reordered and numbered the entries, for clarity and ease of reference
- rewrote some passages for clarity and conciseness.

CONTRIBUTING: streamline token guidelines

---

pages/linux/logger.md
pages/osx/logger.md

Splitting page into 2 variants because mac does not have the expanded options. So it's difficult to remember -P (port) and -p (priority). Hence using expanded options in linux, and short options in mac.

logger: add page

---

pages/common/ansible.md

Add new page for `ansible`.
I've verified the commands listed in the page on my MacBook, with `localhost` as the test group

ansible: add page

---

pages/common/sudo.md

Makes the example consistent with the command

sudo: use `shutdown -h` to halt rather than reboot

---

pages/common/hub.md

- make main description and command descriptions more specific
- simplify the fork command description
- simplify the pull-request example (both the command and description) hopefully without sacrificing information
- replace the browse issues example (which opens a page in the web browser) with one create a github remote for the current repo

hub: overhaul the page for improved clarify

---

pages/linux/apt.md

Since #1164 was closed I thought I might give it a try. I included the `purge` command in the description of `remove` because the page already has more than the recommended amount of commands (5-6).
Also included the `search` command, since @agnivade mentioned it in #1164. Most of the other commands are adapted or taken directly from the `apt-get` page.
Thanks for reviewing

apt: add page

---

pages/linux/dpkg.md

This is the `apt` equivalent of `yum`'s `what-provides` command.
dpkg -S `which dpkg`
-> dpkg: /usr/bin/dpkg

Adds dpkg note for finding which package owns a file

---

pages/linux/cmus.md

Addresses #1162 for cmus
Currently in pages/linux because I'm not sure if other operating systems have different commands.

cmus: add page

---

pages/linux/apt-key.md

It's useful when dealing with errors like:
`There is no public key available for the following key IDs:xxxxx`

apt-key: add adv option

---

pages/common/git-fetch.md

`git fetch --prune` deletes the local *references* to upstream branches (i.e. entries in `.git/refs/remotes/`), but the local *branches* that tracked them (i.e. entries in `.git/refs/heads/`) are kept.

git-fetch: --prune doesn't delete local branches

---

pages/common/git-push.md

Hopefully making it more useful and explicit.
Added a plain `git push` example, a `git push --all`, updated the remote branch deletion example, and reworded the descriptions.

git-push: revamp page

---

pages/common/bc.md

Usually `bc` isn't very useful if it doesn't return floating point numbers where appropriate. e.g., 3/4 returns 0 when started with `-i` but for most users they would expect 0.75 to be returned so the tldr should mention that the argument `-l`does floating point arithmetic.

bc: add a line about interactive usage with mathlib

---

pages/common/find.md

> -mtime n
File's data was last modified n*24 hours ago. See the comments for -atime to understand how rounding affects the interpretation of file modification times.
[source](https://linux.die.net/man/1/find)
You can also search [this page](https://www.gnu.org/software/findutils/manual/html_mono/find.html) for `-mtime` to see some examples:
```
find ~/ -daystart -type f -mtime 1
find /tmp /var/tmp -depth -not -type d -mtime +3 -delete
find /var/tmp/stuff -mtime +90 -exec /bin/rm {} \;
find /var/tmp/stuff -mtime +90 -delete
```

mtime argument (find command) expect numeric value

---

scripts/template.tex

Very small change due to https://github.com/tldr-pages/tldr-pages.github.io/pull/21#issuecomment-287008958
> Consolas is a proprietary font. Inconsolata, on the other hand, is an openly-licensed font inspired by Consolas, so it would probably be the best choice in our case.

Change font in template.tex

---

pages/common/yesod.md

The *yesod* CLI has a `--help` option but using it through the *stack* tool is a requirement and thus passing double dash arguments to it is cumbersome. This `TLDR` comes in handy to remember that clumsy commands to actually use the CLI tool.

yesod: add page

---

pages/linux/ip.md

`a` should be used instead of `an` in this context.

ip: update grammar

---

pages/linux/zramctl.md

zram is a linux kernel module, available since 3.14 and installed by default, that allows you to create virtual disks that are compressed on the fly and stored in ram.
While this PR adds a page about it, I don't expect it to be anywhere near perfect at first :P
http://karelzak.blogspot.co.uk/2014/08/zramctl.html

zramctl: add page

---

pages/common/tput.md

* Added `word wrap` examples
So I kind of pushed us to 7 examples here - however - i feel like if you have an enable word wrap command you need to also know how to disable it.

tput: add two examples

---

pages/common/mailx.md

I noticed that the wording was a bit awkward on the mailx command page, so I improved it a bit.

mailx: Improve the readability of the descriptions

---

pages/linux/x11vnc.md

Follow-up of #1264.
I would also like to clarify the last example: it's not clear to me what "monitor" means here (screen or display?) and why the description says 2 but the tokens say 0 and 1.

x11vnc: wording tweaks

---

pages/common/cowsay.md

I'm sorry @jeeftor, but I don't think the example introduced in #1266 adheres to the spirit of tldr-pages. It seems to be overly complex, too specific, and making use of way more commands than we normally accept as auxiliary to demonstrate the main command's functionality.
Looking forward to hear what you guys think.

cowsay: remove overly complex example, reword desc

---

pages/common/scp.md

The command to "copy [...] on a remote host to a local
directory" in the current scp tldr page was backwards.
scp arguments take the form `scp from to`.

Recursive scp arguments reversed

---

pages/common/cp.md

- change "directory" to "folder" (more beginner-friendly)
- change "original" --> "copy" to "file"/"folder" --> "copy", to be more explicit (inspired by #289)
- use an extension to distinguish file paths from folder paths
- reword some of the descriptions for clarity
- include examples to clarify when the target argument defines the actual copy, and when it defines the folder where to put the copy
- add an example to copy contents of a folder into another (existing) folder

[RFC] cp: major overhaul of the page

---

pages/common/curl.md

I wonder if `-k` is needed here. If so, should we use the spelled-out version (`--insecure`)?

curl: simplify last example (#1246)

---

pages/common/git-show.md

- adjust punctuation & spacing in main description
- adjust descriptions ("changes" --> "information", and explicitly list which info is returned in the first example)
- use a concrete example for the tilde notation
- add abbreviated example
Follow-up of #1331.

git-show: various tweaks

---

README.md

I just found out about this -- it looks like DistroWatch has put together a [web client](https://distrowatch.com/dwres.php?resource=man-pages) for tldr pages!
This was first announced on [DistroWatch Weekly, Issue 697, 30 January 2017](https://distrowatch.com/weekly.php?issue=20170130#sitenews), and is linked in the [Contributing to DistroWatch](https://distrowatch.com/dwres.php?resource=contributing#manpage) page.

README: add DistroWatch web client

---

pages/common/timew.md

This is a repeat of #1310. It will add the `timew` command. Timewarrior is advertised as:
> ... a command line time tracking application, which allows you to record time spent on activities.
[For more information see their website](https://taskwarrior.org/docs/timewarrior/)

timew: add page

---

pages/osx/carthage.md

- changed the main command description to match the project's standards
- reduced the size of the first example's description
- reworded example descriptions for clarity and consistency
Follow-up of #1278.

carthage: description tweaks

---

pages/common/elinks.md
pages/common/screen.md
pages/common/tail.md
pages/common/tmux.md
pages/linux/xsel.md

Title case, + sign as separator, wrapped in backticks.

standardize format of keyboard shortcuts

---

pages/common/elinks.md
pages/common/fzf.md
pages/common/kill.md
pages/common/killall.md
pages/common/screen.md
pages/common/tail.md
pages/common/tmux.md
pages/common/wuzz.md
pages/linux/at.md
pages/linux/rdesktop.md
pages/linux/xsel.md

This is a follow up of #1354, after discussion in [#1353](https://github.com/tldr-pages/tldr/pull/1353#discussion_r113900953).
This commit primarily changes all keyboard shortcuts to have spaces around the + sign, but it also adjusts capitalization (fzf.md), combinator symbol (fzf.md) and wrapping in backticks (at.md) that were missed in #1354, and standardizes sequences of shortcuts to be comma-separated (screen.md, tmux.md) as was already the case in wuzz.md.

keyboard shortcuts: further standardization

---

pages/common/git-checkout.md

As described in http://stackoverflow.com/a/9537923 (paraphrased below):
> You need to create a local branch that tracks a remote branch.
> The following command will create a local branch
> tracking the remote branch of the same name.
> When you push your changes the remote branch will be updated.
>
> `git checkout --track [remotename]/[branch]`
>
> This is a shorthand for `git checkout -b [branch] [remotename]/[branch]`.
>
> For git 1.7.2.3 and higher this is enough: `git checkout daves_branch`
>
> Note that with recent git versions,
> **this will command not create a local branch and will put you in a 'detached HEAD' state.**
> If you want a local branch, use the --track option.
> Full details here: http://git-scm.com/book/en/v2/Git-Branching-Remote-Branches#Tracking-Branches
This has …

git-checkout: correct checkout of remote branch

---

.github/stale.yml

So this is my proposal for configurations to use in our [probot-stale](https://github.com/probot/stale) integration, as discussed in #1350.
Any feedback about the time periods, messages, or other details of the configuration? /cc @agnivade @ostera @jeeftor @sbrl @igorshubovych @rubenvereecken.
Note: merging this won't automatically enable probot-stale on this repo; we'll need to activate it in https://github.com/integration/probot-stale.

create configuration file for probot-stale

---

pages/common/pygmentize.md

- adjust punctuation in main description and first example's description
- mention "list" (rather than "show") in the -L examples, to improve memorability
- explain what lexers are
- clarify which of the parameters are input and output filenames
- simplify last example

pygmentize: various tweaks

---

pages/linux/whatis.md

Some might find the glob easier to use if they don't understand regular expressions.

whatis: add glob example

---

CONTRIBUTING.md

the cla-assistant link leads to a page requesting the user to sign it, which may not be as friendly
since prospective contributors may want to simply read the CLA without a prompt to sign it.

CONTRIBUTING.md: fix link to CLA

---

pages/linux/hostnamectl.md

I've been setting up a raspberry pi just now, and I noticed that `hostnamectl` isn't in tldr-pages! This PR rectifies the problem :P

New command: hostnamectl

---

pages/linux/lxc.md

Confusingly, `lxd` uses `lxc` as its command. Also, I wasn't sure from the contributing guide how to format optional parameters so have gone with linux standard. I'll remove them if it's not the done thing.

lxc: add page

---

pages/linux/calc.md

There's a ton more you can do with this one, but I personally haven't learnt the full capabilities of this one :P
If you're on a debian-derivative, install it with `sudo apt install apcalc`.

New command: calc

---

pages/common/perl.md

For completeness: the -0 option is actually used to specify the input record separator
(as an octal or hexadecimal number).
Without it, the record separator is the newline character,
i.e. the files are processed line by line
(which doesn't allow find-replace expressions that include newlines to work).
According to the [documentation](http://perldoc.perl.org/perlrun.html#Command-Switches),
using plain `-0` is not guaranteed to have the effect of parsing the entire file,
because if the file does contain characters
with octal value equal to the parameter passed to (or implied by) the -0 option,
these characters will be treated as line breaks.
However, if the value exceeds 377<sub>8</sub> (i.e. 255),
it won't be matched to characters on the file.
777 is the preferred convention within that …

perl: swap -M example with -0, for multiline regex

---

pages/common/cmake.md

This makes the command slightly more complex, but it better reflects the use case of when the project is first generated.
In any case, the `-p` in `mkdir` ensures the command does not error out if the build folder already exists, so now both cases are supported.
I'm considering a further PR replacing this command by a version using the [-H -B trick](https://www.reddit.com/r/programming/comments/6b9r19/how_to_build_a_cmakebased_project/dhlfh05/), which would change the command to be:
cmake -H. -B{{build}} && make -C {{build}}
but that can be discussed separately.

cmake: add mkdir to the out-of-source build example

---

pages/common/mosh.md

This PR adds example commands for the `mosh` mobile shell (https://mosh.org) application (a replacement to SSH).
Mosh is [primarily available](https://mosh.org/#getting) on MacOS and Linux (various distros) and also on Windows (via Chrome), which is why this document was added to `common`. If you think otherwise, please let me know, and I can duplicate it into `osx` and `linux`, and remove from `common`.

mosh: add page

---

pages/common/quota.md

Because `quota` has an odd syntax for printing sizes in human readable units, i.e, `-s` and not `-h` like in other commands, I think it should be included in the tldr.

quota: added example of using human readable output

---

pages/linux/logwatch.md

Logwatch is a useful command to summarize log files. It can be configured to use settings from it's config file and run by cron, but it can also be useful to run ad-hoc from the command line.

logwatch: add page

---

pages/common/hugo.md

Hi there!
Hugo is kind of weird in that there's a bit of setup necessary to get up and running, the general flow is defined below in the commit message. 
I added the note on 
>you may also download one from
since it takes quite a bit of effort to create a theme from scratch, yet you need one as stated when you build a site for the first time:
```
[~/d/l/hugo]-> hugo new site mywebsite
Congratulations! Your new Hugo site is created in /home/dhaynes/development/lang-tutorials/hugo/mywebsite.
Just a few more steps and you're ready to go:
1. Download a theme into the same-named folder.
Choose a theme from https://themes.gohugo.io/, or
create your own with the "hugo new theme <THEMENAME>" command.
2. Perhaps you want to add some content. You can add single files
with "hugo new …
```

hugo: add page

---

pages/common/make.md

Personally, I find myself always forgetting the letter to run jobs in parallel (I don't use it often enough! :P).

make: add multithreading example

---

pages/linux/isoinfo.md

Another strange one! You probably don't need this. Mounting isos instead is much more convenient! Still, it's useful for scripts, I think.

isoinfo: add page

---

pages/common/cmake.md

As initially discussed in #1379. This removes the need to use `mkdir` and `cd`.
Inspired by this post:
https://www.reddit.com/r/programming/comments/6b9r19/how_to_build_a_cmakebased_project/dhlfh05/

cmake: use -H -B trick for out-of-source build

---

pages/common/git-config.md

- expand description of local and global options
- adjust example descriptions for clarity
- change the descriptions of the get/set/remove examples to be more generic 
- change the alias example to a more useful one

git-config: overhaul page

---

pages/common/umount.md

Note: the "dangerous" remark was not clear about what the danger is -- we can mention possible caveats, but it's better to be explicit.

umount: make descriptions more explicit

---

pages/common/curl.md

(also, minor tweaks to some of the descriptions)
fixes #1406

curl: remove -I from auth example

---

pages/linux/genkernel.md

Gentoo kernel generator often used by beginners or people who don't have the time to manually configure, compile and install the Linux kernel.

genkernel: add page

---

pages/common/xmllint.md

- fix string example, and improve its description
- move xpath information to the main description
- add "tags" synonym for "nodes"
- add a html example
- simplify description of doctype example
- capitalize "xml" consistently
----
"command: add page" for new pages, or "command: description of changes" for pages being edited

xmllint: various fixes

---

pages/common/duplicity.md

I didn't have the chance to comment on #1443. These are some of the changes I'd propose to make the page more readable. I still have some questions -- hopefully @sbrl can answer them:
- In the WebDAV example, is the variable still FTP_PASSWORD, or was that a copy-paste error?
- In the GPG example, is that meant to be GPG or PGP? I always mix the two. I changed the abbreviation in the description to the less ambiguous GnuPG, but I might have made the wrong assumption.
- In any case, the phrasing of that example feels a little awkward:
> Restore a **folder** from a gpg-encrypted local backup to a **folder**
Could it be clarified somehow?
----
"command: add page" for new pages, or "command: description …

duplicity: various tweaks

---

.github/PULL_REQUEST_TEMPLATE.md

The current wording seems to be confusing (cf. PR #1453),
so hopefully with a more explicit placeholder notation, this won't trip other contributors. /cc @jasonxia23.
----
"command: add page" for new pages, or "command: description of changes" for pages being edited

improve PULL_REQUEST_TEMPLATE

---

pages/linux/dmesg.md

This PR introduces `dmesg -w`  which is available since kernel 3.5.0 to follow the output of messages (same kind of `tail -f` for P `dmesg`)

dmesg: include flag to follow messages

---

pages/common/moro.md

These PR lowercases the title, as we normally do, and makes the descriptions more in line with the langyuage other tldr-page entries use ("To do X" --> "Do X")
I'm still unsure about one the first example, "Run moro once right after starting the working day, and once more before leaving work": is that an instruction for the user, who should run that command manually every day, or is it a way to start moro which from then on will automatically do the start/stop dance by itself (using the default day start / day ent times)? /cc @omidfi.
----
- [_] The page (if new), does not already exist in the repo.
- [_] The page (if new), has been added to the correct platform folder:  
`<command name>: add page` for …

moro: minor tweaks

---

pages/common/openssl.md

* Pretty great use case for `openssl` - to check the start and end date of a domain's certificate. 
* Also demonstrates how you can pipe a cert to `openssl x509` to read particular fields from it - which none of the existing commands seem to do.

openssl: display a domain's cert's start and end dates

---

pages/common/xxd.md

----
- [_] ~~The page (if new), does not already exist in the repo.~~
- [_] ~~The page (if new), has been added to the correct platform folder:  

xxd: reword descriptions for clarity & consistency

---

pages/common/ffmpeg.md

The ffmpeg command detects the output file type and automatically selects the proper output format. We do not need to specify format or sample rate. This greatly simplifies the extraction of audio from video files.

ffmpeg: simplify convert to audio example

---

pages/common/peerflix.md

- add a torrent url example (previously requested [here](https://github.com/tldr-pages/tldr/pull/1457#discussion_r135743311))
- add the --list and --subtitles options (given as examples in the [official documentation](https://github.com/mafintosh/peerflix/blob/master/README.md))
- make the magnet link example more realistic:
BitTorrent info hashes (BTIH) are hex-encoded SHA-1 hash sums of the "info" sections of BitTorrent metafiles;
SHA-1 hash values are typically rendered as a hexadecimal number, 40 digits long.
- replace "your favorite player" with "a media player" in the main description
- clarify which files from the torrent will be streamed in each case
- use snake_case in tokens
----
- [_] ~~The page (if new), does not already exist in the repo.~~
- [_] ~~The page (if new), has been …

peerflix: expand based on official docs

---

pages/common/find.md

Make the description clearer and more specific to the given `-1` parameter. Remove unnecessary `-name '{{}}'` from example.

find: improve -mtime example

---

pages/osx/port.md

Proposed page for mac ports port cli.
----

port: add page

---

pages/linux/ufw.md

One of the more obscure features of UFW is being able to add comments to your rules and was only added last year. This feature helps significantly when managing a complicated rule set. 
I tried to shim it in to an existing example without introducing too much complexity as the entry already has eight examples.
----

ufw: Added an example of rule comments

---

pages/common/mongod.md

mongod: add page

---

pages/common/traefik.md

traefik: add page

---

pages/common/r.md

r: add page

---

pages/common/locust.md

locust: add page

---

pages/linux/sar.md

sar: add page

---

pages/linux/microcom.md

I noticed the [microcom](http://manpages.ubuntu.com/manpages/xenial/man1/microcom.1.html) tool was missing from tldr. It's not a complicated tool, so the number of examples is limited.
----

microcom: add page

---

pages/common/zip.md

Use quotes instead of escaping the `*` in the `-x` example. Also making examples more meaningful, and with token highlighting.

zip: minor change in -x example

---

pages/common/sendmail.md

The syntax in the last two examples was reversed. This fixes those inaccuracies and shortens the notes about the postfix server not being configured for sending non-local emails.
----
- ~[ ] The page (if new), does not already exist in the repo.~
- ~[ ] The page (if new), has been added to the correct platform folder:  
`common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.~

sendmail: corrected inaccuracy in example

---

pages/common/last.md

Last by default puts its hostname information in a fixed width column. When you are trying to track down a long host name it is really inconvenient to have it truncated. The `-a` flag used in the  example resolves this issue. I have also included an example of using the `-i` flag to just get the ip address associated with the login
The last two examples were worded in such a way as to imply that the most recent entry would be returned, however the complete list of logins would be returned. I have changed the wording to reflect this reality.
----

last: add example that avoids hostname truncation

---

pages/common/couchdb.md

----
- [ x] The page (if new), does not already exist in the repo.
- [x ] The page (if new), has been added to the correct platform folder:  
- [ x] The page has 8 or fewer examples.
- [ x] The PR is appropriately titled:  
- [ x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines 
Closes #1175

couchdb: add page

---

pages/common/zip.md

zip: add encryption example

---

CONTRIBUTING.md

git push from a local branch fails if there is no branch of the
same name in the remote repository.
----

CONTRIBUTING: add missing args to git push (#1554)

---

pages/linux/perf.md

perf: add page

---

pages/linux/lscpu.md

This time I'm pulling rabbits out of hats by demonstrating a thing or two you didn't know `lscpu`. For instance, did you that Linux lets you dynamically enable and disable cpu cores?
----

lscpu: add page

---

pages/linux/pstree.md

pstree: add page

---

pages/linux/update-alternatives.md

update-alternatives: add page

---

pages/common/nmap.md

nmap: added examples for scanning a host with nse scripts and scanning enabled SSL/TLS ciphers/protocols on a host on port 443

---

pages/linux/write
pages/linux/write.md

----
- [OK] The page (if new), does not already exist in the repo.
- [OK] The page (if new), has been added to the correct platform folder:  
- [OK] The page has 8 or fewer examples.
- [OK] The PR is appropriately titled:  
- [OK] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines

write: add page

---

pages/common/dotnet.md

The CLI is quite extensive, I've tried to cover the most frequently used commands.
A similar page could be added for `mono`.
----

dotnet: add page

---

pages/linux/rspamc.md

I keep forgetting how to train my spam filter, and I realised the reason was that I hadn't created a tldr page yet :P
Apparently you can even adjust the weighting of individual rules with this command, but I haven't yet had to do that, so I'm not too sure on how it's done - which probably means it's a more advanced usage of the command.
----

rspamc: add page

---

pages/linux/modinfo.md

modinfo: add page

---

pages/common/borg.md

borg: add page

---

README.md

----
`<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited~~

Sudo is not needed for npm install

---

pages/common/npm.md

Added a use case for listing all globally installed modules with a tree depth of 0.

 npm: additional module listing use case

---

pages/linux/xdotool.md

I have added some more examples to xdotool since i didn't find them in there. Examples include sending text & keystrokes as well as focusing the current window and acquiring the current's window id
----

xdotool: added more examples

---

pages/linux/cal.md

For clarity I changed "-m" to "--monday".
Also, I've removed the "cal -y" for simplicity.
You could just user "cal {year}" to get the same information.
----
~~- [ ] The page (if new), does not already exist in the repo.~~
~~- [ ] The page (if new), has been added to the correct platform folder:  ~~
~~      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.~~

cal: Add use case for spanning date

---

pages/common/sudo.md

This adds the example `sudo -i`, which allows the user to enter an interactive shell with sudo.
Running sudo version 1.8.21p2 on Arch Linux, there is also a spelled flag `--login`, but this doesn't work on my macOS 10.11.6 system (sudo 1.7.10p9), hence using the syntax above.
----
~~`common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.~~

sudo: Add example to run an interactive shell

---

pages/common/ruby.md

ruby: add page

---

pages/common/chmod.md

Might not be approved, but this is the classic 755 on all directories, 644 on all files in a tree a la: https://stackoverflow.com/questions/18817744/change-all-files-and-folders-permissions-of-a-directory-to-644-755
As I just discovered `tldr`, I had to try my hand at updating a page with a command I have to Google every single time.
----

chmod: Add recursive 755/644 chmod example

---

pages/linux/whereis.md

whereis: add page

---

pages/common/ember.md

ember: Add `ember build -prod` command

---

pages/linux/iptables.md

"-p" with small "p" is for protocol
----

linux/iptables: fix capitalisation of option "-p"

---

pages/osx/xattr.md

While extended attributes can be of interest to various developers, removing the annoying quarantine attribute is by far the most common use of this command.  Being explicit is worthwhile here.
----

xattr: Add removing quarantine; the by far most common use of this command

---

pages/common/dep.md

dep is a tool for dependency management in the Go ecosystem.
Fixes #1659.
----

dep: add page

---

pages/common/speedtest-cli.md

speedtest-cli: add page

---

pages/common/mvn.md

mvn: add page

---

pages/common/hg-add.md
pages/common/hg.md

Related to #1728.
I'm not entirely sure where to add the `See also` information in the main `pages/common/hg.md` page. I've looked at PR #1675 but it doesn't mention if it should be on the 2nd line of the description, or at the end of the file.
----

hg-add: add page

---

pages/common/pg_ctl.md

pg_ctl: add page

---

pages/osx/base64.md

Add the `-n` option of `echo` in examples, so we can get expected Base64 data of `plain_text` and not the `plain_text\n`.
For example: 
- `echo tldr | base64` output `dGxkcgo=`
- `echo -n tldr | base64` output `dGxkcg==`
----

base64: add the -n option of echo in examples

---

.github/ISSUE_TEMPLATE.md

The placeholder was inadvertently made invisible by Github's HTML sanitization while rendering the text [here](https://github.com/tldr-pages/tldr/pull/1504#issuecomment-354375185). I've updated that comment to escape the `<` and `>`, and this PR fixes the actual template file.

ISSUE_TEMPLATE: add missing placeholder

---

.github/PULL_REQUEST_TEMPLATE.md

It's easier (and nicer-looking) to just remove entries than to format them with strike-through.
I'm not 100% sure this is better than the previous wording, but I personally feel (as a contributor) that this is easier.
(Also added punctuation to the last two entries, which was inconsistent with the first ones.)

PULL_REQUEST_TEMPLATE: simplify instructions

---

.travis.yml
pages/common/df.md

Used my token here.
Travis seems to be down. Will test it once it's up.

Using new travis token

---

.travis.yml
scripts/build.sh

Added documentation about travis token

---

COMMUNITY-ROLES.md

This completes the recent updates to the owners of the tldr-pages organization, following the actions described at https://github.com/tldr-pages/tldr/issues/1878#issuecomment-358610454
I managed to dig up public references for the invitations for @agnivade and @sbrl, and for @rprieto it was easy: I simply located the first commit in the repo. From now on, [according to the documented procedure](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md#for-adding-new-organization-owners), there will be issues we can refer to, so the next additions should be easier.
I couldn't find public discussions about my own addition, but I had the invitation email so I could get the date. That said, if I recall correctly, @rubenvereecken added me and @ostera at the same time, or at least in …

COMMUNITY-ROLES: update list of owners

---

contributing-guides/maintainers-guide.md

Just a small addition to the maintainers' guide about how to handle squash-type merges, plus small wording changes in the PR merging section.

maintainers-guide: cleanup msg when squashing

---

pages/common/stow.md

Gnu Stow - A symlink manager.
More information here: https://www.gnu.org/software/stow/

stow: add page

---

pages/linux/mkswap.md

mkswap: add page

---

pages/linux/swapoff.md

swapoff: add page

---

pages/common/box.md

This is tested to work with both versions of Box. Hence the `-c` for config. In `humbug/box` it was changed from `--configuration` to `--config` which breaks compatibility.
----
Unmaintained Repo: https://github.com/box-project/box2
Active Fork: https://github.com/humbug/box

box: add page

---

pages/common/rustup.md

Plenty of Rust crates require the nightly toolchain. Making `rustc` use the nightly toolchain globally has a tldr entry already, but I had to Google how to use nightly for just the current project. Switching back and forth between nightly and stable is done fairly often, so I think this example would be helpful.
([Link](https://github.com/rust-lang-nursery/rustup.rs/blob/master/README.md#directory-overrides) to command documentation.)
----

rustup: add override example

---

pages/common/gzip.md

From my testing in Ubuntu 16.04, the compressed files do not have the gz extension. Removed this to alleviate a little confusion.
----

gzip: Remove gz extension from output file

---

pages/common/sl.md

I came across the sl command recently and noticed that not all of the flags were covered in the TLDR page. This adds the other two possible flags.

sl: Include -l and -e examples

---

pages/osx/rubocop.md

I'm scoping this under `osx` because I have not confirmed that the instructions look identical on other platforms.
Resolves #1660 
----

rubocop: add page

---

pages/linux/ncat.md

This option let ncat accept multiple connections and keep them open after they are closed.

ncat: add -k option

---

pages/common/git-grep.md
pages/common/git-shortlog.md

git-shortlog: add page

---

pages/osx/brew-cask.md

Brew Cask has had a proper upgrade command since Homebrew/brew#3396
----
~~- The page (if new), does not already exist in the repo.~~ N/A
~~- The page (if new), has been added to the correct platform folder:  
`common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.~~ N/A

brew-cask: add cask upgrade

---

pages/common/jq.md

Examples look simpler with file as last parameter than with using `cat`,
also they explicitly show that you must use `.` as the default
all-matching rule.
Keep the last two examples with piping, and change their descriptions
accordingly.

jq: accepts a file as last parameter

---

pages/linux/fallocate.md

Linux-specific command line tool to allocate sparse files. Useful for allocating VM images or dummy files without "wasting" write cycles.
----

fallocate: add page

---

pages/common/ffmpeg.md

Added trim line and seconds fraction precision to the line relative to frame extraction.
----

ffmpeg: added trim example plus augmented precision to seconds

---

pages/common/ipfs.md

Added ipfs to common.
It actually has 10 examples.. Any suggestion on how to reduce them? Actually, I find important all of them as a not daily user reference .-.
----

ipfs: add page

---

pages/common/mysql.md
pages/common/mysqldump.md

Make sure to use the `-r <filename>` option, instead of redirecting command-line output to a file `> <filename>`. Redirection does not capture UTF characters properly, while the -r option does.
As well the import part was changed to fix the same issue.
----
- [ x] The page has 8 or fewer examples. (this is an edit)
- [ x] The PR is appropriately titled:  
- [ x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines.

mysqldump: make correct dump of UTF-8 databases

---

pages/osx/base64.md

One must use uppercase -D to decode.
Excerpt from the man page:
"base64 [-h | -D] [-b count] [-i input_file] [-o output_file]"
This is on macOS 10.12.6, man page from February 8, 2011.
----

base64: "Decode a file", changed from -d to -D

---

pages/common/fswatch.md

Without the `-n 1` argument to `xargs`, fswatch will will not trigger on
events.
Fixes #2119 
----

fswatch: Fix broken commands + simplifications

---

pages/common/finger.md

finger: add page

---

pages/common/cut.md

Found myself using this after consulting the tldr-page to refresh my memory on the arguments to `cut`, and thought I'd add it the page.
----

cut: Show syntax for n-to the end of a line

---

pages/common/uptime.md

....I suspect that this belongs in `linux/` too. Thoughts?
----

uptime: Fill out some more options

---

pages/linux/dnf.md

The `update` command of `dnf` doesn't work like `apt-get`'s : `dnf` automatically handles synchronizing list of packages.
In fact, it is a *deprecated* alias for the `upgrade` command.
Source : https://dnf.readthedocs.io/en/latest/command_ref.html#update-command
I also added `sudo` to all the listed commands, as all of them require root privileges (second point of the `CONTRIBUTING.md` file).

dnf: removed bad example

---

pages/windows/scoop.md

___
This adds a page for [Scoop](https://scoop.sh), a Windows command-line installer.

scoop: add page

---

pages/common/git-merge.md

Added `git merge --abort` example.
----

git-merge: add --abort

---

pages/common/ping.md

When I'm not using `mtr`, I'll often use the `-O` option to see when my server goes down and comes back up again during a reboot.
----

ping: add -O example

---

pages/linux/reset.md

The reset command comes with many more options, but most of them are quite advanced and you (almost) never need to use them - I certainly haven't had to yet.
----

reset: add page

---

pages/common/nimble.md

Nimble is the official package manager for Nim. Follow-up to https://github.com/tldr-pages/tldr/pull/2207 :smiley:

nimble: add page

---

pages/linux/shuf.md

updated linux/shuf  in favour of osx/shuf so that the pages remain consistent across Operating systems.
this happened as we changed osx/shuf in #2186

updated linux/shuf to match with osx/shuf

---

pages/common/sshfs.md

`umount` is [recommended](https://github.com/osxfuse/osxfuse/wiki/FAQ#48-how-should-i-unmount-my-fuse-for-os-x-file-system-i-cannot-find-the-fusermount-program-anywhere) according to the official wiki, `fusermount` is not found on recent versions of macOS.
Related: [this StackOverflow question](https://stackoverflow.com/questions/14057830/unmount-the-directory-which-is-mounted-by-sshfs-in-mac). Despite the (wrong) accepted answer, there are quite a few confirmations that `umount` should be used now.

sshfs: use umount instead of fusermount

---

pages/linux/apt-get.md

----
I realize this is a bit of a stretch, but I have personally had to repeatedly google how to search for a package w/ apt-get only to re-learn it was apt-cache many times.  I suspect I'm not the only person who has had this expectation of apt-get.
- [x ] The page has 8 or fewer examples.
- [x ] The PR is appropriately titled:  
- [ x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines.

apt-get: add pointer to apt-cache when searching for pacakges

---

pages/windows/where.md

I'm not sure whether this is the right way to override `commons/where.md`, but since `where` differs significantly on Windows, it should be treated differently IMHO. It is not limited to executables and has command line options available only Windows.
----

where: add page

---

pages/linux/dirname.md

I dropped by #2213, and found that `dirname` wasn't a page yet. Thought I'd fix that!
----

dirname: add page

---

pages/common/git-commit.md

Reorder commands in a more logical manner
I just moved the last command closer to the first one, because they were both similar.
----

git-commit: reorder commands

---

COMMUNITY-ROLES.md

This allows the template messages to retain the semantic line-breaking
that improves the readability of their source code version control diffs,
while at the same time they can be copy-pasted to issues
without the line breaks (which is slightly problematic
because github includes the line breaks
even when rendering content as rich-text prose).
(Case in point: this very PR, which reuses the extended commit message.)
Also, slightly reword a sentence in the "Past owners" section,
to make it more general and cover more cases.

COMMUNITY-ROLES.md: format messages as quotes

---

pages/linux/f5fpc.md

Had some issues with f5fpc and connecting via VPN to my university today. Long story short: I needed to `sudo` the `f5fpc` commands. Thought I'd update the tldr-page accordingly :slightly_smiling_face: 
----

f5fpc: Prepend all examples with sudo

---

pages/linux/nproc.md

I _think_ this is linux-specific, but I don't have a Mac to test on :P
For #2213.
----

nproc: add page

---

pages/linux/dpkg.md

Add example for listing package contents of a downloaded `.deb` file, because `dpkg -L` only works with the `apt` name of the package (and only when installed).
----

dpkg: add -c option (list local deb file contents)

---

pages/common/make.md

----
GNU Make does not support -J option and looking at BSD man page, the use of -J is discouraged anyway*.
* https://www.freebsd.org/cgi/man.cgi?make(1)

make: GNU Make does not support -J option

---

pages/common/autojump.md

From the autojump readme: https://github.com/wting/autojump
"Open File Manager To Directories (instead of jumping):
Instead of jumping to a directory, you can open a file explorer window (Mac Finder, Windows Explorer, GNOME Nautilus, etc.) to the directory instead.
jo music"
----

autojump: adding 'jo' command to open directory in OS file manager

---

pages/linux/eject.md

eject: add page

---

pages/common/bat.md

bat: add page (#2296)

---

pages/common/tsort.md

A command from the list in #2213

tsort: add page

---

pages/common/set.md

set: add page (#2268)

---

pages/common/tig.md

___
This adds a page for the [tig](https://jonas.github.io/tig/) text-mode interface to Git.

tig: add page

---

COMMUNITY-ROLES.md

The message templates for role changes pointed to the governance guidelines, but this document is the one that actually describes them.
So this commit changes links to GOVERNANCE.md to point to COMMUNITY-ROLES.md instead.
In addition, some wording changes were made elsewhere that hopefully make the intended message clearer.

COMMUNITY-ROLES.md: fix links, improve wording

---

pages/common/mpv.md

----
Thought this could be useful for some. Is there a specific style for keyboard shortcuts that can be used while the command/program runs? mpv accepts a bunch of shortcuts while playing video, and some of those would be nice to add to the tldr page, but I'm not sure if that's a) something you want in the tldr pages, and b) what syntax to use for that.

mpv: add page

---

pages/common/jupyter.md

Jupyter lab is now available for general use. It's common so might as well add it even though it's an obvious command.
----

jupyter: add jupyter lab command

---

pages/common/jpegoptim.md

----
Hi again, I find it useful to have an example of recursive optimization of `jpegoptim`
I use it only this way , also with --size param
`find {{.}} -name "{{*.jpg}}" -exec jpegoptim --strip-all --all-progressive --size={{250k}}  {} \;`

jpegoptim: added max size param example

---

MAINTAINERS.md

MAINTAINERS.md: add collaborators and organization members

---

pages/linux/users.md

users: add page

---

pages/common/subl.md

This adds a page for the command line interface for the popular text editing software [Sublime Text](https://www.sublimetext.com/)
-----

subl: add page

---

pages/common/php-yii.md

This adds a page for [Yii Framework's command line interface](https://www.yiiframework.com/doc/guide/2.0/en/tutorial-console)
-----

php yii: add page

---

GOVERNANCE.md

This is a simple change that doesn't affect the actual content in any way; it only changes the presentation, by using a numbered list (rather than a bulleted one) to make it possible to refer directly to specific governance rules.

GOVERNANCE: number principles to allow x-refs

---

pages/common/virtualenv.md

Adding --prompt option to customize the prompt prefix. It's helpful to distinguish between multiple virtualenvs as most of the time `venv` is chosen as the name of  the virtualenv directory and that it's chosen as the prompt prefix by default.

virtualenv: add --prompt option

---

pages/common/docker.md

The start and stop examples are pretty much identical, so it doesn't make sense to use up the space of two examples in the limited length of a tldr page (especially for such a complex command as docker).
In the slot left by combining the two entries, a new one is added mentioning how to launch a container from an image. Placing this example before the start/stop commands (and naming the parameter "container_name" consistently trhoughout the page) also makes the sequence more logical, by first explaining how containers are instantiated, and only then mentioning how they are managed.
----

docker: combine start/stop, add basic run example

---

MAINTAINERS.md

Changed the section names and intro paragraph for clarity.
Also, edited the first two sections to use semantic linebreaks,
which was already the case for the last two sections.

MAINTAINERS.md: clarify; use semantic linebreaks

---

pages/common/bat.md

The CLI argument is plural as seen here:
https://github.com/sharkdp/bat/blob/f9fd5e485173adf71b44888f72980577f16ddcf7/src/clap_app.rs#L55-L61

bat: fix typo

---

pages/linux/namei.md

namei: add page

---

pages/linux/dircolors.md

dircolors: add page

---

pages/common/banner.md

banner: add page

---

pages/common/dig.md

Remove google's mention, as proposed in 
https://github.com/tldr-pages/tldr/pull/2435#discussion_r224964020
----

dig: remove google's mention

---

pages/common/wpa_supplicant.md

wpa_supplicant: add page

---

pages/common/waitress-serve.md

Page for [waitress](https://docs.pylonsproject.org/projects/waitress/en/latest/index.html)'s CLI tool `waitress-serve`.
----

waitress-serve: add page

---

pages/common/helm.md

This adds a page for helm commands.
[Helm](https://helm.sh/) is a package manager for Kubernetes, that helps in defining, installing and updating k8s applications.

helm: add page

---

pages/common/fkill.md

This adds a page for fkill command.
[Fkill](https://github.com/sindresorhus/fkill) is cross-platform CLI tool that "fabulously" kill processes.

fkill: add page

---

pages/common/xsv.md

---
A first crack at #2333
- Should this use `{{path/to/worldcities.csv}}` instead of `{{worldcities.csv}}`?
- Should I describe that worldcities.csv can be downloaded with `curl -LO http://burntsushi.net/stuff/worldcitiespop.csv`?

xsv: add page

---

pages/common/sqlmap.md

sqlmap: add page

---

pages/common/cp.md

cp: remove redundant example

---

pages/common/pandoc.md

Shortened the example descriptions and added another example that shows standalone mode that is especially useful when working with LaTeX.
----

pandoc: add example

---

pages/common/darkhttpd.md

darkhttpd: add page

---

pages/common/kafkacat.md

This is for [kafkacat](https://github.com/edenhill/kafkacat).
There are some more examples on the kafkacat GitHub page. If you feel there should be more complicated examples included, I am happy to replace one or more of the ones already provided.

kafkacat: add page

---

pages/common/ag.md

Hi all,
I move the example introduced in #2491 to make it the 2nd example, as requested by @agnivade.
----

ag: move text to make it the 2nd example

---

pages/osx/whereis.md

`whereis` added without flags which don't exist for `osx`

whereis: add page to osx folder

---

pages/common/git-checkout.md

Adds an example for creating and checking out a new branch that's based on an existing remote/source branch with a different name.
It's similar to https://github.com/tldr-pages/tldr/pull/1359 - but shows the example of allowing the new branch being created having a different branch name than the source.
It's something I don't use super often, but end up having to Google each time because it's not in `tldr git checkout` :)
----

git checkout: add example for creating new branch based on remote branch with different name

---

pages/common/script.md

I created a page for the unix command script that records the terminal.
- [x ] The page (if new), does not already exist in the repo.
- [ x] The page (if new), has been added to the correct platform folder:  
- [ x] The page has 8 or fewer examples.
- [ x] The PR is appropriately titled:  
- [ x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines.

script: add page

---

pages/common/dot.md

dot: fix typo

---

COMMUNITY-ROLES.md

- Template links were added to the "When to change roles" section,
to make it easier to assess the thresholds described there.
- The "Who can change roles" section was changed
to make it clear that anyone can propose role changes.

COMMUNITY-ROLES: add links; clarify last section

---

MAINTAINERS.md

Hopefully as we refine the [role transition process](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md#how-to-change-roles), this metadata will be preserved more regularly.

MAINTAINERS.md: add missing dates and links

---

pages/common/iperf3.md

Added some spacing to match what the utility expect.
----

iperf3: fix spacing

---

pages/common/guile.md

I have added a tldr page for guile, the scheme interpreter.

guile: add page

---

pages/linux/rfkill.md

rfkill: add page

---

pages/common/stolonctl.md

Stolon is a cloud native PostgreSQL manager for PostgreSQL high availability, and stolonctl is the command line tool for it.
Ref: https://github.com/sorintlab/stolon

stolonctl: add page

---

pages/common/svn.md

The `svn help` example isn't of much use, so I replaced it with a more useful example which describes basic usage of `svn log`.

svn: add `svn log` example, remove unnecessary `svn help` example

---

scripts/build.sh

Now that we are supporting pages in multiple natural languages (#2339), we need to include all those pages in the tldr archive.

TravisCI: include pages of all languages in archive

---

pages/common/sudo.md

My changes are as follows:
1. Changed the more complex examples *involving* `sudo` to simple examples showing the *usage* of `sudo`.
2. Separate the examples of editing a file and doing something as another user
3. Standardized the wording to use superuser instead of root
4. Clarified the usage of `sudo !!` which is not a feature of sudo, but the shell you use. I'm half tempted to say we should just take it out, but it is a very useful shortcut that more people should know about.
5. Added the `-e` flag that allows you to edit files using your default editor as specified by the environment variables `VISUAL` or `EDITOR`. This has several other benefits over editing the file directly with a command like `sudo vim /etc/fstab` as well.
6. Fixed the odd syntax for the `shutdown` example which …

sudo: general revision of entry

---

pages/linux/pamac.md

Add a page for the command line utility of the GUI package management pamac which is also called pamac.
----

pamac: add page

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

This commit updates the commit message guidelines in CONTRIBUTING.md:
- Add example commit messages for translations and for changes that affect multiple pages;
- Prefix each example with a description of the type of change it refers to.
It also updates the PR template, to make it more compact and reduce duplication of information included in CONTRIBUTING.md:
- Remove horizontal rule at the top
(the comments are sufficient as visual separation);
- Shorten the comments to make them more compact and more likely to be read;
- Make each checklist entry take a single line;
- Remove blank lines between checklist entries.
This is a follow-up to the discussion at #2512.

Update Contribution guidelines and PR template

---

.github/PULL_REQUEST_TEMPLATE.md

Relative links may not work if the PR is created from a branch containing slashes in it, as pointed out by @pxgamer in [this comment](https://github.com/tldr-pages/tldr/pull/2575#discussion_r233264824).
ps - I've tested the changes in this PR by manually changing the links in the checklist above. It works as expected :)

PULL_REQUEST_TEMPLATE.md: use more robust links

---

pages/common/sed.md

I think this example is useful here because it allows to **remove** matching lines from the output. Doing so with a replacement is more complicated as you need to enable multi-line matching and add a `\n` at the end of the pattern (or something like that).
A beginner intuition would be to do `sed 's/pattern\n//' filename`, and it would not work. Here the `sed '/{{line_pattern}}/d' {{filename}}` command is simple and easily memorized (delete -> d).
The example could be improved by one of the two following propositions:
1. Add `and print the result` at the end of the description (to emphasize it is not in-place modification)
2. Add the `-i` option and emphasize it will modify the file
Let me know what you think :slightly_smiling_face: !

sed: add example to delete lines

---

pages/common/drill.md

Add TL;DR page for a `drill` command from `ldns` package.

drill: add page

---

pages/common/monop.md

Following on from my previous 2 pages (#2557 and #2558), I went looking for a .NET assembly browser - and stumbled across this command :P
For my own reference, the Mono project have a [page](https://www.mono-project.com/docs/tools+libraries/tools/) dedicated to the tools that come bundled with `mono`.
----

monop: add page

---

pages/common/restic.md

I think it must be frequent that people only want to restore 1 file (or a specific path).

restic: add how to restore a specific file

---

pages/common/php-artisan.md

This adds a page for the command line interface for the popular PHP framework [Laravel](https://laravel.com/docs/master/artisan)
-----

php artisan: add page

---

pages/common/kubens.md

I have added `kubens`. An utility to switch between `kubectl` namespaces.

kubens: add page

---

pages/common/kubetail.md

I have add `kubetail` - a [bash script](https://github.com/johanhaleby/kubetail) that enables you to aggregate (tail/follow) logs from multiple kubernetes pods into one stream.

kubetail: add page

---

pages/linux/getent.md

Correction of a little typo for getent page

getent: correct typo in group example

---

pages/common/docker.md

This is the first of PRs that is attached to the raised issue #2592, reverting the changes of #1505 to the more common real-world suggested usage, with the intent to create further docker command specific pages. 
I'm not sure how you'd want to handle the fact that it has 9 examples though. You could probably merge the two run examples, but not sure how to specify an optional `{{command}}` parameter.

docker: simplify examples

---

README.md

I wrote a(nother) client in Go, that uses a database for performance and Go's cross compilation to support most platforms (providing only common pages on 'non-tldr platforms').
As far as I can see I support all required features (ie. page lookup and downloading the pages from <https://tldr.sh/assets/tldr.zip>).
If you think there is anything missing, please let me know. :slightly_smiling_face:

Add another Go client

---

pages/common/aws.md

We already have [`aws-s3`](https://github.com/tldr-pages/tldr/blob/master/pages/common/aws-s3.md) page, but I think there is need for a more general one like `aws`.

aws: add page

---

pages/linux/uprecords.md

With my fancy new bash command, I identified that we didn't have a page for this already. Although uprecords, by default, shows you the top 10 longest uptimes, it's actually really useful as it tracks _every_ reboot you've done, what your kernel version was, and how long you were down for. All it needs to make it perfect is a reason column......
Here's said bash command:
```bash
while read nextcmd; do tldr "${nextcmd}" >/dev/null 2>&1; if [[ $? -ne 0 ]]; then echo $nextcmd; fi done < <(history | awk '{print $2}' | sort | uniq | grep -iP '^[a-zA-Z0-9]+$')
```
It'll search your entire shell history and display a list of all the commands you've used that don't yet have a tldr page.

uprecords: add page

---

pages/common/elm.md

Update the Elm tldr to the most recent (0.19) version of Elm and add examples

elm: update page, add elm make example

---

pages/common/history.md
pages/common/id.md
pages/common/kill.md
pages/linux/brctl.md

---
- Add new page for the `brctl` linux command, a useful tool for creating and managing netwok ethernet interfaces.
- Add two examples for `id`:
- The most basic example: `id`
- An example showing how to check the id of a different user.
- Add one example for `history` on how to delete history entries.
- Add two examples for `kill` on how to work with multiple processes of the same group.
- Fixed a typo in the `kill` page:
```diff
- pause a program, it until
+ pause a program until
```

brctl: add page;  id, history, kill: add examples;  kill: fix a typo 

---

pages.pt-BR/common/ack.md
pages.pt-BR/common/airpaste.md
pages.pt-BR/common/apg.md
pages.pt-BR/common/apm.md
pages.pt-BR/common/az.md

Translated first five pages in Portuguese. 
I'm planning to translate more in the near future. 
Regarding the folder name: I have created the folder based on IETF language codes (BCP 47) as it was discussed on gitter. The link for the start of the discussion can be found [here](https://gitter.im/tldr-pages/tldr?at=5c37ceb383c7e377654cb4e4).
As this is my first contribution for this repository I would like to know if there is anything missing from my side. 
Thanks a lot.

Add Brazilian Portuguese translation for some common pages

---

pages/common/timeout.md

The second example mentioned SIGTERM as the default signal, but the first example was worded in a way that may have implied SIGKILL is sent by default.

timeout: clarify the default signal sent to the process

---

CONTRIBUTING.md

Added guidelines on how to contribute with new translations and clear specification of top level language specific directory names, [as previously agreed](https://gitter.im/tldr-pages/tldr/archives/2019/01/11).

Add contribution guidelines for translations.

---

pages/osx/split.md

osx does not have a `-n` option, but does have a `-p` option

split: remove split into n files, add split by pattern

---

pages/common/zpool.md

This command is used to add cache (L2ARC) devices to zpools

zpool: added zpool add {{pool_name}} cache

---

pages/linux/lastb.md

lastb: add page

---

pages/linux/xfce4-screenshooter.md

---
I decided to add 7 examples because I personally use each one of them regularly to take screenshots (mostly combined with `--delay`) and I feel like they are quite essential to know.
I use these commands as keyboard shortcuts, and I added the first one (option-less) just because it's the simplest, but I actually think it is very rarely used from command line. Would it be better to remove it?
Options not covered are:
- `--mouse`: to show the mouse pointer. You usually don't want your mouse in a screenshot.
- `--display`: to change display. You usually take a screenshot of the current display.
- `--upload`: to launch a GUI for uploading to ZimageZ (requires user/passw).
- `--imgur`: same for Imgur but no user/passw required.

xfce4-screenshooter: add page.

---

pages/common/chgrp.md

Fixed a typo and also clarified examples' descriptions to specify that the owner _group_, rather than _user_, is affected by the command. More like it is specified in `chown`.

chgrp: fix typo and clarify examples.

---

pages/linux/pathchk.md

---
Part of #2213.
Short options `-p` and `-P` don't have a `--long` counterpart.
<sup>whoops, mixed some italian translations by mistake haha, fixed</sup>

pathchk: add page

---

.travis.yml

The build dir is being silently cleaned, and the `index.json` script is not being built. This ends up silently not uploading `index.json` to the `tldr-pages/tlrd-pages.github.io` repo. See [here in this build log](https://travis-ci.org/tldr-pages/tldr/jobs/488514400#L546) for example.
Fixed by simply adding `skip_cleanup: true` in Travis' configuration. You can see [it works](https://travis-ci.org/mebeim/tldr/jobs/488522673#L528) and successfully generates the `index.json` on my fork.
I also added `on: repo: tldr-pages/tldr` to prevent unneeded deployment on forks if people want to enable TravisCI on their fork for testing purposes (like I just did on mine).

TravisCI: don't clean build dir needed for deployment.

---

pages/common/sn.md

Another mono-related page! This time, it's for `sn`, the Mono StrongNaming signing tool.

sn: add page

---

pages.pt-BR/windows/cls.md
pages.pt-BR/windows/cmd.md
pages.pt-BR/windows/dir.md
pages.pt-BR/windows/mkdir.md
pages.pt-BR/windows/print.md
pages.pt-BR/windows/type.md

Translated first six windows pages in Portuguese. 
List: 
cls.md
cmd.md
dir.md
mkdir.md
print.md
type.md

Translate first 6 windows pages in Brazilian Portuguese

---

pages.pt-BR/common/airpaste.md
pages.pt-BR/windows/dir.md

---
Fix two typos in `pt-BR` translations. Most probably caused by #2756.

airpaste, dir: fix typo.

---

pages/linux/tshark.md

Special thanks to @jvns for here inspiring post https://twitter.com/b0rk/status/1091733136935923717

tshark: add page

---

scripts/deploy.sh

As it can be seen in [this previous build](https://travis-ci.org/tldr-pages/tldr/jobs/488514400#L546): the [`deploy.sh`](https://github.com/tldr-pages/tldr/blob/master/scripts/deploy.sh) script was executing a command which failed, which was:
rebuild_index && echo "Rebuilding index done."
However the build did not fail as it should have, hiding the error and pushing an invalid empty `index.json` file to the site repo. This is something more dangerous than a failing build because it can go unnoticed. Fortunately I was looking at the build log and noticed it so I wrote #2752 to quickly fix and push a correct `index.json` to the site.
I did not understand why the build didn't fail until now. So what happened in that build? The `deploy.sh` script does `set -ev` at the beginning so it should …

Deploy: run all commands separately to avoid unnoticed errors.

---

.github/PULL_REQUEST_TEMPLATE.md
contributing-guides/style-guide.md
pages.it/common/7z.md
pages.it/common/7za.md
pages.it/common/7zr.md
pages/common/7z.md
pages/common/7za.md
pages/common/7zr.md
pages/common/ag.md
pages/common/asar.md
pages/common/chgrp.md
pages/common/chmod.md
pages/common/chown.md
pages/common/code.md
pages/common/cpio.md
pages/common/duplicity.md
pages/common/git-log.md
pages/common/hg-commit.md
pages/common/ln.md
pages/common/pdfunite.md
pages/common/rm.md
pages/common/rsync.md
pages/common/scp.md
pages/common/srm.md
pages/common/subl.md
pages/linux/chattr.md

This PR partially fixes the issues described in #2751; in particular, points 2 and 3 of the numbered list.
- Commit [`1b35d43`](https://github.com/mebeim/tldr/commit/1b35d4313c52d9dc67e662e78e90f61abba2b76b) addresses point 2:
> "directory" used in the example description, but "folder" used in the example code, or vice versa.
- Commit [`aa32f71`](https://github.com/mebeim/tldr/commit/aa32f718e524829fd72f6d9fb5c3659144815c22) addresses point 3: 
> descriptions saying "in a file or folder" and example code showing `path/to/file` instead of `path/to/file_or_folder`, as recommended by the [style guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/style-guide.md).
In addition to the above, "folder" becomes "directory" in both the [style …

Refactor: fix incorrect and/or inconsistent usage of the word "folder" (pt. 2,3)

---

pages.it/common/fmt.md
pages/common/fmt.md

`fmt` pages in English and Italian for  #2213.

fmt: add page and Italian translation

---

pages/common/rsync.md

rsync -r src/bar /dest
is different from 
rsync -r src/bar/ /dest
and it's hard to remember which is which.

rsync: add -r example with trailing backslash

---

pages/common/npm-why.md

Another day, another page on my continuing quest to have a page for every command in my shell history :P

npm-why: add page

---

pages/common/vdir.md

---
Another one from the GNU Coreutils (#2213).

vdir: add page

---

pages/common/flutter.md
pages/common/mpv.md
pages/linux/dmesg.md
pages/linux/run-mailcap.md
pages/osx/ditto.md
pages/osx/dmesg.md
pages/osx/launchctl.md
pages/osx/oathtool.md
pages/sunos/dmesg.md

Change Unicode characters to ASCII:
- non-breaking spaces (\xc2\xa0) to normal spaces (\x20)
- apostrophes (there are only 2 Unicode apostrophes, all others are already ASCII)
- hyphen (−) to minus (-)
- fix wording (STD‐OUT to "standard output")

multiple pages: change Unicode characters to ASCII

---

pages/linux/whiptail.md

I bring you `whiptail`, the default TUI dialog box command on most Debian-based systems. It should be installed by default, and you may have seen it when you update via `apt` in the terminal, asking you what you want to do if a configuration file got changed.
[source tutorial](http://xmodulo.com/create-dialog-boxes-interactive-shell-script.html)

whiptail: add page

---

pages/common/conda.md

When one uses `conda` and unload an environment with the `source deactivate` command, he receives the following message `DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.`

conda: source deactivate is deprecated

---

pages/common/npm.md

Updates and simplifies the npm page.
Specifically:
* Removes unnecessary `--save` flag (added by default in npm > 5).
* Adds an example that installs a package wihtout a version since thats a simpler case.
* Moves the global install example down the page since it's a more complicated case
* Switch to the longversion of global option (`--global`) instead of `-g` to comply with guidelines
* Simplified description of adding a dependency
* Switched from the terms "dependency" and "module" to "package" where possible since package is more idiomatic in this context.
* Removed `npm list --global` example to stay under 8 example limit

npm: remove unnecessary --save flag and simplify descriptions

---

pages/osx/netstat.md

When looking at #2841, I noticed that the `netstat` page was using single curly-braces for token syntax.

netstat: fix token naming and curly braces

---

pages/common/virtualenv.md

adds instructions for specifying different Python version with virtualenv
source: https://stackoverflow.com/a/1534343

virtualenv: add python version example

---

pages/common/rename.md

I encountered a display issue when looking at the `rename` page, whereby asterisks prefaced by backslashes (`\*`) were actually showing up to the end user like so:
```
$ tldr rename
rename
Renames multiple files.
- Rename files using a Perl Common Regular Expression (substitute 'foo' with 'bar' wherever found):
rename 's/foo/bar/' \*
- Dry-run - display which renames would occur without performing them:
rename -n 's/foo/bar/' \*
- Force renaming even if the operation would overwrite existing files:
rename -f 's/foo/bar/' \*
- Convert filenames to lower case (use -f in case-insensitive filesystems to prevent "already exists" errors):
rename 'y/A-Z/a-z/' \*
- Replace whitespace with underscores:
rename 's/\s+/_/g' \*
```
I'm assuming this is not the expected behavior, so this PR may fix …

rename: fix display issue

---

pages/common/column.md

column: fix typo

---

package.json
scripts/build-index.js
scripts/deploy.sh

The `index.json` file contains information about *all* the pages and *all* the languages, and it should be located at the top level of the ZIP file which is generated when deploying to tldr-pages.github.io, not inside the `/pages/` folder (which is for English pages only).
I updated the build and deploy scripts to produce a copy of said file and add it at the top of the generated `tldr.zip`. I did not however disable the generation of `/pages/index.json`, since some clients rely on this file. 
Since this is kind of an architectural change, if this is merged I will notify each client by creating an issue on its repository, and also create a new issue in this repo to track which clients are up to date with the change. Once they all are or we think enough time has passed, we can then close …

Update building of index.json to be at the top level of the generated ZIP

---

pages/common/pax.md

`pax` is a core util and think this tldr page would be useful for some. I included only one example, where pipes / I/O redirection is used, because this feature of `pax` is not needed in the basic use cases.

pax: add page

---

COMMUNITY-ROLES.md

Just small wording changes to make the progression steps' summaries more explicit and link better with each other (and with the contents of MAINTAINERS.md).
In particular, organization members are no longer conflated with the term "maintainer", which is more of an umbrella term covering all of the roles described here.

COMMUNITY-ROLES.md: tweak phrasing

---

pages/common/monodevelop.md

With my [new improved missing pages detector](https://gitlab.com/sbrl/bin/blob/master/tldr-missing-pages), I discovered we didn't have a page for Monodevelop O.o

monodevelop: add page

---

COMMUNITY-ROLES.md

Looks like every time we make role changes new wrinkles are found in the process description :)
In this case, #2874 was closed with no mention of MAINTAINERS.md needing an update ~~(it was actually done in #2746, but without a backlink to the issue)~~. Actually, my bad -- the update was not done after all, that was the older change from when he became a collaborator. More evidence that the process was missing steps :)
While on it, I also made some formatting changes and assorted adjustments to streamline the process. Here is the full list of changes:
- Use preformatted blocks for the message templates
(instead of quote blocks, which required escaping of markdown formatting,
yet still didn't prevent "smart" links from being rendered by github).
- Use a numbered list to make the role change …

COMMUNITY-ROLES: streamline the How-to section

---

COMMUNITY-ROLES.md

A quick follow-up to #2881, so that step 2 (which asks to wait for the message recipients to accept the proposal) actually matches what the template messages say.

COMMUNITY-ROLES: tweak template messages to provide an explicit choice

---

MAINTAINERS.md

Just added myself as collaborator on Maintainers.md
Closes #2899

MAINTAINERS.MD: Add @schneiderl as contributor

---

pages/common/trawl.md

I have added [trawl](https://github.com/robphoenix/trawl) - The package that does pretty printing network interface information to the console, much like `ifconfig/ipconfig/ip/ifdata`.

trawl: add page

---

pages/common/smartctl.md

There is a redirection on Wikipedia from `S.M.A.R.T` to `S.M.A.R.T.`, but it's nicer to get to `S.M.A.R.T.` directly.

smartctl: Fix link to Wikipedia

---

COMMUNITY-ROLES.md

Tweaking the template messages for role changes, per the discussion at #2898.

COMMUNITY-ROLES: remove mid-sentence line breaks

---

COMMUNITY-ROLES.md

Without wrapping in code spans using backticks, angle brackets are interpreted as HTML tags, and stripped out from the rendered version.
Hopefully this will be the last update in the recent series of changes to this page. (Maybe I should stop re-reading the page once the PRs are merged :P)

COMMUNITY-ROLES: fix usage of angle brackets

---

pages/common/jq.md

test with:
`echo '[1, 2, 2, 3, 4]' | jq 'unique | sort | reverse'`

jq: add 'combines multiple filters' example

---

pages/common/crystal.md

Fixed the language name in the page, which is "Crysatl" with a capital C, and also added a homepage link.

crystal: fix typos and add homepage

---

pages/common/cp.md

Fixes #2484 condensing the two similar examples into one with a longer and clearer description, as originally suggested by @waldyrious.

cp: clarify and condense similar examples

---

pages/linux/ss.md

I changed a "connected socket" example to a "listening" one. The next example is also about "connected" ones.

ss: add listening socket example

---

pages/linux/scriptreplay.md

scriptreplay: add page

---

pages/linux/silentcast.md

Although I mainly use [OBS](https://obsproject.com/) for my screen recording needs now (which also deserves its own page), silentcast is still a great program that deserves it's own page (hey, @colinkeenan!).

silentcast: add page

---

pages/common/cppcheck.md

https://github.com/tldr-pages/tldr/blob/0ec75ee9a21f53d0d366ec64ff653460accb5088/pages/common/cppcheck.md#L18-L20
I don't think the additional piping into `grep` is needed here, it just makes the example unnecessarily more complex: of course whenever there's a program that lists something it can be piped into `grep` to search for keywords, but that's not what the example should focus on IMHO. I'd propose to remove it, what do you guys think?

cppcheck: simplify example

---

pages/common/crontab.md

The fact that `{{path/to/script.sh}}` is used in all the jobs' examples gives the wrong impression that cron jobs have to be scripts, when they can actually be any command.
I edited the first two examples to use a more general `{{command_to_execute}}` token, and left the script in the last example, clarifying its description and the fact that the path must be absolute.

crontab: clarify and simplify job examples

---

pages/common/csc.md

Clarify that a resource does not have to be another `.cs` source file, but can be any kind of file. Also, the identifier following the resource name is not needed since it defaults to the embedded resource filename.

csc: clarify example

---

pages/osx/wifi-password.md

I have added [wifi-password](https://github.com/rauchg/wifi-password) - osx tool for getting wifi password.

wifi-password: add page

---

package.json

Note, this can probably be rebased and merged rather than squashing. 👍
-----
Due to the issues mentioned in PRs #2867 and #2868, I've created this new PR with the appropriate changes committed by Dependabot.
I was planning on updating [`markdownlint-cli`](https://npm.im/markdownlint-cli) to `v0.15.0` which is the latest, but it now actually enforces the tests (see the [Travis build failure](https://travis-ci.com/pxgamer/tldr/builds/109987111)) so it may be better to implement this with a future PR.

package.json: update dependencies

---

package.json

As part of #2960, I bumped `husky` from `0.11.3` to `1.3.1`. I didn't want to bump 2 major versions as there was a breaking change. Version `2.0.0` removes support for `Node 6`, but I'm not sure if we still would support Node 6 at all?
This PR updates `husky` to `v2.2.0`. I've also used a hat (minor) version indicator as `husky` is now stable and follows semver. I can always hardcode it to `2.2.0` if needed though.

package.json: update husky to v2.2.0

---

.markdownlintrc
package.json

As mentioned in #2960, this updates [`markdownlint-cli`](https://npm.im/markdownlint-cli) to `v0.15.0`.
The package now actually enforces the tests. The issue that arises from this is that there is a page [`pages/linux/whiptail.md:27`](https://github.com/pxgamer/tldr/blob/da2344c7a5e289b92aa3d767363bfba4afb67e67/pages/linux/whiptail.md) that has a line with **233** characters. Whereas we restrict pages to a max of **200** characters in our linting config.
This is mentioned in previous builds, but it won't be enforced when linting (the exit code is `0`). In the new versions, the exit code is `1`, so Travis CI fails to build.
To resolve this, we could cut down or remove the `Display a multiple-choice menu` example in `whiptail` (@sbrl?), or increase/remove the line length limit?

package.json: update markdownlint-cli to v0.15.0

---

pages.pt-BR/common/ab.md

ab: add Brazilian Portuguese translation

---

pages/common/ssh.md

Real domains should not be used as to alleviate bias and prevent people accidentally running commands against real sites.

ssh: Remove real domains to remain neutral

---

pages/common/diff.md

The current version of the page doesn't do a great job of explaining how the order of the arguments affect the output, this PR tries to remedy that by changing all instances of `{{file1}}` to `{{old_file}}` and all instances of `{{file2}}` to `{{new_file}}` as well as elaborating on the explanations for `diff {{old_file}} {{new_file}}` and `diff -r {{directory1}} {{directory2}}`.
`{{directory1}}` and `{{directory2}}` retain their old names since diffs between directories is a little different. With just the `-r` option it does list differences in files similar to when called with no options but a lot of differences in file structure is just showed as is, for example with output such as "Only in directory2: file1".
The examples themselves are great and left unchanged.

diff: clarified and elaborated examples

---

pages/common/transmission-remote.md

Some thoughts on this PR:
- The trickiest thing to figure out with this command is how to select torrents. The option -t is quite flexible. I tried to illustrate different ways in which -t can be used to select individual torrents, ranges such as torrent 1-10, combinations of the two as well as the option "all".
- If `{{hostname}}` isn't specified it's assumed to be localhost. I'd like to illustrate this somehow since a lot of people will be connecting to a local daemon, but I'm not sure how best to illustrate it without it looking like a mistake in the page.
- The order of the arguments when dealing with `-t` and `-a` is very important. This is made clear with `-t` I think, but less so for `-a`. For example in the first example if -a and -w are flipped the default download directory is …

transmission-remote: add page

---

MAINTAINERS.md

I have added @andrik & @Aracki as repository collaborators.
Closes #2988.

MAINTAINERS.md: Add @andrik & @Aracki as repos collaborators

---

pages/common/xo.md

Fix a typo ("gives" > "given"), and improve descriptions for clarity.
This is a follow-up of #2552.

xo: reword descriptions

---

README.md
pages/common/dig.md
pages/common/drill.md
pages/common/irssi.md
pages/common/salt.md
pages/common/socat.md

This PR proposes the standardization of domain examples in tldr-pages. 
As most pages already use example.com as example to domains I have decided to keep that and change only the pages that do not follow that.

multiple pages: standardize domain examples

---

pages/linux/lynis.md

Lynis is a brilliant security auditing tool that cacn give you tips on hardening your Linux installation.
Personally I don't think much to the suggestions for SSH (as it doesn't give reasons for some of it's claims, I've found [this](https://sshcheck.com/) to be useful for ssh, as is [this](https://github.com/imthenachoman/How-To-Secure-A-Linux-Server)), but it's great everywhere else.

lynis: add page

---

pages/common/column.md

The `-s` option only works if `-t` is passed as well (as the description indicates!)
And because of that, it should be shown after the `-t` example.

column: fix and reorder -s example

---

pages/common/atoum.md

As noticed in #3024, the URL should be HTTP, not HTTPS.

atoum: fix homepage URL

---

pages/linux/rtcwake.md

rtcwake: fix command typo

---

pages/common/f3probe.md

f3probe: add page

---

pages/common/dexter.md

I have added [dexter](https://github.com/gini/dexter/) - a helper tool for authenticating kubectl users with OpenID Connect.

dexter: add page

---

scripts/deploy.sh

see: https://github.com/koalaman/shellcheck/wiki/SC2006 and https://github.com/koalaman/shellcheck/wiki/SC2086

chore: fix use doublequotes and $(..) notation in deploy script

---

pages/common/rsync.md

Use `directory` instead of `folder`
Use paths in the form of `path/to/remote_directory` instead of `remote_directory_location`. This is also how similar tools (e.g. `scp`) refer to remote locations.

rsync: standardize verbiage and path styles

---

pages/linux/lslocks.md

lslocks: add page

---

pages/linux/xclip.md

The `-t image/png` argument is required to paste the image correctly in software such as GIMP.

xclip: add PNG image copying example

---

pages/common/git-stash.md

This PR replaces the deprecated method of stashing changes with a message (`git stash save`) with the new way (`git stash push -m <message>`).
From the git docs:
> This option is deprecated in favour of git stash push. It differs from
> "stash push" in that it cannot take pathspecs, and any non-option
> arguments form the message.

git-stash: replace deprecated git stash save

---

pages/common/git-commit.md

This command was missing, but it's very important one.

git commit: add example for committing specific files

---

pages/linux/do-release-upgrade.md

I was upgrading Ubuntu to v19.04 the other day, and naturally I checked to see if there was a tldr page for the upgrader :P

do-release-upgrade: add page

---

pages/common/sqlmap.md

Fixed broken `{{user_token}}` in second example missing closing brackets.

sqlmap: fix user token typo

---

pages/common/hyperfine.md

Missing brackets around a user token.

hyperfine: fix typo

---

pages/common/deluge-console.md
pages/common/deluged.md

After reading these these two Deluge pages more carefully while translating them, I feel like the description is a bit unclear: it should be more clearly stated that these are specifically for the Deluge BitTorrent client, and not any other client.

deluged, deluge-console: clarify description

---

pages/common/git-check-ignore.md

git-check-ignore: add page

---

pages/common/find.md

The information content of the page should be unchanged, but hopefully it's now easier to read
(and respects our length recommendations of 8 maximum examples).
The changes include:
- Make the `-mtime` example more intuitive, so it only needs to be shown once,
and combine the `-delete` option with the first (now only) `-mtime` example
(thus reducing the page size back to 8 examples)
- Fix a comma splice in the `-exec` example, and a missing "a" in the `-path` example
- Reorder the examples to provide a more consistent and intuitive sequence
(e.g. by introducing `-iname` in an earlier example, and moving the `-exec` command down)

find: various improvements

---

pages/linux/fstrim.md

While I suspect that *BSD variants support `fstrim` (does Solaris or macOS support too? I'm not sure), I'm unsure about other platforms.
This is `fstrim` that's part of `util-linux` on Ubuntu, but it appears to be common across most distributions with the same feature set.

fstrim: add page

---

pages/common/docker-containers.md

Replaced two strange [Unicode quotation mark](https://www.fileformat.info/info/unicode/char/2019/index.htm) characters with the correct ASCII apostrophe.

docker-containers: fix typo

---

README.md

Temporary patch while we wait for #3111 to be properly solved, since having a broken badge is just not useful.

README: remove broken file count badge

---

pages.it/common/astyle.md

Just noticed that the short description for the astyle Italian page is incorrect and strangely worded.

astyle: reword description

---

pages/common/git-revert.md

Hey guys! Found another one that's missing.
Thanks for all the work that's gone into this project, it's saved me hours of time digging through man pages looking for options.

git-revert: add page

---

pages/common/cat.md

Inspired by [this UnixToolTip tweet](https://twitter.com/UnixToolTip/status/1145733858970742786), and further informed by [this commandlinefu example](https://www.commandlinefu.com/commands/view/1637/view-non-printing-characters-with-cat).
See also [this Unix.SX answer](https://unix.stackexchange.com/a/522300/30336) for further background.

cat: add -v example

---

pages/linux/mimetype.md

Another day, another command from my tldr-missing-pages list. 1 down, 147 to go.....

mimetype: add page

---

pages/common/rbac-lookup.md

I have added [rbac-lookup](https://github.com/reactiveops/rbac-lookup) - a util tool for K8s RBAC by ReactiveOps guys.

rbac-lookup: add page

---

pages/common/hub.md

Hi! Thanks for such a great project!
I add `hub pr` usege for checkout someone created pull-request.
Cited from `hub` official readme https://hub.github.com/#maintainer
best,

hub: add hub pr usage for checkout someone created pull-request

---

pages/linux/cpulimit.md

`cpulimit` needs the special option `--` after its arguments if used to directly run a program as shown in the examples. I also added `arg1 arg2...` to the first one to show that the program can be run with its own arguments.

cpulimit: correct wrong examples

---

pages/common/bitcoin-cli.md

First draft at a page for `bitcoin-cli`.
Further documentation:
- [Manpage source](https://github.com/bitcoin/bitcoin/blob/v0.18.0/doc/man/bitcoin-cli.1)
- [Rendered manpage from Debian](https://manpages.debian.org/experimental/bitcoind/bitcoin-cli.1.en.html)
- [Code that produces the help messages](https://github.com/bitcoin/bitcoin/blob/v0.18.0/src/bitcoin-cli.cpp#L43-L58)

bitcoin-cli: add page

---

pages/linux/radeontop.md

I was looking for an alternative to the Nvidia GPU top program (I can't remember what it's called now) for my AMD Radeon card in my laptop, and I found this. It's quite handy! It's available in most distro repos.

radeontop: add page

---

pages/common/renice.md

This page has a very long description that would really read better splitted in two different lines.

renice: split description in two lines

---

.travis.yml
scripts/build.sh
scripts/deploy.sh

Fixes #3148.
I finally figured this out. After looking at the output of some failed builds, it seems that the build always crashes around ~1100 lines of output: for some reason Travis chokes on the very long output of `zip -r pages* ...`. The immediate fix for this was to add `-q` to make the `zip` command quiet. This also means there is no need to use `travis_retry` (or any sort of retry logic at all).
Other than this, as previously discussed in #3148 I also updated the build process to be more consistent. To summarize, the changes are the following:
1. Added `-q` to the `zip` command to create the archive.
2. Moved the actual building of the index and the archive from `deploy.sh` to a new `build.sh` script.
3. Added a `script:` step to `.travis.yml` to run `build.sh` after `npm test`. …

Travis: separate building from deployment

---

README.md

added a link to the vim client at https://github.com/wlemuel/vim-tldr

README: add Vim client

---

pages/common/pdflatex.md

pdflatex: add -output-directory example

---

pages/linux/vmware-checkvm.md

I've got a few VMWare virtual machines from my University, and I realised that they have the VMware guest tools installed, so I thought I'd play around with them a bit.
I even discovered a sweet hidden flag!

vmware-checkvm: add page

---

pages/common/git-grep.md

I have added `git grep` missing command which is very useful. [Source](https://stackoverflow.com/questions/7151311/using-git-how-could-i-search-for-a-string-across-all-branches)

git-grep: add new command

---

pages/linux/snapper.md

`-c config snapshot` doesn't work for me and can't find a reference... maybe the option changed.
`-c config create` does the job.
[openSUSE reference](https://en.opensuse.org/openSUSE:Snapper_Tutorial#Manually_Creating_A_Snapshot)
not sure about `-d` or `--description`
modified also the order of the things, this way it should be more straight forward, isn't it?

snapper: snapshot creation

---

pages/common/emacs.md

- Use the word "start" instead of "open" when launching emacs.
- Clarify exit example and keyboard shortcuts.

emacs: clarify examples

---

pages/common/mat2.md

I added a page for `mat2`. It is in `common` because it is available for GNU/Linux and OSX.
More information: <https://0xacab.org/jvoisin/mat2>

mat2: add page

---

pages/linux/feedreader.md

Feedreader is a GUI application for viewing RSS feeds.

feedreader: add page

---

pages/common/unalias.md

I created a page for `unalias`. It is cross-platform, so I included it in `common`.

unalias: add page

---

pages/common/enca.md

- Clarify and simplify examples' descriptions.
- Change the token `{{files(s)}}` to `{{file1 file2 ...}}` for consistency with other pages.

enca: clarify examples and fix tokens

---

pages/common/envsubst.md

Page description and last example were unclear. I also changed `output` to `output_file` and stdin to `stdin` for consistency with other pages.

envsubst: clarify examples and description

---

pages/linux/apt-add-repository.md

We have `add-apt-repository`, and now we have `apt-add-repository`.

apt-add-repository: add page

---

pages/common/mosquitto.md

I'm setting one of these up, and I find having a tldr page to hand really helpful. Stay tuned for another PR adding `mosquitto_passwd`.

mosquitto: add page

---

pages/common/mosquitto_passwd.md

Sadly no long options here :-/
Part of #3231.

mosquitto_passwd: add page

---

pages/common/xkill.md

There isn't much to write about it, but it may still be useful to document its "canceling" behavior :slightly_smiling_face:
PS: I added the page to the `common/` subdirectory, is this correct? Xorg can run on *BSDs after all.

xkill: add page

---

pages/common/git-switch.md

Part 1 of several from GitHub's blog post about git v2.23!
Original source: https://github.blog/2019-08-16-highlights-from-git-2-23/?utm_campaign=1565911976&utm_medium=social&utm_source=twitter&utm_content=1565911976

git-switch: add page

---

CLIENT-SPECIFICATION.md

As per the discussion in #3161, this PR adds a new required `--language` CLI argument to the spec. Once clients have good support for it, we may consider updating the tldr page for tldr (though we should be careful to mention there that pages are returned in the system language by default).
Ping @pepa65 ([tldr-bash-client](https://gitlab.com/pepa65/tldr-bash-client), has language support already), @elecprog ([elecprog/tldr](https://github.com/elecprog/tldr), also has language support), @felixonmars ([tldr-python-client](https://github.com/tldr-pages/tldr-python-client)), @agnivade ([tldr-node-client](https://github.com/tldr-pages/tldr-node-client)) - please feel free to @mention anyone else who maintains a client that I've missed (I'm probably missing a bunch).

Client spec v1.2: new --language flag, BCP47 to POSIX and other clarifications

---

pages/common/git-restore.md

git-restore: add page

---

pages/linux/nmcli.md

The way the command is shown in the tldr page currently will result in `Unknown parameter: {password}` because nmcli expects `{network name} password {password}` (with the literal word password in between).

nmcli: add password flag to command

---

pages/common/firefox.md

I noticed that we recently gained a page about firefox - which had been already merged by the time I got to it.
I also noticed that the syntax was out-of-date - recent versions of Firefox bring a much more powerful CLI that's even capable of taking headless screenshots!
This PR updates it to match the new syntax, and expands the page with some powerful new examples (which, when mixed together, mean you can take headless screenshots with Firefox whilst Firefox is already open :D)
I wanted to fit in setting the window width & height too, but was unsure how to do so.

firefox: expand & update syntax to version 60+

---

pages/common/singularity.md

Updating the examples to reflect two recent(ish) changes to singularity:
* Singularity 3.0 introduced a new file format, with a new standard file extension: `.sif`
* The new [Sylabs Cloud](https://cloud.sylabs.io/) service has arguably overtaken [Singularity Hub](https://singularity-hub.org/) as the primary remote repository for singularity images

singularity: update file formats, replace shub with scloud

---

pages/linux/lxc.md

`lxc init` does what the current description says, it creates a container. In contrast, `lxc launch` initializes and then immediately starts the container. Since the tldr guide follows with `lxc start` (which does not work on a "launched" container), I think it makes more sense to list `lxc init` here, especially since it's an under-documented, but desirable command.

lxc: change container creation command

---

pages/linux/mkfs.md

mkfs: add page

---

pages/linux/runuser.md

runuser: add page

---

pages/common/git-lfs.md

Just been setting up Git LFS, so I thought I'd contribute a page for it :-)

git lfs: add page

---

pages/common/expand.md

Thought the last command could be more useful with a concrete example instead of just `{{list}}`.

expand: clarify last command using a concrete example.

---

pages/common/exec.md

The `-c` example description was wrong, and two others were strangely worded.

exec: correct and clarify example descriptions.

---

pages.it/common/git-add.md
pages.it/common/git-am.md
pages.it/common/git-bisect.md
pages.it/common/git-blame.md
pages.it/common/git-branch.md
pages.it/common/git-check-ignore.md
pages.it/common/git-checkout.md
pages.it/common/git-cherry-pick.md
pages.it/common/git-clean.md
pages.it/common/git.md

git-commands: add Italian translations

---

pages/linux/xinput.md

I put disable before enable, because most distros have things enabled by default (for example, a touchscreen).

xinput: add disable/enable commands

---

README.md

The gianasista/tldr-viewer repo has not been updated in 4 years. The Google Play link does not resolve to a published app, so removing this bullet-point item.

Remove bullet for gianasista/tldr-viewer, an outdated project

---

README.md

I think this should probably be removed because it is no longer possible to install via `cargo install tldr` as the `tldr` crate has been [yanked from the crates.io package registry](https://crates.io/crates/tldr).

README: remove deprecated rust client

---

pages/common/tar.md

Dropped the examples for extraction of specific compressed archives, tar
has had autodetection of the compression for over two decades.
Removed the dashes. No versions of tar require them and all they do is
cost you POSIX compatibility. (POSIX tar did *not* allow for the
dashes.)

tar: simplify extraction examples

---

pages/common/fd.md
pages/common/gradle.md
pages/common/hugo.md
pages/common/ipfs.md
pages/common/nikto.md
pages/common/rg.md
pages/common/xsv.md

Hi
On multiple occasions ([1](https://github.com/tldr-pages/tldr/pull/3004#pullrequestreview-236040219) [2](https://github.com/tldr-pages/tldr/pull/3020#issuecomment-492260939) [3](https://github.com/tldr-pages/tldr/pull/1137#discussion_r85696118) ) I've seen us talking about omitting adjectives in our command descriptions. 
And, to be honest, it always bothered me a little. 
This PR rephrases a few pages to get rid of some adjectives that slipped in.
If this PR gets approved I intent to update other pages that also have adjectives on the descriptions.

multiple pages: rephrase without adjectives

---

pages/common/tar.md

As discussed in #3412 the tar page had mutliple file tokens written as `{{file1 file2 file3}}`, which would be more clear if it would be written as `{{file1}} {{file2}} {{file3}}`.
This pull request separates those file tokens.
I also checked all the other pages (on Windows I ran inside the `pages` folder: `findstr /d:common;linux;osx;sunos;windows /S "file1 file2 file3" *`. Looking for multiple file occurences) and only found that stow.md could be considered updating.
Output regarding stow.md:
``` 
stow.md:`stow --target={{path/to/target_directory}} {{file1 directory1 file2 directory2}}`
stow.md:`stow --delete --target={{path/to/target_directory}} {{file1 directory1 file2 directory2}}`
stow.md:`stow --simulate --target={{path/to/target_directory}} {{file1 directory1 file2 directory2}}` …
```

tar: update multiple file tokens

---

pages/common/pip3.md

I think `search` should definitely be there, as finding and confirming the correct package name (PyPI doesn't enforce naming conventions, so names are *wild*) is the first thing I do.
The `--user` flag also strikes me as important, as users won't want a system-wide installation in many cases. I don't know if my formatting fits the tldr style, not sure how to keep things brief and tidy looking. Feel free to edit it, in case you accept this PR.
Also, if the number of listed commands has become too high, I'd rather see something more niche go.

pip3: add search command, mention 'user' flag

---

pages.fr/common/awk.md
pages.fr/common/borg.md
pages.fr/common/cat.md
pages.fr/common/chmod.md
pages.fr/common/install.md
pages.fr/common/ls.md
pages.fr/common/ssh.md
pages.fr/common/wc.md

Fixed usage of spaces before the ":" character in existing French pages (as discussed in #3446), and fixed a few typos.

French punctuation and typos

---

pages/common/git-clone.md

This page had some wrong and also strangely worded examples. I corrected and reworded them.

git-clone: correct and reword examples.

---

pages/common/cargo.md

It gives the false impression that cargo build doesnt compile with multiple jobs in parallel. By default it actually uses one job per cpu core:
https://github.com/rust-lang/cargo/blob/b03182a8ff0117ffa1c426119ae2b5a418776bbd/src/cargo/core/compiler/build_config.rs#L90

cargo: Reword cargo build -j example

---

pages/linux/runcon.md

Per issue #2213, adding runcon

runcon: add page

---

pages.fr/common/wc.md

Just a typo, the page ends with `\n\n` instead of just `\n`.

wc (fr): remove additional trailing whitespace

---

pages/osx/spotify.md

The name of the project is [**sh**potify](https://github.com/hnarayanan/shpotify), whereas the command is called `spotify` (without the **h**). I took a look at [another page](https://github.com/tldr-pages/tldr/blob/8b87e5f8285fd5b9d06fea143745d10abfb57ed9/pages/common/rg.md) where the repository name doesn't match the command name and following the same convention, I named the markdown file the same as the executable and set the page's title to the project name.

spotify: add page

---

pages/common/rg.md

Use parentheses around the second sentence instead of a double dash.

rg: fix grammar

---

pages/common/docker-compose.md

add "--rmi all --volumes" parameters to docker-compose down command, in order to match with description (by default, docker-compose didn't remove volumes).
- [/ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ /] The page has 8 or fewer examples.
- [ /] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ /] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ /] The page description includes a link to documentation or a homepage (if applicable).

docker-compose: add --rmi all --volumes

---

pages/common/qcp.md
pages/common/qmv.md

Personal note:
- I add 2 commands at once because the interface is quite the similar, and they comes with `renameutils` package.
- `qmv` has 5 examples, while `qcp` has only 3 since the ability to copy directories do not work now.
- What I'm not sure the most is do these 2 commands should go to `linux/` instead of `common/`? On my Ubuntu I can just run `apt install renameutils` and done, but I don't know about OS X or Windows (or others). I see that there is a source code but I don't have other platform to compile and try it.

qmv, qcp: add page

---

pages/windows/findstr.md

added more useful examples and removed some old ones. fixes #3504

findstr: edit-page

---

pages/linux/debman.md

Yet another command that you wish you'd known about earlier. This one requires the `debian-goodies` package to be installed.

debman: add page

---

pages/linux/pidstat.md

pidstat: add page

---

pages/common/drush.md

It seems the page was written for Drupal 7 and some of these examples don't apply to Drupal 8.
(`drush dl` has been replaced by `composer`. `dis` and `cc all` are deprecated.)

drush: switch to Drupal 8 examples

---

pages/common/javadoc.md

javadoc: add page

---

pages/common/convert.md

Summary:
The current description only has appending pictures horizontally. It's
very common to append pictures vertically too.
Test:
The command about +append is correct. I tested it with
```
convert 1.png 2.png 3.png -append vertical.png
```
, which successfully combine the three pictures into one.
I'm not sure how to test this in tldr locally. I installed tldr on my
local machine with `brew install tldr`. If anyone can let me know
about it, I'd be happy to do it.

convert: add -append example

---

.gitignore
scripts/build-index.js

Previously they were stored separately in their own arrays.
This made them disconnected, and impossible to know if a page
belonged to which platform and language combination.

Correctly store language and platform mappings together

---

pages/common/hub.md

The current instructions don't match the actual behavior of the tool, since it [does not set up the alias by default](https://github.com/github/hub/issues/1791); that has to be done manually by the user (and by the way, doing so can result in unexpected behavior: https://github.com/github/hub/issues/153, https://github.com/github/hub/issues/1721, https://github.com/github/hub/issues/1778).

hub: fix instructions for aliasing the command

---

pages/common/stack.md

Three changes:
* project -> package change as that's what it's referred to in the haskell ecosystem.
* Also include the template_name parameter
* Removing the `stack install` usage as it's just a synonym for `stack build --copy-bins`. Also it doesn't actually install all the packages needed by a project as documented here. Also, this command's inclusion was considered a mistake by the stack team. So, I'm removing it to discourage the use.

stack: clarify command

---

pages/common/git-show.md

This is a handy option which I have to look up how to do every now and then — most recently when seeking old versions of the Homebrew formula for cmake in the context of #3598.

git-show: add example for showing file contents

---

pages/common/git-ls-tree.md
pages/common/git-rev-list.md
pages/common/git-rev-parse.md

git-ls-tree, git-rev-list, git-rev-parse: add pages

---

pages/common/magick.md

Ref #3653.
I've also updated the description, since I didn't get a chance to comment on it. `magick` is actually only available in ImageMagick v7+, which isn't yet available on Ubuntu (why? it's been out long enough).

magick: Fix title & add better description

---

pages.es/linux/lsb_release.md

lsb_release: add Spanish translation

---

LICENSE.md

This change has been a long time coming, but we can finally wrap up the long-running discussion at #1076!
This change is justified by the following:
1. The MIT license is appropriate for open source software, but the vast majority of content in this repository is open content prose;
2. The best-known licenses for open content text are the Creative Commons ones;
3. The Creative Commons license that most closely approximates the properties of the MIT license is CC-BY (Attribution) 4.0;
4. The community has voiced overall support for this change in #1076; 
5. The MIT license allows for relicensing content subject to it.
Note: The software part of this repository, i.e. the contents of the `scripts/` directory, remains under the MIT license.
Fixes #1076 (at long last! 🎉)

Change main license to CC-BY 4.0

---

LICENSE.md

Rework the markdown syntax used in the LICENSE file to emphasize the main license, and better separate the MIT license part.
This is a follow-up to #3687.

Reformat LICENSE file

---

pages/linux/stress.md

stress: add page

---

pages/linux/xinput.md

xinput: add disable and enable examples

---

pages/common/firefox.md

also added note that profile selection is not available on windows

firefox: add extra flag options

---

pages/common/cargo-doc.md

cargo-doc: add page

---

pages/linux/sinfo.md

Behold! I now have access to my University's resident HPC (or, as I like to call it, supercomputer :D). It uses Slurm - so naturally I wrote a page on it. Checking though, it looks like we already have one - but since it uses the short-form options I thought I could do slightly better.
My University uses Slurm 15.08.8 for reference.

sinfo: add link and improve examples

---

pages/linux/tic.md

tic: add page

---

pages/common/cpdf.md

Hi guys, this one is from #3689 I'll try to create other ones. As the cheat project allows more examples then we do, I decided to pick up what looks like the most common ones.

cpdf: add page

---

.editorconfig

Changes (in `.editorconfig`):
- Makefile section removed
- reason: Makefile not used
- `.md` trailing whitespace rule removed
- reason: it leaves possibility for needless trailing whitespaces, while having no use (it's not used for `<br>`, since all lines have to be short)

Trim .editorconfig

---

pages/common/qcp.md
pages/common/qmv.md

These changes are a follow-up to #3458. Besides the self-explanatory clarification changes, I also restored the fully-spelled `--recursive` option instead of `-R` (reverting the change discussed [here](https://github.com/tldr-pages/tldr/pull/3458#discussion_r337400925)), since the word "recursive" is not used in the example's description, so the single letter option's meaning isn't obvious (unlike the `-d` option which was changed from `--directory` following [this discussion](https://github.com/tldr-pages/tldr/pull/3458#discussion_r337399770)).
/cc @einverne and @neizod.

qcp, qmv: small tweaks

---

pages/common/bison.md

Used as part of the _Languages and Compilers_ module I did at University. Not to be confused with `yacc`, which is its predecessor.

bison: add page

---

pages/common/git-show.md

As the title says :)
Also reword two descriptions to avoid misleading people regarding when the commit hash is shown.

git-show: add example for --stat option

---

README.md

Ref #3723. We've actually discussed changing from OS X to macOS before - but we didn't change the platform name to avoid breaking clients.

README: OSX -> macOS

---

README.md

This tldr client written in Haskell is [available as a Debian package](https://packages.debian.org/sid/tldr) maintained by the Debian Haskell Group and Clint Adams, so it can be installed with the different commands Debian has to manage packages. The README already gives alternative installation instructions for some clients (one written in Go and one in Python).

Add extra installation instructions to clients which OS packaged versions

---

pages/linux/numlockx.md

To solve that really annoying problem where numlockx is always turned off when you boot Ubuntu (sorry wayland users, you'll have to keep looking).

numlockx: add page

---

scripts/send-to-bot.py

GitHub wraps text in comments even when a single newline is encountered. This caused @tldr-bot messages to be formatted like this:
> The [build](https://travis-ci.org/tldr-pages/tldr/builds/635578923)
> for this PR failed with the following error(s):
> ...
Which does not look good. They should instead be formatted like this:
> The [build](https://travis-ci.org/tldr-pages/tldr/builds/635578923) for this PR failed with the following error(s):
> ...
This PR removes the unneeded newlines in the script.

Fix tldr-bot messages

---

MAINTAINERS.md

I think my surnames weren't available in my GitHub profile when I was added as collaborator (#3691) and as an organization member (#3737), so I am in the list as "Iván". This PR address this change.

maintainers: add surnames to @ivanhercaz

---

pages/common/qr.md

I was surprised to see that `qr` doesn't have a page yet! It's a great little utility for quickly generating temporary qr codes on the terminal.

qr: add page

---

pages/common/tldr.md

Adds missing hyphon from tldr tldr example page: 
tldr {{git checkout}} should read 
tldr {{git-checkout}}

tldr: fix typo. 

---

pages.ko/common/docker-logs.md
pages/linux/losetup.md

read-only losetup and partscan are commonly used options in digital forensics. It is benefitial to know about '--partscan' as it sometimes gives other results then losetup and partprobe/kpartx, e.g. with BSD-style partitions.
]x] The page has 8 or fewer examples.
]x] The PR title conforms to the recommended templates.
]x] The page follows the content guidelines.

losetup: added example for --read-only and --partscan

---

pages/linux/mullvad.md

Information on the mullvad command line utility.

mullvad: add page

---

pages/common/youtube-dl.md

With this command the user can download the best audio and video separately. After it's done downloading, it will spawn ffmpeg to merge the two files together. Handy when downloading stuff from youtube as they host video and audio separate.

youtube-dl: add download the best audio+video

---

pages/linux/openrc.md
pages/linux/rc-service.md
pages/linux/rc-status.md
pages/linux/rc-update.md

I noticed that although we have pretty extensive pages for systemd and sysvinit, we don't yet have any have any pages for OpenRC.
This PR adds pages for the full suite of public-facing OpenRC commands.

openrc, rc-status, rc-service, rc-update: add pages

---

pages/common/mmls.md

Added explanation for mmls, a tool used in digital forensics to read partition tables of (mostly) image files.

mmls: add page

---

pages/common/git-flow.md

Hello, I'm a [git flow](https://github.com/nvie/gitflow) user and saw that it there is no page for it yet. My biggest concern is that it would live next to other standard git commands under `/common/git-` even though git flow is an extension to git and therefore its own thing.  Nonetheless in practice it extends the standard git cli.

git flow: add page

---

pages/common/initdb.md

initdb: Add new page for initdb

---

pages/linux/losetup.md

losetup: change order

---

pages.pt_BR/linux/top.md
pages/common/gist.md
pages/common/htpasswd.md
pages/common/last.md
pages/common/odps-auth.md
pages/common/sendmail.md
pages/linux/chage.md
pages/linux/htop.md
pages/linux/smbpasswd.md
pages/linux/top.md

This PR changes the token `user_name` to `username` in multiple files. 
**Why?**
To me `user_name` is just weird to read.
Also: Most pages use the token `username` so just to have it concise between pages.

multiple pages: change user_name to username

---

pages/linux/tree.md
pages/osx/tree.md

Ignoring of the specific directories is very important when you're going to print the tree of the repositories these days. 
I expected this information in `tldr` but didn't find it, so decided to add it.

tree: ignore specific directories

---

pages/linux/findfs.md

 findfs: add page

---

pages/common/gh.md

Sorry for the questions, this is my first pull request in this repository. Since it is a new command, which is supposed to be multi-platform, I placed into `common ` directory.

gh: add page

---

pages/linux/snap.md

I am surprised this isn't in here yet as it is one of the most important commands for a package manager. This is very different from updating all packages with `snap refresh`. You may be able to guess the syntax for updating one package if you know apt but the tldr pages are not about guessing.

snap: add update package

---

pages/common/vault.md

Really important one that was missing. I thought it was better to use `field_name` instead of already used in previous commands `value`.

vault: add command

---

pages/linux/zramctl.md

I wrote this page a long time ago, and I discovered that you can have a dynamic number of devices when configuring _zram_ if you `modprobe` it differently. This PR updates the `modprobe` examples to show this.
Note that the zram kernel module is _not_ loaded by default - and as such you _need_ to `modprobe` it first.

zramctl: improve module loading examples

---

pages/common/mysqldump.md

- always use `-p` for password
- use short hand syntax for restoring a database (like the one used for restoring all databases)

mysqldump: harmonize the examples

---

pages/linux/firewall-cmd.md

I do this a lot with my test servers - put an interface into trusted
zone. The syntax is a bit weird, therefore I always tend to dig in the
man page.
The patch also adds arbitrary port naming because the syntax is also a
bit weird and hard to remember. Cheers!

firewall-cmd: add zone change and arbitrary ports

---

README.md

Add link to albert plugin that utilises and displays TL;DR pages
https://raw.githubusercontent.com/bergercookie/awesome-albert-plugins/master/misc/tldr.gif

Add link to albert plugin

---

pages/linux/postfix.md

Postfix is an awesome and extremely lightweight MTA - just supremely complicated to configure :P
Note that there are a _ton_ of random extra commands that are post of the Postfix system:
```
SEE ALSO
Commands:
postalias(1), create/update/query alias database
postcat(1), examine Postfix queue file
postconf(1), Postfix configuration utility
postfix(1), Postfix control program
postfix-tls(1), Postfix TLS management
postkick(1), trigger Postfix daemon
postlock(1), Postfix-compatible locking
postlog(1), Postfix-compatible logging
postmap(1), Postfix lookup table manager
postmulti(1), Postfix multi-instance manager
postqueue(1), Postfix mail queue control
postsuper(1), Postfix housekeeping
mailq(1), Sendmail compatibility interface
newaliases(1), Sendmail compatibility interface
sendmail(1), …
```

postfix: add page

---

pages/linux/nmcli-connection.md
pages/linux/nmcli-device.md
pages/linux/nmcli.md

I know this expands the page up to maximum of 8 examples, but the
problem here is that NetworkManager is used both on clients (laptops,
PCs) mainly for WiFi connection management but also on servers to manage
ethernet, bond or VLAN connections.
It's one of the quite complex commands with lots of options, I
handpicked three new examples I struggle quite a lot: static IP
configurations for both IPv4 and IPv6. These options are inconsistent
(ip4 vs ipv4) and I always need to dig in the man page.
To hit the 8 examples limit, I propose to delete the last exapmle which
is IMHO rarely used (`ip` is preferred) and it renders the very similar
output as the very first example (the only difference is that it lists
unmanaged devices).
Cheers!

nmcli: add more server examples

---

pages/common/git-lfs.md

Oops! I accidentally committed this to master instead of opening a PR. Hopefully all should be fixed now, thanks to a sneaky ninja force-push.
Anyway, I've found this pair of commands extremely useful, as git lfs doesn't always like to automatically check out files.

git-lfs: add fetch and checkout subcommands

---

pages/common/godot.md

This also adds more information about the `-s` switch's requirements.

godot: update the `--export` example

---

pages/common/mysql.md
pages/common/mysqldump.md

Addressing [this comment thread](https://github.com/tldr-pages/tldr/pull/3835#pullrequestreview-371083122) in #3835.
This moves backup restore examples from `mysqldump` to `mysql` and also adds a reference to the latter in the description of the former.

mysqldump: move backup restore examples to the right page

---

pages/common/git-update-index.md

git-update-index: add page

---

pages/linux/trash.md

#3909 
Does not include the more complex and powerful pattern-matching command ex. `trash-rm '*.o'` for simplicity. Let me know if this should be included. We have room for one more example.

trash: add trash-rm examples

---

pages/common/qpdf.md

Running this command locally with actual files results in this error: `open --pages: No such file or directory`. [QPDF's manual seems to support my change](http://qpdf.sourceforge.net/files/qpdf-manual.html#ref.page-selection) as their documented example looks like this:
```sh
qpdf --collate --empty --pages a.pdf 1-5 b.pdf 6-4 c.pdf r1 -- out.pdf
```

qpdf: fix merge documentation

---

pages/linux/ip-address.md

We've needed subpages for the `ip` command for ages in my opinion, so with the current IRL situation affecting the world I thought I'd use this as a welcome distraction.
As it happens the man page has some quite helpful examples at the bottom - this page is a curation and adjustment thereof.
By doing `man ip` you can see a list of all the subcommands if you're interested.
Edit: it's probably worth knowing that `ip address` is actually really powerful - it's just not possible to demonstrate all the crazy stuff it lets you do in a single tldr page :P

ip address: add page

---

pages/common/git-add.md
pages/common/git-stage.md

git-stage: add page

---

pages/common/find.md

As mentioned in man page, should always enclose the pattern in quotes in order to protect it from expansion by the shell.

find: always enclose the pattern in quotes

---

CLIENT-SPECIFICATION.md
contributing-guides/style-guide.md

Makes titles consistent through the project.

Avoid title case

---

pages/common/youtube-dl.md

This adds examples for getting the list of available subtitle languages and downloading subtitles in a chosen language.
The page already had the maximum eight examples, so I removed two that I thought were far less important. The addition and removal are in separate commits in case you think that it would be better to break the no more than 8 rule.

youtube-dl: add subtitle options

---

CONTRIBUTING.md
README.md

This PR does two things:
1. Updates the outdated licensing section in `CONTRIBUTING.md` to include both CC and MIT
2. Changes license badges to show CC-BY-4.0 instead of `license not identifiable`

Update the LICENSE information

---

pages/osx/GetFileInfo.md

GetFileInfo: add page

---

pages/common/nomad.md

I'm putting together a Raspberry Pi cluster with the Hashicorp stack and a page for Nomad would be very useful :P
Note that while the `agent` subcommand is commonly used, in a 'proper' setup you would generally have Nomad running as a system service, and so you would generally not use it day-to-day. Furthermore, the only time you'd use it is when you're learning it - and the official getting started guide contains plenty of guidance in that department.

nomad: add page

---

pages/common/ssh-keyscan.md

Just discovered this whilst configuring my cluster.
Ref https://www.techrepublic.com/article/how-to-easily-add-an-ssh-fingerprint-to-your-knownhosts-file-in-linux/

ssh-keyscan: add known_hosts example

---

pages/common/git-subtree.md

git-subtree: add page

---

common/pages/git-help.md

Who knew that the `help` subcommand of `git` could be so useful?!
Of particular note is `git help --all`, which gives a complete list of all the subcommands built into git - include the most obscure ones available You can be sure that I'll be (eventually) making my way down that list!
Part 4 / 4 of this batch; for #3953

git-help: add page

---

CONTRIBUTING.md

The ability to add subcommands is not documented anywhere. This is my proposal for a documentation.
Closes #4003 (Although the issue is both about subcommands and the `go` command.)

Add subcommand section to contributing guidelines

---

pages/common/git-show-branch.md

Part 1 of 4, for #3953.
This is a pretty interesting command actually. A bit on the obscure side, but still interesting and probably useful all the same.
It's also pretty complicated (but not as complex as some of the ones I plan to do later - those will be heaps of fun - check out the PR for `git help`.....) - so I'm splitting these 4 up into separate PRs.

git-show-branch: add page

---

pages/linux/efibootbgr.md

As you might have already seen, I included a specific example on creating a new boot option. I believe that in this case It is simpler to understand it with an extra example (because of the weird fat \ instead of / and it is possible that adding the UEFI Shell as a Bootoption.

efibootmgr: add page

---

README.md

As I commented in #4032, I developed a new Elixir client for tldr-pages, although it is still in progress, it works fine at this moment and, as you can see in ivanhercaz/extldr#6, the main priority is to accomplish with the clients specification of tldr-pages. I am not going to extend much explaining the client and the aims, because there are already [open issues in the ExTldr repository](https://github.com/ivanhercaz/extldr/issues) and I explained practically everything in the issue mentioned at the beginning of this already long paragraph.
About this PR, three points about the changes I performed:
1. I rename the existing, but archived and apparently inactive, Elixir client.
2. I created a group of Elixir clients and then I added ExTldr.
3. I didn't specify instructions for ExTldr …

readme: add ExTldr client

---

pages/linux/dos2unix.md
pages/linux/mac2unix.md
pages/linux/unix2dos.md
pages/linux/unix2mac.md

dos2unix/unix2dos: add pages

---

pages/common/git-notes.md

In my continuing adventures to go where no tldr-pages author has gone before..... oops, I think that went a bit wrong.

git notes: add page

---

pages/common/julia.md

The link previously pointed to language's homepage, but not the REPL. @waldyrious @owenvoke  What do you think, is this link actually more useful?
I also added another example.

julia: add -E example, fix link

---

pages/linux/dnf.md

dnf: add and reorder examples

---

pages/common/df.md
pages/linux/lsblk.md

lsblk df: add exclude example

---

pages.fr/common/rsync.md

The command "TLDR_LANG=FR tldr rsync " results in the following error: Page common/rsync.md not properly linted!  Line 18
2nd character no space
This change solved this issue
- [X ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

Bugfix to correct linting error in french rsync tldr page

---

CONTRIBUTING.md
README.md

The stats showcased by this badge (from the [IsItMaintained](https://isitmaintained.com/) project) don't accurately represent the responsiveness of the tldr-pages project.
See the discussion at https://github.com/tldr-pages/tldr/pull/4084#discussion_r433465926 for context.

Remove issue-stats badge

---

pages/linux/wipefs.md

Hi,
Here's a PR adding an entry for Linux's [wipefs](https://manpages.ubuntu.com/manpages/bionic/man8/wipefs.8.html) command.

wipefs: add page

---

CONTRIBUTING.md
README.md

Just a few adjustments to the badges to use more appropriate colors:
- gitter: use a deep pink to match the platform's brand
- PRs merged: switch from yellow to green, to convey the intended positiveness
- license: switch from the dull grey to a move vivid blue

Tweak badge colors

---

pages/common/gpgv.md

Hi,
Here's a PR adding an entry for the [gpgv](https://manpages.ubuntu.com/manpages/bionic/man1/gpgv.1.html) command.

gpgv: add page

---

pages/common/gpgv.md

Hi, the arguments in the final example were the wrong way round.

gpgv: fix typo

---

pages/common/youtube-viewer.md

I have changed the example URL so instead of being a placeholder, it is in the correct format of a video ID (right amount of characters, right type of characters, etc.)

Update example URL in youtube-viewer page

---

pages/common/cloc.md

This might not be a very common option for large projects, but it's one I find myself looking for quite often when I want to get a feel for how large my source files are.

cloc: add --by-file example

---

.github/workflows/ci.yml

Fix check for "deploy" step of GitHub Actions CI (see #4125).
**Note**: please do a "squash merge" when merging.

CI: fix deployment branch check

---

pages/linux/htop.md

Added sorting option to htop command.
htop man: https://linux.die.net/man/1/htop
Issue: https://github.com/tldr-pages/tldr/issues/4133#issuecomment-651060960

htop: add sorting option

---

pages/common/vlc.md

- Exists
- Updating already existing page
- As of 29.06.2020 page has 4 examples, 5 with mine
- Concluded that it does follow these guidelines
- Already present

vlc: playing video from the web

---

pages.de/common/cut.md
pages.de/common/ffmpeg.md
pages.de/common/fish.md
pages.de/common/gpg.md
pages.de/common/less.md
pages.de/common/lolcat.md
pages.de/common/pass.md
pages.de/common/rev.md
pages.de/common/tar.md
pages.de/common/zsh.md

Translated 10 of the common pages to German.

German translations for common commands

---

pages/common/pdftk.md

The ellipsis character (U+2026) generates an encoding error in the web client (tldr.ostera.io): the UTF-8 input is interpreted as Latin-1, resulting in garbled output.

pdftk: Avoid non-ascii characters

---

pages/common/cp.md

I paste the text directly from the official `cp` manpage:
```
Historic versions of the cp utility had a -r option. This implementation supports that option;
however, its use is strongly discouraged, as it does not correctly copy special files, symbolic
links, or fifo's.
```

cp: replace -r with -R

---

pages/common/cmake.md

The "cmake -i" wizard mode is no longer supported.
Use the -D option to set cache values on the command line.
Use cmake-gui or ccmake for an interactive dialog.
```
The "cmake -i" wizard mode is no longer supported.
Use the -D option to set cache values on the command line.
Use cmake-gui or ccmake for an interactive dialog.
```

cmake: remove cmake -i example

---

pages.zh/osx/netstat.md
pages/osx/netstat.md

`netstat -c` is supported in Linux, but not in macOS.

netstat: remove inexistent option for MacOS

---

pages/common/newman.md

---
The examples are taken directly from https://github.com/postmanlabs/newman/.
Fixes #4181.

newman: add page

---

pages/osx/uptime.md

Added uptime.md to OSX platform since OSX doesn't support the arguments listed in common/uptime.md such as `--version`, `--pretty` and `--since`.

uptime: add page

---

pages/common/pg_restore.md

This is a handy command for listings contents of a dump file before applying it.
Feedback is welcome,
Thanks

pg_restore: add example for listing contents of a dump file

---

pages/common/jq.md

This example covers the functionality which `jq` provides to transform JSON input in to another JSON object. I've found this to be a common use case for `jq`.
This does bring the number of examples up to 9. In my experience this new example is a more common use case than the last two examples, so would propose that we remove one of those two.

jq: Add example for constructing new JSON object

---

pages/common/git-config.md

I've found this to be a pretty common thing to want to do, particularly if you want to edit multiple config values at once, or can't quite remember the name of the property you need to change.

git-config: add example for editing in default editor

---

pages/common/curl.md

Add curl -d {{'@filename'}} option. This is purely documented in curl man document but is very handy.

curl: explain -d example

---

pages/common/sd.md

In version 0.6.4 `-i` has been deprecated and is the default now. The previous behavior can be forced with the `-p` option.

sd: Remove option -i in favour of option -p

---

pages.es/common/git-diff.md
pages.it/common/git-diff.md
pages/common/git-diff.md

Closes #3753.
I removed the example I found the least useful. The last two are common use cases.

git-diff: remove 9th example

---

pages/common/cp.md
pages/linux/cp.md

I misunderstood `path/to/copy` as "the path of the file for this command to copy" instead of the correct meaning of "the path to place the new copy of the source file", so I thought making the text on this page more explicit could be helpful.

cp: replace ambiguous text

---

pages/common/plantuml.md

There was a space missing. Command didn't work without that space.

plantuml: fix space was missing

---

pages/common/jq.md

The jq example was missing an important `.` character. If a user tried to follow the example, they would have received an error from jq.

jq: fix jq syntax error

---

pages/common/git-apply.md

-------------------------
Edit by @sbrl: Part of #3953.

git-apply: add page

---

pages/common/grep.md

grep searches for regexp by default on Linux, and the '-F' switch is required for the exact string. 
Corrected by replacing `search_string` with `regexp`, or adding the mentioned switch.
Please review / confirm.

grep: regexp is used by default

---

pages/common/inkscape.md

`-e` is obsolete option.
Added an example for output the drawing area `-D`, which should be very helpful to know.
`--verb` could receive more than one verbs.

inkscape: fix obsolete option, add -D example

---

CONTRIBUTING.md

The `> More information: <url>` seems to be used repository-wide so i think it's a good idea to be placed in contributing.
- Invalid
- Invalid
- Invalid

CONTRIBUTING: Include homepage in example

---

pages/common/jq.md

From the latest [jq manual](https://stedolan.github.io/jq/manual/#Basicfilters), it's said that when `use '.[]' on an object, and it will return all the values of the object`, but not all key-value pairs from objects

jq: correct description of example

---

CLIENT-SPECIFICATION.md

This updates the specification to include a recommendation on exiting with a non-zero exit code in addition to showing an error message, which is helpful for scripts and things that may be consuming this tool.
---------------------
Edit by @sbrl: Fixes #4227

Client spec: require exiting with non-zero code on missing page

---

pages/common/git-send-email.md

git-send-email: add page

---

pages.it/common/ffmpeg.md
pages.it/common/man.md
pages.it/common/mount.md
pages.it/common/mpv.md
pages.it/common/sudo.md
pages.it/common/vim.md
pages.it/common/zsh.md

Italian translations for `ffmpeg`, `man`, `mount`, `mpv`, `sudo`, `zsh`. Also fixed a small typo in italian tldr page for `vim`.

6 translations to Italian + fixing a typo

---

pages/common/env.md

I had the question of whether or not I could set multiple variables before the command. I looked here first, but didn't' find it.

env: add multi var set example

---

pages/osx/brew.md

Change "formulas" to "formulae" because that is what's used in the rest of the page.
Another thing - are you gonna be changing the name "osx" to "macos" or something because Big Sur will no longer officially be OS _X_ (No longer version 10)

brew: use the term "formulae" for consistency

---

pages/common/tcpdump.md

I found this typo while trying to dump all non-SSH traffic and was hitting a syntax error.

tcpdump: fixed negation example

---

pages/common/svgo.md

I'm currently using svgo 1.3.2 which as of right now is the latest released version: https://github.com/svg/svgo/releases
The second command did not work and according to the help docs you need to specify `-o` to the output file, otherwise everything is treated as input files.
Without this change you will get an error like:
```
$ svgo email-03.svg email-03.min.svg
Error: Error: no such file or directory 'email-03.min.svg'.
```
Here's a link to the docs: https://github.com/svg/svgo#cli

svgo: add -o to second example

---

pages/common/git-update-ref.md

git-update-ref: add page

---

pages/common/git-bundle.md

git-bundle: add page

---

pages/common/cryfs.md
pages/common/df.md
pages/common/dfc.md
pages/common/fls.md
pages/common/ipfs.md
pages/linux/duperemove.md
pages/linux/edquota.md
pages/linux/lsattr.md
pages/osx/diskutil.md

In https://github.com/tldr-pages/tldr/pull/4379#discussion_r498534894 I mentioned making a PR to use "filesystem" consistently instead of "file system" in `df`. What I've done instead is do it for all occurrences I could find (which to my surprise also made me realise that I managed to miss 2 inside `dfc` after having said that I fixed it which is my bad).
I ran `grep -Hni "file system" */*` inside the pages directory to get a list of all files containing the words "file system" and those (with two exceptions) are the pages I've changed in this PR.
In [ipfs](https://github.com/tldr-pages/tldr/blame/master/pages/common/ipfs.md#L3) I left "Inter Planetary File System" as is as that's a name and is how its written in the [ipfs docs](https://docs.ipfs.io/).
And in [mount …

cryfs, df, dfc, fls, ipfs, duperemove, edquote, lsattr, diskutil: consistently use "filesystem"

---

pages/common/ocaml.md
pages/common/ocamlc.md
pages/common/ocamlfind.md
pages/common/ocamlopt.md

* New pages: ocamlopt (native code compiler), ocamlfind (library manager).
* New example for ocamlc: automatic module generation.
* Homepage links in all `ocaml*` pages.

ocaml*: add ocamlopt and ocamlfind and improve existing ocaml* pages.

---

pages/common/indent.md
pages/osx/indent.md

indent: add page

---

pages/common/git-describe.md

add a page for git describe command.
git describe is a command from the git scm software.
* [Let's document git](https://github.com/tldr-pages/tldr/issues/3953)

git-describe: add page

---

.github/workflows/ci.yml
scripts/check-pr.sh

By default, `actions/checkout@v2` only checks out the latest commit of the current branch. Unfortunately, this causes the `git diff` check in `check-pr.sh` to fail, as `master` branch isn't available.
This change checks out all commits of all branches, which allows `git diff` to work correctly.
Ideally, I'd like to use the `ref` setting of `actions/checkout@v2`, but that only supports a single ref so it's not possible to check out the PR branch _and_ `master` branch at the same time.

Checkout all branches in GitHub Actions
