pages/linux/login.md

login: add page

---

CLIENT-SPECIFICATION.md
pages.es/common/git-rebase.md
pages.es/common/git-rev-list.md
pages.es/common/git-revert.md
pages/common/git-rebase.md
pages/common/git-request-pull.md
pages/common/git-rev-list.md
pages/common/git-revert.md
pages/common/git-subtree.md
pages/common/gocryptfs.md

In an effort to promote more inclusive language, replacing the words master/slave where applicable (other than in the names of repository/branch links). [GitHub is changing the default branch name](https://github.com/github/renaming) from `master` to `main`, so these examples will be more accurate in the future with the new terminology.

(chore) replace master/slave with inclusive language

---

pages/common/basename.md

The previous description was wrong, because `basename {{path/to/directory/}}` does not return the non-directory portion of the specified path (which would be the empty string), but `directory`.

basename: change description and add directory example

---

pages/linux/fail2ban-client.md

Since I have only used `fail2ban-client` command in Linux systems, I have not placed in common. I have seen that `fail2ban-client` can be installed in Mac with [MacPorts](https://ports.macports.org/port/fail2ban/summary), but since Mac installation is not supported in [Wiki installation documentation page](https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually), I have just included it in `linux` directory.
Moreover, I have documented the main options I usually use, for example, to manage `nginx-http-auth` jail.
* [fail2ban commands](https://www.fail2ban.org/wiki/index.php/Commands)
* [GitHub repository](https://github.com/fail2ban/fail2ban/)
* [fail2ban-client(1) - Linux man page](https://linux.die.net/man/1/fail2ban-client)

fail2ban-client: add page

---

pages/linux/isosize.md

isosize: add page

---

pages/common/git-cherry.md

Requested in #3953.
----
Opened as a draft as (IMO) the language feels a bit awkward, and would welcome suggestions.

git-cherry: add page

---

pages/windows/scoop.md

_Please see below, I want to discuss which example should be removed or moved to it's own page._
Hello,
I've been using scoop for more than a year now and sometime I was beginning to wonder why my SSD, where `scoop` was installed, has been filling up so fast. At this time, I didn't know, that scoop doesn't automatically removes old versions of installed software. To do this you have to run the `scoop cleanup *` command manually. Just recently I discoverd, that by using the `-k` option, also the download cache of old software would be cleared. That's the reason why I think, it's worth adding this example. 
But there are now eight examples in this file. This is according to your guidelines not allowed. I would propose to move the two `bucket` commands into the separate file …

scoop: add cleanup example

---

pages.de/common/7z.md

The grammar of the german translation of 7z was not consistent.

7z: improve German translation

---

README.md

This PR is to fix the dead link for the Wikipedia article mentioned in the issue #4552 
Link changed from https://en.wikipedia.org/wiki/TL;DR to https://en.wikipedia.org/wiki/Wikipedia:Too_long;_didn%27t_read
Signed-off-by: Karthikeyan Vaithilingam <seenukarthi@gmail.com>
Fixes #4552

Fixes #4552

---

pages/windows/scoop-bucket.md

Hello,
this is the follow-up pull request for #4531.
I'm creating a new `scoop-bucket.md` page to keep the eight example limit on the `scoop.md` page. 
If you compare the two old bucket examples on the `scoop.md` page to this page, you may see that I've added three options.
1. I guess it's useful to see, which buckets you are currently using: `scoop bucket list`
2. I've had to split up the `scoop bucket add` command, because the syntax has changed.
If you want to add an unknown bucket, you have to set a name and a repository url.
3. To complete the lifecycle of buckets, there's also an example how to remove them.

scoop-bucket: add page

---

pages/linux/htpdate.md

Since I have only used `htpdate` command in Linux systems, I have not placed in common.
* [htpdate(8) - Linux man page](https://linux.die.net/man/8/htpdate)
* [Keene Enterprises :: Open Source :: HTP](http://www.rkeene.org/oss/htp/)
* [ntpdate(8) - Linux man page](https://linux.die.net/man/8/ntpdate)

htpdate: add page

---

pages/common/jupyter.md

Hello,
I've added the command that allows to export `.ipynb` into `html`, `markdown`, `pdf` and plain `script`.
According to the guidelines it should have gone under `jupyter-nbconvert.md` but I saw the file already contained similar commands and, IMHO, for a basic usage (purpose of the project), it should be good enough as it is now.
Would you suggest to split the command `jupyter` into chunks?
Thanks for the nice project!

jupyter: add nbconvert example

---

pages.fr/common/git-reset.md

This PR adds a French translation of the `git reset` command.

git-reset: add French translation

---

pages/common/aws-kinesis.md

aws-kinesis: add page

---

pages/common/git-replace.md
pages/linux/w.md

w command shows who is logged in and their processes.

git-replace, w: add pages

---

pages/linux/lslogins.md

lslogins: add page

---

pages/common/aws-ec2.md

aws-ec2: add page

---

pages/windows/azcopy.md

Missed token syntax on initial page creation.

azcopy: add missing token syntax

---

pages/linux/module.md

As a short summary, the module command allows for loading in different programs, or modules, into the user environment. This is useful in the case of HPC systems that may have numerous pieces of software that do not need to be loaded to run a job.

module: add page

---

pages/common/nodenv.md

I didn't notice an issue requesting `nodenv`, but went looking for other commonly used but missing commands. There is a tldr page for `rbenv` and other variants, but `nodenv` was conspicuously missing.

nodenv: add page

---

pages/linux/scontrol.md
pages/linux/sstat.md

sstat, scontrol: add page

---

pages.pt_BR/common/git-add.md
pages.pt_BR/common/git-mv.md
pages.pt_BR/common/git-remote.md
pages.pt_BR/common/git.md

Hello there :)
This is a first PR to create some basic git translation to Brazilian Portuguese. However, I found this translation quirk since in Brazil is very common to use neologisms when talking about git (e.g. "Eu vou **commitar**", "Precisa dar um **push**", ...). I believe the translation should keep those terms in English when applicable. Feedbacks? 
Thanks!
(cc @schneiderl)
---

git*: add pt_BR translation

---

pages/linux/asterisk.md

One of the pages requested in #3689. I've focused on commands used for managing a running server with SIP clients on `chan_sip` as these are used most frequently.

asterisk: add page

---

pages/common/elixir.md

Though the `elixir` command has multiple uses and purposes, the included examples are the simplest of them. This addresses the second half of #2680, and likely closes it.

elixir: add page

---

pages/linux/semanage.md

semanage: add page

---

pages/common/gdb.md

The current `--args` example is ambiguous, since it's not clear which program reads those given arguments, `gdb` itself or  `executable`. Fix that by adding a minor note.
---

gdb: disambiguate --args example

---

pages.es/common/gradle.md

Hello, I've added the translation in spanish for gralde page.
A note for spanish reviewers: Which is the rule that applies for spanish translation in verbs? I've readed some translations and some uses the "indicative" form and others "present simple". Some people comments in other pull requests and suggests to use the spanish present simple in every translation, but I could not found any rule

gradle: Add spanish translation

---

pages/common/gh-pr.md

https://github.com/tldr-pages/tldr/pull/4635 moved the main page to 8 examples, so I've created a new page for the subcommand pr by adding some commands that I use to manage PRs.
Ref: #4701

gh-pr: add page

---

pages/common/git-commit.md

`git commit -a ` amends (or, in a more simple way, "adds") current staged changes on the last commit. The way is currently written gives the impression that changes on the last commit will be deleted and replaced by those new changes.
I understand why this was written in this way, since in `git commit --help` there is:
```
--amend
Replace the tip of the current branch by creating a new commit. [...]
```   
But notice that "replace" here is referring to the commit, that will be replaced by a new commit that has the combination of changes of the old commit and the new added changes.
---

git-commit: clarify amend example

---

pages/common/youtube-dl.md

Adding quotation marks when specifying a URL is necessary, since youtube URLs almost always contain a question mark (?), which is usually interpreted by the shell as globbing.
Signed-off-by: Atrate <Atrate@protonmail.com>

youtube-dl: add quotation marks

---

pages/common/syncthing.md

I know this PR puts this page at 8 examples, but please consider adding it.  For those of us using Linux, this example can be set to auto-start upon login, removing the overhead of opening a web browser while other processes are starting up.  
Unfortunately, starting the daemon in the background is often not done by default in most distributions.

syncthing: add -no-browser example

---

README.md

I modified an existing Haskell client heavily in order to have the fastest tldr-client. It does pretty good, it's a bit faster than the fastest other client I could find [Tealdeer](https://github.com/dbrgn/tealdeer). 
It follows the minimum requirements. It also follows large parts of the full requirements for tldr-clients, though I still have to assess to what extend.
I'd also appreciate if you'd add it to your [Wiki](https://github.com/tldr-pages/tldr/wiki/tldr-pages-clients) :)

README: add fast-tldr Haskell client

---

pages.fr/common/bat.md

I have created a new page for the french language

bat: add french translation

---

pages/common/gh.md

correct some errors about gh issue view and gh pr view, due to api
changes.
add new example to cover all github process:
repo creation -> issue management -> pr management -> release management
After discussions, this PR is only for some fixes and we will create sub-commands to add some details for each gh commands.
This PR will now resolve:
change command order to keep a logic on the examples from cloning a
repo, to issue/ticket creation to PR management.
fix a mistake on the pr/issue view commands, due to an api change on the
gh command.

gh: change command order and fix a mistake on pr/issue view command

---

pages.it/linux/binwalk.md

Add italian translation for `binwalk` command. I've finally created the `linux` subfolder inside `pages.it`... hopefully this is just the start :)

binwalk: add Italian translation

---

pages.es/common/git-pr.md
pages/common/git-pr.md

git-pr: add more information link

---

pages/common/rsync.md

Hi 
To make more clear the documentation, I replaced [p](perms) with [P](progress).
Lowercase p and uppercase P have different meaning in rsync

rsync: fix example description

---

pages/common/gh-config.md

Add a new page for `gh config`
I could not figure out what does `--host` option do - neither does it say anywhere in the official documentation. If someone ever knew, it would be nice to fill that
Ref: #4701

gh-config: add page

---

pages/common/scrcpy.md

The `--serial` command is important to users who have more than one Android devices connected. Since each `scrcpy` command can only be able to mirror one device, they will need to specify the serial ID or the IP address of the connected device for mirroring.
The examples are taken straight from [scrcpy's README file](https://github.com/Genymobile/scrcpy#multi-devices), but you're welcome to replace `0123456789abcdef` to something more random, mimicking the actual device ID.

scrcpy: add --serial example

---

pages/common/openssl-dgst.md
pages/common/openssl-genpkey.md

Add two pages for openssl subcommands related to digital signatures.
* One to generate asymmetric keypairs
* One how to generate and verify signatures

openssl-dgst, openssl-genpkey: add page

---

pages/common/flutter.md

`flutter` page contained some examples that were pretty much useless and obvious, so I removed them, and added two other useful examples

flutter: remove useless examples and add release APK

---

pages/common/make.md

I find this option quite useful when I have to deal with poorly written Makefiles that do not define variables with `?=`.

make: add --environment-overrides example

---

pages.de/common/ssh-agent.md
pages.de/common/ssh-copy-id.md
pages.de/common/ssh-keygen.md
pages.de/common/ssh-keyscan.md
pages.de/common/ssh.md
pages.de/common/sshfs.md
pages.de/common/sshpass.md

Hello again!
I translated all the ssh pages into German.

ssh*: Add German translation

---

pages.de/linux/cfdisk.md
pages/linux/cfdisk.md

Add new page for the command `cfdisk`.
Part of #2214

cfdisk: add page

---

pages/common/openssl-req.md
pages/common/openssl-s_client.md
pages/common/openssl-x509.md
pages/common/openssl.md

The old openssl page contained examples for various subcommands. This violates the contribution guide and prohibits adding more examples. This PR splits all available commands into appropriate subpages, adds the correct examples for the main command.
It also uses the new existing space to add a few more examples.

openssl: add subcommand pages

---

pages/common/gh-issue.md

Add a new page for `gh issue`
Ref: #4701

gh-issue: add page

---

pages/common/redis-cli.md

Many Redis cloud services/hosting provider gives the connection info as a full URI, so an example on how to connect with that is nice to have

redis-cli: add URI connection example

---

pages/common/amass-db.md
pages/common/amass-enum.md
pages/common/amass-intel.md
pages/common/amass-track.md
pages/common/amass-viz.md
pages/common/amass.md
pages/common/httprobe.md
pages/common/sublist3r.md
pages/common/theHarvester.md

This PR adds several pentesting tools to tldr.

amass, httprobe, sublist3r, theHarvester: add page

---

pages/common/reflex.md

This pull request adds a page for [reflex](https://github.com/cespare/reflex), a populair tool to run arbitrary command when files change.

reflex: add page

---

pages/linux/yetris.md

yetris: add page

---

pages/common/gdalbuildvrt.md

gdalbuildvrt: add page

---

pages/common/vela.md

Note: Vela is a new-ish tool, but is being used an enterprise levels. The example command is the simplest format of the vela command that I have used so far to do a deploy, which is why it is the first & only example so far. The vela tool can be used for other purposes, which should eventually be put earlier, but I have not used them in my day to day.
Cheers

vela: add page

---

pages/common/tmux.md

Window management commands are important to correctly work with tmux. I replaced two redundant commands with two window management commands.
Please note I reverted the full command names used by @ryanolsonx. This is a subjective choice, but I think the shorter command names are sufficient to understand what they do and preferable to a `tldr` (people can check more information on the `man` page anyway). I can revert this specific commit if you prefer.

tmux: add window management commands and small improvements

---

pages/linux/asciiart.md

asciiart: add page

---

pages/common/docker-stats.md

docker-stats: add page

---

pages/common/bundle.md

I just added a very popular bundle command: `bundle exec`. Please check it!

bundle: add exec example

---

.github/workflows/ci.yml
scripts/deploy.sh

This adds PDF generation as a build step in the CI. It's currently only generating a Solarized Dark version, however we could upload a `tldr-book-dark.pdf` if we wanted to. 🤷🏻
You can view the  generated output on my test run here: https://github.com/owenvoke/tldr/runs/1462999918
And download the zipped build artifact containing the PDF here: https://github.com/owenvoke/tldr/suites/1570682479/artifacts/28298606
Personally I'm not sure a PDF is worth the wait time (3 minutes for that build step), which will only increase. But if people actually use it, then I guess this seems ok. The only other thing I'm not sure about is if multiple commits go to the master branch, which PDF would be uploaded last.
Closes #4969, and it would probably be good to wait until after #4993 is merged. 👍🏻

ci: add PDF generation to deployment

---

pages/common/openssl-genrsa.md
pages/common/openssl-prime.md
pages/common/openssl.md

Added two command for prime numbers. One generates a prime number, the other checks if given number is prime.
**Rational for exceeding 8 examples limit**:
I'm aware that this tldr page already has 8 examples, however all current examples are related to certificates. Direct generation of prime numbers using cryptographically secure methods is also a useful, even if it is just a niche function of openssl.

openssl-prime: add page

---

pages/common/etcdctl.md

Adds page for [etcdctl](https://etcd.io/docs/v3.4.0/dev-guide/interacting_v3/), the CLI for [etcd](https://etcd.io/).  Page for `etcd` coming soon!

etcdctl: add page

---

pages/common/conan.md

Adds page for [conan](https://conan.io/).  Eventually I will add separate pages for conan subcommands.

conan: add page

---

pages/common/scp.md

The `ssh` example shows how to connect to the remote host using a specific port (`-p`), and in the past I've been caught-out that specifying a port with `scp` uses `-P` instead.

scp: add -P example

---

pages/common/kubectl.md

https://github.com/tldr-pages/tldr/pull/4494 added `kubectl describe` help, but the main page still doesn't mention it. Add a note about its usage.
~~This is an important command, but it exceeds the suggested limit of 8 examples (do subcommands count as "examples"?). We could instead replace the `kubectl get` example with `kubectl {{get|describe}}`, but I'm really not a fan of that, since they're two different subcommands.~~

kubectl: add kubectl describe in header

---

pages/linux/lsblk.md

I generally find the output of lsblk presets to be lacking, and a customized output is very helpful, particularly as I've provided.

lsblk: add custom output example

---

COMMUNITY-ROLES.md

I recently noticed [this comment](https://github.com/tldr-pages/tldr-lint/pull/20#pullrequestreview-557006083) where a PR in the [tldr-lint](https://github.com/tldr-pages/tldr-lint) repository went unnoticed for a while because not enough people were watching it, and decided to add a line to the message template for adding new organization members, suggesting that they subscribe to all repositories in the organization.
I also took the opportunity to make additional edits to the messages, but those didn't make any substantial changes to the content.
In addition to this, we may want to consider implementing the stale bot in all our repos, to avoid such cases. It's important to give early feedback to avoid discouraging new contributors.

Improve role change message templates

---

pages/common/direnv.md

Second example for `direnv allow` should be `direnv edit` as per description

direnv: fix direnv edit example

---

pages/common/arc.md
pages/common/deemix.md
pages/common/eva.md
pages/common/fnm.md
pages/common/glow.md
pages/common/ipython.md
pages/common/kotlin.md
pages/common/nativefier.md
pages/common/notmuch.md
pages/common/virsh.md
pages/linux/efibootmgr.md
pages/linux/homeshick.md
pages/linux/netselect.md
pages/linux/rofi.md
pages/linux/vgs.md
pages/windows/choice.md

Changes split out from #5043. All credit to @owenvoke.

Fix syntax of "More information" links

---

pages/common/pip-install.md
pages/common/pip.md

The `pip` file has a lot of commands, and many of them are different kinds of installation. I broke them into a separate file to keep `pip.md` concise. Since `pip-install.md` now has some room, I also added the useful command for installing in editable mode.

pip-install: add page

---

pages/common/nc.md

This page edit is in its own PR, as I ended up making some more extensive modifications to it in addition to bringing it under the 8 example limit.
I argue that the send / receive a file examples a redundant, as it showcases existing shell functionality. The first 1 examples should cover these fine I think.
Part of #5046.

nc: improve grammar; bring under the 8 example limit

---

scripts/build.sh

Closes #2865.
Of the three clients listed that have not updated to use the new `index.json` location, two are essentially abandoned / dead, and I have opened a PR for [pepa65/tldr-bash-client](https://gitlab.com/pepa65/tldr-bash-client): https://gitlab.com/pepa65/tldr-bash-client/-/merge_requests/13
However, given that these clients have had a year and half to make this change, I think it's probably fair to make this change and remove the duplicate file.

remove duplicate pages/index.json file

---

MAINTAINERS.md

Fixes the link to Zlatan Vasović's profile from the old `@zdroid` that they used at some point in the past to their actual current profile @zlatanvasovic. The old name had been reclaimed by someone in December 2020.

MAINTAINERS: Fix link to @zlatanvasovic's GH profile

---

pages/osx/brew.md

This removes the cleanup example from the brew page. The [2.0 release](https://brew.sh/2019/02/02/homebrew-2.0.0/) back in Feb. 2019 made it so that cleanup is run automatically every 30 days, making manual usage of this command not really necessary for the casual user. Removing this example also brings this page to having only 8 examples as part of #5046.

brew: remove cleanup example

---

CLIENT-SPECIFICATION.md

Updates changelog section in `CLIENT-SPECIFICATION.md`:
* Link to PRs, don't just reference them
* Link to the most recent commit of the linked PR in the title

CLIENT-SPECIFICATION: fix changelog links

---

pages/common/uvicorn.md
pages/linux/flameshot.md

Fixes the title of this page so that it does not run afoul of the lint rule `TLDR014` which says to have no trailing spaces. This was caught in testing patch for tldr-lint (https://github.com/tldr-pages/tldr-lint/pull/31) to catch these sorts of lint errors.

flameshot: remove trailing space in title line

---

pages/common/uvicorn.md

Fixes the title of this page so that it does not run afoul of the lint rule `TLDR014` which says to have no trailing spaces. This was caught in testing patch for tldr-lint (https://github.com/tldr-pages/tldr-lint/pull/31) to catch these sorts of lint errors.

uvicorn: remove trailing space in title line

---

scripts/deploy.sh

This amends the commit message for the deploy from:
> `[GitHub Actions] uploaded assets after commit 0392bcf423708dca266ddd09e657c8b3950bbd99`
To: 
> `[GitHub Actions] uploaded assets after commit tldr-pages/tldr@0392bcf423708dca266ddd09e657c8b3950bbd99`
This allows the web UI to make use of GitHub's auto parsing of the text so that the second example would provide a hyperlink automatically back to the commit in question on GitHub's UI versus the first example which is always just plain text that the user then has to manually input into the URL bar (as well as getting the right prefix stem).

ci: add tldr-pages/tldr before commit hash for auto gh linking

---

pages/common/tar.md

tar: remove last example to reduce count to 8

---

pages.es/linux/brew.md
pages.it/osx/brew.md

Corrects `Github` to `GitHub` in Spanish and Italian `brew.md` translations.

brew: fix GitHub case in translations

---

pages/common/sort.md

---
This PR aims to add an example for redirecting the sorted output to a file. I especially like the ability to use the `--output` flag to modify a file in-place, replacing the contents with the sorted lines.
Maybe even using the shorter version `sort -o path/to/file path/to/file`, since `-o` is a common flag, but the long version follows the guidelines and is probably easier to understand.
However, the sort page already has 8 examples. My commit suggestion removes an example that in my opinion refers to a more specific usecase. The possibility to sort by a field is also outlined in the 7th example.
But of course this is open for discussion and i'm interested to hear your feedback!

sort: add output file example

---

pages/common/watson.md

Add [Watson](https://github.com/TailorDev/Watson) page.

watson: add page

---

pages/common/stolonctl.md

Per discussion in #5071, this updates the `stolonctl` page to have its title match the file name. I have updated the description here to include the `Stolon` reference and that the description now matches the first sentence in the README as well.

stolonctl: change page title to filename

---

pages/common/gpg.md
pages/common/gpg2.md

Fixes the page title of `gpg2` to match its filename, per #5071. I have also appended this page (and `gpg`) to include a link to the other page per @owenvoke's [comment](https://github.com/tldr-pages/tldr/issues/5071#issuecomment-753867840) in that issue.

gpg2: update page title to match file name

---

pages/linux/btrfs-filesystem.md

I'm setting up a new storage NAS, and I've decided to go with btrfs as the filesystem. To this end, I thought I'd contribute a series of tldr pages for btrfs, since it's rather like `docker` and `git` in that it's got a whole bunch of subcommands. I'm pretty familiar with them right now, so it's the best time to write those pages :P

btrfs-filesystem: add page

---

pages/linux/btrfs-scrub.md

btrfs-scrub: add page

---

pages/common/git-check-mailmap.md

git-check-mailmap: add page

---

pages/common/git-annotate.md

git-annotate: add page

---

pages/common/git-stripspace.md

git-stripspace: add page

---

pages.fr/common/git-pr.md
pages/common/hub.md

this pr renames "github" to "GitHub" as it is the official name of the service.

rename github to GitHub

---

pages/common/git-column.md

git-column: add page

---

pages/common/git-bugreport.md

git-bugreport: add page

---

pages/common/git-check-attr.md

git-check-attr: add page

---

pages/common/git-commit-tree.md

git-commit-tree: add page

---

pages.de/common/git-switch.md
pages.es/common/git-restore.md
pages.es/common/git-switch.md
pages.fr/common/git-ls-remote.md
pages.fr/common/git-restore.md
pages.fr/common/git-switch.md
pages.it/common/git-ls-remote.md
pages.it/common/git-restore.md
pages.it/common/git-switch.md
pages/common/git-ls-remote.md
pages/common/git-restore.md
pages/common/git-switch.md

`git-ls-remote` had an extra `.html`, and the others had a trailing `/` which git-scm.org [can't deal with 😄](https://git-scm.com/docs/git-restore/).

git-ls-remote, git-switch, git-restore: fix "More information" links

---

pages/osx/valet.md

Update the Laravel version in the link 5.8 → 8.x.
This is good for users' impression of tldr-pages, as they will see 8.x the latest version and think we're very up-to-date! 😄

valet: update more information link

---

pages/common/git-var.md

git-var: add page

---

pages/common/apktool.md
pages/common/croc.md
pages/common/dotnet-publish.md
pages/common/evil-winrm.md
pages/common/jekyll.md
pages/common/mpg321.md
pages/common/security-checker.md
pages/common/transmission-remote.md
pages/windows/replace.md

Changes "folder" to "directory" when appropriate.
The only ones I didn't change were:
- [`bw.md`](https://github.com/tldr-pages/tldr/blob/master/pages/common/bw.md)
- [`gdrive.md`](https://github.com/tldr-pages/tldr/blob/master/pages/common/gdrive.md)
- [`skicka.md`](https://github.com/tldr-pages/tldr/blob/master/pages/common/skicka.md)
- [`syncthing.md`](https://github.com/tldr-pages/tldr/blob/master/pages/common/syncthing.md)
...because "folder" seems more appropriate in those pages.
---

*: change folder to directory

---

pages/common/git-checkout-index.md

git-checkout-index: add page

---

pages/common/git-credential.md

git-credential: add page

---

pages/linux/lvresize.md

- In the positional arg, it's needed to specify the VG and LV name as in `VG/LV`. As so, add `{{volume_group}}/`.
- Add example to extend LV with `--size +`
- normalize use of extended parameter names (e.g. `--resizefs` instead of `-r`).
- Move shrink example to below extend examples.
- clarify in description it's operating in a logical volume.

lvresize: add vg to positional arg and example extend

---

pages/common/git-commit-graph.md

git-commit-graph: add page

---

pages/common/lambo-new.md
pages/common/lambo.md

lambo, lambo-new: add page

---

pages/common/promtool.md

promtool: add page

---

pages/linux/numactl.md

numactl: add page

---

pages/linux/btrfs-filesystem.md

Found & fixed a few issues in this page.
Particularly of note is that it's a **very bad idea** to defragment when you have a deduplication agent started. According to the documentation, it will really ruin your ~~day~~ week - and I don't want to find out lol :P

btrfs-filesystem: correct and improve

---

pages.zh/common/gpg-zip.md
pages.zh/common/gpg.md
pages.zh/common/gpg2.md
pages.zh/common/gpgv.md

Description: add gpg pages in pages.zh/common.
@ChungZH @KsRyY @whriedplanck

gpg*: add Chinese translation

---

contributing-guides/style-guide.md

This PR proposes a set of rules to use `backticks` in the command descriptions. Currently, it feels like there are no rules and there is no document to back us up in case we have any doubts on this. 
This goes along with #5119 as this sets the set of rules and #5119 implements them.
This is an only personal preference so I'm more than welcome to receive any feedback to add or remove anything from this set of rules.
I would especially like other's opinions about if we should or should not add two types of information to that list:
1. File types, ex. `JSON`
2. Addresses, ex. `localhost`, `123.456.789.1:3030`
What are your thoughts on this?

style-guide: add backticks guide

---

scripts/pdf/render.py

`tdlr-pages-to-PDF` → `tldr-pages-to-pdf` 😄

scripts/pdf/render.py: fix typo

---

pages.zh/common/rsync.md

rsync: add Chinese translation

---

pages/common/react-native.md

react-native: add page

---

pages/linux/rankmirrors.md

Note that I've used a concrete example of a filepath here, because that's where the mirrorlist is actually located (so it saves some effort on the part of the reader in locating their mirrorlist file).

rankmirrors: add page

---

pages/linux/genfstab.md

genfstab: add page

---

README.md

Added a reference to the PDF version at the start of the "How do I use it" section
Fixes #4975

README: add link to PDF version

---

COMMUNITY-ROLES.md

Fixes broken links in [COMMUNITY-ROLES.md](COMMUNITY-ROLES.md).  Mostly because in #3006 @waldyrious forgot to update it, when he modified `MAINTAINERS.md`.

COMMUNITY-ROLES: fix broken links

---

pages/linux/systemctl.md

Edit example description for Mask/Unmask to clarify meaning as per man page:
This is a stronger version of disable, since it prohibits all
kinds of activation of the unit, including enablement and manual
activation.

systemctl: improve mask/unmask example description

---

pages/common/z.md

Details:
---
* add the `-c` parameter to the [`z`](https://github.com/tldr-pages/tldr/blob/master/pages/common/z.md) command that enables user to go to a subdirectory of the current  directory

z:  add `-c` parameter to the command description

---

pages/linux/systemctl.md

Fix: https://github.com/tldr-pages/tldr/pull/5274#discussion_r579141281

systemctl: fix example description caps

---

pages/common/mutool.md

Add an example to print the table of contents in a PDF using the outline sub-command.

mutool: add outline example

---

pages/linux/arch-chroot.md

Source code for check functionality: https://git.archlinux.org/arch-install-scripts.git/tree/arch-chroot.in

arch-chroot: add page

---

README.md

README: add link to tldr.finzzz.net

---

pages/linux/lvextend.md

Added a line to indicate that lvextend is part of a larger toolset and to make sure that the page would be returned by "tldr -s lvm".
Added a more information link.

lvextend: expand description

---

pages/linux/pacman-mirrors.md

The man page and the Manjaro wiki state that it's necessary to run `sudo pacman -Syyu` after every run of `pacman-mirrors`. However I'm not sure if and where I should add that to the tldr page.

pacman-mirrors: add page

---

pages/common/if.md

Using `{{command}} && {{command1}} || {{command2}}` does not actually work like if. The difference is that in the above expression, command2 gets executed if command1 fails, which does not happen in a real if as in `if {{command}}; then {{command1}}; else {{command2}}; fi`

if: actually use if to test a command's success

---

pages/common/scp.md

So to use a specific port, the -P parameter comes first.

scp: fix -P example

---

pages.fr/common/git-add.md
pages.fr/common/git-flow.md
pages.fr/common/git-format-patch.md
pages.fr/common/git-show-ref.md
pages.fr/common/lua.md
pages.fr/common/mc.md

**(valid)** because `TLDR015` and `TLDR104`, which are found a lot on the French pages, don't apply to any language but English.

French pages: fix (valid) tldr-lint errors

---

pages/common/mscore.md
pages/common/musescore.md

There's also `mscore`, which is identical to `musescore`. Is the alias system already in place or should I just add a new seperate page?

musescore: add page

---

.github/workflows/mirror.yml

Adds a commit mirror from `master` to `main`. This begins the transition from one branch to the other, testing to make sure this works, so that once `main` becomes the primary branch, we are confident that the reverse (`main` -> `master`) will work. Once this PR is merged and set-up, I will create a similar PR in tldr-pages/tldr.github.io.
Note: This probably requires the `main` branch to be created, though I am not positive.
This follow discussion in #5110

ci: add 'master' to 'main' branch mirroring workflow

---

pages.de/common/awslogs.md
pages.de/common/borg.md
pages.de/common/convert.md
pages.de/common/cradle-install.md
pages.de/common/git-push.md
pages.de/common/tar.md
pages.de/linux/cfdisk.md

**(valid)** because `TLDR015` and `TLDR104`, which are found a lot on the German pages, don't apply to any language but English.

German pages: fix (valid) tldr-lint errors

---

pages.pt_BR/common/git-add.md
pages.pt_BR/common/git.md
pages.pt_BR/common/kill.md
pages.pt_BR/common/tar.md
pages.pt_BR/linux/apt-get.md

**(valid)** because `TLDR109`, which is only erroring on `eyeD3.md`, I would like to fix, along with other offenders of that rule, in a separate PR.

Portuguese (Brazil) pages: fix (valid) tldr-lint errors

---

pages.id/common/cd.md

**(valid)** because `TLDR015` and `TLDR104`, which are found a lot on the Indonesian pages, don't apply to any language but English.

Indonesian pages: fix (valid) tldr-lint errors

---

pages.ja/common/tldr.md

**(valid)** because `TLDR015` and `TLDR104`, which are found a lot on the Japanese pages, don't apply to any language but English, and Japanese/Chinese use their own punctuation, which currently `TLDR004` and `TLDR005` don't account for.

Japanese pages: fix (valid) tldr-lint errors

---

package-lock.json
package.json

Closes #5255
Closes #5071
Enables the following PRs to be merged:
#5205
#5088
---
This PR is waiting for the following pages to be corrected:
```
pages/common/R.md:0: TLDR109 File name should be lowercase
pages/common/theHarvester.md:0: TLDR109 File name should be lowercase
pages/linux/eyeD3.md:0: TLDR109 File name should be lowercase
pages/osx/GetFileInfo.md:0: TLDR109 File name should be lowercase
pages/osx/SafeEjectGPU.md:0: TLDR109 File name should be lowercase
pages/osx/csshX.md:0: TLDR109 File name should be lowercase
```
Checklist:

Bump tldr-lint to 0.0.10

---

README.md

`tealdeer` is available via Homebrew (https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/tealdeer.rb)

README: tealdeer is available via homebrew

---

pages/common/[.md
pages/common/test.md

The examples are reused from `test.md`.
`tldr-lint` would not let me use `[` as the page title.

test, [: add page, improve examples

---

pages.nl/windows/find.md
pages.nl/windows/shutdown.md

**(valid)** because `TLDR015` and `TLDR104`, which are found a lot on the Dutch pages, don't apply to any language but English.

Dutch pages: fix (valid) tldr-lint errors

---

CLIENT-SPECIFICATION.md

In preparation of landing tldr-lint@0.0.10 and resolving #5085 and #5255, I figured it would be good to add to the client specification about the lowercasing of file names as a transparent step to end users.

CLIENT-SPECIFICATION: add lowercasing of commands

---

pages/common/dig.md

I originally made a [pull request ](https://github.com/tldr-pages/tldr/pull/5413) for adding a new `dig.md` page. However, I was recommended to take the good parts in my  `dig.md` file and merge them in the file already existing in the `common` directory. 
I have added what I think are the good changes to the existing `dig.md` file. In my original pull request, I wrote an acronym for dig "Domain Information Groper", upon further research, I learned that it was [removed in 2017](https://en.wikipedia.org/wiki/Dig_(command)#History).  A lot of sources online still use the acronym, so I was conflicted as I was editing new changes. I settled on removing it.  
Am looking forward to hearing your thoughts on the new changes. Thank you in advance.

dig: add more examples

---

pages/linux/paru.md

Change "paru -P --stats", which no longer works, to a new, and also useful, example.

paru: replace -P example by 2 --getpkgbuild examples

---

pages/common/platformio.md

`platformio` is an alias of `pio` (#5404)

platformio: add alias page

---

pages/common/bshell.md
pages/common/bssh.md
pages/common/bvnc.md

This situation is actually a bit complicated. There is only one binary (`bssh`) and the other ones are just links to that one. The default behaviour of the command changes depending under which name it is called. Hower I couldn't just make two alias pages, since the arguments depend on the name it is called. I hope the way I did it is okay.

bssh, bvnc, bshell: add pages

---

MAINTAINERS.md

@jeeftor became a collaborator before @jsonbruce did.

MAINTAINERS: move @jeeftor to 1st position

---

pages.nl/common/yapf.md
pages/common/yapf.md

yapf: add page and Dutch translation

---

pages.es/common/git-diff.md

They were translated into Spanish, which is great, but they don't actually work, which might be an unpleasant surprise to the user.

git-diff: use English names for natural language dates in Spanish translation

---

CLIENT-SPECIFICATION.md

Sneaking in this tiny change to address #5184, before #5428 is merged. Fixes #5184.

Client specification: use HTTPS for archive links

---

pages/linux/mkfs.btrfs.md

You'll need this if you want to get started with btrfs - part of #5103.
Note that raid1 is actually misnomer in btrfs - it doesn't do whhat you think it does. In btrfs, you can have as many disks as you like (they don't even have to be the same size) in raid1 - all it means is that btrfs will keep 2 copies of every block of data on 2 different disks. Indeed, it's actually a smart idea to have 3 disks in raid1 - that way if 1 fails you don't end up with a degraded filesystem.
Note also that I'm not including raid5/6 examples here, because a bug in the current implementation causes data to be lost under obscure circumstances (it's not considered stable just yet).

mkfs.btrfs: add page

---

README.md

Earlier it pointed to melpa repo on github, which is not useful for someone trying to install the Emacs package.

README: link emacs client to melpa.org package

---

pages/common/pgbench.md

According to pgbench 13.2, on my MacOS computer, the right parameter name is `client`.
>   -c, --client=NUM         number of concurrent database clients (default: 1)
According to https://www.postgresql.org/docs/10/pgbench.html ; the right parameter is `client` too.

pgbench: fix typo in --client example

---

CLIENT-SPECIFICATION.md

This converts the links in the changelog of the client spec to point to version tags instead of commit hashes as suggested by @bl-ue in #5428, and also includes a maintainer note in the form of a comment for future reference when updating the changelog. 
I've already pushed the tags from v1.0 to v1.5, which should be visible to everyone [here](https://github.com/tldr-pages/tldr/tags).

Client specification: point changelog to tags, add maintainer note

---

pages.it/common/man.md
pages.pt_BR/common/man.md
pages.tr/common/man.md
pages/common/man.md

man: add more info link and --locale example

---

pages.fr/common/basename.md
pages.it/common/basename.md
pages/common/basename.md

Please consider merging this pull request.
Also, can someone explain me how can I add the "translation" label to the pull request in order to sort it better?

basename: update French translation

---

pages/common/grep.md

Inspired by #5216
I removed the stdin example so I could add the `-o` example, which I personally find very useful but less obvious.

grep: refresh

---

pages/common/less.md

I think we should use the official website because is header to find the a link to a man page.
Another option is the official repo: https://github.com/gwsw/less.
For #5510

less: add more information link

---

pages/common/pio-settings.md

Reference: https://github.com/tldr-pages/tldr/pull/5522#discussion_r602935938

pio-settings: fix typo

---

pages.de/common/echo.md
pages.fr/common/echo.md
pages.it/common/echo.md
pages.zh/common/echo.md
pages.zh_TW/common/echo.md
pages/common/echo.md

echo: add more information link

---

pages.fr/linux/a2disconf.md
pages.fr/linux/a2dismod.md
pages.fr/linux/a2dissite.md
pages.fr/linux/a2enconf.md
pages.fr/linux/a2enmod.md
pages.fr/linux/a2ensite.md
pages.fr/linux/a2query.md
pages.fr/linux/apache2ctl.md
pages/linux/a2disconf.md
pages/linux/a2dismod.md
pages/linux/a2dissite.md
pages/linux/a2enconf.md
pages/linux/a2enmod.md
pages/linux/a2ensite.md
pages/linux/apache2ctl.md

a2disconf, a2dismod, a2dissite, a2enconf, a2enmod, a2ensite, a2query, apache2ctl : add French translation

---

.gitattributes

tldr-pages is a mostly markdown repository, let's have GH detect markdown files as such.

Update .gitattributes to force GH linguist to recognize pages

---

pages/linux/pamac.md

pamac: add note about AUR packages in the command description

---

pages/common/espanso.md

espanso: add page

---

pages/linux/archinstall.md

I read the source code and I tested it in a VM but I couldn´t find any command line argument, only the guided/interactive mode.
I add this page because is a built-in command in the Arch Linux official ISO image <https://archlinux.org/news/installation-medium-with-installer/>.

archinstall: add page

---

pages/common/gist.md

gist: enhance list/update description

---

pages.nl/common/autopep8.md
pages/common/autopep8.md

autopep8: add page

---

pages.hbs/common/sha224sum.md
pages.hbs/common/sha256sum.md
pages.hbs/common/sha384sum.md
pages.hbs/common/sha512sum.md
pages/common/sha224sum.md
pages/common/sha256sum.md
pages/common/sha384sum.md
pages/common/sha512sum.md

sha*sum: add more information link

---

README.md

[Corresponding wiki update](https://github.com/tldr-pages/tldr/wiki/tldr-pages-clients/_compare/d45a8430c14897c810708049ea9c0d3aaa410ebd...da5004d61bf224226b84447421c8ae4a5e3991e9): https://github.com/tldr-pages/tldr/wiki/tldr-pages-clients/da5004d61bf224226b84447421c8ae4a5e3991e9
I'm compiling a list of clients' status based on the README list for #4044 (and #5240)

README: update clients' urls

---

pages/linux/compsize.md

2 pages in 1 day! Wow. This is almost part of #5103, but it's not actually a `btrfs` subcommand. Still, it's very useful if you're  trying to determine how effective compressing a file or directory was.

compsize: add page

---

pages/common/zip.md

From the `zip` man page: 
> The -sf show files option can be used to scan for files and get the list of files scanned without actually processing them.
I noticed that `zip` already has 8 examples, so adding this PR does not adhere to the Guidelines.
I'm proposing this change as listing files within an archive is quite common for me and `-sf` is quite obscure and require me to check the `man` page almost every time. TLDR is very useful in this regard and I think such a basic option should be present too. I'm not sure how cases like this are handled, so I created a Draft PR. If you consider this change acceptable I'll move this in ready for review, otherwise feel free to close this.
Thank you!

zip: add list files example and update first example

---

pages.it/common/cmark.md
pages/common/cmark.md

Inspired by [this discussion](https://github.com/tldr-pages/tldr/pull/5694#issuecomment-814006257) in #5694.

cmark: fix capitalization of "LaTeX"

---

pages/linux/sic.md

sic: add page

---

package.json

The recommended way to use husky with npm is to put the `husky install` line in the `prepare` run-script, not `postinstall`. This is principally aimed at libraries where using `postinstall` would affect downstream consumers (unless you used pinst to prune the `postinstall` line), but might as well be consistent here.

package.json: Move husky install to prepare run-script

---

MAINTAINERS.md

* Format all of the dates in the format '1 January 2021'
* Add @owenvoke and @mebeim to the collaborators section as emeritus
* Sort all entries by date
* Set all of the dates to the UTC date of the opening of the linked issue
* Minor wording adjustments

MAINTAINERS: normalize dates, reorder entries

---

pages/common/pio-device.md

pio-device: add page

---

pages/common/pio-package.md

pio-package: add page

---

pages/common/fakedata.md

fakedata: add page

---

pages/common/base64.md

Reading "Encode a file" made me worry that the command would edit the file inplace. Clarify that it prints the results instead.

base64: clarify example descriptions that do not edit files inplace

---

pages/common/docker-image.md

A few notes about this one:
- `docker image` ≠ `docker images`
- A number of subcommands of `docker image` have top-level counterparts (e.g. `docker image rm` has `docker rmi`), so I've focused on unique functionality of `docker image`

docker-image: add page

---

pages/linux/homectl.md

homectl: add page

---

pages.it/common/cowsay.md
pages.ko/common/cowsay.md
pages/common/cowsay.md

Fix commands that fail with `zsh` due to missing escaping for the exclamation mark:
$ cowsay -f dragon "Hello!"
dquote>
$ uname -a
Darwin **** 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
$ echo $SHELL
/bin/zsh
$ cowsay -h
cow{say,think} version 3.03, (c) 1999 Tony Monroe
Usage: cowsay [-bdgpstwy] [-h] [-e eyes] [-f cowfile]
[-l] [-n] [-T tongue] [-W wrapcolumn] [message]

cowsay: fix commands for zsh

---

pages/common/espanso.md

My bad, I introduced the wrong command in commit 46ae3bf76a2170ddf12ac508e1f71ec5b5cdbf41 (#5662). 😇
Before:
```sh
$ espanso config
error: Found argument 'config' which wasn't expected, or isn't valid in this context
USAGE:
espanso [FLAGS] [SUBCOMMAND]
For more information try --help
```
Now:
```sh
$ espanso edit config
Editing file: "/Users/nicolas/Library/Preferences/espanso/user/config.yml"
No file has been created, avoiding reload
```

espanso: fix "edit config" command

---

pages/common/ansible.md

Add example to list groups in an inventory.

ansible: add list groups in an inventory example

---

pages/common/ansible-inventory.md

ansible-inventory: add page

---

pages.de/common/ssh.md
pages.fr/common/ssh.md
pages/common/ssh.md

- Edit the [D]ynamic port forwarding example to not use [C]ompression, which is only recommended for slow connections and doesn't help the user perform the task as described.
- Change the port from 9999 to the standard SOCKS proxy port of 1080 to align with other examples.
---

ssh: remove -C and use SOCKS port

---

pages/common/gh-workflow.md

gh-workflow: add page

---

MAINTAINERS.md

MAINTAINERS: add @Waples to collaborators

---

pages.es/linux/groupdel.md
pages.es/linux/userdel.md
pages.fr/linux/useradd.md
pages.fr/linux/userdel.md
pages.fr/linux/usermod.md
pages.it/linux/adduser.md
pages.it/linux/deluser.md
pages.ko/linux/deluser.md
pages.pt_BR/linux/adduser.md
pages.zh/linux/adduser.md
pages/linux/adduser.md
pages/linux/deluser.md
pages/linux/groupadd.md
pages/linux/groupdel.md
pages/linux/groupmod.md
pages/linux/useradd.md
pages/linux/userdel.md
pages/linux/usermod.md

user*, group*, add*, group*: add more info links

---

pages/linux/pacman-files.md

Parameter --quite is almost certainly a typo. A correct form is --quiet.
This was tested before PR.

pacman-files: fix typo

---

pages.fr/common/atom.md
pages.fr/common/clear.md
pages.fr/common/convert.md
pages.fr/common/df.md
pages/common/df.md

Fix a few `fr` warnings from https://lukwebsforge.github.io/tldri18n/.

atom, clear, convert, df: sync French translations with English pages

---

pages.fr/common/ansible.md

Should fix a `fr` warning from https://lukwebsforge.github.io/tldri18n/.

ansible: sync French translation with English page (list groups)

---

pages/common/virt-install.md

Running the existing example (on Ubuntu 20.04) gives the error message:
ERROR    
--name is required

virt-install: add --name option to example

---

pages.fr/common/cp.md

Should fix a `fr` warning from https://lukwebsforge.github.io/tldri18n/.

cp: sync French translations with English page (remove "--parents")

---

pages/linux/tlp-stat.md
pages/linux/tlp.md

- The See also was not on the new line.
- The More information was missing - included manned.org.
Found out while investigating details regarding https://github.com/tldr-pages/tldr/pull/5821#discussion_r619425974

tlp, tlp-stat: fix description

---

pages/common/acme.sh.md

acme.sh: add page

---

pages/common/kate.md

Resolve open discussion in #5834

kate: improve remote document example

---

pages/common/passwd.md

passwd doesn't accept changing a password via specifying the password after the username in the command line, consider removing the example as it's misleading

passwd: remove invalid example

---

pages/windows/cinst.md
pages/windows/clist.md
pages/windows/cuninst.md

There's quite a few other aliases to `choco` subcommands, namely:
- `cpack` — CMake has a command called [`cpack`](https://cmake.org/cmake/help/v3.20/manual/cpack.1.html#manual:cpack(1))
- `cpush` — we don't have `choco push`
- `cup` — seems like there could easily be another command called `cup` and a page for this would override that for Windows users
- `cver` — we don't have `choco version`

cinst, cuninst, clist: add page

---

pages/linux/pkgfile.md

- Remove the invalid option as there is no  `--binary` option in the present version of pkgfile v21-2. 
- **EDIT:** add `--binaries` option instead
- Additionally, add `sbin` directory into the valid `--binaries` option to provide more precise description and reword that description slightly. 
- Change the More information link to the actual manual page.
- **EDIT:** include description in see also section.
- The change was tested before submitting.

pkgfile: fix example and update link

---

pages/common/virsh.md

The current example throws the following error:
error: failed to connect to the hypervisor
error: internal error: invalid URI qemu://system (maybe you want qemu:///system)

virsh: fix syntax of connect example

---

pages.nl/common/yes.md

The verb 'output' doesn't correctly translate to the Dutch verb 'uitvoeren'.
Uitvoeren means to execute something, which isn't what 'yes' does.
To avoid confusion about whether or not 'yes' prints the message to an actual
printer, or just the console, the description has also been altered slightly.

yes: change verb 'uitvoeren' to 'printen' in Dutch translation

---

pages/common/tar.md

Before this patch the document suggested that the `f` allows the user to list some files to extract or insert to the archive.
This patch fixes that: the `f` allows an archive file to be specified. Without it the archive would be read from or written to stdout.

tar: fix mnemonic for f

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml
.github/workflows/mirror.yml
CLIENT-SPECIFICATION.md
COMMUNITY-ROLES.md
CONTRIBUTING.md
LICENSE.md
MAINTAINERS.md
README.md
contributing-guides/style-guide.md
scripts/check-pr.sh

I think the other things we need to do is basically switch the default branch in the settings, and add a branch protection rule for `main` instead of `master`. As far as I know, pull requests to `master` should be automatically changed to `main` (🤞🏻).
Closes https://github.com/tldr-pages/tldr/issues/5110

feat: update to use main branch as default

---

pages/common/tar.md

Before this change, the `v` did not actually do anything since the `t` command already outputs the names of files in the archive.
It is more useful in a `c` or `x` command.

tar: add verbose argument to extract example

---

README.md

The shields.io badge for displaying a count of contributors has two variants: `contributors` and `contributors-anon`, as shown in https://shields.io/category/activity (click the demo "contributors" badge there to see the configuration modal).
Apparently the former only counts contributions (i.e. commits) whose author emails can be mapped to GitHub users. Other contributions are considered "anonymous" by GitHub. They are usually the result of either a misconfigured git installation, emails that haven't been added to the user's GitHub profile, or accounts that have been deleted or that changed their email address.
Since the project has always existed on GitHub from its inception, the anonymous count is closer to the real number, since all contributions would have come from GitHub pull …

README: tweak contributors badge

---

pages.pt_BR/common/[.md
pages.pt_BR/common/arduino-builder.md
pages.pt_BR/common/arduino.md
pages.pt_BR/common/bash.md
pages.pt_BR/common/clear.md

- [
- arduino-builder
- arduino
- bash
- clear
---

[, arduino-builder, arduino, bash, clear: add pt-BR translation

---

pages.pt_BR/common/git.md
pages.pt_BR/windows/choco-install.md
pages.pt_BR/windows/choco-source.md

Checking the repo we use `caminho/para` without `o/` or `os/`.

choco-install, choco-source, git: normalize 'caminho para' argument

---

pages/linux/mmcli.md

The 2 example commands are derived from the following documentation:
https://wiki.pine64.org/wiki/PinePhone_FAQ#SMS
Just thought it'd be nice to have quick access to them via tldr.

mmcli: add page

---

pages/common/git-rename-branch.md

git-rename-branch: add page

---

pages/common/kdeconnect-cli.md

For the link, we have <https://github.com/KDE/kdeconnect-kde/blob/master/cli/kdeconnect-cli.cpp> or <https://manned.org/kdeconnect-cli> and both are not ideal. (`manneg.org`, because it's completely outdated.)

kdeconnect-cli: add page

---

pages/common/aws-google-auth.md
pages/common/balena.md
pages/common/bosh.md
pages/common/firebase.md
pages/common/gcloud.md
pages/common/gh-auth.md
pages/common/gist.md
pages/common/heroku.md
pages/common/k6.md
pages/common/lpass.md
pages/common/molecule.md
pages/common/netlify.md
pages/common/oc.md
pages/common/packtpub.md
pages/common/pio-account.md
pages/common/rtv.md
pages/common/snyk.md
pages/common/youtube-viewer.md
pages/linux/login.md
pages/windows/azcopy.md

Login or logout, when used as a verb is incorrect (<https://grammarist.com/spelling/log-in-login/>).

change `login`/`logout` to `log in`/`log out`

---

pages/common/acme.sh-dns.md
pages/common/acme.sh.md

The wildcard went completely missing somewhere before the merge. In the original design, wildcard certificate usage was about to be referenced with a manual mode example. Running a manual mode with the current example would not produce a wildcard certificate because of the missing \*. subdomain. Furthermore, it would not do anything because a manual DNS mode requires a sort of confirmation command, more info acmesh-official/acme.sh#1029. Because of the many quirks of the various DNS modes, a separate subcommand page `acme.sh dns` was created.

acme.sh-dns: add page; acme.sh: remove example

---

README.md

https://tldr.ooops.me/ is broken, with an infinite redirect back to itself.

README: Remove tldr.ooops.me

---

pages/common/git-verify-commit.md

git-verify-commit: add page

---

pages/linux/dconf-write.md
pages/linux/dconf.md

dconf, dconf-write: add page

---

pages/common/aria2.md

Hi, due to the following issue: #5978 I have reformed aria2 just to be a pointer for aria2c
closes #5978

aria2: convert into page alias for aria2c

---

pages/common/git-authors.md

git-authors: add page

---

pages/common/rg.md

It's better to include a `--` prior to the search string so that strings starting with `--` (e.g. `--foo`) aren't processed as cli options.
https://github.com/BurntSushi/ripgrep/discussions/1560#discussioncomment-6346

rg: improved fixed string suggestion

---

MAINTAINERS.md

MAINTAINERS: add @SethFalco to collaborators

---

pages/common/gh-secret-set.md
pages/common/gh-secret.md

The `prompt` for the secret was added in the github-cli v1.10.0, I think the examples were invalid.

gh-secret-set: add page

---

pages/common/mv.md

I think this is an important feature of `mv` and it's not obvious from the examples that already existed on this page.

mv: add move multiple source paths to a directory example

---

pages/linux/screenkey.md

screenkey: add page

---

pages/common/pio-remote.md

For #5517
I'm not sure about the capitalization of `Remote Development` and `Remote Agent`. At least that's how the official docs do it.

pio-remote: add page

---

pages/common/git-authors.md

I re-check the command and don't `replace` the file, only append. Also, if you run the command twice, the authors appears twice.

git-authors: fix example descriptions

---

pages/common/git-extras.md

git-extras: add page

---

pages/common/conda.md

Bumped the python version to remove the deprecated `2.7`.
`conda deactivate` does not accept arguments.

conda: fix examples

---

pages/linux/snap.md

Sadly, tldr didn't tell me how to change an application I already had installed to another channel. :c
Figured since there is space for it, it'd be nice to add.
Referenced the snap docs:
https://snapcraft.io/docs/channels
This command allows a user to change the channel that an already installed package is on. For example, latest/stable → latest/beta or vice versa.

snap: add example to update to another channel

---

pages/common/git-range-diff.md

Helpful SO link for reference:
https://stackoverflow.com/questions/52323008/can-somebody-explain-the-usage-of-git-range-diff

git-range-diff: add page

---

pages/common/git-info.md

git-info: add page

---

pages/common/git-setup.md

git-setup: add page

---

pages/common/git-contrib.md

git-contrib: add page

---

pages.fr/common/ln.md
pages.it/common/ln.md
pages/common/ln.md

When running `ln -s path1/file path2/symlink`, while in `path3` you'd expect it to create a symlink `path2/symlink`, which points to `path3/path1/file`. However the symlink points to `path2/path1/file`, so the base for the relative path of the file is actually the directory of the symlink and not the directory this was executed from. The easiest solution is to just specify an absolute path to the file.

ln: convert paths to absolute and fix typo in Italian page

---

pages/linux/qtchooser.md

This one was kind of annoying. 🤔 
The man pages and help document different commands, and have contradicting arguments.
* In the man pages it documents `qtchooser -print-env [-qt=version]`, but I don't think one can use the `-qt` argument with `-print-env`.
* The man pages doesn't document the `-install` argument, but it's available in help and works as well.
What's preferred, using the official source repository, or manned?
* https://github.com/qtproject/qtsdk-qtchooser
* https://manned.org/qtchooser

qtchooser: add page

---

pages/common/git-rename-tag.md

For #5137 
See #5950 for what I based this on

git-rename-tag: add page #6092

---

pages/common/git-release.md

For #5137 
This PR and command is cursed, it has coursed me nothing but trouble, I accidentally made a tag on tldr rather than my test repo. 
I had to rebase for the first time because of a commit between a good one and another good one

git-release: add page

---

pages/common/git-summary.md

git-summary: add page

---

pages/linux/pacman.md

For me personally the command I have removed seems a little less important compared to the command I have added.

pacman: use long arguments and replace -Qo example

---

pages/osx/readlink.md

on MacOS `readlink -f` doesn't work, so I copied `readlink.md` to /pages/osx and removed the `-f` option.

readlink: add page

---

pages/common/git-obliterate.md

I haven't tested this command so if anyone would like to double check, please do.
#5137

git-obliterate: add page

---

pages/common/git-daemon.md

git-daemon: add page

---

pages.fr/common/pip3.md
pages.id/common/pip3.md
pages/common/pip3.md

```bash
Install Options:
-r, --requirement <file>    Install from the given requirements file. This option can be used multiple times.
```
It's `--requirement`, not `--requirements`!

pip3: fix argument spelling

---

pages/common/aws-secretsmanager.md

aws-secretsmanager: add page

---

pages/common/git-missing.md

git-missing: add page

---

pages/common/kdeconnect-cli.md

---
- add share file/url
- remove redundant pair
- copyedit

kdeconnect-cli: add share file/url; remove redundant pair; copyedit

---

pages/common/git-rename-remote.md

For #5137 
I couldn't find any more use cases for this command, if you can, please suggest them

git-rename-remote: add page

---

pages/linux/mklost+found.md

Never seen or used the command, and it maybe could be an arch exclusive since I have never seen it on Debian based.
Unaware on how useful it really is since fsck will make one every boot anyway

mklost+found: add page

---

pages/common/aws-ecr.md

aws-ecr: add page

---

pages/common/docker-login.md

docker-login: add page

---

pages/common/aws-s3api.md

aws-s3api: add page

---

pages/common/aws-cur.md

aws-cur: add page

---

pages/common/docker-build.md

More information: https://docs.docker.com/engine/reference/commandline/build/#text-files
This builds an image from stdin, which allows us to build an image with no build context.

docker-build: add example with docker from stdin

---

pages/common/git-verify-tag.md

git-verify-tag: add page

---

pages/common/history.md

This page also has an `es` and `pt_PT` translation, which also should be updated now, since we'll probably never see if there's a difference in a command description.

history: add note for zsh

---

pages.de/common/gcc.md
pages.pt_BR/common/gcc.md
pages/common/gcc.md

gcc: add long flag

---

pages/common/git-show-tree.md

git-show-tree: add page

---

pages/common/gpg.md

gpg: add --full-generate-key example

---

pages.zh_TW/common/bash.md

bash: add traditional Chinese translation

---

pages.es/common/bc.md
pages.es/common/figlet.md

bc, figlet: add Spanish translation

---

pages/common/restic.md

Using long arguments in examples increases verbosity. The `-r` argument
can mean multiple things, the most common being _recursive_, which is
not what it means under `restic init`.

restic: replace -r by long argument --repo 

---

pages/linux/ffuf.md
pages/linux/fuff.md

Request to add FUFF.md to TLDR
Ran .md against tldr-lint , changed EOL from WIN to UNIX, No other error on re-run.
Cheers

ffuf: add page

---

pages/common/az-vm.md

az-vm: add page

---

pages/common/restic.md

The restore command, at least as of the current stable version v0.12.0
requires --target to specify where the restored data should go. With the
urrent command here, meaning without the --target, there is this error:
> Fatal: more than one snapshot ID specified
I have also included a latest word that automatically picks the latest
tag without needing the actual snapshot ID.

restic: fix restore example

---

pages.de/common/git-commit.md
pages/common/git-commit.md

If nothing changes, we probably should do a rebase for this one.

git-commit: add gpg-sign example and sync German translation

---

pages/common/gunzip.md

Add option to keep original files
Quicker than `gunzip -c {{archive.tar.gz}} > {{archive.tar}}`

gunzip: add command to keep original files

---

pages/common/git-abort.md

git-abort: add page

---

pages/linux/fdisk.md

fdisk is a crucial disk editing command, which is key for setting up Arch Linux for example.
However it is not documented very well and is a useful command itself when things like GParted aren't available because someone doesn't have a desktop 
My edits will need a little help

fdisk: refresh

---

pages.es/common/gradle.md
pages/common/gradle.md

`assembleDebug` and `assembleRelease` tasks are specific to Android Studio:
https://developer.android.com/studio/build/building-cmdline#ReleaseMode
https://stackoverflow.com/questions/44185165/what-are-the-differences-between-gradle-assemble-and-gradle-build-tasks
They are not common tasks like `build`, `assemble` and `check`:
https://docs.gradle.org/current/userguide/command_line_interface.html#sec:command_line_executing_tasks

gradle: edit assembleRelease example to show Android Studio specificity

---

pages/common/htop.md

htop command uses `--user` instead of `--username`. 
Here is output from `htop --help` command:
```
htop 2.2.0 - (C) 2004-2019 Hisham Muhammad
Released under the GNU GPL.
-C --no-color               Use a monochrome color scheme
-d --delay=DELAY            Set the delay between updates, in tenths of seconds
-h --help                   Print this help screen
-s --sort-key=COLUMN        Sort by COLUMN (try --sort-key=help for a list)
-t --tree                   Show the tree view by default
-u --user=USERNAME          Show only processes of a given user
-p --pid=PID,[,PID,PID...]  Show only the given PIDs
-v --version                Print version info
Long options may be passed with a single dash.
Press F1 inside htop for online help.
See 'man htop' for more information.
```

wrong parameter in htop

---

pages/common/figlet.md

figlet: fix typo in example description

---

pages/common/yacas.md

The primary function of this command is to start a read-eval-print-loop console session to evaluate math statements.
I have taken a guess at a tldr format for the console session examples by saying "In the console session, ..." and by including the "In>" and "Out>" prompts. Please suggest something better.
The last sample is POSIX plumbing to evaluate a yacas statement at the command line and print the result to stdout. Yacas actually has both an --execute flag and a read-from-stdin flag, -f, but they don't work as advertised and this does.
I have not explained the -p and -c flags (dumb-term and no-prompts). Together as -pc, they are effectively --batch-mode, although one must also give an input file as a parameter to exit without starting the interactive repl.
`yacas --help` isn't a flag …

yacas: add page

---

pages/common/gml2gv.md
pages/common/graphml2gv.md
pages/common/gv2gml.md
pages/common/gv2gxl.md
pages/common/gxl2gv.md
pages/common/mm2gv.md

See #2580. These are the `xxx2yyy` graph converter commands from the
`graphviz` package. The commands have (mostly) the same syntax except
for the formats they convert between. These files are generated from
one template.

gml2gv, graphml2gv, gv2gml, gv2gxl, gxl2gv, mm2gv: add page

---

pages/common/circo.md
pages/common/dot.md
pages/common/fdp.md
pages/common/neato.md
pages/common/osage.md
pages/common/patchwork.md
pages/common/sfdp.md
pages/common/twopi.md

See #6270, #2580.
This pull-request contains the other seven graphviz layout commands in
addition to `dot`, which is awaiting approval at #6270. These files
are generated from the same template as `dot.md` there. The eight
commands differ in the command name, description line and the content
of the `echo` command in one example. (If any more changes are
required, I will regenerate all the files together.)

circo, fdp, neato, osage, patchwork, sfdp, twopi: add page

---

pages/linux/inotifywait.md

inotifywait: fix typo

---

.github/PULL_REQUEST_TEMPLATE.md

Due to the links being a little annoying to copy for the user, unless they read the link and find the page or they press `preview` they wont be able to easily use the links, meaning they are less likely to even give the effort, meaning more bug fixing.

PULL_REQUEST_TEMPLATE: add easy to copy links

---

pages/common/paci.md

This is the homepage repository, the PyPi page is a copy of the readme and the github wiki is only one page long.
For #6062

paci: add more information link

---

pages/linux/hcitool.md

Page on a CLI-tool, which monitors and configures
bluetooth devices available within a threshold range.
Close #6315

hcitool: add page

---

pages.de/common/ssh-keygen.md
pages/common/ssh-keygen.md

Current versions of openssh generate keys in its own format while many CI/CD, hosted Git platforms do not accept this type of keys  
You can identify the openssh format private key by checking if it has the tags
-----BEGIN OPENSSH PRIVATE KEY-----
-----END OPENSSH PRIVATE KEY-----

ssh-keygen: add key format conversion

---

pages/common/svgo.md

The `--enable` flag was removed in SVGO 2.0. For now, the only way to enable optional plugins is via config. Setting up a config file is out of scope for tldr so I'm just removing the deprecated flag in this PR.
See: https://github.com/svg/svgo/releases/tag/v2.0.0

svgo: remove deprecated --enable=plugin_name example

---

pages/common/xml-canonic.md
pages/common/xml-depyx.md
pages/common/xml-edit.md
pages/common/xml-elements.md
pages/common/xml-escape.md
pages/common/xml-format.md
pages/common/xml-list.md
pages/common/xml-p2x.md
pages/common/xml-pyx.md
pages/common/xml-select.md
pages/common/xml-transform.md
pages/common/xml-unescape.md
pages/common/xml-validate.md
pages/common/xml.md

Resolves issue #6368.
XML Starlet (`xml`) is a toolkit of commands that operate on XML documents. It has twelve subcommands.
PLEASE READ: This PR is _incomplete_. The three most complex commands, `select`, `edit`, and `transform`, have only "TBD" lines so far. I'm submitting the other nine subcommands now for your review while I work on the difficult three.

xml*: add pages

---

pages/common/r2.md

The use of `r2` as an alias can be seen [here](https://rada.re/n/radare2.html).
Addresses one page in #6346.
---

r2: add page

---

pages/common/youtube-dl.md

Extend the custom filenames example to also include the playlist_index. It is a useful way to keep the downloaded playlist sorted, which is an option I keep forgetting, and others probably as well.
_(Please let me know in case the pr does not follow the desired standard. Thank you for a great project!)_

youtube-dl: extend the custom filenames example

---

pages/common/fgrep.md

The language used before was misleading, since fgrep specifically does
not match regular expressions nor patterns. The man page reads:
> -F, --fixed-strings
>       Interpret PATTERNS as fixed strings, not regular expressions.
---

fgrep: remove incorrect use of 'regular expression'

---

pages.pt_BR/common/mvn.md
pages.zh/common/mvn.md
pages/common/mvn.md

Started with @hboutemy, @fbiville and @lydianeU during a [Paris Hackergarten session](https://www.meetup.com/Paris-Hackergarten/events/279653683/): `-Dmaven.test.skip` is simpler and correct.
Continued on myself, favoring `-DskipTests` (it compiles tests):
http://maven.apache.org/surefire/maven-surefire-plugin/examples/skipping-tests.html#:
You can also skip the tests via the command line by executing the following command:
mvn install -DskipTests
If you absolutely must, you can also use the maven.test.skip property to skip compiling the tests. maven.test.skip is honored by Surefire, Failsafe and the Compiler Plugin.
mvn install -Dmaven.test.skip=true
http://maven.apache.org/surefire/maven-failsafe-plugin/verify-mojo.html:
<skipTests>	boolean	2.4	Set this to 'true' to skip running tests, …

mvn: simplify skip unit tests

---

pages/common/acyclic.md
pages/common/bcomps.md
pages/common/ccomps.md
pages/common/edgepaint.md
pages/common/gvcolor.md
pages/common/gvpack.md
pages/common/mingle.md
pages/common/nop.md
pages/common/sccmap.md
pages/common/tred.md
pages/common/unflatten.md

Please see issue #2580.
This PR adds the `graphviz` filter commands: `acyclic`, `bcomps`,
`ccomps`, `edgepaint` (aka `clarify`), `gvcolor` (aka `colorize`),
`gvpack`, `mingle`, `nop`, `sccmap`, `tred`, and `unflatten`. These
commands all accept a graph in gv/dot format, transform it in some way
and output another graph in the same format.
Several of these filters require that the input graph be previously processed by `dot` or another layout engine (without using the -T option) to produce a text `layout.gv` file that includes layout information.
The multiple entries in this PR are substantially similar and were originally generated using `autogen` before manual editing to add unique flags and parameters.
Each filter command's entry includes a list of all Graphviz filters as there is …

acyclic, bcomps, ccomps, edgepaint, gvcolor, gvpack, mingle, nop, sccmap, unflatten: add page

---

pages.id/windows/xcopy.md

Here's my translation for `windows/xcopy`, with some notes:
+ I closely follow `common/cp`'s translation style for consistency, and
+ The translation for `xcopy {{path/to/file_or_directory}} {{path/to/destination}} /y` is quite different than the ones in English, which in this case means "allows `xcopy` to keep override/overwrite existing files" instead of disabling the overwrite prompt.

xcopy: add Indonesian translation

---

pages.de/common/ssh.md

Fixed a typo in the German translation. Let me know if I got the commit message right. :)

ssh: fix typo in German translation

---

pages/linux/ldapdomaindump.md

ldapdomaindump: add page

---

pages/linux/resize2fs.md

The statement `the filesystem must be unmounted` is not true: according to `man 8 resize2fs`:
>  It can be used to enlarge or shrink an unmounted file system located on device.
>  If the filesystem is mounted, it can be used to expand the size of the mounted
>  filesystem, assuming the  kernel and  the file system supports on-line
>  resizing.
Another option is to fix the statement to explain that the filesystem must be
unmounted only in some cases. However, the guideline states that `tldr` is not
meant as a substitute for `man`. Also, I find it difficult to express this
explanation more tersely than the man page, but I suppose the entire explanation
is too long to be included into a `tldr` page. So I suggest to just remove it completely.
If users assume that the filesystem can be mounted …

resize2fs: remove false statement

---

contributing-guides/translation-templates/alias-pages.md
contributing-guides/translation-templates/subcommand-mention.md

Since we're now getting more of those templates we can't just dump them all into `contributing-guides`. I created a directory `contributing-guides/translation-templates`, where we can have one file per template. There was also the idea to put everything into a single file, but that's still open for discussion. Personally I think that would get messy after some time.

Reorganize translation templates

---

pages/common/llvm-gcc.md

llvm-gcc: add page

---

pages/common/clang.md

the `gcc` page also has it and it makes sense

clang: add -c example

---

pages/common/find.md

Option is wrong. want to display files older than 7 days, should use the `-daystart -mtime -7`  or `-ctime -6`.
for example:
```
$ find . -daystart -mtime -7
.
./test_2021-09-04.log
./test_2021-09-07.log
./test_2021-09-05.log
./test_2021-09-08.log
./test_2021-09-03.log
./test_2021-09-06.log
./test_2021-09-09.log
$ find . -ctime -6
.
./test_2021-09-04.log
./test_2021-09-07.log
./test_2021-09-05.log
./test_2021-09-08.log
./test_2021-09-03.log
./test_2021-09-06.log
./test_2021-09-09.log
```

find: add -daystart argument in example

---

pages.de/common/cargo.md
pages.it/common/cargo.md
pages.ko/common/cargo.md
pages.nl/common/cargo.md
pages/common/cargo.md

For information, usage is:
```
$ cargo build --help | grep jobs
-j, --jobs <N>                   Number of parallel jobs, defaults to # of CPUs
```

cargo: use long argument --jobs

---

pages/common/cake.md
pages/common/clj.md
pages/common/coffee.md
pages/common/ghc.md
pages/common/guile.md
pages/common/ipython.md
pages/common/julia.md
pages/common/python.md
pages/common/r.md
pages/common/ruby.md
pages/common/sbcl.md
pages/common/sbt.md
pages/common/scala.md
pages/common/scheme.md
pages/common/swift.md

Normalized almost all references to a REPL to `Start a REPL (interactive shell)`.
I think that it is unacceptable for any serious project to have so many conflicting styles:
- `Start a(n) $LANG interactive shell (REPL)`
- `Run interactive REPL`
- `Start a REPL (interactive shell)`
- `Start a REPL`
- `Start the $LANG REPL`
- `Start a(n) $LANG REPL session`
- `Open an Interactive $LANG Shell (REPL)`
- (maybe more)
You might have cases in this diff, where you think that different descriptions might fit better and that is ok. But most of these should be normalized.

pages/common/*.md: REPL Normalization

---

pages/common/cargo-clippy.md

See usage:
```
$ cargo clippy --help | egrep "(--deny|--allow)"
-A --allow OPT      Set lint allowed
-D --deny OPT       Set lint denied
```
Also removed experimental feature for `--fix` (see [the doc](https://github.com/rust-lang/rust-clippy#automatically-applying-clippy-suggestions)).

cargo-clippy: use long arguments

---

pages.it/common/man.md
pages.pt_BR/common/man.md
pages.tr/common/man.md
pages/common/man.md

Update the `man` syntax for sections. I have tested the previous syntax `<command>.<section>` on Linux and macOS:
```shell
~ $ man 3 strcmp >/dev/null 2&>1 && echo "Exit status: $?"
Exit status: 0
~ $ man strcmp.3
No manual entry for strcmp.3
~ $ echo "Exit status: $?"
Exit status: 1
```
E: I had a typo in one of my commands. I reran it and updated the results.

man: correct syntax

---

pages/linux/ip-rule.md

ip-rule: add page

---

pages.it/common/exec.md
pages.ta/common/javac.md
pages.zh/common/javac.md
pages/common/exec.md
pages/common/javac.md

issue #6062 
- **exec:** Since `exec` is a shell builtin, https://manned.org/exec.1 ask you to redirect to `bash` man page. However `bash` man page is too massive to find out the usage of `exec`. So I choose https://linuxcommand.org/lc3_man_pages/exech.html.
- **history:** The information link added by #5825 is fine since it's from an official source https://www.gnu.org/software/bash/manual/html_node/Bash-History-Builtins.html. Therefore I didn't change it.
- **javac:** I choose oracle's man page https://docs.oracle.com/en/java/javase/13/docs/specs/man/javac.html.

exec, javac: add more information link

---

pages.zh/linux/aura.md
pages.zh/linux/brightnessctl.md

aura, brightnessctl: add Chinese translation

---

pages/common/llvm-bcanalyzer.md

**There is one big problem with this page: The official documentation is outdated.** (can't bug report this to them, because their sign-ups for the bugtracker are unnecessarily annoying) **It contains `-nodetails` and `-verify`, which don't work.** (as of `12.0.1` from Homebrew on macOS and from reading the code from HEAD in Git) **We might want to consider just linking to the source code, as it has [a nice comment that documents the tool](https://github.com/llvm/llvm-project/blob/main/llvm/tools/llvm-bcanalyzer/llvm-bcanalyzer.cpp#L9-L25).**

llvm-bcanalyzer: add page

---

pages/common/llvm-ar.md
pages/common/llvm-nm.md
pages/common/llvm-strings.md

aliases of `binutils` equivalents

llvm-ar, llvm-nm, llvm-strings: add page

---

pages.pt_BR/common/lsof.md
pages/common/last.md
pages/common/ldapsearch.md
pages/common/leave.md
pages/common/lex.md
pages/common/lorem.md
pages/common/lp.md
pages/common/lpstat.md
pages/common/lsof.md

issue #6062
- Apple doesn't provide pages of `lp`, `lpstat`.
- Repositories of `last`, `lsof`, `lex` don't provide human readable man pages.
- I didn't find an official source of `lorem`.

common/l*: add more information link

---

pages/common/sdk.md

Example on my machine:
```sh
$ sdk current
Using:
java: 21.2.0.r11-grl
mvnd: 0.6.0
scala: 3.0.2
visualvm: 2.1
```

sdk: add current example

---

CONTRIBUTING.md

The hyperlink for word `here`  over at [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/main/CONTRIBUTING.md#translations) on 107 line points to https://github.com/tldr-pages/tldr/blob/main/contributing-guides/alias-pages.md which does not exists.
The correct link is https://github.com/tldr-pages/tldr/blob/main/contributing-guides/translation-templates/alias-pages.md.
This PR fixes the following issue.

CONTRIBUTING: fix link to alias-pages

---

pages.es/common/git-revert.md
pages.fr/common/git-revert.md
pages.it/common/git-revert.md
pages/common/git-revert.md

As of git v1.8.5 `@` is an alias for HEAD, so for clarity changing the docs to simply use HEAD.
Closes #6624

git-revert: use HEAD in example

---

COMMUNITY-ROLES.md

I fixed what I assume is a typo, since it doesn't really make sense otherwise.

COMMUNITY-ROLES: fix typo

---

.github/PULL_REQUEST_TEMPLATE.md

When we get a new page, we don't know the version of the command being documented. This can lead to issues when some examples don't work anymore and we don't know why. I think it would help a lot if we can go back to that PR and look it up.

PULL_REQUEST_TEMPLATE: ask for command version number

---

pages/common/az-storage.md

az-storage: add page

---

pages/common/az-bicep.md

az-bicep: add page

---

pages/common/nodemon.md

If you give `--inspect` as an argument to nodemon, it passes it through to nodejs, which then listens for a Debugger. It is not meant as "inspect the given file for changes".

nodemon: make --inspect a generic example

---

pages/linux/spectre-meltdown-checker.md
pages/linux/timedatectl.md
pages/linux/xcursorgen.md

As far as i know, we only put extra information in the link if it is needed.

*: remove unnecesary trailing .1 of manned.org links

---

pages.de/common/ssh-agent.md
pages.de/common/ssh-copy-id.md
pages.de/common/ssh-keygen.md
pages.de/common/ssh-keyscan.md
pages.de/common/sshpass.md
pages.zh/common/ssh-add.md
pages.zh/common/sshuttle.md
pages/common/ssh-add.md
pages/common/ssh-agent.md
pages/common/ssh-copy-id.md
pages/common/ssh-keygen.md
pages/common/ssh-keyscan.md
pages/common/sshpass.md
pages/common/sshuttle.md

Relates to issue #6062
Extra Notes:
* Did not add information link to `/common/ssh` as it has been covered by https://github.com/tldr-pages/tldr/pull/6604 
* In the description of related issue https://github.com/tldr-pages/tldr/issues/6062#issue-905809548
* `linux/sshuttle` is listed, but this file is actually in `common/sshuttle`

common/ssh*: add more information link

---

pages.id/common/gh.md

gh: add Indonesian translation

---

pages/common/py-spy.md

py-spy is a sampling profiler for Python programs.
**Version of the command being documented (if known):** 0.3.10

py-spy: add page

---

pages/common/dune.md

[Dune](https://dune.build) is the most popular build system for the OCaml programming language now, used by many (if not most) packages from the OPAM repository.
- **Version of the command being documented (if known):** 2.9, but commands used in examples existed for a long time and the interface is stable

dune: add page

---

pages/linux/chntpw.md

- [x ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
#6863

chntpw: add page

---

pages.it/linux/iptables.md

Added iptables to the italian documentation

iptables: add Italian translation

---

pages/linux/keyctl.md

**Version of the command being documented (if known):** `keyctl from keyutils-1.6.3`

keyctl: add page

---

pages/common/clang-tidy.md

A mention of the value of a compilation database (`compile-commands.json`) would be good, but i was unsure where to fit it in, briefly.

clang-tidy: add page

---

scripts/set-more-info-link.py

`Daha fazla bilgi için` means `For more information`. I think this is a more exact translation for Turkish pages.

set-more-info-link: fix Turkish translation

---

pages/common/handbrakecli.md

handbrakecli: add rip DVD examples; use long arguments

---

pages/linux/nixos-option.md

**Version of the command being documented (if known):** not applicable.

nixos-option: add page

---

pages/common/shopt.md

See #6062
I put the gnu.org link over the manned.org link because there is more explanations of the options.

shopt: add more information link

---

pages/common/python.md

After a discussion with @navarroaxel , I fix the python deprecated documentation,
* update deprecated script path for each python command example.
* replace {{script.py}} to {{path/to/file.py}}

python: update deprecated script/file path

---

pages.it/linux/pulseaudio.md

I kept "daemon" as an English noun since it makes it more recognizable as a system function. Otherwise it can be translated in "servizio"

pulseaudio: add Italian translation

---

pages/linux/iptables.md
pages/linux/nft.md

If find the masquerade (NAT) functionality to be the one I actually use most, and it wasn't documented here.
I have to look it up myself sometimes and I think that other user can also benefit from the example.
For the nft page, it's a pity that you have to issue multiple commands (since a `nat` table or `postrouting` chain do not exist by default), but the TLDR guidelines don't allow multiple commands per example.

iptables, nft: add masquerade example

---

pages/linux/add-apt-repository.md

Based on [http://manpages.ubuntu.com/manpages/bionic/man1/add-apt-repository.1.html](http://manpages.ubuntu.com/manpages/bionic/man1/add-apt-repository.1.html)

add-apt-repository: improve --enable-source example description

---

pages/common/git-changelog.md

**Version of the command being documented (if known):** 6.2.0
Opened from #5137

git-changelog: add page

---

contributing-guides/translation-templates/common-arguments.md
contributing-guides/translation-templates/subcommand-mention.md

I have added Tamil snippets to `translation-templates`. Sorry about the slightly misaligned table column separators. The Tamil script has no monospace font.
This pull request came up in the context of #7350

translation-templates: add Tamil translation

---

pages/common/wasm-objdump.md
pages/common/wasm-opt.md
pages/common/wasm2c.md
pages/common/wasm2wat.md

Adds more links to address part of #6062.
I hope the mass change is acceptible given that they are all almost the same.
`wasm-objdump`, `wasm2c` and `wasm2wat` are all from [wabt](https://github.com/WebAssembly/wabt), which they all link to, as [`wat2wasm` does](
https://github.com/tldr-pages/tldr/blob/a178733e8e19d07f54d90abdea24e4f79676169d/pages/common/wat2wasm.md?plain=1#L4). `wasm-opt` is from [binaryen](https://github.com/webassembly/binaryen).

wasm-objdump, wasm-opt, wasm2c, wasm2wat: add link

---

pages/linux/lxc-network.md
pages/linux/lxc-profile.md

lxc-network, lxc-profile: add page

---

pages/common/rsync.md

The page said that the --delete parameter deletes local files that don't exist on remote.
But the actual behaviour is OPPOSITE of that!
From the man page:
```
--delete                delete extraneous files from dest dirs
```
https://www.mankier.com/1/rsync#--delete

rsync: fix --delete example description

---

pages/linux/notify-send.md

notify-send: Add `--app-name` to example

---

pages/common/tail.md

I'm not sure if this is even an error, but it sounds very weird.
From the man page:
-F     same as --follow=name --retry
--retry
keep trying to open a file if it is inaccessible
-f, --follow[={name|descriptor}]
output appended data as the file grows;
an absent option argument means 'descriptor

tail: fix wording

---

pages/common/pylint.md

pylint: add page

---

pages/common/aws-ses.md

aws-ses: add page

---

pages/common/pve-firewall.md

pve-firewall: add page

---

pages.de/linux/xrandr.md
pages.tr/linux/xrandr.md
pages/linux/xrandr.md

The last example (`-q`) is the same as the first one (`--query`)

xrandr: remove duplicate example

---

pages.fr/common/install.md
pages/common/install.md

Citing from our contributing guidelines,
> Try to incorporate the spelled-out version of single-letter options in the example's description. The goal is to allow people to *understand* the syntax of the commands, not just *memorize* it.

install: use long arguments format

---

pages/common/git.md

Added notes for using tldr for git subcommands. This note feels more instinctive to me. A CLI user should be able to see how to use tldr without visiting its github repo.
Also elongated line #15 with common subcommands for mnemonic purpose. New users often forget subcommands, and they have no way to recall them with tldr.

git: add more subcommand examples

---

pages/common/masscan.md

showed on tldr.sh as ```masscan {{10.0.0.0/16}} ââtop-ports {{100}} ââexcludefile {{path/to/file}}```

masscan: correct typo in hypen

---

.github/workflows/labeler.yml

Add a new GH action that acts on any new PR to automatically update its labels. I've added rules for the adding the following:
new command
page edit
translation
documentation
tooling
While dealing with these labels could probably be done by using the existing actions/labeler, I've gone with writing our own as we may add to it to support things like mass edit, reviews wanted, etc. which will require more complex logic than simple globing, but will re-use a lot of the logic written here.
Comes from #7330 
Close #7325

tooling: add PR labeler

---

pages/linux/wdctl.md

wdctl: add page

---

pages/linux/getopt.md

**Version of the command being documented (if known):** getopt from util-linux 2.34

getopt: use long argument for --options

---

.github/workflows/labeler.yml

Automatically use new versions from our labeler actions using the same mechanism that use `actions/checkout@v2` or `actions/setup-node@v2`.
To receive new versions automatically the tag `v0` should be updated when a new tag, e.g. `v0.1.1`, is created.

labeler.yml: use alias tag v0

---

pages/common/fish.md

- short options preferred over long ones
- page made more consistent with elvish page (check my PR)
- commands reordered: interactive commands, non-interactive commands
- set command example removed because it is example of Fish language but not of fish command
**Version of the command being documented (if known):** fish, version 3.3.1

fish: update page

---

pages/linux/ytfzf.md

**Version of the command being documented (if known):** 1.2.0

ytfzf: add page

---

pages/common/apt-moo.md

This page is highly essential, yet extremely stupid. Nothing more than a joke in apt.
If we don't think this fits TLDR's aims and expectations then close!

apt-moo: add page

---

pages/common/az-appconfig.md

az-appconfig: add page

---

pages/common/hping3.md

hping3: add page

---

pages/linux/resolvectl.md

resolvectl: add page

---

pages/windows/get-childitem.md
pages/windows/get-content.md
pages/windows/get-filehash.md
pages/windows/get-history.md

Similar to the `This command can only be used through adb shell` notice for some `android/` commands, I decided to do the same for `windows/get-childitem`, `windows/get-content`, `windows/get-filehash`, and `windows/get-history` since they are exclusive to PowerShell and cannot be run from the regular, Command Prompt (`cmd.exe`).

windows/get-*: add PowerShell-only notice

---

pages/linux/cgroups.md

cgroups are used via cgcreate, cgexec, and cgclassify, and users may look for `tldr cgcreate` or something, so i'll make individual pages for them.

cgroups: add page

---

contributing-guides/style-guide.de.md
contributing-guides/style-guide.md
contributing-guides/style-guide.zh.md

* I added the `--global` flag, because otherwise, it wouldn't be available as command.
* I replaced `tldrl` with `tldr-lint`, because with `tldr tldrl` you just get the alias page.

style-guide: mention tldr-lint instead of tldrl

---

pages/common/groff.md

Without --RAW-CONTROL-CHARS less in the example would mangle the display by converting the control characters into the caret notation.

groff: add --RAW-CONTROL-CHARS to pager example

---

pages/windows/vswhere.md

```
Visual Studio Locator version 2.8.4+ff0de50053 [query version 3.0.4492.23473]
Copyright (C) Microsoft Corporation. All rights reserved.
Error 0x57: The pattern ""**/VC/Auxiliary/Build/vcvarsall.bat"" is invalid
exit status 87
```
**Version of the command being documented (if known):** All

vswhere: remove invalid quotes in example

---

pages.de/common/nvm.md
pages.id/common/nvm.md
pages/common/nvm.md

From https://github.com/tldr-pages/tldr/pull/7511#discussion_r764356745 by @sbrl:
> `0.12` and `v4.2` are seriously old and unsupported versions of Node.js. Could we update these slightly at all please?
So I decided to update these versions to reflect newer versions of Node.js and to standardize documentation with other versions of `nvm` (#7511, #7512)

nvm: update versions in command description

---

pages/linux/taskset.md

Fix the syntax for running on non-sequential CPUs, which is done with commas. Also fix the syntax for running on sequential CPUs, which uses a "-".

taskset: fix syntax

---

pages/common/volta.md

I discovered [`Volta`](https://volta.sh) recently, I use it for some personal/professional JavaScript projects. 🤓
Version `1.0.5` (as seen via `volta --version`).

volta: add page

---

contributing-guides/git-terminal.md

Updates the docs for updating an old email address. This way is _much_ better than before, and much simpler to perform.
It might be worth revising the instructions, I wanted them to be verbose so people could maybe take the knowledge away with them, but at the same time explaining things rather than providing flat instructions might be daunting. 🤔 
For example, the fact that an interactive rebase works by rewinding the commit history and replaying commits might be redundant information.
Example of me performing the instructions for a single commit:

git-terminal: update instructions to amend author

---

contributing-guides/git-terminal.md

I hate myself.
Despite reading it 10 times over before making the PR, I didn't notice these typos until the _SINGLE_ time I chose to read it after it was merged.

git-terminal: fix typos

---

MAINTAINERS.md

MAINTAINERS: remove @zlatanvasovic from organization owners

---

pages/linux/xbps.md

The sync option in xbps should be `--sync` or `-S`, never be `--synchronize`.
And the fullname of `-u` is `--update`, I also edited it due to the consistency.

xbps: fix --sync and --update examples

---

pages/linux/makepkg.md

This matches the Arch Wiki, since it needs to be in capitals for the pkgbuild compliance

makepkg: fix command to match standard

---

pages/windows/nvm.md

**Version of the command being documented (if known):** 1.1.8
This is related to our discussion on https://github.com/tldr-pages/tldr/discussions/7480

nvm: add page

---

pages/common/glab-repo.md

* add a page for the glab repo subcommand.

glab-repo: add page

---

pages/common/git-pr.md

git-pr: fix grammar

---

pages/common/git-delete-tag.md

git-delete-tag: add backticks to git-extras

---

pages/common/go-build.md

go-build: add clarity

---

pages/common/git-pr.md

git-pr: add git-extras note in the command description

---

pages/common/git-mr.md

git-mr: add page

---

pages/linux/enum4linux.md

enum4linux: fix typo

---

pages/common/nvm.fish.md

**Version of the command being documented (if known):** 2.2.6
This is related to our discussion on #7480. However, this might break some tldr clients as this is the first known file to have more than one dot characters (`.`).

nvm.fish: add page

---

pages.de/linux/a2query.md
pages.de/linux/dpkg.md
pages.fr/linux/a2query.md
pages.id/linux/dpkg.md
pages.it/linux/a2query.md
pages.it/linux/dpkg-deb.md
pages.it/linux/dpkg.md
pages.pt_BR/linux/a2query.md
pages.pt_BR/linux/dpkg.md
pages.pt_PT/linux/a2query.md
pages.zh/linux/a2query.md
pages/linux/a2query.md
pages/linux/check-support-status.md
pages/linux/dpkg-deb.md
pages/linux/dpkg.md
pages/linux/netselect-apt.md
pages/linux/reportbug.md

a2query, dpkg*, check-support-status, netselect-apt, reportbug: update Debian link

---

pages/linux/ncdu.md

ncdu: add `--color` example and link

---

pages/common/code.md

It seems to be VS Code's default behavior (when opened from a terminal) to open files in an existing window, so I end up having to look up --new-window much more than --reuse-window.
1.63.2

code: add --new-window example

---

pages.it/common/dig.md
pages.ja/common/dig.md
pages.ko/common/dig.md
pages.pt_BR/common/dig.md
pages/common/dig.md

The old URL (<https://manpages.debian.org/dnsutils/dig.1.html>) is now 404ing.
**Version of the command being documented (if known):** DiG 9.17.21-1-Debian

dig: fix more information link

---

pages/windows/if.md

- there is no need to compare two string literals

if: update page

---

pages/common/git-standup.md

git-standup: add page

---

pages/linux/dm-tool.md

dm-tool: add page

---

pages.es/common/df.md
pages.es/common/dig.md
pages.es/common/du.md
pages.es/common/ln.md
pages.es/common/tree.md

I chose not to translate `example.com` in the `dig` page because it is reserved by an RFC and neither `ejemplo.es` nor `ejemplo.com` are.

df, dig, du, ln, tree: add Spanish translation

---

pages/osx/bird.md

I actually didn't notice this when reviewing the original PR, what a shame.

bird: fix capitalization in command description

---

pages/common/glab-auth.md

glab-auth: add page

---

pages/common/docker-run.md

Docker complains if I try non-absolute paths when adding volumes:
```
$ docker run -it -v example/foo:/example fedora
docker: Error response from daemon: create example/foo: "example/foo" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
$ docker run -it -v ~/example/foo:example fedora
docker: Error response from daemon: invalid volume specification: '/home/user/example/foo:example': invalid mount config for type "bind": invalid mount path: 'example' mount path must be absolute.
See 'docker run --help'.
```
```
cat /etc/fedora-release 
Fedora release 34 (Thirty Four)
rpm -q --file `which docker` …
```

docker-run: fix paths in -v example

---

pages/linux/adduser.md

tldr claims that adduser can add an *existing* user to an *existing* group:
https://github.com/tldr-pages/tldr/blob/0c99df4a332eb1c12b3617067a0f4c3a32a8feea/pages/linux/adduser.md#L26-L28
This does not work for me:
```sh
$ sudo adduser user docker
Usage: adduser [options] LOGIN
adduser -D
adduser -D [options]
Options:
--badnames                do not check for bad names
-b, --base-dir BASE_DIR       base directory for the home directory of the
new account
--btrfs-subvolume-home    use BTRFS subvolume for home directory
-c, --comment COMMENT         GECOS field of the new account
-d, --home-dir HOME_DIR       home directory of the new account
-D, --defaults                print or change default useradd configuration
-e, --expiredate EXPIRE_DATE  expiration date of the new account
-f, …
```

adduser: remove invalid example

---

pages/common/fnm.md

"ls" is an alias of [list](https://github.com/Schniz/fnm/blob/master/docs/commands.md#fnm-list), so besides being more obscure, it's not even the canonical name for the subcommand.
v1.30.1

fnm: spell out the "list" subcommand

---

CLIENT-SPECIFICATION.md

Closes #7076. This adds to the specification that it's recommended to treat `macos` as an alias for `osx`. At some point it might be good to migrate to `macos` for folder structure, this at least is a step in that direction.

CLIENT-SPECIFICATION: add macos recommendation

---

CLIENT-SPECIFICATION.md

As discussed in #7528 and [here](https://github.com/tldr-pages/tldr/pull/7561#issuecomment-997473651):
Drop the special `all` platform.

CLIENT-SPECIFICATION: drop the special "all" platform

---

scripts/set-more-info-link.py

Catalan translation is created in #7736. A few pages use `Más información` rather than `Más informació`, I guess it might be a typo.

set-more-info-link.py: add Catalan translation

---

pages.zh/linux/asciiart.md

Make `path/to/image.jpg` (路径/到/图片.jpg) follow [common-argument.md](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/translation-templates/common-arguments.md).

asciiart: update Chinese translation

---

pages/common/rsync.md

The example talks about transferring a directory, but the code block says file. Fixed so they both say directory.

rsync: fix remote_directory in -rauL example

---

pages/common/chsh.md
pages/linux/chsh.md

Fixes #7800
**Version of the command being documented (if known):** The behavior is the same on recent macOS and Linux (and I think other unix too)
I checked and none of the non-English translations have this bug.
I've used just `-s` because that seems very idiomatic (it's used in all the translations), it may work on older machines where `--shell` does not, and anyhow there's an example with `--shell`.

chsh: Fix `chsh -s SHELL` syntax

---

contributing-guides/style-guide.md

A simple but needed addition to the guide, considering that most of the
newcomers are unaware of this convention as it's not very explicit.
I consider this as a temporary quick-fix while the refactoring of the style
guide is ongoing (#7441).

style-guide: add information about links

---

pages/linux/setsid.md

`setsid from util-linux 2.37.4`

setsid: add page

---

pages/linux/dunstify.md
pages/linux/homectl.md
pages/linux/nmcli-connection.md
pages/linux/nmcli-device.md
pages/linux/xdg-open.md

Does not replace links of pages directly associated with archlinux (eg: pacman)

linux/*: replace man.archlinux.com link

---

pages/common/errno.md

Added a page for the `errno` command provided by the `moreutils` package

errno: add page

---

pages/linux/ufw.md

ufw: use range in deny port example

---

pages/common/ogr2ogr.md
pages/common/ogrinfo.md

This pull request updates the pages `ogr2ogr` and `ogrinfo`
`GDAL 3.2.2, released 2021/03/05`

ogr2ogr, ogrinfo: refresh

---

pages/common/ogrmerge.py.md

This pull request adds the page `ogrmerge.py`. The official documentation is on: https://gdal.org/programs/ogrmerge.html
`GDAL 3.2.2, released 2021/03/05`

ogrmerge.py: add page

---

CLIENT-SPECIFICATION.md

The last PR merged into the client specification did not add an entry to the changelog list. This PR recitifies this, and keeps it most up-to-date.

CLIENT-SPECIFICATION: Add entry to unreleased changelog

---

pages/osx/sdef.md
pages/osx/xml2man.md

sdef, xml2man: add page

---

pages/common/pwd.md

pwd: fix flags

---

pages.tr/linux/ip-neighbour.md
pages/linux/ip-neighbour.md

the syntax of title is now consistent with the others commands

ip-neighbour: fix command name

---

pages/common/zoxide.md

zoxide's remove command requires options _after_ the query string, and this is not well explained in either the built-in help or the current tldr database.
v0.8.0

zoxide: add --interactive to remove example

---

pages.zh/linux/apt.md

Previously, it means "It is better to use apt-get in Ubuntu versions 16.04 and later."
Now, it means "It is better to use apt in Ubuntu versions 16.04 and later."

cat: fix a translation error

---

pages/common/openssl-s_client.md

This adds `-servername` to `openssl s_client`.
It's one of the most common options to `openssl s_client` I use -- it's very useful when checking that a TLS cert is working correctly before you've updated the DNS.

openssl s_client: add '-servername'

---

pages/common/mtr.md

I think the '-z' option to `mtr` (to show the ASN) is very cool and useful, might be worth a 6th example.

mtr: add --aslookup example

---

pages/linux/pihole.md

Updates the more information link and replaces `pihole updatePihole` by the equivalent and more well-known `pihole -up`.
**Version of the command being documented (if known):** v5.10

pihole: update more information link

---

pages/common/nix.md

**Version of the command being documented (if known):** latest, 2.8.0

nix: fix deprecated optimise-store example

---

pages/common/dumpcap.md

Add some common commands when trying to capture packets using dumpcap, which is part of wireshark.
- [X ] The page (if new), does not already exist in the repository.
- [X ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ X] The page has 8 or fewer examples.
- [ X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [X ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ X] The page description includes a link to documentation or a homepage (if applicable).

dumpcap: add page

---

pages/common/perl.md

In this PR:
* A simplified matching pattern example
* A new example for printing matching lines
* More consistency of long-form arguments in all examples
* Nix the `-0` argument from the multiline find/replace example (it's not needed)
* Collapsed the in-place find/replace examples into one (it's always a good idea to use `-i'.ext'`!) to keep the total at 8, and turned `.old` into `.{{extension}}`
**Version of the command being documented (if known):** Perl 5

perl: improve matching pattern example, arg consistency, etc.

---

.github/workflows/ci.yml
.github/workflows/stale.yml

Update stale action to v5.
Update actions to use node16 runtime instead of node12.

ci.yml, stale.yml: update runtime to node16

---

pages/common/gh-issue.md
pages/common/gh-pr-create.md
pages/common/gh-pr.md
pages/common/gh-repo.md
pages/common/gh.md
pages/common/glab-alias.md
pages/common/glab-issue.md
pages/common/glab-mr.md
pages/common/glab-repo.md
pages/common/glab.md

This PR synchronizes changes between the `gh` and `glab` pages so the documentation within can be standardized for easier maintenance. Inspired by #7416 and #7423 for shell pages.

gh*, glab*: standardize documentation

---

pages/linux/efibootmgr.md

**Version of the command being documented (if known):** version 17

efibootmgr: add clarity

---

pages/linux/nsenter.md

Add `-a` to nsenter (which I find quite useful) and adjust some of the grammar.

nsenter: add --all example and refresh

---

pages/linux/rpm.md

Updated to  use long options per guidelines
4.17.0

rpm: use long arguments format

---

pages/common/grep.md

**Version of the command being documented (if known):** 3.6
It may help to add an example for enabling colour output in grep.

grep: improve example to add color

---

pages/linux/conntrack.md

Fedora 35 IoT, conntrack-tools-1.4.5-8.fc35.aarch64

conntrack: add page

---

pages/common/vboxmanage.md

double hyphen for long option --type correction, see usage:
vboxmanage startvm
Usage:
VBoxManage startvm          <uuid|vmname>...
[--type gui|sdl|headless|separate]
[-E|--putenv <NAME>[=<VALUE>]]

vboxmanage: fix typo in example

---

pages/common/hydra.md

hydra: replace telnet with brute force example

---

pages.ca/common/wal.md
pages/common/wal.md

pywal expects a path after the -i argument.
**Version of the command being documented (if known): 3.3.0

wal: fix examples

---

README.md

* Use capitalization for alt of image.
* Add serial comma to list of operating systems.
* Replace British English (en-GB) with American English (en-US).
* Move bropages to the bottom.
* Rename Bro pages to bropages, which is how they refer to themselves.
* `Bro pages show concise` → `It shows concise` to avoid starting a sentence with a lowercase letter.

chore: move bropages to bottom

---

pages/linux/xdg-desktop-menu.md

1.1.3
---
I don't know how I managed that, should be correct this time.

xdg-desktop-menu: fix incorrectly documented command

---

pages/common/gpg.md

This updates the `gpg` encryption example to indicate that multiple recipients and signing is possible. One use-case for multiple recipients is being able to send a file to someone while also retaining the option to decrypt it oneself.
**Version of the command being documented (if known): 2.2.4**

gpg: add signing and multiple recipients

---

pages/common/gpg.md

**Version of the command being documented (if known):** 2.2.35

gpg: add notice that command is often symlinked

---

pages/common/ffmpeg.md

Swap one of similar examples for a much more useful one that shows scaling and framerate
**Version of the command being documented (if known):** 5.0.1

ffmpeg: replace with -vf and -r example

---

pages/linux/cgroups.md

* please see https://github.com/tldr-pages/tldr/issues/8123

cgroups: fix typo in command description

---

pages/linux/journalctl.md

**Version of the command being documented (if known):** 251

journalctl: add --vacuum-time example

---

.github/workflows/stale.yml

Some issues are being marked as stale, when they shouldn't be such as page request
I suggest that we either: 
Do what is done here, increasing the time for issues to be marked as stale and be closed
OR
make stalebot ignore the help wanted labelled issues

stale.yml: Change time for issues to be stale

---

pages/common/tmsu.md

TMSU is a simple file tagging utility: https://tmsu.org/
**Version of the command being documented (if known):** `0.7.5`

tmsu: add page

---

pages/linux/chpasswd.md

New page for linux command: [`chpasswd`](https://manpages.debian.org/jessie/passwd/chpasswd.8.en.html)
- Used `printf` instead of `echo` for consistency across systems.
-- https://stackoverflow.com/a/8467449/11200630
-- https://askubuntu.com/a/467756/1316257

chpasswd: add page

---

pages/common/gdal2tiles.py.md

Add the CLI tool [gdal2tiles.py](https://gdal.org/programs/gdal2tiles.html) from the GDAL/OGR suite.
3.2.2

gdal2tiles.py: add page

---

pages/linux/cgroups.md

... i hope thus will resolve #8123
* https://www.kernel.org/doc/Documentation/cgroup-v2.txt
* https://en.wikipedia.org/wiki/Cgroups

cgroups: explicitly declare non-existent man pages

---

pages/common/pip.md

Signed-off-by: Muhammad Falak R Wani <falakreyaz@gmail.com>
Cherry-Picked the example from `pip3`

pip: add install from requirements.txt example

---

pages/common/ld.md

GNU ld (GNU Binutils) 2.38
Closes #7794.

ld: add page

---

pages.ca/linux/dos2unix.md
pages.es/linux/dos2unix.md
pages.zh/linux/dos2unix.md
pages.zh/linux/mac2unix.md
pages.zh/linux/unix2dos.md
pages.zh/linux/unix2mac.md
pages/linux/dos2unix.md
pages/linux/mac2unix.md
pages/linux/unix2dos.md
pages/linux/unix2mac.md

Unix systems use the Line Feed character (LF) to specify a newline while
early macOS versions used a Carriage Return (CR). In the descriptions of
`dos2unix` and all related commands, this was reported the wrong way
round.
I fixed the error for all languages. I can speak English and Spanish but not Chinese, so I used Google Translate for that. Maybe someone speaking Chinese can verify that it is in the correct order now.
**Version of the command being documented (if known):** 7.4.2

dos2unix, mac2unix, unix2dos, unix2mac: fix error in descriptions

---

pages/common/code.md

**Version of the command being documented (if known):** `1.69.0`

code: fix typo in --user-data-dir example

---

pages/osx/mate.md

**Version of the command being documented (if known):** `mate 2.13.3 (Oct 12 2021)`

mate: add page

---

pages.zh/linux/brightnessctl.md
pages/linux/brightnessctl.md

Fixed incorrect example of negative brightness offset.
According to the docs, the `-` sign should come **after** the value, not **before** it. Placing the minus sign before the value yields nothing.
<https://github.com/Hummer12007/brightnessctl#usage>
```
Valid values:
specific value		Example: 500
percentage value		Example: 50%
specific delta		Example: 50- or +10
percentage delta		Example: 50%- or +10%
```
---
**Version of the command being documented (if known):** 0.5.1

brightnessctl: fix typo in decrease example

---

pages/linux/fuser.md

fuser: add example to kill processes bound to a specific socket

---

pages/linux/dnf.md

The history command shows well formatted installation log. Gives quick idea about what has happened so far.
Also, you retrieve the list and repeat the same operations on the new system to get up and running quickly.
Sample output of `dnf --reverse history`:
```
ID    | Command line                                                                                           | Date and time    | Action(s)      | Altered
------------------------------------------------------------------------------------------------------------------------------------------------------------
1 | install chrome                                                                                         | 2022-01-31 11:06 | Install        |    4 E<
2 | module install nodejs:16 …
```

dnf: add history example

---

pages.de/common/zsh.md
pages/common/zsh.md

I'm not sure if this should be in the `zsh`-page, but adding a new `noglob.md` page didn't feel right either.
I'm also not sure if we should maybe use a more specific example, like `noglob calc 3*sqrt(2)`.

zsh: add noglob example

---

pages.pt_BR/osx/aa.md
pages.pt_BR/osx/afinfo.md
pages.pt_BR/osx/afplay.md
pages.pt_BR/osx/airport.md
pages.pt_BR/osx/airportd.md
pages.pt_BR/osx/apachectl.md
pages.pt_BR/osx/applecamerad.md
pages.pt_BR/osx/appsleepd.md
pages.pt_BR/osx/arch.md
pages.pt_BR/osx/archey.md
pages.pt_BR/osx/as.md
pages.pt_BR/osx/asr.md
pages.pt_BR/osx/automountd.md
pages.pt_BR/osx/avbdeviced.md
pages.pt_BR/osx/base64.md
pages.pt_BR/osx/bc.md
pages.pt_BR/osx/bird.md
pages.pt_BR/osx/bless.md
pages.pt_BR/osx/bnepd.md
pages.pt_BR/osx/brightness.md

**Version of the command being translated (if known):**
https://github.com/tldr-pages/tldr/blob/main/pages/osx/aa.md
https://github.com/tldr-pages/tldr/blob/main/pages/osx/afinfo.md
https://github.com/tldr-pages/tldr/blob/main/pages/osx/afplay.md
https://github.com/tldr-pages/tldr/blob/main/pages/osx/airport.md
https://github.com/tldr-pages/tldr/blob/main/pages/osx/airportd.md
https://github.com/tldr-pages/tldr/blob/main/pages/osx/apachectl.md
https://github.com/tldr-pages/tldr/blob/main/pages/osx/applecamerad.md
https://github.com/tldr-pages/tldr/blob/main/pages/osx/appsleepd.md
https://github.com/tldr-pages/tldr/blob/main/pages/osx/arch.md
https://github.com/tldr-pages/tldr/blob/main/pages/osx/archey.md
https://github.com/tldr-pages/tldr/blob/main/pages/osx/as.md …

osx/*: add pt_BR translations

---

pages/linux/create_ap.md
pages/linux/ctr.md
pages/linux/f5fpc.md
pages/linux/htpdate.md
pages/linux/ipcmk.md
pages/linux/paru.md
pages/linux/rc-service.md

Fixes a manually corrected selection of typos reported by [typos](https://github.com/crate-ci/typos) in `pages/linux`.

linux/*: fix typos

---

pages/common/licensor.md

**Version of the command being documented (if known):** `licensor 2.1.0`

licensor: add page

---

pages/common/psql.md

- **Version of the command being documented (if known):**  12.11
The first example for psql is wrong or at least misleading. It lets users to believe that `psql my_db` is the same as `psql -h 127.0.0.1` which is not. By default (at least in v12.11), it connects via Unix Socket. 
This makes a difference for instance for access configuration in the `pg_hba.conf` file. I could not connect because usually by default (afaik), only the postgres user is allowed to access via socket. 
Alternatively one could say "... connects to the local database..." or something without naming localhost.

psql: clarify default host behaviour

---

pages.fr/common/ansible-doc.md
pages.fr/common/ansible-galaxy.md
pages.fr/common/ansible-inventory.md

ansible-doc, ansible-galaxy, ansible-inventory: add French translation

---

pages.fr/common/apktool.md
pages.fr/common/apm.md
pages/common/apktool.md
pages/common/apm.md

- **Version of the command being documented (if known):**  
---
Hi everyone 👋 
I translated this 2 pages, but also suggest editing the original english pages.
I removed an `s` to framework because we handle [only one framework at a time ](https://forum.xda-developers.com/t/how-to-use-and-install-apktool.1760133/)
Also `framework` does not have a translation in french. (can you confirm @nicokosi ?)
Same thing as apktool, they say we install `packages` and `themes` but we do not install multiple elements. so i changed the sentence to use singular.

apktool, apm: add French translation, update

---

pages/osx/security.md

This commit adds examples of adding custom CA certificates to the MacOS
trusted settings keychain. This allows developers working with locally
generated self-signed certificates to quickly trust a CA certificate for
testing purposes and remove them when done testing.
- **MacOS 12.4 Monterey, PROJECT:Security-60158.120.9**  (note that the `security` binary doesn't have a version flags, but running `strings $(which security)|grep PROJECT` will emit the packaged security version.)

security: add trusted cert add/remove examples

---

pages.de/common/docker-run.md
pages.pt_BR/common/docker-run.md
pages.tr/common/docker-run.md
pages/common/docker-run.md

Signed-off-by: Muhammad Falak R Wani <falakreyaz@gmail.com>

docker-run: use long options for examples

---

pages/common/make.md

Makefile variables can be overridden via the command line in the form of
`{{variable}}={{override}}` See the [Make manual section 9.5] for more
information.
[Make manual section 9.5]: https://www.gnu.org/software/make/manual/html_node/Overriding.html
- - -
**Note:** This syntax seems very useful but doesn't seem commonly used or discussed. I see value in adding it but it's a bit further out of the core set of functions that user might need, so I'd like a rationality check on if this seems useful enough for inclusion.
This allows for make invocations such as `make cleanup cloud=aws version=stable`.
- - -
- **GNU Make 3.81**

make: add variable override example

---

pages/linux/flameshot.md

This is already correct in fr, de.

flameshot: fix time unit in --delay example

---

pages/common/gdalwarp.md

- Add the CLI tool [gdalwarp](https://gdal.org/programs/gdalwarp) from the GDAL/OGR suite.
- Version of the command: `3.2.2`

gdalwarp: add page

---

pages.pt_BR/common/fc.md
pages/common/fc.md

The command `fc list` doesn't exist. We only have `fc-list`, which is a completely different command.

fc: remove subcommand mention

---

pages/common/sdk.md

1. There was a mix between 'gradle' and 'SDK'. We now only refer to 'SDK'.
Using the acronym for conciseness (the description explains the acronym).
2. Explanation for 'sdk use' was misleading. See https://sdkman.io/usage#use:
> It is important to realise that this will switch the candidate version for the current shell only.
3. Explanation for 'sdk current' has been enhanced, introducing the stable version concept aka 'candidate'.
See https://sdkman.io/usage#listcandidates:
> This will render a searchable alphabetic list with name, current stable default version (...)
~~**Version of the command being documented (if known):**~~

sdk: generalize for any SDKs and enhance explanations

---

pages/linux/grub-bios-setup.md

grub-bios-setup: add page

---

pages/common/gum.md

- **Version of the command being documented (if known):** gum version 0.4.0 (131ae3b)

gum: add page

---

pages/common/perl.md

Description was kind of misleading, since optional parameter for -i provides extension for saving backup, not the edited file.
Basically I've only edited description for one option, so no checklist boxes apply :)

perl: fix -i option description

---

pages/linux/inotifywait.md

This is mostly to remove the confusing `while` loops. 
I'm not so sure about the last example, but it kind of was there in the previous version, and I didn't want to completely remove it.

inotifywait: refresh

---

pages/linux/retroarch.md

I added the GitHub repo link in `More information:`. We can replace it with [manned](https://manned.org/retroarch.1) if needed.
_Note: I had skipped some advanced commands like shaders, netplay, etc as there are a lot of examples and people rarely use it from the command line. I think basic commands are enough. Do I need to add more commands? What do you think?_

retroarch: add page

---

pages/common/git-config.md

git version 2.37.1
`git config --show-origin` is very helpful when troubleshooting git configs that have `include` and/or `includeif` directives. It shows you where a configuration object comes from.
The purpose of this PR was just to introduce the `--show-origin` flag; but I had to find a way to correct the assumptions made by the two previous commands (showing `--local` and `--global`, but obscuring that `--system` is another configuration scope). So, following TLDR tradition, of making successive commands more complex; I added both `--global` and `--show-origin` to my example.

git-config: add --show-origin example

---

pages.de/common/aws-ec2.md
pages.fr/common/aws-ec2.md
pages.pt_BR/common/aws-ec2.md
pages/common/aws-ec2.md

As suggested in #8347, moving `help` after all subcommands.

aws-ec2: Reorder commands in page

---

pages/common/pwd.md

- **Version of the command being documented (if known):** latest
- according to [this](https://unixhealthcheck.com/blog?id=157) site `-L` example redundant
I think we can always omit options that are enabled by default unless documentation explicitly tells not to rely on this behavior.

pwd: refresh page

---

pages/common/gcc.md

gcc: use short -o option for output 

---

pages/windows/assoc.md
pages/windows/attrib.md

- **Version of the command being documented (if known):** latest
- Command examples reordered: from simple to complex. Complexity is measured in arguments count.
- `{{path\to\directory}}` is used instead of `{{path/to/directory}}` to suggest the right path delimiter in Windows.
I think we can apply the same corrections for all other Windows specific pages.

assoc, attrib: update page

---

pages/common/objdump.md

Also remove hyphen from disassemble to use more common form.
Maybe make a mention intel syntax applies to x86 asm but that should be obvious.
Resolves #8389

objdump: add intel syntax command

---

CONTRIBUTING.md

contributing(doc): fix typo 'simpliest' -> 'simplest'

---

pages/common/zstdless.md

- **Version of the command being documented (if known):** 1.5.2
This page is a virtual clone of the `zless` - I'll make some improvement suggestions for that command as well.

zstdless: add page

---

pages/common/gifsicle.md

I reworked the existing page and added some more examples.
- **Version of the command being documented (if known):** 1.93

gifsicle: update page

---

pages/common/emacs.md

I think it's valuable to acknowledge Emacs's capability as a script backend. It seems a lot of people seem to forget/miss this, even when they're testing their own Elisp files or performing script-like actions with Emacs.
- **Version of the command being documented (if known):** 28.1

emacs: add `--script` example

---

pages/common/cargo.md

The `+nightly` syntax is somewhat unusual and easy to forget. It composes nicely with many other cargo commands. None of the others have a +nightly example as yet.
- **Version of the command being documented (if known):** 1.62.1

cargo: add example to compile using the nightly version

---

pages/common/asdf.md

Recent versions of asdf have [subcommands that have their own subcommands](https://asdf-vm.com/manage/commands.html#all-commands), so hyphens are no longer valid
- **Version of the command being documented (if known):** 0.10.2

asdf: remove hyphens from subcommands

---

pages.de/common/docker-compose.md
pages.es/common/docker-compose.md
pages.fr/common/docker-compose.md
pages.it/common/docker-compose.md
pages.ko/common/docker-compose.md
pages.pt_BR/common/docker-compose.md
pages.tr/common/docker-compose.md
pages/common/docker-compose.md

- **Version of the command being documented (if known):** Docker Compose version v2.6.0
A while back docker-compose (v1) was deprecated in favor of a plugin for Docker called compose (v2).
Because of this change, we now do `docker compose` instead of `docker-compose`.
> The new Compose V2, which supports the compose command as part of the Docker CLI, is now available.
> 
> Compose V2 integrates compose functions into the Docker platform, continuing to support most of the previous docker-compose features and flags. You can run Compose V2 by replacing the hyphen (-) with a space, using docker compose, instead of docker-compose.
> 
> — https://docs.docker.com/compose/reference/
This does spotlight a potential problem with our current naming convention, however.
For example, a hypothetical …

docker-compose: update command to v2

---

pages/linux/protontricks.md

- Updating page description, and help command.
-  Adding new commands.

protontricks: refresh page

---

contributing-guides/style-guide.md

- Removing trailing `/` from the manned link.
- Updating **Chinese Copywriting Guideline** link from <https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.en-US.md> (The link doesn't work as the file name appears to have changed, In GitHub mobile app the link just defaults to the repository, I think updating the link would be better.) to <https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.en.md>.
- Moving Line 104: "**Pre-translated alias page templates can be found [here](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/translation-templates/alias-pages.md)**" outside codeblock. I think it is an error being placed inside the example codeblock.

style-guide: fix links

---

pages/common/cdk.md

As per https://docs.aws.amazon.com/cdk/v2/guide/cli.html#cli-ref The proper command is `cdk docs`

cdk: fix typo in example

---

pages/common/g++.md

Added the version command as well as multiple file compile and link commands for g++.

g++: add multiple file example

---

pages/common/npm-query.md

- **Version of the command being documented (if known):** 8.18.0

npm-query: add page

---

pages/common/pulumi.md

pulumi: add page

---

.github/ISSUE_TEMPLATE/page-translation.yml

- Removing the `new command` label from the issue temple ( `new command, translation`) as the page request is for a translation of the existing page and not an entirely new command. Also, unlike page requests, we would rarely get any issues regarding existing translations. So, I think we could manage both **translation requests and translation issues under the same label**. 
- Updating placeholder text from *Tell us what TLDR page you want to see!* to **Tell us what TLDR page you want to see in your language!**.

ISSUE_TEMPLATE/page-translation.yml: remove new command label

---

pages/common/mysqldump.md

mysqldump: fix example curly brackets placeholders

---

.github/workflows/ci.yml
.github/workflows/mirror.yml
.github/workflows/stale.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

workflows/*: add security hardening

---

pages/common/az-upgrade.md

- **Version of the command being documented (if known):** 2.40.0
Part of https://github.com/tldr-pages/tldr/issues/6141

az-upgrade: add page

---

pages/common/rpi-imager.md

rpi-imager: add page

---

CONTRIBUTING.md

An alternative fix would be to update the link to https://github.com/tldr-pages/tldr/blob/main/pages/linux/caja.md.

CONTRIBUTING: fix typo caja to tar

---

pages.fr/common/aws-quicksight.md
pages.fr/common/aws.md

I had some troubles to find a good translation, and i would be glad if another french can review my PR
The sentence is `Use auto prompt to help`. `prompt` is really hard to translate in french because there is no real direct translation, most of the time we must use a word which match the context.
I had a look at the AWS documentation and I notice that this flag just add auto-completion so, i translated `Utilise l'aide automatique au remplissage pour une commande` which means `Use the autocompletion help for this command`
I would like your point of view, is it ok ? (for native english speaker if it's ok to focus on the auto-completion)

aws, aws-quicksight: add French translation

---

pages.es/android/logcat.md
pages/android/logcat.md

Start with Spanish translations for Android commands.

logcat: improve command description

---

pages.id/android/am.md
pages.id/android/bugreport.md
pages.id/android/bugreportz.md
pages.id/android/cmd.md
pages.id/android/dalvikvm.md
pages.id/android/dumpsys.md
pages.id/android/getprop.md
pages.id/android/input.md
pages.id/android/logcat.md
pages.id/android/pkg.md
pages.id/android/pm.md
pages.id/android/settings.md
pages.id/android/wm.md

android/*: use imperative mood on Indonesian translation

---

pages/linux/getcap.md

Add a sample of getcap to look for all files under the given directories recursively.

getcap: add -r example

---

pages/common/gh-pr.md

- **Version of the command being documented (if known):** 2.16.1
For #7470

gh-pr: mention subcommand pages in command description

---

pages/linux/dnstracer.md

1.9, ref: https://www.kali.org/tools/dnstracer/

dnstracer: add page

---

pages/common/smalltalkci.md

This was indeed a slip. `--vm` is a regular optional argument:
```
$ smalltalkci --help
USAGE: run.sh [options] /path/to/project/your_smalltalk.ston
This program prepares Smalltalk images/vms, loads projects, and runs tests.
OPTIONS:
--clean             Clear cache and delete builds.
-d | --debug        Enable debug mode.
-h | --help         Show this help text.
--headful           Open vm in headful mode and do not close image.
--image             Custom image for build (Squeak/Pharo).
--install           Install symlink to this smalltalkCI instance.
--print-env         Print all environment variables used by smalltalkCI
--no-color          Disable colored output
--no-tracking       Disable collection of anonymous build metrics (TravisCI & AppVeyor only).
-s | --smalltalk    Overwrite …
```

smalltalkci: remove superfluous space

---

pages/common/fastmod.md
pages/common/gnmic-subscribe.md
pages/common/renice.md
pages/common/s3cmd.md
pages/common/virt-install.md
pages/linux/toolbox-init-container.md

I noticed a typo, then checked to see if I can find some more and collected them into this PR :)

fastmod, gnmic-subscribe, renice, s3cmd, virt-install, toolbox-init-container: fix typo

---

scripts/pdf/basic.css
scripts/pdf/render.py

PR fixes #7870, improving how the PDF bookmarks is laid out such that each command is listed underneath its directory. I also modified the title page such that it doesn't have an entry in the bookmark list for its subtitles.
The problem for why this is happening is that weasyprint uses the header tags to determine how content should be logically grouped. The way the tags were laid out prior to this PR was essentially (each 2 space indentation indicates another header level)
```
* tldr-pages
* Simplified and community-driven man pages
*  Generated on ...
* android
* am
...
* wm
* common
* 2to3
...
```  
And so, we end up with a weird setup where the directory page separator for `common` ends up under the `wm` page in android, etc.
To address this, I moved the directory page separators up …

scripts: improve generated PDF bookmark layout

---

pages/common/lzip.md

Added lzip common page, based on the 7z example (commands are very similar)
- **Version of the command being documented (if known):** 1.23

lzip: app page

---

contributing-guides/style-guide.md

Hello,
There has been a lot of confusion surrounding the tense that must be used on French pages. (As seen in a recent PR [#8632](https://github.com/tldr-pages/tldr/pull/8632).) The imperative mood used on English pages is not desirable in French because it can seem rude and overly familiar.
Simply using the infinitive would be an option in French and many French-speakers will have that instinct. However, the closest tense to match the English imperative, while remaining respectful, is the third person singular indicative present, which was recommended in the now closed issue [Grammar in French - verbs #4714](https://github.com/tldr-pages/tldr/issues/4714).
To avoid confusion in future contributions, I am proposing adding this …

style-guide: add French verb tense guideline

---

pages/common/aws-s3-ls.md

Hello! I was a little bit concerned about how the wording, as AWS S3 uses "prefixes" and "objects" instead of "folders" and "files".
- Tested using `aws-cli/1.23.12 Python/3.6.15 Linux/5.13.0-41-generic botocore/1.25.12`

aws-s3-ls: add page

---

pages/common/aws-history.md

- **Version of the command being documented (if known):** 2.7.25
Related: #5653

aws-history: add page

---

pages/linux/trashy.md

trashy: add page

---

pages/common/aws-configure.md

- **Version of the command being documented (if known):** 2.7.25
Related: #5653

aws-configure: add page

---

pages/common/fossil-delete.md
pages/common/fossil-forget.md
pages/common/fossil-rm.md

Link to the specific command pages vs the general help index page.

fossil-delete, fossil-forget, fossil-rm: fix more info links

---

pages/linux/register_new_matrix_user.md

---
When self-hosting a Matrix server, this tool is used to register new users by the admin.
Anyone have an idea of a simple and clean way to specify why the latter command is not recommended in most cases? (Shouldn't place passwords directly in commands.)

register_new_matrix_user: add page

---

pages/linux/qmrestore.md

Add examples for basic usage (without options!), --force and --live-restore
version 7.2, Wed 04 May 2022 07:30:00 AM CEST ( https://pve.proxmox.com/pve-docs/qmrestore.1.html )

qmrestore: add examples

---

pages/common/gnatmake.md
pages/common/gnatprep.md
pages/common/gprbuild.md

Add pages for [Ada](https://ada-lang.io/) build tools. gnatmake and gnatprep are from the GNAT toolchain (which is also a part of the GCC compiler suit), while gprbuild is a separate tool developed by AdaCore and released under the GNU GPL.

gnatmake, gnatprep, gprbuild: add page

---

pages/common/octave.md

Adds a page for [GNU Octave](https://octave.org/). Addresses https://github.com/tldr-pages/tldr/issues/7419

octave: add page

---

pages/osx/security.md

Documentation available here: https://ss64.com/osx/security-internet.html. Apple keychains end with *.keychain.

security: fix typo in example

---

pages/linux/qm-monitor.md
pages/linux/qmmonitor.md

qm-monitor: fix filename

---

pages.de/common/aws-kinesis.md
pages.de/common/aws-s3.md
pages.de/common/aws.md
pages.de/common/bat.md
pages.de/common/chmod.md
pages.de/common/cmake.md
pages.de/common/dd.md
pages.de/common/docker-service.md
pages.de/common/docker-system.md
pages.de/common/dotnet.md
pages.de/common/ffmpeg.md
pages.de/common/git-bisect.md
pages.de/common/gpg.md
pages.de/common/mount.md
pages.de/common/plantuml.md
pages.de/common/ssh.md
pages.de/linux/addr2line.md
pages.de/linux/alpine.md
pages.de/linux/arithmetic.md
pages.de/linux/certbot.md
pages.de/linux/nordvpn.md
pages.de/linux/pacman-files.md
pages.de/linux/pacman-sync.md
pages.de/linux/zathura.md
pages.de/windows/color.md

Related to https://github.com/tldr-pages/tldr/pull/8761 but I wanted to split this into a separate PR since I'd imagine that since it's about a different language maybe different people would review the changes.
So like the title describes, these are just a bunch of typos I found in some german translations :)

pages.de/*: fix typo in German translation

---

pages.pt_BR/common/aws-google-auth.md
pages.pt_BR/common/aws-help.md
pages.pt_BR/common/aws-history.md

aws-google-auth, aws-help, aws-history: add pt_BR translation

---

pages/windows/pabcnetcclear.md

The extenison of the output file should be `.exe`, not `.pas`.

pabcnetcclear: fix extension in Output example

---

pages/common/aws-s3api.md

- **Version of the command being documented (if known):** aws-cli/1.25.71

aws-s3api: add --region to create-bucket example

---

pages/common/jar.md
pages/common/jarsigner.md
pages/common/java.md
pages/common/javac.md
pages/common/jhat.md
pages/common/jmap.md
pages/common/jps.md
pages/common/jstack.md
pages/common/kotlin.md

As mentioned in https://github.com/tldr-pages/tldr/pull/8758#discussion_r991419458 this PR is to adjust various java related pages so that the titles are consistent and don't use title case. By java related pages I mainly mean the ones listed in https://docs.oracle.com/en/java/javase/18/docs/specs/man/ and additionally also the Kotlin page as it is tangentially related and had the same issue.

java related pages: fix command description case

---

pages/common/aws-route53.md

Hi everyone, 
adding a new page for AWS Route53 CLI tool.
Thanks
Yuri.
N.B. I was thinking of showing how to add an A record to a zone, unfortunately, it requires the input to be in JSON (on CLI or from file), so not sure if it suits here. E.g.:
- Add A record www.example.com to the zone file "example.com":
aws route53 change-resource-record-sets --hosted-zone-id {{zone_id}} --change-batch ' {
"Comment": "Adding A record",
"Changes": [
{
"Action": "CREATE",
"ResourceRecordSet": {
"Name": "www.example.com",
"Type": "A",
"TTL": 600,
"ResourceRecords": [
{
"Value": "1.2.3.4"
}
]
}
}
]
}
'

aws-route53: add page

---

pages/common/cf.md

The `cf login` command is very important and the first step to authenticate the end user.

cf: add login example

---

pages/common/aws-lightsail.md

- **Version of the command being documented (if known): 2.8.2**

aws-lightsail: add page

---

pages.pt_PT/android/am.md
pages.pt_PT/android/bugreport.md
pages.pt_PT/android/bugreportz.md
pages.pt_PT/android/cmd.md
pages.pt_PT/android/dalvikvm.md
pages.pt_PT/android/dumpsys.md
pages.pt_PT/android/getprop.md
pages.pt_PT/android/input.md
pages.pt_PT/android/logcat.md
pages.pt_PT/android/pkg.md
pages.pt_PT/android/pm.md
pages.pt_PT/android/settings.md
pages.pt_PT/android/wm.md

android/*: add pt_PT translations

---

pages/common/doctl-kubernetes-options.md

doctl version 1.82.0-release
Addresses  #7475
doctl kubernetes command has 3 main subcommands (create, options, and 1-click). This covers the options subcommand

doctl-kubernetes-options: add page

---

pages/linux/elink.md
pages/linux/esearch.md

7.40
There are several executables in the edirect package and so I am starting with two of them, esearch and elink.

elink, esearch: add page

---

pages/common/kubectl-delete.md
pages/common/kubectl-describe.md
pages/common/kubectl-get.md

Ref: #8746; In order to better align with other `kubectl` pages having a `.yaml` file extension outside the path, I am updating this page.

kubectl-*: move .yaml inside token syntax

---

pages.es/osx/wifi-password.md

wifi-password: add Spanish translation

---

pages/linux/ldd.md

The script to automatically add more tldr entries is great, but it's lacking some information that I think will be important for the cheatsheet. So I've gone ahead and clarified the tldr to be a bit more helpful.
This is to hopefully help and close [this issue](https://github.com/tldr-pages/tldr/issues/8998)
- **Version of the command being documented (if known):** 2.35 as of the time of writing.

ldd: add more info

---

pages.ko/common/docker-build.md

docker-build: add Korean translation

---

pages/common/aws-cognito-idp.md

- **Version of the command being documented (if known): 2.8.2**

aws-cognito-idp: add page

---

pages/common/ac.md

Closes #7859.
- **Version of the command being documented (if known):** Version 5 AT&T UNIX

ac: add page

---

pages/common/git-bulk.md

* add a new page for git-bulk from git-extras

git-bulk: add page

---

pages.fr/common/dart.md

* translate the dart command from english to french

dart: add French translation

---

pages.fr/linux/cp.md

Create pages.fr/linux/cp.md as translation from linux directory english page.

cp: add French translation

---

pages/windows/find.md

The search string must be quoted, and iit must be double quotes.

find: add double quotes in examples

---

pages/common/rss2email.md

Completes a task in https://github.com/tldr-pages/tldr/issues/3689

rss2email: add page

---

pages/common/podman.md

- **Version of the command being documented (if known): N/A (applies to most/all versions)**

podman: examples parity with docker

---

pages/windows/curl.md
pages/windows/wget.md

Due to tldr-pages/tldr-node-client#336 impacting some Windows users who are using the Node.js version of `tldr` client, I decided to add the non-standard `--os` version to the documentation as a workaround.
Hopefully tldr-pages/tldr-node-client#337 can be merged to fix this issue.

windows/curl,windows/wget: fix tldr client param inconsistencies

---

pages/common/aws-workmail.md

- **Version of the command being documented (if known): 2.8.2**

aws-workmail: add page

---

pages/common/zip2john.md

- **Version of the command being documented (if known):** 1.9.0
A utility tool for extracting password hashes from zip archives for use with John the Ripper password cracker

zip2john: add page

---

pages.es/osx/uuidgen.md
pages.es/osx/warm.md

uuidgen, warm: fix Spanish translation

---

pages/common/gyb.md

Solves a task in https://github.com/tldr-pages/tldr/issues/3689

gyb: add page

---

pages/common/zip.md

The `-r`  option in the third example was missing. The command should be recursive, since it adds directories to the archive (`{{path/to/file_or_directory1 path/to/file_or_directory2 ...}}`).

zip: fix missing -r option, add hints for single-letter options

---

pages/linux/enum4linux.md

Removed connection to a dead link and related information

enum4linux: remove enum.exe from command description

---

pages/common/git-hash-object.md

git-hash-object: add page

---

contributing-guides/translation-templates/common-arguments.md

common-arguments: add Japanese translation

---

pages/common/find.md

I can see people woken up at 4am for some alert they're on-call to resolve, trying to remember the syntax for finding files modified in the last week, and accidentally deleting them because, in a sleep induced haze, they copied and pasted `find root_path -daystart -mtime -7 -delete`, then only modified `root_path` and forgot to take out `-delete`.
This PR makes it a bit less likely they'll do that.
If people want to delete files, tldr already shows them how to do that in the 8th (last) example.  (Edit: To make this clear - there are **two** examples for delete. This PR only modifies one of them to hopefully prevent accidental data loss.)
<sup><sub>As an aside, perhaps suitable for a different PR, `-daystart` is an invalid operator on macOS (and maybe *BSD too?)</sup></sub>

find: remove redundant -delete from -daystart example

---

pages/common/xzless.md

- **Version of the command being documented: xz (XZ Utils) 5.2.5**
Issue: #8859

xzless: add page

---

pages/common/twine.md

Follow up to https://github.com/tldr-pages/tldr/pull/8624.
```
$ twine --version
twine version 4.0.1 (importlib-metadata: 4.13.0, keyring: 23.9.3, pkginfo: 1.8.3, requests: 2.28.1, requests-toolbelt: 0.9.1, urllib3: 1.26.12)
```

twine: add examples

---

pages/linux/wipefs.md

It may often be misconceived that `wipefs --all /dev/sdX` will recurse and wipe sub-level block signatures, i.e. those for filesystems, etc. However `--all` does not recurse the layers. In order to more fully wipe at all layers, the glob pattern can help make the wiping more thorough.

wipefs: add --all example with glob pattern

---

pages.it/common/date.md
pages.ko/common/date.md
pages.pt_BR/common/date.md
pages.tr/common/date.md
pages/common/date.md

- **Version of the command being documented (if known):** GNU coreutils 9.1, Arch Linux
Adding a missing percent sign. Without it, `Z` is just displayed as the letter `Z`. This is clearly not intentional.
Adding the `%` causes `%Z` to evaluate to `UTC`.
It generally evaluates to the timezone's abbreviation, but the -u flag forces UTC.

date: fix typo in -u example

---

pages/common/exiftool.md

The second new example shows how to remove most image metadata (e.g., geolocation, camera model) without messing up the image's appearance.

exiftool: add print example and image metadata example

---

pages/common/cron.md
pages/common/ripgrep.md
pages/common/todoman.md

This was one of the oldest requests that motivated the need for [alias pages](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#aliases), so I'm surprised it hadn't been added yet.
Fixes #904 (finally!!)
I've also fixed the text of the `ripgrep` and `todoman` alias pages, which used a wording slightly different from the standard alias description [defined in the guidelines](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#aliases).

cron: add alias page

---

pages/linux/qtile.md

- **Version of the command being documented (if known):** `v0.22.1`
Added a page for the `qtile` tiling window manager for Linux with some examples of useful commands

qtile: add page

---

pages/common/git-blame.md

This just adds an explanation for running git blame on an older commit. I have used this very often recently, like when the commit shown by blame already contained the bug I was looking for and I wanted to continue blaming deeper into the past. Since the TLDR page of blame was so short, I thought it would be a nice addition.

git-blame: add commit examples

---

.github/workflows/codespell.yml

Signed-off-by: Seth Falco <seth@falco.fun>
We're getting complaints in other PRs when we shouldn't atm, it seems to only occur when one of non-English pages are touched or added. Testing on my private branch, the problem seems to get resolved just from trimming spaces. :thinking: 
Regardless, I explicitly add to ignore `package-lock.json` as well to avoid having it try to provide corrections from there.
See the following for an example of the issue:
* https://github.com/tldr-pages/tldr/pull/9427/files
* https://github.com/tldr-pages/tldr/pull/9425/files
* https://github.com/tldr-pages/tldr/pull/9424/files
* https://github.com/tldr-pages/tldr/pull/9422/files

codespell.yml: ignore package-lock.json

---

pages/common/black.md

- **Version of the command being documented (if known):** black, 22.10.0 (compiled: no)
Just some minor changes, modified the order and description of the examples using `--diff` and `--check` to more accurately reflect the difference between them, and made the link point to the project's documentation page.

black: adjust example descriptions for `--diff` and `--check` examples

---

pages/common/errno.md

errno: fix grammar in example description

---

pages.fr/common/cargo.md

* add a french translation to cargo main documentation

cargo: add French translation

---

pages/linux/conky.md

---
The examples for the Conky command were formed incorrectly.
> `conky -a top_left -x 5 -y 500 -d`
> 
> — https://www.mankier.com/1/conky#Examples
> `conky -a top_left -x 5 -y 500 -d`
> 
> — https://manned.org/conky.1#head10
Fun fact btw, not too familiar with Mankier, seems to be a browser based frontend for man pages, similar to manned. Except at the top it puts a tldr page before showing a man page. :o
> Note how it shows a tldr page first, then the man page.

conky: fix align example

---

pages/common/cut.md

The `--delimiter` option only applies when separating fields. I have changed the second example to use `--fields` instead of `--characters`, which threw an error.

cut: use `--delimiter` with `--fields`

---

pages/common/gcc.md

I believe "-g" is the flag for debug symbols. The tldr could do without "-Og" but it is usual to include both.
[-g](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html) Produce debugging information in the operating system’s native format (stabs, COFF, XCOFF, or DWARF). GDB can work with this debugging information.
[-Og](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#Optimize-Options) Optimize debugging experience. -Og should be the optimization level of choice for the standard edit-compile-debug cycle, offering a reasonable level of optimization while maintaining fast compilation and a good debugging experience. It is a better choice than -O0 for producing debuggable code because some compiler passes that collect debug information are disabled at -O0.
- **Version of the …

gcc: add -g to -Wall -Og example

---

pages/common/quarto.md

Updating the examples and adding more options to the use of the `quarto` command.

quarto: refresh page

---

pages.it/common/aria2.md
pages.ko/common/aria2.md
pages.zh/common/aria2.md

---
I noticed that these translated pages fell out of sync with the English version.
The English page is now an alias page, so the previous translations of it should be made alias pages as well.
I do realize there is one problem with this, which is that the English page says:
> View documentation for the updated command
But the alias page templates I used are translations of:
> View documentation for the original command
It'd be better if we could make them all match. :thinking:

aria2: update translations to match en page

---

pages/windows/scoop.md

`Scoop.md` advises to update all packages with `scoop update *`. 
The result of that command is dependent on the shell being used. When using bash, `*` is error-prone as it is expanded to the content of the directory where the command is executed.
`scoop update -a` guarantees consistent results and is supported by scoop's built-in help.
```shell
$ scoop update --help
Usage: scoop update <app> [options]
...
-a, --all                 Update all apps (alternative to '*')
```
- **Version of the command being documented (if known):** `v0.3.0 - Released at 2022-10-10`

scoop: improve example to update all packages

---

pages/common/exiftool.md

A common use of exiftool is removing location data from photos.  One may wish to preserve most EXIF data (ex. rotation, date/time taken, etc.) but remove private location data.  This example accomplishes this common task.
The proposed example (including quotes) comes from exiftool's author, Phil Harvey: https://exiftool.org/forum/index.php?topic=6037.msg29731#msg29731
This example works to not only remove GPS data from EXIF but also from Adobe's XMP tags.
Tested with JPEG and HEIC photos using exiftool 12.50.
- **Version of the command being documented (if known): 12.50**

exiftool: Add "-gps*=" removal example

---

pages/osx/icalbuddy.md

- https://github.com/tldr-pages/tldr/blob/main/pages/osx/icalbuddy.md
Add long options on `icalbuddy` examples as requested on PR: https://github.com/tldr-pages/tldr/pull/9495#discussion_r1027005180

icalbuddy: Add long options on examples

---

scripts/test.sh

This fixes #9468 by adding batching to call of markdownlint.

scripts/test.sh: add batching to markdownlint

---

pages.zh/common/mkfile.md
pages/common/mkfile.md

As far as I know, this command first appeared in `sunos` (Solaris), then FreeBSD cloned it, and macOS got it from them.

mkfile: move to common

---

pages.es/common/krunvm.md
pages/common/krunvm.md

Adding Krunvm utility in english and spanish languages
This utility is compatible in Linux and OSX.
Signed-off-by: Juan Manuel Parrilla Madrid <jparrill@redhat.com>
- **Version of the command being documented (if known): krunvm 0.2.3**

krunvm: add page, add Spanish translation

---

pages/common/git-merge-base.md

- **Version of the command being documented (if known): 2.38.1**

git-merge-base: add page

---

pages/common/audacious.md

- **Version of the command being documented (if known):** 4.2

audacious: add page

---

pages/common/qmv.md

- **Version of the command being documented (if known):** v1.3.0

qmv: add -f do example

---

contributing-guides/git-terminal.md

These are instructions to avoid some strange warnings when editing pages in editorconfig-aware editor on Windows.
See #7097

git-terminal.md: add instructions for CRLF on Windows

---

contributing-guides/style-guide.md

style-guide.md: fix broken path placeholders

---

pages/windows/get-acl.md
pages/windows/get-date.md
pages/windows/measure-command.md
pages/windows/measure-object.md
pages/windows/out-string.md
pages/windows/pwsh-where.md
pages/windows/resolve-path.md
pages/windows/select-string.md
pages/windows/set-acl.md
pages/windows/set-date.md
pages/windows/set-service.md
pages/windows/show-markdown.md
pages/windows/sls.md
pages/windows/sort-object.md
pages/windows/start-service.md
pages/windows/stop-service.md
pages/windows/tee-object.md
pages/windows/test-json.md
pages/windows/wait-process.md
pages/windows/where-object.md

Thanks for this amazing project. Many times I needed to know how to run a command but the help/manpage was too complex.
I'm still working on adding more commands to this PR. Please hold from verifying until done.
Question: I noticed that some PowerShell related aliases have the same name of other tools. Is it possible to group utility related commands in a sub folder for disambiguation?
eg:
```
pages/
windows/
powershel/
where.md
...
```
For #6621

windows/*: add page

---

README.md

- Added our C clients  `brew install tldr` option to README.
I added the `brew install tldr` option to README as it seems to be used by a lot of mac users. As you can see here https://formulae.brew.sh/formula/tldr.

README: add brew option

---

scripts/deploy.sh

PR modifies the deploy process so that a `sha256sums` file is generated that has the SHA256 hash of each asset file that was generated during the deploy. This can be used by folks to verify that the `zip` or `index.json` or `pdf` that they downloaded matches the one we built, as well as could be used as an easy way to tell if the source has changed at all since the previous update (which would help me tackle https://github.com/tldr-pages/tldr-c-client/issues/94).

scripts/deploy.sh: generate sha256sum of artifacts

---

CLIENT-SPECIFICATION.md

PR updates the client spec doc so that the link to the `asset.zip` file in the raw `tldr-pages.github.io` URL uses the `main` branch, instead of the `master` branch. This probably should have been done in a66723d2c54b70541b325753547c6e03dc51846d as part of #5110.

CLIENT-SPECIFICATION: Use main for asset link

---

pages/linux/pyrit.md

- **Version of the command being documented: 0.5.0**
#6863

pyrit: add page

---

CLIENT-SPECIFICATION.md

Inspired by: https://github.com/tldr-pages/tldr/pull/9252#discussion_r1008695955
For a project that emphasizes long and readable options as much as we do (imho often to an unnecessary degree), it is honestly completely incomprehensible to me that we would only support short options, and I have yet to come across any reasonable excuse for that. If you have one, please comment.

CLIENT-SPECIFICATION: Require support for long options

---

pages/common/pv.md

* fix 'stop at' option by including --size parameter
* replace -s and -S with their spelled out variants
- **Version of the command being documented (if known):** 1.6.20

pv: fix 'stop at' example

---

pages/common/vite.md

- **Version of the command being documented (if known):** 4.0.3
This adds a new page for [vite](https://vitejs.dev/). It's a common JS build tool.
I always forget the command and have to go to their website so I thought I'd just add it to the tldr pages.

vite: add page

---

pages/common/cp.md

Think of:
find . -name '*foobar*' -type f -print0 | xargs -0 cp -t DEST_DIR
All of the files passed by the pipe will remain in DEST_DIR

cp: example using -t

---

pages/common/sam2p.md
pages/common/scd.md

Completes a task in https://github.com/tldr-pages/tldr/issues/3689

scd: add page

---

contributing-guides/style-guide.md

- Moved `Range syntax` under  `Placeholder syntax`.
- _Require generic placeholders always until they cause confusion (strictly defined)._ Addresses [this](https://github.com/tldr-pages/tldr/pull/9716/files#diff-6d7b5ac94fb71d5f0e18bbe601e0380866cd931813bd86356e2f3e722ae99fd4R25) issue: no formal rule defined yet when to use placeholders which don't permit arbitrary content inside them like ranges.
- Fix spacing between headings.
- Make Chinese points in Language-specific rules as subpoints and remove space (bugfix).
- Fix spacing between the heading and codespaces.
- Fix typos.

style-guide: refresh page

---

contributing-guides/style-guide.md
pages/linux/adig.md

- Move placeholder grouping rules to a separate sections
- Allow specifying duplication count for placeholders (as now it's impossible)
If this PR and #9741 will be merged we will be able to use `{{path/to/directory1 path/to/directory2 ...(0..infinity..2)}}` where even number of directories expected for instance.

style-guide: refresh page: move ellipsis to a separate section and extend syntax

---

contributing-guides/style-guide.md

Motivation: `infinity` can be misinterpreted and lead to confusion as all computer numbers are limited while infinity is not.

style-guide: refresh page: use `n` instead of `infinity` in ranges

---

pages/common/conda.md

- **Version of the command being documented (if known):** N/A
---
`activate` and `deactivate` are commands, not args
Looks like before we had the token syntax because it was an enum `{{activate|deactivate}}` but it was split up into 2 separate examples. Now that it's 2 examples though, it doesn't make sense to use the token syntax imo, they are no longer considered user-defined elements of the command they're documenting.
* https://github.com/tldr-pages/tldr/pull/6050/files

conda: activate/deactivate are not args

---

MAINTAINERS.md

EmilySeville7cfg has [voluntarily left the project](https://github.com/tldr-pages/tldr/pull/9766#issuecomment-1379570139) and is working on a different one. As per `COMMUNITY-ROLES.md`, I am updating `MAINTAINERS.md` to reflect the same. 
_Thanks for all your contributions @EmilySeville7cfg, feel free to join back in future._

MAINTAINERS: remove @EmilySeville7cfg from org

---

pages/common/tts.md

- **Version of the command being documented (if known):**  
0.10.2
TTS is a CLI utility that comes with Coqui, a free and open-source engine for text-to-speech.
https://coqui.ai/
Not everything they do is open-source unfortunately, but the CLI tool and some of the models they use are. Overall seems pretty cool. :thinking: 
Seems like they're building an alternative to [VOCALOID](https://www.vocaloid.com/en/). :thinking: 
Most of the examples are derived from their help command, they use a TL;DR like syntax in the first place, so it just rewords things to make sense and sorts commands in what I think would be most relevant first.
> From their help command.

coqui: add page

---

pages/common/git-annotate.md

- **Version of the command being documented (if known):** 2.34.1

git-annotate: add -L example

---

pages/common/holehe.md

holehe v1.61
Repo: https://github.com/megadose/holehe
A similar tool to [Sherlock](https://github.com/sherlock-project/sherlock), but for email addresses instead of usernames.
PS: While this basically is a cyberstalking tool, I see it as a tool to aid privacy-conscious users in discovering and erasing online accounts/personal data.

holehe: add page

---

pages/common/nu.md

This flag should be called `log-level`
```
> nu --loglevel info
× The `nu` command doesn't have flag `loglevel`.
╭─[source:1:1]
1 │ nu --loglevel
·    ─────┬────
·         ╰── unknown flag
```
After:
```
> nu --log-level info
2023-01-28 07:57:42.536 PM [INFO ] nu: start logging src/main.rs:288:67
```

nu: fix log-level command instructions

---

pages/common/dd.md

`pgrep` does not exist and `kill` needs `-s`.
But most importantly, `dd` doesn't have any "showing progress" functionality.
- **Version of the command being documented (if known):** The Open Group Standard: Base Specifications, Issue 7, 2018 Edition

dd: remove checking progress example

---

pages/common/head.md
pages/linux/head.md
pages/osx/head.md

- **Version of the command being documented (if known):** The Open Group Standard: Base Specifications, Issue 7, 2018 Edition; macOS 13.2, FreeBSD 13.1; GNU coreutils 9.1

head: split POSIX, BSD and GNU

---

pages/common/sleep.md
pages/linux/sleep.md

The PR adds some practical uses of the `sleep` command:
- The `sleep` command is mostly used for delaying other commands.
- Also multiple arguments with different time units are allowed.
PR checks:

sleep: refresh page

---

pages.fr/common/arping.md

corrects a French mistake on the description of a command

arping : fix typo in French translation

---

pages/common/gfortran.md

- **Version of the command being documented (if known):** GNU Fortran (GCC) 12.2.1 20230201
Since GCC and GFortran are very similar, I just copy&pasted the GCC page and adapted it.

gfortran: add page

---

pages/linux/lftp.md

Hi
**lftp** does not automatically ask for the username to connect to the ftp server.
Without the "--user" parameter, you must use the "login" command.

lftp: add login parameter to connect to the server

---

pages/common/b3sum.md

I like b3sum and use tldr pages. So I thought I would start contributing with writing the missing tldr page for b3sum. If anything is wrong please tell me/suggest changes.
- **Version of the command being documented (if known):** b3sum 1.3.3

b3sum: add page

---

pages/osx/csrutil.md

`address` suffix is required to be omitted to make placeholder convertible.
Conversion result thanks to fixes:
```md
> Manage the System Integrity Protection configuration
> More information: https://ss64.com/osx/csrutil.html
- Display the System Integrity Protection status:
`csrutil status`
- Disable the System Integrity Protection:
`csrutil disable`
- Enable the System Integrity Protection:
`csrutil enable`
- Display the list of allowed NetBoot sources:
`csrutil netboot list`
- Add an IPv4 address to the list of allowed NetBoot sources:
`csrutil netboot add {string ip}`
- Reset the System Integrity Protection status and clear the NetBoot list:
`csrutil clear` …
```

osx/csrutil.md: make placeholder convertible to CLIP one

---

pages/osx/as.md

- `{{out.o}}` is completely messed up placeholder as there is no `file` keyword inside it and `path/to` prefix, that's why it can't be automatically [recognized](https://github.com/command-line-interface-pages/prototypes/pull/32) as file
- other placeholders are broken but can be interpreted as file as contain `path/to`

osx/as.md: make placeholders auto convertible to CLIP ones

---

pages/osx/cot.md

`line_number` and `column_number` are not automatically convertible, sample integer value is required to make them recognizable by [CLIP converter](https://github.com/command-line-interface-pages/prototypes/pull/32).
Conversion result thanks to fixes:
```md
> The Plain-Text Editor for macOS
> More information: https://coteditor.com/
- Start CotEditor:
`cot`
- Open specific files:
`cot {file* some description}`
- Open a new blank document:
`cot --new`
- Open a specific file and block the terminal until it is closed:
`cot --wait {file some description}`
- Open a specific file with the cursor at a specific line and column:
`cot --line {int some description: 1} …
```

osx/cot.md: make placeholders auto convertible to CLIP ones

---

pages/osx/asr.md

`file` suffix is required to make placeholder convertible.
Conversion result thanks to fixes:
```md
> Restore (copy) a disk image onto a volume
> The command name stands for Apple Software Restore
> More information: https://www.unix.com/man-page/osx/8/asr/
- Restore a disk image to a target volume:
`sudo asr restore --source {file image file with mandatory .dmg extension} --target {file volume file}`
- Erase the target volume before restoring:
`sudo asr restore --source {file image file with mandatory .dmg extension} --target {file volume file} --erase`
- Skip verification after restoring:
`sudo asr restore --source {file image file with mandatory .dmg extension} …
```

osx/asr.md: make placeholders auto convertible to CLIP ones

---

pages/osx/asr.md
pages/osx/codesign.md

`file` suffix is required to make placeholder convertible.
Conversion result thanks to fixes:
```md
> Create and manipulate code signatures for macOS
> More information: https://www.unix.com/man-page/osx/1/codesign/
- Sign an application with a certificate:
`codesign --sign "{string some description: My Company Name}" {file application file with mandatory .app extension}`
- Verify the certificate of an application:
`codesign --verify {file application file with mandatory .app extension}`
```

osx/codesign.md: make placeholders auto convertible to CLIP ones

---

pages/osx/csshx.md
pages/osx/dd.md
pages/osx/dhcp6d.md
pages/osx/diskutil.md
pages/osx/ditto.md
pages/osx/du.md
pages/osx/emond.md
pages/osx/fileicon.md
pages/osx/ftxdiff.md
pages/osx/hdiutil.md
pages/osx/head.md
pages/osx/icalbuddy.md
pages/osx/indent.md
pages/osx/launchctl.md
pages/osx/lipo.md
pages/osx/notifyd.md
pages/osx/readlink.md
pages/osx/security.md
pages/osx/sed.md
pages/osx/sips.md
pages/osx/systemsetup.md
pages/osx/tail.md
pages/osx/tart.md
pages/osx/textutil.md
pages/osx/wacaw.md
pages/osx/whatis.md
pages/osx/xcode-select.md
pages/osx/xml2man.md
pages/osx/xsltproc.md
pages/osx/yaa.md

- https://github.com/command-line-interface-pages/cli-pages/pull/26

osx/*.md: make placeholders more compatible with CLIP ones

---

pages/sunos/prstat.md
pages/sunos/snoop.md
pages/sunos/svccfg.md

- use placeholders for numbers
- use "path/to" and "file": missing "file" suffix breaks placeholder conversion
- simplify ip placeholders: existing "_address" suffix breaks placeholder conversion
These changes are compatible with [this](https://github.com/command-line-interface-pages/prototypes/pull/32) version of TlDr -> CLIP converter and used [here](https://github.com/command-line-interface-pages/cli-pages/pull/27).

sunos/*.md: make placeholders more compatible with CLIP

---

pages/common/tar.md

- use ellipsis
- add path/to prefix
Recreation of [this](https://github.com/tldr-pages/tldr/pull/9881) PR.

tar: update placeholders

---

pages/common/rg.md

Removed the --type flag as that command needs one to go through `man rg` to figure out which arguments work for the filetype

rg: Add example for searching filenames

---

pages/android/dumpsys.md

- `seconds` keyword is not recognized, but concrete integer value is

dumpsys.md: make integer placeholder convertible to CLIP placeholder

---

.gitattributes
contributing-guides/git-terminal.md

---
Above is N/A.
Replaces manual instructions with the .gitattributes config that should achieve the same thing. No manual commands or documentation necessary.
If we could just get someone on Windows to test if they can reproduce the original problem, and if this fixes it, we should be fine to merge this.
* https://github.com/tldr-pages/tldr/pull/9010

.gitattributes: specify eol as LF

---

pages/common/gcc.md

- **Version of the command being documented (if known):12.2.1**

gcc: fix typo

---

pages/common/clip-view.md
pages/common/md-to-clip.md

- **Version of the command being documented (if known):** latest
TlDr pages for other CLIP project tools will be added later. Accepting this PR will help my project gain more popularity, thanks for understanding.

Add Command Line Interface Pages project support

---

pages/linux/gummy.md

- **Version of the command being documented (if known): [0.4](https://github.com/Fushko/gummy/releases/tag/0.4)**
[Release 0.4](https://github.com/Fushko/gummy/releases/tag/0.4) for gummy split the single brightness flag into 2 different brightness controls - monitor backlight and pixel brightness. This tldr page addresses that and aims to make the separation clear for new and existing users. The relative value support was added in 0.4 which is also covered in the tldr page.

gummy: add page

---

pages/osx/split.md

OSX also has the same option with the same syntax.
Note: The link https://ss64.com/osx/split.html does not match my local documentation (has only `-b` and `-l`). I was unable to find a reputable sources that follows the exact documentation below. The closest I found was https://nxmnpg.lemoda.net/1/split but I don't know how reputable this website is. I have kept the link the same.
```
$ man split
SPLIT(1)                                                                        General Commands Manual                                                                        SPLIT(1)
~
NAME
split – split a file into pieces
~
SYNOPSIS
split -d [-l line_count] [-a suffix_length] [file [prefix]]
split -d -b byte_count[K|k|M|m|G|g] [-a suffix_length] [file [prefix]]
split -d -n chunk_count [-a …
```

split: update page

---

pages/linux/grub-set-default.md

It resolves part of issue #8080

grub-set-default: add page

---

pages/common/openvpn.md

Usage of `openvpn --genkey --secret` is deprecated. One should use `openvpn --genkey secret` instead.
`openvpn --genkey --secret [file]` results in `WARNING: Using --genkey --secret filename is DEPRECATED.  Use --genkey secret filename instead.`
- **Version of the command being documented (if known):** 2.5.1

openvpn: update command

---

pages/linux/handlr.md

- **Version of the command being documented (if known):0.6.4**
I have based this page largely on the Usage section of the README.md file in the handlr project as well as the [xdg-mime.md page](https://github.com/tldr-pages/tldr/blob/main/pages/linux/xdg-mime.md).

handlr: add page

---

pages/linux/sed.md

The original description makes it sound like sed would wait for additional input while it actually just modifies the specified file in-place.
- **Version of the command being documented (if known):** GNU sed 4.8

sed: improve description of -i option

---

pages/common/ffmpeg.md

[as far as i can tell](https://ffmpeg.org/ffmpeg.html#Stream-specifiers-1), the syntax does not use `:video` and `:audio` for the stream specifier, and instead uses `:v` and `:a`, respectively
these are the errors i received:
`Invalid stream specifier: video`, `Invalid stream specifier: audio`
i'm on version 4.4.2, on ubuntu
`ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1)`
- 4.4.2

ffmpeg: update syntax for the -codec switch

---

pages/common/az-repos.md

az-repos: add page

---

pages/linux/systemd-run.md

- **Version of the command being documented (if known):** systemd-253

systemd-run: add page

---

.github/ISSUE_TEMPLATE/config.yml
COMMUNITY-ROLES.md
CONTRIBUTING.md
GOVERNANCE.md
MAINTAINERS.md
README.md
contributing-guides/maintainers-guide.md

- Update Gitter Links to Matrix.
- Discussion: [here](https://matrix.to/#/!zXiOpjSkFTvtMpsenJ:gitter.im/$Fte7Zjp0XTMZnFac-B3aezKf206I--jMNh45AfYQnWk?via=gitter.im&via=matrix.org&via=one.ems.host)

Community: Update Gitter links to Matrix, Update Badges, Remove editor extensions

---

pages.de/common/aircrack-ng.md

Translated the current aircrack-ng.md into german.

aircrack-ng: add German translation

---

pages/common/mcfly.md

Creates a new page in common for [McFly](https://github.com/cantino/mcfly), a fast and intelligent
command history search engine.
**Version of the command being documented (if known):** 0.8.0

mcfly: add page

---

pages.es/android/logcat.md
pages.es/common/adb-logcat.md
pages/android/logcat.md
pages/common/adb-logcat.md

adb-logcat, logcat: add --pid examples

---

pages/common/pwsh.md

Since #7984, `powershell` is in `common`. This makes `pwsh` an alias of it, as AFAIK it should be.
Closes #7194.

pwsh: refresh page

---

pages/linux/ifmetric.md

- **Version of the command being documented (if known):** Not known
---
For those of you with more than one network adapter, sometimes you might be connected to more than one network, right? i.e. on Wi-Fi + Ethernet for laptop users.
I noticed that some of my traffic was going over Wi-Fi for some reason even though I'm connected via Ethernet. (They both ultimately hit the same router, so there's no benefit to this.) :thinking: 
This lets you configure the priority interfaces should have when you're connected to multiple, so you can indicate which is fastest or should handle traffic first if available.
i.e. If you want to stay connected to Wi-Fi as a fallback, but don't want to use `wlo1` unless `enp6s0` is down:
```sh
sudo ifmetric wlo1 1
```

ifmetric: add page

---

pages/common/git-am.md
pages/common/git-apply.md

`curl` now uses the `-L` option to follow redirects, which is required
when applying patch files from GitHub URLs. The example was also added
to `git-am` where it works too.
The difference between `git-am` and `git-apply` was also clarified in each
command's description.
- **Version of the command being documented (if known):** Git 2.39.2, curl 7.85.0 (Linux). `curl -L` has been around for a long time, so even very old curl versions support it.

git-am, git-apply: add and tweak remote patch examples

---

pages/common/cmake.md

Given that the selection of generator can significantly impact project build times, I think adding the `-G` flag to the CMake page would be useful. This PR adds a short example for using this flag.
PS: First time contributing so let me know if I missed any steps in your typical workflow 

cmake: add generator flag, help example

---

pages.de/common/airodump-ng.md

Translated the current airodump-ng.md into German.

airodump-ng: add German Translation

---

pages/linux/obabel.md

tool to convert between chemistry files
- **OpenBabel 3.1.1**

obabel: add page
