tldr-pages/tldr

pages.de/common/aws-codecommit.md
=> aws-codecommit: add German translation

pages.de/common/arp.md
=> arp: add German translation

pages/linux/systemd-analyze.md, pages/linux/systemd-run.md
=> systemd-analyze, systemd-run: update page

pages/common/molecule.md
=> molecule: add command

pages/common/lua.md, pages/common/luajit.md
=> luajit: add page, lua: update page

pages/common/chroma.md
=> chroma: update page

pages/common/hugo.md
From https://github.com/tldr-pages/tldr/pull/9578
=> hugo: fix command

pages/linux/unix2dos.md
From https://github.com/tldr-pages/tldr/pull/9578
=> unix2dos: update page

pages/linux/unix2mac.md
=> unix2mac: update placeholders

pages.nl/common/2to3.md, pages.nl/common/7za.md, pages.nl/common/7zr.md
---
I added curly braces for `-mhe=on` since that's the convention. I have updated the other languages in this PR:
* https://github.com/tldr-pages/tldr/pull/10217
=> 2to3, 7za, 7zr: Dutch translations

pages.fr/android/input.md
---
Looks like someone left an English string. Using LibreTranslate, the line below is probably the French version of the line above.
=> input: remove english sentence from fr

pages.it/common/eslint.md, pages.pl/common/eslint.md, pages/common/eslint.md
=> eslint: update path placeholder

pages/common/git-merge.md
=> git-merge: update page

pages.es/common/aws-iam.md
=> aws-iam: add Spanish translation

pages.es/common/aws-help.md
=> aws-help: add Spanish translation

pages.it/windows/clip.md
=> clip: add Italian translation

pages.es/common/aws-google-auth.md
=> aws-google-auth: add Spanish translation

pages/common/b2sum.md, pages/common/b3sum.md, pages/common/md5sum.md, pages/common/sha1sum.md, pages/common/sha224sum.md, pages/common/sha256sum.md, pages/common/sha384sum.md, pages/common/sha512sum.md, pages/common/shasum.md
---
All checksum pages were written in a slightly different way, this PR makes them all consistent (same examples, just different command).
=> *sum: update pages to make them consistent

pages/common/tslint.md
=> tslint: update path placeholder

pages/common/ocamlfind.md
=> ocamlfind: update path placeholders

pages/linux/sensible-editor.md
=> sensible-editor: update path placeholder

pages.es/osx/yaa.md
=> yaa: add Spanish translation

pages.es/osx/xsltproc.md
=> xsltproc: add Spanish translation

pages.es/common/autossh.md
=> autossh: add Spanish translation

pages.es/common/aws-cur.md
=> aws-cur: add Spanish translation

pages/common/sc-im.md
=> sc-im: update placeholder

pages/common/csvkit.md
=> csvkit: update page

pages.de/common/docker-start.md, pages.fr/common/docker-start.md, pages.pt_BR/common/docker-start.md, pages.tr/common/docker-start.md, pages/common/docker-start.md
=> docker-start: update placeholder

pages.de/common/vifm.md, pages/common/vifm.md
=> vifm: update path placeholder

pages/common/mutool.md
From #9578
- Updated placeholders.
- Updated link to readthedocs directly.
=> mutool: update page

pages.fr/common/hping.md, pages/common/hping.md, pages/common/hping3.md
=> hping, hping3: update page

pages/common/mitmproxy.md, pages/common/mitmweb.md
- **Version of the command being documented (if known): 9.0.1 (both commands)**
=> mitmweb: add page, mitmproxy: update page

pages.ja/common/curl.md
=> curl: add Japanese translation

pages.pl/linux/sqfscat.md, pages/linux/sqfscat.md
=> sqfscat: add page and Polish translation

pages/common/git-mv.md
From https://github.com/tldr-pages/tldr/pull/9578
=> git-mv: update page

pages.zh/osx/ipconfig.md, pages/osx/ipconfig.md
=> ipconfig: add page and Chinese translation

pages.nl/common/aapt.md, pages.nl/common/ab.md, pages.nl/common/abduco.md
=> aapt, ab, abduco: Dutch translations

.github/dependabot.yml
This will cause dependabot to check all the package dependencies which this project uses for updates in order to keep everything up-to-date.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
=> dependabot.yml: check for package updates monthly

pages/common/airshare.md
- **Version of the command being documented (if known): 0.1.6**
=> airshare: add page

pages.de/common/git-config.md
=> git-config: add German translation

pages.nl/common/ac.md, pages.nl/common/ack.md, pages.nl/common/acme.sh-dns.md, pages.nl/common/acme.sh.md
=> ac, ack, acme.sh, acme.sh-dns: add Dutch translation

pages.nl/common/act.md, pages.nl/common/acyclic.md, pages.nl/common/adb-install.md, pages.nl/common/adb-logcat.md
=> act, acyclic, adb-logcat, adb-install: add Dutch translation

pages/linux/xset.md
Give information about disabling annoying bell sound
=> xset: add disable bell command

pages.es/common/at.md
=> at: add Spanish translation

pages.es/osx/auvaltool.md
=> auvaltool: add Spanish translation

pages/common/xzmore.md
=> xzmore: add page

pages/common/lzegrep.md, pages/common/lzfgrep.md, pages/common/lzgrep.md, pages/common/lzless.md, pages/common/lzmore.md, pages/common/xzegrep.md, pages/common/xzfgrep.md
=> xz*, lz*: add alias pages

pages.nl/common/adb-reverse.md, pages.nl/common/adb-shell.md, pages.nl/common/adguardhome.md
=> adb-reverse, adb-shell, adguardhome: add Dutch translation

pages.ca/linux/pkgadd.md, pages.ca/linux/pkgrm.md, pages.es/linux/pkgadd.md, pages.es/linux/pkgrm.md, pages.id/common/java.md, pages.pl/common/java.md, pages.pt_BR/common/java.md, pages.pt_BR/common/javac.md, pages.ta/common/java.md, pages.ta/common/javac.md, pages.zh/common/jarsigner.md, pages.zh/common/java.md, pages.zh/common/javac.md, pages.zh/common/javadoc.md, pages.zh/common/jmap.md, pages.zh/common/jps.md, pages/common/jarsigner.md, pages/common/java.md, pages/common/javac.md, pages/common/javadoc.md, pages/common/javap.md, pages/common/jdeps.md, pages/common/jmap.md, pages/common/jps.md, pages/common/keytool.md, pages/common/serialver.md, pages/linux/pkgadd.md, pages/linux/pkgmk.md, pages/linux/pkgrm.md
=> pages.*: update Java links

pages.zh/common/act.md
=> act: update Chinese translation

pages/common/git-clone.md
=> git-clone: update page

pages.it/common/ls.md
=> ls: update Italian translation

pages/common/minifab.md
=> minifab: fix typo

pages/linux/tc.md
=> tc: fix typo

pages/common/musl-gcc.md
=> musl-gcc: add page

pages.zh/common/git-remote.md
=> git-remote: update Chinese translation

pages.zh/common/git-config.md
=> git-config: update Chinese translation

pages.nl/common/adscript.md, pages.nl/common/afconvert.md, pages.nl/common/ag.md, pages.nl/common/agate.md, pages.nl/common/age.md
=> adscript, afconvert, ag, agate, age: add Dutch translation

pages/common/bash.md
=> bash: add restricted shell command

pages.es/osx/w.md, pages/osx/w.md
=> w: add Spanish translation, update page

MAINTAINERS.md
Signed-off-by: Muhammad Falak R Wani <falakreyaz@gmail.com>
Closes: #10053
=> MAINTAINERS: add @mfrw as org owner

pages/osx/xcrun.md
=> xcrun: swap help and version examples

pages/linux/dpkg-reconfigure.md
=> dpkg-reconfigure: add page

pages/common/vale.md
=> vale: fix minAlertLevel parameter

pages.zh/osx/wifi-password.md
=> wifi-password: update Chinese translation

pages.it/common/git-init.md
=> git-init: update Italian translation

.github/ISSUE_TEMPLATE/page-request.yml, .github/workflows/stale.yml
Ref. https://www.codefactor.io/repository/github/tldr-pages/tldr/issues#
=> .github: fix trailing spaces and lines

pages/common/age.md
=> age: reword example

pages/linux/bchunk.md
=> bchunk: add page

pages/common/lzcmp.md
Continuation of #10185, because I forgot about one page.
=> lzcmp: add alias page

pages/linux/pacman.md
=> pacman: replace -Ss example by -F

pages/common/mods.md
- **Version of the command being documented (if known): v0.2.0**
=> mods: add page

pages/common/mods.md
I misplaced quotes in my suggestion in #10391.
=> mods: fix quoting

MAINTAINERS.md
=> MAINTAINERS: add @kbdharun as org owner

MAINTAINERS.md
=> MAINTAINERS: add @acuteenvy as org member

pages/common/rustc.md
=> rustc: update page

pages/linux/systemd-delta.md
=> systemd-delta: add page

pages/common/datashader_cli.md
=> datashader_cli: add page

pages.id/android/logcat.md, pages.id/android/screencap.md
1. screencap: command description
2. logcat: translate new English command examples
=> android/*: update Indonesian translations

pages.ta/common/rustup-init.sh.md
=> rustup-init.sh: add Tamil translation

pages/common/cb.md
- **Version of the command being documented (if known):** 0.8.0
=> cb: add page

pages/osx/valet.md
=> valet: update page

pages.es/osx/aiac.md
=> aiac: add Spanish translation

pages/common/bzip3.md
=> bzip3: add page

pages/common/weechat.md
=> weechat: add backticks on stdout

pages.zh/common/go-build.md
=> go-build: update Chinese translation

pages.zh/common/gpg.md
=> gpg: update Chinese translation

pages.es/osx/m.md
=> m: add Spanish translation

pages.es/osx/usernoted.md
=> usernoted: add Spanish translation

pages.es/osx/osascript.md
=> osascript: add Spanish translation

pages/windows/cmdkey.md
=> cmdkey: add page

pages/windows/sc.md
=> sc: add page

pages/linux/trayer.md
- **Version of the command being documented (if known):** 1.1.8-3
---
Closes #10440.
=> trayer: add page

pages/linux/mount.cifs.md, pages/linux/mount.smb3.md
=> mount.{cifs,smb3}: add page

pages.es/osx/xml2man.md
=> xml2man: add Spanish translation

pages.es/windows/getmac.md
=> getmac: add Spanish translation

pages.es/osx/opensnoop.md
=> pensnoop: add Spanish translation

pages.es/osx/spctl.md
=> spctl: add Spanish translation

MAINTAINERS.md
Close #10054.
It's an honor for me. Hope that I can spare more time to devote to this project better next year.
=> MAINTAINERS: Add @blueskyson to org owner, Update page

pages/linux/swaplabel.md
=> swaplabel: add page

pages/common/cavif.md
- **Version of the command being documented (if known):** 1.5.3
=> cavif: add page

pages/common/fold.md, pages/common/head.md, pages/linux/fold.md
=> head, fold: update links

pages/common/exfatlabel.md
=> exfatlabel: add page

pages/common/ffplay.md
Add nodisp option and an example of piping into ffplay
=> ffplay: add more examples

pages.es/osx/java_home.md
=> java_home: add Spanish translation

pages.de/common/bgpgrep.md, pages.de/common/peerindex.md
=> bgpgrep, peerindex: add German translation

pages.es/osx/uname.md
=> uname: add Spanish translation

pages.es/common/autoflake.md
=> autoflake: add Spanish translation

pages/common/whisper.md
Fix a typo in the example command
=> whisper: fix typo

pages/common/nping.md
- **Version of the command being documented (if known):** 0.7.93
=> nping: add page

pages/windows/ipconfig.md
=> ipconfig: add local dns cache example

pages/linux/qm-suspend.md
=> qm-suspend: add page

pages/common/yard.md
- **Version of the command being documented (if known):** 0.9.34
=> yard: add page

pages/windows/net.md
=> net: add page

pages.de/common/babeld.md, pages.de/common/bird.md, pages.de/common/birdc.md, pages.de/common/fastd.md, pages.de/common/pystun3.md, pages.de/common/stun.md, pages/common/birdc.md, pages/common/fastd.md
=> birdc, fastd: remove double colon; babeld, bird, birdc, fastd, pystun3, stun: add German translation

pages/common/traceroute.md
- **Version of the command being documented (if known):** `Modern traceroute for Linux, version 2.1.0`
=> traceroute: update page

pages/linux/v4l2-ctl.md
Changed one of the video device filepaths to be relative and added a new entry for setting a value.
=> v4l2-ctl: update page

pages/common/mtr.md
- **Version of the command being documented (if known):** 0.94
=> mtr: update page

pages/linux/xbps-install.md, pages/linux/xbps-query.md, pages/linux/xbps-remove.md, pages/linux/xbps.md
=> xbps-{install,remove,query}: add page; xbps: update page

pages.es/common/axel.md
=> axel: add Spanish translation

pages/common/minikube.md
=> minikube: add `tunnel` example

pages/common/supervisorctl.md
Add status example. IMHO it is helpful as it lets you know the process names you can use for the subsequent examples.
- **Version of the command being documented (if known):** 3.3.5
=> supervisorctl: add `status` example

pages/linux/systemd-mount.md, pages/linux/systemd-umount.md
=> systemd-mount: add page; systemd-umount: add alias page

pages/linux/mmcli.md
=> mmcli: add examples

pages.es/osx/xsand.md
=> xsand: add Spanish translation

pages/linux/nmcli.md
=> nmcli: add examples

pages/linux/cam.md
=> cam: add page

pages.es/osx/coreaudiod.md
=> coreaudiod: add Spanish translation

pages/common/echo.md
=> echo: add exit code command

pages/osx/ps.md
Remove commands that don't work, add correct sorting commands.
- **Version of the command being documented (if known):** BSD/macOS 13.4 March 20, 2005
=> ps: add OSX page

pages/common/tectonic.md
- **Version of the command being documented (if known):** 0.14.1
=> tectonic: add page

pages.es/osx/lipo.md
=> lipo: add Spanish translation

pages/linux/pw-play.md
=> pw-play: remove list all playback targets example

pages.es/osx/shuf.md
=> shuf: add Spanish translation

pages.es/osx/fsck.md
=> fsck: add Spanish translation

pages.es/osx/cot.md
=> cot: add Spanish translation

pages/common/gst-inspect-1.0.md, pages/common/gst-launch-1.0.md
=> gst-launch-1.0, gst-inspect-1.0: add page

pages.nl/common/airmon-ng.md, pages.nl/common/airodump-ng.md, pages.nl/common/airpaste.md, pages.nl/common/airshare.md, pages.nl/common/ajson.md, pages.nl/common/alacritty.md, pages.nl/common/alex.md
=> airmon-ng, airodump-ng, airpaste, ajson, alacritty, alex: add Dutch translation

pages/common/ooniprobe.md
OONI Probe Cli User Guide: https://ooni.org/support/ooni-probe-cli
- **Version of the command being documented (if known):** 3.18.1
=> ooniprobe: add page

pages/common/lando.md
=> lando: add page

pages/linux/usbip.md
=> usbip: add page

pages.es/osx/open.md
=> open: add Spanish translation

pages/linux/help.md
=> help: add page

pages/common/conda-install.md
=> conda install: add page

pages/linux/avifenc.md
=> avifenc: update page

pages/linux/wg.md
=> wg: edit page

pages/common/mongo.md, pages/common/mongod.md, pages/common/mongosh.md
=> mongo, mongod: update page; mongosh: add page

pages/linux/nmcli-agent.md, pages/linux/nmcli-connection.md, pages/linux/nmcli-device.md, pages/linux/nmcli-radio.md, pages/linux/nmcli.md
=> nmcli*: update pages

pages/linux/!.md
=> !: add page

pages/linux/wpctl.md
=> wpctl: add page

pages.es/osx/ed.md
=> ed: add Spanish translation

pages.es/osx/dhcp6d.md
=> dhcp6d: add Spanish translation

pages.es/osx/dot_clean.md
=> dot_clean: add Spanish translation

pages/common/case.md
=> case: update description

pages/linux/select.md
=> select: add page

pages.pt_BR/common/hexdump.md
=> hexdump: add pt_BR translation

pages/common/pop.md
- **Version of the command being documented (if known): v0.2.0**
=> pop: add page

pages/linux/mediamtx.md
=> mediamtx: add page

pages/linux/fluidsynth.md
=> fluidsynth: add page

pages/common/pydoc.md
=> pydoc: add page

pages/common/while.md
=> while: replace incorrect link

pages/linux/pkgctl.md
=> pkgctl: add page

pages.es/osx/xip.md
=> xip: add Spanish translation

pages.es/osx/valet.md
=> valet: add Spanish translation

pages.es/osx/xcode-select.md
=> xcode-select: add Spanish translation

pages.es/osx/webinspectord.md
=> webinspectord: add Spanish translation

pages/common/gem.md, pages/common/irb.md, pages/common/rake.md, pages/common/ruby.md
=> ruby, gem: update page; irb, rake: add page

pages.es/osx/ping.md
=> ping: add Spanish translation

pages.es/osx/wps.md
=> wps: add Spanish translation

pages.es/osx/whatis.md
=> whatis: add Spanish translation

pages.es/osx/wwand.md
- [] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
=> wwand: add Spanish translation

pages.es/osx/xartstorageremoted.md
=> xartstorageremoted: add Spanish translation

pages.es/common/atoum.md
=> atoum: add Spanish translation

pages.es/osx/top.md
=> top: add Spanish translation

pages.es/osx/sw_vers.md
=> sw_vers: add Spanish translation

pages.es/osx/shortcuts.md
=> shortcuts: add Spanish translation

pages.es/osx/xcrun.md
=> xcrun: add Spanish translation

pages.es/osx/llvm-lipo.md
=> llvm-lipo: add Spanish translation

pages.es/osx/lldb.md
=> lldb: add Spanish translation

pages.es/osx/pbpaste.md
=> pbpaste: add Spanish translation

pages.es/osx/safeejectgpu.md
=> safeejectgpu: add Spanish translation

pages.es/osx/diskutil.md
=> diskutil: add Spanish translation

pages/common/age-keygen.md, pages/common/age.md
=> age-keygen: add page; age: update page

pages/linux/nm-online.md, pages/linux/nmtui-connect.md, pages/linux/nmtui-edit.md, pages/linux/nmtui-hostname.md
=> nm-online: add page; nmtui-{connect,edit,hostname}: add alias pages

pages/common/popd.md, pages/common/pushd.md
The PR updates pushd and popd pages and adds `-n` option.
=> popd: add '-n' option; pushd: add '-n' option

pages.es/osx/internetsharing.md
=> internetsharing; add Spanish translation

pages.es/osx/sips.md
=> sips: add Spanish translation

pages.es/osx/nvram.md
=> nvram: add Spanish translation

pages.ja/common/colorls.md
=> colorls: add Japanese translation

pages.es/osx/terminal-notifier.md
=> terminal-notifier: add Spanish translation

pages.es/osx/photoanalysisd.md
=> photoanalysisd: add Spanish translation

pages/common/time.md
=> time: update page

pages.es/osx/bc.md
=> bc: add Spanish translation

pages.es/osx/hidd.md
=> hidd: add Spanish translation

pages/osx/system_profiler.md
=> system_profiler: update page

pages/linux/mkhomedir_helper.md
=> mkhomedir_helper: add page

pages/common/qdbus.md
=> qdbus: edit page

pages/linux/pkgctl-auth.md
=> pkgctl-auth: add page

pages/linux/pkgctl-version.md
=> pkgctl-version: add page

pages.es/osx/reboot.md
=> reboot: add Spanish translation

pages.es/osx/readlink.md
=> readlink: add Spanish translation

pages.es/osx/ctkd.md
=> ctkd: add Spanish translation

pages.es/osx/csrutil.md
=> csrutil: add Spanish translation

pages.es/osx/csshx.md
=> csshx: add Spanish translation

pages.es/osx/bnepd.md
=> bnepd: add Spanish translation

pages.es/osx/bless.md
=> bless: add Spanish translation

pages.es/osx/appsleepd.md
=> appsleepd: add Spanish translation

pages.es/osx/emond.md
=> emond: add Spanish translation

pages.es/osx/fdesetup.md
=> fdesetup: add Spanish translation

pages/linux/pkgctl-diff.md
=> pkgctl-diff: add page

pages/common/aws-batch.md
=> aws-batch: add page

pages/common/kismet.md
=> kismet: add page

pages.es/osx/ftxdiff.md
=> ftxdiff: add Spanish translation

pages/linux/mkswap.md, pages/linux/swapoff.md, pages/linux/swapon.md
=> mkswap, swap{on,off}: update page

pages/common/timetrap.md
=> timetrap: add command to edit last entry

pages.es/common/docker-compose.md, pages/common/docker-compose.md
Co-authored-by: Lucy Diniz <lucydiniz.rs@gmail.com>
I'll be happy to contribute more to this amazing project ^^
=> docker-compose: run specifying a project name (#10596)

pages.es/osx/dd.md
=> dd: add Spanish translation

pages/common/nix3-run.md
=> nix3-run: add more examples

pages.id/common/clamav.md, pages.id/common/clamdscan.md, pages.id/common/clamscan.md, pages.id/common/freshclam.md
1. clamav: update Indonesian translation
2. clamdscan, clamscan, freshclam: add Indonesian translation
The `clamav` page was considered to be an alias page of `clamdscan`, but there was no Indonesian translation for `clamdscan`.
=> clamav, clamdscan, clamscan, freshclam: update Indonesian translations

pages/linux/systemd-path.md
=> systemd-path: add page

pages/common/watchexec.md
=> watchexec: update page

pages/common/ncu.md
- add tldr page for npm package `npm-check-updates`
- how to install package 
- `npm install -g node-check-updates`
- how to list oudated packages in current folder
- `ncu` - how to list outdated global packages
- `ncu -g` 
- how to upgrade all packages in current folder 
- `ncu -u && npm install` 
- how to interactively upgrade npm package in current folder 
- `ncu -i && npm install` 
- how to view `ncu` options 
- `ncu -h`
- useful command for listing outdated npm packages
- ./pages/common/ncu.md
tldr -u
tldr ncu
---
=> ncu: add page

pages/common/mvn.md
=> mvn: fix typo

pages/linux/optimus-manager.md
=> optimus-manager: add page

pages/common/checksec.md
- **Version of the command being documented (if known): v2.6.0**
=> checksec: add page

pages/common/objdump.md
- **Version of the command being documented (if known): 2.41.0**
=> objdump: add -x example

pages/common/shar.md, pages/linux/shar.md
Based on #9412
Closes #9344
- **Version of the command being documented (if known):** 4.4BSD, GNU sharutils 4.13.3
=> shar: add page

pages.de/common/base64.md
this is what every other page uses:
```terminal
$ grep -R '{{befehl}}' pages.de
pages.de/osx/caffeinate.md:`caffeinate -s {{befehl}}`
pages.de/common/sshpass.md:`sshpass -f {{pfad/zu/datei}} ssh -o StrictHostKeyChecking=no {{benutzer}}@{{server}} "{{befehl}}"`
pages.de/common/aws-codecommit.md:`aws codecommit {{befehl}} help`
pages.de/common/ssh.md:`ssh {{externer_server}} {{befehl}}`
pages.de/common/docker-exec.md:`docker exec --detach {{container_name}} {{befehl}}`
pages.de/common/docker-exec.md:`docker exec --interactive -tty --workdir {{pfad/zum/verzeichnis}} {{container_name}} {{befehl}}`
pages.de/common/docker-exec.md:`docker exec --interactive --detach {{container_name}} {{befehl}}`
pages.de/common/docker-exec.md:`docker exec --user {{benutzer}} {{container_name}} {{befehl}}` …
```
=> de/base64: replace kommando with befehl

pages/common/packwiz.md
=> packwiz: add page

CLIENT-SPECIFICATION.md, contributing-guides/maintainers-guide.md, pages.fr/android/bugreport.md, pages.fr/android/bugreportz.md, pages.fr/android/dumpsys.md, pages.fr/android/input.md, pages.fr/android/pm.md, pages.fr/android/wm.md
=> /*: fix typos

pages/common/texcount.md
=> texcount: add page

pages/linux/schroot.md
=> schroot: add session examples, move --list to the top

pages/common/ropper.md
- **Version of the command being documented (if known): 1.13.8**
=> ropper: add page

pages/common/ropgadget.md
- **Version of the command being documented (if known): v7.3**
=> ROPgadget: add page

pages/windows/uwfmgr.md
=> uwfmgr: add page

pages/common/rustup-check.md, pages/common/rustup-default.md, pages/common/rustup-show.md, pages/common/rustup-target.md, pages/common/rustup-toolchain.md, pages/common/rustup-update.md, pages/common/rustup.md
=> rustup: update page, rustup-{show,update,check,default,toolchain,target}: add page

pages/linux/systemd-tty-ask-password-agent.md
=> systemd-tty-ask-password-agent: add page

pages/common/liquidctl.md
=> liquidctl: add page

pages/common/cs.md, pages/common/git.md, pages/common/nix.md
https://github.com/tldr-pages/tldr/pull/10642#discussion_r1309350345
=> cs, git, nix: remove "accessible via `tldr command subcommand`"

pages/common/stressapptest.md
=> stressapptest: add page

MAINTAINERS.md
=> MAINTAINERS: add @Managor as collaborator

pages/linux/systemd-tmp-files.md, pages/linux/systemd-tmpfiles.md
=> systemd-tmpfiles: add page

pages/common/unzstd.md, pages/common/zstd.md, pages/common/zstdcat.md, pages/common/zstdmt.md
=> zstd, unzstd: update page; zstd{cat,mt}: add alias page

pages.ko/common/ab.md
=> ab: update Korean translation

MAINTAINERS.md
=> MAINTAINERS: remove @schneiderl from Organization Owners

pages/linux/abroot.md
**Disclosure**: I am a maintainer at Vanilla OS. The future version of docs can be found [here](https://github.com/Vanilla-OS/documentation/blob/main/articles/en/abroot-manpage.md).
=> abroot: update page

pages/linux/ikaros.md, pages/linux/vso.md
**Disclosure:** I am a maintainer at Vanilla OS. The future version of docs can be found [here](https://github.com/Vanilla-OS/documentation/blob/main/articles/en/ikaros-manpage.md).
=> ikaros: add page; vso: update page

pages/common/l2ping.md
=> l2ping: add page

pages/common/cargo-help.md, pages/common/cargo-version.md
=> cargo-{help,version}: add page

pages/common/eza.md
Ported existing exa to eza now that exa is no longer maintained
=> eza: add page

pages/common/op.md
=> op: add page

pages.es/osx/mdfind.md
=> mdfind: add Spanish translation

pages.es/osx/nettop.md
=> nettop: add Spanish translation

pages/linux/!.md
=> !: edit page

pages/osx/xcodes-runtimes.md, pages/osx/xcodes.md
=> xcodes, xcodes-runtimes: add page

pages/common/stylua.md
=> stylua: add page

pages/common/bun.md
=> bun: add page

pages/linux/systemd-detect-virt.md
=> systemd-detect-virt: add page

pages/linux/ip6tables-restore.md, pages/linux/ip6tables-save.md, pages/linux/ip6tables.md, pages/linux/iptables-restore.md, pages/linux/iptables-save.md, pages/linux/iptables.md
=> iptables: update page; ip6tables, ip{6,}tables-{restore,save}: add page

pages/common/socat.md
=> socat: update page

pages/linux/dracut.md, pages/linux/lsinitrd.md
=> dracut, lsinitrd: add page

pages/linux/apx-pkgmanagers.md, pages/linux/apx-stacks.md, pages/linux/apx-subsystems.md, pages/linux/apx.md
**Disclosure**: I am a maintainer at Vanilla OS. The future version of docs can be found [here](https://github.com/Vanilla-OS/documentation/blob/main/articles/en/apx-manpage.md)
=> apx: update page; apx-{pkgmanagers,stacks,subsystems}: add page

pages.ko/android/bugreport.md
=> bugreport: add Korean translation

pages.ko/android/am.md
=> am: add Korean translation

pages.ko/common/aws-backup.md
=> aws-backup: add Korean translation

pages/common/cargo-init.md, pages/common/cargo-new.md, pages/common/cargo.md
=> cargo: update page; cargo-{init,new}: add page

pages/common/devcontainer.md
=> devcontainer: add page

pages/common/cargo-update.md
Related issue: https://github.com/tldr-pages/tldr/issues/10630
=> cargo-update: add page

pages.pt_BR/android/logcat.md
=> logcat: update pt_BR translation

pages.tr/linux/trash.md
=> trash: fix typo in Turkish translation

pages/common/cargo-check.md
related issue: https://github.com/tldr-pages/tldr/issues/10630
=> cargo-check: add page

pages.es/linux/grub-mkconfig.md
- [ x ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ x ] The page description(s) have links to documentation or a homepage.
- [ x ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ x ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
=> grub-mkconfig: add Spanish translation

pages/common/shellcheck.md
=> shellcheck: fix typo

pages/common/w3m.md
`w3m version w3m/0.5.3+git20230121`
=> w3m: update page, fix invalid options

pages/linux/lchage.md
=> lchage: add page

pages/linux/mkosi.md
- **Version of the command being documented (if known):** v16
Closes #10692
=> mkosi: add page

.github/CODEOWNERS
Message (for @kant): after this PR is merged, you will be requested a review automatically on PRs when Spanish pages are added/modified. This is optional if you don't want to be requested a review by default close this PR.
=> CODEOWNERS: add @kant for Spanish pages

pages/common/idea.md
=> idea: add page

pages/linux/hwinfo.md
=> hwinfo: update documentation link

pages/linux/aa-complain.md, pages/linux/aa-disable.md, pages/linux/aa-enforce.md, pages/linux/aa-status.md
=> aa-*: add pages

pages/linux/tod.md
=> tod: add page

pages/common/flutter-pub.md, pages/common/flutter.md
- **Version of the command being documented (if known):** Flutter 3.13.1
=> flutter: update page; flutter-pub: add page

pages/common/cargo-clean.md, pages/common/cargo-fmt.md
=> cargo-{clean,fmt}: add page

pages/common/flutter.md
=> flutter: update page

pages/linux/bcachefs.md
=> bcachefs: add page

pages.ko/common/aws-cloudwatch.md
=> aws-cloudwatch: add Korean translation

pages/osx/goku.md
=> goku: add page

pages.pt_BR/osx/xcodes-runtimes.md, pages.pt_BR/osx/xcodes.md
=> xcodes*: add pt_BR translation

pages/common/readonly.md
=> readonly: add page

pages/common/cargo-fix.md
=> cargo-fix: add page

pages/common/cargo-bench.md
=> cargo-bench: add page

pages/linux/protonvpn-cli.md
- **Version of the command being documented (if known):** 3.13
=> protonvpn-cli: add mention of associated page

pages.ca/linux/halt.md, pages.es/linux/halt.md, pages.id/linux/halt.md, pages.it/linux/halt.md, pages/linux/halt.md
=> */halt: update link to `manned`

pages.es/linux/dnf.md
=> dnf: fix typo in Spanish translation

pages.fr/common/drill.md
=> drill: add French translation

pages.fr/linux/resolvectl.md
=> resolvectl: add French translation

scripts/pdf/render.py, scripts/send-to-bot.py, scripts/set-alias-page.py, scripts/set-more-info-link.py
- This updates some of the python scripts to modern standards using `f-strings` instead of addition concatenation.
- This PR also removes some unneeded else blocks 
- This PR converts an instance of a `for-loop` to using the python `next` operator
=> scripts/*.py: update coding style

pages.fr/linux/reboot.md, pages/linux/reboot.md
=> reboot: update French translation, update halt description

pages/common/magick.md
Update according to example at https://imagemagick.org/Usage/resize/
- `magick --version`
Version: ImageMagick 7.1.1-18 Q16-HDRI x86_64 21582 https://imagemagick.org
=> magick: update resizing example

pages/linux/waydroid.md
Add page for common waydroid commands.
Related issue: https://github.com/tldr-pages/tldr/issues/10668
=> waydroid: add page

pages/common/cargo-remove.md
=> cargo-remove: add page

pages/common/compare.md, pages/common/convert.md, pages/common/identify.md, pages/common/import.md, pages/common/magick.md, pages/common/mogrify.md, pages/common/montage.md
=> compare,convert,identify,import,magick,mogrify,montage: update page

.github/CODEOWNERS
Message (for @reinhart1010): after this PR is merged, you will be requested a review automatically on PRs when Indonesian pages are added/modified. This is optional if you don't want to be requested a review by default, feel free to close this PR.
=> CODEOWNERS: add @reinhart1010 for Indonesian pages

pages.id/windows/cd.md
add the 'go to root' description, reorder the translation according to the English version, update some translation details to obey the translation guideline
=> windows/cd: update Indonesian translation

pages.id/windows/date.md
=> windows/date: add Indonesian translation

pages.pl/common/php.md
=> php: update Polish translation

MAINTAINERS.md
=> MAINTAINERS: add @gutjuri as collaborator

pages/common/fio.md
=> fio: edit page

pages/linux/yplan.md
Closes https://github.com/tldr-pages/tldr/issues/8860
=> yplan: add page

pages.id/windows/logoff.md
=> windows/logoff: add Indonesian translation

pages/linux/systemd-ask-password.md
- Version - systemd 247 (247.3-7)
=> systemd-ask-password: add page

pages/common/cargo-run.md
=> cargo-run: add page

pages/osx/dtrace.md
=> dtrace: add page

pages/linux/postconf.md
- **Version of the command being documented (if known): >= 2.9**
=> postconf: add page

pages.pt_BR/common/aws-s3-cp.md
=> aws-s3-cp: add pt_BR translation

pages.pt_BR/common/git-alias.md, pages.pt_BR/common/git-clone.md, pages.pt_BR/common/git-config.md
=> git-alias, git-clone, git-config: add pt_BR translation

pages/linux/pkgctl-build.md, pages/linux/pkgctl-db-update.md, pages/linux/pkgctl-release.md, pages/linux/pkgctl-version.md, pages/linux/pkgctl.md
=> pkgctl: update page; pkgctl-{build,db-update,release}: add page; pkgctl-version: remove page

pages.fr/common/bun.md
- **Version of the command being documented (if known):** v1.0.2
=> bun: add French translation

pages.fr/common/gem.md
I chose not to translate `gem` into `gemme` (french) and keep it as a non-translatable noun.
=> gem: add French translation

pages.fr/common/jq.md, pages/common/jq.md
=> jq: add French translation, update page

pages.fr/common/hashcat.md
=> hashcat: add French translation

pages.fr/common/gulp.md, pages/common/gulp.md
```
$ gulp --version
CLI version: 2.3.0
Local version: 4.0.2
```
=> gulp: add French translation, update page

pages.fr/common/crystal.md, pages/common/crystal.md
- **Version of the command being documented (if known):** 1.9.2
=> crystal: add French translation, update page

pages.fr/common/john.md
=> john: add French translation

contributing-guides/translation-templates/alias-pages.md, contributing-guides/translation-templates/common-arguments.md, contributing-guides/translation-templates/subcommand-mention.md, pages.cs/common/cd.md, pages.cs/windows/cd.md
I would like to start helping with translation into my native language - Czech. From reading docs I didn't understand if starting a new language is possible just like that, or if something more has to be done. Please point me out to right direction, if I did something wrong.
=> cd, translation-templates/*: add Czech translation

.github/ISSUE_TEMPLATE/page-modification-request.yml, .github/ISSUE_TEMPLATE/page-request.yml
=> ISSUE-TEMPLATES: add page modification request template; update page request template

pages/linux/lz.md
Again a command with no options resulting in a short tldr page.
=> lz: add page

pages.fr/common/ruby.md, pages/common/ruby.md
=> ruby: add French translation, update page

pages.pt_BR/common/dvc-add.md, pages.pt_BR/common/dvc-checkout.md, pages.pt_BR/common/dvc.md
=> dvc, dvc-add, dvc-checkout: add pt_BR translation

.github/ISSUE_TEMPLATE/page-modification-request.yml
I seem to have accidentally missed it in my previous PR when adding the Issue template.
=> ISSUE-TEMPLATES: fix typo

pages/linux/pdfcrop.md
- **Version of the command being documented (if known):** 1.40
=> pdfcrop: add page

pages.de/common/php.md
=> php: add German translation

pages.es/common/az-account.md, pages.es/common/az-appconfig.md, pages.es/common/az-bicep.md, pages.es/common/az-config.md, pages.es/common/az-devops.md, pages.es/common/az-feedback.md
=> az-account, az-appconfig, az-bicep, az-config, az-devops, az-feedback: add Spanish translation

pages/common/pamfile.md
=> pamfile: add page

pages/linux/systemd-repart.md
=> systemd-repart: add page

contributing-guides/style-guide.md, pages/common/krita.md
=> krita: move to `common`, update description; style-guide: add description guidelines

pages.pl/common/exa.md, pages.pl/common/eza.md
=> exa, eza: add Polish translation

pages.id/common/docker-ps.md
=> docker-ps: add Indonesian translation

pages/linux/zforce.md
This command has no options, so its tldr page is rather short.
=> zforce: add page

pages/linux/systemd-inhibit.md
=> systemd-inhibit: add page

pages/common/anytopnm.md
=> anytopnm: add page

pages/common/kops.md
- **Version of the command being documented (if known):** `1.28.0`
=> kops: add validate example

pages/common/gladtex.md
=> gladtex: add page

pages.id/common/cd.md, pages.id/linux/man.md
=> man: add Indonesian translation; cd: update Indonesian translation

pages/linux/shnsplit.md, pages/linux/shntool-split.md
=> shnsplit: add page; shntool-split: add alias page

pages/common/zeisstopnm.md
=> zeisstopnm: add page

pages/common/git-guilt.md
=> git-guilt: add page

pages/common/hd.md
- **Version of the command being documented (if known):** 2.37.2
=> hd: add alias page

pages.nl/common/alias.md
=> alias: fix typo in Dutch translation

pages/common/k9s.md
- **Version of the command being documented (if known):** `0.27.4`
=> k9s: add page

pages.fr/common/rubocop.md
=> rubocop: add French translation

pages/linux/ico.md
- **Version of the command being documented (if known):** 1.0.5
=> ico: add page

pages/linux/kernel-install.md
=> kernel-install: add page

pages/linux/machinectl.md
=> machinectl: add page

pages/common/az-apim.md
=> az-apim: add page

pages/linux/nitch.md
=> nitch: add page

pages/common/az-account.md, pages/common/az-appconfig.md, pages/common/az-login.md, pages/common/az-upgrade.md, pages/common/az-version.md
Signed-off-by: GitHub <noreply@github.com>
Ref. https://github.com/tldr-pages/tldr/pull/10915#issuecomment-1756665832
=> az-*: update page description

pages/common/scala-cli.md
- **Version of the command being documented (if known):** `1.0.4`
=> scala-cli: add page

pages.pt_BR/common/!.md, pages.pt_BR/common/aapt.md, pages.pt_BR/common/acme.sh.md
=> !, aapt, acme.sh: add pt_BR pages

pages.pt_BR/common/du.md, pages.pt_BR/common/dua.md, pages.pt_BR/common/duc.md
=> du, dua, duc: add pt_BR pages

pages.pt_BR/common/aws-ses.md, pages.pt_BR/common/aws-sqs.md, pages.pt_BR/common/aws-sts.md
=> aws-ses, aws-sqs, aws-sts: add pt_BR pages

pages/linux/systemd-cgls.md
=> systemd-cgls: add page

pages/linux/systemd-cgtop.md
=> systemd-cgtop: add page

pages.ko/common/java.md
=> java: add Korean translation

pages.pl/common/composer.md, pages/common/composer.md
=> composer: add Polish translation, update page

pages.pt_BR/common/nvim.md, pages.pt_BR/common/passwd.md, pages.pt_BR/common/rsync.md, pages.pt_BR/common/tldr.md, pages.pt_BR/linux/rmdir.md
=> nvim, passwd, rsync, rmdir, tldr: add pt_BR translation

pages/common/aks.md, pages/common/az-aks.md
=> az-aks: add page

pages.de/common/gcloud.md
=> gcloud: add German translation

pages.uk/linux/dpkg-reconfigure.md
=> dpkg-reconfigure: add Ukrainian translation

pages/common/git-fresh-branch.md
=> git-fresh-branch: add page

pages/common/az-storage.md
=> az-storage: update to long options

pages/common/ppmhist.md
=> ppmhist: add page

pages/linux/gzexe.md
This command has only one option, so the tldr page is rather short.
=> gzexe: add page

pages/common/aws-s3-rb.md
This PR addresses https://github.com/tldr-pages/tldr/issues/8406
=> aws-s3-rb: add page

pages.hi/linux/bluetoothctl.md
=> bluetoothctl: add Hindi translation

pages.pt_BR/common/bash.md, pages.pt_BR/common/calc.md, pages.pt_BR/common/cat.md, pages.pt_BR/common/cd.md, pages.pt_BR/common/code.md, pages.pt_BR/common/cp.md, pages.pt_BR/common/date.md, pages.pt_BR/common/docker-build.md, pages.pt_BR/common/docker-image.md, pages.pt_BR/common/echo.md, pages.pt_BR/common/g++.md, pages.pt_BR/common/gpg.md, pages.pt_BR/common/gzip.md, pages.pt_BR/common/htop.md, pages.pt_BR/common/java.md, pages.pt_BR/common/ls.md, pages.pt_BR/common/man.md, pages.pt_BR/common/nano.md, pages.pt_BR/common/pip3.md, pages.pt_BR/common/python.md, pages.pt_BR/common/touch.md, pages.pt_BR/common/uname.md, pages.pt_BR/common/zsh.md
=> common/*: update pt_BR translation

pages/common/neotoppm.md
=> neotoppm: add page

pages/common/git-pull-request.md
=> git-pull-request: add page

pages.pt_BR/linux/cat.md, pages.pt_BR/linux/daemon.md, pages.pt_BR/linux/dconf-read.md, pages.pt_BR/linux/dconf-reset.md, pages.pt_BR/linux/dconf-write.md, pages.pt_BR/linux/dconf.md, pages.pt_BR/linux/gsettings.md, pages.pt_BR/linux/locale.md, pages.pt_BR/linux/lscpu.md, pages.pt_BR/linux/man.md, pages.pt_BR/linux/mkfs.ext4.md, pages.pt_BR/linux/mkfs.fat.md, pages.pt_BR/linux/mkfs.md, pages.pt_BR/linux/pacman-mirrors.md, pages.pt_BR/linux/poweroff.md, pages.pt_BR/linux/pwd.md, pages.pt_BR/linux/rename.md, pages.pt_BR/linux/rm.md, pages.pt_BR/linux/sed.md, pages.pt_BR/linux/systemctl.md
=> linux/*: add pt_BR translation

pages/common/git-paste.md
=> git-paste: add page

pages/common/git-delete-squashed-branches.md
=> git-delete-squashed-branches: add page

pages/common/gitui.md
=> gitui: add page

scripts/set-more-info-link.py
=> scripts/set-more-info-link.py: add Czech translation

pages/common/git-rscp.md
=> git-rscp: add page

pages/common/git-rebase-patch.md
=> git-rebase-patch: add page

pages/common/git-psykorebase.md
=> git-psykorebase: add page

pages/windows/wget.md
=> wget: fix typo

pages.nl/windows/wget.md
=> wget: update Dutch translation

pages.nl/common/cd.md, pages.nl/windows/cd.md
=> cd: update Dutch translation

pages.zh_TW/windows/systeminfo.md
=> systeminfo: add traditional Chinese translation

pages/common/azure-cli.md
Edit. Nice #11000th Issue/PR 😎
=> azure-cli: add alias page

pages.id/osx/xcodes-runtimes.md, pages.id/osx/xcodes.md
=> xcodes, xcodes-runtimes: add Indonesian translation

pages.id/common/[[.md
Improves the existing `[` command page and add `[[`.
=> [, [[: add and improve Indonesian translation

pages.ko/common/yarn-why.md, pages.ko/common/yarn.md
=> yarn, yarn-why: add Korean translation

contributing-guides/translation-templates/common-arguments.md
=> common-arguments: update Dutch translation

pages/windows/certutil.md
=> certutil: add page

pages.nl/windows/dir.md
=> dir: update Dutch translation

pages.nl/common/chmod.md
=> chmod: update Dutch translation

pages.ko/linux/systemctl.md
=> systemctl: add Korean Translation

pages.nl/common/cargo.md
=> cargo: update Dutch translation

pages/common/bmptopnm.md
=> bmptopnm: add page

pages.zh_TW/windows/winget.md
=> winget: update traditional Chinese translation

pages/common/dotnet-add-package.md, pages/common/dotnet-add-reference.md
- **Version of the command being documented (if known):** since .NET 3.1
=> dotnet-add-{package, reference}: add page

pages/windows/bcdboot.md
=> bcdboot: add page

pages/common/ddgr.md
=> ddgr: add page

pages.ko/common/sed.md
=> sed: add Korean translation

pages.ko/common/prettier.md
=> prettier: add Korean translation

MAINTAINERS.md
Closes https://github.com/tldr-pages/tldr/issues/11075
=> MAINTAINERS: add @sebastiaanspeck to collaborators

.github/CODEOWNERS
Closes https://github.com/tldr-pages/tldr/issues/11075
=> CODEOWNERS: add @sebastiaanspeck to codeowners

pages.de/common/httpie.md
=> httpie: add German translation

pages/common/asciitopgm.md
Umbrella issue #10887
This PR adds asciitopgm page documentation
=> asciitopgm: add page

pages.ko/common/tcpdump.md
=> tcpdump: add Korean translation

pages.hi/windows/ipconfig.md
=> ipconfig: add Hindi translation

pages/common/pnmtopng.md
=> pnmtopng: add page

pages/common/jpegtopnm.md
=> jpegtopnm: Add page

pages.pl/linux/abbr.md
=> abbr: add Polish translation

pages.pl/linux/ac.md
=> ac: add Polish translation

pages/common/pgmtopgm.md
=> pgmtopgm: add page

pages/common/soxi.md
=> soxi: add page

pages/common/kubectl-label.md
=> kubectl label: add page

pages.de/common/zoxide.md
=> zoxide: add German translation

pages/common/packer.md
=> packer: add fmt example

contributing-guides/translation-templates/alias-pages.md
=> alias-pages: add Bengali translation

pages/common/ppmtopgm.md
=> ppmtopgm: add page

pages/common/kubectl-replace.md
=> kubectl replace: add page

pages.pt_BR/common/coffee.md
=> coffee: add pt_BR translation

pages.pt_BR/common/afconvert.md
=> afconvert: add pt_BR translation

pages/common/kubectl-taint.md
=> kubectl-taint: add page

contributing-guides/translation-templates/alias-pages.md
=> alias-pages: add Serbian translation

pages.es/osx/du.md
=> du: add Spanish translation

pages.ko/common/wget.md
=> wget: add Korean translation

pages/linux/pstoedit.md
=> pstoedit: add page

pages/common/kubectl-scale.md
=> kubectl-scale: add page

pages/common/docker-container-rename.md, pages/common/docker-rename.md
=> docker-rename: add page; docker-container-rename: add alias page

pages/common/docker-container-remove.md, pages/common/docker-container-rm.md, pages/common/docker-rm.md
=> docker-rm: add page; docker-container-{remove, rm}: add alias pages

pages.hi/android/cmd.md, pages.pt_BR/common/fastboot.md
=> cmd, fastboot: update links

pages/common/docker-container-diff.md, pages/common/docker-diff.md
=> docker-diff: add page

pages.pt_BR/common/cut.md
=> cut: add pt_BR translation

pages.ko/linux/add-apt-repository.md
=> add-apt-repository: add Korean translation

pages.de/common/kitty.md
=> kitty: add German translation

pages.de/common/k6.md
=> k6: add German translation

pages.de/common/omz.md
=> omz: add German translation

MAINTAINERS.md
Add @Magrid0 to the collaborators list.
Closes #11159
=> MAINTAINERS: add @Magrid0 as collaborator

.github/CODEOWNERS
Add @Magrid0 to the IT codeowner.
=> CODEOWNERS: add @Magrid0 for Italian files

pages/osx/xctool.md
=> xctool: update link

pages.es/osx/xed.md
=> xed: add Spanish translation

pages.es/osx/xctool.md
=> xctool: add Spanish translation

contributing-guides/translation-templates/alias-pages.md
=> alias-pages: add Uzbek translation

pages/windows/remove-appxpackage.md
=> remove-appxpackage: add page

pages.es/osx/xcodes-runtimes.md
=> xcodes-runtimes: add Spanish translation

pages/common/telegram-desktop.md
- **Version of the command being documented (if known): 4.10.3**
=> telegram-desktop: add page

pages.pl/linux/alien.md
=> alien: add Polish translation

pages.pl/linux/apk.md, pages.pl/linux/aplay.md
=> aplay, apk: add Polish translation

pages.pl/linux/ahost.md
=> ahost: add Polish translation

pages/common/perl.md
=> perl: update page

pages.pl/linux/adig.md
=> adig: add Polish translation

pages/linux/pw-play.md
=> pw-play: update page

pages.es/osx/vpnd.md
=> vpnd: add Spanish translation

MAINTAINERS.md
=> MAINTAINERS: add @gutjuri as org member

pages.es/osx/wc.md
=> wc: add Spanish translation

pages.es/osx/universalaccessd.md
=> universalaccessd: add Spanish translation

pages/linux/portablectl.md
=> portablectl: add page

pages/common/gh-screensaver.md
=> gh-screensaver: add the `life` screensaver

pages/windows/slmgr.md, pages/windows/slmgr.vbs.md
=> slmgr, slmgr.vbs: update link

pages/windows/bcdboot.md
- **Version of the command being documented (if known):** Windows 11 (10.0.22621.1702)
This PR adds command mnemonics, use imperative mood for command description, and remove the locale from the More Information link.
=> bcdboot: add mnemonics and imperative mood

pages.hi/android/bugreportz.md
=> bugreportz: add Hindi translation

pages.ko/linux/esbuild.md
=> esbuild: add Korean translation

pages.hi/android/am.md
=> am: add Hindi translation

.github/CODEOWNERS
Hindi is my third language and I can preliminarily read and write in it. I am adding myself to the CODEOWNERS file to review these PRs by default for structural issues (which might slip through other maintainers who can't read Hindi) and occasionally fix them.
=> CODEOWNERS: add @kbdharun for Hindi

pages.hi/linux/apache2ctl.md
=> apache2ctl: add Hindi translation

pages.hi/linux/adduser.md
=> adduser: add Hindi translation

pages/common/tar.md
=> tar: explain [a] flag more clearly

pages.hi/windows/bcdboot.md
=> bcdmode: add Hindi translation

pages.nl/windows/cd.md, pages.nl/windows/rd.md, pages.nl/windows/remove-item.md, pages.nl/windows/rmdir.md, pages.nl/windows/set-location.md
=> windows/*: add, update PowerShell commands and aliases for Dutch translation

pages.pl/linux/aptitude.md, pages/linux/aptitude.md
Adds backticks and applies my suggestion from https://github.com/tldr-pages/tldr/pull/11294#discussion_r1373780855
=> aptitude: update page and Polish translation

pages.id/osx/xcodes-runtimes.md, pages/osx/xcodes-runtimes.md
This PR adds three new examples to `xcodes runtimes` as well as its Indonesian translation.
=> xcodes-runtimes: add new examples

pages.hi/windows/diskpart.md
=> diskpart: add Hindi translation

pages.hi/windows/title.md
=> title: add Hindi translation

pages.fr/windows/choco-info.md
=> choco-info: fix typo in French translation

contributing-guides/translation-templates/common-arguments.md, contributing-guides/translation-templates/subcommand-mention.md
=> translation-templates/*: add Bengali translation

pages.es/osx/sed.md
=> sed: add Spanish translation

pages/common/imgtoppm.md
=> imgtoppm: add-page

pages.ko/common/gitmoji.md
=> gitmoji: add Korean translation

pages/common/accelerate.md
=> accelerate: add page

pages/common/cargo-pkgid.md, pages/common/cargo-tree.md, pages/common/cargo-vendor.md, pages/common/cargo-verify-project.md
=> cargo-*: add page

pages.ko/common/jar.md
=> jar: add Korean translation

pages.ko/common/javadoc.md
=> javadoc: add Korean translation

pages.de/linux/aa-complain.md
=> aa-complain: add German translation

pages.es/osx/machine.md
=> machine: add Spanish translation

pages.es/osx/mas.md
=> mas: add Spanish translation

pages/common/linode-cli-volumes.md
=> linode-cli-volumes: fix typo

pages/common/linode-cli.md
=> linode-cli: fix typo

README.md
- Update the Homebrew client from the C client to the Rust client (`tlrc`).
- Minor fixes to the Installation section.
I have already updated [the Wiki](https://github.com/tldr-pages/tldr/wiki) for the same.
=> README: update Homebrew client to Rust client `tlrc`

pages.es/osx/ps.md
=> ps: add Spanish translation

pages.ko/common/accelerate.md
=> accelerate: add Korean translation

pages.ko/common/argocd-app.md, pages.ko/common/argocd.md
=> argocd, argocd-app: add Korean translation

pages/common/eyuvtoppm.md, pages/common/ppmtoeyuv.md, pages/common/ppmtoyuv.md, pages/common/ppmtoyuvsplit.md, pages/common/yuvsplittoppm.md, pages/common/yuvtoppm.md
=> eyuvtoppm, ppmtoeyuv, ppmtoyuv, ppmtoyufsplitm, yuvsplittoppm, yuvtoppm: add pages

pages.ko/common/apktool.md
=> apktool: add Korean translation

pages/common/brew-list.md, pages/common/brew-outdated.md, pages/common/brew-search.md, pages/common/brew-update.md, pages/common/brew-upgrade.md
=> brew-{update,upgrade,list,outdated,search}: add page

pages/linux/systemd-nspawn.md
Moved from #11358. I made some additional fixes and tweaks.
=> systemd-nspawn: add page

pages/linux/wl-copy.md
- **Version of the command being documented (if known):** wl-copy
=> wl-copy: add image copying example

pages/common/pamtoqoi.md, pages/common/pbmtozinc.md, pages/common/ppmtoarbtxt.md, pages/common/qoitopam.md, pages/common/rawtopgm.md, pages/common/rawtoppm.md
=> pamtoqoi, pbmtozinc, ppmtoarbtxt, qoitopam, rawtopgm, rawtoppm: add pages

pages/common/gemtopbm.md, pages/common/gemtopnm.md, pages/common/pamtotga.md, pages/common/ppmtotga.md, pages/common/tgatoppm.md
=> gemtopbm, gemtopnm, pamtotga, ppmtotga, tgatoppm: add pages

pages.ko/android/bugreportz.md
=> bugreportz: add Korean translation

pages/common/pamtoxvmini.md, pages/common/pbmtoybm.md, pages/common/pnmtoxwd.md, pages/common/xvminitoppm.md, pages/common/xwdtopnm.md, pages/common/ybmtopbm.md
=> pamtoxvmini, pbmtoybm, pnmtoxwd, xvminitoppm, xwdtopnm, ybmtopbm: add pages

pages/common/pbmtolj.md, pages/common/pjtoppm.md, pages/common/pnmtopclxl.md, pages/common/ppmtolj.md, pages/common/ppmtopj.md, pages/common/ppmtospu.md, pages/common/sldtoppm.md, pages/common/spctoppm.md, pages/common/sputoppm.md, pages/common/thinkjettopbm.md
=> pbmtolj, pjtoppm, pnmtopclxl, ppmtolj, ppmtopj, ppmtospu, sldtoppm, spctoppm, sputoppm, thinkjettopbm: add pages

pages.nl/common/amass-intel.md
=> amass-intel: add Dutch translation

pages.nl/common/amass-enum.md
=> amass-enum: add Dutch translation

pages.nl/common/amass.md
=> amass: add Dutch translation

pages.nl/common/amass-db.md
=> amass-db: add Dutch translation

pages.pl/common/azure-cli.md, pages.pl/common/docker-container-diff.md, pages.pl/common/docker-container-remove.md, pages.pl/common/docker-container-rename.md, pages.pl/common/docker-container-rm.md, pages.pl/common/docker-container-top.md, pages.pl/common/git-stage.md, pages.pl/common/hd.md, pages.pl/common/hping.md
=> pages.pl/*: add links

pages.de/common/!.md
=> !: fix typo in German translation

pages/common/unp.md
=> unp: add page

pages/common/ps-nvm.md
=> ps-nvm: fix typo

pages/common/ilbmtoppm.md, pages/common/pcxtoppm.md, pages/common/ppmtoilbm.md, pages/common/ppmtoleaf.md, pages/common/ppmtomitsu.md, pages/common/ppmtompeg.md, pages/common/ppmtoneo.md, pages/common/ppmtopcx.md
=> ilbmtoppm, pcxtoppm, ppmtoilbm, ppmtoleaf, ppmtomitsu, ppmtompeg, ppmtoneo, ppmtopcx: add pages

pages/common/pamoil.md, pages/common/pgmbentley.md, pages/common/pgmdeshadow.md, pages/common/pgmoil.md, pages/common/ppmrainbow.md, pages/common/ppmrelief.md, pages/common/ppmshadow.md, pages/common/ppmshift.md, pages/common/ppmspread.md, pages/common/ppmtoacad.md, pages/common/ppmtobmp.md, pages/common/ppmtoicr.md
=> pamoil, pgmbentley, pgmdeshadow, pgmoil, ppmrainbow, ppmrelief, ppmshadow, ppmshift, ppmspread, ppmtoacad, ppmtobmp, ppmtoicr: add pages

pages.ko/android/dalvikvm.md
=> dalvikvm: add Korean translation

pages.nl/linux/apport-bug.md, pages.nl/linux/cal.md, pages.nl/linux/cgcreate.md, pages.nl/linux/cgexec.md, pages.nl/linux/ip-route-show.md, pages.nl/linux/megatools-dl.md, pages.nl/linux/update-alternatives.md
=> linux/*: add Dutch translation

pages.ko/android/dumpsys.md
=> dumpsys: add Korean translation

pages.nl/common/anki.md
=> anki: add Dutch translation

pages.nl/common/ani-cli.md
=> ani-cli: add Dutch translation

pages.nl/common/androguard.md
=> androguard: add Dutch translation

pages/linux/rlogin.md
=> rlogin: add page

pages/linux/rsh.md
=> rsh: add page

pages/linux/dnsdomainname.md
=> dnsdomainname: add page

pages.id/common/adb-install.md, pages.id/common/adb-logcat.md
This PR adds the following:
+ **adb install:** Use standard `{{jalan/menuju/file_atau_direktori}}` placeholder convention, add new subcommands
+ **adb logcat:** Add Indonesian translation
=> adb-logcat: add Indonesian translation; adb-install: update Indonesian translation

pages.id/common/cd.md, pages.id/windows/cd.md, pages.id/windows/set-location.md, pages.id/windows/sl.md
This command improves the Indonesian translation of `common/cd`, `windows/cd`, and `Set-Location` as well as their aliases:
+ **cd (Common):** Use imperative mood (#8576, #10858)
+ **cd (Windows):**
- Use imperative mood (#8576, #10858)
- Add PowerShell alias notice
- Reorganize examples to be similar to common version
- Use backslashes on `{{path\to\file_or_directory}}` placeholder convention
+ **Set-Location:** Add translation including `sl` as an alias
=> cd: update Indonesian translation; set-location: add Indonesian translation

pages.zh/common/deno.md
=> deno: add Chinese translation

pages.id/windows/set-location.md
=> set-location: fix tldr-lint issue

pages.id/netbsd/pkgin.md
=> pkgin: fix more info link

pages/linux/libtool.md
=> libtool: add page

pages.nl/common/ansible.md
=> ansible: add Dutch translation

pages/linux/kdesrc-build.md, pages/linux/kdesrc-run.md
=> kdesrc-build, kdesrc-run: add page

pages.ko/android/input.md
=> input: add Korean translation

pages.es/osx/pod.md
=> pod: add Spanish translation

pages.ko/android/logcat.md
=> logcat: add Korean translation

pages/common/a2ping.md
=> a2ping: fix typo

pages.ko/android/screencap.md, pages.ko/android/settings.md, pages.ko/android/wm.md
=> screencap, settings, wm: add Korean translation

pages.fr/common/anki.md, pages.fr/common/anytopnm.md, pages.fr/common/argocd.md
=> anki, anytopnm, argocd: add French translation

pages/common/tldr.md
=> tldr: update page

pages.ko/common/anytopnm.md
=> anytopnm: add Korean translation

pages.ko/common/bb.md
=> bb: add Korean translation

pages.pl/common/tldr.md
=> tldr: update Polish translation

pages/linux/lvextend.md
- **Version of the command being documented (if known):** `lvextend`
=> lvextend: fix typo, update link

pages.es/osx/mysides.md
=> mysides: add Spanish translation

.github/CODEOWNERS, MAINTAINERS.md
=> MAINTAINERS, CODEOWNERS: remove @marchersimon from Org

pages.fr/common/docker-pull.md, pages.fr/common/docker-rename.md, pages.fr/common/docker-rm.md
=> docker-{pull,rename,rm}: add French translation

pages.ja/common/case.md
Use recommended More information translation (https://github.com/tldr-pages/tldr/blob/778555a1fb8e55b014161d64385d0f0a15994c41/scripts/set-more-info-link.py#L27)
=> case: update Japanese translation

pages.ko/common/django-admin.md, pages/common/django-admin.md
=> django-admin: update link

pages.es/osx/scutil.md
=> scutil: add Spanish translation

pages.es/osx/systemsoundserverd.md
=> systemsoundserverd: add Spanish translation

pages.nl/common/fossil-add.md, pages.nl/common/fossil-commit.md, pages.nl/common/fossil-init.md, pages.nl/common/fossil-rm.md, pages.nl/common/fossil.md, pages/common/fossil-rm.md
=> fossil-*: add Dutch translation

pages.zh/common/ffsend.md
=> ffsend: add Chinese translation

pages/common/docker-image.md, pages/common/f3fix.md, pages/common/f3probe.md, pages/common/f3read.md, pages/common/f3write.md, pages/common/nvim.md, pages/common/podman-image.md, pages/common/vim.md, pages/common/vimdiff.md, pages/common/vimtutor.md, pages/linux/lrunzip.md, pages/linux/lrzip.md, pages/linux/openrc.md, pages/linux/vgscan.md
=> pages/*: align "See also:" lines

pages/common/ncu.md
=> ncu: add use cases, use long options

pages.ko/common/asciitopgm.md
=> asciitopgm: add Korean translation

pages.es/osx/say.md
=> say: add Spanish translation

pages.zh/common/fish.md
=> fish: add Chinese translation

pages.es/osx/airportd.md
=> airportd: add Spanish translation

pages.es/osx/automountd.md
=> automountd: add Spanish translation

pages.es/osx/avbdeviced.md
=> avbdeviced: add Spanish translation

pages.es/osx/backupd.md
=> backupd: add Spanish translation

pages/linux/chatgpt.md
=> chatgpt: add page

pages.es/osx/arch.md, pages.pt_BR/osx/arch.md, pages.pt_PT/osx/arch.md, pages.zh/osx/arch.md, pages/osx/arch.md
=> arch: add Spanish translation

pages.es/common/dotnet-publish.md
=> dotnet-publish: fix typo

pages/common/vboxmanage-clonevm.md, pages/common/vboxmanage-export.md, pages/common/vboxmanage-import.md, pages/common/vboxmanage-unregistervm.md, pages/linux/exiqgrep.md
=> vboxmanage-*, exiqgrep: update page

pages.es/common/dotnet-restore.md
=> dotnet-restore: fix typos in Spanish translation

pages.es/common/docker.md
=> docker: fix typos in Spanish translation

pages.es/common/cpdf.md
=> cpdf: update Spanish translation

pages.id/osx/getfileinfo.md, pages.id/osx/goku.md, pages.id/osx/w.md, pages.id/osx/xip.md
=> getfileinfo, goku, w, xip: add Indonesian translation

pages/common/clang++.md, pages/common/clang.md, pages/common/g++.md, pages/common/gcc.md
=> clang, clang++, gcc, g++: edit page

.github/CODEOWNERS
Adding myself to CODEOWNERS to get automatic review requests for some stuff.
=> CODEOWNERS: add @sbrl, @sebastiaanspeck and @kbdharun for specific directories

pages.nl/common/env.md
=> env: add Dutch translation

pages/common/aws-s3.md
=> aws-s3: add subcommand mention

pages.ko/common/agate.md
=> agate: add Korean translation

pages.ko/common/acyclic.md
=> acyclic: add Korean translation

pages.nl/common/ps-nvm.md
=> ps-nvm: update Dutch translation

pages/common/xteddy.md
Adding the most important page 🧸
=> xteddy: add page

pages.es/common/git-mv.md
=> git-mv: fix typo in Spanish translation

pages.es/common/git-checkout.md
=> git-checkout: fix typos in Spanish translation

pages.es/common/git-pull.md
=> git-pull: fix typos in Spanish translation

pages.es/common/git-reset.md
=> git-reset: update Spanish translation

pages.de/windows/ipconfig.md
=> ipconfig: add German translation

pages.es/common/tree.md
=> tree: fix typo in Spanish translation

pages.es/common/yes.md
=> yes: fix typos in Spanish translation

pages.es/common/nest.md
=> nest: fix typo in Spanish translation

pages/common/gcloud-components-install.md, pages/common/gcloud-config-set.md
=> gcloud-{components-install, config-set}: add pages

pages/common/gcloud-logging-logs-list.md, pages/common/gcloud-sql-export-sql.md
Thanks to @danielsagie for creating this page (this PR fixes the previous PRs with failing CLA).
=> gcloud-{logging-logs-list, sql-export-sql}: add page

pages.nl/common/clj.md
=> clj: add Dutch translation

pages.nl/common/ykman-config.md, pages.nl/common/ykman-fido.md, pages.nl/common/ykman-oath.md, pages.nl/common/ykman-openpgp.md, pages.nl/common/ykman.md
=> ykman*: add Dutch translation

pages.es/linux/man.md
=> man: update Spanish translation

pages.es/linux/raspinfo.md
=> raspinfo: fix Spanish typo

pages.es/linux/yum.md
=> yum: translate placeholders to Spanish

pages.es/osx/as.md
=> as: fix Spanish syntax issue

pages.es/linux/xdg-open.md
=> xdg-open: minor fix in Spanish translation

pages.ko/common/androguard.md
=> androguard: add Korean translation

pages.es/common/helm-install.md
=> helm-install: fix typo in Spanish translation

pages/common/gcloud-sql-backups-describe.md
=> gcloud-sql-backups-describe: add page

pages.nl/common/get-nodeversions.md
=> get-nodeversions: add Dutch translation

pages.ko/common/atuin.md
=> atuin: add Korean translation
